erigontech/erigon

cmd/caplin/main.go
cmd/devnet/devnet/node.go
cmd/erigon/main.go
cmd/silkworm_api/snapshot_idx.go
diagnostics/setup.go
turbo/app/backup_cmd.go
turbo/app/import_cmd.go
turbo/app/init_cmd.go
turbo/app/snapshots_cmd.go
turbo/app/support_cmd.go
turbo/debug/flags.go

fixed start diag server

---

cmd/downloader/main.go
cmd/integration/main.go
cmd/rpcdaemon/main.go

Cherry pick PR #10215 into the release

downloader: --seedbox doesn't init snaptypes

---

cmd/utils/flags.go

Fix typo in externalcl flag

---

node/node.go

e3: set dirty-space for chaindb to 512mb

---

erigon-lib/diagnostics/entities.go
erigon-lib/diagnostics/snapshots.go
erigon-lib/diagnostics/snapshots_test.go
erigon-lib/downloader/downloader.go

Added diagnostics collection for file downloaded statistics (time took and average download speed)

added snapshot files downloaded stats

---

erigon-lib/state/inverted_index.go

- fix anti-pruning during pruning (loading into rwtx)
- make History prune ordered, less random access - less spill-unspill pages

fix inverted index pruning

---

p2p/server.go

remove nils from p2p logs

---

core/state/rw_v3.go

it's the same code for the 3 cases changing only the domain, so the code can be safely simplified

Remove code duplication

---

cmd/diag/stages/stages.go

Updated stages command to use table print output:

diagnostics: up diag stage comand

---

cl/spectest/Makefile

See https://github.com/git-lfs/git-lfs/issues/5749

fix Consensus specification tests CI

---

cl/spectest/Makefile

Cherry-pick: https://github.com/ledgerwatch/erigon/commit/bc5fa6f156778125ff7aea20161ef550efb754cd
Need this to get PR CI green for v2.60.1 patches, e.g. - https://github.com/ledgerwatch/erigon/pull/10390

fix Consensus specification tests CI (#10391)

---

core/rawdb/accessors_metadata.go
eth/backend.go
turbo/stages/stageloop.go

This test causes hive tests to fail and now 11 more tests pass

Fixed faulty unwind on memory mutation

---

cmd/rpcdaemon/health/check_time.go

Fix TestProcessHealthcheckIfNeeded_HeadersTests

---

cl/beacon/handler/blocks.go
cl/beacon/handler/builder.go
cl/beacon/handler/committees.go
cl/beacon/handler/duties_attester.go
cl/beacon/handler/duties_proposer.go
cl/beacon/handler/duties_sync.go
cl/beacon/handler/headers.go
cl/beacon/handler/rewards.go
cl/beacon/handler/states.go
cl/beacon/handler/validators.go
cl/phase1/execution_client/execution_client_direct.go
cl/phase1/execution_client/execution_client_rpc.go
cl/phase1/execution_client/execution_engine_mock.go
cl/phase1/execution_client/interface.go
cl/phase1/execution_client/types.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/interface.go
cl/phase1/forkchoice/mock_services/forkchoice_mock.go
cl/phase1/forkchoice/on_block.go
cl/phase1/forkchoice/optimistic/optimistic.go
cl/phase1/forkchoice/optimistic/optimistic_impl.go
cl/phase1/forkchoice/optimistic/optimistic_test.go

https://github.com/ethereum/consensus-specs/blob/dev/sync/optimistic.md
- Optimistic store manages op status
- API

Optimistic execution

---

cmd/evm/internal/t8ntool/execution.go
cmd/evm/internal/t8ntool/gen_stenv.go
cmd/evm/internal/t8ntool/transition.go
cmd/state/exec3/trace_worker2.go
consensus/clique/verifier.go
consensus/errors.go
consensus/ethash/consensus.go
consensus/merge/merge.go
core/types/block.go
core/types/gen_header_json.go
eth/protocols/eth/protocol.go
eth/stagedsync/exec3.go
p2p/sentry/sentry_multi_client/sentry_multi_client.go
polygon/bor/bor.go
tests/block_test_util.go
tests/gen_btheader.go
turbo/adapter/ethapi/api.go
turbo/execution/eth1/eth1_utils/grpc.go
turbo/execution/eth1/getters.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go

Add some [EIP-7685](https://eips.ethereum.org/EIPS/eip-7685) bits missed by PR #10238

Add some missing EIP-7685 wirings

---

core/rawdb/rawdbreset/reset_stages.go
erigon-lib/txpool/pool.go
eth/stagedsync/exec3.go
eth/stagedsync/stage_mining_create_block.go
eth/stagedsync/stage_mining_exec.go
turbo/engineapi/engine_helpers/fork_validator.go
turbo/execution/eth1/forkchoice.go

* Unwind issue: This happened only in `ForkValidator`, we shared the `SharedDomains` both for unwinds and execution. now setting them to nil and letting 2 different domains getting created fixed the issue
* Block Production issue: Needed to increase the difference allowed to report to txPool.

Fix almost all hive tests for E3

---

turbo/execution/eth1/forkchoice.go

closes https://github.com/ledgerwatch/erigon/issues/10445

fix #10445

---

turbo/adapter/ethapi/api.go

Cherry pick PR #10451 into the release branch

fix gas price not right problem

---

turbo/stages/stageloop.go

Hot-Fix for E3 unwind

---

turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_call.go
turbo/jsonrpc/eth_call_test.go

Copy PR #10495 into the release branch

eth_estimateGas: default feeCap to base fee

---

cmd/utils/flags.go
migrations/prohibit_new_downloads2.go
polygon/bor/snaptype/types.go
turbo/snapshotsync/freezeblocks/bor_snapshots.go

Cherry pick PR #10281 into the release branch

Add flag for bor waypoint types

---

turbo/jsonrpc/tracing.go

Cherry pick PR #10401 into the release branch

try to fix 'method handler crashed' for debug_traceCall of #9090

---

cmd/utils/flags.go
diagnostics/setup.go
erigon-lib/diagnostics/client.go
erigon-lib/diagnostics/speedtest.go

Cherry pick PR #10449 into the release branch

diagnostics: cherry pick speedtest disable

---

params/bootnodes.go

Cherry pick PR #10460 into the release branch

Enable DNS p2p discovery on holesky

---

.github/workflows/qa-clean-exit-block-downloading.yml
.github/workflows/qa-clean-exit-snapshot-downloading.yml
.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch.yml
.github/workflows/qa-tip-tracking.yml

- fix upload artifact name
- rename jobs for monitoring
- change some schedule

qa-tests: small fixes

---

turbo/snapshotsync/freezeblocks/bor_snapshots.go

for: https://github.com/ledgerwatch/erigon/issues/10485

e3: remove overlapped files only after merge save

---

core/rawdb/accessors_chain.go
core/rawdb/blockio/block_writer.go
eth/stagedsync/stage_bor_heimdall.go
polygon/bor/bordb/prune.go
polygon/bor/snaptype/types.go

Cherry pick PR #10468 into the release branch

add flag checking for pruning waypoints

---

erigon-lib/state/domain.go
erigon-lib/state/domain_test.go

touches https://github.com/ledgerwatch/erigon/issues/10317

do not remove state files bigger than `maximin(domainsTxNum)`

---

polygon/bor/finality/whitelist/milestone.go
polygon/bor/finality/whitelist/service_test.go

Cherry pick PR #10493 into the release branch

add lock to purgeMilestoneIDsList

---

erigon-lib/diagnostics/snapshots.go
erigon-lib/diagnostics/stages.go
erigon-lib/diagnostics/sys_info.go

Fixed https://github.com/ledgerwatch/erigon/issues/10490

diagnostics: fix 10409

---

eth/stagedsync/stage_polygon_sync.go

Running with the new polygon sync stage on Amoy hits an execution error:
```
EROR[05-27|20:29:48.771] Staged Sync                              err="[4/6 Execution] ExecV3: nil block 6400000"
```
The error is a result of `ReadCanonicalHash` in execution returning `nil`.
This PR fixes that by using `fixCanonicalChain` which updates the canonical hash for each block height in a backward path (for loop using ParentHash) from the current fork choice update tip height+hash until it reaches a canonical hash that has been already set previously.

stagedsync: polygon sync stage fix canonical hash

---

erigon-lib/kv/kv_interface.go
erigon-lib/kv/tables.go
eth/stagedsync/bor_heimdall_shared.go
node/node.go
polygon/bor/bor.go
polygon/bridge/bridge.go
polygon/bridge/db.go
polygon/bridge/log_prefix.go
polygon/bridge/service.go
polygon/heimdall/entity_store.go
polygon/heimdall/event_record.go
polygon/heimdall/service.go
polygon/polygoncommon/database.go

This PR contains the implementation of the bridge component
- gets all events from Heimdall and persists in MDBX
- create map from block number to event IDs during block download
PRs to follow:
- initialisation of bridge
- integration with execution
- optimisation of map storage and background rlp encode/decode

polygon/sync: Bridge implementation

---

turbo/app/README.md
turbo/app/support_cmd.go

- removed unused tis config as diagnostics switched to websocket
- updated support command documentation

removed unused var, updated docs

---

eth/stagedsync/exec3.go

Allows to prune already snapshotted data in not-yet committed tx, reducing costs of further flush/commit

prune tx if something available

---

erigon-lib/state/history.go

So i got `buildVI: nil decompressor passed` error then found that corrupted files are not closed and removed from `dirtyFiles` -> coming into list for `BuildMissingIdx` then crashes.
I suppose rather than log Corrupted file into debug, we can remove them and associated indices. Otherwise those files will persist on disk and will be touched each time aggregator open files. 
so maybe instruct user to remove files and remove `prohibit_new_downloads.lock` to re-download bad corrupted file, rather than keep them on disk

buildVI: nil decompressor passed fix

---

eth/ethutils/receipt.go

Cherry pick PR #10551 into the release branch

blobGasPrice should be marshalled as hex

---

cmd/prometheus/dashboards/erigon.json

grafana: add consumer delay row to "simple" board

---

cl/sentinel/service/service.go

Cherry pick PR #10546 into the release branch

Caplin: Fixed reforwarding of Bls Execution changes

---

cl/beacon/beaconhttp/args.go
cl/beacon/handler/blobs.go

Cherry pick PR #10576 into the release branch

Caplin: Update BlobSidecars Beacon API endpoint to the latest specs

---

core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/blockio/block_writer.go
eth/stagedsync/stage_snapshots.go
turbo/app/snapshots_cmd.go
turbo/services/interfaces.go
turbo/snapshotsync/freezeblocks/block_snapshots.go

Trying to implement #10461 solution, still not final version, review and tests required

don't prune if not needed implementation (1st attempt)

---

cmd/evm/staterunner.go
core/state/database_test.go
tests/state_test.go
tests/state_test_util.go

closes https://github.com/ledgerwatch/erigon/issues/10349

root evaluation with e3 primitives

---

erigon-lib/txpool/pool.go
erigon-lib/txpool/pool_test.go

txpool: EIP-3860 should only apply to create transactions

---

.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch.yml
.github/workflows/qa-tip-tracking.yml

Fix results uploading with a correct env var expansion

qa-tests: fix results uploading

---

erigon-lib/state/domain_committed.go
erigon-lib/state/domain_shared.go
eth/stagedsync/exec3.go

move file lock inside SD.ComputeCommitment to prevent un-decodable commit branch during merge

---

core/rawdb/accessors_chain.go
core/state/rw_v3.go
erigon-lib/config3/config3.go
erigon-lib/kv/tables.go
erigon-lib/state/domain.go
erigon-lib/state/domain_shared.go
erigon-lib/state/domain_shared_test.go
erigon-lib/state/state_changeset.go
erigon-lib/state/state_changeset_test.go
eth/stagedsync/exec3.go
eth/stagedsync/stage_execute.go
turbo/execution/eth1/forkchoice.go

Now we store them on MDBX as chunks

E3: Store Diffs in MDBX

---

erigon-lib/diagnostics/provider.go
erigon-lib/diagnostics/provider_test.go
turbo/snapshotsync/snapshotsync.go

Removed "RegisterProvider" and test for it as it doesn't use in code at all. It closes #9379

fixed race

---

cl/antiquary/beacon_states_collector.go
cl/antiquary/state_antiquary.go
erigon-lib/etl/buffers.go
erigon-lib/etl/collector.go

collector.Collect does copy of `k` and `v` with any buffer type

cl: etl collector does copy under the hood

---

core/rawdb/accessors_chain.go

change from: 
```
Status of ChangeSets3
Pagesize: 8192
Tree depth: 3
Branch pages: 10
Leaf pages: 903
Overflow pages: 195596
Entries: 99586
```
to 
```
Status of ChangeSets3
Pagesize: 8192
Tree depth: 2
Branch pages: 1
Leaf pages: 99
Overflow pages: 7579
Entries: 7957
```

stateDiff: 1 overflow page per entry 

---

p2p/discover/v4_udp.go

This is a fix for: 
https://github.com/ledgerwatch/erigon/issues/10192
This fixes is a deadlock in v4_udp.go where 
* Thread A waits on mutex.Lock() in resetTimeout() called after reading listUpdate channel.
* Thread B waits on listUpdate <- plist.PushBack(p) called after locking mutex.Lock()
This fix decouples the list operations which need locking from the channel operations which don't by storing the changes in local variables.    These updates are used for resetting a timeout - which is not order dependent.

Fix potential p2p shutdown hangup

---

polygon/heimdall/checkpoint.go
polygon/heimdall/entity.go
polygon/heimdall/entity_fetcher.go
polygon/heimdall/milestone.go
polygon/heimdall/span.go

Fixes panic encountered when trying to sync on Amoy using `polygon.sync`. Implements the same checkpoint ID solution as `batchFetchCheckpoints`.

polygon/heimdall: Fix checkpoint ID

---

erigon-lib/state/inverted_index_test.go

e3: Fix one test

---

cmd/diag/downloader/diag_downloader.go
cmd/diag/stages/stages.go
diagnostics/snapshot_sync.go
erigon-lib/diagnostics/client.go
erigon-lib/diagnostics/entities.go
erigon-lib/diagnostics/snapshots.go
erigon-lib/diagnostics/stages.go
erigon-lib/diagnostics/stages_test.go
erigon-lib/diagnostics/utils.go

- Added progress and time stats for stages.
- Display progress and time stats for snapshot downloading and header chain stages.
- Moved sync stages overview info to root of diagnostics client.
- Added separate endpoint to query sync stages.
- Optimize stages command code.

diagnostics: stages stats

---

cmd/rpcdaemon/cli/httpcfg/http_cfg.go
turbo/cli/flags.go
turbo/engineapi/engine_server.go
turbo/jsonrpc/corner_cases_support_test.go
turbo/jsonrpc/daemon.go
turbo/jsonrpc/debug_api_test.go
turbo/jsonrpc/erigon_receipts_test.go
turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_api_test.go
turbo/jsonrpc/eth_block_test.go
turbo/jsonrpc/eth_callMany_test.go
turbo/jsonrpc/eth_call_test.go
turbo/jsonrpc/eth_filters_test.go
turbo/jsonrpc/eth_mining_test.go
turbo/jsonrpc/eth_system_test.go
turbo/jsonrpc/send_transaction.go
turbo/jsonrpc/send_transaction_test.go

Cherry pick PR https://github.com/ledgerwatch/erigon/pull/10636 to Erigon 2

rpc: Fix incorrect txfeecap

---

erigon-lib/common/dir/rw_dir.go

for https://github.com/ledgerwatch/erigon/issues/10644

skip hidden files when list files with given extension 

---

erigon-lib/diagnostics/snapshots.go

fixed spelling, added more details print for not found substage

diagnostics: smfix

---

erigon-lib/kv/mdbx/kv_mdbx.go

tx.get instead of cursor primitives

---

.github/workflows/ci.yml
.github/workflows/test-integration.yml

up macos to 14

---

cmd/utils/flags.go

Cherry pick https://github.com/ledgerwatch/erigon/issues/10792

Downloader: fix staticpeers flag

---

turbo/engineapi/engine_server.go

Cherry pick PR #10093 into the release branch

Fix NewPayload Validation during header download

---

erigon-lib/common/dir/rw_dir.go

skip hidden files when list files with given extension

---

erigon-lib/state/aggregator.go
erigon-lib/state/domain.go
erigon-lib/state/inverted_index.go

Got this situation on Amoy network when nothing to prune but `PruneSmallBatches` still looped

add pruneNothing checker and fix endless pruning on Amoy

---

erigon-lib/downloader/downloader.go

releasing parts of https://github.com/ledgerwatch/erigon/pull/10715/files

dl: WebseedActiveTrips counters

---

core/vm/runtime/runtime_test.go

changed TestCall to E3 primitives

---

cl/phase1/forkchoice/on_block.go

Caplin: Demote annoying log

---

eth/stagedsync/stage_mining_exec.go
turbo/stages/stageloop.go

Reverts ledgerwatch/erigon#10862

Revert "try don't use membatch in mining"

---

erigon-lib/kv/mdbx/kv_mdbx.go

union streams and cursors

---

erigon-lib/state/aggregator.go
eth/stagedsync/sync.go

We do not have commitment history anymore, so i need to re-adapt the unwind functions to reflect that

E3: Added automatic bounded unwind

---

erigon-lib/downloader/snaptype/files.go
erigon-lib/state/bps_tree.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go

almost everything printed on openSnapshots but
+ caplin stats
+ downloader lock file stat

`erigon snapshots stats` command to print status of snapshots

---

erigon-lib/state/appendable.go
erigon-lib/state/domain.go
erigon-lib/state/files_item.go
erigon-lib/state/history.go
erigon-lib/state/inverted_index.go

- use `src` pointer
- allow nil `src` for simplify unit-tests

simplify close ctx 

---

accounts/abi/bind/bind_test.go
cmd/downloader/main.go
erigon-lib/common/datadir/dirs.go
erigon-lib/common/dir/rw_dir.go
erigon-lib/downloader/downloader.go
erigon-lib/downloader/downloadercfg/downloadercfg.go
erigon-lib/downloader/snaptype/files.go
erigon-lib/downloader/snaptype/type.go
erigon-lib/downloader/torrent_files.go
erigon-lib/downloader/util.go
erigon-lib/kv/mdbx/kv_mdbx.go
erigon-lib/state/aggregator.go
erigon-lib/state/appendable.go
erigon-lib/state/domain.go
erigon-lib/state/existence_filter.go
erigon-lib/state/history.go
erigon-lib/state/inverted_index.go
erigon-lib/state/merge.go
eth/stagedsync/stage_snapshots.go
migrations/prohibit_new_downloads2.go
migrations/prohibit_new_downloads_lock.go
turbo/app/backup_cmd.go
turbo/snapshotsync/freezeblocks/block_snapshots.go

changed FileExists declaration

---

tests/exec_spec_test.go

tests: Undo skip EIP-7685 spec tests

---

polygon/bor/bor.go
polygon/bridge/bridge.go
polygon/bridge/bridge_test.go
polygon/bridge/db.go

Supersedes #10973
Fixes #10970

polygon: Fix type mismatch during check

---

cmd/rpcdaemon/cli/config.go
cmd/state/commands/opcode_tracer.go
cmd/state/exec3/historical_trace_worker.go
cmd/state/exec3/state.go
cmd/state/exec3/state_recon.go
consensus/aura/aura.go
consensus/aura/aura_test.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/merge/merge.go
consensus/misc/eip4788.go
core/blockchain.go
core/chain_makers.go
polygon/bor/bor.go
turbo/jsonrpc/trace_filtering.go

- This PR is created to from the https://github.com/ledgerwatch/erigon/pull/10757 to simplify it's review and merge process.
- In this PR, we have plugged tracing hook framework to the consensus engine.

feat: tracing hooks added to consensus engine

---

eth/backend.go
polygon/bor/bor.go

Supersedes #10990
Fixes #10989

polygon: Fix interface nil check

---

erigon-lib/downloader/downloader.go

for https://github.com/ledgerwatch/erigon/issues/10993
probably need write it into separated log file

dl: remove too verbose non-greppable logs

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Should Fix:
https://github.com/ledgerwatch/erigon/issues/10972
https://github.com/ledgerwatch/erigon/issues/10991
https://github.com/ledgerwatch/erigon/issues/10995
https://github.com/ledgerwatch/erigon/issues/10996

Fixes for torrent connection races and panic

---

erigon-lib/diagnostics/snapshots.go

Diagnostics: loglevel

---

erigon-lib/downloader/downloader.go

cherry-pick of https://github.com/ledgerwatch/erigon/pull/10853

dl: additional pre-check for having info 

---

erigon-lib/state/aggregator.go

First sync was failed due to unwind to current head being thought impossible by the `node`

E3: Use domain state instead of math.MaxUint64 in CanUnwind

---

erigon-lib/diagnostics/client.go
erigon-lib/diagnostics/snapshots.go
erigon-lib/diagnostics/stages.go
erigon-lib/diagnostics/sys_info.go
erigon-lib/diagnostics/utils.go
erigon-lib/diagnostics/utils_test.go

fix - https://github.com/ledgerwatch/erigon/issues/11035

Diagnostics: fix unreasonable warns on start

---

.github/workflows/qa-sync-from-scratch-minimal-node.yml

Add sync-from-scratch test for "--prune=minimal" mode.

qa-tests: add sync-from-scratch for minimal node

---

erigon-lib/diagnostics/client.go
erigon-lib/diagnostics/entities.go
erigon-lib/diagnostics/snapshots.go
erigon-lib/diagnostics/stages.go
erigon-lib/diagnostics/sys_info.go

Changes from PR https://github.com/ledgerwatch/erigon/pull/11016

Diagnostics: cherrypick from 2.60.3

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Should fix:
https://github.com/ledgerwatch/erigon/issues/11040
https://github.com/ledgerwatch/erigon/issues/11041
https://github.com/ledgerwatch/erigon/issues/11042

Fix torrent connection sync issues

---

.github/workflows/qa-tip-tracking-gnosis.yml

This add a Tip-Tracking test on Erigon v2 for Gnosis chain/network

qa-tests: add Tip-Tracking test for Gnosis

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

pick up optimizations in [v1.3.0](https://github.com/holiman/uint256/releases/tag/v1.3.0)

go.mod: update uint256

---

core/state/state_object.go
eth/tracers/logger/logger.go

Benchmarks here https://go-review.googlesource.com/c/go/+/471400
Inspired by https://github.com/ethereum/go-ethereum/pull/29365

core/eth: use maps.Clone

---

cmd/integration/commands/flags.go
cmd/integration/commands/refetence_db.go
cmd/integration/commands/reset_state.go
cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_domains.go
cmd/integration/commands/state_stages.go

closes #11019 but not sure is this enough

added flag to integration

---

cmd/rpctest/getBlockByNumber.json
cmd/rpctest/getLogs.json
erigon-lib/downloader/mdbx_piece_completion.go
turbo/snapshotsync/freezeblocks/block_reader.go
turbo/snapshotsync/freezeblocks/block_snapshots.go

for: https://github.com/ledgerwatch/erigon/issues/11090
thank you [tholcman](https://github.com/tholcman) for finding

rpc bottleneck: block files mutex (e3)

---

p2p/discover/table.go

for https://github.com/ledgerwatch/erigon/issues/11158

discovery table: revalidate race fix

---

cl/beacon/handler/handler.go
cl/beacon/handler/validators.go

Caplin: Added POST `Validators` 

---

tests/solidity/test/opCodes.js

[test] remove unused variables

---

erigon-lib/diagnostics/entities.go
erigon-lib/diagnostics/snapshots.go
erigon-lib/diagnostics/snapshots_indexing.go
erigon-lib/diagnostics/snapshots_test.go
turbo/snapshotsync/freezeblocks/block_snapshots.go

- refactored snapshot indexing
- covered with tests

diagnostics: refactor snapshot indexing

---

consensus/clique/snapshot.go

More of https://github.com/erigontech/erigon/pull/11079

consensus: use slices/maps.Clone

---

turbo/adapter/ethapi/api.go
turbo/adapter/ethapi/state_overrides.go

cherry pick of https://github.com/erigontech/erigon/pull/10531

compatibility with geth - of stateDiff encoding 

---

.github/workflows/ci.yml
.github/workflows/docker-tags.yml
.github/workflows/hive-nightly.yml
.github/workflows/test-erigon-is-library.yml
.github/workflows/test-integration-caplin.yml
.github/workflows/test-integration.yml

Will remove warnings like this in the CI logs
https://github.com/erigontech/erigon/actions/runs/10122481375

upgrade actions to latest

---

docs/programmers_guide/dupsort.md

doc: fix KV path in DupSort

---

eth/tracers/native/call.go

for https://github.com/erigontech/erigon/issues/11257

callTracer: dont capture logs txs failed with error

---

polygon/bridge/bridge.go
polygon/bridge/db.go

polygon/bridge: Fix bridge crash at chain tip

---

eth/tracers/native/call.go

for https://github.com/erigontech/erigon/issues/11257

callTracer: don't capture logs txs failed with error

---

polygon/bridge/bridge.go
polygon/bridge/bridge_test.go

Sync events time limit was not following Indore rules
Fixes #11325

polygon/bridge: Set correct time limit

---

cmd/integration/commands/stages.go
eth/backend.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_bor_heimdall.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stage_senders_test.go
eth/stagedsync/stagedsynctest/harness.go
turbo/stages/mock/mock_sentry.go
turbo/stages/stageloop.go

- we have loopBreaker in stage_headers - probably it's enough 
- rely on stage_headers progress. keep stages aligned

stage_bor_heimdall: remove loopBreaker 

---

cl/abstract/beacon_state.go
cl/abstract/mock_services/beacon_state_reader_mock.go
cl/beacon/handler/utils_test.go
cl/beacon/handler/validator_registration.go
cl/monitor/interface.go
cl/monitor/metrics.go
cl/monitor/mock_services/validator_monitor_mock.go
cl/monitor/validator.go
cmd/caplin/caplin1/run.go

part of https://github.com/erigontech/erigon/issues/11147

monitor block proposer hit/miss count

---

erigon-lib/diagnostics/client.go
erigon-lib/diagnostics/entities.go
erigon-lib/diagnostics/sys_info.go

- get all available data re CPU

diagnostics: updated cpu info 

---

erigon-lib/diagnostics/entities.go
erigon-lib/diagnostics/sys_info.go
erigon-lib/diagnostics/utils_test.go

- Added additional fields for RAM info
- Fixed bug with free RAM

diagnostics: ram info update

---

erigon-lib/commitment/commitment.go

Do not sort BranchData after commitment - we waste it because writes comes down to `SharedDomain` where they are etl'ed. 
Touches #11326

`commitment`: do not sort trie branch updates

---

cmd/utils/flags.go
erigon-lib/chain/snapcfg/util.go
eth/backend.go

Write file snapshots/preverified.toml
Read from it as the new oracle

E3: Better backward compatibility for evergreen (fixes headerdownload case)

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Pick up https://github.com/erigontech/erigon-snapshot/pull/236,  https://github.com/erigontech/erigon-snapshot/pull/239, https://github.com/erigontech/erigon-snapshot/pull/238, https://github.com/erigontech/erigon-snapshot/pull/240, https://github.com/erigontech/erigon-snapshot/pull/241, https://github.com/erigontech/erigon-snapshot/pull/242,  https://github.com/erigontech/erigon-snapshot/pull/243, https://github.com/erigontech/erigon-snapshot/pull/244, and https://github.com/erigontech/erigon-snapshot/pull/245.

Pick up latest snapshots

---

polygon/bor/bor.go
polygon/bridge/bridge.go
polygon/bridge/db.go

polygon/bridge: Use `atomic`

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go
eth/gasprice/feehistory_test.go
eth/gasprice/gasprice_test.go
eth/protocols/eth/handlers.go
eth/stagedsync/stage_bodies_test.go
p2p/sentry/sentry_multi_client/sentry_multi_client.go
turbo/jsonrpc/erigon_receipts.go
turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_call.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_system.go
turbo/jsonrpc/graphql_api.go
turbo/jsonrpc/otterscan_api.go
turbo/jsonrpc/otterscan_block_details.go
turbo/jsonrpc/otterscan_search_trace.go
turbo/jsonrpc/overlay_api.go
turbo/jsonrpc/receipts/receipts_generator.go
turbo/stages/blockchain_test.go
turbo/stages/mock/mock_sentry.go

use it in `SimulatedBackend` and `TestFeeHistory`

Add receipts generator to `mock` 

---

eth/protocols/eth/handler_test.go

added receipts assertion

---

cmd/diag/sysinfo/sysinfo.go
cmd/diag/util/util.go

- Added CPU overall info to report file
Example output:

diagnostics: updated sys info to include CPU stats

---

erigon-lib/commitment/commitment.go
erigon-lib/commitment/commitment_bench_test.go
erigon-lib/commitment/commitment_test.go
erigon-lib/commitment/hex_patricia_hashed.go
erigon-lib/commitment/hex_patricia_hashed_bench_test.go
erigon-lib/commitment/hex_patricia_hashed_fuzz_test.go
erigon-lib/commitment/hex_patricia_hashed_test.go
erigon-lib/commitment/patricia_state_mock_test.go
erigon-lib/state/domain_shared.go

Make Cell unexported
Remove ProcessTree/Keys/Update
Reviewed and refreshed all unit/bench/fuzz tests related to commitment
#11326

Commitment code cleanup

---

cmd/diag/downloader/diag_downloader.go
cmd/diag/stages/stages.go
cmd/diag/util/util.go

Refactored table utils to have an option to generate table and return it as string which will used for saving data to file.

diagnostics: refactored table utils

---

turbo/app/snapshots_cmd.go

Main checks:
* No gap in steps/blocks
* Check if all indexing present
* Check if all idx,  history, domain present

Erigon: Added verification for whether snapshots are publishable or not and added clearIndexing command

---

cmd/diag/sysinfo/sysinfo.go

- added flags which was applied to run command to report

diagnostics: added flags to report

---

cmd/diag/sysinfo/sysinfo.go
cmd/diag/util/util.go

- Added CPU overall info to report file Example output:
51](https://github.com/user-attachments/assets/834c3f48-ec37-48ea-8688-ee6ea00186a4)

diagnostics: updated sys info to include CPU stats (#11497)

---

cl/beacon/beaconevents/model.go
cl/beacon/beaconevents/state_feed.go
cl/beacon/handler/block_production.go
cl/beacon/handler/events.go
cl/monitor/interface.go
cl/monitor/mock_services/validator_monitor_mock.go
cl/monitor/validator.go
cl/phase1/forkchoice/fork_choice_test.go
cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/forkchoice/fork_graph/fork_graph_test.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/on_block.go
cl/phase1/network/services/block_service.go
cl/phase1/network/services/block_service_test.go
cl/phase1/stages/chain_tip_sync.go
cl/phase1/stages/forkchoice.go
cl/spectest/consensus_tests/fork_choice.go
cmd/caplin/caplin1/run.go

part of https://github.com/erigontech/erigon/issues/11149
All events are supported now

more cl state events

---

cl/spectest/Makefile

cherry-pick 391fc4b94c6f110bad11246f3e5a7ba948a0087e for E2
needed to unblock PR https://github.com/erigontech/erigon/pull/11551

don't use lfs for consensus spec tests (#11545)

---

cmd/diag/sysinfo/sysinfo.go

- added flags which was applied to run command to report

diagnostics: added flags to report (#11548)

---

cmd/txpool/readme.md

FIx txpool readme

---

cmd/state/exec3/trace_worker.go
core/vm/analysis_test.go
core/vm/contract.go
core/vm/evm.go
core/vm/evm_test.go
core/vm/instructions_test.go
core/vm/mock_vm.go
eth/stagedsync/exec3.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_mining_exec.go
eth/tracers/js/tracer_test.go
eth/tracers/logger/logger_test.go
turbo/jsonrpc/erigon_receipts.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/otterscan_generic_tracer.go
turbo/jsonrpc/otterscan_search_v3.go

it's not thread-safe
also made `JumpDestCache` env-configurable - for experiments

exec: use dedicated worker for mining

---

cl/beacon/handler/validators.go

Fix https://github.com/erigontech/erigon/issues/11414 
root cause: empty validator set

Fix panic in caplin api get validator (#11419)

---

erigon-lib/recsplit/index.go
erigon-lib/state/btree_index.go
erigon-lib/state/files_item.go

I also added a more readable err when panicking on incomplete file. hopefully, it will not scare users.

Cleanup torrents of indexing files

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

I did an oopsie and switched erigon to a test branch on erigon-snapshot

Bump up erigon-snapshots

---

cl/antiquary/state_antiquary.go
cl/persistence/state/historical_states_reader/historical_states_reader.go

related to https://github.com/erigontech/erigon/issues/11482

fix panic issue in initializeStateAntiquaryIfNeeded

---

polygon/sync/sync.go

addresses follow ups from https://github.com/erigontech/erigon/pull/11568#discussion_r1713613404

polygon/sync: naming follow up

---

diagnostics/setup.go

Fixed issue with setup diagnostics client on erigon start

diagnostics: fix setup

---

diagnostics/setup.go

Fixed issue with setup diagnostics client on erigon start

diagnostics: fix setup (#11633)

---

.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch-minimal-node.yml
.github/workflows/qa-sync-from-scratch.yml
.github/workflows/qa-tip-tracking.yml

Save erigon logs into test zip attachment

qa-tests: save erigon logs for future inspections

---

erigon-lib/seg/compress.go
erigon-lib/seg/parallel_compress.go

- increasing compress ratio by 10%

comp: DictionaryBuilder - separate soft/hard limits

---

core/state_transition.go
core/vm/evmtypes/evmtypes.go
eth/tracers/native/prestate.go

Add blob fee to prestate tracer (#11650)

---

erigon-lib/state/domain.go
erigon-lib/state/domain_committed.go
erigon-lib/state/domain_test.go
erigon-lib/state/inverted_index.go
erigon-lib/state/inverted_index_test.go

for: https://github.com/erigontech/erigon/issues/11690

fix race in recalcVisible

---

erigon-lib/state/cache.go

we faced problem because of: https://github.com/erigontech/erigon/pull/11691

flag to disable domain lru 

---

eth/stagedsync/stage_polygon_sync.go
polygon/bridge/bridge.go
polygon/bridge/db.go
polygon/bridge/reader.go

Switches bridge to store last event IDs.
Fixes #11673

polygon/bridge: Remove reader duplication

---

diagnostics/sysinfo.go
turbo/app/support_cmd.go

- Added functionality to grab the heap profile by calling the diagnostics endpoint
- Added support to pass heap profile file to diagnostics UI through WebSocket

diagnostics: added func to grab heap profile (#11643)

---

cmd/diag/ui/ui.go
diagnostics/block_body_download_stats.go
diagnostics/bodies_info.go
diagnostics/bootnodes.go
diagnostics/cmd_line.go
diagnostics/db.go
diagnostics/flags.go
diagnostics/header_downloader_stats.go
diagnostics/headers.go
diagnostics/logs.go
diagnostics/mem.go
diagnostics/nodeinfo.go
diagnostics/peers.go
diagnostics/setup.go
diagnostics/snapshot_sync.go
diagnostics/sysinfo.go
diagnostics/version.go

- Changed UI serving port to 5137 as 6060 is busy with diag API
- Refactored request headers to be set in middleware

diagnostics: updated serving ui port

---

erigon-lib/state/aggregator_test.go

reduce stepSize in test 

---

turbo/snapshotsync/freezeblocks/block_reader.go

turbo: optimize HeaderByNumber and BlockByNumber

---

.github/workflows/release.yml

Minor changes:
- remove run-name
- add input parameter publish_latest_tag
- remove obsolete debug outputs
- do not create git tag.

Minor changes in release workflow

---

erigon-lib/downloader/downloader_grpc_server.go

- Fixed total time calculating and displaying

downloader: fixed total time

---

erigon-lib/downloader/webseed.go

- faster resolution of absent buckets/hosts/etc...

dl: check if webseed exists by `HEAD` request with small deadline

---

erigon-lib/commitment/hex_patricia_hashed.go

Follow-up on:
https://github.com/erigontech/erigon/pull/11804

Clear cell arrays using clear()

---

core/vm/evm.go
erigon-lib/chain/chain_config.go
params/protocol_params.go
polygon/bor/borcfg/bor_config.go

[Polygon] Bor: [PIP-30: increased max code size limit to 32KB](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-30.md)

[Polygon] Bor: PIP-30: increased max code size limit to 32KB

---

polygon/heimdall/service.go

fixing typo in previous PR https://github.com/erigontech/erigon/pull/11808

polygon/heimdall: fix errors.Is typo for ErrNotInMilestoneList

---

eth/stagedsync/sync.go
turbo/execution/eth1/forkchoice.go

Basically when state progress > block progress, we try to unwind below state progress and it does not work

Fixed sepolia sync

---

polygon/heimdall/client.go
polygon/heimdall/entity_fetcher.go
polygon/heimdall/scraper.go
polygon/heimdall/scrapper_test.go
polygon/heimdall/service.go

fixes https://github.com/erigontech/erigon/issues/11826

polygon/heimdall: make scrapper resilient to 502s

---

cl/sentinel/gossip.go
cl/sentinel/libp2p_settings.go
cl/sentinel/sentinel.go

need more peers to publish gossip msgs

adjustments to caplin peer count

---

cl/spectest/consensus_tests/epoch_processing.go
cl/transition/impl/eth2/statechange/process_epoch_test.go
cmd/devnet/scenarios/suite.go
cmd/integration/commands/stages.go
migrations/migrations.go
polygon/p2p/fetcher_base_test.go
polygon/p2p/fetcher_tracking_test.go
polygon/p2p/message_listener_test.go
polygon/p2p/peer_tracker_test.go

Detected with `gocritic check ./...`

all: unlambda function literals

---

.github/workflows/test-kurtosis-assertoor.yml

notifications for the results of kurtosis ci runs show up on #github-actions channel (erigon team discord)

test github actions discord reporting

---

cl/persistence/blob_storage/blob_db.go

blobDb: remove right folder

---

cl/phase1/forkchoice/utils.go
cl/phase1/stages/forward_sync.go

10x less memory allocs during forward sync

Caplin: Fixed bad performance on low-end consumer hardware

---

eth/stagedsync/bor_heimdall_shared.go
polygon/bridge/bridge.go
polygon/bridge/bridge_test.go

polygon/bridge: Handle overrideStateSyncRecords

---

.github/workflows/qa-tip-tracking-polygon.yml

Add tip-tracking test for bor-mainnet using a dedicated self-hosted runner

qa-tests: add Tip-Tracking test for Polygon

---

cmd/devnet/services/polygon/heimdall.go
cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go
polygon/bor/bor_test.go
polygon/heimdall/client.go
polygon/heimdall/client_mock.go
polygon/heimdall/entity_fetcher.go
polygon/heimdall/entity_fetcher_test.go
polygon/heimdall/scraper.go
polygon/heimdall/scraper_test.go
polygon/heimdall/service.go
polygon/heimdall/service_test.go
polygon/heimdall/span.go

polygon: Batch fetch spans

---

.github/workflows/ci-cd-main-branch-docker-images.yml

Fix on-trigger (correct branch)
Grammar fixes

Fix on-trigger (correct branch)

---

.github/workflows/ci-cd-main-branch-docker-images.yml

Following the request -- use short commit id instead of full one.

---

eth/calltracer/calltracer.go

As the value for each to address is not used, keep the same logic for `froms` and `tos`,

feat(eth/calltracer): the captured to address's value is not used

---

README.md
docs/mining.md

Raised on Discord: https://discord.com/channels/687972960811745322/1001501454076477450/1280972456722694327

Update README on block production

---

cl/beacon/handler/block_production.go
cl/beacon/synced_data/synced_data.go
cl/phase1/forkchoice/on_block.go
cl/phase1/network/gossip_manager.go
cl/phase1/network/services/attestation_service.go
cl/validator/attestation_producer/attestation_producer.go
cl/validator/committee_subscription/committee_subscription.go

- memory usage improvement
- fix `invalid target block` error

caplin memory usage improvement

---

turbo/snapshotsync/freezeblocks/bor_snapshots.go

Fixes: https://github.com/erigontech/erigon/issues/11905

Fix bor event check start-up

---

turbo/rpchelper/config.go

rpchelper: limits for filters by default

---

turbo/rpchelper/config.go

cherry pick from E3 to E2 https://github.com/erigontech/erigon/commit/d7d9ded0ea3f5f887206f6c7f5e976eb58405154

rpchelper: limits for filters by default (#11911)

---

.github/workflows/ci.yml
.github/workflows/qa-sync-from-scratch-minimal-node.yml
.github/workflows/test-erigon-is-library.yml
.github/workflows/test-integration-caplin.yml
.github/workflows/test-integration.yml
cmd/rpcdaemon/test.http
erigon-lib/go.mod
go.mod

`go1.23.1` released, means time to drop `go1.21` support

drop `go1.21` 

---

docs/programmers_guide/witness_formal_spec.md

HI there, I found that the old testcase is deleted in the repo now. So here is my advice
1 used the old link with commit hash
2 delete the link
Im using the first solution now.

docs: update the test action path

---

diagnostics/profile.go
diagnostics/setup.go
diagnostics/sysinfo.go

Extended pprof read API to include: goroutine, threadcreate, heap, allocs, block, mutex

diagnostics: all pprofs (#11891)

---

.github/workflows/ci-cd-main-branch-docker-images.yml
.github/workflows/release.yml

https://github.com/erigontech/erigon/issues/11898

Upgrade goreleaser-cross to 1.22.7 and alpine base image to 3.20.3

---

.github/workflows/release.yml

Upgrade goreleaser-cross to 1.22.7 and alpine base image version to 3.20.3

Upgrade goreleaser-cross to 1.22.7 and alpine base image version to 3.20.3

---

eth/stagedsync/stage_mining_exec.go

- bug found by Mario/Pari from EF.
- needs to be cp'ed into docker_pectra branch

modify EIP-3607 to accept tx type 4

---

turbo/snapshotsync/freezeblocks/block_snapshots.go

avoid panic when closing segmentsRotx

---

turbo/snapshotsync/freezeblocks/block_reader.go

fixes: https://github.com/erigontech/erigon/pull/11557#issuecomment-2343855764
this surfaced when running astrid

polygon/bor: fix panic in BorRoSnapshots checkpoint funcs when waypoint snapshots disabled

---

erigon-lib/kv/kv_interface.go
erigon-lib/state/aggregator.go
eth/stagedsync/exec3.go

chain-tip: stop PruneSmallBatches if `tx.SpaceDirty() > 64mb`

---

cl/beacon/builder/client.go
cl/beacon/handler/block_production.go
cl/cltypes/aggregate.go
cl/phase1/network/services/block_service.go
cl/transition/impl/eth2/validation.go
cl/utils/bytes.go
cl/validator/committee_subscription/committee_subscription.go

- Wrong aggregated signature
- improve attestation selection

caplin: Wrong attestations included by block proposer

---

cl/phase1/stages/forkchoice.go

We do not need a copy here, and we cannot know the next suggested fee recipient so setting this to 0.
`GetExpectedWithdrawals` works the same regardless.
Also everything else needed (randao mix and proposer index) are predetermined

Caplin: Reduced memory usage when emiting next payload attributes

---

cl/phase1/network/gossip_manager.go
cl/phase1/network/services/aggregate_and_proof_service.go
cl/phase1/network/services/batch_signature_verification.go
cl/phase1/network/services/constants.go
cl/sentinel/handlers/heartbeats.go

Fixed DDOS on AggregateAndProof

---

core/state/plain_readonly.go

PR #11959  is fine for the latest state, but not for historical access

Refine PR 11959

---

cl/beacon/handler/pool.go
cl/cltypes/aggregate.go
cl/phase1/network/gossip_manager.go
cl/phase1/network/services/aggregate_and_proof_service.go
cl/phase1/network/services/attestation_service.go
cl/phase1/network/services/batch_signature_verification.go

current proposed block https://holesky.beaconcha.in/slot/2543846#attestations
- Need to immediately process signature verification for those from http call (post attestation / post aggregation and proof)
- Separately process signatures from the attestation service and the aggregateAndProof service.

caplin: improvement in signature verification flow

---

consensus/misc/eip1559.go
eth/gasprice/feehistory.go
eth/gasprice/feehistory_test.go
turbo/jsonrpc/eth_system.go

Implemented:
https://www.quicknode.com/docs/hedera/eth_feeHistory
https://www.quicknode.com/docs/hedera/eth_baseFee
https://www.quicknode.com/docs/hedera/eth_blobBaseFee

Add support to `eth_blobBaseFee`, `eth_baseFee` and EIP4844 support to `eth_feeHistory`

---

docs/programmers_guide/guide.md

Sorry, I missed updating the keyword in the last update. https://github.com/erigontech/erigon/pull/11754

guide: fix conception key word

---

cl/beacon/handler/lighthouse.go

When finding the last non-missed slot in an epoch, we can go backwards from the end, instead of walking from the front.
This is the small optimization that was discussed in #12061

Optimize findEpochRoot

---

erigon-lib/state/aggregator.go
erigon-lib/state/domain_committed.go
erigon-lib/state/domain_shared.go

state: separate 'lookupFileByItsRange'

---

turbo/jsonrpc/erigon_block.go

cherry-pick of PR #11918 on e2

erigon_getBlockByTimestamp() add check on header == null on e3 (#11918)

---

.github/workflows/test-kurtosis-assertoor.yml

- `make docker` might increase build time for few minutes, but should be fine (the whole workflow takes 1hr+)

get kurtosis assertoor tests to run on each main commit

---

eth/stagedsync/README.md

ci docker build doesn't trigger for changes inside .github folder. Making this change in order to trigger the build.

linter recommendations for stagedsync README

---

eth/stagedsync/exec3.go

prevention of strange logs due to uint underflow

---

README.md
cmd/devnet/README.md
cmd/devnet/main.go
cmd/diag/flags/flags.go
cmd/utils/flags.go
turbo/app/support_cmd.go
turbo/debug/flags.go

New default ports

---

.github/workflows/ci-cd-main-branch-docker-images.yml
.github/workflows/ci-cd-main-branch-docker-images2.yml
.github/workflows/test-kurtosis-assertoor.yml
core/vm/interpreter.go

made format change in interpreter so that `make docker` task runs (it doesn't run if the changes are only in .github/ dir)

fix checkout in kurtosis ci

---

cmd/caplin/caplin1/run.go

Caplin: Reduced BLS caching

---

turbo/app/support_cmd.go

Fixed port value after https://github.com/erigontech/erigon/pull/12102#pullrequestreview-2331154467

diagnostics: fix port

---

cl/beacon/handler/attestation_rewards.go
cl/beacon/handler/committees.go
cl/beacon/handler/duties_attester.go
cl/beacon/handler/duties_sync.go
cl/beacon/handler/lighthouse.go
cl/beacon/handler/liveness.go
cl/beacon/handler/rewards.go
cl/beacon/handler/validators.go
cl/persistence/state/historical_states_reader/historical_states_reader.go
cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/forkchoice/fork_graph/interface.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/interface.go
cl/phase1/forkchoice/mock_services/forkchoice_mock.go
cl/sentinel/handlers/blocks.go
cl/sentinel/handlers/handlers.go
cl/sentinel/handlers/light_client.go
cl/transition/impl/eth2/statechange/process_epoch.go
cl/validator/sync_contribution_pool/sync_contribution_pool.go
cmd/utils/flags.go
turbo/cli/flags.go

I found these typos annoying, while debugging (and grepping) rewards in caplin, but forgot to include them in my original PRs.

Fix english typos

---

consensus/merge/merge.go
consensus/misc/eip2935.go
core/vm/eips.go
core/vm/instructions.go
core/vm/jump_table.go
core/vm/operations_acl.go
core/vm/runtime/runtime.go
core/vm/runtime/runtime_test.go
params/protocol_params.go

EIP-2935 Historical block hashes

---

core/types/withdrawal_requests.go
turbo/engineapi/engine_types/jsonrpc.go

add withdrawalRequests to execution payload

---

core/vm/eips.go
core/vm/operations_acl.go

Update EIP-2935: Adjust gas-costs for 2935

---

core/rawdb/accessors_chain_test.go
core/types/deposit_request.go
core/types/encdec_test.go
core/types/request.go
turbo/engineapi/engine_types/jsonrpc.go

core: Rename Deposit to DepositRequest for EIP-6110

---

consensus/merge/merge.go
consensus/misc/eip7002.go
consensus/misc/eip7251.go
core/types/consolidation_request.go
core/types/encdec_test.go
core/types/request.go
core/types/withdrawal_request.go
params/protocol_params.go
tests/exec_spec_test.go
turbo/engineapi/engine_server.go
turbo/engineapi/engine_types/jsonrpc.go

Add EIP-7251 consolidation requests support

---

cl/phase1/execution_client/execution_client_rpc.go
turbo/engineapi/engine_server.go
turbo/engineapi/engine_types/jsonrpc.go
turbo/engineapi/interface.go

engineapi: Add pectra engine api changes

---

core/types/encdec_test.go
core/types/legacy_tx.go
core/types/transaction.go
core/types/transaction_test.go
rlp/decode.go

rlp: disallow trailing bytes in transactions (#10296)

---

accounts/abi/bind/backends/simulated.go
cmd/rpcdaemon/cli/config.go
consensus/aura/aura.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/ethash.go
consensus/merge/merge.go
core/evm.go
core/state_transition.go
core/vm/evmtypes/evmtypes.go
core/vm/runtime/env.go
eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/internal/tracetest/prestate_test.go
eth/tracers/tracers_test.go
polygon/bor/bor.go
polygon/bor/fee_log.go
polygon/tracer/trace_bor_state_sync_txn.go
turbo/adapter/ethapi/api.go
turbo/jsonrpc/eth_call.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/otterscan_api.go
turbo/jsonrpc/overlay_api.go
turbo/jsonrpc/trace_adhoc.go
turbo/jsonrpc/trace_adhoc_test.go
turbo/jsonrpc/trace_filtering.go
turbo/transactions/call.go
turbo/transactions/tracing.go

Move bor_fee_log from core to polygon

---

turbo/engineapi/engine_server.go

engineapi: Fix req list check

---

cmd/utils/flags.go
erigon-lib/txpool/pool.go
erigon-lib/txpool/txpoolcfg/txpoolcfg.go
erigon-lib/txpool/txpoolutil/all_components.go

Wire OverridePragueTime into txpool

---

cl/clparams/config.go

Caplin: Added electra config support

---

core/types/consolidation_request.go
core/types/deposit_request.go
core/types/withdrawal_request.go

core/types: Fix JSON (un)marshalling of request types

---

erigon-lib/chain/chain_config.go

Fix json name for deposit contract address

---

turbo/engineapi/engine_server.go

engineapi: Remove redundant nil check

---

turbo/engineapi/engine_server.go

engineapi: Send status SYNCING for fcu when busy

---

consensus/misc/eip2935.go

el-consensus: Add 2935 condition to fail silently if no code in HistoryStorageAddress

---

core/state_transition.go
crypto/crypto.go
erigon-lib/crypto/secp256k1.go
erigon-lib/txpool/pool.go
erigon-lib/txpool/pool_test.go
erigon-lib/txpool/txpool_grpc_server.go
erigon-lib/txpool/txpoolcfg/txpoolcfg.go
erigon-lib/types/txn.go
erigon-lib/types/txn_test.go

Update EIP-7702: simpler transaction validity

---

params/protocol_params.go
tests/exec_spec_test.go

Update EIP-7251 address

---

cmd/rpcdaemon/README.md

The 'Trace transactions progress' in there seems not exist

docs: remove 404 link

---

cmd/rpcdaemon/README.md

chore: delete missing part

---

erigon-lib/state/domain_shared.go

Closes https://github.com/erigontech/erigon/issues/12208

Allow `Commitment` to lookup dirty files for key dereferencing

---

cmd/evm/runner.go

Added temporal db to evm cmd

---

eth/stagedsync/stage_mining_create_block.go

We cannot increase the gas limit

Sanity check gas limit before block building

---

.github/workflows/qa-rpc-test-bisection-tool.yml

Initial version of a bisection tool based on rpc integration tests

qa-tests: add rpc test bisection tool

---

.github/workflows/ci.yml

See https://github.com/erigontech/erigon/issues/12125

Do not cancel in progress jobs in case of 'main' branch.

---

eth/tracers/js/goja.go
eth/tracers/js/tracer_test.go

backport ethereum/go-ethereum#30231

feat(eth/tracers): add coinbase to ctx

---

core/types/transaction_marshalling.go

As the MarshalJson function does not generate the gasPrice field.

Removing gasPrice check in UnmarshalJson of dynamicFeeTx

---

.github/workflows/ci.yml

See https://github.com/erigontech/erigon/issues/12125 for more details.

Do not cancel in progress jobs for 'main' and latest release branches.

---

.github/workflows/qa-rpc-test-bisection-tool.yml

- avoid cloning rpc-tests at each step
- bump rcp-tests version

qa-tests: improve rpc bisection tool 

---

.github/workflows/qa-rpc-integration-tests.yml
turbo/rpchelper/helper.go

for https://github.com/erigontech/erigon/issues/12323

e3: compatibility with e2 on future blocks rpc

---

Makefile

See https://github.com/erigontech/erigon/issues/11715

Introduce GOAMD64 variable with default=v2 for AMD64 arch.

---

turbo/snapshotsync/freezeblocks/block_snapshots.go

port of https://github.com/erigontech/erigon/pull/12362
rely on https://github.com/erigontech/erigon/pull/12373

e2: don't reopen files when new created

---

erigon-lib/chain/snapcfg/util.go
erigon-lib/go.mod
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go

`frozen: Seedable(f)` looks buggy because E3 can seed small (non-frozen) files.

seg: add IsFrozen helper

---

erigon-lib/common/dbg/experiments.go

relates to https://github.com/erigontech/erigon/issues/11387#issuecomment-2382684325

dbg: env var for heap profile output file path

---

turbo/stages/headerdownload/header_algos.go

e2 cherry-pick of https://github.com/erigontech/erigon/pull/12404

headerdownload: fix OOM due to inifinitely growing children in link

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/main.go
core/rawdb/accessors_metadata.go
eth/backend.go

cherry-pick https://github.com/erigontech/erigon/pull/12373
for https://github.com/erigontech/erigon/issues/12281

e2_60: rpcd no open before download

---

turbo/stages/bodydownload/body_algos.go

BodyDownload: differentiate between empty vs nil withdrawals/requests

---

cmd/state/commands/opcode_tracer.go
cmd/state/exec3/historical_trace_worker.go
cmd/state/exec3/state.go
cmd/state/exec3/state_recon.go
consensus/aura/aura.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/merge/merge.go
core/blockchain.go
core/chain_makers.go
core/state/txtask.go
eth/stagedsync/stage_mining_exec.go
polygon/bor/bor.go
polygon/bor/fake.go

Input requests are unused after PR #12370 & #12337

Don't pass requests to consensus Finalize

---

.github/workflows/qa-rpc-integration-tests.yml
cmd/rpcdaemon/README.md
turbo/engineapi/engine_server.go
turbo/engineapi/interface.go

See https://hackmd.io/@n0ble/deprecate-exchgTC

Remove engine_exchangeTransitionConfiguration

---

cl/antiquary/antiquary.go
cl/antiquary/tests/tests.go
cmd/caplin/caplin1/run.go

Cherry pick #12237 into `release/2.61`

Disable antiquation

---

.github/workflows/release.yml
Dockerfile.release

Cherry pick #12331 into `release/2.61`

Rework release workflow for release/2.60 branch

---

turbo/jsonrpc/tracing.go
turbo/transactions/tracing.go

Cherry pick #12364 into `release/2.61`

rpcdaemon: Add missing flag

---

erigon-lib/downloader/snaptype/type.go

Cherry pick #12394 into `release/2.61`

e2: port salt assert logic

---

ChangeLog.md

Cherry pick #12427 into `release/2.61`

Added Changelog

---

erigon-lib/go.mod
erigon-lib/go.sum

Syncing to `master` branch in `interfaces` repo and adding back missing proto updates in https://github.com/erigontech/erigon/pull/11962

lib: Update interfaces go mod

---

cl/transition/impl/eth2/operations.go
cl/transition/impl/eth2/statechange/process_registry_updates.go

fix some function names in comment

chore: fix some function names in comment

---

p2p/sentry/sentry_multi_client/sentry_multi_client.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go

Cherry pick #12426 into `release/2.61`

Remove remnants of requests from block body downloader

---

core/state_transition.go
core/types/authorization.go
erigon-lib/common/fixedgas/protocol.go
tests/exec_spec_test.go

Cherry pick #12416 into `release/2.61`

Modify EIP-7702 Txn impl per pectra-devnet-4 specs

---

erigon-lib/chain/snapcfg/util.go
erigon-lib/chain/snapcfg/util_test.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/block_snapshots_test.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go

same as #11710 and #12351 but for 2.60

known cfg 2.60

---

turbo/engineapi/engine_server.go
turbo/engineapi/interface.go

See https://github.com/ethereum/execution-apis/pull/586

engine: Remove engine_getPayloadBodiesBy{Hash|Range}V2

---

README.md

Fix the wiki for gnome Tracker

---

cmd/state/exec3/historical_trace_worker.go

Reproduce in sepolia,  `rm-state --domain=receipt` and then` run stage_custom_trace`.
when exec.workers > 1,  `[EROR] [10-25|06:17:05.577] ReadHeaderRLP failed                     err="mdbx_get: MDBX_THREAD_MISMATCH: A thread has attempted to use a not owned object, e.g. a transaction that started by another thread"`
BTW, after this the commit,  the generate domain receipt file are same, but history file have different torrent_hash.

Fix stage_custom_trace

---

params/chainspecs/chiado.json
params/chainspecs/gnosis.json
params/chainspecs/holesky.json
params/chainspecs/mainnet.json
params/chainspecs/sepolia.json

The json field has been renamed `chain_config`

params: Update depositContractAddress field in json's

---

cmd/downloader/main.go

downloader: check chainID before torrent_create

---

eth/stagedsync/stage_txlookup.go

For: https://github.com/erigontech/erigon/issues/12502
- non-chain-tip: aggressive prune
- chain-tip: 250ms limit or 10 blocks

Prune: determenistic TxnLookup prune time

---

Dockerfile

Cherry pick the commit from `pectra_e2`

Update dockerfile to golang 1.22

---

turbo/jsonrpc/trace_adhoc.go
turbo/jsonrpc/trace_filtering.go

Duplicate #12559 into `release/2.61`

trace API: commit state changes from InitializeBlockExecution

---

consensus/merge/merge.go
consensus/misc/eip6110.go
consensus/misc/eip7002.go
consensus/misc/eip7251.go
core/types/block.go
turbo/engineapi/engine_server.go
turbo/execution/eth1/block_building.go

Cherry pick #12544 into `main`

Fix multiple hive/EEST issues + wait condition loop before sending SYNCING

---

cl/beacon/handler/validator_registration.go
cl/beacon/router.go
cl/monitor/validator.go
cl/validator/committee_subscription/committee_subscription.go

Demote logs in validator

---

turbo/jsonrpc/tracing.go

for https://github.com/erigontech/erigon/issues/12589

debug_traceCallMany: lost `ibs.Reset()`

---

.github/workflows/qa-rpc-integration-tests.yml
turbo/jsonrpc/tracing.go

after https://github.com/erigontech/erigon/pull/12593

rpc-test: enable `debug_` prefix

---

.github/workflows/qa-rpc-integration-tests.yml
turbo/jsonrpc/trace_adhoc.go

`trace_replayBlockTransactions/test_10.json`

trace_replayBlockTransactions: rpc-tests

---

.github/workflows/test-hive.yml
Makefile

Copy hive tests workflow from `main`

workflows: Add hive tests to e2 branches

---

eth/stagedsync/stage_mining_finish.go
turbo/engineapi/engine_server.go
turbo/engineapi/engine_types/jsonrpc.go

Cherry pick https://github.com/erigontech/erigon/pull/12588

Fix bug with sending empty requests list in pectra-devnet-4 (#12588)

---

.github/workflows/test-hive-eest.yml
Makefile

Cherry pick https://github.com/erigontech/erigon/pull/12599

workflows: Add ethereum/eest separate workflow  (#12599)

---

docs/programmers_guide/guide.md

docs: fix crypto.go path

---

erigon-lib/kv/remotedb/kv_remote.go
erigon-lib/kv/remotedbserver/remotedbserver.go

Fixed PageToken management in IndexRange and DomainRange functions
Fixed PageSize management in remote db server

PageToken ad PageSize in IndexRange and DomainRange functions

---

.github/workflows/test-integration-erigon.yml
.github/workflows/test-integration-michele.yml

This PR adds test-integration-erigon.yml, which takes over test-integration.yml

Add test-integration-erigon.yml

---

erigon-lib/common/dbg/experiments.go

ops, kept it set to true on `main` :D

Caplin: disabled deadlock detector

---

erigon-lib/state/domain_committed.go

fix visiblie file failed lookup logging

---

cmd/evm/internal/t8ntool/transition.go
core/state_transition.go
core/types/authorization.go
core/types/encdec_test.go
core/types/transaction_marshalling.go
erigon-lib/types/txn.go
erigon-lib/types/txn_test.go
tests/state_test_util.go

Cherry pick #12666 into `main`

EIP-7702 authorization: limit chain_id to uint64 and y_parity to uint8

---

.github/workflows/qa-rpc-integration-tests.yml

Bump rpc-tests to v1.12 plus specific commit to fix eth_syncing test incompleteness

qa-tests: bump rpc-tests version to latest

---

cl/clparams/config.go
cl/phase1/core/checkpoint_sync/remote_checkpoint_sync.go

fixes below error:
```
[DBUG] [11-11|16:37:19.885] Gotten unexpected root got=0xd566eb4ba463ffbfd9bbe503d295cb5f28ba86fa90f700e2f0d7582dbc8a3814 expected=0x3af6a8f94d7d81e513eeb3a94d8ccda9a4d7d3f1de1e38b5e4c12cd6b4496346
```
due to `BeaconBody` `HashSSZ` root hash being inaccurate
it was affected by chain config params that are different in Gnosis as per [specs](https://github.com/gnosischain/specs/blob/master/beacon_chain.md)

cl: fix chiado

---

core/state/dump.go

account range fix for test_11.json

---

go.mod
go.sum

Up-dep BLS

---

params/network_params.go

reduce chainDB size

---

cmd/integration/commands/stages.go
eth/stagedsync/stage_bor_heimdall.go

step2 of #11094. 
step1:  #12097

commit every N blocks in BorHeimdallForward

---

txnprovider/txpool/pool_test.go

Fixed txpool tests

---

erigon-lib/kv/tables.go

```
[EROR] [11-25|04:45:46.789] Staged Sync                              err="[3/9 BorHeimdall] label: consensus, table: BorSeparate, mdbx_get: MDBX_BAD_DBI: The specified DBI-handle is invalid or changed by another thread/transaction"
```

fix missed consensus tables

---

.github/workflows/qa-rpc-integration-tests.yml

Check rpc tests execution before merge!

qa-tests: bump rpc-tests version to 1.20.0

---

.github/workflows/kurtosis/config.properties
.github/workflows/test-kurtosis-assertoor.yml

- Running it off `ubuntu-latest`
- Removing go cache action
- Remove directory cleanup
- Remove other EL types

workflows: Simplify kurtosis assertoor workflow

---

erigon-lib/.golangci.yml
erigon-lib/common/bitutil/compress_test.go
erigon-lib/rlp/decode.go
erigon-lib/rlp/decode_test.go
erigon-lib/rlp/raw_test.go

Issue : https://github.com/erigontech/erigon/issues/12883

Remove rlp and bitutil from lint exclude-rules

---

erigon-lib/commitment/hex_patricia_hashed.go

seems `hashKey` didn't pass escape analysis and highlited by pprof

hashKey: escape analysis

---

.github/workflows/test-hive.yml

This test is broken, needs fixing in hive. Will take it up later

workflows: silence rpc compat in hive test for now

---

cmd/integration/commands/stages.go
eth/ethconfig/config.go
eth/stagedsync/stage_snapshots.go
eth/stagedsync/stage_txlookup.go
turbo/cli/flags.go
turbo/stages/mock/mock_sentry.go
turbo/stages/stageloop.go

e2 periodically spending too much time for pruning on chain-tip
- chain-tip: less aggressive prune
- non-chain-tip: more aggressive prune

e2: reduce prune limit on chain tip

---

cl/phase1/network/services/attestation_service.go

Frees 300MB of memory without any drawback. will leave it commented tho in case i need it again

Caplin: simplify attestation skip check

---

.github/workflows/test-integration-erigon.yml

This issue should now be fixed. Additional comments will be done on 09Dec at 10:00 (devops prioritisation meeting).

Fix issue #12644 

---

Dockerfile.release

Same as PR #12957 (or #12958) + `STOPSIGNAL 2`

Define UID and GID for erigon user as well as STOPSIGNAL.

---

turbo/engineapi/engine_server.go

As per the [specs](https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#engine_newpayloadv4) 
`V4`-Prague follows on from `V3`-Cancun, plus the added changes. So, in my interpretation, the following checks should hold:
- Params validation precedes over fork-version check. 
- Param validation for the additional param `executionRequests` should have the same semantics as point (1) from "Specification" section of [`newPayloadV3`](https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md#engine_getpayloadv3)
(This may break some opinionated hive tests, and potentially some spec tests)

engineapi: Add version-based check for requests list

---

turbo/engineapi/engine_server.go

Fixes bug introduced in https://github.com/erigontech/erigon/pull/12979

Fix bug on pre-Pectra `newPayload`

---

erigon-lib/chain/snapcfg/util.go
erigon-lib/downloader/util.go
turbo/snapshotsync/caplin_state_snapshots.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go
turbo/snapshotsync/snapshots.go

`KnownCfg` call is very expensive

speedup files open 

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Closes https://github.com/erigontech/erigon/issues/12739

downloader: fix stuck at 100%

---

erigon-lib/txpool/pool.go

Added check for bill, closes: #12858

txpool: nil pointer fix

---

cl/beacon/handler/block_production.go
cl/sentinel/sentinel.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go

fixed missing orphans on holesky. this way to retrieve head state to build the block on is much faster

Caplin: Speedup in block production

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

See https://github.com/holiman/uint256/releases/tag/v1.3.2

go.mod: holiman/uint256 v1.3.1 => v1.3.2

---

erigon-lib/downloader/README.md
erigon-lib/downloader/mdbx_piece_completion.go

availible → available
seperate → separate
reather → rather
intefere → interfere

Spelling and Formatting Improvements in Documentation

---

cl/clparams/config.go
eth/ethconfig/config.go

This will pump the price to 6000$ so it is very important.

Increase default gas limit from 30MN to 36MN

---

turbo/snapshotsync/freezeblocks/block_reader.go

Cherry pick PR #13027 into `release/2.61`

Pre-Shapella blocks must have nil withdrawals

---

cl/beacon/handler/block_production.go

Caplin: fix consensus-value in block production

---

turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_call.go
turbo/jsonrpc/eth_call_test.go

cherry-pick https://github.com/erigontech/erigon/pull/11743 to E2
closing https://github.com/erigontech/erigon/issues/13084

EstimateGas supports overriding state

---

.github/workflows/test-kurtosis-assertoor.yml

Attempt to fix pull request limit.
Issue https://github.com/erigontech/devops-metarepo-for-issues/issues/39
Thanks @michelemodolo for the idea.

Add login to dockerhub as attempt to fix pull request limit issue.

---

cl/beacon/router.go
cmd/caplin/caplinflags/flags.go

I just changed default value. If we ever want to change it, we can do it as a command line option.

set write timeout infinite

---

turbo/jsonrpc/eth_receipts.go

mentioned here https://github.com/ethereum/execution-apis/issues/296
and I was asked for it here https://github.com/erigontech/erigon/pull/13121#issuecomment-2543954611

more compatibility with eth spec for getLogs

---

turbo/jsonrpc/eth_receipts.go

added null topics skip

---

ChangeLog.md
cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cmd/rpcdaemon/README.md
cmd/snapshots/README.md
polygon/bridge/mdbx_store.go
turbo/app/README.md

Fixed typos that airdrop farmers found

---

erigon-lib/config3/config3.go
erigon-lib/state/aggregator.go
erigon-lib/state/aggregator_test.go
erigon-lib/state/domain.go
erigon-lib/state/domain_test.go
erigon-lib/state/files_item.go
erigon-lib/state/history_test.go
erigon-lib/state/inverted_index_test.go

- Rename Cold -> Frozen because its current name is misleading
- Move constant to the same place other hardcoded configs are

Rename/move StepsInFrozenFile constant

---

cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go
erigon-lib/common/dbg/experiments.go

this seems to be source of instability

Caplin: fix reusable states during reorg

---

cmd/rpcdaemon/cli/config.go

This fixes Issue #12525 (and similar ones) with remote RPC daemon. This is an auxiliary fix on top of the main one in PR  #12559.

Handle The Merge in remoteConsensusEngine

---

cmd/integration/commands/stages.go
eth/stagedsync/default_stages.go
eth/stagedsync/stage_blockhashes.go
eth/stagedsync/stage_senders.go

closing https://github.com/erigontech/erigon/issues/12799

remove noop prune methods

---

cl/beacon/handler/duties_attester.go
cl/beacon/handler/duties_proposer.go

fix root value in events

---

cmd/rpcdaemon/cli/config.go
consensus/aura/aura.go
consensus/aura/epoch.go
erigon-lib/kv/helpers.go
erigon-lib/kv/tables.go
polygon/bor/bor.go

Cherry pick PR #13141 into `release/2.61`

Implement AuRa remoteConsensusEngine

---

.github/workflows/backups-dashboards.yml

This introduces a new workflow for automating the dashboards backup.

Automation for dashboards backup

---

.github/workflows/backups-dashboards.yml

I streamlined the workflow for backing up dashboards and avoided unnecessary fiddling of users with erigon repo branch.

dashboards backup

---

cl/phase1/network/gossip_manager.go

[#closes 13154](https://github.com/erigontech/erigon/issues/13154)

not synced not logging

---

erigon-lib/state/aggregator.go
erigon-lib/state/aggregator_test.go
erigon-lib/state/domain.go
erigon-lib/state/domain_test.go
erigon-lib/state/history.go
erigon-lib/state/history_test.go
erigon-lib/state/inverted_index.go
erigon-lib/state/inverted_index_test.go
erigon-lib/state/merge_test.go
migrations/reset_stage_txn_lookup.go

- `extract domain compresscfg` from domain to schema
- extract schema out of agg constructor

agg: schema

---

erigon-lib/kv/tables.go
erigon-lib/state/aggregator.go
erigon-lib/state/domain_shared.go
erigon-lib/state/domain_shared_test.go
erigon-lib/state/squeeze.go

`minimaxTxNumInDomainFiles` method - to accept list of domains from outsides

agg: less hardcode domains. step1

---

eth/backend.go

non-funcional PR to prepare for future move of `setUpBlockReader` out of `backend.go` package

buildSema: accept it as a constructor parameter 

---

core/state/rw_v3.go
core/state/txtask.go
eth/stagedsync/exec3.go

E3: Remove unused "PruneNonEssentials" feauture

---

erigon-lib/etl/collector.go

pick: https://github.com/erigontech/erigon/pull/13299

etl: cursor leak (e2 pick)

---

eth/protocols/eth/protocol.go
turbo/stages/bodydownload/body_algos.go

fix some struct names in comment

chore: fix some struct names in comment

---

cmd/sentry/README.md

docs: Spelling error.

---

README.md

Corrected from "accessors" to "accessor"

Corrected "accessor" folder mistyping

---

cl/beacon/beaconhttp/api.go

caplin: Fix `nil` panic during error handling

---

cmd/evm/runner.go
cmd/evm/staterunner.go
cmd/integration/commands/stages.go
cmd/rpcdaemon/cli/config.go
cmd/state/commands/opcode_tracer.go
core/genesis_write.go
core/state/intra_block_state_test.go
core/state/state_test.go
core/test/domains_restart_test.go
core/vm/gas_table_test.go
core/vm/runtime/runtime.go
core/vm/runtime/runtime_test.go
erigon-lib/kv/membatchwithdb/memory_mutation_test.go
erigon-lib/kv/temporal/temporaltest/kv_temporal_testdb.go
erigon-lib/state/aggregator.go
erigon-lib/state/aggregator2.go
erigon-lib/state/aggregator_bench_test.go
erigon-lib/state/aggregator_fuzz_test.go
erigon-lib/state/aggregator_test.go
eth/backend.go
turbo/app/snapshots_cmd.go
turbo/app/squeeze_cmd.go

https://github.com/erigontech/erigon/issues/13326 and https://github.com/erigontech/erigon/issues/13325

move domains/ii registration out of aggregator constructor

---

cl/beacon/handler/pool.go
cl/beacon/handler/utils_test.go
cl/cltypes/aggregate.go
cl/cltypes/bls_to_execution_change.go
cl/cltypes/contribution.go
cl/cltypes/validator.go
cl/phase1/network/gossip_manager.go
cl/phase1/network/services/aggregate_and_proof_service.go
cl/phase1/network/services/aggregate_and_proof_service_test.go
cl/phase1/network/services/attestation_service.go
cl/phase1/network/services/attestation_service_test.go
cl/phase1/network/services/batch_signature_verification.go
cl/phase1/network/services/bls_to_execution_change_service.go
cl/phase1/network/services/bls_to_execution_change_service_test.go
cl/phase1/network/services/interface.go
cl/phase1/network/services/mock_services/aggregate_and_proof_service_mock.go
cl/phase1/network/services/mock_services/attestation_service_mock.go
cl/phase1/network/services/mock_services/blob_sidecars_service_mock.go
cl/phase1/network/services/mock_services/block_service_mock.go
cl/phase1/network/services/mock_services/bls_to_execution_change_service_mock.go
cl/phase1/network/services/mock_services/proposer_slashing_service_mock.go
cl/phase1/network/services/mock_services/sync_committee_messages_service_mock.go
cl/phase1/network/services/mock_services/sync_contribution_service_mock.go
cl/phase1/network/services/mock_services/voluntary_exit_service_mock.go
cl/phase1/network/services/sync_committee_messages_service.go
cl/phase1/network/services/sync_committee_messages_service_test.go
cl/phase1/network/services/sync_contribution_service.go
cl/phase1/network/services/sync_contribution_service_test.go
cl/phase1/network/services/voluntary_exit_service.go
cl/phase1/network/services/voluntary_exit_service_test.go

Basically libp2p handles that automatically and I did not know

Caplin: Avoid republishing in `GossipManager`

---

turbo/jsonrpc/eth_block.go

rpcdaemon: Set miner on `eth_getBlockByNumber` on Polygon

---

txnprovider/txpool/pool.go
txnprovider/txpool/pool_test.go
txnprovider/txpool/txpoolcfg/txpoolcfg.go

fixes a potential vulnerability

Added gas limit cap to txs in txpool

---

tests/exec_spec_test.go

Add pectra devnet 5 tests (eest disabled)

---

erigon-lib/bptree/node.go

Using standard library methods to simplify code, inspired by https://github.com/erigontech/erigon/pull/11380/files

refactor: use slices.contains

---

cl/beacon/beaconhttp/api.go
cl/beacon/handler/block_production.go
cl/beacon/handler/duties_attester.go
cl/beacon/handler/pool.go
cl/rpc/rpc.go

* Fixed inconsistent dependet_root
* Fixed panics when Erigon is not synced in the Beacon API
* Also do not error on failing to publish

Caplin: fixed small bugs

---

.github/workflows/qa-tip-tracking-polygon.yml
.github/workflows/qa-tip-tracking.yml

Upload plots created during test

qa-tests: upload metrics based plots generated in the tip-tracking test

---

params/version.go
turbo/engineapi/engine_server.go
turbo/engineapi/engine_types/jsonrpc.go
turbo/engineapi/interface.go

A rather simple implementation for `engine_getClientVersionV1`
Cherry pick https://github.com/erigontech/erigon/pull/13071

Implement GetClientVersionV1 (#13071)

---

params/protocol_params.go
tests/exec_spec_test.go

Cherry pick https://github.com/erigontech/erigon/pull/13349

BlockHash EIP-2935 changes for pectra-devnet-5  (#13349)

---

.github/workflows/ci.yml
.github/workflows/test-integration-caplin.yml
.github/workflows/test-integration-erigon.yml
params/protocol_params.go

See https://github.com/ethereum/EIPs/pull/9119 and https://github.com/ethereum/EIPs/pull/9118

Update addresses for EIPs 7002 and 7251

---

eth/backend.go
turbo/jsonrpc/eth_block.go
turbo/jsonrpc/eth_txs.go

found while running https://github.com/erigontech/erigon/pull/13415
few apis are missing calls to the new flow with the bridge reader when run with astrid hence not returning bor state sync txn

jsonrpc: fix state sync event txn for bor with astrid

---

.github/workflows/backups-dashboards.yml

This activates the erigonQA dashboard backup.

Add erigonQA backup

---

.github/workflows/ci.yml
.github/workflows/test-integration-caplin.yml
.github/workflows/test-integration.yml
core/state_transition.go
erigon-lib/common/fixedgas/protocol.go
erigon-lib/txpool/pool.go
erigon-lib/txpool/pool_test.go
erigon-lib/txpool/txpoolcfg/txpoolcfg.go
erigon-lib/txpool/txpoolcfg/txpoolcfg_test.go
tests/transaction_test_util.go

See https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7623.md
Issue board - https://github.com/erigontech/erigon/issues/12401
Cherry pick https://github.com/erigontech/erigon/pull/13080

Implement calldata cost increase per EIP-7623 (#13080)

---

cl/phase1/network/services/constants.go

fixes node falling out of sync sometimes

Caplin: Higher block and blob interval

---

core/rawdb/rawdbreset/reset_stages.go
core/state/rw_v3.go
erigon-lib/kv/kv_interface.go
erigon-lib/kv/tables.go
erigon-lib/state/aggregator.go
erigon-lib/state/aggregator2.go
erigon-lib/state/aggregator_files.go
erigon-lib/state/domain_shared.go
erigon-lib/state/integrity.go
erigon-lib/state/inverted_index.go
erigon-lib/state/merge.go
erigon-lib/state/squeeze.go

- trying to solve this - https://github.com/erigontech/erigon/issues/13432
- doesn't solve it completely...next step is to AccountsHistoryIdx, StorageHistoryIdx etc. linked to AccountsDomain, StorageDomain etc. this will make IndexRange one-liner

get rid of InvertedIndexPos

---

erigon-lib/state/aggregator.go
erigon-lib/state/history.go

- issue: https://github.com/erigontech/erigon/issues/13434

simplify HistorySeek

---

erigon-lib/common/dbg/experiments.go
eth/backend.go

e2 port of https://github.com/erigontech/erigon/pull/12698

dbg: add periodic save heap routine (#12698)

---

README.md

- updated link for blog
- removed duplicate links for blog and Twitter in the "Getting in touch section"

Update README.md link for blog

---

erigon-lib/state/aggregator.go

responding to comment in https://github.com/erigontech/erigon/pull/13431

small refactorings in aggregator.go

---

core/vm/contracts_test.go

Missed in https://github.com/erigontech/erigon/pull/13346

core/vm: Small fix

---

cmd/prometheus/dashboards/erigon_internals.json
dashboards/erigon_custom_metrics/erigon_custom_metrics.internal.json
erigon-lib/kv/kv_interface.go
erigon-lib/kv/mdbx/kv_mdbx.go

space retired metric added

---

txnprovider/txpool/pool.go

closing https://github.com/erigontech/erigon/issues/13477

txpool: race in logging

---

eth/backend.go

fixes https://github.com/erigontech/erigon/issues/13488

backend: fix sentry disable block download

---

erigon-lib/downloader/downloader.go

Removed web download client stats calculation as it isn't used at all.

downloader: removed web download client stats calculation

---

cmd/integration/commands/reset_state.go
cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_domains.go
cmd/integration/commands/state_stages.go

allSnapshots should not panic regardlessly

---

Makefile

Porting from the workflows to makefile for local testing. Benefits:
- Hiveview
- Faster execution of tests
- Easier to execute for a developer on local quickly

Add makefile entry for hive local

---

turbo/jsonrpc/debug_api.go
turbo/jsonrpc/erigon_receipts.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/receipts/bor_receipts_generator.go

at least I've eliminated getReceipts call where it was not needed
closes #13152

tx gran or smth like that to bor

---

erigon-lib/chain/chain_config.go
polygon/bor/borcfg/bor_config.go

Fix a small typo made in #13510

typo: GeAhmedabadBlock

---

.github/workflows/test-hive-eest.yml
core/state_transition.go
params/protocol_params.go

- Fix an issue where after the refund the gasUsed could go below floor gas
- Update spec tests for devnet-5 to release 1.2.0
- Update spec test version in Hive-EEST

core: Modify refund gas behaviour for floorgas and update EEST

---

erigon-lib/common/math/big.go
erigon-lib/common/math/big_test.go

Security issue https://github.com/erigontech/security/issues/12

Potential Out-of-Range Panic in UnmarshalJSON() of HexOrDecimal256

---

.github/workflows/qa-tip-tracking.yml

Implement https://github.com/erigontech/erigon-qa/issues/41

qa-tests: use a clean prebuilt db

---

erigon-lib/go.mod
erigon-lib/go.sum
erigon-lib/kv/mdbx/kv_mdbx.go
go.mod
go.sum

Reverts erigontech/erigon#13552

Revert "mdbx: v0.13.3"

---

cmd/state/commands/opcode_tracer.go
core/asm/asm.go
core/vm/absint_cfg_proof_gen.go
core/vm/opcodes.go
core/vm/opcodes_test.go
eth/tracers/js/goja.go

See https://github.com/erigontech/security/issues/17, https://github.com/ethereum/go-ethereum/pull/28520 & https://github.com/ethereum/go-ethereum/pull/30418

eth/tracers/js: fix isPush for push0

---

cmd/devnet/blocks/checks.go
cmd/devnet/blocks/waiter.go
cmd/devnet/contracts/util.go
cmd/devnet/requests/block.go
cmd/devnet/requests/nopgenerator.go
cmd/devnet/requests/request_generator.go
cmd/devnet/requests/transaction.go
cmd/devnet/services/polygon/proofgenerator.go
cmd/devnet/services/polygon/proofgenerator_test.go
cmd/evm/internal/t8ntool/transition.go
turbo/adapter/ethapi/api.go
turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_txs.go
turbo/jsonrpc/otterscan_api.go
turbo/jsonrpc/otterscan_search_trace.go
turbo/jsonrpc/txpool_api.go

Cherry pick PR #13575 into `release/2.61`

Unify jsonrpc.RPCTransaction & ethapi.RPCTransaction

---

erigon-lib/rlp/encode.go
erigon-lib/rlp/encode_test.go

Follow-up to PR #12869 & #13574

Fix EncodeUint256 to work with bigger buffers

---

cl/aggregation/mock_services/aggregation_pool_mock.go
cl/aggregation/pool.go
cl/aggregation/pool_impl.go
cl/beacon/handler/handler.go
cl/beacon/handler/pool.go
cl/beacon/handler/validators.go

https://github.com/ethereum/beacon-APIs/releases/tag/v3.0.0-alpha.9
https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/postStateValidatorIdentities

New beacon api for electra 

---

erigon-lib/rlp/encode.go
erigon-lib/rlp/encode_test.go

Follow on after https://github.com/erigontech/erigon/pull/13580

rlp: simplify `EncodeUint256`

---

core/types/blob_tx_wrapper.go
erigon-lib/chain/chain_config.go
erigon-lib/chain/chain_config_test.go
erigon-lib/common/fixedgas/protocol.go
erigon-lib/txpool/pool.go
erigon-lib/txpool/pool_fuzz_test.go
erigon-lib/txpool/pool_test.go
erigon-lib/txpool/txpoolutil/all_components.go
eth/gasprice/feehistory.go
params/chainspecs/chiado.json
params/chainspecs/gnosis.json
params/chainspecs/holesky.json
params/chainspecs/mainnet.json
params/chainspecs/sepolia.json
params/config_test.go
turbo/stages/mock/mock_sentry.go

Cherry pick #13443 into `release/2.61`

EIP-7840: Add blob schedule to EL config files

---

core/types/blob_tx.go
core/types/block_test.go
core/types/encdec_test.go
core/types/set_code_tx.go
core/types/transaction_test.go

One of the solutions to fix https://github.com/erigontech/security/issues/18

Nil Pointer Dereference Panics in encodePayload() of Blob Tx

---

cl/phase1/network/services/block_service.go

Caplin: disabled parallel exec of consensus and exec

---

turbo/jsonrpc/eth_block.go

See https://github.com/erigontech/erigon/pull/12469 and https://github.com/ethereum/hive/pull/1186

jsonrpc: Remove totalDifficulty hack for hive

---

.github/workflows/qa-rpc-performance-tests.yml

Add RPC performance testing workflow adapted from the Silkworm workflow.
Implements points 1 and 2 of https://github.com/erigontech/erigon-qa/issues/48

qa-tests: add rpc performance tests

---

ChangeLog.md
turbo/adapter/ethapi/api.go
turbo/jsonrpc/eth_accounts.go
turbo/jsonrpc/eth_api_test.go
turbo/jsonrpc/eth_call.go
turbo/jsonrpc/eth_receipts.go
turbo/rpchelper/helper.go

Set of minor changes to align with hive's `rpc-compat` tests
Also reverts https://github.com/erigontech/erigon/pull/8337

RPC-compat hive fixes

---

.github/workflows/scripts/run_rpc_tests.sh
cmd/state/exec3/historical_trace_worker.go
core/rawdb/rawtemporaldb/accessors_receipt.go
core/state/txtask.go
erigon-lib/state/domain_shared.go
erigon-lib/state/history.go
eth/integrity/receipts_no_duplicates.go
eth/stagedsync/exec3_serial.go
eth/stagedsync/stage_custom_trace.go

fixing https://github.com/erigontech/erigon/issues/13367 (will take couple days to gen and release new files)

ReceiptDomain: interity check

---

cl/antiquary/beacon_states_collector.go
cl/antiquary/state_antiquary.go
cl/beacon/handler/duties_proposer.go
cl/persistence/state/state_accessors.go
turbo/snapshotsync/caplin_state_snapshots.go

it is actually useless and buggy. there is a more elagant way to implement proposers endpoint with rando mixes instead.

Caplin: Remove `kv.Proposers`

---

cl/cltypes/solid/attestation.go
cl/phase1/network/services/aggregate_and_proof_service.go
cl/phase1/network/services/sync_contribution_service.go
cl/spectest/Makefile
cl/transition/impl/eth2/operations.go

Also fix https://github.com/erigontech/erigon/issues/13658 by copy validator data before processing it.
scan:
```
https://dora.pectra-devnet-6.ethpandaops.io/
```
run:
```
wget https://github.com/ethpandaops/pectra-devnets/raw/refs/heads/master/network-configs/devnet-6/metadata/genesis.ssz
wget https://raw.githubusercontent.com/ethpandaops/pectra-devnets/refs/heads/master/network-configs/devnet-6/metadata/genesis.json
wget https://raw.githubusercontent.com/ethpandaops/pectra-devnets/refs/heads/master/network-configs/devnet-6/metadata/config.yaml
```

Misc bugfix for electra

---

dashboards/erigonQA/erigonQA.internal.json

The erigonQA dashboard got changed so the new version should overtake the currently stored one, which should in turn get archived in a compressed form

[automation] Backup of erigonQA dashboard - 05 Feb 2025

---

ChangeLog.md
eth/backend.go
polygon/sync/service.go
txnprovider/shutter/pool.go
txnprovider/txpool/pool.go

noticed while debugging https://github.com/erigontech/erigon/pull/13689
also reported by a user on discord: [link](https://discord.com/channels/687972960811745322/983710221308416010/1334851818592927824)

backend: fix clean exit upon astrid err

---

.github/workflows/qa-rpc-performance-tests.yml

Use correct file name as input for hdr analysis script

qa-tests: fix rpc performance tests

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/holesky.json
params/chainspecs/sepolia.json

See https://github.com/ethereum/EIPs/pull/9322

Schedule Pectra hard-fork for Holešky and Sepolia

---

polygon/heimdall/client_http.go

Polygon node crashed with the following error
```
[EROR] [02-06|09:17:35.922] polygon sync crashed - stopping node     err="pos sync heimdall failed: span scraper failed: can't fetch id range: error while fetching data from Heimdall: url='https://heimdall-api-amoy.polygon.technology/bor/latest-span', status=404, body='<!DOCTYPE html>\n<html>\n\n<head>\n  <title>Error ・ Cloudflare Access</title>
```
This should not be a failing error as it is likely due to Cloudflare masking downtime of the Heimdall endpoint that are currently covered by `ErrServiceUnavailable`. We specifically check for `404` status codes as other status codes like `403` may signal other errors such as Cloudflare's DDoS protection.

polygon: Add Cloudflare transient err

---

eth/stagedsync/stage_mining_exec.go

I think the code speak for itself

Erigon 3: bad block produced when OPCode blockhash is invoked in block building

---

erigon-lib/state/aggregator.go
eth/backend.go

run building files in background after node startup

---

eth/stagedsync/stage_txlookup.go
turbo/jsonrpc/debug_api.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_txs.go
turbo/jsonrpc/trace_adhoc.go
turbo/jsonrpc/trace_filtering.go

stateTx bor txlookup fix

---

cmd/snapshots/genfromrpc/genfromrpc.go
core/rawdb/accessors_chain.go
core/types/arb_types.go
core/types/arb_types_test.go

Arbitrum: add scraping support to arb transactions

---

erigon-lib/go.mod
erigon-lib/go.sum
erigon-lib/kv/mdbx/kv_mdbx.go
go.mod
go.sum

connected to https://github.com/erigontech/mdbx-go/pull/160 and https://github.com/erigontech/mdbx-go/pull/161
closes #13673

MapFull message

---

tests/exec_spec_test.go

tests: enable EESTs

---

core/rawdb/accessors_chain.go
core/rawdb/blockio/block_writer.go
core/rawdb/state_version.go
erigon-lib/kv/kv_interface.go
erigon-lib/kv/kvcache/cache.go
erigon-lib/kv/kvcache/cache_test.go
erigon-lib/kv/mdbx/kv_mdbx.go
erigon-lib/kv/mdbx/kv_mdbx_test.go
erigon-lib/kv/membatchwithdb/memory_mutation.go
eth/stagedsync/stage_snapshots.go

https://github.com/erigontech/erigon/issues/13675

use ReadSequence and add mdbxtx.ResetSequence()

---

.github/workflows/qa-clean-exit-block-downloading.yml
.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/qa-rpc-performance-tests.yml
.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch-minimal-node.yml
.github/workflows/qa-tip-tracking-gnosis.yml
.github/workflows/qa-tip-tracking-polygon.yml
.github/workflows/qa-tip-tracking.yml

Schedule some QA tests to run on every commit to the 3.x branch

qa-tests: execute qa-tests on every commit to the 3.x branch

---

cl/merkle_tree/merkle_tree.go
cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/network/beacon_downloader.go
cl/phase1/stages/forward_sync.go

Caplin: fix bad `CopyTo` (#13797)

---

turbo/engineapi/engine_helpers/constants.go
turbo/engineapi/engine_server.go

engineapi: Add Pectra banner (#13785)

---

turbo/engineapi/engine_server.go

Engine API: shorter waits

---

.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/scripts/run_rpc_tests.sh

qa-tests: improve rpc-integration tests

---

.github/workflows/qa-clean-exit-block-downloading.yml
.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/qa-rpc-performance-tests.yml
.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch-minimal-node.yml
.github/workflows/qa-tip-tracking-gnosis.yml
.github/workflows/qa-tip-tracking-polygon.yml
.github/workflows/qa-tip-tracking.yml

Schedule some QA tests to run on every commit to the 3.x branch
(cherry picked from commit 7d45903e93ee5378a6a0896065d3f3e8424a32a5)

qa-tests: execute tests on every commit to the 3.x branch (#13783)

---

eth/stagedsync/exec3.go

Cherry pick #13813 into `release/3.0`

Erigon3: never skip transactions in block production

---

cl/sentinel/discovery.go
cl/sentinel/sentinel.go
cl/sentinel/sentinel_gossip_test.go
cl/sentinel/sentinel_requests_test.go

I also removed some code from `discovery` which is mostly useless

Cherry-pick: Caplin: now respecting max peer count (#13858)

---

cl/clparams/config.go

caplin: Omit marshalling if `nil` 

---

erigon-lib/kv/kv_interface.go
erigon-lib/kv/mdbx/kv_mdbx.go

Solves concurrency issues with MDBXSummaries global map.

Make mdbx summaries map concurrent

---

cl/phase1/stages/forward_sync.go

unnecessary and this should somewhat simplify

Caplin: remove beacon blocks filtering

---

core/vm/common.go
core/vm/contracts_test.go

Fixes https://github.com/erigontech/security/issues/1

Handle potential overflow in getData

---

cl/phase1/stages/forward_sync.go

Cherry pick PR #13883 into `release/3.0`

Cherry-pick: fix stuck forward sync

---

turbo/snapshotsync/snapshots.go

fixes: https://github.com/erigontech/erigon/issues/13897

set ready on file open as well as download complete

---

core/blockchain.go
eth/stagedsync/exec3_serial.go

ports https://github.com/erigontech/erigon/pull/9340 to E3's `BlockPostValidation`

stagedsync: dbg option to log receipts on receipts hash mismatch

---

turbo/jsonrpc/eth_call.go

Needed for #13636 (But doesn't optimally achieve the requirements yet)

Basic fix to historical `eth_estimateGas`

---

.github/workflows/qa-tip-tracking-polygon.yml
.github/workflows/qa-tip-tracking.yml

qa-tests: import into release/3.0 some changes made to tip-tracking workflows 

---

erigon-lib/kv/mdbx/kv_mdbx.go

ust to not worry about them in tests and small cli tools

db: add comments to roLimiter field

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/chiado.json

Schedule Pectra for Chiado

---

turbo/app/snapshots_cmd.go

Cherry pick of #13872 to release/3.0

Cherry Pick: `snapshots retire --from/to` fix  #13872 

---

cmd/devnet/services/polygon/heimdall.go
cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go
polygon/bor/bor_test.go
polygon/heimdall/client.go
polygon/heimdall/client_http.go
polygon/heimdall/client_mock.go
polygon/heimdall/metrics.go
polygon/heimdall/service.go
polygon/heimdall/service_test.go
polygon/heimdall/status.go
polygon/sync/sync.go

cherry-pick https://github.com/erigontech/erigon/pull/13807 patch into release/3.0

Implemented wait if heimdall is not synced to the chain (#13807)

---

cl/utils/bytes.go

Cherry pick PR #13941 into `release/3.0`

Caplin: fix len in snappy decompression (#13941)

---

turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/receipts/bor_receipts_generator.go

rpcdaemon: Show state sync transactions in `eth_getLogs` (#13924)

---

.github/workflows/qa-tip-tracking.yml

see https://github.com/erigontech/erigon/pull/13966

Cherry-pick: fix tip-tracking workflow under cancellation

---

README.md

Due to new website, from:
https://erigon.tech/news/
to:
https://erigon.tech/blog/

Update link to blog in README.md

---

txnprovider/txpool/pool.go

Increased gas lim according to https://github.com/erigontech/erigon/pull/13057

increased gas limit in pool

---

cl/clparams/config.go

Refer to https://github.com/gnosischain/specs/pull/67

Gnosis: set BlobSidecarSubnetCountElectra to 2

---

erigon-lib/kv/temporal/kv_temporal.go
erigon-lib/state/aggregator.go
erigon-lib/state/domain_shared.go

discussed in https://github.com/erigontech/erigon/issues/13261

tx param should be last in `GetAsOf`

---

.github/workflows/qa-tip-tracking-gnosis.yml
.github/workflows/qa-tip-tracking.yml

Add missing workflows from branch 2.60

qa-tests: add missing tip-tracking workflows on branch 2.61

---

.github/workflows/qa-txpool-performance-test.yml

Fix/QA TXPool Workflow

---

.github/workflows/qa-sync-from-scratch.yml

qa-tests: add automatic trigger for sync-from-scratch test on release/3.0

---

erigon-lib/state/aggregator.go
erigon-lib/state/aggregator2.go
erigon-lib/state/domain_shared.go

slowly reducing amount of private method used by SharedDomains

move DiscardHistory - from runtime to Schema

---

rules.go

- Improved report messages:  
- Updated "maybe" phrasing to "Did you mean" for better readability.
- Fixed wording in the rollback recommendation message for clarity and consistency.

Improve report messages in `rules.go`

---

ChangeLog.md

Copy PRs #13995 & #14004 from `release/3.0` into `main`. Start a change log for v3.1.0.

Add v3.0.0 & v3.1.0 changelog

---

txnprovider/txpool/txpoolcfg/txpoolcfg.go

this is not critical. it just prints trash

TxPool: Fix panic in the `TransactionPool`

---

erigon-lib/common/dbg/experiments.go
erigon-lib/config3/config3.go
eth/stagedsync/stage_execute.go

for: https://github.com/erigontech/erigon/issues/13546#issuecomment-2677504018

added `MAX_REORG_DEPTH=512` env variable

---

cl/aggregation/pool_test.go
cl/cltypes/solid/bitlist.go

Cherry pick https://github.com/erigontech/erigon/pull/14035 into release/3.0

error on aggregation_bit merge (#14035)

---

consensus/misc/eip6110.go

See
https://sepolia.etherscan.io/tx/0xaebb84d80e12682fd1eafc494081cc8207abd26af3feb75c65b3c398561f2328#eventlog

Cherry-pick: Pectra: fix bad deposit contract deposit unmarshalling (#14066)

---

turbo/jsonrpc/debug_api.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_txs.go
turbo/jsonrpc/trace_adhoc.go
turbo/jsonrpc/trace_filtering.go

rpcdaemon: Set correct txnum for bridge txns 

---

turbo/jsonrpc/eth_receipts.go

cherry-pick https://github.com/erigontech/erigon/pull/14091 to release/3.0

cherry-pick: nil ptr in gen bor logs 

---

turbo/snapshotsync/snapshots.go

pick https://github.com/erigontech/erigon/pull/13901 to 3.0

cherry-pick: external rpcdaemon can't start

---

turbo/app/support_cmd.go

Fixed stuck on "ctrl+c" for support command

fix terminate support cmd

---

cmd/rpcdaemon/cli/config.go
cmd/state/exec3/historical_trace_worker.go
cmd/state/exec3/state.go
consensus/aura/aura.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/merge/merge.go
core/blockchain.go
eth/stagedsync/exec3_parallel.go
eth/stagedsync/exec3_serial.go
polygon/bor/bor.go
polygon/bor/fake.go

state, consensus: skip requests check when receipts unavailable after exec (#14107)

---

.github/workflows/scripts/run_rpc_tests.sh

qa-tests: re-enable eth_estimateGas/test_14

---

.github/workflows/test-hive-eest.yml
.github/workflows/test-hive.yml

Increasing threshold to 10% failed

workflows: Stricter failure checks for hive tests

---

README.md

pr:https://github.com/erigontech/erigon/pull/12477 removed `for-remote-db`

update readme json-rpc-daemon link

---

cmd/integration/commands/state_domains.go

Add step range filters for domain file processing during purification.

---

eth/gasprice/feehistory.go
eth/gasprice/gasprice.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_system.go
turbo/jsonrpc/receipts/receipts_generator.go

followup on https://github.com/erigontech/erigon/pull/14135

simplify receipts data type in oracle

---

eth/gasprice/feehistory.go
eth/gasprice/gasprice.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_system.go
turbo/jsonrpc/receipts/receipts_generator.go

Reverts erigontech/erigon#14166
seems my PR did break RPC tests in `main`. reverting.

Revert "simplify receipts data type in oracle"

---

.goreleaser.yml
Makefile

As requested in https://github.com/erigontech/erigon/pull/14176#issuecomment-2729029296

Cherry-Pick: Fixed sigill in released files (#14176)

---

eth/backend.go

remove debug printf leftover from a recent PR

backend: remove dbg printf in setupSnapDownloader

---

erigon-lib/chain/snapcfg/util.go
erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Cherry pick PR #14188 and set DefaultSnapshotGitBranch to release/3.0

Explicit DefaultSnapshotGitBranch release/3.0

---

tests/block_test.go

See https://github.com/ethereum/tests/releases/tag/v17.0

Upgrade ethereum/tests to v17.0

---

cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_ethgetlogs.go
cmd/rpctest/rpctest/request_generator.go
cmd/rpctest/rpctest/utils.go
erigon-lib/downloader/downloader.go
erigon-lib/state/domain_test.go
eth/integrity/bor_snapshots.go
eth/integrity/e3_ef_files.go
eth/integrity/e3_history_no_system_txs.go
eth/integrity/integrity_action_type.go
eth/integrity/snap_blocks_read.go
turbo/app/snapshots_cmd.go

pick: https://github.com/erigontech/erigon/pull/14175
pick: https://github.com/erigontech/erigon/pull/13662
pick: https://github.com/erigontech/erigon/pull/14197

release3.0: pick integirty checker and `rpctest invariantsEthGetLogs`

---

.github/workflows/test-hive-eest.yml

Cherry pick the related commits, #14178 #14217 , from main

tests: Update EEST fixtures to Vítkov (v4.1.0) release (#14178 #14217)

---

cl/phase1/stages/forward_sync.go
cl/phase1/stages/stage_history_download.go

- Removed logging of println around the code
- Made better and more readable loggings of downloading history
- Filtered out bad logs in `ForwardSync`

Caplin: More user-friendly logging

---

erigon-lib/kv/mdbx/kv_mdbx.go

This should be more accurate than `mdbx_env_set_syncperiod()` which only checks if the period has been reached during `Commit()`, which also has the effect of making certain commits blocking.
With this PR a separate goroutine is running in the background, periodically flushing to disk  more accurately while also making any `tx.Commit()`  nonblocking when the db is in MDBX_SAFE_NOSYNC mode.

Goroutine for accurate periodic flush (in MDBX_SAFE_NOSYNC mode)

---

cl/clparams/config.go

See https://github.com/ethereum/consensus-specs/blob/v1.5.0-beta.3/configs/mainnet.yaml#L128

cl: RESP_TIMEOUT should be 10s

---

core/rawdb/accessors_indexes.go
core/rawdb/accessors_indexes_test.go
turbo/jsonrpc/debug_api.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_txs.go
turbo/jsonrpc/otterscan_search_v3.go
turbo/jsonrpc/receipts/receipts_generator.go
turbo/jsonrpc/trace_adhoc.go
turbo/jsonrpc/trace_filtering.go
turbo/snapshotsync/freezeblocks/block_reader.go

blockReader: just return what we wrote to db
app-level logic: to handle +1 of system txn somehow

`blockReader.txnLookup` to not increment `txNum` before return

---

cl/clparams/config.go
cl/phase1/network/blobs.go
cl/phase1/stages/chain_tip_sync.go
cl/phase1/stages/forward_sync.go
cl/phase1/stages/stage_history_download.go
cl/sentinel/communication/topics.go
cl/sentinel/handlers/handlers.go

Cherry pick #14222 into `release/3.0`

Caplin: missing MAX_REQUEST_BLOB_SIDECARS_ELECTRA

---

polygon/heimdall/client_http.go

https://github.com/erigontech/erigon/issues/14208#issuecomment-2734496267

Add "operation timed out" as transient error

---

core/state_transition.go
core/vm/evmtypes/evmtypes.go
turbo/adapter/ethapi/api.go
turbo/jsonrpc/eth_call.go

jsonrpc: add Authorizations to callArgs for `eth_estimateGas` (#14152)

---

consensus/merge/merge.go
eth/stagedsync/exec3_serial.go

https://github.com/erigontech/erigon/issues/14234
https://github.com/erigontech/erigon/issues/14269
I was not able to reproduce the crash, I had to delete chaindata for some reason and since then couldn't get this. It was happening on every restart until then.
Root issue investigation pending

return error when receipt is nil

---

polygon/heimdall/client_http.go
polygon/sync/sync.go

Follow up to https://github.com/erigontech/erigon/pull/14220
Closes #14208

Add Heimdall transient errors

---

turbo/jsonrpc/eth_call.go

Picking from a fix already merged into `release/3.0`

jsonrpc: Fix intrinsic case in `estimateGas`

---

erigon-lib/kv/mdbx/kv_mdbx.go

This should waste less CPU cycles on the MDBX flusher goroutine.

Remove default case in flusher

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test-hive.yml
.github/workflows/test-integration-erigon.yml
.github/workflows/test-kurtosis-assertoor.yml

Switch to ubuntu- and macos- "latest" runners,
Add missed dockerhub login action.
Small fixes.

Updates in github actions (-latest runners, etc).

---

erigon-lib/downloader/downloader.go

Erigon has many functions: sync, been validator, rpc (with public users), etc…
“Seeding files” - very low-priority functionality. No reason to crush everything if can’t seed some file.

downloader: don't panic on caplin files

---

erigon-lib/downloader/webseed.go

Closes https://github.com/erigontech/erigon/issues/14191

remove etag check (#14191)

---

erigon-lib/state/aggregator.go
erigon-lib/state/merge.go

for https://github.com/erigontech/erigon/issues/14268

agg: merge files must not crush app

---

erigon-lib/downloader/webseed.go

closes https://github.com/erigontech/erigon/issues/12578

exclude manifest.txt from webseed check

---

cl/beacon/builder/types.go
cl/beacon/handler/block_production.go
cl/cltypes/beacon_block_blinded.go
cl/phase1/execution_client/execution_client_direct.go
cl/phase1/execution_client/execution_client_rpc.go
cl/phase1/execution_client/execution_engine_mock.go
cl/phase1/execution_client/interface.go
turbo/execution/eth1/eth1_chain_reader/chain_reader.go

https://discord.com/channels/1133875232453693480/1133875510745772121/1354497502992138280
Issue: https://github.com/erigontech/erigon/issues/14319

Include execution requests in produced block

---

eth/protocols/eth/handler_test.go
eth/protocols/eth/handlers.go

Fixes: https://github.com/erigontech/erigon/issues/13931
and includes tests for the `GetBlockHeaders` request.

Fix overflow issue in P2P  GetBlockHeaders request  and add tests for GetBlockHeaders

---

turbo/engineapi/engine_server.go

Cherry pick PR #14338 into `release/3.0`

Engine API: log requests on block hash mismatch

---

.github/workflows/kurtosis/deposit-request.io
.github/workflows/kurtosis/pectra.io
.github/workflows/kurtosis/regular-assertoor.io

Small slot times not stable, increasing.
Also, I missed pushing the links in the last PR before merging https://github.com/erigontech/erigon/pull/14378

workflows: Fix links and increase slot times on kurtosis test files

---

core/types/blob_test_util.go
core/types/blob_tx_wrapper.go
core/types/block_test.go
core/types/testdata/testdata.go
core/types/transaction_test.go
erigon-lib/direct/txpool_client.go
erigon-lib/go.mod
erigon-lib/go.sum
erigon-lib/gointerfaces/txpoolproto/txpool.pb.go
erigon-lib/gointerfaces/txpoolproto/txpool_grpc.pb.go
params/config.go
turbo/engineapi/engine_api_methods.go
turbo/engineapi/engine_server.go
turbo/engineapi/engine_server_test.go
turbo/engineapi/engine_types/jsonrpc.go
turbo/engineapi/interface.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/mock/mock_sentry.go
txnprovider/txpool/pool.go
txnprovider/txpool/pool_mock.go
txnprovider/txpool/pool_test.go
txnprovider/txpool/txpool_grpc_server.go

engineeapi, txpool: Implement GetBlobsV1 (#13975)

---

erigon-lib/rlp/decode.go
erigon-lib/rlp/encode.go
erigon-lib/rlp/encode_test.go
erigon-lib/rlp/typecache.go

port `https://github.com/ethereum/go-ethereum/pull/22902`

rlp: port atomic typecache

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/mainnet.json

See https://github.com/ethereum/EIPs/pull/9560

Schedule Pectra hard fork for Ethereum Mainnet

---

cl/beacon/builder/types.go
cl/beacon/handler/block_production.go
cl/cltypes/beacon_block_blinded.go
cl/phase1/execution_client/execution_client_direct.go
cl/phase1/execution_client/execution_client_rpc.go
cl/phase1/execution_client/execution_engine_mock.go
cl/phase1/execution_client/interface.go
turbo/execution/eth1/eth1_chain_reader/chain_reader.go

https://discord.com/channels/1133875232453693480/1133875510745772121/1354497502992138280 
Issue: https://github.com/erigontech/erigon/issues/14319

cherry-pick: Include execution requests in produced block (#14326)

---

erigon-lib/common/fdlimit/fdlimit_darwin.go

Cherry pick #14017 into `release/3.0`

Increase maximum open files limit on MacOSX

---

.github/workflows/test-hive-eest.yml
.github/workflows/test-hive.yml

Cherry pick PRs #14115, #14249, and partially #14059 & #14302

workflows: Sync hive CI with main

---

turbo/engineapi/engine_api_jsonrpc_client.go
txnprovider/shutter/block_building_integration_test.go

closes: https://github.com/erigontech/erigon/issues/14417

engineapi: add retries to engineapi jsonrpc client

---

tests/state_test_util.go

Fix `evm` statetest crash

---

cl/antiquary/antiquary.go
cmd/caplin/caplin1/run.go

We really do not need to worry too much here.

Caplin-Archive: silenced early indexing error

---

erigon-lib/go.mod
erigon-lib/go.sum

Commit was not updated after https://github.com/erigontech/interfaces/pull/253 was merged

Fix interfaces commit

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/mainnet.json

See https://github.com/ethereum/EIPs/pull/9560
Cherry pick #14424

Schedule Pectra hard fork for Ethereum Mainnet (#14424)

---

erigon-lib/commitment/commitment.go
erigon-lib/commitment/commitment_test.go
erigon-lib/commitment/hex_patricia_hashed.go
erigon-lib/state/domain_shared.go

getting one hasher from the pool is slightly faster

Commitment: no embedded keccak

---

.github/workflows/kurtosis/deposit-request.io
.github/workflows/kurtosis/eip7702-test.io
.github/workflows/kurtosis/eip7702-txpool-invalidation.io
.github/workflows/kurtosis/el-triggered-consolidation-of-consolidations.io
.github/workflows/kurtosis/el-triggered-consolidations-test.io
.github/workflows/kurtosis/el-triggered-exit.io
.github/workflows/kurtosis/el-triggered-withdrawal.io
.github/workflows/kurtosis/fast_lifecycle.io
.github/workflows/kurtosis/pectra.io
.github/workflows/kurtosis/regular-assertoor.io
.github/workflows/kurtosis/validator-lifecycle-test-v3.io
.github/workflows/test-kurtosis-assertoor.yml

workflows: Add a subset of pectra tests and use smaller slot time for Kurtosis tests

---

cmd/integration/commands/stages.go

pick https://github.com/erigontech/erigon/pull/14121

[3.0 pick] fix: correct error handling in LogStats callback 

---

erigon-lib/state/aggregator.go
erigon-lib/state/aggregator2.go
erigon-lib/state/squeeze.go

pick https://github.com/erigontech/erigon/pull/14488

bug/race: recalcVisibleFiles doesn't lock dirty files

---

txnprovider/txpool/pool.go

Should check sender is a previously pending authority, before adding the authorities to `p.auth`
Cherry-pick #14502

txpool: Fix same sender-authority invalidation (#14502)

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/gnosis.json

See https://github.com/gnosischain/configs/pull/44 and  https://github.com/gnosischain/specs/pull/74

Schedule Pectra hard fork for Gnosis Mainnet

---

cl/clparams/config.go

cl: explicit FuluForkEpoch for all configs

---

cmd/utils/flags.go
erigon-lib/downloader/webseed.go

pick https://github.com/erigontech/erigon/pull/14317
pick https://github.com/erigontech/erigon/pull/14362

r30: manifest check CI 

---

cmd/pics/state.go
cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_txreceipts.go
cmd/rpctest/rpctest/request_generator.go
cmd/rpctest/rpctest/utils.go
cmd/state/exec3/state.go
cmd/utils/flags.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/rawdbreset/reset_stages.go
core/state/txtask.go
core/types/log.go
core/types/receipt.go
core/types/receipt_test.go
erigon-lib/kv/dbutils/composite_keys.go
erigon-lib/kv/tables.go
eth/ethconfig/config.go
eth/stagedsync/exec3.go
eth/stagedsync/exec3_serial.go
eth/stagedsync/stage_execute.go
go.mod
turbo/cli/default_flags.go
turbo/jsonrpc/eth_call_test.go
turbo/jsonrpc/receipts/receipts_generator.go
turbo/stages/mock/mock_sentry.go

pick https://github.com/erigontech/erigon/pull/14398
For: https://github.com/erigontech/erigon/issues/14371

r30: recent receipts persistence: to reduce RPC latency 

---

erigon-lib/state/aggregator.go
erigon-lib/state/aggregator_files.go

https://github.com/erigontech/erigon/pull/14553
https://github.com/erigontech/erigon/pull/14556

cp: remove unsafe closing of subsumed files in mergeLoopStep

---

cl/beacon/handler/utils_test.go
cl/clparams/config.go
cl/clparams/config_test.go
cl/clparams/initial_state/initial_state.go
cl/clparams/initial_state/initial_state_test.go
cl/cltypes/beacon_block_test.go
cl/persistence/state/slot_data_test.go
cl/phase1/core/checkpoint_sync/checkpoint_sync_test.go
cl/sentinel/handlers/blobs_test.go
cl/sentinel/handlers/heartbeats_test.go
cl/sentinel/msg_id_test.go
cl/sentinel/sentinel_gossip_test.go
cl/sentinel/sentinel_requests_test.go
cl/spectest/consensus_tests/fork_choice.go
erigon-lib/chain/networkid/network_id.go
txnprovider/shutter/config.go

tiny reduction in code duplication

cl: use networkid from erigon-lib

---

.github/workflows/test-hive-eest.yml

tests: Update to EESTs Vyšehrad (v4.2.0) release (#14547)

---

turbo/engineapi/engine_logs_spammer/engine_log_spammer.go

engineapi: increase externalcl spam timeout (#14561)

---

erigon-lib/state/domain_shared.go
erigon-lib/state/squeeze.go

In the scope of [the issue](https://github.com/erigontech/erigon/issues/14626)
related to[#14630](https://github.com/erigontech/erigon/issues/14630)

remove rotx from sd

---

cmd/integration/commands/state_domains.go

remove duplicate package imports

chore: remove duplicate package imports

---

erigon-lib/downloader/snaptype/files.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/caplin_state_snapshots.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/snapshots.go
turbo/snapshotsync/snapshots_test.go

pick https://github.com/erigontech/erigon/pull/14650

[r3.0 pick] seg blocks: cleanup garbage even if nothing to merge 

---

core/vm/evm.go
core/vm/instructions.go
core/vm/interpreter.go

This is a mess - oh my god. will divide this odyssey in many episodes

Arbitrum: Fix stylus part 1

---

.github/workflows/ci.yml
.github/workflows/test-all-erigon.yml

forgot to update this in https://github.com/erigontech/erigon/pull/14699

sonar: move sonar github action after make test-all

---

rpc/jsonrpc/internal_api.go

follow up on https://github.com/erigontech/erigon/pull/14684

Reuse internal _txNumReader

---

txnprovider/shutter/block_building_integration_test.go
txnprovider/shutter/internal/testhelpers/mock_cl.go

closes https://github.com/erigontech/erigon/issues/14692

txnprovider/shutter: fix shutter block building test on windows

---

erigon-lib/commitment/hex_patricia_hashed_test.go
erigon-lib/commitment/patricia_state_mock_test.go

Close https://github.com/erigontech/erigon/issues/14742, https://github.com/erigontech/erigon/issues/14752

fix race within concurrent trie in test

---

erigon-lib/state/aggregator.go

pick https://github.com/erigontech/erigon/pull/14745

[pick r3.0] merge: look only at state domains when canceling merge

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test-all-erigon.yml
.github/workflows/test-integration-caplin.yml
.golangci.yml
cmd/rpcdaemon/cli/config.go
erigon-lib/.golangci.yml
erigon-lib/seg/decompress_fuzz_test.go
erigon-lib/state/aggregator_bench_test.go
erigon-lib/state/aggregator_test.go
erigon-lib/state/btree_index_test.go
erigon-lib/state/domain_test.go
erigon-lib/tools/golangci_lint.sh
erigon-lib/types/aa_transaction.go
erigon-lib/types/transaction_marshalling.go
turbo/stages/genesis_test.go

we don't provide much support on old win - so run tests on recent version

CI: run on win2025

---

.github/workflows/ci.yml
.github/workflows/test-integration-caplin.yml
.github/workflows/test-integration-erigon.yml

pick https://github.com/erigontech/erigon/pull/14748

[r30 pick] CI: run on win2025

---

cmd/integration/commands/state_domains.go
erigon-lib/seg/compress.go
erigon-lib/seg/patricia/patricia_test.go
erigon-lib/seg/seg_auto_rw.go
erigon-lib/state/aggregator_test.go
erigon-lib/state/archive_test.go
erigon-lib/state/domain.go
erigon-lib/state/domain_shared.go
erigon-lib/state/domain_stream.go
erigon-lib/state/history.go
erigon-lib/state/inverted_index.go
erigon-lib/state/merge.go
erigon-lib/state/squeeze.go
turbo/app/snapshots_cmd.go

Port non-functional changes:
https://github.com/erigontech/erigon/pull/14680
https://github.com/erigontech/erigon/pull/14029
https://github.com/erigontech/erigon/pull/14680
to no diverge much `r3.0` and `main`

[r30 pick] `seg.Writer`: to satisfy `io.Writer` 

---

erigon-lib/kv/mdbx/kv_mdbx.go

pick https://github.com/erigontech/erigon/pull/14765

 increase in-mem db limit 

---

erigon-lib/state/aggregator.go
erigon-lib/state/merge.go
turbo/app/snapshots_cmd.go

pick https://github.com/erigontech/erigon/pull/14727

[r30] `erigon seg retire`: to remove garbage state files

---

erigon-lib/common/compress/compress.go
erigon-lib/common/compress/compress_test.go
erigon-lib/common/page/page.go
erigon-lib/common/page/page_test.go
erigon-lib/go.mod
erigon-lib/go.sum
erigon-lib/seg/decompress_test.go
erigon-lib/seg/seg_auto_rw.go
erigon-lib/state/aggregator2.go
erigon-lib/state/domain_stream.go
erigon-lib/state/domain_test.go
erigon-lib/state/gc_test.go
erigon-lib/state/history.go
erigon-lib/state/history_stream.go
erigon-lib/state/history_test.go
erigon-lib/state/merge.go
erigon-lib/state/state_recon.go
go.mod
go.sum

pick https://github.com/erigontech/erigon/pull/14679

[r30] history: page-level compression support

---

cmd/integration/Readme.md

closing https://github.com/erigontech/erigon/issues/14804

integration/readme.md for E3

---

cmd/diag/db/db.go
cmd/rpcdaemon/health/health.go
event/feed.go
p2p/netutil/net.go
rpc/handler.go
rpc/http.go

Optimize code using a more modern writing style.

refactor: use a more modern writing style

---

eth/stagedsync/stage_txlookup.go

Remove `borTxnLookupTransform`

---

.github/workflows/test-hive-eest.yml
consensus/merge/merge.go
consensus/misc/eip7002.go
consensus/misc/eip7251.go

See https://github.com/ethereum/EIPs/pull/9582 and https://github.com/ethereum/EIPs/pull/9508
- update EEST to v4.3.0
- downgrade `testdata` to v15.0
---------
Cherry-pick #14403

[cherry-pick] consensus: Add syscall failure scenarios (#14403)

---

Makefile
consensus/misc/eip6110.go

See https://github.com/ethereum/EIPs/pull/9460
Cherry-pick #14741

consensus: validate fixed lengths in abi decoding EIP-6110 deposit requests

---

erigon-lib/commitment/hex_patricia_hashed.go

Closes https://github.com/erigontech/erigon/issues/13236

Commitment: set `witness` prefix to witness related functions 

---

cmd/integration/commands/stages.go
cmd/state/exec3/historical_trace_worker.go
eth/stagedsync/stage_custom_trace.go
polygon/sync/execution_client.go
polygon/sync/sync.go

also picked: https://github.com/erigontech/erigon/pull/14824

[r30] stage_custom_trace: remove wrong assert

---

erigon-lib/chain/snapcfg/util.go
erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

This is a cherry pick of https://github.com/erigontech/erigon/pull/14829 to E30.

Switches CDN to R2; fallback to GH

---

cl/phase1/stages/stage_history_download.go

pick cl: Improve exec history download logs

[r30] cl: Improve exec history download logs

---

cl/phase1/stages/stage_history_download.go

Reverts erigontech/erigon#14838

Revert "cl: Improve exec history download logs" and replace with more decent logging

---

.github/workflows/qa-sync-with-externalcl.yml

Implement https://github.com/erigontech/erigon-qa/issues/67

qa-tests: fix external-cl log uploading in the sync-with-externalcl test

---

turbo/app/snapshots_cmd.go

for https://github.com/erigontech/erigon/issues/14894

workarount "retire" for bormilestone files

---

.github/workflows/test-hive-eest.yml
Makefile

See https://github.com/erigontech/eest-fixtures/pull/12

tests: Update EESTs to release v4.4.0 (Stromovka)

---

cmd/integration/commands/stages.go
ethdb/prune/storage_mode.go
ethdb/prune/storage_mode_test.go
turbo/cli/flags.go

https://github.com/erigontech/erigon/issues/14006

[r30] prune mode flag parsing and `String()`-ing

---

cmd/rpctest/rpctest/bench_txreceipts.go

[main][rpctest]: BenchBlockReceipts fix

---

cmd/rpctest/main.go
cmd/rpctest/rpctest/bench1.go
cmd/rpctest/rpctest/bench_debugTrace.go
cmd/rpctest/rpctest/request_generator.go
cmd/rpctest/rpctest/request_generator_test.go

Review and new parameter for BenchDebugTraceTransaction

[release/3.0][rpctest]: BenchDebugTraceTransaction review

---

cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_tracetransaction.go
cmd/rpctest/rpctest/request_generator.go

Added bench for trace_transaction API

[main][rpctest]: BenchTraceTransaction

---

cmd/rpctest/main.go
cmd/rpctest/rpctest/bench1.go
cmd/rpctest/rpctest/bench_debugTrace.go
cmd/rpctest/rpctest/request_generator.go
cmd/rpctest/rpctest/request_generator_test.go

Review and new parameter for BenchDebugTraceTransaction

[main][rpctest]: BenchDebugTraceTransaction review

---

cmd/utils/flags.go

pick https://github.com/erigontech/erigon/pull/14903

reduce default `--torrent.download.slots` 

---

.github/workflows/test-hive-eest.yml
Makefile
cl/sentinel/sentinel_gossip_test.go
cmd/utils/flags.go

Cherry-pick tests improvement commits from main

---

.github/workflows/kurtosis/pectra.io

Been failing for no reason on GH actions only, probably hardware issue. Will optimize this test and enable in future.
Cherry-pick #14834

[cherry-pick] workflows: Temp disable 7702 invalidation test on kurtosis (#14834)

---

.github/workflows/qa-rpc-integration-tests.yml

Merged PR #366 integration/mainnet: remove aura fields by

qa-integration-test: update rpc-test version to 1.58.0

---

cl/phase1/stages/stage_history_download.go

… decent logging (#14873)
Reverts erigontech/erigon#14838

Cherry-Pick: log revert

---

erigon-lib/downloader/downloadercfg/downloadercfg.go

Reverts erigontech/erigon#14642

Revert "[3.0 pick] downloader: same NetworkChunkSize as in Erigon2"

---

cmd/utils/flags.go

https://discord.com/channels/1133875232453693480/1133875412418699354/1370103433931001966

Disable diagnostics by default

---

cmd/utils/flags.go

pick https://github.com/erigontech/erigon/pull/14953

[r31] disable diagnostics by default

---

core/snaptype/block_types.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/bor_snapshots.go
turbo/snapshotsync/merger.go

https://github.com/erigontech/erigon/issues/14909

fix erigon seg retire to handle incomplete merges

---

polygon/sync/sync.go
turbo/app/snapshots_cmd.go

Cherry-pick polygon snapshot related commits from main(#14946)

---

cl/phase1/execution_client/execution_client_direct.go

Cherry-Pick: Erigon: optimistic inclusion for deep reorgs #14875

---

cmd/integration/commands/idx_optimize.go
cmd/integration/commands/idx_verify.go
cmd/integration/commands/refetence_db.go
cmd/integration/commands/reset_state.go
cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/rpcdaemon/cli/config.go
erigon-lib/state/entity_extras/emptydir.go
turbo/app/snapshots_cmd.go

- fast fail integration subcommands
- improve error message and resolution steps

fast fail integration subcommands on missing salt files

---

cmd/rpctest/rpctest/bench_ethgetlogs.go
core/snaptype/block_types.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/bor_snapshots.go
turbo/snapshotsync/merger.go

https://github.com/erigontech/erigon/pull/14973

cherry-pick: fix erigon seg retire to handle incomplete merges

---

turbo/engineapi/engine_block_downloader/core.go
turbo/engineapi/engine_server.go

A more robust version of #14911

EngineBlockDownloader: pass heightToDownload when available

---

erigon-lib/state/history.go
erigon-lib/state/inverted_index.go
erigon-lib/state/snap_repo.go
erigon-lib/version/file_version.go

added eq method
added ok as return parameter to `FindFilesWithVersionsByPattern`

Minsup improvements

---

.github/workflows/kurtosis/eip7702-test.io

Fix recently failing Kurtosis assertoor tests

workflows: Fix 7702 assertoor test

---

.github/workflows/ci.yml
.github/workflows/test-all-erigon.yml
.github/workflows/test-erigon-is-library.yml
.github/workflows/test-integration-caplin.yml
p2p/nat/natupnp_test.go
wmake.ps1

to fix `race - too many address space`
we have unit-tests - run on old OS's (for compatibility check) - it's enough

qa: run CI `make test-all` on modern OS and Golang

---

core/vm/instructions.go
core/vm/jump_table.go

benches are here `https://github.com/ethereum/go-ethereum/pull/31267`

vm: push2 

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/rpcservices/eth_backend.go
core/state/rw_v3.go
erigon-lib/common/dbg/dbg_env.go
erigon-lib/kv/kv_interface.go
erigon-lib/kv/remotedb/kv_remote.go
erigon-lib/kv/temporal/kv_temporal.go
erigon-lib/state/aggregator.go
erigon-lib/state/aggregator_debug.go
erigon-lib/state/kv_temporal_copy_test.go
erigon-lib/state/squeeze.go
eth/backend.go
rpc/jsonrpc/receipts/receipts_generator.go

https://github.com/erigontech/erigon/issues/15020
(cherry picked from commit 158c474f52a66a0454df7d7a0a5ed80b0a6af735)

notify rpcd when e3 files change (#15044)

---

core/test/domains_restart_test.go
erigon-lib/state/aggregator_test.go
erigon-lib/state/domain_shared.go
rpc/jsonrpc/eth_call.go

Need to separate SD and SDCTX so commitment will be computed separately.

refactor `sharedDomains.SeekCommitment` [step1]

---

.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/scripts/run_rpc_tests.sh

qa-tests: enable tests for parity_listStorageKeys()

---

erigon-lib/downloader/snaptype/files.go
turbo/snapshotsync/snapshots.go
turbo/snapshotsync/snapshots_test.go

issues: 
https://github.com/erigontech/erigon/issues/15175
https://github.com/erigontech/erigon/issues/15173

consider different index types when finding overlaps

---

cl/sentinel/httpreqresp/server.go
polygon/bor/bor.go
polygon/sync/canonical_chain_builder.go

This adds more info to errors that happen before sync errors

Add times to future block errors

---

turbo/app/snapshots_cmd.go

re-revert commit reverted due to release

don't delete state-salt file on rm-all-state-snapshots

---

rpc/ethapi/api.go

https://github.com/erigontech/nitro-erigon/issues/156
https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/rpc-methods#transactions

RPCd: Add arbitrum txs support

---

txnprovider/shutter/block_tracker.go
txnprovider/shutter/block_tracker_test.go

ci: fix flakiness in TestBlockTracker

---

cl/phase1/network/backward_beacon_downloader.go
cl/sentinel/handlers/heartbeats.go

Sentinel: Ignore goodbye err

---

polygon/sync/execution_client.go

follow up after https://github.com/erigontech/erigon/pull/15277
we should add a retry for "busy" in astrid when calling ExecutionModule.Ready

polygon/sync: retry ExecutionModule.Ready when busy

---

core/state/intra_block_state.go
core/state/versionedio.go
core/state/versionmap.go
core/state/versionmap_test.go
go.mod
go.sum

This adds a versioned map for managing dependencies for parallel transaction execution

Add versioned txn io

---

core/state/intra_block_state.go

Fixes compile error after https://github.com/erigontech/erigon/pull/15202 due to duplicate methods

Remove duplicate methods in ibs

---

polygon/sync/sync.go

follow up fix after https://github.com/erigontech/erigon/pull/15327 (forgot to update 1 place)

polygon/sync: fix inserts of new blocks when partially connected due to err

---

turbo/engineapi/engine_types/jsonrpc.go

See https://github.com/erigontech/erigon/discussions/15109

Engine API: omit CriticalError from JSON

---

.github/workflows/qa-rpc-test-bisection-tool.yml

Update workflow (test runner and test suite version)

qa-tests: update rpc test bisection tool

---

.github/workflows/qa-rpc-performance-tests.yml

Closes https://github.com/erigontech/erigon-qa/issues/138

perf_test: modify max rate eth_getBlockByHash from 10000:20 to 5000:20

---

.github/workflows/qa-test-report.yml

Workflow skeleton for test report; it is needed to test the workflow in a branch

qa-tests: add test report skeleton workflow

---

core/gaspool.go

The gas pool is shared between the apply and worker tasks in order to manage gas at a block level.  Although with recent updated this may not be necessary I don't want to remove it yet.

Add mutex to gas pool

---

.github/workflows/scripts/run_rpc_tests.sh

ci: re-enable failing tests after PR 12907

---

erigon-lib/kv/mdbx/kv_mdbx.go
eth/integrity/bor_snapshots.go

fix for heimdall integrity

---

execution/eth1/forkchoice.go
rpc/jsonrpc/receipts/receipts_generator.go

Basically, need to regen if the block was reorged.

E3: Fix receipts dangling from reorged blocks

---

params/chainspecs/amoy.json

Added Bhilai fork number (22765056) to amoy config

add fork number to config

---

turbo/jsonrpc/eth_accounts.go

[pick] jsonrpc: Add `acc.IsEmptyCodeHash` check in GetCode (#15360)

---

erigon-lib/seg/parallel_compress.go

for https://github.com/erigontech/erigon/issues/15378

comp: copyN with buf 

---

params/chainspecs/amoy.json

Bhilai fork number update

---

cmd/integration/commands/state_domains.go
erigon-lib/state/aggregator.go
erigon-lib/state/domain_shared.go
eth/stagedsync/stage_custom_trace.go
execution/exec3/historical_trace_worker.go

for: https://github.com/erigontech/erigon/issues/15219

[r30] stage_custom_trace: used deprecated config field

---

.github/workflows/qa-rpc-integration-tests.yml

includes tests of debug_traceTransaction() withLogs with position field

qa_integration: update rpc integration

---

cmd/integration/commands/reset_state.go
cmd/integration/commands/stages.go
core/state/history_reader_v3.go
erigon-lib/kv/kv_interface.go
erigon-lib/kv/membatchwithdb/memory_mutation.go
erigon-lib/kv/temporal/kv_temporal.go
erigon-lib/state/aggregator.go
erigon-lib/state/domain.go
erigon-lib/state/kv_temporal_copy_test.go
eth/integrity/receipts_no_duplicates.go
eth/stagedsync/stage_custom_trace.go
eth/stagedsync/stage_custom_trace_test.go
rpc/jsonrpc/eth_call.go

issue: https://github.com/erigontech/erigon/issues/15522
- can't print txNum for commitment domain (only step presented)

print_stages: print min/max step (or txnum) per each domain

---

polygon/heimdall/scraper.go
polygon/heimdall/service.go
polygon/heimdall/service_test.go
polygon/sync/sync.go

Another commit from main which needs to be cherry-picked. I forgot to add it in this PR - https://github.com/erigontech/erigon/pull/15540

Fixed polygon sync when no heimdall waypoints are available (#13844)

---

cl/beacon/handler/block_production.go
cl/phase1/execution_client/block_collector/block_collector.go
cl/phase1/execution_client/execution_client_direct.go
cl/phase1/execution_client/execution_client_rpc.go
cl/phase1/execution_client/execution_engine_mock.go
cl/phase1/execution_client/interface.go
cl/phase1/stages/forkchoice.go

caplin: fix safe block hash in fork choice update

---

cl/beacon/handler/block_production.go
cl/phase1/execution_client/block_collector/block_collector.go
cl/phase1/execution_client/execution_client_direct.go
cl/phase1/execution_client/execution_client_rpc.go
cl/phase1/execution_client/execution_engine_mock.go
cl/phase1/execution_client/interface.go
cl/phase1/stages/forkchoice.go

[r30] caplin: fix safe block hash in fork choice update

---

core/types/transaction_signing.go

This adds missing cases to MakeSigner and LatestSigner to allow code signing on Bhilai.
fixes: https://github.com/erigontech/erigon/issues/15572

Set code signer to handle bhilai code signing

---

erigon-lib/types/transaction_signing.go

Cherry Pick of: https://github.com/erigontech/erigon/pull/15577 for main.

Cherry Pick: Set code signer to handle bhilai code signing

---

polygon/heimdall/checkpoint.go
polygon/heimdall/client_http.go
polygon/heimdall/milestone.go
polygon/heimdall/span.go
polygon/heimdall/status.go

Part of the work for Heimdall V2 api integration. This is the changes which fix client side response format to meet heimdall v2 api requirements.

Fixed heimdall v2 responses

---

core/vm/evm.go

[r30] rpc: return empty code for store out-of-gas in CREATE calls

---

.github/workflows/qa-test-report.yml
.github/workflows/scripts/test_report/generate-test-report.ts
.github/workflows/scripts/test_report/package-lock.json
.github/workflows/scripts/test_report/package.json
.github/workflows/scripts/test_report/tsconfig.json

(cherry picked from commit 331d49fd7325b12aa101e915373f748a99657ce6)

[r30] qa-tests: cherry pick test report impl

---

core/vm/contracts.go

A nitpick to improve consistency between the `modExpMultComplexity`... comments.

core/vm: harmonize comments of modExpMultComplexity

---

params/chainspecs/bor-mainnet.json

(cherry picked from commit 6ad612d4bdd5fe0db992f59786c5159d66ab18d2)

Updated config for bor-mainnet Bhilai fork

---

.github/workflows/scripts/test_report/generate-test-report.ts

- Tests are now ordered alphabetically.
- Softer icons for cancelled runs.

qa-tests: improve test report formatting

---

.github/workflows/qa-rpc-integration-tests.yml

See https://github.com/erigontech/rpc-tests/releases/tag/v1.65.0

qa_tests: upgrade rpc-tests version 1.65.0

---

.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch-minimal-node.yml
.github/workflows/qa-sync-from-scratch.yml
.github/workflows/qa-sync-with-externalcl.yml
.github/workflows/qa-tip-tracking-gnosis.yml
.github/workflows/qa-tip-tracking-polygon.yml
.github/workflows/qa-tip-tracking.yml

port PR https://github.com/erigontech/erigon/pull/15292 on release/3 branch

[r30] qa-tests: Upload torrent client status artifact

---

execution/stagedsync/exec3.go

for parallel need more time to revise 
closes #15476

improved serial "Committed" log

---

turbo/execution/eth1/forkchoice.go

cherry pick https://github.com/erigontech/erigon/commit/29378d42dfb874d88bf91ce84b924b47253ff13e
protects the limitedBigJump calculation from a uint64 underflow
e.g. there can be cases (for example on chains like bor) where the ufc header number is a few blocks less than the previous exec progress from the last ufc - if we are on block 10 on fork A but then block 9 on fork B appears with higher difficulty (or when we handle milestone mismatches for example we call ufc for the milestone finalised end block which can be ~16 blocks behind)
such an underflow can cause limitedBigJump to be set to true which then sets IsInitialCycle=true potentially causing furious/aggressive prunes on chain tip

execution: fix potential limitedBigJump calc uint underflow in update ForkChoice

---

cmd/devnet/contracts/gen_childreceiver.go
cmd/devnet/contracts/gen_childsender.go
cmd/devnet/contracts/gen_faucet.go
cmd/devnet/contracts/gen_rootreceiver.go
cmd/devnet/contracts/gen_rootsender.go
cmd/devnet/contracts/gen_subscription.go
cmd/devnet/contracts/gen_testrootchain.go
cmd/devnet/contracts/gen_teststatesender.go
cmd/pics/contracts/gen_token.go
core/state/contracts/gen_changer.go
core/state/contracts/gen_phoenix.go
core/state/contracts/gen_poly.go
core/state/contracts/gen_revive.go
core/state/contracts/gen_revive2.go
core/state/contracts/gen_selfdestruct.go
execution/consensus/aura/auraabi/gen_block_reward.go
execution/consensus/aura/auraabi/gen_validator_set.go
rpc/jsonrpc/contracts/gen_poly.go
rpc/jsonrpc/contracts/gen_token.go
tests/contracts/gen_selfDestructor.go
tests/contracts/gen_testcontract.go
txnprovider/shutter/internal/contracts/gen_key_broadcast_contract.go
txnprovider/shutter/internal/contracts/gen_keyper_set.go
txnprovider/shutter/internal/contracts/gen_keyper_set_manager.go
txnprovider/shutter/internal/contracts/gen_sequencer.go
txnprovider/shutter/internal/contracts/gen_validator_registry.go

`gofmt -s -w .`
Follow up after #15675

Chore: Batch fmt after dir changes

---

cmd/rpctest/rpctest/bench_ethgetlogs.go

pick https://github.com/erigontech/erigon/pull/15779

[r31] rpctest: concurrent  invariantGetLogs, print blk/s 

---

.github/workflows/scripts/run_rpc_tests.sh
.github/workflows/scripts/run_rpc_tests_gnosis.sh
.github/workflows/scripts/run_rpc_tests_polygon.sh

same as https://github.com/erigontech/erigon/pull/15759 for test purposes

[r3.0] manual exec of rpc tests with venv

---

.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/scripts/run_rpc_tests.sh
.github/workflows/scripts/run_rpc_tests_gnosis.sh

closes #15755
closes #15754 (connected with https://github.com/erigontech/rpc-tests/pull/406)

manual exec of rpc tests with venv

---

cl/persistence/genesisdb/genesis_db.go
cl/phase1/core/state/raw/state.go

Fixes bad encoding size for genesis state

Caplin: Fix holesky/hoodi startup on develop

---

cmd/rpctest/rpctest/bench_ethgetlogs.go
cmd/rpctest/rpctest/request_generator.go

pick https://github.com/erigontech/erigon/pull/15817

[r30] rpctest invariantsEthGetLogs: speedup

---

.github/workflows/ci.yml
.github/workflows/qa-clean-exit-snapshot-downloading.yml
.github/workflows/qa-rpc-integration-tests.yml
.github/workflows/test-integration-erigon.yml

https://github.com/erigontech/erigon/commit/310c9db6b48be5a09dfd5f25549041d3725c28d8
https://github.com/erigontech/erigon/commit/ba0e3365be5b213e5846a198164afd42cadeb8df
https://github.com/erigontech/erigon/commit/2ebd1c38b07bc491774d0f5cb28d7338423aa3aa

cp: workflow fixes to release

---

eth/integrity/receipts_no_duplicates.go
execution/stagedsync/stage_custom_trace.go
turbo/app/snapshots_cmd.go

pick https://github.com/erigontech/erigon/pull/15816

[r31] integrity ReceiptsNoDupsRange: parallel 

---

erigon-lib/common/dbg/experiments.go
turbo/cli/default_flags.go
turbo/cli/flags.go
turbo/snapshotsync/snapshotsync.go

Forgot to uncomment + done clean ups

E3: History expiry was not working

---

cmd/rpctest/rpctest/bench_ethgetlogs.go
eth/integrity/receipts_no_duplicates.go
eth/stagedsync/stage_custom_trace.go

[r30] EthGetLogsInvariants: wait for pending work

---

core/forkid/forkid_test.go
params/chainspecs/bor-mainnet.json

- Cherry-picks https://github.com/erigontech/erigon/pull/15864 for release
- Fix fork id tests

Move bhilai fork to bor config and fix fork id tests

---

rpc/jsonrpc/eth_receipts.go
rpc/jsonrpc/receipts/receipts_generator.go

added dbg logs for receipt generator

---

cl/phase1/network/gossip_manager.go

Caplin: Enable Recover panic in gossip handling

---

docs/programmers_guide/guide.md
rpc/jsonrpc/otterscan_api.go

---
**Description:**  
- Updated outdated documentation link in the programmer's guide to the correct stagedsync reference.
- Replaced Infura reference with QuickNode documentation in the Otterscan API comments for better clarity and reliability.
---

Update Documentation Links 

---

turbo/app/snapshots_cmd.go

rm state snapshots flag mixer

---

.github/workflows/qa-rpc-integration-tests-gnosis.yml

Closes https://github.com/erigontech/erigon-qa/issues/213

qa_tests: add Gnosis RPC Integration Tests

---

core/vm/contracts.go
erigon-lib/chain/chain_config.go
rpc/jsonrpc/eth_api.go
rpc/jsonrpc/eth_system.go
rpc/jsonrpc/eth_system_test.go
rpc/jsonrpc/send_transaction_test.go

Closes https://github.com/erigontech/erigon/issues/14276
Note: This implementation is based on an evolving initial draft, there could be many changes to the spec. It's better to keep things simple and make small changes as things get to consensus on this among other core devs/client teams

 jsonrpc: implement eth_config 

---

cmd/integration/commands/stages.go
core/state/cached_writer.go
core/state/intra_block_state.go
core/state/versionedio.go
core/state_transition.go
erigon-lib/metrics/ema.go
erigon-lib/types/aa_transaction.go
erigon-lib/types/gen_header_json.go
eth/ethconfig/config.go
execution/stagedsync/exec3_status.go
execution/stagedsync/stage.go
execution/stagedsync/stage_bodies.go

This is what will hopefully be the last pre-parallel merge PR update.
It contains a series of minor print, or performance changes - each is identified by its own checkin below.  I've done this to remove the final noise from the parallel checking which should make it easier to review.

Misc async testing refactors

---

.github/workflows/qa-rpc-performance-tests.yml

Partial implementation for https://github.com/erigontech/erigon-qa/issues/214

qa_tests: move RPC perf tests to dedicated runner

---

turbo/jsonrpc/receipts/receipts_generator.go

[r30] r_lru: no clone

---

.github/workflows/qa-rpc-integration-tests-gnosis.yml
.github/workflows/qa-rpc-integration-tests-polygon.yml
.github/workflows/qa-rpc-integration-tests.yml

Part of https://github.com/erigontech/erigon-qa/issues/214

qa_tests: adjust runner labels in RPC Integration Tests

---

erigon-lib/state/integrity.go

integrity recover to check filename

---

turbo/app/snapshots_cmd.go
turbo/app/squeeze_cmd.go

issue: https://github.com/erigontech/erigon/issues/15893

lock datadir for some snapshot commands

---

execution/eth1/forkchoice.go
execution/eth1/metrics.go

relates to https://github.com/erigontech/erigon/pull/16104
adds a prune duration metric

execution: add metric for prune duration

---

execution/stagedsync/exec3.go

pick https://github.com/erigontech/erigon/commit/836fce7535e1af44173cdb99030c11d00f64a392

[e31] Exec3 small prune timeout 

---

execution/stagedsync/metrics.go
execution/stagedsync/sync.go

to help us see time spent per stage - can further help with https://github.com/erigontech/erigon/pull/16104

execution/stagedsync: add stage metrics

---

txnprovider/txpool/pool_db.go

Cherry pick of: https://github.com/erigontech/erigon/pull/15941

Add bor init to txpool configuration [main]

---

.github/workflows/test-hive-eest.yml

It runs with parallelism up to 32 very smoothly on a WD SN850x locally with 16 core processor.
I suspect there is a disk bottleneck

workflows: Remove hive parallelism from hive-eest 

---

erigon-lib/chain/params/protocol.go

closes https://github.com/erigontech/erigon/issues/16173

EIP-7918: change BlobBaseCost to 2^13

---

erigon-lib/chain/params/protocol.go

closes https://github.com/erigontech/erigon/issues/16174

EIP-7825: Update txn gas lim to 16,777,216

---

tests/block_test.go

closes https://github.com/erigontech/erigon/issues/16195

tests: re-enable TestExecutionSpecBlockchain after devnet-3 changes

---

cl/persistence/blob_storage/blob_db.go
cl/sentinel/handlers/blobs.go
cl/sentinel/handlers/handlers.go

https://github.com/erigontech/erigon/issues/16197

Remove spamming logs for requesting blobs not exist

---

.github/workflows/scripts/test_report/generate-test-report.ts

[r31] qa-tests: add "Tip tracking & migration" to Test Report

---

turbo/snapshotsync/snapshotsync.go

works fine after restart and post `seg reset` 
issue: https://github.com/erigontech/erigon/issues/16170

skip SyncSnapshots when preverified is local

---

erigon-db/rawdb/rawtemporaldb/accessors_receipt.go
erigon-lib/kv/kv_interface.go
erigon-lib/kv/remotedb/kv_remote.go
erigon-lib/kv/temporal/kv_temporal.go
erigon-lib/state/aggregator.go
erigon-lib/state/kv_temporal_copy_test.go
erigon-lib/state/version_schema.go
erigon-lib/version/file_version.go
execution/stagedsync/exec3_serial.go
rpc/jsonrpc/receipts/bor_receipts_generator.go
rpc/jsonrpc/receipts/receipts_generator.go

cherry pick: https://github.com/erigontech/erigon/pull/16204

cp: backwards compatibility for receipt data

---

cmd/erigon/main.go
cmd/utils/flags.go
erigon-db/downloader/downloader.go
erigon-db/downloader/downloader_grpc_server.go
erigon-db/downloader/downloadercfg/downloadercfg.go
go.mod
go.sum
turbo/app/reset-datadir.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/snapshotsync.go

Pull snapshot and downloader changes that went directly into 3.1, to main so they're similar there.

[3.2] more info in dbg trrent progress

---

erigon-lib/recsplit/index.go

for https://github.com/erigontech/erigon/issues/16277#issuecomment-3116708394

[r3.1] recsplit: backward compatibility fix

---

rpc/ethapi/api.go

After merge of main `NewRpcTransaction` flow was broken, this pr fixes that

Fix: RpcTx after merge

---

.github/workflows/qa-txpool-performance-test.yml

import changes from the main branch

[r31] qa-tests: update tx-pool performance workflow

---

cmd/downloader/main.go
erigon-lib/downloader/torrent_files.go
erigon-lib/downloader/util.go

`cd erigon_datadir && git pull && make downloader && /home/ubuntu/erigon/build/bin/downloader --chain=sepolia --datadir=datadir torrent_hashes --all --release` command for testing

hashes check for release fix

---

tests/block_test.go

The fixtures PR: https://github.com/erigontech/eest-fixtures/pull/21

tests: Use separate eest fixtures folder for devnets 

---

erigon-db/snaptype/block_types.go
erigon-lib/snaptype/caplin_types.go
erigon-lib/state/version_schema.go
polygon/heimdall/types.go

[r3.1] v1.1zation of e3.1 snapshots

---

rpc/batch_limit_ws_test.go

and https://github.com/erigontech/erigon/issues/16382

unstuck CI: TestBatchLimit_WebSocket_Exceeded

---

erigon-lib/chain/params/protocol.go
erigon-lib/types/blob_tx.go
erigon-lib/types/blob_tx_wrapper.go
eth/ethutils/utils.go
execution/engineapi/engine_server.go
txnprovider/txpool/pool.go

See https://github.com/ethereum/EIPs/pull/9981

Add blob per tx limit

---

turbo/app/snapshots_cmd.go

block number -> txNum range
txNum -> block number

adds debug tool `seg txnum` tool for block <-> txNum conversions

---

cl/phase1/forkchoice/on_block.go
erigon-lib/types/blob_tx.go
erigon-lib/types/blob_tx_wrapper.go
eth/ethutils/utils.go
execution/engineapi/engine_server.go

Follow up #16391. Fixes Hive EEST tests

Engine API: enforce MaxBlobsPerTxn only from Fusaka

---

turbo/app/snapshots_cmd.go

[main] publishable small fix (#16403)

---

polygon/bor/bor.go
polygon/bor/bor_internal_test.go
polygon/bor/bridge_reader_mock.go
polygon/bor/errors.go

cleanup follow up after https://github.com/erigontech/erigon/pull/16433

polygon/bor: cleanup dead remnants post recent cleanup

---

erigon-lib/state/domain.go

cp: https://github.com/erigontech/erigon/pull/16460

surface drowning error in accessor building

---

cmd/integration/commands/idx_optimize.go
cmd/integration/commands/idx_optimize2.go

cp: https://github.com/erigontech/erigon/pull/16461

adds idx_optimize2: idx_optimize but for a specific file

---

turbo/app/reset-datadir.go

Remove heimdall and polygon-bridge from datadir on reset

---

cl/beacon/builder/client.go
cl/beacon/handler/block_production.go
cl/beacon/handler/builder.go

* basically added `Date-Milliseconds` to `GetHeader`
* use of `/eth/v2/builder/validators`

Caplin: implemented mev-boost for Fulu

---

turbo/snapshotsync/freezeblocks/block_snapshots.go

Reverts erigontech/erigon#16345
otherwise Amoy doesn't create bor files at all

Revert "Added timeout for bor snapshots if data is not ready"

---

cl/clparams/config.go
cl/das/peer_das.go

basically the API was returning null for unset blob schedule and lh was shitting the bed

Caplin: fixed running lighthouse vc alongside it

---

README.md
eth/ethconfig/config.go
execution/eth1/forkchoice.go
execution/stages/stageloop.go
turbo/cli/flags.go

Reverts erigontech/erigon#16429
just for the time being

Revert "enable `--persist.receipts` by default"

---

rpc/jsonrpc/receipts/receipts_generator.go

Cherry pick #16496 into `release/3.1`

[r3.1] rpc: fix evm timeout in GetReceipts (#16496)

---

cmd/rpcdaemon/cli/config.go

do not receive snapshots through privateApiAddr, because it can connect to completely another node on the same machine

do not receive snapshots through privateApiAddr

---

turbo/snapshotsync/snapshotsync.go

First part addressing https://github.com/erigontech/erigon/issues/16448. https://github.com/erigontech/erigon/pull/16208 introduced skipping using the Downloader.Completed RPC. This means "completion" flags that the Downloader respects are skipped. Until https://github.com/erigontech/erigon/issues/15514 those are needed.
This introduces the behaviour suggested by https://github.com/erigontech/erigon/pull/16208#pullrequestreview-3042421807.
Note that it doesn't *alone* fix https://github.com/erigontech/erigon/issues/16448. Another change is needed to make sure that torrents with verification requested block Completed too. But there are probably other unexpected behaviours introduced by shortcutting the function as in https://github.com/erigontech/erigon/pull/16208.
After this is main I …

Don't skip Downloader complete check

---

cmd/utils/flags.go

3.1 default rate flags

---

cl/clparams/config.go
cl/das/peer_das.go

basically the API was returning null for unset blob schedule and lh was shitting the bed

Cherry-Pick: Caplin: fixed running lighthouse vc alongside it (#16495)

---

erigon-lib/types/aa_transaction.go
erigon-lib/types/access_list_tx.go
erigon-lib/types/blob_tx_wrapper.go
erigon-lib/types/dynamic_fee_tx.go
erigon-lib/types/legacy_tx.go
erigon-lib/types/transaction.go
eth/tracers/native/prestate.go

cherry-pick https://github.com/erigontech/erigon/pull/16497 to 3.1
Implements logic from https://github.com/erigontech/erigon/pull/16016 to main branch

tracer: fix prestates for EIP7702 transactions (#16497)

---

README.md

#16509 inadvertently reverted some README changes

[r3.1] revert readme change 

---

erigon-lib/chain/snapcfg/util.go

cp: https://github.com/erigontech/erigon/pull/16572

fix 500k file deletion on snapshotters

---

eth/stagedsync/stage_snapshots.go
turbo/snapshotsync/snapshotsync.go

pick https://github.com/erigontech/erigon/pull/16567

[r31] start on broken files 

---

erigon-lib/kv/kv_interface.go

pick https://github.com/erigontech/erigon/pull/16539

`kv` package improve docs (#16539)

---

cl/phase1/network/services/blob_sidecar_service_test.go
cmd/devnet/services/polygon/heimdallsim/heimdall_simulator_test.go
db/state/aggregator_bench_test.go
polygon/sync/event_channel_test.go
turbo/privateapi/logsfilter_test.go
txnprovider/txpool/fetch_test.go

Optimize code using a more modern writing style. Official support from Go Team. https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace context.WithCancel with t.Context

---

README.md
txnprovider/shutter/README.md

closes https://github.com/erigontech/erigon/issues/14283

txnprovider/shutter: add README with general info and run instructions

---

erigon-db/downloader/downloader.go

Fixes https://github.com/erigontech/erigon/issues/16529

Defer to torrent lib to manage data and lower log levels for ux

---

README.md
txnprovider/shutter/README.md

cherry-pick: https://github.com/erigontech/erigon/pull/16592
---
closes https://github.com/erigontech/erigon/issues/14283

txnprovider/shutter: add README with general info and run instructions (#16592)

---

.github/workflows/test-hive.yml
README.md

missed few places in previous PR...

workflows: test-hive and readme update to go 1.24

---

.github/workflows/qa-tip-tracking.yml

[r3.1] qa-tests: tip-tracking test with automatic upgrade

---

erigon-lib/state/domain.go
erigon-lib/state/history.go
erigon-lib/state/integrity.go
erigon-lib/state/inverted_index.go
erigon-lib/state/merge.go

NotDone: 
- I didn't add MinVersion check

versioning: `agg.BuildMissedAccessors` to see all available versions

---

execution/consensus/misc/eip4844.go

Make our implementation consistent with nethermind/reth/besu. See [Eth R&D discord](https://discord.com/channels/595666850260713488/1404938250761535553)

[EIP-7918] patch fusaka-devnet-4 issue

---

turbo/snapshotsync/snapshotsync.go

We need these for fast eth_getLogs

Erigon 3: Download `logaddr` and `logtopic` indicies

---

erigon-lib/chain/snapcfg/util.go

Wasn't setting the right values so KnownWebseeds and other values weren't updated correctly.
Now it works properly.

Fix snapshot overriding

---

erigon-db/downloader/downloader.go
eth/backend.go

Fixes the other component of https://github.com/erigontech/erigon/issues/16448.

Require torrents added from disk to complete on `downloader.verify`

---

turbo/snapshotsync/snapshotsync.go

We need these for fast eth_getLogs

Cherry-pick: download log indicies alongside rcache

---

.github/workflows/release.yml

See https://github.com/erigontech/erigon/pull/16737

Cherry-pick PR16737

---

.github/workflows/ci.yml
.github/workflows/test-all-erigon-race.yml
.github/workflows/test-all-erigon.yml
.github/workflows/test-hive-eest.yml
.github/workflows/test-hive.yml
.github/workflows/test-kurtosis-assertoor.yml
wmake.ps1

Cherry picks for:
- https://github.com/erigontech/erigon/pull/16445
- https://github.com/erigontech/erigon/pull/16456
- https://github.com/erigontech/erigon/pull/16459
Fixes https://github.com/erigontech/erigon/issues/16593

[r30] Fix CI checks

---

cmd/rpcdaemon/cli/config.go

Reverts erigontech/erigon#16734

Revert "rpcd: do txpool version compat check only when txpool is needed"

---

core/stateless/witness.go
p2p/sentry/sentry_multi_client/sentry_multi_client.go

Removed from Bor: https://github.com/0xPolygon/bor/pull/1705

Remove witness compression

---

txnprovider/txpool/pool.go

cherry-pick 93b6161 into release/3.1

txnprovider/txpool: unblock p.lastSeenCond.Wait on shutdown (#16750)

---

turbo/app/snapshots_cmd.go

e.g. `go run ./cmd/erigon seg integrity --datadir /erigon-data/chiado --check=Blocks,RCacheNoDups`

[r31] allow list of checks to be passed in publishable command

---

turbo/app/snapshots_cmd.go

issue: https://github.com/erigontech/erigon/issues/16721

[r31] add rcache/receipt/ii to publishable checks

---

core/genesis_write.go
execution/consensus/misc/eip2935.go
go.mod
go.sum
polygon/bor/bor.go
polygon/chain/config.go
polygon/heimdall/service.go
polygon/heimdall/span_block_producers_tracker.go
polygon/heimdall/validator_set.go
polygon/sync/block_producers_reader.go
polygon/sync/canonical_chain_builder.go
polygon/sync/canonical_chain_builder_factory.go
polygon/sync/canonical_chain_builder_test.go
polygon/sync/header_time_validator.go
polygon/sync/header_validator.go
polygon/sync/service.go
turbo/app/init_cmd.go

Cherry-pick https://github.com/erigontech/erigon/commit/9907be81956ed33b07a828e520602bd0d227cd72 from release/3.0 to main.

cherry-pick 9907be8 polygon: Implement VeBlop consensus changes

---

db/downloader/downloader.go
db/downloader/env.go
go.mod
go.sum

Cherry pick commits in individual commits.

Cherry pick downloader and torrent fixes from 3.1

---

cl/persistence/blob_storage/blob_db.go
cl/phase1/network/services/blob_sidecar_service.go
erigon-lib/go.mod
erigon-lib/go.sum
execution/types/blob_test_util.go
execution/types/blob_tx_wrapper.go
go.mod
go.sum
txnprovider/txpool/pool.go

Switch from https://github.com/crate-crypto/go-kzg-4844/pull/6 to a smaller https://github.com/crate-crypto/go-kzg-4844/pull/10

go-kzg-4844: pass blobs by pointer to VerifyBlobKZGProofBatch(Par)

---

rpc/jsonrpc/eth_receipts.go

issue: https://github.com/erigontech/erigon/issues/16833, https://github.com/erigontech/erigon/issues/16834

fix wrong header used in getLogsV3

---

.github/workflows/kurtosis/pectra.io
.github/workflows/kurtosis/regular-assertoor.io

workflows: use fixed teku version in kurtosis test (#16836)

---

execution/eth1/ethereum_execution.go

Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace HasPrefix+TrimPrefix with CutPrefix

---

.github/workflows/qa-rpc-performance-tests.yml

[r3.1] qa-tests: less strict error handling in RPC Performance Tests

---

.github/workflows/qa-constrained-tip-tracking.yml
.github/workflows/qa-snap-download.yml
.github/workflows/qa-sync-from-scratch-minimal-node.yml
.github/workflows/qa-sync-from-scratch.yml
.github/workflows/qa-sync-with-externalcl.yml
.github/workflows/qa-tip-tracking-gnosis.yml
.github/workflows/qa-tip-tracking-polygon.yml
.github/workflows/qa-tip-tracking.yml
db/datadir/dirs.go
db/state/domain.go
go.mod
go.sum
turbo/app/reset-datadir.go
turbo/app/snapshots_cmd.go

https://github.com/erigontech/erigon/pull/16879#issuecomment-3236026063 and some other fixes that went into 3.1.

Cherrypick fixes from 3.1

---

tests/block_test.go
tests/init_test.go
tests/state_test.go

cherry-picked some skips from Geth

testdata: skip slow tests

---

erigon-lib/gointerfaces/txpoolproto/txpool.pb.go
execution/engineapi/engine_server.go
execution/engineapi/engine_types/jsonrpc.go
txnprovider/txpool/txpool_grpc_server.go

See https://discord.com/channels/595666850260713488/1410267965341044819. Depends on https://github.com/erigontech/interfaces/pull/266

Engine API: more robust engine_getBlobsV2

---

cl/phase1/stages/forward_sync.go

The change essentially sets the startSlot as either:
- HighestSeenSlot - 300 (a reorg range)
- the finalized slot (if it is not too far)
- or the anchor slot (the lowest we can)

Caplin: better startSlot heuristic for non-finality

---

cmd/integration/commands/stages.go
cmd/rpctest/main.go
db/datastruct/fusefilter/fusefilter_reader.go
db/recsplit/index.go
db/state/domain.go
db/state/history.go
db/state/integrity.go
db/state/inverted_index.go
db/state/merge.go

pick https://github.com/erigontech/erigon/pull/16892

[r32] fuse_filter: keep in app's memory instead of mmap

---

erigon-db/go.mod
erigon-db/go.sum
erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Fixes https://github.com/erigontech/erigon-qa/issues/267

Fix panic on index out of range in torrent lib

---

core/evm.go
erigon-lib/chain/chain_config.go
polygon/bor/borcfg/bor_config.go
polygon/bor/borcfg/bor_config_test.go

Pick of https://github.com/0xPolygon/bor/pull/1743/files#diff-4ba922ac894c3457f34db3c567c59b9c7f5c6a2aa97f1c2529e62761f711a7ff

[r30] Rio/VeBlop custom coinbase address

---

erigon-lib/snaptype/files.go
erigon-lib/snaptype/type.go
erigon-lib/state/domain.go
erigon-lib/state/history.go
erigon-lib/state/inverted_index.go
erigon-lib/version/file_version.go
turbo/snapshotsync/merger.go
turbo/snapshotsync/snapshots.go

building indexes on old files if have some

---

erigon-lib/recsplit/index.go

cp of https://github.com/erigontech/erigon/pull/16591

[r3.1] catchinn panic in index lookup

---

db/recsplit/index.go

cp of https://github.com/erigontech/erigon/pull/16591

[main] catchinn panic in index lookup

---

execution/chain/chain_config.go
polygon/bor/bor.go
polygon/bor/borcfg/bor_config.go
polygon/chain/chainspecs/mumbai.json
polygon/heimdall/entity_fetcher.go
polygon/heimdall/service.go
polygon/sync/header_time_validator.go
polygon/sync/sync.go

Cherry-pick of :
https://github.com/erigontech/erigon/pull/16988
https://github.com/erigontech/erigon/pull/16991

Cherry-pick: Rename VeBlop to Rio, and  remove small wait when block author is not in the producer set

---

cmd/utils/flags.go
core/genesiswrite/genesis_test.go
core/genesiswrite/genesis_write.go
eth/backend.go
eth/ethconfig/config.go
turbo/cli/default_flags.go

Useful for shadow fork [testing](https://discord.com/channels/@me/948470027013742622/1413652485654184018)

Add --keep.stored.chain.config flag

---

cl/das/peer_das.go
cl/sentinel/sentinel.go
cl/sentinel/sentinel_gossip_test.go
cl/spectest/Makefile

- Avoid overwhelming peers by limiting the requested columns
- Update ENR when fork happens
- Update spec test

misc updates for fulu

---

cl/phase1/stages/forkchoice.go

This prioritize all events emitted near head

Cherry-Pick: Caplin: prioritize head event (#17122)

---

cl/beacon/handler/blobs.go
cl/beacon/handler/handler.go
cl/das/peer_das.go
cl/das/state/interface.go
cl/das/state/mock_services/peer_das_state_reader_mock.go
cl/das/state/state.go
cl/phase1/network/services/data_column_sidecar_service.go

new in fulu
https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlobs

CherryPick: API get blobs (#17076)

---

erigon-db/downloader/downloader.go

Fix a race I spotted running with the race detector in testing. It's pretty minor but it is a clear data race. I pushed to main in https://github.com/erigontech/erigon/pull/16895.

Fix race reading start time in Downloader logging

---

cmd/rpctest/rpctest/bench_ethgetlogs.go

for https://github.com/erigontech/erigon/issues/16833

[r31] restore topic invariant check in rpctest

---

polygon/sync/sync.go

cherry-pick of : https://github.com/erigontech/erigon/pull/17129

cherry-pick : synchronize spans before initial sync (#17129)

---

cl/das/peer_das.go
cl/persistence/blob_storage/data_column_db.go

It takes too much time to wait for and acquire a single lock, so try to avoid lock contention by using lock striping.

Improve performance of blob recovery

---

db/snapshotsync/merger.go
db/snapshotsync/snapshots_test.go

[main] cp bf merger fix main

---

erigon-lib/common/dir/rw_dir.go

[main] assert: deleted files revive

---

db/seg/decompress.go

better handle of out of bounds

---

cmd/utils/flags.go

Copies https://github.com/erigontech/erigon/pull/16526 which was merged to 3.1.

3.1 default rate flags to main

---

go.mod
go.sum

cherry-pick of https://github.com/erigontech/erigon/pull/16990 since I run into the same panic in `main` while running tests

torrent: cherry-pick from r31 to fix panic on index out of range in torrent lib

---

cl/das/p2p_utils.go
cl/das/peer_das.go
cl/phase1/network/services/data_column_sidecar_service.go
cl/phase1/network/services/data_column_sidecar_service_test.go

issue https://github.com/erigontech/security/issues/37 and https://github.com/erigontech/security/issues/39

constrain and check column data length

---

execution/abi/bind/backends/simulated.go
rpc/jsonrpc/eth_call.go

Cherry pick #17251 into `release/3.2`

[r32] [EIP-7825] EstimateGas: cap hi by MaxTxnGasLimit in Osaka

---

db/kv/remotedb/kv_remote.go
txnprovider/txpool/assemble.go

for https://github.com/erigontech/erigon/issues/17297

remote txpool: typed chainDB object 

---

execution/stagedsync/exec3.go

- with discard_commitment=true, the doms.Flush was skipped, leading to serial exec error

fix error in stage_exec with --no-commit

---

cl/phase1/network/backward_beacon_downloader.go
cl/phase1/network/beacon_downloader.go
cl/phase1/stages/chain_tip_sync.go
cl/phase1/stages/clstages.go
cl/phase1/stages/stage_history_download.go
cl/sentinel/service/service.go
cmd/capcli/cli.go

Reverts erigontech/erigon#15255

Revert "Caplin: Improved block downloader". potential regression

---

.github/workflows/scripts/run_rpc_tests_ethereum.sh
.github/workflows/scripts/run_rpc_tests_ethereum_latest.sh
execution/commitment/hex_patricia_hashed.go
rpc/contracts/direct_backend.go
rpc/jsonrpc/eth_api.go
rpc/jsonrpc/eth_call.go
rpc/jsonrpc/eth_call_test.go
turbo/transactions/call.go

includes rpc-test with estimateGas with block overrides

rpcademon: estimateGas WithBlockOverrides

---

rpc/jsonrpc/eth_filters.go
rpc/rpchelper/filters.go
rpc/rpchelper/logsfilter.go
rpc/subscription.go

rpc: fix no changes and filter not found in eth_getFilter* (#17327)

---

eth/tracers/logger/access_list_tracer.go

This is a fix to avoid access list tracing from returning results in random map order by adding code to preserve insetion order.
This will make access list RPC's return the same results when called with the same input.  I made the fix to address what I thought was a regression - it seems with the right version of json-diff this is not strictly necessary - however I think its a reasonable fix to include.

Make access list trace order deterministic
