erigontech/erigon

internal/build/util.go

Since go 1.8 GOPATH isn't required to be set on the target system, the default path is assumed to be `<HOME>/go`.

build: don't panic if GOPATH is not set.

---

.circleci/config.yml
Makefile

* Update circleci golang version
* Update golangci-lint version

Linters are not stable

---

cmd/state/state.go
cmd/state/stateless.go

This will be needed to reproduce an apparent bug in `trie.Resolver`

Control the size of the trie in stateless prototype, save state snapshot after errors

---

trie/gen_struct_step.go
trie/hack.go
trie/hashbuilder.go
trie/hasher.go
trie/resolve_set.go
trie/resolver.go
trie/resolver_test.go
trie/rlphacks/bytes.go
trie/rlphacks/bytes_test.go
trie/rlphacks/struct.go
trie/rlphacks/utils_bytes.go
trie/tapes.go
trie/utils.go

refactor trie package a bit

---

cmd/state/state.go
cmd/state/state_snapshot.go
cmd/state/state_snapshot_test.go
cmd/state/stateless.go

fixes #180 
to reduce the probability of breaking something during this refactoring I added a test for database copying.

Use `ethdb.Database` interface to generate snapshots.

---

cmd/hack/hack.go
cmd/rpctest/main.go
cmd/rpctest/proofs.go
cmd/state/state_snapshot.go
trie/debug.go
trie/trie.go

Partially solves https://github.com/ledgerwatch/turbo-geth/issues/190
It uses `eth_getProof` to narrow down from the root to the branches of the trie that have different hashes from what is expected (what is expected is taken from the results of the `eth_getProof` RPC call).

Debug tool for recursively comparing state (in DB or in a file) with geth archive node

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/root.go
cmd/state/commands/global_flags_vars.go
cmd/state/commands/state_growth.go
cmd/state/stateless/state.go
ethdb/remote/bolt_remote.go
ethdb/remote/bolt_remote_test.go
node/node.go
node/service.go

- #211 
- added context into `remote.NewDB`. Need to discuss - maybe move it out and check `<-ctx.Done()` in user's code (in for loop of `cursor.Next`). Because if we calling `remote.NewDB` from HTTP Handler - then we can't pass request ctx (it will close after current request finish) to `remote.NewDB` (we wan't reuse DB connection). 
- cancel context on interruption signal
- `./cmd/state stateGrowth` with batch size 100K take 20min. Current implementation spend most of time in network read/write.

/cmd/state stateGrowth

---

cmd/state/stateless/state.go
ethdb/remote/bolt_remote.go
ethdb/remote/remote_bolt_db.go

Next implementation does break some static analysis of Goland:
If remove `err != nil` from loop definition - warning disapear. 
Must we think about it as about static analyzer bug? 
I reported issue here: https://youtrack.jetbrains.com/issue/GO-7976
```go
func scan(keyPrefix []byte, limit int) ([]KV, error) {
tx, err := client.Begin(context.TODO())
if err != nil {
return nil, err
}
it, err := tx.Iter(context.TODO(), key.Key(keyPrefix), nil)
if err != nil {
return nil, err
}
defer it.Close()
var ret []KV
for it.Valid() && limit > 0 {
ret = append(ret, KV{K: it.Key()[:], V: it.Value()[:]})
limit--
it.Next(context.TODO())
}
return ret, nil
}
```
```go
ri := kv.NewRangeIterator(sc.execCfg.DistSender)
for ri.Seek(ctx, tableSpan.Key, kv.Ascending); ; ri.Next(ctx) {
if !ri.Valid() {
return …
```

return error from .First() and .Next() methods of RemoteDb

---

cmd/state/commands/gas_limits.go
cmd/state/commands/root.go
cmd/state/commands/state_growth.go
cmd/state/stateless/state.go
cmd/state/stateless/transaction_stats.go
common/typedtree/radix.go
ethdb/remote/bolt_remote.go
ethdb/remote/bolt_remote_test.go
go.mod
go.sum

- Analytics client eating too much memory (store buckets data in maps)
- Analytics server eating too much memory (long read transaction holding Bolt pages from GC)
- Analytic steps taking a long time, but can't interrupt it and then continue from last position
- use radix tree to reduce memory usage of analytics client
- add .FirstKey() and .NextKey() methods which don't transfer values by network
- `save/restore` of analytics progress - can start from last saved position (by cbor serialization of whole analytic state to file)
- snapshot file name has YY-MM-DD - it means everyday analytics will run from scratch (but I don't clean up old files). 
- Need somehow rollback server read transaction (to avoid server memory growth)

State analytic less memory and checkpoints

---

cmd/state/stateless/stateless.go
cmd/state/stateless/witness_db.go

fixes a out of memory issue when running `state stateless` and storing resolution witnesses to the DB

stateless: flush the partial witnesses DB for every saved witness

---

common/dbutils/composite_keys.go
core/state/database.go
trie/resolver_stateful_cached.go

* skip storage subtree by .Seek() when len(cacheK) <= common.HashLength
* dbutils.RemoveIncarnationFromKey - doesn't do allocation

Optimize resolver cached

---

cmd/hack/hack.go
cmd/state/commands/stateless.go
cmd/state/stateless/stateless.go
cmd/tester/block_generator.go
cmd/tester/interfaces.go
cmd/tester/main.go
cmd/tester/protocol.go
core/state/database.go
eth/backend.go
eth/handler.go
eth/mgr.go
trie/trie_witness.go

Naive implementation of MGR ( https://ethresear.ch/t/merry-go-round-sync/ ) P2P SubProtocol:
```
epoch := tds.GetBlockNr() / 4096
subtree := epoch % 256          // define first byte
for i := 0; i < 256; i++ {     // define second byte and spread witness of each 2-bytes subtree
prefix := []byte{byte(subtree), byte(i)}
witness, err := tds.ExtractWitnessForPrefix(prefix)
p2p.Send(p.rw, MGRWitness, witness,)
}
```
Also in PR: 
- [Stateless] Make `./cmd/state stateless` cancelable 
- [Tester] Move ForkGenerator to core.GenerateChain
- [Tester] Add basic support of MGR

Naive implementation of MGR P2P SubProtocol

---

cmd/state/stateless/stateless.go

don't pass common ctx to commit block, to avoid cancelation in the middle of commit

don't pass common ctx to blochain.Commit

---

cmd/tester/block_generator.go
cmd/tester/interfaces.go
cmd/tester/main.go
cmd/tester/protocol.go

Problem: forkFilter variable are catched by goroutine when peer connected (not when status msg received) - it means to change it tester must reconnect.
See: https://github.com/ledgerwatch/turbo-geth/blob/master/eth/peer.go#L600

Tester: to reconnect after new genesis setup

---

core/state/database.go
core/state/database_test.go
trie/hashbuilder.go
trie/node.go
trie/resolver_stateful.go
trie/trie.go
trie/trie_transform.go

Support `ReadAccountCodeSize` operation natively w/o caching the whole code in the trie.

Code size in account nodes

---

cmd/utils/flags.go

They tries to initialized the pruner but the configuration was incorrect.
This commit disabled the pruner completely.

Fix `geth export` and other auxiliary commands.

---

cmd/state/commands/stateless.go
cmd/state/stateless/stateless.go
cmd/state/stateless/stateless_block_providers.go

fixes: #445
replaces `--chaindata=<path-to-boltdb>` parameter with a more flexible `--blockSource` that can take 3 types of arguments:
- `exportfile:///path/to/exportfile` -- use a `geth export` result instead of chaindata
- `db:///path/to/db` -- use a "normal" chaindata
- `/path/to/db/` -- use a "normal" chaindata

Use `geth export` generated files in the stateless prototype

---

.buildkite/hooks/pre-command
.buildkite/pipeline.yml
nightly.sh

Adds a script to run turbo-geth sync for 5 hours every night.
The job is: https://buildkite.com/ledgerwatch/nightly-tests

Nightly tests

---

internal/debug/flags.go

Fixes the issue that causes a panic when starting `state` command.
```
> go run ./cmd/state verifySnapshot
panic: expect file.go:234
```

Handle empty backtrace parameter gracefully

---

cmd/state/commands/gas_limits.go
cmd/state/commands/state_growth.go
cmd/state/commands/stateless.go
cmd/state/commands/verify_snapshot.go
cmd/state/stateless/state_snapshot.go

Also remove unnecessary arguments from the stateless prototype sub-commands.

Don't use `chaindata` where we don't need it.

---

cmd/prometheus/docker-compose.yml
cmd/prometheus/prometheus.yml
ethdb/kv_abstract_test.go
ethdb/remote/bolt_remote.go
internal/debug/flags.go
metrics/exp/exp.go

Now: `--metrics` doesn't depend on `--pprof`

Metrics server without pprof

---

.gitignore
cmd/state/stateless/stateless.go
cmd/state/stateless/stateless_block_providers.go

Block 76328 accesses the header from the block 76327. This access failed because the `ChainContext` that was provided to `ApplyTransaction` was based on `statedb` that didn't yet have this information.
I implemented `ChainContext` interface for `BlockProviders` because they always have this info. For the export file, I also had to make a temp database to store them.

Fix hash mismatch at block 76328

---

eth/downloader/stagedsync_downloader.go
eth/downloader/stagedsync_stage_execute.go
eth/downloader/stagedsync_stage_hashcheck.go
eth/downloader/stagedsync_stages.go

After we executed blocks until N, we build the root hash of the current state and compare it to the block root hash, stored in the header.
That way, we are ensuring that everything was executed correctly. It is very unlikely that we can get the same root hash for the trie at the block N, but with a different path.

Staged Sync: check trie root hash stage

---

cmd/state/stateless/stateless.go
cmd/state/stateless/stateless_block_providers.go

fixes #489
As I figured out, we don't store blocks in the state snapshot, only the current state.
Now we get pre-root from the block provider.
NB! if you use an export file, there still can be issues due to the fact that the headers database is re-created every time.

Issue 489 stateless prototype resume

---

core/types/transaction_signing.go
crypto/secp256k1/secp256.go
crypto/signature_cgo.go
eth/downloader/stagedsync_state_senders.go
ethclient/signer.go

an attempt to fix a bottleneck when `secp256k1_context` was shared between goroutines, possibly making the procedure "less parallel" than we would like too

Parallel signature verification

---

core/vm/instructions.go

There are a lot of contracts on the Ethereum mainnet that were compiled with Solidity prior to the shifting operations were available. For those, exponentiation 2^160 is used to emulate 1<<160. Measurements performed on turbo-geth confirm this

Shortcut for 2^e

---

cmd/prometheus/dashboards/turbo_geth.json
metrics/metrics.go

Grafana dashboard to support multiple-turbo-geth-insances
add goroutines and threads chart

Grafana dashboard: show multiple TurboGeth instances at same time chart

---

core/state/intermediate_hashes.go
trie/trie.go

- parent node type - doesn't matter for IH - just check that node itself is fullNode or duoNode is enough (I introduced this check very long time ago, I think it "hided" some bug in resolver - after removal always had problems with resolving, but now looks like it works)
- in unloading - 64 nibbles - it's hex of a.storage, but not a - then 64 nibbles hex must be stored in IH with incarnation
- EmptyRoot can't come to `WillUnloadBranchNode` method - because if account has no storage - then accountNode will have no branches in a.storage, a.storage will equal to `hashNode(EmptyRoot)` - and we don't unload hashNodes (only fullNode/duoNode). 
- I wonder if next assertion needed?
```go
if len(prefixAsNibbles) == 64 && nodeHash == trie.EmptyRoot {
panic("unexpected input of WillUnloadBranchNode …
```

IH: don't check parent type and avoid store EmptyRoot

---

cmd/hack/hack.go
trie/resolver_stateful.go

This change replaces loops with `cursor.Next()` with calls to `cursor.SeekTo` that would allow the resolver to skip over large ranges of deleted storage items efficiently

Optimise resolver

---

cmd/pics/state.go
core/state/database.go
trie/flatdb_sub_trie_loader.go
trie/stream.go
trie/sub_trie_loader.go

Just a first step. Here, the processing is moved from automated transactions `bolt.DB.View(func(tx *bolt.Tx) error {...})` to manual transaction `tx := bolt.DB.Begin(false);....;tx.Rollback()`, which allows the introduction of an iterator, at a cost of the risk of not closing the transaction and causing the deadlock in the system (which will hopefully be apparent very quickly).

Start transforming SubTrieLoader into iterator/stream

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
common/changeset/account_changeset.go
common/changeset/account_changeset_test.go
common/changeset/account_changeset_utils.go
common/changeset/storage_changeset.go
common/changeset/storage_changeset_test.go
common/changeset/storage_changeset_utils.go
common/dbutils/bucket.go
common/dbutils/composite_keys.go
common/dbutils/composite_keys_test.go
core/blockchain.go
core/rawdb/accessors_account.go
core/state/change_set_writer.go
core/state/database.go
core/state/db_state_reader.go
core/state/db_state_writer.go
core/state/intra_block_state.go
core/state/plain_state_reader.go
core/state/plain_state_writer.go
core/state/readonly.go
core/state/stateless.go
core/state/util.go
eth/downloader/stagedsync_downloader.go
eth/downloader/stagedsync_stage_execute.go
ethdb/walk.go

**NB! this PR will break the hash check phase, I disabled it intentionally.**
Basically, staged sync right now writes to a separate set of buckets, that have "plain" state.
Instead of `<address-hash> => <account-data>` they have `<address> => <account-data>`.
The same is true for the composite keys in storage and in changesets.
Next steps: 
- chain rollback
- to generate "hashed" (default) state to be able to check root hashes. 
- to take intermediate hashes into account.

Staged Sync: Execution phase should use "plain state"

---

eth/downloader/stagedsync_stage_senders.go

Dankrad is trying to use staged sync to prototype for polynomial commitments, but he gets this all the time:
````
INFO [05-14|18:09:06.461] Recovered for blocks:                    blockNumber=4820001
INFO [05-14|18:10:41.206] Recovered for blocks:                    blockNumber=4830001
INFO [05-14|18:12:05.953] Recovered for blocks:                    blockNumber=4840001
Killed
````
This PR caps number of utilised CPUs to 3, I asked Dankrad to test on this branch.
We do not see more than 3x improvement even if we use 8 CPUs

Staged sync: Cap number of go routines to 3 for recovery stage

---

core/generate_index.go
ethdb/bolt_db.go
ethdb/mutation.go

Proplem statement: current mutation.MultiPut do sort entities by keys - it means entries with different buckets are mixing and underlying BoltDatabase.MultiPut does call bolt.MultiPut on same bucket multiple times with small amoount of keys during 1 transaction.

sort buckets then sort keys inside buckets, then send data to MultiPut

---

common/math/integer.go
core/vm/instructions.go

the compiler optimises away math.bits

Use math.bits in common math Safe* for performance

---

cmd/geth/main.go
core/blockchain.go
core/state/db_state_reader.go
core/state/db_state_writer.go
eth/downloader/stagedsync_stage_execute.go
ethdb/bolt_db.go
ethdb/mutation.go
ethdb/mutation_puts.go

Entries in the `accountCache` were preventing GC from freeing state objects and it caused memory leak. Also, large bytecodes are now not placed into the codeCache

Remove memory leak caused by accountCache, count batch size in bytes

---

cmd/hack/hack.go
core/state/db_state_reader.go
core/state/db_state_writer.go
core/state/plain_state_reader.go
core/state/plain_state_writer.go
eth/downloader/stagedsync_stage_execute.go

The problem was that `codeCache` was not cleared when account was deleted. Also, old storage was visible through the `storageCache`.
Also changed LRU cache to fastcache, because it allows keys that are byte slices (instead of arrays), and you can specify maximum size if bytes, not in number of objects.

Fix staged sync issue introduced by LRU caches

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/stagedsync_test.go

This brings the granularity of possible termination from between chain segments (which could take a long time to get imported) to individual blocks

Stop blockchain when terminating downloader

---

common/dbutils/bucket.go
core/genesis.go
core/state/database.go
core/state/db_state_reader.go
core/state/db_state_writer.go
core/state/plain_state_reader.go
core/state/plain_state_writer.go
core/state/readonly.go
core/vm/gas_table_test.go
eth/downloader/stagedsync_stage_execute.go
eth/downloader/stagedsync_stage_execute_test.go
ethdb/walk.go

When pruning stage is implemented, the incarnation map can be pruned after all the storage records with expired incarnations are pruned away
Closes https://github.com/ledgerwatch/turbo-geth/issues/560

Explicit incarnation map in the database for deleted contracts

---

.circleci/config.yml

CircleCI will fail if `go mod tidy` results differs from what is commited in the branch.

Enforce go mod tidy

---

ethdb/kv_badger.go
trie/flatdb_sub_trie_loader.go

- badger-compatible trie loader (key and value in badger iterator valid only until .Next/.Seek call)
- disable badger compaction for in-mem mode
- fixed bug in kv_badger:Put method: did pass buffer `c.prefix` to `badger.Set` method
- kv_badger to return key=[]byte instead of nil when err!=nil. It's about following next api definition in AbstractKV.md: 
Methods .First, .Next, .Seek - can return error. If err!=nil then key SHOULD be !=nil (can be []byte{} for example). Then looping code will look as: 
```go
for k, v, err := c.First(); k != nil; k, v, err = c.Next() {
if err != nil {
return err
}
// logic
}
```

badger-compatible trie loader

---

accounts/abi/bind/backends/simulated.go

- simulated backend - replace .MemCopy by .NewBatch and native transactions
- close database which created inside the simulated backend
- it significantly increases the speed of the simulated backend

simulated backend: replace .MemCopy by .NewBatch+.Commit

---

.golangci/step1.yml

To silent advises like: `method ChainId should be ChainID (golint)`
because go-ethereum doesn't follow it (will harder to merge)

increase golint confidence level to reduce renaming advises

---

Makefile
cmd/hack/hack.go
common/dbutils/bucket.go
ethdb/badger_db.go
ethdb/kv_badger.go
ethdb/kv_bolt.go
ethdb/kv_lmdb.go
ethdb/kv_remote.go
ethdb/object_db.go
go.mod
go.sum

Lmdb internal objects reuse (built-in feature of lmdb):
- lmdb read transactions pool
- lmdb pool of cursors (of read transactions)
And kv abstraction objects reuse: 
- lmdbKV pools of all tx and cursor objects
- boltKV pools of all tx  and cursor objects
- badgerKV pools of all tx  and cursor objects

KV: Tx objects pool 

---

.golangci/step1.yml
.golangci/step2.yml
.golangci/step3.yml
.golangci/step4.yml
cmd/state/stateless/stateless.go

- Enable golint but hide recommendations of changing `Db` to `DB`
- Add new linter which checks that used `errors.Is` instead of direct `==` of errors
- Remove `megacheck` because enable all sub-linters which it has
- Don't run `gosec` and `unused` linters on test files

Enable golint back but with conditions

---

cmd/hack/hack.go
eth/stagedsync/stage.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_execute_test.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stagedsync.go
eth/stagedsync/stages/stages.go
eth/stagedsync/state.go
eth/stagedsync/state_test.go
eth/stagedsync/unwind.go
eth/stagedsync/unwind_test.go

use `s.UpdateWithStageData(db, <block number>, <key>)` to store the key
use `s.StageData` with `etl.NextKey` to restart ETL from where it was interrupted.

stagedsync: allow long stages/unwinds to be interrupted

---

ethdb/kv_lmdb.go
go.mod
go.sum

Downgrade lmdb to version of 2019, which is compatible with https://github.com/jnwatson/py-lmdb (lmdb of 2020 year version - upgaded lock file version from 1 to 2 - and python binding can't open database if lockfile exists - if main app is running).

Use same lmdb version as in python bindings: version of 2019 year

---

cmd/state/stateless/stateless_block_providers.go

Some of the recent updates broke using the export file as a source for the stateless prototype. This commit fixes it.

Fix broken export file usage.

---

common/dbutils/helper.go
trie/flatdb_sub_trie_loader.go

- do seek only when the cursor is behind the target. (just check prefix is not correct).
- `common.NextSubtrie` - didn't make prefixes shorter on overflow, it prevented usage of short IH (which gives the biggest state-jumps). The rationale is: in tries after 11ff goes 12, but not 1200. 
Result: 100x less Seek calls (not the same gain in speed, but much less friction).

Loader speed: do seek only when cursor is behind, NextSubtrie must produce shorter prefixes on overflow

---

eth/stagedsync/stage_interhashes.go
trie/flatdb_sub_trie_loader.go

Main bottleneck now is the amount of c.Next calls (on retain list of 1K items I see millions of .Next calls). 
- Reduced 100x amount of c.Next calls by removing next part: https://github.com/ledgerwatch/turbo-geth/compare/skip_too_much_ih?expand=1#diff-c75c86eeedd7661f1a471993b71b8774L419  - this logic is correct for `c` cursor, but not applicable for `ih` cursor. If `ih` cursor after jump to short prefix returns long `ihK` - it's still valid and can be used - no reason of jump to a next account. 
- Another minor improvement - reduce the amount of `.SeekTo` calls: funcion `keyIsBefore` returns true if keys are equal, but if keys are equal - no reason to call `.SeekTo`. Introduced function `keyIsBeforeOrEqual` and distinguish from `keyIsBefore`. 
Timings:
- Unwind of 1 block (300 items in …

Reduce amount of c.Next calls in loader

---

common/etl/buffers.go
eth/stagedsync/stage_interhashes.go

I have inserted the de-duplication logic in the `storageLoad` (the same one as I put in the `accountLoad` earlier). But I do not know still why duplicates appear in the first place

Fix loader crash (kludge)

---

cmd/integration/flags.go
cmd/integration/main.go
cmd/integration/sync_by_small_steps.go
cmd/tester/main.go
common/chan.go
common/etl/etl.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_interhashes.go

We need to run integration(acceptance) tests. For example "run genesis sync in 1 hop" or "run genesis sync with multiple unwind/rewind steps and with multiple integrity checks on each step". Such tests may take a few days. Here is a basic place to put them (to help `hack.go` deal with depression).
Exapmples: 
`go run ./cmd/integration -h` 
`go run ./cmd/integration sync_by_small_steps -h`
`go run ./cmd/integration sync_by_small_steps  --blocks_per_step=10 --chaindata=... --verbosity=2`
Added test: 
- Staged sync in mode '1 step back 2 steps forward' with integrity checks after each step
- For Exec and IH stages only for now

Command for long and heavy integration tests

---

cmd/hack/hack.go
cmd/integration/flags.go
cmd/integration/reset_state.go
cmd/integration/state_stages.go
cmd/integration/sync_by_small_steps.go
common/etl/collector.go
common/etl/etl.go
core/generate_index.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_indexes.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stagedsync.go
ethdb/kv_lmdb.go

```
go run ./cmd/integration reset --chaindata=...
go run ./cmd/integration state_stages -h
go run ./cmd/integration state_stages  --chaindata=... --verbosity=3 --block=2_000_000 --unwind=10 --unwind_every=1_000 
```
Also, it inherits flags from geth:
```
--pprof.cpuprofile=./cpu.out   // to file
--pprof --pprof.port=6060     // launch pprof server
--metrics                  //  sends to prometheus 
```

Integration tests2

---

core/state/database.go
core/state/stateless.go
trie/gen_struct_step.go
trie/hashbuilder.go
trie/trie_from_witness.go
trie/witness_builder.go
trie/witness_operators.go
trie/witness_operators_test.go
trie/witness_test.go

Fix 1: Retain List for witness generation should have no incarnations.
Fix 2: EXTCODESIZE should be supported even when there is no code in the witness.

Fix broken witness generation due to EXTCODESIZE

---

cmd/integration/stages.go
cmd/integration/state_stages.go
eth/backend.go

set default configs, jumpdest cache of same size
but still `ethash.NewFaker()`

integration test - to use same blockchain config as production

---

cmd/integration/commands/flags.go
cmd/integration/commands/refetence_db.go
cmd/integration/commands/reset_state.go
cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
cmd/integration/main.go

Problem:
Init func runs only for main.go
Before:
```
go run ./cmd/integration/main.go --help
long and heavy integration tests for turbo-geth
```
After:
```
go run cmd/integration/main.go --help
long and heavy integration tests for turbo-geth
Usage:
integration [command]
Available Commands:
compare_bucket compare bucket to the same bucket in '--reference_chaindata'
compare_states compare state buckets to buckets in '--reference_chaindata'
help           Help about any command
print_stages   
...
```

Ability to use go run for cmd/integration

---

cmd/integration/commands/state_stages.go

now it doesn't do last cycle if it smaller than `--unwind_every`

Integration: stop exactly on "--block"

---

eth/stagedsync/stage_interhashes.go

I got this
```
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1428fc9, 0x16)
/snap/go/current/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xcd08000000, 0x2cc000000, 0x2475c78)
/snap/go/current/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x245ff20, 0x2ca000000, 0x245ff28, 0x165000)
/snap/go/current/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x245ff20, 0x165000, 0x0)
/snap/go/current/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x245ff20, 0x165000, 0x7ffd78ed0000, 0x2475c88, 0x17)
/snap/go/current/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
/snap/go/current/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x245ff20, 0x165000, 0x100, 0x168c638)
/snap/go/current/src/runtime/mheap.go:865 +0x81 …
```

Release map keys and values on stage4

---

eth/downloader/downloader_test.go
eth/downloader/testchain_test.go
ethdb/kv_lmdb.go

Found problem with memory in tests: 
`eth/downloader/downloader_test.go` in init method reduce some big constants to use less memory, but `eth/downloader/testchain_test.go` reading constants values before `init` method run. 
Fixed and reduced lmdb in-mem limit from 64mb to 32mb.

Ci lmdb - reduce memory usage 

---

cmd/prometheus/dashboards/turbo_geth.json
core/blockchain.go
eth/stagedsync/stage_execute.go
ethdb/mutation.go
ethdb/object_db.go

- block execution timer
- db commit/get/put timers
- drop bolt and leveldb charts
- drop trie charts

Prometheus dashboard revisit

---

cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
eth/downloader/downloader.go
eth/stagedsync/stage.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stage_txpool.go
eth/stagedsync/stagedsync.go
eth/stagedsync/state.go
eth/stagedsync/state_test.go
eth/stagedsync/types.go
eth/stagedsync/unwind.go

- after "runInterruptedStage" we set state.CurrentStage to 0. It runs exec, then stage5 (but now it expecting that stage6 was run on previous iteration. 
Remove concepts 'interrupted stage' and 'partially executed stage' - persistent unwind stack must be enough

fix stage5 interruption

---

cmd/state/generate/regenerate_index.go
core/generate_index.go
core/generate_index_test.go
eth/stagedsync/stage_indexes.go

All temp files for all stages are supposed to be in the datadir. Indexes generation had a bug where it used the actual temp dir and that could unexpectedly fill the whole partition, especially if someone syncs on the external drives.

Use datadir for temp files when generating indexes

---

README.md
docker-compose.yml

As of feedback gotten here: https://github.com/ledgerwatch/turbo-geth/issues/832#issuecomment-667532694
- Disable ipc RPC
- Make Readme less confusing - people thought points are depend on each-other (for example need to build restapi before build docker).

Disable ipc RPC

---

cmd/geth/main.go
eth/stagedsync/stage_execute.go

Remove unnecessary memory profiling

---

eth/stagedsync/stage_senders.go

because lmdb also does lock thread and maybe we got conflict. related to https://github.com/ledgerwatch/turbo-geth/issues/885

don't lock thread in stage3

---

eth/stagedsync/stage_interhashes.go

We removed "interrupted stage" concept - and now after TG restart - it starts from stage 0. 
But if interrupt HashState stage - then on start IHashes stage will show "root hash not match". 
I propose next fix: 
- IHashes will check if "progress of IHashes">="progress of HashState" - if not match, then noop.
- HashState will propagate to InterHashes stage, not to Exec stage.
- yes, HashState reading data from plainstate (which is on progress of Exec stage). But it's fine, just to handle special case. 
Example: Exec=9, IHashes=9, HashState=9, next iteration, Exec->10, IHashes->10, HashState=9 (interrupted during promotion to 10), next iteration, Exec->11, IHashes=10 noop, HashState=9 (again interrupted during promotion to 10, why not :slight_smile: ), next iteration, Exec->12, IHashes=10 …

recover_from_hashstate_stage_interruption

---

cmd/hack/hack.go
cmd/state/py/dbutils.py
cmd/state/py/main.py
cmd/utils/flags.go
common/dbutils/bucket.go
common/debug/experiments.go
ethdb/kv_lmdb.go
migrations/dupsort_hash_state.go
migrations/dupsort_hash_state_test.go
migrations/migrations.go

**Main idea:**
CurrentStateBucket layout which utilises DupSort feature of LMDB (store multiple values inside 1 key).
LMDB stores multiple values of 1 key in B+ tree (as keys which have no values).
It allows do Seek by values and other features of LMDB.
You can think about it as Sub-Database which doesn't store any values.
```
-------------------------------------------------------------
key              |            value
-------------------------------------------------------------
[acc_hash]              | [acc_value]
[acc_hash]+[inc]        | [storage1_hash]+[storage1_value]
| [storage2_hash]+[storage2_value] // this value has no own key. it's 2nd value of [acc_hash]+[inc] key.
| [storage3_hash]+[storage3_value]
| ...
[acc_hash]+[old_inc]    | [storage1_hash]+[storage1_value]
| ... …
```

DupSort of hash state

---

cmd/utils/flags.go

```
INFO [08-15|09:42:25.316] Allocated trie memory caches             clean=1.60GiB dirty=0.00B
INFO [08-15|09:42:25.316] Opening Database (LMDB)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10063dd]
github.com/ledgerwatch/turbo-geth/cmd/utils.RegisterEthService.func1(0xc000220900, 0xc0002cf530, 0xc0004ab998, 0xc0001a5800, 0x2)
github.com/ledgerwatch/turbo-geth@/cmd/utils/flags.go:1733 +0x4d
github.com/ledgerwatch/turbo-geth/node.(*Node).Start(0xc0000e3680, 0x0, 0x0)
github.com/ledgerwatch/turbo-geth@/node/node.go:209 +0x407
github.com/ledgerwatch/turbo-geth/cmd/utils.StartNode(0xc0000e3680)
github.com/ledgerwatch/turbo-geth@/cmd/utils/cmd.go:69 +0x2f …
```

fix RegisterEthService nil panic

---

cmd/integration/commands/stages.go
cmd/utils/flags.go
core/generate_index.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/stagedsync.go
eth/stagedsync/state.go

Main ideas:
- IH stage must only validate that state is correct - it must not use any hacks to override state (for example accountsMap or code hash adjust) - because it means that we store in db invalid state.
- But it means that during unwind HashState stage must go before IH, it's fine - I added to `state.unwindOrder`.
- All tweaks moved into HashState stage (it's extract part)
- IH Receiver removed
Future steps: 
- After merge of https://github.com/ledgerwatch/turbo-geth/pull/918 - I wanna try - use transaction to delete IH which now hidden by RetainList and if hashRoot match - commit all changes at once.

Swap IH and HashState stages

---

common/etl/buffers.go
common/etl/collector.go
common/etl/etl.go
common/etl/etl_test.go
core/state/db_state_writer.go
core/state/history_test.go
eth/stagedsync/stage_execute.go
ethdb/interface.go
ethdb/kv_lmdb.go
ethdb/mutation.go
ethdb/object_db.go
ethdb/tx_db.go
trie/flatdb_sub_trie_loader.go

- etl.loadFilesIntoBucket - does load in single transaction without mutation.go
- ethdb.ObjectDb.MultiPut - does logging progress of .Put calls every 30 sec
- "Batch committed" log message did show time of .Put calls + .Commit call. Now it shows only timing of commit (show log message only if commit took longer than 10sec). 
- some buffers are set to nil to release underlying memory pointers https://github.com/ledgerwatch/turbo-geth/pull/919
- Separate `commit` and `fsync` (see kv_lmdb.go `env.Sync(force=true)`) - it allow write logs to console more often on slow devices
- Can increase kv_lmdb.IdealBatchSize
- Interesting effect: bigger mutation size reducing commit time - probably because OS starts flushing to disk while we calling .Put and when we call .Commit already not much left to …

lmdb transactions of unlimited size

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/net.go
cmd/rpcdaemon/commands/net_version.go

Extract `net` API as a service
closes #923

Net api as a service

---

common/etl/collector.go
common/etl/etl.go
common/etl/progress.go

based on the first byte of the key. [0...F] -> [0%...49%].
for loading we just add 50% to that.
we also centralize this progress printing

Print approximate progress for ETL stages

---

eth/stagedsync/stage_execute.go
ethdb/interface.go
ethdb/kv_lmdb.go
ethdb/mutation.go
ethdb/object_db.go
ethdb/tx_db.go

- Usage of TxDb means don't open read transaction every time you wanna read something from db. 
- On fast disk it speeding genesis sync 21hour -> 17hours
- But it a bit increases complexity of stage_exec - now there is db.Begin, then tx.NewBatch, then both of them need periodical commit
- I need your advise - maybe we can simplify code somehow?

[to discuss] exec blocks without ObjectDb: Mutation over TxDb

---

common/dbutils/bucket.go
ethdb/kv_abstract.go
ethdb/kv_abstract_test.go
ethdb/kv_bolt.go
ethdb/kv_lmdb.go
ethdb/kv_migrator_test.go
ethdb/kv_remote.go
go.mod
go.sum

Now I use global variables in file bucket.go to store list of buckets and their configs.
But now guys working on adding SnapshotDb - which need separated list of buckets and maybe configs will not match. 
This PR is refactoring to use bucket.go only as a Defaults settings, but defaults can be replaced before db open. 
Also defaults are immutable now.

KV: to support multiple databases and multiple set of buckets

---

eth/downloader/downloader_stagedsync.go
eth/downloader/downloader_stagedsync_test.go
eth/handler.go
eth/stagedsync/prefetched_blocks.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stagedsync.go
eth/stagedsync/types.go

When there is a broadcast about a new block, we add this to a fixed-size `lru` cache, so it could be used on stage 3.
It is a very simple and naive implementation and affects only block bodies at the moment.
It also does not affect the case when the block body is broadcasted before it is actually downloaded that might be fixed in the following PRs.

Prefetch block bodies

---

cmd/integration/commands/reset_state.go
core/state/plain_state_writer.go
eth/stagedsync/stage_execute.go
eth/stagedsync/testutil.go
ethdb/interface.go
ethdb/mutation.go
ethdb/object_db.go

I think we might have introduced performance regression by switching `Append` to `Put` for changesets and Receipts. This is to test if we did

Use Append for changesets and receipts

---

docs/programmers_guide/indices.md
ethdb/kv_lmdb.go

Just found that Next and First methods work as expected with with DupSort buckets, so, I just removed additional logic

simplify cursor.Next and cursor.First implementation

---

docker-compose.yml
turbo/node/node.go

As @AskAlexSharov noticed, we are missing the `--nousb` flag.
Since we aren't going to (so far) integrate with hardware wallets directly (maybe through Clef only or something), I hardcoded it always to be `true` in the node config.
Also, removed this flag from docker-compose.yml.

Fix `nousb` flag missing.

---

turbo/cli/default_flags.go

@MysticRyuujin uses it to be able to see which nodes are connected to which.
It looks like it doesn't need any extra treatment, so I'm adding it back to `DefaultFlags`

Restore `--identity` flag

---

README.md
cmd/rpcdaemon/commands/eth_api.go

Fixes #1073, plus I made a slight refactor to `eth_getTransactionByHash` to use code from `./internal/ethapi/api.go`.
I also added support for `eth_getTransactionByBlockHashAndIndex` since it was so similar.
My first PR to a golang repo, so I'd greatly appreciate any feedback.
Looking for advice on how to add testing...

1073 eth get transaction by block number and index

---

turbo/cli/default_flags.go
turbo/node/node.go

we don't seem to use it at all, so I will disable it and remove according flags (currently these flags have no effect since commit 07ca5c643adc051cb30d744ca10238f90295878d)

Disable IPC and remove flags for it

---

Makefile
cmd/tg/main.go
turbo/node/node.go

When making `turbo-api` I broke reproducible builds by passing the date on compile time. This commit fixes that.

Fix reproducible builds

---

turbo/rpchelper/helper.go

I ran this
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4", "0x0"],"id":64}' -H "Content-Type: application/json" localhost:8545
```
against all the pre-fund addresses and it now returns the same amounts as Parity for all the prefund acounts.
Fixes #1103

Fixes issue #1103

---

cmd/rpcdaemon/commands/eth_api.go

Sorry for the double PR. I found that the code I pushed the other day returned incorrectly for non-contract accounts. This corrects it and fixes #1070.

Corrects incorrect return from eth_getCode for non-contract accounts

---

cmd/state/stateless/check_change_sets.go
cmd/state/stateless/stateless.go

runBlock was creating a new vm.Config, ignoring the one passed inside of the core.ChainContext. This made it impossible to set a Tracer in the caller.
(let me know whether it would make more sense to add a basic Tracer to the PR)

Use the passed VMConfig

---

cmd/rpcdaemon/commands/get_receipts.go
common/dbutils/bucket.go
eth/stagedsync/stage_log_index.go
eth/stagedsync/stage_log_index_test.go
ethdb/bitmapdb/dbutils.go
ethdb/bitmapdb/dbutils_test.go
ethdb/kv_abstract.go
ethdb/kv_lmdb.go
ethdb/kv_remote.go
ethdb/remote/remotedbserver/server.go
migrations/dupsort_state.go

Method `writeBitmapSharded` using not optimal algo to split big bitmap to shards - probably need do kind of binary search. 
But it works fast enough, tomorrow will try to improve/simplify it. 
4Kb shard size - increase bucket size 1%.

History-style sharding for bitmap indices 

---

cmd/rpcdaemon/README.md

Just a small README fix since eth_getLogs should now work with `--chaindata`. See https://github.com/ledgerwatch/turbo-geth/issues/1168#issuecomment-702564359 for context.

Update rpcdaemon README

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/get_chain_config.go
cmd/rpcdaemon/commands/get_receipts.go
cmd/rpcdaemon/commands/trace_api.go
cmd/rpcdaemon/commands/trace_api_custom.go
cmd/rpcdaemon/commands/trace_api_filtering.go

rpc daemon will not start if TG not started - which is bad architecture practice - startup must be independent. need find another way to cache - something like sync.Once

Revert "rpcdaemon to cache chainconfig"

---

Dockerfile

Because sometime circleci fails to build: https://app.circleci.com/pipelines/github/ledgerwatch/turbo-geth/8438/workflows/b5dcbe60-376f-4f00-a6cd-ca28c5ca1875/jobs/8773

Dockerfile: stick minor version of alpine

---

cmd/prometheus/prometheus.yml
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/main.go
cmd/rpcdaemon/test.http
cmd/rpctest/Readme.md
cmd/utils/cmd.go
docker-compose.yml
eth/backend.go
ethdb/kv_remote.go
ethdb/remote/remotedbserver/server.go

Fixes:
- Server: GracefulShutdown grpc server
- Client: GracefulShutdown json server (stop accepting new requests, wait for pending request finish or cancel by 5sec timeout) and only when no pending clients left - then close db. 
- Client cursor: 1) If sreaming not requested: do `CloseSend+Recv` as "happy path" and `defer cancelCursorContext` as "unhappy path if send/recv finished with error" 2) if streaming requested - cancelCursorContext
Of course it's a bit stupid that we received "context canceled" instead of "connection closed" error. It making things harder to debug.

Rpcdaemon: Gracefull shutdown, better grpc stream close

---

cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
core/evm.go
eth/downloader/downloader.go
eth/stagedsync/all_stages.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stagebuilder.go
eth/stagedsync/stagedsync.go

While work on MDBX - it returned error: MDBX_TXN_OVERLAPPING: Overlapping read and write transactions for the current thread and I found that deep inside EMV used 1 method blockchain object GetHeader. And blockchain holding another database object from exec stage. 
So, here is replacement for blockchain object for execution stage. 
I suspended MDBX_TXN_OVERLAPPING in `kv_mdbx` branch - it's safe. But I testing it in the corner.

use less blockchain

---

common/etl/collector.go
migrations/dupsort_state.go
migrations/migrations.go
migrations/migrations_test.go
migrations/receipts.go
migrations/receipts_test.go
migrations/stagedsync_to_use_stage_blockhashes.go
migrations/stages_to_use_named_keys.go

- don't clean if panic happened
- don't clean if any error happened
- save progress of stage and use collected files only if progress value is == "load"

Migration idempotency: handle corner-cases of CriticalCollector

---

migrations/migrations.go
migrations/receipts.go

now it using separated folder for tmp files: 
Normal tmp: `/datadir/etl-tmp`
Migrations tmp: `/datadir/some_hand_crafded_folder_name/etl-tmp`
which is hard to mount to separated drive, because name is not predictable. I will change it to:
Migrations tmp: `/datadir/migrations/some_hand_crafded_folder_name/etl-tmp`
And probably need mention somewhere in docs about: that if you wanna place tmp files to separated drive need mont 2 folders `/datadir/etl-tmp` and `/datadir/migrations` - where to write about it?

migrations: make tmp dir name predictable and unique

---

core/skip_analysis.go

There is one new exclusion caused by this:
```
INFO [10-22|08:02:08.473] Checked                                  blocks=11079000
WARN [10-22|08:03:31.434] Code Bitmap used for detecting invalid jump tx=0xcdb5bf0b4b51093e1c994f471921f88623c9d3e1b6aa2782049f53a0048f2b32 block number=11079912
INFO [10-22|08:03:38.983] Checked                                  blocks=11080000
```

[Pending test] Update skip analysis

---

cmd/rpcdaemon/commands/eth_call.go

Fixes #1284
Cause was that, when adapting the old rpc to the new rpcdaemon, `gasCap != 0` was translated to `gasCap != nil`, however gasCap does not come null by default, it cames as a big Int object initialized with zero value. 
The zero gasCap means infinite gasCap. 
This gascaps are added to ensure that public rpc endpoints cannot be broken with infinite loops in the estimategas and call, as they essentially run without block gas limit. 
The fix was simple, just add the check against zero again. I kept the != nil, but might be removed.

Fix infinite rpc.gascap on eth_estimateGas

---

core/vm/evm.go

CallCode, DelegateCall and StaticCall were missing the CaptureStart and CaptureEnd calls, which made it impossible to trace them.

Add the missing CaptureStart and CaptureEnd

---

.dockerignore

before
`Sending build context to Docker daemon  685.6MB`
after
`Sending build context to Docker daemon  41.25MB`
should also speed-up CI

make docker: don't send .git to Docker

---

cmd/state/stateless/check_change_sets.go

**I am not sure of this**, but it looks to me like the batch management should only happen inside of the writeReceipts if?

Move batch management into the writeReceipts case?

---

eth/stagedsync/stage_interhashes.go
turbo/trie/trie_root.go

If you promote sync to stage 2, then unwind to 0, then promote to 4:
- then on second promotion IH bucket will be not clean while retain list empty - it causing hash-root mismatch 
Also removed additional cursor for deletes - because LMDB and MDBX are fixed this problem already.

IH: regenerate must clear IH bucket  

---

cmd/rpcdaemon/README.md

* `eth_subscribe` is supported over WebSocket
* Only `newHeads` is supported at this time
* `eth_unsubscribe` is supported

Update rpcdaemon README with eth_(un)subscribe

---

common/changeset/storage_changeset_test.go
common/etl/collector.go
core/generate_index_test.go
core/state/db_state_writer.go
core/state/plain_state_writer.go
ethdb/interface.go
ethdb/kv_lmdb.go
ethdb/kv_mdbx.go
ethdb/mutation.go
ethdb/object_db.go
ethdb/tx_db.go

Problem 1: only AppendDup used now for dupsort buckets, not Append - as a result pages where keys stored filled not 100%
Problem 2: most of changesets are too small - as a result sub-db's have not much values - page allocated but not filled 100%.

[to discuss] More compact append implementation

---

cmd/snapshots/seeder/commands/root.go
cmd/state/verify/verify_headers_snapshot.go
ethdb/kv_lmdb.go

Related to: https://discord.com/channels/687972960811745322/687972960811745326/795267751803355168
```
INFO [01-03|01:48:24.372] Batch                                    fsync=40.169264829s
INFO [01-03|01:48:24.372] Commit cycle                             in=40.245551376s
INFO [01-03|01:48:24.387] Batch                                    commit=35.216617572s
INFO [01-03|01:48:24.408] Batch                                    fsync=39.218927812s
INFO [01-03|01:48:24.706] Batch                                    fsync=35.535533856s
INFO [01-03|01:48:24.706] Batch                                    fsync=35.535767206s
INFO [01-03|01:48:24.706] Batch                                    fsync=36.738516926s
They are all happened within 1 sec. it means: 1 goroutine of Sync cycles and 5 goroutines …
```

[to discuss] lmdb: move fsync inside commit (to avoid start next write transaction before previous fsync finished)

---

docs/programmers_guide/guide.md
turbo/trie/trie_root.go

The `trie` package was moved under `turbo/` directory, I found there were some broken links in docs.
This PR fixed these broken link with regex replace.
Note: this file was removed from trie `turbo/trie/resolve_set.go`, and the link doesn't work anymore.

Update broken link

---

eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_hashstate_test.go

Closes #1266
Actions:
1.Added quitCh field to NewPromoter to stop HashState stage by pressing CTRL+C.
2. Added tests to test shutdown of promoteHashedStateIncrementally, PromoteHashedStateCleanly and unwindHashStateStageImpl.

Hashstate graceful shutdown

---

go.mod
go.sum

Pull in https://github.com/golang/snappy/pull/56
I experienced a crash on Apple M1:
```
INFO [02-05|15:31:30.077] [1/14 Headers] Imported new block headers count=8040  elapsed=118.406ms number=6512640 hash="381d35…e5de60" age=2y4mo5d
unexpected fault address 0xaa5b45a7af6e024c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xaa5b45a7af6e024c pc=0x1045f7050]
goroutine 30042 [running]:
runtime.throw(0x104c2ff01, 0x5)
runtime/panic.go:1117 +0x54 fp=0x4400c4f0960 sp=0x4400c4f0930 pc=0x1040b9b14
runtime.sigpanic()
runtime/signal_unix.go:741 +0x230 fp=0x4400c4f09a0 sp=0x4400c4f0960 pc=0x1040d1470
github.com/golang/snappy.encodeBlock(0x4400c59e003, 0x1d094, 0x1d094, 0x4400c546000, 0x10000, 0x1fe00, 0x14001674d00) …
```

Update snappy to prevent crash on Apple M1

---

Makefile
common/debug/experiments.go
ethdb/kv_mdbx.go
ethdb/memory_database.go
ethdb/object_db.go

```
DEBUG_BIG_RO_TX_KB - print logs with info about large read-only transactions
DEBUG_BIG_RW_TX_KB - print logs with info about large read-write transactions
DEBUG_SLOW_COMMIT_MS - print logs with commit timing details if commit is slower than this threshold 
```

mdbx: switch CI to mdbx, fix SeekExact, print slow/big transactions info

---

ethdb/interface.go
ethdb/kv_abstract.go
ethdb/kv_lmdb.go
ethdb/kv_mdbx.go
ethdb/kv_remote.go
ethdb/kv_snapshot.go
ethdb/mutation.go
ethdb/object_db.go
ethdb/tx_db.go

This PR prunes KV and other DB interfaces, removing forgotten, superseded and simply unused code. Besides TG itself this is important for porters, as it allows concentrating attention on rewriting code that counts.

Clean up DB interfaces

---

cmd/integration/commands/state_stages.go
core/blockchain.go
core/state/intra_block_state.go
core/state/plain_state_writer.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_mining_create_block.go
eth/stagedsync/stage_mining_exec.go
eth/stagedsync/stage_mining_finish.go
eth/stagedsync/stagebuilder.go

mined in test first 50k blocks

Mining - don't write changesets to batch

---

cmd/integration/commands/state_stages.go
cmd/utils/flags.go
common/debugprint/receipts.go
core/rawdb/accessors_chain.go
eth/stagedsync/stage_mining_create_block.go
eth/stagedsync/stage_mining_exec.go
eth/stagedsync/stage_mining_finish.go

Mining test: set correct header.Timestamp and header.GasLimit

---

cmd/integration/commands/state_stages.go
cmd/utils/flags.go
common/debugprint/receipts.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/ethash/ethash.go
consensus/ethash/ethash_test.go
consensus/ethash/sealer.go
consensus/ethash/sealer_test.go
core/blockchain.go
core/rawdb/accessors_chain.go
core/tx_pool.go
core/types/accounts/account.go
core/types/transaction.go
core/types/transaction_test.go
eth/backend.go
eth/downloader/downloader.go
eth/handler.go
eth/handler_test.go
eth/stagedsync/stage_mining_create_block.go
eth/stagedsync/stage_mining_exec.go
eth/stagedsync/stage_mining_finish.go
eth/stagedsync/stagebuilder.go
eth/sync.go
miner/worker.go
miner/worker_test.go
turbo/adapter/chain_context.go

Rational: 
- TurboGeth is moving towards splitting monolith to components (services). Mining is not part of db-service responsibility. 
- TurboGeth will only prepare blocks: choosing txs from txPool, calculate new state root, add uncles. Then just send work to remote miners.
Details:
- mining loop doesn't wait for remote miners anymore. it accepts `resultCh` and `consesusCtx` as incoming params. then prepare block, send it to consensus engine, that's it.
- Another component (probably new downloader) will need goroutine to manage this: receive result, forward it to sentry, or cancel remote miners work.

Mining: remove local pow mining (from ethash), --miner.notify is required now, cycle is non-blocking now

---

cmd/rpcdaemon/commands/trace_filtering.go

Erroneusly set it to the base block on top of which transactions were executed. I.e. a skew of -1.

trace_block: fix block number in traces

---

consensus/clique/clique.go
consensus/clique/verifier.go

Attempts to fix this
```
INFO [04-22|23:06:43.901] NewBlockMsg{blockNumber: 4666045} from [e15a32beb1b4328a58302899425f3374c855026d0fe266406df317166da2912a]
INFO [04-22|23:06:44.026] database closed (LMDB)                   lmdb=goerli
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4936247]
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).verifyCascadingFieldsBySnapshot(0xc0033e9810, 0x57d5618, 0xc00131d860, 0x5c096f146c0, 0x0, 0x6758038, 0x5c0bd4fbfe0)
github.com/ledgerwatch/turbo-geth/consensus/clique/verifier.go:165 +0x67
github.com/ledgerwatch/turbo-geth/consensus/clique.(*Clique).verifyHeaderBySnapshot(0xc0033e9810, 0x57d5618, 0xc00131d860, 0x5c096f146c0, 0x0, …
```

Clique fixes

---

consensus/clique/clique.go
consensus/clique/snapshot.go
consensus/clique/verifier.go
consensus/ethash/consensus.go
consensus/ethash/ethash.go
eth/handler_eth_test.go
eth/protocols/eth/handshake.go
turbo/snapshotsync/bittorrent/downloader.go

closes https://github.com/ledgerwatch/turbo-geth/issues/1764
1. Reduces batch size for snapshots
2. Fixes storing snapshouts by timer
3. Adds additional logging for errors like "nil snapshot"
Was tested on Aleut and Rinkeby

Clique snapshot timer fixed

---

ethdb/kv_lmdb.go
ethdb/kv_mdbx.go

- problem: every tx.Put/Del op did open cursor and doesn't close. It caused next issue - each cursor was pointed to own dirty page - dirty pages on which pointed cursor can't spill - in result all dirty pages can't spill -> txn_full
- will add cursors counter to grafana later 
- mdbx maintainer anyway plan to handle this corner-case somehow

txn full fix - cursors leak

---

eth/stagedsync/stage_finish.go
eth/stagedsync/stage_indexes.go
eth/stagedsync/stage_txpool.go
eth/stagedsync/stagebuilder.go
eth/stagedsync/state.go

https://github.com/ledgerwatch/turbo-geth/issues/1454 happens because: 
- to unwind staged sync - you need run it forward first. It's make sense, because better finish all unfinished things - only then unwind.
- But most of time it means: run staged sync forward without blocks progress... i mean from block N to block N. 
- Most of stages don't do anything in this case, but TxPool and Finish stages do print some logs. 
- I added progress check to TxPool and Finish stages
- But line `[11/14 CallTraces] disabled. Work In Progress` still here because it's implemented in general-purpose code where we can't check progress. I don't have good Ideas - what to do in this case...

All stages - finish fast if current progress > target

---

Dockerfile

Alpine containers, by default, do not include `tzdata` package, so they do not honor the `TZ` environment variable. When running in a docker container the logs timestamps will always be in UTC without this package. I propose we add `tzdata` so that the timezone can be changed.

Add tzdata to alpine container for log timestamps

---

turbo/stages/headerdownload/header_data_struct.go

To reduce memory footprint of Stage1 which lasts beyond this stage

Reduce persistent link kept

---

README.md
win-build.ps1

* PowerShell script
* Patch Readme.md
The script checks :
* Running with `Administrator` privileges
* chocolatey is installed
* required chocolatey components (`cmake`, `make`, `mingw`) are installed
* GO is installed and >= 1.16
```
PS D:\GitHub\erigon> .\win-build.ps1
Found GO version 1.16.4
Found C:\ProgramData\chocolatey\bin in PATH
Found Chocolatey component cmake 3.20.2
Found Chocolatey component make 4.3
Found Chocolatey component mingw 10.2.0
Building libmdbx.dll ...
-- The C compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for a CXX compiler
-- Looking for a …
```

Windows build automation

---

cmd/headers/commands/sentry.go
cmd/utils/flags.go

In TG we have code: 
```
if ctx.GlobalIsSet(NATFlag.Name) {
p2pcfg.Nat := nat.Parse(ctx.GlobalString(NATFlag.Name))
}
```
This code is controversial because: 
NATFlag default value is "any" (means p2pcfg.Nat is not nil), but this value not used if flag not set (means p2pcfg.Nat is nil) :-)
This RP: changing default value of this flag (and flag in sentry) to match current TG behavior: do not detect nat automatically.

nat settings similar to tg behaviour

---

cmd/utils/flags.go

Cobra CLI - by StringSlice means not comma separated flag, but --flag v1 --flag v2 --flag v3
I will replace by stringFlag+SplitAndTrim

sentry addr comma separate

---

cmd/headers/download/downloader.go
cmd/headers/download/grpc-direct.go
cmd/headers/download/sentry.go
eth/protocols/eth/tx_pool.go

- server to listen stream context
- client to check code.Canceled and don't log it

sentry: better handle grpc errors

---

accounts/abi/bind/backends/simulated.go
cmd/rpcdaemon/commands/erigon_receipts.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/trace_filtering.go
common/dbutils/bucket.go
common/dbutils/composite_keys.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/accessors_indexes.go
core/state/plain_readonly.go
ethdb/kv_abstract.go
ethdb/kv_lmdb.go
ethdb/kv_mdbx.go
ethdb/kv_remote.go
ethdb/kv_snapshot.go
turbo/stages/blockchain_test.go

- do not read blocks twice (in eth_getTransactionReceipt and couple other methods)
- fix some bad docs in bucket.go

simplify receipts reading

---

eth/stagedsync/stage_tevm.go

I think need change logic to next one: 
- call func transpileBatch in loop
- transpileBatch will start new tx if need,new batch, open cursor, commit if need AND return (k,v) where it stopped (when commit happened)
- external func will pass this (k,v) to next call of transpileBatch
This will solve `TODO: This creates stacked up deferrals` and allow remove code when need reopen tx/batch/cursor/etc... 
- external func to call transpileBatch until it returns k==nil
something like:
```
func SpawnStage() {
for lastKey != nil  {
lastKey, lastValue = processBatch(lastKey, lastValue) // start tx, open batch, open cursor, commit tx if need - but doesn't reopen anything
}   
}
func processBatch(k, v []byte) {
useExternalTx := tx != nil
if !useExternalTx {
tx := db.Begin()
defer tx.Rollback()
}
b := …
```

tevm open cursor after commit

---

cmd/integration/commands/stages.go
eth/stagedsync/stage_senders.go

- 1 place didn't check error - it lead to hang 
```
case recoveryErr := <-errCh:
if recoveryErr.err != nil {
if recoveryErr.blockHash == (common.Hash{}) {
return recoveryErr.err
} // here is no "else" - and real error comes here, need stop 
}
```
- add context for goroutines shutdown - cancel this context if any error happen
- use 1 select for all channels to avoid deadlock in `recoverSenders` func - for example if producer failed and no `in` messages until context cancelation 
- integration: senders to use right chainconfig
This PR - is a bit quick fix, but stage_senders needs some love and simplification. 
For example next code looks dangerous: 
```
if minBlockErr != nil {
unwind(minBlockNum-1)
s.Done()
}
tx.Commit()
```
^ error happened, but we only log it and commit transaction. …

Sender stage hangs

---

cmd/integration/commands/root.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_tevm.go
eth/stagedsync/state.go
ethdb/kv/kv_mdbx.go
ethdb/kv/kv_remote.go
ethdb/kv/kv_snapshot.go
ethdb/kv_interface.go
go.mod
go.sum
turbo/node/node.go

- Do log tables size
- db metrics - avoid concurrency - by bound it to RwTx
- check stale reads once an hour (inside CollectMetrics method)
-

Do log tables size, db metrics - avoid concurrency, check stale readers hourly 

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/trace_adhoc.go
core/types/block.go
core/types/transaction_marshalling.go
internal/ethapi/api.go

In EIP 1559, the gas field was renamed.
tip -> maxPriorityFeePerGas
feeCap -> maxFeePerGas
baseFee -> baseFeePerGas
References:
https://github.com/ethereum/go-ethereum/pull/23010
https://github.com/ethereum/go-ethereum/blob/release/1.10/internal/ethapi/api.go#L1201
https://github.com/ethereum/eth1.0-specs/blob/05d6bf480a4e3228cf42b86b044de6832c077b3a/json-rpc/spec.json#L1709

update tx block base fee, tips,fee cap json fields. (eip1559)

---

cmd/rpcdaemon/commands/corner_cases_support_test.go
cmd/rpcdaemon/commands/debug_api_test.go
cmd/rpcdaemon/commands/eth_api_test.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/commands/eth_ming_test.go
cmd/rpcdaemon/commands/send_transaction_test.go
cmd/rpcdaemon/commands/trace_adhoc_test.go
cmd/rpcdaemon/commands/txpool_api_test.go
cmd/rpcdaemon/rpcdaemontest/test_util.go
cmd/sentry/download/broadcast.go
eth/backend.go
eth/protocols/eth/handler_test.go
eth/stagedsync/stagebuilder.go
ethdb/remote/remotedbserver/events.go
turbo/stages/mock_sentry.go
turbo/stages/txpropagate/deprecated.go

- without any optimisation (go-ethereum maintain list of sent hashes, trying to accumulate bigger batches, etc...)
- now it's done as separated goroutine because it's easy, but it's hard to test - will need change it in future 
- Also removed `SendPendingTxsToRpcDaemon` - it's old subscription mechanism of pending txs in rpcdaemon

Propagate new txs to P2P

---

cmd/rpcdaemon/commands/eth_receipts.go

Some projects would like to have effectiveGasPrice in eth_getTransactionReceipt.
So add effectiveGasPrice field to eth_getTransactionReceipt, eth_getBlockReceipts.
https://github.com/ethereum/eth1.0-specs/pull/206
the effectiveGasPrice field:
The actual value per gas deducted from the senders account. Before EIP-1559, this is equal to the transaction's gas price. After, it is equal to baseFeePerGas + min(maxFeePerGas - baseFeePerGas, maxPriorityFeePerGas). Legacy transactions and EIP-2930 transactions are coerced into the EIP-1559 format by setting both maxFeePerGas and maxPriorityFeePerGas as the transaction's gas price.
Refence:
https://notes.ethereum.org/@timbeiko/london-json-rpc
https://github.com/ethereum/eth1.0-specs/pull/206

add effectiveGasPrice field to eth_getTransactionReceipt, eth_getBlockReceipts

---

eth/backend.go
eth/ethconfig/config.go
turbo/cli/default_flags.go
turbo/cli/flags.go

This PR adds a config option for the `blockDownloaderWindow` that is used to set the number of outstanding block body requests in flight, see the comment here:
https://github.com/ledgerwatch/erigon/blob/3d6d45a82f5fbd8b48faf323dbf1099369f539b0/turbo/stages/bodydownload/body_data_struct.go#L38
Any suggestions for renaming the CLI flag name from `blockDownloaderWindow` to something more canonical? All of the other flags are lowercase with dot separations between namespaces besides `batchSize` which is camel case and doesn't have a namespace.
The previous default value is maintained but now it can be lowered without the need to make a diff to the codebase.
Discord conversation here about a user manually setting the value lower which allowed them to sync: …

config: add block downloader window flag

---

Dockerfile

Some container engines such as podman have started to prompt the user to explicitly state (thus sometimes causing service scripts on systemd) to fail for lack of mentioning what container image hub is used. This change declares the hub to be docker.io, thus removing the prompt on systems that use podman.

Docker: explicitly declare base image source

---

eth/backend.go
eth/ethconfig/config.go
turbo/cli/default_flags.go
turbo/cli/flags.go
turbo/stages/stageloop.go

This pull requests adds a cli parameter `--sync.loop.throttle`, which allows us to set minimum time between loop iterations. I.e. If you want to have at least 30 minutes between sync loops, you add `--sync.loop.throttle 30m`. This way, Erigon will not start the next cycle if it happens before an interval of 30 minutes from the start of previous one. The parameter is parsed as a duration.
*Rationale*
I order to decrease the SSD wear and server utilisation I have introduced a throttling mechanism to the syncing process. To ensure more consistent update times the delay between loops is the rest of the minimum time between loop cycles. For instance if we set a 30 minutes minimum loop time, and the previous cycle took 12 minutes, Erigon will wait for another 18 minutes before the start of the …

Add parameter for minimum time between sync loop iterations

---

common/etl/buffers.go
common/etl/collector.go

I discovered it by reducing Buffer size to 1Mb (and event to 128Kb) just for test

ETL: Enforce "oldest appeared" property at load time

---

Makefile
README.md
docker-compose.yml

I found out it's possible to set the PID namespace so that both `erigon` and `rpcdaemon` docker containers share the same namespace. This has the nice side-effect that it's possible to use `--datadir` on both containers with a mounted volume because the mdbx lock is not exclusive anymore. This PR is an experimental workaround for running `rpcdaemon` in dockerized Local-Mode.
I've tested it on Ubuntu 18.04.5 LTS with a USB stick mounted as a volume and passed via `XDG_DATA_HOME` 
I've also changed the default user of the containers to either `$UID_GUID` env or `1000:1000` as default if it's not set so that permissions are properly handled for the volume. 
So far it works pretty stable for me :construction_worker:

Feat: Experimental workaround for dockerized rpcdaemon in Local-Mode

---

Dockerfile
Makefile
README.md
docker-compose.yml

1. I reduced the number of processes visible in both containers to only `erigon` and `rpcdaemon` which is sufficient
2. I created an erigon user in the thorax/erigon image and run all containers with that user for the benefit of consistent data permissions
1. I used the erigon container PID namespace instead of the entire host namespace.
2. After some digging I found out that when the volumes are initially created by docker-compose they will be owned by root which is causing problems in various scenarios. Therefore `make docker-compose` now takes care of creating the initial docker volume sub-directories `erigon`, `erigon-grafana` and `erigon-prometheus`
I've also created a `erigon` user in the Dockerfile and using the same UID:GID combination for the prometheus and grafana containers.
- …

docker-compose with minimal PID namespace and non-root permissions

---

wmake.ps1

* .\wmake.ps1 accepts array of strings (comma separated) to build multiple targets
* .\wmake.ps1 without arguments builds erigon,rpcdaemon by default

Build multiple targets

---

rpc/handler.go

Fixing it just because batch doesn't stream.
But "err after streaming started" problem is unfixable in-general - impossible to return valid json error if we already sent part of successful json to client.

RPC: Fix "err after streaming started" problem for batch

---

core/types/dynamic_fee_tx.go
core/types/legacy_tx.go
eth/gasprice/gasprice.go

Avoid decreasing gasFeeCap at each GetEffectiveGasTip call
Add baseFee if any to suggested gas price (changed in SuggestPrice function because seems easier there)
Fixes #2483

Fix eth_gasPrice in RPCDaemon

---

cmd/rpcdaemon/commands/txpool_api.go
cmd/rpcdaemon/commands/txpool_api_test.go
cmd/sentry/download/broadcast.go
core/tx_pool.go
ethdb/privateapi/txpool.go
go.mod
go.sum
turbo/mock/txpool.go

Changes:
- Implements new gRPC `Txpool.Status()` method
- Adds `txpool_status` JSON-RPC method: https://geth.ethereum.org/docs/rpc/ns-txpool#txpool_status
- Fixes panic in `cmd/sentry/download/broadcast.go` seen while testing
- Minor go.mod update

rpcdaemon: add txpool_status()

---

cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpctest/rpctest/bench_tracefilter.go
cmd/rpctest/rpctest/request_generator.go

This fixes the only remaining nine tests cases from TrueBlocks that were failing against Erigon (compared with OpenEthereum). All related to Erigon not support `trace_filter`'s `after` or `count` options.
I also added test cases to the `rpctest` code.

Fixes issue #2527 and #2526 and adds testing to rpctest

---

Makefile

Allow the location of the golang exectuable to be specified by
Makefile variable.  This can help building in situations where the
default system golang executable is not of sufficient version to build.

build: parameterize location of go executable

---

cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
cmd/rpcdaemon/cli/config.go
cmd/sentry/commands/sentry.go
cmd/state/commands/root.go
cmd/utils/flags.go
node/config.go
node/config_test.go
node/node.go

**** THIS IS A BREAKING PR **** evaluate carefully !
Data paths are "polluted" by erigon's [internal config.name](https://github.com/ledgerwatch/erigon/blob/devel/turbo/node/node.go#L110-L121) which is set to constant "erigon" string
Hence resulting tree is 
```
C:\USERS\ANDREA\APPDATA\LOCAL\ERIGON
├───erigon
│   └───chaindata
└───nodes
├───eth65
└───eth66
```
which depicts a "redundacy" of "erigon" name in the paths (particularly chaindata)
All ancillary binaries (rpcdaemon, integration etc) hardcode "erigon" when building path to chaindata and is quite unlikely node instance name will ever change.
Also ecosystem apps (Silkworm and Akula) are forced to keep that hardcode path.
This pr removes "the pollution" and will make the tree simpler like this
```
├───chaindata
└───nodes
├───eth65 …
```

Remove config.name (const "erigon") from paths

---

cmd/sentry/download/downloader.go
cmd/sentry/download/sentry.go
eth/backend.go
turbo/stages/mock_sentry.go

- clients can't slow down each-other, sentry to work well even if client very slow
- moved sending headers to dedicated stream, because: 1. headers propagation speed important for network health 2. sending bodies and receipts may be slow and it's ok to drop some of this P2P requests if we can't process them, and better don't block headers propagation by this messages

Sentry: clients can't slow down each-other, dedicated stream for sending headers  

---

cmd/rpcdaemon/cli/config.go

To be consistent with the change in https://github.com/ledgerwatch/erigon/commit/e9b2c80529fbaeb54ae369ade61978966eca950e.

rpc: Increase the default gas limit to 50 million

---

docs/mining.md
turbo/cli/default_flags.go

Seems like `--miner.sigkey` has been lost in command-line parsing routines; also the cli argument has been incorrectly referred in `mining.md`.

Expore --miner.sigkey cli parameter

---

cmd/rpcdaemon/commands/erigon_block.go

`{"jsonrpc":"2.0","method":"erigon_getHeaderByNumber","params": ["latest"],"id":0}`
was failing and returning 
`{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"block header not found: -1"}`
and now fetches latest and returns the proper header.

Support for `latest` block in `erigon_getHeaderByNumber`

---

cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/trace_filtering.go
common/hexutil/json.go
core/state/history.go
core/state/history_test.go
core/state/plain_readonly.go
core/vm/instructions.go
core/vm/interpreter.go
ethdb/bitmapdb/dbutils.go
rpc/handler.go
turbo/adapter/reader.go

- trace_filter - don't create intermediate copy of json
- seek in bitmap - don't create iterator
- getAsOf - don't create cursors

RPC: small optimizations

---

cmd/sentry/download/sentry.go

for 
```
Read at 0x00c0002044f0 by goroutine 50:
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).SetStatus()
github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:815 +0x249
github.com/ledgerwatch/erigon-lib/gointerfaces/sentry._Sentry_SetStatus_Handler.func1()
github.com/ledgerwatch/erigon-lib@v0.0.0-20210913043526-b3f03203e43e/gointerfaces/sentry/sentry_grpc.pb.go:283 +0x88
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1()
github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33 +0x144
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e …
```

fix sentry discover race

---

cmd/sentry/download/sentry.go

for 
```
Write at 0x00c0005bc050 by goroutine 119:
github.com/ledgerwatch/erigon/core/forkid.newFilter()
github.com/ledgerwatch/erigon/core/forkid/forkid.go:118 +0x2fb
github.com/ledgerwatch/erigon/core/forkid.NewFilterFromForks()
github.com/ledgerwatch/erigon/core/forkid/forkid.go:92 +0xb3
github.com/ledgerwatch/erigon/cmd/sentry/download.handShake.func2()
github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:174 +0x15c
github.com/ledgerwatch/erigon/cmd/sentry/download.handShake.func3()
github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:228 +0x39
Previous write at 0x00c0005bc050 by goroutine 126:
github.com/ledgerwatch/erigon/core/forkid.newFilter()
github.com/ledgerwatch/erigon/core/forkid/forkid.go:118 +0x2fb …
```

fix sentry forks slice race

---

core/types/dynamic_fee_tx.go

CallBundle in eth_block.go uses
```
firstMsg, err := txs[0].AsMessage(*signer, nil)
```
which was crashing
Maybe this is the wrong fix, but it works.

fix eth_callBundle by allowing nil baseFee in tx serialize

---

core/types/dynamic_fee_tx.go
core/types/transaction_signing.go
core/types/transaction_signing_test.go

I am getting a
```dynamicfee tx is not supported by signer Signer[chainId=1,malleable=false,unprotected=true,protected=true,accesslist=true,dynamicfee=false``` 
error when using erigon as a library in a custom tool when using
```types.LatestSignerForChainID()``` on top of EIP-1559 transaction. Specifically when calling the `signedTx.Sender(*signer)`
This simple fix seems to fix it. Not sure however how it might affect the other users using erigon as a library.

mark support for eip-1559 tx types for most permissive signer

---

cmd/utils/flags.go
go.mod
go.sum
node/config.go
node/node.go
turbo/cli/default_flags.go

meaning: 
```
/** \brief Controls the in-process limit to grow a list of reclaimed/recycled
* page's numbers for finding a sequence of contiguous pages for large data
* items.
*
* \details A long values requires allocation of contiguous database pages.
* To find such sequences, it may be necessary to accumulate very large lists,
* especially when placing very long values (more than a megabyte) in a large
* databases (several tens of gigabytes), which is much expensive in extreme
* cases. This threshold allows you to avoid such costs by allocating new
* pages at the end of the database (with its possible growth on disk),
* instead of further accumulating/reclaiming Garbage Collection records.
*
* On the other hand, too small threshold will lead to unreasonable database
* growth, or/and to …
```

--mdbx.augment.limit

---

rpc/websocket.go

This PR increases frame size, so it'll be possible to use more complicated RPC requests(like `eth_getBlockByNumber`, `trace_` and etc.),  via websocket.

Increase websocket frame size

---

eth/stagedsync/stage_finish.go
turbo/stages/stageloop.go

Only notify for canonical header obtained from last Finish.
Imho this should be enough. But review !!

Update stage_finish.go : notifications to rpc daemon

---

cmd/prometheus/dashboards/erigon.json
cmd/rpcdaemon/README.md
cmd/rpcdaemon/cli/config.go

Reason: 
- benchmark of large batches with fast sub-requests showed that high concurrency harming it.
- benchmark of much parallel batches also suffer from too high parallelism.
- value 2 still increasing throughput of batches with fast sub-requests 2 times. (value 4 increasing throughput 3 times, which is not great anymore, then further increasing must be done manually depending on traffic and server capacity).
- value 2 useful when batch has much sub-requests, but small sub-set of them is slow.
- users who have much slow sub-requests will need manually increase it - depend on their Server capacity.

RPCDaemon: reduce --rpc.batch.concurrency default from 50 to 2

---

consensus/ethash/consensus.go
consensus/misc/eip1559_test.go
core/forkid/forkid_test.go
core/vm/runtime/runtime.go
params/config.go

Implement [Arrow Glacier network upgrade](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md) and enable it for mainnet.
Also remove `CatalystBlock` because the Merge won't use a specific block number.
Geth already has Arrow Glacier: https://github.com/ethereum/go-ethereum/pull/23810.

Arrow Glacier network upgrade

---

consensus/serenity/serenity.go
consensus/serenity/serenity_test.go

This PR just introduces the checks that Serenity does from the execution layer side. This is not the whole "merger"

Added serenity consensus engine

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/engine_api.go

This PR adds the following namespaces (not the implementations):
* engine_forkchoiceUpdatedV1: POS_FORKCHOICE_UPDATE defined in EIP-3675
* engine_executePayloadV1: Execute a block sent by the beacon chain
* engine_getPayloadV1: get payload (validator node only)
This is based on the latest specs (nov 1st): https://notes.ethereum.org/@9AeMAlpyQYaAAyuj47BzRw/rkwW3ceVY

added engine_ namespace in rpcdaemon

---

turbo/stages/headerdownload/header_algos.go

Multiple edge-cases here. Commits are split up to make the changes more readable. The first commit fixes just the underflow problem, while retaining the original logic.
Third commit changes the logic, to how I believe `RequestSkeleton()` was intended to work.

Fix header skeleton

---

cmd/sentry/download/sentry_api.go

The `Skip` parameter of the Eth API is unintuitive, and easy to assume as an offset or multiple.  `Length` already includes the base block, so it needs to be `Length - 1` here.
This would have been causing valid peer choices to be ignored as header sources, especially when close to the current head, resulting in a synched node repeatedly falling out of synch (before catching up again).

Fix SendHeaderRequest peer minBlock

---

cmd/sentry/commands/sentry.go
cmd/sentry/download/sentry.go
cmd/utils/flags.go
turbo/cli/default_flags.go

Refactored the enode url list parsing first, as there was a lot of duplication and almost-duplication (eg. `log.Error` vs `log.Crit`, and returning with an error if a one url was invalid vs ignoring just that url).
Trusted peers were already supported at runtime, but they just needed to have a flag exposed to configure them from the CLI.

Add trusted peers flag

---

turbo/stages/headerdownload/header_algo_test.go
turbo/stages/headerdownload/header_algos.go

Plenty more of these, but this was a trivial one.

Avoid a redundant rlpHash() in FeedHeader()

---

cmd/rpcdaemon/commands/eth_receipts.go
core/state/database_test.go
eth/stagedsync/stage_txlookup.go

* Cleanup
* Restore
* Fix for existing tx
* Cleanup

eth_getTransactionReceipt not to return unrelated different tx receipts

---

cmd/sentry/download/sentry.go
cmd/sentry/download/sentry_test.go
p2p/server.go

Partially solves https://github.com/ledgerwatch/erigon/issues/2985
The root cause of https://github.com/ledgerwatch/erigon/issues/2985 is mdbx failure, this patch solves only "panic" during sentry server initialization in case there were some errors.
Also, I think `srv.running` should be set to `true` right before actual server startup, because `Start()` can exit earlier and this variable wouldn't reflect the internal state of the server.

Fix Sentry server initialization

---

cmd/sentry/download/downloader.go
core/types/hashing.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/headerdownload/header_test.go

Lots of optimizations here, mainly around avoiding redundant hashing, re-encoding RLP, map look-ups, and even just `big.Int` to `uint64` conversions. Aside from that, they also make the code a lot simpler.
As a result of the simplification, it also removes a latent bug in `SplitIntoSegments()` where `headersRaw` was being indexed with the sorted order of `headers`, despite not being sorted itself. `headersRaw` wasn't being used anywhere yet, so this bug had not yet manifested.

ChainSegment efficiency

---

turbo/stages/headerdownload/header_algos.go

Simplify logic by using sub-slices of `ChainSegment` instead of the full slice with `start` and `end` indexes.

Use sub-slices for ChainSegment actions

---

cmd/hack/hack.go
cmd/integration/commands/state_stages.go
cmd/state/commands/check_change_sets.go
cmd/state/commands/opcode_tracer.go
consensus/ethash/sealer_test.go
core/blockchain.go
core/chain_makers.go
core/rawdb/accessors_chain_test.go
core/types/block.go
core/types/block_test.go
eth/stagedsync/stage_mining_finish.go
migrations/receipt_repair.go
tests/block_test_util.go
turbo/stages/headerdownload/header_algos.go
turbo/transactions/tracing.go

`Block.Header()` does a deep-copy of the entire header using `CopyHeader()`, so try to avoid redundant copies, and prefer using `Block.HEADER_FIELD()` accessors.

Avoid redundant Block.Header() deep-copy

---

accounts/abi/bind/backends/simulated.go
cmd/evm/internal/t8ntool/transition.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/trace_adhoc.go
core/state_transition.go
core/types/block.go
core/vm/contracts.go
core/vm/runtime/runtime_test.go
eth/protocols/eth/protocol.go
internal/ethapi/api.go

A few places using `big.Int.BitLen()` or `uint256.Int.BitLen()` only for testing zero or non-zero. This replaces those with `big.Int.Sign()` and `uint256.Int.IsZero()`.
Also during RLP-encoding of blocks and headers, where `big.Int.BitLen()` was called 2 or 4 times each for a single unchanged value.

Avoid redundant BitLen()

---

core/types/block.go

A `Random` field was added to `Header.EncodeRLP()`, but the change was not also reflected in `Header.EncodingSize()`.
This also fixes a copy/paste error in a couple of error messages for decoding `Random` in `Header.DecodeRLP()`.

Fix Header.EncodingSize() to match EncodeRLP() with EIP-3675

---

cmd/rpcdaemon/commands/admin_api.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/erigon_api.go
cmd/rpcdaemon/commands/erigon_nodeInfo.go
cmd/rpcdaemon/services/eth_backend.go
cmd/sentry/download/sentry.go
eth/backend.go
eth/backend_test.go
ethdb/privateapi/ethbackend.go
go.mod
go.sum

Add NodeInfo implementation (https://github.com/ledgerwatch/erigon/issues/2679)
(blocked by https://github.com/ledgerwatch/erigon-lib/pull/196 need to revert `go.mod` after the merge)
Not sure if we can assert that `p2p.NodeInfo.Protocols` is either `map[string]eth.NodeInfo` or `map[string]string`. Even though I didn't find any other usages, `p2p.NodeInfo` declares this field as `map[string]interface{}`, so i decided just to marshal it into json, as the first approach.

Add NodeInfo implementation

---

eth/protocols/eth/peer.go
p2p/simulations/adapters/inproc.go
p2p/simulations/adapters/types.go
p2p/simulations/network_test.go

`eth.Peer` (distinct from `p2p.Peer`) was still using a `string` for its `id` field (and `ID()` accessor), although this was not actually being used by anything. This update changes it to use `enode.ID` in keeping with the rest of the code base.
`p2p.NodeInfo` and `p2p.PeerInfo` (distinct from Sentry's `download.PeerInfo`) continue to use a `string` for the id as they are informational / presentation types.
Related to #3013.

Change eth.Peer.ID() type from string to enode.ID

---

cmd/rpcdaemon/commands/engine_api.go

[Kintsugi v3](https://hackmd.io/@n0ble/kintsugi-spec#Kintsugi-Spec-v3) is going to use Engine API [v1.0.0-alpha.5](https://github.com/ethereum/execution-apis/releases/tag/v1.0.0-alpha.5).

Update Engine API to v1.0.0-alpha.5

---

cmd/rpcdaemon/services/eth_backend.go

Following https://github.com/ledgerwatch/erigon/pull/3073#issuecomment-984425567
The solution is rather ugly, but unfortunately, I don't have any other ideas on how to deal with `map[string]interface{}` datatype (maybe we can implement a custom serializer for it?).
The problem was in numeric precision loss during json unmarshalling of big integers since they are decoded as a float64.
So after this fix, "NodeInfo.Protocols.Difficulty" field is formatted properly in rpcdaemon response.

Fix NodeInfo.Protocols decoding

---

cmd/sentry/download/downloader.go
eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algo_test.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

1. Anchors are now deleted from both `anchors` map and the `anchorQueue` to keep them in sync
2. Following (1), function `RequestMoreHeader` can now stop checking if anchor is still in `anchors` map
3. `HeaderRequest` now includes pointer to the anchor, from which that request was originated, it means we don't need to look for the anchor again by hash
4. Function `SentHeaderRequest` renamed to `UpdateRetryTime` to better describe what it does

Header download simplifications

---

cmd/rpcdaemon/README.md

As discussed in Discord, it seems that `--txpool.api.addr` is mandatory when exposing the `txpool` API: https://discord.com/channels/687972960811745322/738982866670714901/919621609961160804

Document txpool.api.addr when using txpool API

---

eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algo_test.go
turbo/stages/headerdownload/header_algos.go

Moves the transition logic out of `FeedHeader()` rather than passing in `terminalTotalDifficulty` and returning `isTrans`.
These changes are split from another larger, dependent PR so that they can be approved without the larger changes blocking the Serenity PR, due to the overlap with `FeedHeaderFunc`.

Move transition logic out of FeedHeaderFunc

---

cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/trace_filtering.go

Implemented intersection mode for Trace API Filter call. 
I'm not sure I used correct way to generate blocks for testing, please correct me if i'm wrong.

#2119 - implemented trace_filter intersection mode for 

---

cmd/downloader/readme.md
cmd/hack/hack.go
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/erigon_issuance.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/eth_txs.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/tracing.go
cmd/rpcdaemon/interfaces/interfaces.go
cmd/rpcdaemon/services/eth_backend.go
cmd/sentry/sentry/downloader.go
cmd/state/verify/verify_txlookup.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/accessors_indexes.go
eth/protocols/eth/handlers.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stage_senders_test.go
eth/stagedsync/stage_txlookup.go
ethdb/privateapi/ethbackend.go
go.mod
go.sum
turbo/cli/snapshots.go
turbo/snapshotsync/block_reader.go
turbo/snapshotsync/block_snapshots.go

- added new .idx file like `v1-005000-005500-transactions-to-block.idx` 
- .idx files now created in etl-tmp folder and moved to snapshots folder on success .Build
(will do same for .seg in anoter RP)

Snapshots: tx lookup in RPC from snapshots

---

core/types/transaction_signing.go

I suppose that the data race with legacy tx could appear because of overwriting the pointer value (which is the field of a tx structure) during runtime (v *uint256.Int).

Suggesting fix for data race

---

cmd/integration/commands/stages.go
core/vm/eips.go
eth/backend.go

`BSCChainConfig` doesn't have `LondonBlock`, so no need to remove [London](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md) EIP-3198 & EIP-3529.

No need for ApplyBinanceSmartChainEIPs

---

cmd/sentry/sentry/sentry.go

This solves #3318
_The Sentry already sends the PeersReply_Connect event to remote clients when a new Peer connects. 
Also it should send the PeersReply_Disconnect event to signal that a Peer disconnected so the clients can react and take actions, for example simple tracing the event or asking for the new peer count._
This PR aims to adds this behavior.

Enable Sentry to send "peer disconnected" event

---

core/state_processor.go
core/state_transition.go

BSC always have in block system transaction that consume 2^256/2 gas price that cause block's gas price overflow. That is why applying readonly calls or trace to such transactions and even trace of block fail with insufficient gas.
https://github.com/ledgerwatch/erigon/issues/3329

BSC: Fix of gas bailout flag for trace and call calculations

---

params/version.go

to highlight that Erigon built from the devel branch has some indeterminate future version "2022.99.99-dev" instead of 2021.11.3-alpha.
Also see how many "2021.11.3-alpha" instances https://www.ethernodes.org/client/erigon shows currently.

Explicit dev version

---

cmd/utils/flags.go

cmd/utils: fix typo

---

cmd/rpcdaemon/commands/eth_txs.go

`eth_getTransactionByBlockHashAndIndex` and `eth_getTransactionByBlockNumberAndIndex` should return `null` if the index provided is out of bound (checked with Infura and Cloudflare ETH gateway).

fix compatibility of getting tx by number

---

turbo/stages/headerdownload/header_algos.go

I have a suspicion that after this change we started seeing headers stage stuck again

Revert "Inverted lowestNum and highestNum in header downloader (#3301)"

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/state/commands/check_change_sets.go
cmd/state/commands/opcode_tracer.go
core/state/database_test.go
core/state/intra_block_state_test.go
core/state/plain_readonly.go
core/state/state_test.go
core/vm/runtime/runtime_test.go
turbo/stages/blockchain_test.go
turbo/transactions/tracing.go

This change fixes discrepancy between `state.PlainState` and `GetAsOf`. It also fixes the second part of Issue #3413 (`eth_createAccessList` not returning all accessed addresses/storage keys).

state.PlainState is now at the beginning of blockNbr, not the end

---

cmd/downloader/main.go
cmd/sentry/sentry/downloader.go
eth/backend.go
eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go

@AlexeyAkhunov hi. 
I see that when link get persisted, it set `link.header=nil` at `stages/headerdownload/header_algos.go:769`
and in same time there is code like which reading `link.header.ParentHash` without nil or persisted flag check:
```
_, bad := hd.badHeaders[link.hash]
if !bad {
_, bad = hd.badHeaders[link.header.ParentHash]
}
```
Is this correct fix?
https://github.com/ledgerwatch/erigon/compare/sn_nil?expand=1#diff-afffa34063d33db53677de5b49f3f3fcced5b5c65889f1d27d4d92eedddd1e99L736

Snapshot: link.header is nil sometime

---

turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/mock_sentry.go

* First change for header queues
* Fix
* Fix import
* trigger verification when highestInDb changes
* Print hash, fix MarkAllPreverified
* Fix test
* Cleanup
* More cleanup

[header downloader] introduce queues instead of insertList (#3489)

---

eth/backend.go

```
goroutine 43675 [running]:
github.com/ledgerwatch/erigon/eth.(*Ethereum).Stop(0xc000246340)
github.com/ledgerwatch/erigon/eth/backend.go:760 +0x270
github.com/ledgerwatch/erigon/node.(*Node).stopServices(0x939b88, {0xc000790660, 0x1, 0xc015836b40})
github.com/ledgerwatch/erigon/node/node.go:263 +0xb3
```

fix some nil on shutdown

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/commands/debug_api_test.go
cmd/rpcdaemon/commands/tracing.go
cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_tracetransaction.go
cmd/rpctest/rpctest/request_generator.go

First PR. Reuses a lot of the plumbing from `debug_traceTransaction`. 
Implements: 
* https://geth.ethereum.org/docs/rpc/ns-debug#debug_traceblockbyhash
* https://geth.ethereum.org/docs/rpc/ns-debug#debug_traceblockbynumber
Iteratively calling `debug_traceTransaction` to obtain full traces of a block is extremely resource intensive `O(n^2)`. Since for each transaction all proceeding transactions in the block need to be replayed. The ability to trace an entire block at once greatly reduces the overhead and executing time.
* Compared with results of `debug_traceTransaction`. Call `debug_traceTransactionByHash` and use the transaction index in the block as the index in results returned. `jq '.results[193]' trace.json`
* Use of `callTracer`. e.g. `debug.traceBlockByNumber(14212372,{tracer: …

rpcdaemon: added debug_TraceBlockByNumber and debug_TraceBlockByHash

---

cmd/rpcdaemon/cli/httpcfg/http_cfg.go
eth/backend.go
turbo/cli/flags.go

compatible with geth (and no conflict with existing rpcdaemons)

embed rpcdaemon: enable it only by --http flag

---

cmd/cons/commands/clique.go
cmd/cons/commands/root.go
cmd/downloader/debug/debug_test.go
cmd/downloader/main.go
cmd/integration/commands/flags.go
cmd/integration/commands/refetence_db.go
cmd/integration/commands/reset_state.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/cli/httpcfg/http_cfg.go
cmd/starknet/cmd/generate_raw_tx.go
cmd/state/commands/check_change_sets.go
cmd/state/commands/check_enc.go
cmd/state/commands/check_index.go
cmd/state/commands/erigon2.go
cmd/state/commands/global_flags_vars.go
cmd/state/commands/history2.go
cmd/state/commands/index_stats.go
cmd/state/commands/opcode_tracer.go
cmd/state/commands/state_root.go
cmd/state/commands/verify_txlookup.go
cmd/utils/flags.go
eth/ethconfig/config.go
node/config_test.go
node/errors.go
node/node.go
node/node_test.go
turbo/app/snapshots.go
turbo/cli/flags.go

In most places (100+) the convention is to use "DataDir" in function names and public names,
and use "datadir" for local variables.
This fixes the discrepancies from this rule.
* rename from Datadir to DataDir (functions and public vars)
* rename dataDir to datadir (local variables)

Rename Datadir/dataDir to follow conventions.

---

cmd/utils/flags.go
eth/backend.go
internal/testlog/testlog.go
node/api_test.go
node/config.go
node/node.go
node/rpcstack.go
p2p/discover/table.go
p2p/dnsdisc/client.go
p2p/dnsdisc/client_test.go
p2p/nat/nat.go
p2p/peer.go
p2p/server.go
p2p/server_test.go
p2p/simulations/adapters/inproc.go

* use "log" for struct fields
* use "logger" for function parameters and local vars
This is a compromise between:
1) using `logger := log.New()` to avoid aliasing (as in `log := log.New()`)
2) and keeping it short when logging e.g.: `srv.log.Info(...)`

Rename log/logger to follow conventions.

---

cmd/bootnode/main.go
cmd/sentry/sentry/sentry.go
p2p/discover/common.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go
p2p/server.go
p2p/server_test.go

Add explicit Context to ListenV4 and ListenV5.
This makes it possible to stop listening by an external signal.

Discovery: add Context to Listen.

---

cmd/utils/flags.go
node/config.go
node/config_test.go
p2p/node_key_config.go

Extract private key setup from the global config setup to make it reusable.
Return errors instead of panicing.
* NodeKey() method is removed - it is unused.

Refactor node private key setup.

---

cmd/rpcdaemon/commands/engine_api.go
core/block_proposer.go
core/chain_makers.go
core/types/block.go
eth/backend.go
eth/stagedsync/stage_mining_create_block.go
ethdb/privateapi/ethbackend.go
rpc/errors.go

1. Ensure that, when we're building a payload, our current state matches `headBlockHash` of the corresponding `forkchoiceUpdated`.
2. Use empty (no txns) but valid blocks to initialize pending payloads. They serve as fallback in case we fail to actually build a block with transactions.

Refactor payload building

---

core/state/journal.go
core/state/state_object.go

* storage override revert support
* Fix

[stable] storage override revert support

---

turbo/snapshotsync/block_snapshots.go

Fixes lint errors:
turbo/snapshotsync/block_snapshots_test.go:77:69: not enough arguments in call to findAndMergeBlockSegments (typecheck)
_, err := findAndMergeBlockSegments(context.Background(), s, dir, 1)
turbo/snapshotsync/block_snapshots_test.go:88:68: not enough arguments in call to findAndMergeBlockSegments (typecheck)
_, err = findAndMergeBlockSegments(context.Background(), s, dir, 1)

Fix lint: remove unused findAndMergeBlockSegments log level parameter.

---

cmd/bootnode/main.go
p2p/nat/nat.go
p2p/nat/natpmp.go
p2p/nat/natupnp.go
p2p/server.go

If --nat extip:1.2.3.4 option is specified, the port mapping logic
(AddMapping/DeleteMapping) does nothing.
This optimization avoids running a goroutine for doing nothing.

p2p: Disable port mapping task with --nat extip

---

Makefile

Refactor cmd targets to use a common implicit rule recipe.
Change "make all" to include them all.

Makefile: refactor cmd targets.

---

p2p/discover/table_test.go

macOS CI suffer from high number

p2p/discover: less qcheck iterations in tests

---

cmd/evm/internal/t8ntool/execution.go
cmd/hack/hack.go
cmd/rpcdaemon/health/health.go
cmd/rpcdaemon/main.go
cmd/rpcdaemon/services/eth_backend.go
cmd/rpcdaemon/services/eth_mining.go
cmd/rpcdaemon/services/eth_txpool.go
cmd/sentry/sentry/broadcast.go
cmd/sentry/sentry/downloader.go
cmd/sentry/sentry/sentry.go
cmd/sentry/sentry/sentry_api.go
consensus/bor/bor.go
consensus/bor/genesis_contracts_client.go
consensus/clique/clique.go
consensus/parlia/parlia.go
core/state/plain_readonly.go
core/vm/interpreter.go
eth/calltracer/calltracer.go
eth/gasprice/gasprice.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_finish.go
eth/stagedsync/stage_headers.go
internal/debug/flags.go
rpc/websocket.go
turbo/cli/flags.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/stageloop.go

log.Warn/Error uses "err" key to log errors in most places.
This renames "error" to "err" in some places to adhere to this convention.

Use "err" key for logging errors.

---

Dockerfile
README.md
cmd/rpcdaemon/cli/config.go
docker-compose.yml

Per the [Engine API spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#underlying-protocol), eth API should be exposed alongside engine API.

Expose eth API on the same ports as engine API

---

p2p/discover/node.go
p2p/discover/table_util_test.go
p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v4wire/v4wire.go
p2p/discover/v5_udp_test.go
p2p/enode/idscheme.go
p2p/enode/urlv4.go

Encode and hash logic was duplicated in multiple places.
* Move encoding to p2p/discover/v4wire
* Move hashing to p2p/enode/idscheme
* Change newRandomLookup to create a proper random key on a curve.

Discovery: refactor public key to node ID conversions.

---

cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/eth_subscribe_test.go
cmd/rpcdaemon/commands/send_transaction_test.go
cmd/rpcdaemon/commands/txpool_api_test.go
consensus/clique/snapshot_test.go
core/block_validator_test.go
core/chain_makers.go
docs/evm_semantics.md
docs/merry-go-round-sync.md
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_headers.go
turbo/stages/blockchain_test.go
turbo/stages/mock_sentry.go
turbo/stages/sentry_mock_test.go

This handles the following corner case failing during Hive testing: the chain consists of a single genesis block and a trivial `forkchoiceUpdated` is sent with all hashes pointing to the genesis block.
Also, some typos are fixed.

Handle a corner case in forkchoiceUpdated

---

Makefile

The command builds were always using the root go.mod.
Adding cmd/mycmd/go.mod produced an "package not found" error.
This changes the build to run in the cmd/mycmd directory:
* If cmd/mycmd/go.mod is present, it is used.
* Otherwise it builds the main package using the root go.mod as before.

Makefile: allow command-specific go.mod files

---

cmd/utils/flags.go
turbo/node/node.go

It's useful for those using the dev chain to be able to set the ports for discovery, previously, setting the `--port` flag wouldn't have any effect. 
With this PR merged `--chain=dev --port=30302`:
```
[INFO] [03-10|03:43:50.699] Development chain flags set              --nodiscover=true --v5disc=false --port=:0
...
[INFO] [03-10|03:42:22.305] Started P2P networking                   version=66 self="enode://trimmed@127.0.0.1:30302?discport=0" name=erigon/v2022.99.99-dev-540b41ed/linux-amd64/go1.17.6
```
and with `--chain=dev` and port unset:
```
[INFO] [03-10|03:43:50.699] Development chain flags set              --nodiscover=true --v5disc=false --port=:0
...
[INFO] [03-10|03:43:50.905] Started P2P networking                   version=66 self="enode://trimmed@127.0.0.1:39689?discport=0" …
```

Fix dev chain listen port not set

---

go.mod
go.sum
p2p/enode/nodedb.go

UpdateFindFails/UpdateLastPingReceived/UpdateLastPongReceived events
are causing bursty DB commits (100 per minute).
This optimization throttles the commits to happen at most once in a few seconds,
because this info doesn't need to be persisted immediately.

Discovery: throttle node DB commits (#3581)

---

go.mod
go.sum
p2p/discover/table.go
p2p/enode/nodedb.go

Problem:
QuerySeeds will poke 150 random entries in the whole node DB and ignore hitting "field" entries.
In a bootstrap scenario it might hit hundreds of :lastping :lastpong entries,
and very few true "node record" entries.
After running for 15 minutes I've got totalEntryCount=1508 nodeRecordCount=114 entries.
There's a 1/16 chance of hitting a "node record" entry.
It means finding just about 10 nodes of 114 total on average from 150 attempts.
Solution:
Split "node record" entries to a separate table such that QuerySeeds doesn't do idle cycle hits.

Discovery: split node records to a sepatate DB table (#3581)

---

p2p/discover/lookup.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_udp_test.go

This speeds up the discover package test suite from 60-80 sec to 20-40 sec.
* disable lookup.slowdown() in tests
* dgramPipe: refactor to use a channel
* handle ListenV4 err in tests
The improvements can be compared using:
go test -count 1 ./p2p/discover
go test ./p2p/discover -test.run TestUDPv4_Lookup -blockprofile profile.dat
go tool pprof -tree profile.dat

Discovery: speed up lookup tests

---

cmd/downloader/readme.md
cmd/integration/commands/flags.go
cmd/integration/commands/stages.go
cmd/rpcdaemon/cli/config.go
cmd/state/commands/erigon2.go
cmd/utils/flags.go
core/rawdb/accessors_chain.go
eth/backend.go
eth/ethconfig/config.go
eth/stagedsync/stage_headers.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stage_senders_test.go
turbo/app/snapshots.go
turbo/cli/default_flags.go
turbo/snapshotsync/block_reader.go
turbo/snapshotsync/block_snapshots.go
turbo/snapshotsync/block_snapshots_test.go
turbo/snapshotsync/snapshotsynccli/flags.go
turbo/stages/mock_sentry.go
turbo/stages/stageloop.go

- auto-merge segments on 1K, 10K, 100K, 500K thresholds
- retire old blocks and delete from db
- now background retire initiated by stage_senders.Prune func, even if pruning disabled (maybe in future will move to own stage or smash around multiple sages - will see).
- deletes are not limited yet

Snapshots: retire blocks by default 

---

cmd/rpcdaemon/commands/engine_api.go
eth/stagedsync/stage_headers.go
ethdb/privateapi/ethbackend.go

Useful for debugging issues like the ones we observed in Kiln.

More Merge logging

---

go.mod
go.sum

Update erigon-lib to https://github.com/ledgerwatch/erigon-lib/commit/05b59ea52483e9607258b1ebdca8923a4a2960c3 and thus pick up https://github.com/ledgerwatch/erigon-lib/pull/367.

Pick up erigon-lib fix for h2048 (#367)

---

go.mod
go.sum

as workaround for https://github.com/erthink/libmdbx/issues/269#issuecomment-1068214834

Mdbx: WriteMap fallback on open error

---

cmd/state/commands/erigon2.go
core/rawdb/accessors_chain.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/preverified_hashes_goerli.go

Touches issue https://github.com/ledgerwatch/erigon-lib/issues/257
Here are necessary updates to support different consensus engines during block processing by erigon2.
- Implemented wrapper `cliqueConsensusBlockReader` to read blocks without leading and finishing system transaction. Use of hacky BlockReader led to uint64 overflow, so when first transaction appears, reader tried to read tremendous amount of canonical transactions, which hangs app
- moved stat printing to separate routine. Yes, this is not thread safe to read blockNum, which is easy to solve but more important - statistics will be printed even if block processing took too much time
- blocks processing now using external consensus engine instead of initialized on each block ethash.
Requires merged …

added support of Clique consensus for block processing for erigon2

---

turbo/app/make_app.go

`app.MakeApp()` should pass erigon's `params.GitCommit` to `cli.NewApp()` 
https://github.com/ledgerwatch/erigon/blob/ec4b5e6c6f7561bf34676f868b0c538e45091114/turbo/app/make_app.go#L19-L21

Fix erigon version miss git commit

---

turbo/rpchelper/helper.go

Fixes https://github.com/ledgerwatch/erigon/issues/3630

Fix for eth_getBalance (and other RPC methods accessing history)

---

cmd/rpcdaemon/commands/eth_receipts.go

This changeset is trying to tidy up the eth_getLogs method in RPCDaemon.
The general idea is to keep the logic the same, just tidy up and remove unnecessary clutter. The last commit focuses on bringing the code closer to he Go aesthetic, by keeping the general program flow not indented, to the left, and the exceptional cases indented to the right.
I hopefully have made it easier to read.

rpcdaemon: Tidy up eth_getLogs

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go

in the old version you had to provide `{}`, you can't avoid that
```
{
"id": 2,
"jsonrpc": "2.0",
"method": "eth_estimateGas",
"params": [{}]
}
```
after this fix, you can finally do
```
{
"id": 2,
"jsonrpc": "2.0",
"method": "eth_estimateGas",
"params": []
}
```

Fix 'all defaults' case for eth_estimateGas

---

cmd/bootnode/main.go
consensus/aura/aura.go
crypto/crypto.go
crypto/crypto_test.go
crypto/signature_test.go
p2p/dnsdisc/tree.go
p2p/enode/urlv4.go
p2p/rlpx/rlpx.go
p2p/rlpx/rlpx_test.go
p2p/server.go
p2p/server_test.go
p2p/transport_test.go

Most places that used this method were cutting off the 1st byte.
Refactor this idea to a common place.
* better naming: MarshalPubkey matches existing UnmarshalPubkey
* "Std" suffix for the ANSI standard encoding without cut off
* docs

Refactor crypto.FromECDSAPub to MarshalPubkey/Std

---

eth/stagedsync/stage.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_senders.go

problem: bsc with --prune flag producing much GC in DB. (it's mostly related to stage_senders.prune func)
solution: just prune data by smaller portions on each sync cycle - then new blocks will re-use existing free space in DB and effect will be smaller.

Limit amount of deletes during one sync cycle

---

ethdb/privateapi/ethbackend.go

This should fix the following Hive test failures:
- Invalid Terminal Block in ForkchoiceUpdated: Test sends an fcU with a block that has not reached the TTD (the genesis in this case), expected response is INVALID_TERMINAL_BLOCK, but Erigon responds SYNCING
- Invalid Terminal Block in NewPayload: Test creates a payload that references a PoW block with an invalid total difficulty (the genesis in this case), expected response is INVALID_TERMINAL_BLOCK, but Erigon responds SYNCING

Check TerminalTotalDifficulty for NewPayload & ForkChoice

---

core/types/transaction.go
core/types/transaction_test.go
eth/stagedsync/stage_headers.go
ethdb/privateapi/ethbackend.go

According to [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718), for the purpose of calculating transaction root in headers typed transactions should be serialized with their type prepended as the first byte, without extra wrapping as RLP strings. On the other hand, `DecodeTransaction` (and, by extension,`DecodeTransactions`) parses such string wraps fine.

Prohibit EIP-2718 txn wrapped as RLP strings

---

core/rawdb/accessors_chain.go
eth/stagedsync/stage_headers.go

This should fix the following Hive test failures:
- Unknown SafeBlockHash: Test sends an fcU with an unknown (random) hash in the SafeBlockHash, and expects an error back, Erigon responds with VALID
- Unknown FinalizedBlockHash: Test sends an fcU with an unknown (random) hash in the FinalizedBlockHash, and expects an error back, Erigon responds with VALID
See also https://discord.com/channels/595666850260713488/892088344438255616/961231105921536010

Check that safe & finalized blocks are ancestors of head block

---

cmd/rpcdaemon/commands/rpc_block.go

To be consistent with geth. This partially reverts PR #3806.

RPC: return latest available block rather than forkchoice head

---

cmd/utils/flags.go

A few easy fixes related to my #3932 issue
* Changes the wording on `--http` to clearly indicate that it's default, and how to disable it
* Changes the description of http and ws compression flags
* Fixes typo
* Adds a note about `--verbosity` for `--torrent.verbosity` flag

Fix some cli flag descriptions

---

cmd/sentry/sentry/sentry.go
go.mod
go.sum
turbo/stages/mock_sentry.go

see https://github.com/ledgerwatch/interfaces/pull/101

Sentry GRPC: rename Peers to PeerEvents

---

cmd/rpcdaemon/cli/config.go

Net API is not required for to run the engine rpc

got rid of the automatic usage of net api

---

cmd/downloader/downloader/downloader.go
cmd/rpcdaemon/commands/admin_api.go
cmd/rpcdaemon/services/eth_backend.go
cmd/sentry/sentry/sentry.go
eth/backend.go
ethdb/privateapi/ethbackend.go
go.mod
go.sum

This RPC method returns information about the connected remote nodes.
https://geth.ethereum.org/docs/rpc/ns-admin#admin_peers
The peers are collected from all configured sentries.
See: https://github.com/ledgerwatch/interfaces/pull/102
Test with:
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "admin_peers", "params": [], "id":1}' localhost:8545

RPC: admin.peers()

---

rlp/decode.go
rlp/decode_test.go
rlp/doc.go
rlp/encode.go
rlp/encode_test.go
rlp/typecache.go

This adds support for a new struct tag "optional". Using this tag, structs used
for RLP encoding/decoding can be extended in a backwards-compatible way,
by adding new fields at the end.
see geth commit https://github.com/ethereum/go-ethereum/commit/700df1442d714cb3c42a602c39c042ce88be463f
for https://github.com/ledgerwatch/erigon/pull/3963

rlp: add support for optional struct fields (#22832)

---

p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v4wire/v4wire.go
p2p/discover/v4wire/v4wire_test.go

This changes the definitions of Ping and Pong, adding an optional field
for the sequence number. This field was previously encoded/decoded using
the "tail" struct tag, but using "optional" is much nicer.
see https://github.com/ethereum/go-ethereum/pull/22842
erigon issue https://github.com/ledgerwatch/erigon/issues/3124

p2p/discover/v4wire: use optional RLP field for EIP-868 seq (#3124)

---

README.md
cmd/utils/flags.go
eth/ethconfig/config.go
turbo/snapshotsync/snapshotsynccli/flags.go

Our previous sync mode is closer to geth's `FullSync` (execute all blocks from genesis) rather than `FastSync` (obsolete mode replaced by `SnapSync`). Mind that geth's [snap sync](https://github.com/ethereum/devp2p/blob/master/caps/snap.md) is very different from our new torrent sync, but I defer potential renaming to another PR.

FullSync instead of FastSync

---

p2p/discover/common.go
p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go

The test was slow, because it was trying to find
predefined nodeIDs (lookupTestnet) by generating random keys
and trying to find their neighbours
until it hits all nodes of the lookupTestnet.
In addition each FindNode response was waiting for 0.5 sec (respTimeout).
This could take up to 30 sec and fail the test suite.
A fake random key generator is now used during the test.
It issues the expected keys, and the lookup converges quickly.
The reply timeout is reduced for the test.
Now it normally takes less than.1 sec.

p2p: speed-up TestUDPv4_LookupIterator

---

cmd/utils/flags.go
node/defaults.go
p2p/dial.go
p2p/server.go
p2p/server_test.go
p2p/simulations/adapters/inproc.go

* use semaphore instead of a chan struct{}
* move MaxPendingPeers default value to DefaultConfig.P2P
* log Error if Accept fails
* replace quit channel with context

p2p: refactor MaxPendingPeers handling

---

cmd/observer/observer/crawler.go

Problem: (nil, nil) from CountPingErrors was not handled.
This happens if the node is not in the db (a bootstrap node),
and was never crawled before.

Observer: fix panic on clean start (#4002)

---

node/defaults.go
p2p/server.go
p2p/server_test.go

* exchange RLPx Hello even when maxpeers limit is reached
* bump MaxPendingPeers to increase the default handshake queue
(and the likelyhood of Hello exchange)

p2p: crawler-friendly handshake

---

eth/filters/filter.go

In filter.go:
https://github.com/ledgerwatch/erigon/blob/93ab7f5d826cf9ddb3d2b570036725bcb34e5448/eth/filters/filter.go#L298-L301
If `len(topics)` greater than len(log.Topics), `continue Logs` will make `filterLogs()` got an infinite loop.
So, It should be `continue`, not `continue Logs`.

eth/filters: Fix filterLogs()

---

.github/workflows/ci.yml
Dockerfile

Docker image build will use cached layers, since`go.mod` and `go.sum` won't changed very often, so we can add `RUN go mod download` early in `Dockerfile`.
https://cloud.google.com/architecture/best-practices-for-building-containers#optimize-for-the-docker-build-cache

Speed up docker image build by use layer cache

---

core/state_processor.go

`cfg` was not a pointer so cfg.SkipAnalysis was not saved properly and analysis was never skipped.
I have verified this patch on an older fork of the codebase (Aug 2021) but should also work with the latest version.

Fix ignored SkipAnalysis in core/state_processor.go

---

p2p/discover/common.go
p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_udp_test.go

The UDP test must be closed after the serveTestnet processing.
If it happens during the processing, the serveTestnet encounters this error.
(it tries to emulate a packet receival handling when the handler is already cleaned up)
FindNode triggers a Ping in ensureBond.
This causes an extra Sleep for "ping back".
Don't wait for this in tests.
Close v5 tests.
The requests may also timeout if a lot of them queue up in the udpTest.pipe,
and serveTestnet is slow to process them.
Increase replyTimeout a bit to prevent that.

p2p: TestUDPv4_Lookup - unsolicited reply error

---

.github/workflows/test-integration.yml

Running on PR close event tests the PR commit, not the final merged commit.
The final commit is tested by "push" event, but it appears as "skipped" in the list of devel ccmmits,
because "push" event was skipped by "if".

CI: run integration tests on trunk after PR is merged

---

p2p/discover/v4_lookup_test.go

--- FAIL: TestUDPv4_LookupIterator (1.36s)
155
v4_lookup_test.go:168: handlePacket error: "unsolicited reply"
156

p2p: TestUDPv4_LookupIterator failures workaround

---

.github/workflows/ci.yml
.github/workflows/test-integration.yml

Cache "go-build" containing cached build artifacts from the Go build system.
This saves up to:
- 6 min on Linux (from 10 min to 4 min)
- 3 min on macOS (from 13 min to 10 min)
- 7 min on Windows (from 27 min to 20 min)
Cache Windows deps (mingw, cmake).
This saves 6,5 min on Windows builds (from 20 min to 13,5 min)

CI: more caching

---

cmd/rpcdaemon/rpcdaemontest/test_util.go
core/chain_makers.go
core/types/block.go
core/types/log.go
core/types/receipt.go

* reuse the generated test blockchain across tests
* copy ChainPack to ensure test isolation
This improves the speed from 10s to 4s.
The package tests timeout can be reduced to 5s:
go test ./cmd/rpcdaemon/commands -count 1 --timeout 5s

rpcdaemon: optimize tests

---

core/state_processor.go

Befor this fix there was Warning on mainnet:
```
WARN[05-06|10:20:16.316] Code Bitmap used for detecting invalid jump tx=0x21ab7bf7245a87eae265124aaf180d91133377e47db2b1a4866493ec4b371150 block_num=13119520
```
After this fix error:
```
EROR[05-06|10:20:42.606] [6/16 Execution] Execution failed        block=13119520 hash=0x9d683102479c742b46e9647a8290615e86ecb92a83cdf2b8f2d6ed90c31c189b err="mismatched receipt headers for block 13119520"
```
Reverting this PR

Revert "Fix ignored SkipAnalysis in core/state_processor.go"

---

p2p/peer.go
p2p/peer_error.go

As per https://github.com/ethereum/go-ethereum/pull/24507

p2p: define DiscReason as uint8

---

eth/tracers/jsvm.go
eth/tracers/jsvm_test.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
go.mod
go.sum

Reasons:
* duktape is not maintained
* on macOS it produces a warning: unused function '_duk_debugger_attach'
(this slows down incremental builds and pollutes the test logs)
Why goja?
Geth has migrated some parts to goja (console and clef signer tool),
although not migrated tracers yet.
* fix isPrecompiled() native function
* recursion limit test is obsolete

tracers: replace duktape with goja

---

p2p/discover/common.go
p2p/discover/table.go
p2p/discover/table_util_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_lookup_test.go
p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go

* configure a 50 ms timeout for tests (like v4 tests)
* use in-memory DB (like v4 tests)
* TestUDPv5_callTimeoutReset: improve speed from 1.2s to 0.2s
* TestUDPv5_callTimeoutReset: reduce the likelihood of "RPC timeout"
* move lookup tests to the "integration" suite
* log details of unmatched packets and sends to non-existing nodes
* fix flaky TestUDPv5_findnodeHandling:
Table.nextRevalidateTime was random (from 0 to 10s).
Sometimes it triggered doRevalidate immediately, and it produced an unexpected ping.
Configure a high interval to not revalidate during the tests.
Time improved from 1.7s to 0.2s.
Test with:
go test ./p2p/discover -run TestUDPv5 -count 1

p2p (#4119): treat slow discover v5 tests

---

p2p/dial_integration_test.go
p2p/dial_test.go
p2p/discover/table_integration_test.go
p2p/discover/table_test.go
p2p/discover/v4_udp_test.go
p2p/enode/iter_integration_test.go
p2p/enode/iter_test.go
p2p/nat/natupnp_test.go

* TestTable_ReadRandomNodesGetAll: refactor to integration and examples
* TestTable_bumpNoDuplicates: refactor to integration and examples
* TestUDPv4_smallNetConvergence: speed up from 1.7s to 0.3s by applying the test config
* TestUPNP_DDWRT: move to integration tests
* TestFairMix: split in 2, do more iterations in integration tests
* TestDialSched: speed up from 1s to 0.2s by removing the unexpected dial check,
(keep the check during the integration tests)

p2p (#4119): treat slow integration tests

---

.golangci.yml

https://github.com/golangci/golangci-lint/issues/2649
```
WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] gosimple is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] staticcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the …
```

lint: silence non-working go 1.18 linters

---

p2p/discover/v5_udp_integration_test.go
p2p/discover/v5_udp_test.go

The test fails sometimes on macOS CI with:
v5_udp_test.go:477: unexpected error: "RPC timeout"
Fixing by increasing the timeout from 120ms to 700ms,
and move the test to the integration suite, because it takes up to 1s now.

p2p: fix flaky TestUDPv5_callTimeoutReset

---

.github/workflows/ci.yml
.github/workflows/test-integration.yml

Use matrix.os in cache keys to not share caches between OS versions:
- runner.os = Windows
- matrix.os = windows-2022

CI: windows-2022

---

ethdb/prune/storage_mode.go
turbo/cli/flags.go

Changes:
* Proceeded to check if other h, r, t or c flags for 'before' and 'older' are set before returning from the default state of --prune
Concern:
* Does the 'disabled' value for '--prune=' need to be updated if the '--prune.*' flags are set but the '--prune=' flag is not?

Fix disabled value for `--prune.*` flags

---

cmd/bootnode/main.go
cmd/observer/observer/server.go
cmd/utils/flags.go
p2p/nat/nat.go
p2p/nat/nat_stun.go

--nat stun is an automatic external IP detection alternative to manual --nat extip option.
It can be used both at home or on production servers without any extra setup.
It is fast (up to 5 ms) and more reliable than alternatives (as the request goes to the public internet).
This auto-detection is useful to run multiple instances of a service in cloud environments
where the node IPs are not known in advance.

p2p: STUN external IP detection

---

cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
core/rawdb/accessors_chain.go
eth/integrity/trie.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_headers.go
eth/stagedsync/stage_txlookup.go
turbo/stages/headerdownload/header_algos.go
turbo/trie/structural_branch_test.go

- print amount of blocks in snapshots at node startup (and alloc)
- fix unwind of TxLookup stage behind snapshot threshold
- call AddHeadersFromSnapshot only at initialCycle

Snap: call AddHeadersFromSnapshot only at initialCycle

---

rpc/types.go
rpc/types_test.go

`rpc.BlockNumberOrHash` can be unmarshalled from a JSON dictionary.
I found that if you provide an empty or an invalid dictionary, it still unmarshalls successfully but with `nil` values. That crashes method handlers.
Added tests and error handling for this case.
```
26: {`{}`, true, BlockNumberOrHash{}},
27: {`{"jsonrpc":"2.0","result":{"code":418,"message":"blabla"},"id":""}]`, true, BlockNumberOrHash{}},
```

Fix `rpc.BlockNumberOrHash` unmarshaling

---

.github/workflows/ci.yml
Dockerfile
Makefile

Dockerfile requires some --build-arg options.
Fix "docker" target to pass them.
Fix GIT_TAG to reflect the most recent tag related to HEAD, instead of an unrelated most recent tag.
Use it as the image VERSION.
Image tags need to be passed explicitly if needed:
DOCKER_FLAGS='-t erigon:latest' make docker

Makefile: pass docker build arguments

---

cmd/sentry/sentry/sentry_multi_client.go
go.mod
go.sum

* refactor pumpStreamLoop to support streams with arbitrary message types
* subscribe to PeerEvents
Example output:
```
[DBUG] [05-26|11:43:31.575] Sentry peer did Connect                  peer=2098142ba904cb76194eec84c76b23fcd840d9ba8834633efcd5da5780fee573ea464fbd64e97fd198758df7826497adbd6fcba2ccaaf952a1f840fe2bb63c00
[DBUG] [05-26|11:43:53.823] Sentry peer did Connect                  peer=252ab6a1d0f971d9722cb839a42cb81db019ba44c08754628ab4a823487071b5695317c8ccd085219c3a03af063495b2f1da8d18218da2d6a82981b45e6ffc00
[DBUG] [05-26|11:43:53.823] Sentry peer did Disconnect               peer=252ab6a1d0f971d9722cb839a42cb81db019ba44c08754628ab4a823487071b5695317c8ccd085219c3a03af063495b2f1da8d18218da2d6a82981b45e6ffc00
[DBUG] [05-26|11:43:54.196] Sentry peer did Connect …
```

sentry: log peer events in erigon

---

cmd/integration/commands/stages.go
cmd/observer/database/db.go
cmd/observer/database/db_retrier.go
cmd/observer/database/db_sqlite.go
cmd/observer/main.go
cmd/observer/observer/command.go
cmd/observer/observer/crawler.go
cmd/observer/observer/diplomacy.go
cmd/observer/observer/node_utils/node_addr.go
cmd/observer/observer/node_utils/node_id.go
cmd/observer/observer/sentry_candidates/intake.go
cmd/observer/observer/sentry_candidates/log.go
cmd/observer/observer/sentry_candidates/log_test.go
cmd/observer/reports/command.go
cmd/observer/reports/sentry_candidates_report.go
cmd/observer/utils/pubkey_hex.go
cmd/sentry/sentry/sentry_multi_client.go
cmd/utils/flags.go
eth/backend.go
go.mod
go.sum
node/nodecfg/config.go
turbo/cli/default_flags.go
turbo/stages/mock_sentry.go

The connected peers info is logged by erigon.
Observer is able to grep these events from the erigon log,
and use for crawling with the provided handshake info.
These peers are known to be from the compatible fork/network, and have a known clientID.
This increases the observer quality significantly if the sentries network is large.

observer: sentry candidates intake

---

cmd/rpcdaemon/commands/engine_api_test.go
ethdb/privateapi/ethbackend.go

This is a post-fix for PR #4314.
See also https://github.com/ethereum/execution-apis/pull/217.

Fix LatestValidHash nil pointer

---

consensus/clique/clique.go
consensus/serenity/serenity.go
eth/backend.go

This should fix, for instance, fix "Invalid Terminal Block in ForkchoiceUpdated" Hive test.

Authorize Clique & Parlia even when wrapped into Serenity

---

params/chainspecs/ropsten.json

Per https://blog.ethereum.org/2022/06/03/ropsten-merge-ttd/

New Ropsten TTD

---

README.md

A recent change now causes docker-compose to use buildkit. This
change just documents how to run docker-compose with buildkit.

Add documentation on how to build in docker with BuildKit

---

cmd/integration/commands/refetence_db.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_senders.go
eth/stagedsync/sync.go

Cause non-producing senders in DB during initial sync

StageSenders: wrong canonical array size at initial sync with snapshots

---

turbo/stages/headerdownload/header_algos.go

Previously `MarkAllVerified` was stuck in an infinite loop when `insertQueue` wasn't empty.

Fix MarkAllVerified

---

cmd/utils/flags.go
core/genesis.go
eth/backend.go
eth/ethconfig/config.go
params/chainspecs/kiln-devnet.json
params/config.go
turbo/cli/default_flags.go

Rename `MergeForkBlock` to `MergeNetsplitBlock` for consistency with geth (see https://github.com/ethereum/go-ethereum/pull/24904).

MergeForkBlock -> MergeNetsplitBlock

---

core/vm/instructions.go

When a contract calls suicide where the refund address is same as his address - refunding to himself -, then the tracer should be called after balance change.
I believe the L839 variable `balance` is just a pointer to an uint256 object, which is the same what is used during `AddBalance`.
This fixes #3953 issue.

Fix operation order during tracing suicide op code

---

cmd/rpcdaemon/commands/engine_api.go

Right now if we don't have the latest valid hash we answer with nil, so I changed it so we answer with an empty hash according to the specs

if no latest valid hash default to empty hash

---

cmd/rpcdaemon/commands/eth_system.go

In the PoS world we should wait for `headBlockHash` in [engine_forkchoiceUpdatedV1.forkchoiceState](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#engine_forkchoiceupdatedv1) before making the block available as "latest" in the RPC requests.
See also PR #4382.

eth_blockNumber should be equal to latest in eth_getBlockByNumber

---

cmd/rpcdaemon/commands/trace_adhoc.go

OP code `REVERT` has return data like `RETURN` which can be very useful, we should not hide/drop them.
Example result:
```
{
"action": {
"from": "0x799c5727581cf092fe3f15a6a289146fd908fc7c",
"callType": "call",
"gas": "0x49f8",
"input": "0x9e5faafc",
"to": "0x2cab154122bddaee2c555a58f88913f9e07622fc",
"value": "0x0"
},
"blockHash": "0xc0fc77a433c21cc43823459f92186c2c551548a6e6763cc40ca825a7198d2d48",
"blockNumber": 12336209,
"error": "Reverted",
"result": {
"gasUsed": "0x3809",
"output": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000176368616c6c656e6765206e6f7420636f6d706c65746564000000000000000000"
},
"subtraces": 2,
"traceAddress": [],
"transactionHash": …
```

Add REVERT result to trace

---

cmd/utils/flags.go

After the Merge Erigon won't work w/o exposed Engine API, so it makes sense to enable HTTP RPC by default.

Enable --http by default

---

core/state_processor.go

In BSC repo, the corresponding change was only for the miner, and it only affects the gas pool for the block, not the receipts

[BSC Euler fork] Undo unnecessary change

---

accounts/abi/abi.go
accounts/abi/abi_test.go
accounts/abi/error.go

add 'Error' Handle when using `abigen` to generate erigon code 
Linked error: "Fatal: Failed to generate ABI binding: abi: could not recognize type error of field xxx"

add_abigen_error_handle

---

eth/stagedsync/stage_headers.go
turbo/engineapi/request_list.go

Consider the following scenario:
1. CL sends `engine_newPayload`
2. CL sends `engine_forkchoiceUpdated` with `headBlockHash` pointing to the newly added block
3. CL asks for `eth_getBlockByNumber("latest")`
If we don't commit the DB transaction before replying to CL in 2, there's a race condition between 2 & 3 because in 3 we might be looking at the old `LastForkchoice.headBlockHash`. That's why Hive test "Inconsistent Head in ForkchoiceState" was failing.

Commit transaction before responding on Engine API

---

cmd/rpcdaemon/commands/eth_system.go
cmd/rpcdaemon22/commands/eth_system.go
eth/gasprice/gasprice.go

Currently func (b *GasPriceOracleBackend) HeaderByNumber is not checking wether the block response is not nil causing the following error inside `SuggestedGasPrice`:
`[EROR] [06-24|10:45:22.076] RPC method eth_gasPrice crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 block.go:1184 eth_system.go:206 gasprice.go:120 eth_system.go:117 value.go:556 value.go:339 service.go:222 handler.go:503 handler.go:408 handler.go:353 handler.go:187 handler.go:277 asm_amd64.s:1571]`
I have added a check, and if the response of the block is nil now `SuggestedGasPrice` will log a warning and return the last suggested tip gas

check if block is nil

---

cmd/integration/commands/stages.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/rawdbreset/reset_stages.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_bodies_test.go
eth/stagedsync/stage_headers.go
migrations/txs_begin_end_test.go

Delete headers & bodies of bad blocks (e.g. with invalid state root) on unwind. Otherwise bad blocks stay accessible by `eth_getBlockByHash`.
This should fix "Invalid StateRoot NewPayload" test in Hive.

Delete bad blocks on unwind

---

wmake.ps1

- Amended an error which caused target `db-tools` to be built as if it was a single binary
- Introduced initial check cloned directory has `.git` subfolder
- Enforced proper verification of min version for go lang
- Enforced submodules update for every target build : optionally user can specify `-WnoSubmoduleUpdate` in case is a dev making local changes (to submodules) which we do not want to be overwritten
- Enforced verbosity on go builds so we can see progress (previous version is silent since go 1.18)
- Script can now be invoked from outside source dir (it will return prompt to starting dir)

Wmake.ps1 changes

---

README.md

if you wish to separate node from rpcdaemon need to launch with -http=false or rpcdaemon will not launch as port occupied by erigon

Update Readme re http=false

---

cmd/downloader/downloader/downloadercfg/logger.go
cmd/downloader/main.go
cmd/utils/flags.go

changed the flag `--torrent.verbosity` to use an int value like the `--verbosity` flag.
`--torrent.verbosity` now uses values between zero to five, zero being no verbosity and five being detailed/critical

torrent verbosity now uses int

---

cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/eth_callMany_test.go
cmd/rpcdaemon/commands/tracing.go

In this PR, we want to introduce two new rpc methods `eth_callMany` and `debug_traceCallMany`. The rationale and the specification of those two methods could be found at [Issue #4471](https://github.com/ledgerwatch/erigon/issues/4471). 
We'd love to get code reviews from the erigon team.

Introduce `eth_callMany` and `debug_traceCallMany`

---

cmd/rpcdaemon/commands/eth_call.go

Instead of reading a whole block to get the header, now we are only reading the header to just get the gas limit

eth_estimateGas: read header instead of whole block

---

cmd/rpcdaemon/commands/eth_system.go
cmd/rpcdaemon22/commands/eth_system.go

Instead of getting the whole block to obtain the header inside of `GetHeaderByNumber` now we are getting the header straight away using `._blockreader`

getting header instead of block

---

cmd/rpcdaemon/commands/eth_subscribe_test.go

Reduce the likelihood of a deadlock caused by goroutine starvation on CI.
The CI macOS runners have 3 cores.
When running other tests in parallel having too few available cores could cause a deadlock.
Test with:
GOMAXPROCS=2 go test ./cmd/rpcdaemon/commands/eth_subscribe_test.go -test.count 100 --timeout 10s
Expected: the command finishes within 3 sec
Before the fix: it timeouts (without a timeout - hangs forever)
CI log:
https://github.com/ledgerwatch/erigon/runs/7104670914?check_suite_focus=true#step:10:53

Fix eth_subscribe_test timeout on CI

---

cmd/rpcdaemon/commands/eth_api.go

In some scenarios we are always returning nil as pending block number, while in `rpchelper.GetBlockByNumber` will return the latest block inside of our cache which we never get to do because of the initial if statement.

pending block will only return if it is not nil

---

cmd/downloader/downloader/downloader.go
cmd/downloader/downloader/downloader_grpc_server.go
cmd/downloader/main.go
cmd/utils/flags.go
eth/ethconfig/config.go
eth/stagedsync/stage_headers.go
go.mod
go.sum
turbo/cli/default_flags.go
turbo/shards/state_change_accumulator.go

- it will not report founded problems but just re-download broken pieces
- maybe rename it to --downloader.repair? 
- Erigon will also verify once after downloading all files done (even without flag)

--downloader.verfiy flag to verify once on startup

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_system.go
eth/gasprice/gasprice.go
turbo/snapshotsync/block_reader.go

It was regression from https://github.com/ledgerwatch/erigon/pull/4528 which caused uin64 underflow (PendingBlock=-1 was converted to uint64)

Support "latests block number" in Oracle Backend

---

core/rawdb/accessors_chain.go

We should be getting the amount of non canonical transactions from the non canonical bucket instead of the canonical bucket.

getting amount from non canonical bucket

---

Makefile
docker-compose.yml

Grafana expects to run as user id 472 and group id 0.
https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#user-id-changes
Specify `user: "472:0"` in `docker-compose.yaml` for `grafana` and modify `Makefile` to update permissions lazily as needed.
Patch authored by cory.eth (Cory Gabrielsen) (@cory_eth)

Fix grafana startup in docker-compose

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/eth_txs.go
cmd/rpcdaemon22/commands/eth_receipts.go
core/rawdb/bor_receipts.go
core/types/access_list_tx.go
core/types/bor_receipt.go
core/types/dynamic_fee_tx.go
core/types/legacy_tx.go
core/types/starknet_tx.go
core/types/transaction.go
internal/ethapi/api.go
turbo/adapter/ethapi/internal.go

* Add borTx to `eth_getBlockByHash` response
* Ensure borTxs have correct hashes (computing it if we have to)
* Don't try to derive `RPCTransaction.From` from signature for unsigned (e.g. bor) transactions; default to the zero address
* Derive txHash correctly in `DeriveFieldsForBorLogs`
* Surface borReceipt.Logs in `eth_getLogs`

Additional bor RPC fixes

---

cmd/rpcdaemon/commands/eth_receipts.go

I used `rawdb.ReadCanonicalBodyWithTransactions` to get the list of Transactions associated with the block hash and number. Then used the `txLogIndex` for the particular transaction. Apart from the overhead of using the `api` compared to `rawdb`, I do not see any other optimization. Did I do it wrong?

Fix for issue 4205 (optimize eth_getLogs)

---

eth/stagedsync/stage_headers.go

This partially reverts PR #4611

Ensure no in-memory execution when --experimental.overlay=false

---

eth/stagedsync/stage_headers.go
turbo/stages/sentry_mock_test.go

When some ancestors are downloaded for a new PoS header, the check
```
canExtendCanonical := header.ParentHash == currentHeadHash
```
in `verifyAndSaveNewPoSHeader()`  was too restrictive because the freshly downloaded ancestors might be not canonized yet.

Fix canExtendCanonical when some headers are downloaded

---

cmd/integration/commands/root.go

integration tool don't intent to create db, then easiest way to open db - it's pass mdbx.Accede flag, which allow
to read all options from DB, instead of overriding them

integration to pass mdbx.Accede flag 

---

cmd/downloader/downloader/downloader_grpc_server.go

Sometimes we don't need to build torrent files , which return nil inside of `BuildTorrentFileIfNeed`. This means that sometimes we try to convert a Proto file to an info hash, but we don't have one throwing a nil pointer.

checking if we build torrent file

---

turbo/shards/state_change_accumulator.go

Hopefully this helps with the following error:
```
[INFO] [07-18|15:21:34.158] [10/16 CallTraces] Unwind                from=12616632 to=12616589
[INFO] [07-18|15:21:34.252] [8/16 HashState] Unwinding started       from=12616632 to=12616589 storage=false codes=true
[INFO] [07-18|15:21:34.258] [8/16 HashState] Unwinding started       from=12616632 to=12616589 storage=false codes=false
[INFO] [07-18|15:21:34.330] [8/16 HashState] Unwinding started       from=12616632 to=12616589 storage=true codes=false
[INFO] [07-18|15:21:34.414] [9/16 IntermediateHashes] Unwinding of trie hashes from=12616632 to=12616589 csbucket=AccountChangeSet
[INFO] [07-18|15:21:34.440] [9/16 IntermediateHashes] Unwinding of trie hashes from=12616632 to=12616589 csbucket=StorageChangeSet
[INFO] [07-18|15:21:34.903] …
```

Fix index out of range in (*Accumulator) ChangeStorage

---

cmd/integration/commands/stages.go
eth/stagedsync/default_stages.go
eth/stagedsync/stage_log_index.go
eth/stagedsync/stage_log_index_test.go

Integration stage_log_index --block=N is currently ignored. This change ensures that stage_log_index stops at the specified block.

Support block parameter for integration stage_log_index

---

Makefile

they adding confusion to speed tests and some future version of MDBX will have slower asserts version. 
will enable it back in devel after 1 more version of MDBX (in couple months), by independent PR with speed test

disable asserts in devel 

---

turbo/shards/state_change_accumulator.go

Continuation of PR #4738.
Consider `(a *Accumulator) ChangeStorage()` method. `storageChangeIndex` is used to access `accountChange.StorageChanges`. But there is a condition in the beginning of the method when `accountChange` might be replaced with a new instance of `remote.AccountChange`. In that case the previous `storageChangeIndex` for that address is no longer relevant and would point to non-existent `StorageChanges`.

Still fixing index out of range in (*Accumulator) ChangeStorage

---

cmd/sentry/sentry/sentry_multi_client.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go

fix for https://github.com/ledgerwatch/erigon/issues/4688 
Inuse space at goerli during stage 6/16 
pprof data before patch were similar to https://github.com/ledgerwatch/erigon/issues/4688#issuecomment-1180099181
Another interesting thing: recently were updated `core.ExecuteBlockEphemerally`. Is that correct that it's called during syncing?

fixed passing of raw byte slices to tx processing

---

core/forkid/forkid_test.go
params/chainspecs/sepolia.json
params/config.go

Refer to https://github.com/ethereum/execution-specs/pull/564

Sepolia MergeNetsplit block

---

cmd/rpcdaemon/commands/eth_subscribe_test.go
cmd/rpcdaemon/rpcdaemontest/test_util.go
cmd/rpcdaemon22/rpcdaemontest/test_util.go
eth/backend.go
eth/stagedsync/stage_headers.go
ethdb/privateapi/engine_test.go
ethdb/privateapi/ethbackend.go
turbo/engineapi/request_list.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/mock_sentry.go
turbo/stages/sentry_mock_test.go
turbo/stages/stageloop.go

Moving all non-stagedsync dependent rpc answers outside stage_headers.go as pre-checks in eth_backend.go.
* Not get spammed with stageloop logs
* Avoid filling the request lists to oblivion while syncing up
* Remove code duplication
* Set up a more readable set of pre-requisites
* better UX
* Being less prone to bugs and more simple code in stage_headers overall.
* Ability to give proper answers to Consensus Layer even if stageloop is busy.

Avoid constantly triggering stageloop when using Engine API

---

cmd/rpcdaemon/commands/trace_adhoc.go

i was doing a pairwise comparison with geth trace and found a discrepancy in vmtrace. consider this request
```
trace_replayTransaction
['0x53546f6ac3d342842acfeeedeca5d66d7fda92acaa5bbc91ef94fd52b6f45a94', ['vmTrace']]
```
the stack divergest after this operation:
```json
{
"cost": 5,
"ex": {
"mem": null,
"push": [],
"store": null,
"used": 298747
},
"pc": 17605,
"sub": null,
"op": "SMOD",
"idx": "161-525-1253-663"
}
```
`SMOD` consumes two items from the stack and puts back one, but here it doesn't return what to push.
here is the same operation after the patch applied:
```json
{
"cost": 5,
"ex": {
"mem": null,
"push": [
"0x48"
],
"store": null,
"used": 298747
},
"pc": 17605,
"sub": null,
"op": "SMOD",
"idx": "161-525-1253-663"
}
```

fix(vmtrace): return value pushed by smod

---

eth/backend.go

for https://github.com/ledgerwatch/erigon/issues/4815

remove only etl-tmp content, but not dir itself

---

eth/stagedsync/stage_headers.go
turbo/stages/sentry_mock_test.go

If Erigon is restarted before it's fully synced, we want to continue with the block execution, etc rather than waiting for CL. Also the previous behaviour was a tad wasteful because `forkPoint` was too early since some previous blocks didn't have a chance to progress to canonical.

Don't wait for CL in initialCycle

---

cmd/sentry/sentry/sentry_multi_client.go

A lot of the issues surrounding this point the finger to the call to `Stream.Raw`, after some digging and moving some code around I found the issue to be where a `Link` is created, this holds a reference to the raw header when it gets queued to be written to the DB.  On a successful write the raw header is then nil'd but the GC doesn't seem to want to mop it up properly.  The code change copies the result from the call to Raw into a new slice, pprof shows the allocation move up a level as expected, but this allocation does look to be mopped up properly.  Unsure if this is anything to do with the re-slicing happening inside Raw or not.
In trialling this locally it looks to stop the heap growing out of control.  Tried on chapel and goerli chains and ran them for about an hour each without …

fix memory leak in HandleInboundMessage

---

cmd/sentry/sentry/sentry_multi_client.go

Parithosh's teku-erigon node on MSF10 is stuck at a certain block with the following logs:
```
[WARN] [07-25|10:53:30.761] Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
[EROR] [07-28|09:24:30.643] gasprice.go: getBlockPrices              err=nil
[EROR] [07-28|09:24:30.643] gasprice.go: getBlockPrices              err=nil
```
This extra logging will give us more clues to what's going on.

Log data if cannot decode BlockBodiesPacket66

---

cmd/erigon/main.go
cmd/utils/flags.go
go.mod
testing.yaml
turbo/cli/default_flags.go
turbo/cli/flags.go

`--config-file` will allow for Erigon to accept a YAML file with flags, as specified in #4863 
Also added a log for all the http.api APIs being used

Adding config-file flag

---

eth/stagedsync/stage_headers.go

A couple of corrections to PR #4812:
1. Don't wait for the downloader when `schedulePoSDownload` doesn't actually schedule it.
2. Use `headerHash` rather than parent hash as the check for downloader success in `verifyAndSaveNewPoSHeader` since `verifyAndSaveDownloadedPoSHeaders` uses `downloaderTip`, set to `headerHash`, to report bad blocks.

Improve error handling for the non-delayed PoS downloader

---

cmd/devnettest/rpcdaemon/daemon.go
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/main.go

With this change `rpcdaemon` does not start an Engine API server, only `erigon` itself does. This prevents a conflict [reported](https://discord.com/channels/687972960811745322/687972960811745326/1003409967493156874) on Discord.

Don't start engine API in standalone rpcdaemon

---

cmd/rpcdaemon/cli/config.go

This is a small post-fix for PR #4890, which enables WebSocket on the auth RPC endpoint indiscriminately.

Fix auth RPC logging

---

core/genesis.go

`panic: database contains incompatible genesis (try with --chain=ropsten)`

Better error for incompatible chain config

---

cmd/sentry/sentry/sentry_multi_client.go

This reverts PR #4850 since it clogs the logs. But here's a example of the problematic block bodies packet:
[PR_4850_message.txt](https://github.com/ledgerwatch/erigon/files/9258576/PR_4850_message.txt)

Revert "Log data if cannot decode BlockBodiesPacket66 (#4850)"

---

README.md
cmd/rpcdaemon/cli/config.go
docker-compose.yml
turbo/cli/default_flags.go
turbo/cli/flags.go

After PR #4887 `rpcdaemon` does not listen on the Engine API port – only `erigon` does.

Remove authrpc.* flags from rpcdaemon

---

cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_block_test.go
cmd/rpcdaemon/rpcservices/eth_backend.go
cmd/rpcdaemon22/commands/trace_filtering.go
cmd/rpcdaemon22/rpcservices/eth_backend.go
eth/stagedsync/stage_issuance.go
turbo/services/interfaces.go
turbo/snapshotsync/block_reader.go

Addressing the issue in #4755. We are now reading the block bodies from the `blockreader`

Transaction count fix

---

cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon22/commands/trace_filtering.go
rpc/handler.go

A little bit of guesswork and my first foray into Golang... It has fixed the error case I was exhibiting with some trace_filter requests on polygon (same as #4784) and seems to be running well beyond. Should return a trace (or error) for each transaction and not fail mid-way through the batch of transactions.
maybe
fixes #4838 
fixes #4784

Fix rpc json #4838

---

ethdb/privateapi/ethbackend.go
turbo/engineapi/fork_validator.go

This PR contains a small UX improvement: not spamming the stageloop when fcu is already set to the fields provided. and i also removed a condition from the safety check for non-canonical block bodies in Fcu. lastly, i also removed code duplications. hive tests were not affected.

UX improvement for pre-merge sync with Teku

---

rpc/types.go
turbo/rpchelper/helper.go

Added `latestExecutedBlockNumber` which will return the plainstate block number.

new rpc block number

---

turbo/snapshotsync/block_reader.go

This tiny PR fixes a correctness bug in `BlockReaderWithSnapshots::HeaderByHash`. `HeaderByHash` should stop at the first in-segment match. Otherwise, the result is always whatever the last loop iteration found.
I tested manually with a throw-away test case against an archive node database. Without the fix, `HeaderByHash` always returns `nil` unless the header hash happens to be in the oldest snapshot segment.
Should I write a test for this? If yes, how? I couldn't find a unit-testing / test fixture setup for `BlockReaderWithSnapshots`.

snapshotsync: HeaderByHash segment loop should break on result (tiny)

---

cmd/rpcdaemon/commands/eth_filters_test.go
turbo/rpchelper/filters.go
turbo/rpchelper/logsfilter.go

This time the issue was replicated in the test first to confirm what the problem was.
Opted to clone the maps and return them whilst the mutex is held rather than use the mutex from within the call to `SubscribeLogs` and `UnsubscribeLogs` directly as it seemed to be a little hacky, although likely more performant.  Happy to change the code to suit if that's a problem.
Created to solve #4893

rpc: concurrent map issue with log subscription fix

---

cmd/rpcdaemon/cli/config.go

```
notification about new blocks (state stream) doesn't work now inside erigon - because
erigon does send this stream to privateAPI (erigon with enabled rpc, still have enabled privateAPI).
without this state stream kvcache can't work and only slow-down things
```

disable StateCache when rpcdaemon when embedded

---

cmd/rpcdaemon/commands/eth_system.go

See [4918](https://github.com/ledgerwatch/erigon/issues/4918)
big.Int's Add method will save the result to self, since oracle.SuggestTipCap() might come from [gpo.lastPrice](https://github.com/ledgerwatch/erigon/blob/7e2d46cbe42c958ec541bb1837cc1e351eaf08ef/eth/gasprice/gasprice.go#L153), this will change all following rpc result.

fix eth_gasPrice RPC issue.

---

README.md

docs: add `--authrpc.port` flag to instructions to run multiple instances on the same host

---

cmd/rpcdaemon/commands/send_transaction.go

Issue: https://github.com/ledgerwatch/erigon/issues/4974
The nil pointer is because the `chainConfig` is not initialized at the time of accessing it and validating `chainID`. 
I have moved `chainID` validation logic after the `chainConfig` initialization.

cmd: make sure chain config is initialized before accessing it

---

cmd/sentry/sentry/sentry_grpc_server.go

Explicitly take and release the read lock to prevent the race.

fix(sentry): add locks in sentry grpc (#4981)

---

Dockerfile

Checking the block number in a kubernetes readinessProbe requires the following long command:
```
wget -q -O- --header='Content-Type:application/json' --post-data='{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://0.0.0.0:8545 |  grep -oE '"number":"0x.[a-f0-9]+"' | awk -F\" '{printf("%d\n", $4)}'
```
Add `jq` and `curl` commands to Dockerfile
Able to reduce above command to the following:
```
curl -s -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://0.0.0.0:8545 | jq -rC .result.number | xargs /usr/bin/printf "\%d\n"
```

feat: Dockerfile apk add curl jq

---

README.md
cmd/integration/commands/stages.go
ethdb/prune/storage_mode.go
turbo/cli/flags.go

Pruning unnecessary receipts for POS by setting default prune receipts before deposit contract block

Pruning Receipts Default

---

cmd/rpcdaemon/commands/tracing.go

This PR aims to fix this issue: https://github.com/ledgerwatch/erigon/issues/4340
The `blockWithSenders` method returns a `nil` block on a condition (I'm still investigating to know why that happens. Maybe some blocks are missing).
This PR prevents the crash by making sure the error returns for an invalid/missing block until I find out why it happens

Fix for custom tracer method crashing

---

eth/stagedsync/stage_interhashes.go

We are getting header using a header number from snapshots/db and then we get its hash. After getting the header hash we saved it into `headerHash` to then fetch a header from snapshots/db using the hash. Retrieving the header again is pointless.

No refetching Header

---

.golangci.yml
cmd/observer/database/db_retrier.go
cmd/sentry/sentry/sentry_api.go
cmd/sentry/sentry/sentry_grpc_server.go
cmd/sentry/sentry/sentry_multi_client.go
consensus/clique/clique.go
consensus/parlia/utils.go
p2p/dial.go
p2p/discover/table.go
rpc/subscription.go

Assume these are fine to ignore. Anyway, I think there's value of having the linter turned on so no violating code is checked in without explicit ignores.

Enable gosec linter

---

internal/ethapi/api.go

currently appears like this
`"transactions": [
null
],`
should be:
`"transactions":[]`

changed 1 to 0 to avoid null

---

cmd/integration/commands/stages.go
eth/stagedsync/stage_mining_finish.go
turbo/stages/mock_sentry.go

it may cause light-client state verify failed.

Fix in-flight sealing task not abort when next sealing task coming

---

ethdb/privateapi/ethbackend.go

This should help us with investigation if we ever produce an invalid PoS block.

Log RLP of built PoS blocks

---

core/rawdb/bor_receipts.go

Whenever we remove Bor receipts we keep their logs inside of kv.Logs, which leads to unnecessary logs being kept with no receipt.

added removal of bor logs when deleting receipts

---

.github/workflows/ci.yml
hive/exclusions.json

In the reporting stage, add the ability to ignore failing tests. If an excluded test passes, we include it in the successes, otherwise it goes to the 'skipped' count on failure, which should mean CI remains green for expected failures.
The json file containing excluded tests is currently a WIP, awaiting more detail on expected failures. (If anyone has an extensive list of these please comment and I will update the PR).

Hive - test exclusions

---

Makefile

On my mac doesn't work `date -Iseconds`, i think it's better use `date +"%Y-%m-%dT%H:%M:%S:%z"` instead

Cross-platform iso-8601 date

---

eth/stagedsync/stage_headers.go

Calculate the amount of time left for downloading snapshots. If download speed is 0 we default to a huge time

predict download time left

---

turbo/stages/stageloop.go

This reverts a clean-up of `MiningStep` introduced by PR #5162.
Though `tx.Rollback()` seem to be unnecessary there due to `defer tx.Rollback()` a few lines before, without it I get the following error in tests on macOS:
```
--- FAIL: TestIHCursor (0.00s)
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
panic: sync: WaitGroup is reused before previous Wait has returned
```

Revert recent change to MiningStep

---

hive/exclusions.json

Based on our currently failing hive tests, this is a list of test which look like we should (for now) exclude so that our CI can go green!

feat(hive): add full exclusions list

---

cmd/sentry/sentry/sentry_multi_client.go
eth/stagedsync/stage_headers.go
params/chainspecs/goerli.json
params/chainspecs/kiln-devnet.json
params/chainspecs/ropsten.json
params/chainspecs/sepolia.json
params/config.go

PoW block gossip is disabled for networks that have passed through the Merge, so we should go straight into PoS sync.
See also https://github.com/ethereum/go-ethereum/pull/24538.

Disable PoW sync for networks that have already passed through the Merge

---

cmd/rpcdaemon22/commands/engine_api.go

Discovered by @MariusVanDerWijden:
Hey all been fuzzing the clients a bit, I can crash the erigon handler very easily
```
EROR[08-25|20:08:54.674] RPC method engine_newPayloadV1 crashed: runtime error: slice bounds out of range [64:0]
[service.go:217 panic.go:884 panic.go:153 type_utils.go:36 engine_api.go:168 value.go:584 value.go:368 service.go:222 handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1594] 
```

Prevent slice bounds out of range on invalid payload.LogsBloom

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
Dockerfile.release
Makefile

Upstreams the improvement from the maticnetwork/erigon fork
to add a goreleaser workflow that will build and release
a docker image for both arm and amd64.
**Note**: This will only work if the GHA secrets `DOCKERHUB` and `DOCKERHUB_KEY` are added in
order to push to https://hub.docker.com/r/thorax/erigon.

chore: add multi-arch goreleaser workflow

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon22/cli/config.go
core/asm/compiler.go
node/rpcstack_test.go

It's [more efficient](https://stackoverflow.com/questions/34383705/how-do-i-compare-strings-in-golang) to use `strings.EqualFold()` for [string comparison](https://github.com/dgryski/go-perfbook/blob/master/performance.md#common-gotchas-with-the-standard-library) than the normal operator. Especially when you have to lower or upper case one of the strings first.

Use strings.EqualFold for string comparison

---

cmd/downloader/readme.md
common/debug/experiments.go
eth/stagedsync/sync.go

Adds ability to stop after a stage instead of just before a stage.
This will allow users to use something like:
`STOP_AFTER_STAGE=Finish erigon`
And erigon will stop after a full cycle of syncing.
closes #5201

Add STOP_AFTER_STAGE environ

---

core/rawdb/accessors_chain.go
turbo/snapshotsync/block_snapshots.go

Changed it so `headerBuf` was rlp decoded with `headerBuf[1:]` solving issue of "element is larger than containing list"

Small capacity

---

core/vm/eips.go
core/vm/jump_table.go
core/vm/opcodes.go

[EIP-3855](https://eips.ethereum.org/EIPS/eip-3855) is part of [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).

EIP-3855: PUSH0 instruction

---

eth/stagedsync/stage_mining_create_block.go

Currently if a transaction doesn't pass a check we do this `transactions = transactions[:1]` instead of this
`transactions = transactions[1:]` which would actually get rid of the transactions. This is causing us to keep looping since we fail the same check multiple times #5239

taking bad transaction out the slice

---

eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/stageloop.go

Add specific channel for headers shutdown (rather than relying on payload status - which was blocking due to being attempted to be written multiple times and preventing clean shutdown).

fix(headers): signal cleanly shutdown headers and allow exit #5007

---

.github/workflows/release.yml
Makefile

Use the automatically provided GITHUB_TOKEN secret.
Currently only has the default permissions which should let
it read the tag as needed.
Commented permissions would allow it to also automatically write
a github release, but will see if it works without that for now
for minimimum change.

chore: goreleaser workflow fix

---

cmd/rpcdaemon/commands/eth_block.go

```
{
"id": 420,
"jsonrpc": "2.0",
"method": "eth_getBlockTransactionCountByHash",
"params": ["0x00017db1000010f480725ae9e96e8b613017af0de144037899a46118731e57b7"]
}
```
```
{
"jsonrpc": "2.0",
"id": 420,
"error": {
"code": -32000,
"message": "block 00017db1000010f480725ae9e96e8b613017af0de144037899a46118731e57b7 not found"
}
}
```
```
{
"jsonrpc": "2.0",
"id": 420,
"result": null
}
```
```
{
"jsonrpc": "2.0",
"id": 420,
"result": null
}
```

Fix compatibility of eth_getBlockTransactionCountByHash

---

Makefile

Add makefile command to build the erigon docker image locally, and run hive against it.
Takes 2 env vars - OUTPUT_DIR (where the test results will be stored), and SIM (ethereum/sync, ethereum/engine etc.).

feat(hive): add makefile command to run hive locally

---

eth/backend.go

For some reason recent PR #5212 flipped the logic. It looks to me that the change there was accidental. It stands to reason that new transactions should prompt mining instead of delaying it by resetting the timer.
This change fixes Hive test "PrevRandao Opcode Transactions".

New transactions should prompt mining instead of postponing it

---

ethdb/prune/storage_mode.go

change the minimum required blocks to the blocks where the first deposit has occured.
see also #5026

fix: relax deposit contract prune to first deposit

---

ethdb/prune/storage_mode.go

This reverts commit d8c9b1151d574491baf14e208edabe72c1c65d89.
Reverting PR #5295 since it'd break backward compatibility. For instance, Erigon [v2022.09.01](https://github.com/ledgerwatch/erigon/releases/tag/v2022.09.01), started with `--prune=hrtc`, would've failed to start after upgrade.

Revert "fix: relax deposit contract prune to first deposit (#5295)"

---

hive/exclusions.json

These tests typically pass fine on  https://hivetests2.ethdevops.io, but fail in our CI for some reason.
In any case, I'd like Erigon's Hive status to be finally green – otherwise everybody simply ignores it if it's constantly red. Meanwhile we'll keep looking into fixing the remaining Hive tests.

Disable Hive tests that currently fail in CI

---

rpc/types.go

We are missing a return causing an error since it tries turning a string word into a hex number

missing return

---

core/blockchain.go
eth/stagedsync/stage_execute.go

Separating Bor block execution from normal block execution to avoid causing errors in the future

separated bor block execution

---

rpc/handler.go

Reverts ledgerwatch/erigon#5345

Revert "cancel context before waiting for waitgroup to avoid deadlock in RPC …"

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/erigon_system.go
turbo/rpchelper/rpc_block.go

After "the merge" latest will turn into the latest ForkchoiceHead block number, while some people might still want to get the latest executed block number from Erigon. That won't be possible since `eth_blockNumber` will not return the latest executed so I have added `erigon_executedBlockNumber` which returns the latest executed block number.

added a way to get latest executed block post POS

---

eth/stagedsync/stage_headers.go

Users think this log is an error, so I changed it a little so they understand that we are actually downloading the missing fork choice header

added downloading to avoid user panic

---

ethdb/privateapi/logsfilter_test.go
turbo/rpchelper/filters.go
turbo/rpchelper/filters_test.go

Created to tackle #4030
The shared log subscription that handles logs and passes them back to the filters for the consumer was losing track of the "all addresses" and "all topics" when another subscription came in causing the aggregates count of AllAddresses or AllTopics to rise above 1.  This created a scenario where no subscriptions would receive any logs at all as the first check for AllAddresses would fail so the code checks the Addresses collection which is empty so nothing gets through at all.

allow multiple log subscriptions at the same time

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/cli/httpcfg/http_cfg.go
cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/corner_cases_support_test.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/debug_api_test.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_api_test.go
cmd/rpcdaemon/commands/eth_block_test.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_callMany_test.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/commands/eth_filters_test.go
cmd/rpcdaemon/commands/eth_ming_test.go
cmd/rpcdaemon/commands/eth_system_test.go
cmd/rpcdaemon/commands/send_transaction_test.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_adhoc_test.go
cmd/rpcdaemon/commands/tracing.go
cmd/rpcdaemon/commands/txpool_api_test.go
rpc/rpccfg/rpccfg.go
turbo/cli/default_flags.go
turbo/cli/flags.go
turbo/transactions/call.go
turbo/transactions/tracing.go

This PR solves #5389 issue
* **What kind of change does this PR introduce?**
Make configurable emv call timeouts.
* **Does this PR introduce a breaking change?**
No, if flag is not provided by the user, the default value is used.

add EVM call timeout flag

---

consensus/bor/bor.go

I tried to debug an Erigon node syncing on Polygon/Bor, with a very slow `Inserting headers` stage. After digging a bit, it seems that it took an increasingly high duration to get a `snapshot` at a each new block for Bor's consensus. Most of the time came from writing it in DB, although it seems to be only ever read for block numbers corresponding to checkpoints.
The solution is thus to limit the writes only on those blocks.
It drastically improved by sync perfs:
The left "flat" line is when syncing on latest release, and the right one is with my fix

bor/consensus: Only write Snapshots to DB for checkpoints

---

params/chainspecs/mainnet.json

Similar to geth release [1.10.25](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.25).

Disable PoW sync for mainnet

---

cmd/rpcdaemon/commands/engine_api.go
cmd/rpcdaemon22/commands/engine_api.go

Nimbus incorrectly sends non-zero TerminalBlockHash after The Merge, leading to
"the execution layer has a wrong terminal block hash. expected 0x55b11b918355b1ef9c5db810302ebad0bf2544255b530cdce90674d5887bb286, but instead got: 0x0000000000000000000000000000000000000000000000000000000000000000\"}"

Don't check TerminalBlockHash in exchangeTransitionConfiguration

---

core/systemcontracts/upgrade.go

Fixes #5418.
The system-contract upgrade logic ported from upstream BSC worked for BSC, but was subtly flawed when used under Erigon. This caused sync to stall at block `22885040` on Chapel, the first time the upgraded contract was called. This PR corrects the problem.
Details:
The upgrade logic ported from BSC does not presume that the contract already exists; instead, it assumes that setting the contract's code will work for both existent and non-existent accounts. This assumption works in upstream geth, but in Erigon, contracts don't exist until `CreateAccount` is called on them (which wasn't happening here.)
Gibbs was the first upgrade that tried to "upgrade a contract into existence" by setting its code; previous upgrades were only updating system contracts that had existed since …

Ensure system contracts created by upgrades get persisted correctly

---

cmd/integration/commands/stages.go
core/block_builder_parameters.go
eth/backend.go
eth/stagedsync/stage_mining_exec.go
ethdb/privateapi/ethbackend.go
turbo/stages/mock_sentry.go

created to help diagnose issue #5430.
It appears that the CL is requesting the payload immediately after sending the ForkchoiceUpdated request to build a new block.  These logs should help confirm/deny that theory.

increased logging around POS mining

---

cmd/erigon/main.go
cmd/state/commands/erigon22.go
cmd/state/commands/erigon23.go
cmd/state/commands/global_flags_vars.go
go.mod
go.sum

Implemented logging to different files of error and user logs along with stdout. 
Default log directory is /var/log/erigon
Data printed to stderr doesnt go to this logs.
Requires merge of https://github.com/ledgerwatch/log/pull/5

added separated user/error log files to erigon 22/23

---

cmd/rpcdaemon/commands/erigon_api.go

open `erigon_blockNumber`  feature API that has been implemented. Support request with params options like`safe`/`latest`/`finalized`/`earliest`/`pending`.

open `erigon_blockNumber` API

---

core/blockchain.go

Still trying to sync Erigon with Polygon mainnet ; this time I found an issue when trying to save state-sync "receipts". The issue was that the TransactionIndex of the receipt wasn't set, although it was used in `WriteBorReceipt` https://github.com/ledgerwatch/erigon/blob/390108f352dffa3e0ff10c8997bd23631c3a80dd/core/rawdb/bor_receipts.go#L88 ; which might be overwriting other receipts, or cause any other issues.
BTW, in `WriteBorReceipt` linked above, it seems that receipts are `cbor` encoded, although they are decoded with an RLP decoder. Is there any issue there?

Add a `TransactionIndex` for StateSync receipt in Bor

---

core/types/block.go
core/types/block_test.go
eth/stagedsync/stage_bodies.go
rlp/decode.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go
turbo/stages/bodydownload/body_test.go

Addresses the OOM issue during the block bodies stage by using a bucket which is flushed at the end of each run of the bodies stage.  The bucket is used to effectively replace the slice that held on to bodies as they were downloaded.
The original idea of using an ETL for this fell a little short as it didn't allow for easy checking of whether we already had a block on resuming the process, so switching to the bucket won out here.
A couple of other bits are added in there too:
- easing the understanding of the code by not relying so much on block numbers - requested low to get positions in slices.  These are replaced with maps which makes the code much easier to reason about.
- the existing code had a path for re-requesting bodies but would never be hit.  The changes here always go back to …

OOM fix for bodies stage

---

.github/workflows/stale-issues.yml

- runs at 1:30am daily
- exempts issues/PRs assigned to core team members
- marks issues/PRs with no activity for 40 days as stale
- if an issue remains stale for 7 days, it is then closed

feat(ci): run daily job to mark and close stale issues

---

eth/stagedsync/stage_mining_create_block.go

One quick fix for Erigon-built blocks containing too few transactions.
See also Issues #5435 & #5451.

Block builder: bump maxTransactions to 1000

---

hive/exclusions.json

The exclusions are the tests failing due to reasons other than timeout (which is now fixed in the hive branch in my fork which is used to build thorax/hive)

feat(hive): update exclusions after timeouts fix

---

ethdb/privateapi/ethbackend.go

Otherwise the logs are spammed by "stage loop is busy" when Erigon is catching up with the chain tip.

Demote "stage loop is busy" to debug

---

eth/gasprice/gasprice.go

If we don't find the block we are returning an error message and the err (which is nil) instead of returning nil
#5543

warning of missing block and returning nil if no err

---

eth/stagedsync/exec3.go

let's assume as known issue: "can't interrupt prallel exec" (but can run "integration stage_exec --block=N")

erigon3: allow commit in parallel exec  

---

cmd/state/exec3/state.go
cmd/state/exec3/state_recon.go
core/state/rw22.go
eth/stagedsync/exec3.go
eth/stagedsync/stage_execute_test.go

i see that producer of `workCh` does produce faster than consumers consume. it means we can move some work from consumers to producer
and also remove txTask.Header field because have txTask.Block

erigon3: move tx.AsMessage() out of critical path

---

cmd/lightclient/sentinel/handlers/heartbeats.go
cmd/lightclient/sentinel/sentinel.go

Added no disconnecting with metadata requests, and we answer now with a bogus status call and proper prefix for both status and metadata request. This changes allows for nimbus nodes to connect to us and actually stay connected.

fixed disconnecting and now nimbus happy with us

---

k8s/base/eth66-peering-tcp.yaml
k8s/base/eth66-peering-udp.yaml
k8s/base/http.yaml
k8s/base/kustomization.yaml
k8s/base/metrics.yaml
k8s/base/snap-sync-tcp.yaml
k8s/base/snap-sync-udp.yaml
k8s/base/statefulset.yaml

Adds bare minimum, base kubernetes manifests for running erigon in kubernetes.
Does not include crucial beacon chain, persistent volumes, etc.
I currently use this as a base for 5 erigon Pods, each with an erigon execution node and prysm beacon node, along with 10 rpcdaemon pods, a TLS-terminated Ingress with a cert-manager issued TLS certificate. I would like to give back to the community then use this as an upstream kustomized base.  See: https://kustomize.io

feat: add base kubernetes manifests

---

core/vm/evm.go

[Nethermind/Chains/xdai.json](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/xdai.json) does not contain `maxCodeSize`, so it defaults to 2^63-1 (virtually unlimited).
https://gnosisscan.io/tx/0x3bfa6631d0a3a845c16674f56771de30bc840e828ea8ead21dbea04541a30173 is a transaction example on Gnosis Chain where the code size exceed the mainnet `maxCodeSize` of 24576.

No MaxCodeSize limit for AuRa

---

Makefile

Issue : https://github.com/ledgerwatch/erigon/actions/runs/3202785385/jobs/5232131489
Reason : There is no go-releaser version with v1.18.5
https://hub.docker.com/r/goreleaser/goreleaser-cross/tags
Updated it to v1.18.1 which we use in matic-fork/erigon.

Fix go-releaser version

---

consensus/aura/config.go
consensus/aura/validators.go

This fixes the following panic for Gnosis Chain on the validator switch at block 9186425:
```
panic: method 'getValidators' not found
goroutine 90 [running]:
github.com/ledgerwatch/erigon/consensus/aura.(*ValidatorSafeContract).getListSyscall(0x14000ed9358, 0xd40004bf620)
github.com/ledgerwatch/erigon/consensus/aura/validators.go:634 +0x258
github.com/ledgerwatch/erigon/consensus/aura.(*ValidatorSafeContract).epochSet(0x16?, 0x20?, 0x8c2c79, {0xd4002d77180, 0x25f, 0x25f}, 0x11400fac7ee8?)
github.com/ledgerwatch/erigon/consensus/aura/validators.go:453 +0xdc
github.com/ledgerwatch/erigon/consensus/aura.(*ValidatorContract).epochSet(0x140006ae980?, 0x38?, 0x6f9d00000000c28e?, {0xd4002d77180?, 0x108acc108?, 0x40?}, 0x14000618000?)
```

Use NewValidatorSafeContract in ValidatorContract

---

eth/stagedsync/stage_execute.go
ethdb/olddb/mapmutation.go

Revert to older batch size logic to keep memory usage down during execution phase and closer to the --batchSize flag size.
Spotted a "leak" in key generation as well.  The unsafe pointer keeps the byte slice around for as long as the batch is not committed, takes up a fair chunk of memory surprisingly doing that so removed the unsafe pointer usage giving the GC some chance to clean up along the way.
Moved the batch rollback into a defer func call rather than allowing them to stack in the for loop.  If this isn't going to work just let me know and can change it back.

revert execution batch size logic to size on disk

---

turbo/rpchelper/filters.go

When the filter is in the onNewTxs function, the subscription function exits and no longer receives information from the msg channel. In this case, the unsubscribe_xxx function is triggered, which will cause filter.mu read and write locks to enter a deadlock state

fix deadlock in filters.go

---

eth/tracers/jsvm.go

fix:
fix for issue #5723  type conversion bug by adding check. `expValue` should be `uint64[]`.

fix: issue #5723 type conversion bug

---

eth/stagedsync/README.md

[RPC calls] link path (../../cmd/rpcdaemon/Readme.md) corrected to (../../cmd/rpcdaemon/README.md)

Correct failed link in README.md

---

eth/stagedsync/all_stages.go

hi! 
this pr adds more sync stages to the prometheus metrics. node now shows 
```
sync{stage="account_history_index"} 15742138
sync{stage="block_hashes"} 15742138
sync{stage="bodies"} 15742138
sync{stage="call_traces"} 15742138
sync{stage="cumulative_index"} 15742138
sync{stage="execution"} 15742138
sync{stage="finish"} 15742138
sync{stage="hash_state"} 15742138
sync{stage="headers"} 15742138
sync{stage="intermediate_hashes"} 15742138
sync{stage="log_index"} 15742138
sync{stage="senders"} 15742138
sync{stage="snapshots"} 15742138
sync{stage="storage_history_index"} 15742138
sync{stage="translation"} 0
sync{stage="tx_lookup"} 15742138
sync{stage="verkle_trie"} 0
sync{stage="watch_the_burn"} 0
```

add more sync stages to metrics

---

core/blockchain.go

AuRa storage changes made by `onEpochBegin` should be finalized. Otherwise, `SSTORE` cost might be incorrect in block transactions when [EIP-2200](https://eips.ethereum.org/EIPS/eip-2200) is active. https://gnosisscan.io/tx/0xa6d45d903c977ad237165737ebc4e34fb7756675719d112a199af858bb1275e0 is an example of a transaction on Gnosis Chain whose gas used was previously calculated incorrectly.

FinalizeTx after engine.Initialize

---

cmd/rpcdaemon/commands/eth_receipts.go
core/rawdb/accessors_chain.go
core/rawdb/bor_receipts.go
core/types/bor_receipt.go

Fixes a nil-pointer dereference in Decode when attempting to call `getTransactionReceipt` / `getBlockReceipts` on blocks containing stateSync events.

Return bor receipts correctly in getTransactionReceipt and getBlockReceipts

---

eth/stagedsync/exec3.go

Fixes
```
eth/stagedsync/exec3.go:885:6: ineffectual assignment to txs (ineffassign)
b, txs = nil, nil
^
```

Make lint happy

---

cmd/rpcdaemon/commands/trace_adhoc.go
core/vm/evm.go
core/vm/gas_table.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/jump_table.go
core/vm/memory_table.go
core/vm/opcodes.go
params/protocol_params.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/23976

core/vm: Rename SHA3 instruction to KECCAK256

---

cmd/rpcdaemon/commands/eth_filters.go
turbo/rpchelper/logsfilter.go

Like the newPendingTransaction event, the logs event also has the potential for deadlock when unsubscribed

fix potential deadlock in eth_filters logs event

---

README.md

It seems this got changed around so that `temp` is used but the docs were not changed.

etl-temp location changed so cleaning up docs

---

cmd/state/exec3/state.go
cmd/state/exec3/state_recon.go
core/blockchain.go
core/state_processor.go
core/vm/evm.go
core/vm/interpreter.go

This fixes gas used in https://gnosisscan.io/tx/0x8f3b839a3d179102084a58dc4c3ec91fe13bb00cc1450cd69d22add7f25444e3

AuRa system calls to Certifier should be const

---

cmd/devnet/commands/all.go
cmd/devnet/commands/block.go
cmd/devnet/commands/event.go
cmd/devnet/commands/request.go
cmd/devnet/commands/tx.go
cmd/devnet/devnetutils/utils.go
cmd/devnet/devnetutils/utils_test.go
cmd/devnet/models/model.go
cmd/devnet/node/node.go
cmd/devnet/requests/tx.go
cmd/devnet/services/block.go
cmd/devnet/services/event.go

- Added listening methods for WebSocket subscriptions 
- Listened for new blocks using the newHeads method to determine when to look for a transaction
- Added new util methods and tests for them
- Simplified communication to the user upon initiating the devnet tool

Setup web socket endpoints to listen for new transactions after sending

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/otterscan_api.go
cmd/rpcdaemon/commands/otterscan_block_details.go
cmd/rpcdaemon/commands/otterscan_contract_creator.go
cmd/rpcdaemon/commands/otterscan_default_tracer.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/otterscan_has_code.go
cmd/rpcdaemon/commands/otterscan_search_backward.go
cmd/rpcdaemon/commands/otterscan_search_backward_multi_test.go
cmd/rpcdaemon/commands/otterscan_search_backward_test.go
cmd/rpcdaemon/commands/otterscan_search_forward.go
cmd/rpcdaemon/commands/otterscan_search_forward_multi_test.go
cmd/rpcdaemon/commands/otterscan_search_forward_test.go
cmd/rpcdaemon/commands/otterscan_search_multi.go
cmd/rpcdaemon/commands/otterscan_search_test.go
cmd/rpcdaemon/commands/otterscan_search_trace.go
cmd/rpcdaemon/commands/otterscan_trace_contract_creator.go
cmd/rpcdaemon/commands/otterscan_trace_operations.go
cmd/rpcdaemon/commands/otterscan_trace_touch.go
cmd/rpcdaemon/commands/otterscan_trace_transaction.go
cmd/rpcdaemon/commands/otterscan_transaction_by_sender_and_nonce.go
cmd/rpcdaemon/commands/otterscan_transaction_error.go
cmd/rpcdaemon/commands/otterscan_types.go

Following our previous discussion on erigon's discord, this PR requests to upstream all Otterscan modifications to erigon's repo.
That decision comes after getting feedback from lots of users at events this year, and although it may introduce some friction for development, it will make integrators life easier by having all our modifications available out of box, e.g., dappnode users will get our RPCs since their official packages are built from erigon repo.
I'm submitting the source-code as-is, please let me know if you think there is a better code organization.
The current set of modifications comprises only new RPCs. There are some proposals for extra-stages that would add new tables, but they are still WIP and will be submitted separately in future after more testing.

Upstream all Otterscan patches to devel

---

core/state_processor.go

Correction to PR #5873.
See [Nethermind's code](https://github.com/NethermindEth/nethermind/blob/1.14.5/src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxCertifierFilter.cs#L57).

Only zero-gas transactions may be service ones

---

core/types/block.go
core/types/gen_header_json.go
rlp/encode.go

Also cherry-pick https://github.com/ethereum/go-ethereum/pull/24666.

Simplify Header.EncodeRLP

---

cmd/rpcdaemon/commands/eth_call.go
turbo/rpchelper/helper.go

Will gain more perf improvements when the change for kvcache goes in from erigon-lib.
Hopefully can be validated with hive?  My main concern is the re-use of the state reader, I couldn't find any manipulation of it so it looks safe to re-use.

eth_estimateGas performance tweaks

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_system.go
eth/gasprice/feehistory_test.go
eth/gasprice/gasprice.go
eth/gasprice/gasprice_test.go

Code news up an oracle for every call so existing cache checks always came back as 0.  Moved cache up a layer and pass in via the new `gasprice.Cache` interface.  Looked at putting the oracle instance onto the ethApi itself to re-use it that way, but the backend transaction made it a little hard work as we can't re-use that.  This seemed cleaner but happy to take feedback.
Locally takes me from ±2.5k rps to ±43k rps so quite a difference there.  (k6 with 1000 virtual users)

eth_gasPrice performance tweaks

---

core/types/block.go

For example, see https://gnosisscan.io/block/24938312.
This fixes the following errors:
```
t=2022-11-11T12:39:01+0000 lvl=dbug msg="Handling incoming message" stream=RecvMessage err="newBlock66: too large block difficulty: bitlen 128"
t=2022-11-11T12:39:01+0000 lvl=dbug msg="Handling incoming message" stream=RecvMessage err="newBlock66: too large block difficulty: bitlen 128"
t=2022-11-11T12:39:01+0000 lvl=dbug msg="Handling incoming message" stream=RecvMessage err="newBlock66: too large block difficulty: bitlen 128"
```

Block difficulty can be really big on Gnosis Chain

---

turbo/app/import.go
turbo/app/init.go
turbo/app/make_app.go

Another postfix to PR #6047. This fixes `--datadir` flag passed to `erigon init`. See also https://github.com/ethereum/go-ethereum/pull/24751.

Restore MigrateFlags

---

cmd/rpcdaemon/commands/eth_accounts.go

Feat: add `eth_exists` endpoint.
By introducing this endpoint, Erigon will fully enable remote execution for pre-EIP158 blocks.

Feat: add eth_exitst endpoint

---

consensus/bor/bor.go
eth/backend.go

In context of https://github.com/ledgerwatch/erigon/issues/5694, this PR adds some fixes and improvement in the mining flow. Also, a relevant change in txpool (present in erigon-lib) is made here: https://github.com/ledgerwatch/erigon-lib/pull/737
The mining module didn't honour the block time as a simple 3 second timer and a notifier from txpool was used to trigger mining. This would cause inconsistencies, at least with the bor consensus. Hence, a geth like approach is used instead for simplicity. A new head channel subscription is added in the `startMining()` loop which would notify the addition of new block. Hence, this would make sure that the block time is being honoured. Moreover, the fixed 3 second timer is replaced by the `miner.recommit` value set using flags. 
When all the …

eth, consensus/bor: fixes and improvements related to mining 

---

cmd/rpcdaemon/commands/eth_call.go

The from field would sometimes be nil causing an error when trying to access it, instead changed it to be an empty address #5882

fixed nil ptr err

---

cmd/sentry/sentry/sentry_grpc_server.go

Fixes an issue where if the peer count didn't change much, we'd send the message to the same peers nearly every time.
We now pick new random peers on every call to
SendMessageToRandomPeers().

SendMessageToRandomPeers() now is truely pseudo-random

---

eth/gasprice/gasprice.go

eth_gasPrice(): A maximum of 3 samples should be taken per block (see sample const)
The getBlockPrices() function takes 3 samples on the first block and one on the others.
In the check s.Len() >= limit  s.Len() after first block will contain 3 samples and so the loop will be executed only one time for each block NOT three times

fix on number of samples for blocks

---

cmd/erigon-cl/cl-core/syncfromcheckpoint.go
cmd/erigon-cl/main.go

Part of https://github.com/ledgerwatch/erigon/issues/5965.
An example logging output shows that we are getting accurate data:
the current finalized checkpoint block: https://beaconcha.in/slot/5180288
the current head block: https://beaconcha.in/slot/5180361
```
INFO[11-20|16:52:36.631] Retrieved status.                        status="&{ForkDigest:[74 38 197 139] FinalizedRoot:[133 83 36 34 8 25 208 12 77 180 192 189 151 179 237 244 192 20 216 226 40 178 142 28 242 91 4 66 250 58 200 92] FinalizedEpoch:161884 HeadRoot:[164 219 216 224 200 71 201 76 70 253 61 144 64 238 11 14 224 173 49 5 107 109 238 32 215 126 85 23 10 170 107 223] HeadSlot:5180361}"
INFO[11-20|16:52:36.631] Current finalized root.                  root=855324220819d00c4db4c0bd97b3edf4c014d8e228b28e1cf25b0442fa3ac85c …
```

Add Status fetching and made sentinel request logic generic

---

consensus/bor/bor.go

Due to a change in a previous [commit](https://github.com/ledgerwatch/erigon/pull/5212/files#diff-335eb65f5a52a99fd4cb182ce6385022828dfc04118b85336754d5a142f45be7R134), the txs and receipts are overridden. This breaks compatibility with bor consensus as the `bor.FinalizeAndAssemble` method returns nil txs and receipts. This PR fixes that.

consensus/bor: return txs and receipts in FinalizeAndAssemble

---

cmd/rpcdaemon/commands/eth_block.go

This PR adds correct miner address to the response of `eth_getBlockByNumber`/`eth_getBlockByHash` API methods.
Currently miner address is returned as zero address (`0x000...000`) for Polygon - https://wiki.polygon.technology/docs/edge/faq/validators/#why-do-the-json-rpc-commands-eth_getblockbynumber-and-eth_getblockbyhash-not-return-the-miners-address .
Unfortunately this behaviour confuses a lot, I've succeeded in restoring the miner address in block related API, want this to be the default behaviour.

added miner address extracting for Bor in block api response

---

core/forkid/forkid_test.go

Feels like there's an issue with the latest hardfork (https://docs.gnosischain.com/specs/hard-forks/21735000), as the fork id didn't change?
Related: https://github.com/NethermindEth/nethermind/pull/4925

test: add fork id tests for Gnosis and Chiado

---

cmd/evm/staterunner.go
core/state_transition.go
core/vm/evm.go
core/vm/interpreter.go
eth/tracers/tracer.go
tests/state_test.go
tests/state_test_util.go

[v11.2](https://github.com/ethereum/tests/releases/tag/v11.2) includes, among other things, tests for [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860): Limit and meter initcode.

Update consensus tests to v11.2

---

.github/workflows/hive-nightly.yml

When running from forks results would need to be uploaded as artifacts and separately parsed. This is no longer true when running as a scheduled job and we can therefore fix and get a speedup by reading the results straight from the workspace.

ci(hive): use run context rather than artifacts for results

---

cmd/rpcdaemon/commands/eth_call.go
core/types/transaction.go
core/vm/evm.go
turbo/transactions/call.go

One simple change to send the header in rather than the body allowing re-use in a loop which saves the copy call when looping.
The other one for a reusable evm seems potentially dangerous so feedback more than welcome on that one, local testing shows it gains me around 6k±rps so if it's safe is a good win, but I feel it will need more work.  I could only validate against goerli chain which seems to always return the same value for eth_estimateGas so if anybody could validate it against another chain that would be awesome.

reusable evm caller for purpose of eth_estimateGas

---

cmd/observer/reports/clients_estimate_report.go
cmd/observer/reports/clients_report.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/sentinel/sentinel/pubsub.go
turbo/stages/headerdownload/header_algos.go

Strings builders have a buffer (slice) that can be pre-allocated

Grow string builders

---

p2p/discover/v5_udp.go

tweak(p2p): trace log level for error from t.matchWithCall

---

cmd/erigon-cl/core/transition/beacon_state_utils.go
cmd/erigon-cl/core/transition/beacon_state_utils_test.go

This is described in: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#compute_shuffled_index. 
I ran the prysm implementation locally to generate the expected outputs: https://github.com/prysmaticlabs/prysm/blob/babfc66c5bc5ca6635fbc7d786e22c8ccdc18c16/beacon-chain/core/helpers/shuffle.go#L73

Add ComputeShuffledIndex algorithm.

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go
cmd/rpcdaemon/commands/erigon_block.go
cmd/rpcdaemon/commands/eth_accounts.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/otterscan_search_trace.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/tracing.go
cmd/state/commands/check_change_sets.go
cmd/state/commands/opcode_tracer.go
core/genesis_test.go
core/state/access_list_test.go
core/state/database_test.go
core/state/history.go
core/state/plain_readonly.go
core/state/state_test.go
core/state_transition.go
core/system_contract_lookup.go
core/systemcontracts/upgrade.go
core/vm/runtime/runtime_test.go
turbo/rpchelper/helper.go
turbo/stages/blockchain_test.go
turbo/stages/mock_sentry.go
turbo/transactions/tracing.go

Works around a flaw in the upgrade logic of the system contracts. Since they are updated directly, without first being self-destructed and then re-created, the usual incarnation logic does not get activated, and all historical records of the code of these contracts are retrieved as the most recent version. This problem will not exist in erigon3, but until then, a workaround will be used to access code of such contracts through a special structure, `SystemContractCodeLookup`
Fixes https://github.com/ledgerwatch/erigon/issues/5865

Workaround for the code history of BSC system contracts

---

cmd/sentry/main.go
cmd/utils/flags.go
eth/backend.go
p2p/server.go
turbo/cli/default_flags.go

Regarding https://github.com/ledgerwatch/erigon/issues/6260
added flag `--p2p.allowed-ports=<porta>,<portb>` to restrict which ports to use for sentries for different protocol versions.
Default for this flag is `30303, 30304` (first port is inherited from `--port` flag defaults.
If `--port` is changed and it's new value is not presented in allowed port list, provided port will be allowed as well as list provided via `--p2p.allowed-ports` 
Port picking is straightforward, we create sentry gRPC server for protocol over first allowed port that is not already taken.
If there are no allowed ports left, erigon exits with hint.

added --p2p.allowed-port flag

---

cmd/rpcdaemon/commands/eth_txs.go

FIrst of all, thanks in advance for your advice.
I've found that `eth_getTransactionByHash` is having trouble retrieving some Polygon State Sync transactions such as [`0xd5f4f8c3cd85cf65e8df23a2c1ae02aefda1e6293db0c3a9ddcc08cee8ca1131`](https://polygonscan.com/tx/0xd5f4f8c3cd85cf65e8df23a2c1ae02aefda1e6293db0c3a9ddcc08cee8ca1131), while `eth_getBlockByNumber` can retrieve them without problem.
```shell
$ curl -XPOST 'http://localhost:8545' \
-H 'Content-Type: application/json' \
--data '{"method":"eth_getTransactionByHash","params":["0xd5f4f8c3cd85cf65e8df23a2c1ae02aefda1e6293db0c3a9ddcc08cee8ca1131"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":null}
```
This is because RPCDaemon doesn't query for blocks by Bor Hash, even though `api.txnLookup` has failed.

Fix eth_getTransactionByHash for Bor Transactions

---

cmd/rpcdaemon/commands/eth_receipts.go

Same as #6286 and #6288
This patch closes #6276 
```shell
$ curl -XPOST 'http://localhost:8545' \
-H 'Content-Type: application/json' \
--data '{"method":"eth_getTransactionReceipt","params":["0x31ce15ce9a1ff347f4204a1ed3625861165c53ae08743c1f36a32865c62744c6"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"block has less receipts than expected: 0 \u003c= 0, block: 36635776"}}
```
cc. @0xKrishna

Fix eth_getTransactionReceipt for Bor Transactions

---

cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/tracing.go

FIrst of all, thanks in advance for your advice.
I've found that `trace_replayTransaction` is having trouble tracing some Polygon State Sync transactions such as [`0xd5f4f8c3cd85cf65e8df23a2c1ae02aefda1e6293db0c3a9ddcc08cee8ca1131`](https://polygonscan.com/tx/0xd5f4f8c3cd85cf65e8df23a2c1ae02aefda1e6293db0c3a9ddcc08cee8ca1131), just like [the case of the previous PR][p].
[p]: https://github.com/ledgerwatch/erigon/pull/6286
```shell
$ curl -XPOST 'http://localhost:8545' \
-H 'Content-Type: application/json' \
--data '{"method":"trace_replayTransaction","params":["0xd5f4f8c3cd85cf65e8df23a2c1ae02aefda1e6293db0c3a9ddcc08cee8ca1131",["trace","stateDiff"]],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":null}
```
This is because RPCDaemon doesn't query for blocks by Bor Hash, even …

Fix Trace RPCs for Bor Transactions

---

cmd/downloader/main.go
cmd/utils/flags.go
turbo/cli/default_flags.go
turbo/cli/flags.go

This was a great idea #6261 
Added two new flags to turn off downloader ipv6 and/or ipv4 usage

Disable ipv6 flag

---

cmd/erigon-cl/core/transition/beacon_state_utils.go
cmd/erigon-cl/core/transition/beacon_state_utils_test.go

This is described in https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#compute_proposer_index.
I compared with the Prysm tests to confirm the implementation is correct: https://github.com/prysmaticlabs/prysm/blob/2e49fdb3d22952f47fbead93b344839bfe4fe1e8/beacon-chain/core/helpers/validators_test.go#L506-L614

Add ComputeProposerIndex

---

eth/backend.go

Missing break clause leaded to unnecessary incrementing of `pi` when port is already picked.

add missed break clause during protocols port picking

---

cmd/rpcdaemon/commands/otterscan_default_tracer.go
cmd/rpcdaemon/commands/otterscan_trace_contract_creator.go
cmd/rpcdaemon/commands/otterscan_trace_operations.go
cmd/rpcdaemon/commands/otterscan_trace_touch.go
cmd/rpcdaemon/commands/otterscan_trace_transaction.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/state/commands/opcode_tracer.go
cmd/state/exec3/calltracer22.go
core/vm/access_list_tracer.go
core/vm/evm.go
core/vm/logger.go
core/vm/logger_json.go
eth/calltracer/calltracer.go
eth/tracers/logger/access_list_tracer.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
turbo/transactions/tracing.go

Splitting function `CaptureStart` into `CaptureStart` (when depth == 0) and `CaptureEnter` (when depth > 0), while removing argument `depth`. Same with splitting `CaptureEnd` into `CaptureEnd` and `CaptureExit`

Native tracers - step 2

---

cmd/erigon-cl/core/transition/beacon_state_utils.go
cmd/erigon-cl/core/transition/beacon_state_utils_test.go

This is described in https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#get_beacon_proposer_index.
I compared with the Prysm tests to confirm the implementation is correct: https://github.com/prysmaticlabs/prysm/blob/2e49fdb3d22952f47fbead93b344839bfe4fe1e8/beacon-chain/core/helpers/validators_test.go#L151-L204.

Implement GetBeaconProposerIndex

---

cmd/rpcdaemon/commands/otterscan_default_tracer.go
cmd/rpcdaemon/commands/otterscan_trace_contract_creator.go
cmd/rpcdaemon/commands/otterscan_trace_operations.go
cmd/rpcdaemon/commands/otterscan_trace_touch.go
cmd/rpcdaemon/commands/otterscan_trace_transaction.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/state/commands/opcode_tracer.go
cmd/state/exec3/calltracer22.go
core/vm/access_list_tracer.go
core/vm/evm.go
core/vm/interpreter.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
eth/calltracer/calltracer.go
eth/tracers/logger/access_list_tracer.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
turbo/transactions/tracing.go

Remove `env` argument from all Capture functions except for `CaptureStart`

Native tracers step 3

---

cmd/rpcdaemon/commands/otterscan_default_tracer.go
cmd/rpcdaemon/commands/otterscan_trace_contract_creator.go
cmd/rpcdaemon/commands/otterscan_trace_operations.go
cmd/rpcdaemon/commands/otterscan_trace_touch.go
cmd/rpcdaemon/commands/otterscan_trace_transaction.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/state/commands/opcode_tracer.go
cmd/state/exec3/calltracer22.go
core/vm/access_list_tracer.go
core/vm/evm.go
core/vm/interpreter.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
eth/calltracer/calltracer.go
eth/tracers/logger/access_list_tracer.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
turbo/transactions/tracing.go

Remove `callType` argument from `CaptureStart`, and change `callType vm.CallType` to `typ vm.OpCode` in `CaptureEnter` and move to the first position (as it is in geth)

Native tracers - step 4

---

cmd/rpcdaemon/commands/otterscan_trace_transaction.go

This fixes Otterscan tx tracer, which broke on the following refactoring: https://github.com/ledgerwatch/erigon/commit/60cb4e2bbb94d5749c17fad335dced1e14fd8647
It used to receive value == -1 for delegatecall, now it is receiving nil, so we safeguard against it now.

Fix otterscan tx tracing for delegatecall

---

core/vm/instructions.go
core/vm/interpreter.go
core/vm/jump_table.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/24031

core/vm: fill gaps in jump table with opUndefined

---

.gitignore
core/genesis.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/types/block.go
docs/programmers_guide/dupsort.md
eth/protocols/eth/protocol.go
ethdb/privateapi/ethbackend.go
params/config.go
turbo/adapter/ethapi/api.go

Continuation of PR #6009. Storage and retrieval of withdrawals.

Withdrawals part 2

---

cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/tracing.go

In `debug_traceCallMany` and `eth_callMany` the `IntraBlockState` is not being finalized after each replayed transaction and after each call. This can cause several problems:
- False gas consumption calculation. Specifically in `SSTORE` dynamic gas calculation being affected by "warm" and "cold" storage slots, and by "original" value comparison.
- Ability to call contracts that were `SELFDESTRUCT`ed in the replayed transactions or during previous calls, as the self-destruction has not been finalized.
see https://github.com/ledgerwatch/erigon/issues/6373 as an example.
This pull request adds a call to `FinalizeTx` after each `ApplyMessage` and `TraceTx`

Finalize state after each call in callMany

---

core/vm/absint_cfg_proof_check.go
core/vm/absint_cfg_proof_gen.go
core/vm/errors.go
core/vm/instructions.go
core/vm/interpreter.go
core/vm/jump_table.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/23952

core/vm: Simplify error handling in interpreter loop

---

cmd/evm/internal/t8ntool/transition.go
cmd/evm/runner.go
cmd/evm/staterunner.go
cmd/rpcdaemon/commands/gen_traces_test.go
cmd/rpcdaemon/commands/otterscan_api.go
cmd/rpcdaemon/commands/otterscan_default_tracer.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/otterscan_trace_transaction.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/state/commands/opcode_tracer.go
cmd/state/exec3/calltracer22.go
core/blockchain.go
core/vm/access_list_tracer.go
core/vm/evm.go
core/vm/interpreter.go
core/vm/logger.go
core/vm/logger_json.go
eth/calltracer/calltracer.go
eth/stagedsync/stage_execute.go
eth/tracers/logger/access_list_tracer.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
turbo/transactions/tracing.go

Getting closer to Geth's tracer interfaces

Native tracers step 6: Rename Tracer to EVMLogger, reduce args CaptureExit

---

core/types/withdrawal_test.go
tests/state_test.go
turbo/trie/gen_struct_step.go
turbo/trie/hashbuilder.go

Prior to withdrawals, it was extremely unlikely to have short (RLP < 32) top trie nodes outside test scenarios.

HashBuilder: fix top node shorter than 32 bytes

---

core/vm/evm.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/22766.
Do not keep separate flag for "max code size exceeded" case, but instead assign appropriate error for it sooner.

core/vm: clean up contract creation error handling

---

accounts/abi/bind/backends/simulated_test.go
core/vm/opcodes.go
eth/tracers/internal/tracetest/testdata/call_tracer/inner_throw_outer_revert.json
eth/tracers/internal/tracetest/testdata/call_tracer_legacy/inner_throw_outer_revert.json

Cherry-pick https://github.com/ethereum/go-ethereum/pull/24017.
* core/vm: Define 0xfe opcode as INVALID
* core/vm: Remove opInvalid as opUndefined handles it
Co-authored-by: Alex Beregszaszi <alex@rtfs.hu>

core/vm: Make INVALID a defined opcode

---

turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/prefetched_blocks.go

After PR #6515 `(*PrefetchedBlocks) Pop` doesn't remove the block from the LRU cache anymore, so `Get` is a better name.

(*PrefetchedBlocks) Pop -> Get

---

.gitmodules
core/vm/errors.go
core/vm/evm.go
core/vm/gas_table.go
tests/block_test.go
tests/init.go
tests/state_test.go

See https://github.com/ethereum/EIPs/pull/6249 and https://github.com/ethereum/tests/pull/1125

Amend EIP-3860 per EIPs/pull/6249

---

core/types/withdrawal.go
core/types/withdrawal_test.go

This PR adds SSZ hash and encode/decode to Withdrawal object.

added SSZ encodings for withdrawals

---

core/types/block.go
turbo/engineapi/fork_validator.go
turbo/stages/bodydownload/prefetched_blocks.go

Ensure that withdrawals are not lost in `validateAndStorePayload`.

Switch validateAndStorePayload to Body.RawBody()

---

cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/tracing.go

Continuing the work of https://github.com/ledgerwatch/erigon/pull/6381 . We encountered a problem in blocks with type 2 transactions, specifically blocks with two transactions with the same `tx.from`. When the first tx is replayed, a high `gasPrice` is being calculate in `txn.AsMessage` causing the second replayed tx to fail with the following error:
```
insufficient funds for gas * price + value: address ...
```
This happens in both `eth_callMany` and `debug_traceCallMany`.
This pull request follows the `debug_traceTransaction` usage of `tx.AsMessage` in `ComputeTxEnv`

block BaseFee in callMany

---

core/rawdb/rawdbreset/reset_stages.go

err is being ignored, so it silently fails reset when new table is not whitelisted

Fix err being ignored

---

cmd/rpcdaemon/commands/erigon_system.go

erigon_blockNumber  returns "latest executed block number" or any block number requested. 
In this last case the rpcBlockNum variable was not initialized

Fix erigon_blockNumber

---

cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/tracing.go

Some transactions in replayed blocks do not get reverted, although they were originally reverted due to out of gas. This causes false balance calculations for some addresses

prepare state in replay blocks in callMany

---

cmd/rpcdaemon/cli/config.go

Discord user had issue 
`
hey guys, any tips how to enable ws ? (other than --ws)? Ah its running on 8545 by default. I was expecting it on 8546. I would like if this could also be set by a flag same way as a HTTP flag.
`
later conversation
```
Q: yeah, is it not clear that it's enabling websocket for the http handler?
A: Its not super obvious no.
```
Adds a small copy to ws flag to make this more obvious

Make websocket flag more clear

---

cmd/utils/flags.go
core/tx_pool.go
turbo/stages/mock_sentry.go

pass in new values to the txpool on creation to handle shanghai changes.

txpool changes for eip-3860

---

ethdb/privateapi/ethbackend.go

This is a fix for [withdrawal-devnet-3](https://forkmon.withdrawal-devnet-3.ethpandaops.io/). The problem was that CL calls `NewPayloadV2` for pre-Shanghai blocks with `nil` withdrawals, which is OK, but that `nil` was erroneously converted into an empty array, causing block hash mismatch.

Allow NewPayloadV2 for pre-Shanghai blocks

---

eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

This is more reliable criterion because it is harder to spoof continuously by malicious peers

stage_headers: use block time instead of "topSeenHeight" to determine when it is in sync

---

docs/evm_semantics.md
docs/examples/single-process.md
docs/programmers_guide/witness_formal_spec.md

Fix: typos

---

ethdb/privateapi/ethbackend.go

See https://github.com/ethereum/execution-apis/pull/337

fix: payload version error return

---

eth/stagedsync/stage_bodies.go
turbo/stages/bodydownload/body_algos.go

When body gets evicted from the cache, its corresponding entry in `requestMap` is also removed but was never re-instated when re-request happens

Another fix for body download

---

cmd/rpcdaemon/commands/eth_block.go

There are two fixes:
1) the blockNumber in the CreateHistoryStateReader should be blockNumber + 1 as in the eth_call, eth_createAccessList:
- eth_call: already use blockNumber + 1 see CreateStateReaderFromBlockNumber where the blockNumber 
-                passed to the CreateHistoryStateReader is blockNumber + 1
- eth_createAccessList: call CreateHistoryStateReader directly with blockNumber + 1
2) The eth_callBudle allows to execute the original transaction (here the sender nonce is assigned to the tx) on a user defined block; the original transition could be performed in another block . The sender's nonce when the original transaction was performed had a value that may be different to the nonce of the sender when the tx is  "executed" on new block. So during the execution of the …

eth_callBundle fixes

---

cmd/sentry/sentry/sentry_grpc_server.go
cmd/sentry/sentry/sentry_multi_client.go
eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

There are 3 changes:
1. Replace `anchorQueue` with `anchorTree` to be able to always walk the anchors in the order of increasing blockHeights (not possible with the queue) to prioritise making progress on the lowest block heights
2. Not increment `nextRetryTime` if the request was not sent
3. Reduce the strides in skeleton from `8*192` to `192` to reduce reliance of the long series of requests to make progress

Improvements for the BSC stuck header sync

---

ethdb/privateapi/ethbackend.go

See https://github.com/ethereum/execution-apis/pull/338

Replace INVALID_BLOCK_HASH with INVALID

---

cmd/rpcdaemon/commands/engine_api.go
cmd/rpcdaemon/rpcservices/eth_backend.go
ethdb/privateapi/ethbackend.go
turbo/rpchelper/interface.go

Very basic implementation for get payload bodies rpc calls.  Once we have Hive tests for these calls I can pick this back up and work through any issues.
Implementation of https://github.com/ethereum/execution-apis/pull/352.

engine payload bodies rpc endpoints

---

cmd/rpcdaemon/commands/gen_traces_test.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/rpcdaemontest/test_util.go
core/vm/evm.go
eth/tracers/internal/tracetest/prestate_test.go
eth/tracers/internal/tracetest/testdata/prestate_tracer/create_existing_contract.json
eth/tracers/internal/tracetest/testdata/prestate_tracer_with_diff_mode/create.json
eth/tracers/internal/tracetest/testdata/prestate_tracer_with_diff_mode/create_suicide.json

In v2.36.0 we correctly trace this transaction, however due to a code ordering issue in previous releases, there was an 'out of gas' response, because we fell through to the code here where ErrContractAddressCollision will be returned as such. This change isn't the fix, but ensures the actual error is returned.

feat(trace): use specific error string

---

cmd/rpcdaemon/commands/eth_txs.go

At the moment erigon does not try to look for bor transactions inside the pool

Fix retrieving Bor transactions from the pool

---

cmd/rpcdaemon/commands/eth_receipts.go

rpc: move receipts length check after bor logic

---

consensus/aura/aura.go

Example request that crashed the RPC method handler on Gnosis Chain mainnet.
```
{
"id": "1",
"jsonrpc": "2.0",
"method": "debug_traceBlockByNumber",
"params": [
"0x8a1f76",
{
"tracer": "callTracer"
}
]
}
```

Don't panic on some AuRa transactions in the past

---

cmd/hack/hack.go
cmd/integration/commands/stages.go
cmd/sentry/sentry/sentry_api.go
cmd/sentry/sentry/sentry_grpc_server.go
consensus/bor/bor.go
consensus/bor/heimdall/client.go
turbo/stages/headerdownload/header_algos.go

It turns out that "standard" BSC nodes based on Geth, do not propagate new block hashes and blocks, at least towards Erigon nodes. This is a workaround

Workaround for BSC nodes not propagating new block hashes and blocks

---

ethdb/prune/storage_mode.go

From what I understand, this should be sufficient to add `--prune=r` support for Gnosis and Chiado.

feat: add deposit contract blocks for Gnosis

---

cmd/rpcdaemon/commands/debug_api_test.go
cmd/rpcdaemon/commands/erigon_receipts_test.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_block_test.go
cmd/rpcdaemon/rpcdaemontest/test_util.go

So... for blocks that don't exist, the eth_getBlockTransactionCount RPCs should return `null`. Erigon does this correctly right now and this is covered by the unit test in [rpcdaemon/commands/corner_cases_support_test.go](https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/commands/corner_cases_support_test.go).
But, for blocks that don't have any transactions, like [703696](https://etherscan.io/block/703696), the RPC also returns `null`.
I've changed this to correctly return `0` and have added 2 new tests to handle it. (I had to add another block to the test chain in rpcdaemon/rpcdaemontest/test_util.go and had to fix a few other tests that broke as a result.)
Resolves #6775

Fix getBlockTransactionCount returning null

---

eth/tracers/api.go
turbo/transactions/tracing.go

Created to handle #6758.
Just takes the parameters and passes them down the pipe.  A local test against mainnet showed the trace size varied accordingly when passing true/false values for `onlyTopCall`.

pass config to tracer from RPC request

---

core/state/contracts/selfdestruct.sol
tests/contracts/selfDestructor.sol

Solidity 0.8.0 breaks the current use of `payable` in these test contracts, resulting in errors like
```
Error: Type address is not implicitly convertible to expected type address payable.
--> selfDestructor.sol:10:9:
|
10 |         address payable nil = address(0);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Related to #6680

Fix 'make bindings'

---

.goreleaser.yml

if ever planned to release from arm64 this
fix allows to build it as gcc defaults
to host arch
Signed-off-by: Artur Troian <troian.ap@gmail.com>

fix(release): use prefixed compiler for amd64

---

cmd/erigon-cl/main.go

Some network might have different `SLOTS_PER_EPOCH` configs instead of the currently hardcoded `32`.

fix: use variable for slots per epoch in CL

---

cmd/lightclient/main.go

Missed a spot in #6864, my bad.

fix: variable slots per epoch in light client

---

accounts/abi/bind/template.go

fix: replace common package to libcommon package in `abigen`.

fix: replace common package to libcommon package in `abigen`

---

turbo/snapshotsync/snapcfg/util.go

No change to `go.mod` since `erigon-snapshot` has already been updated in `devel`.
I'll keep my Chiado node up to serve the snapshots for a while, until there are more erigon nodes in the network.
Resolves #6307

Chiado snapshots

---

cl/clparams/config.go
cl/clparams/config_test.go

This adds the Gnosis and Chiado configs to the CL. I'm sure there's other things missing too. Any pointers would be appreciated!
Currently stuck on:
```
INFO[02-06|14:00:01.421] [Checkpoint Sync] Requesting beacon state uri=https://checkpoint.gnosis.gateway.fm/eth/v2/debug/beacon/states/finalized
INFO[02-06|14:00:02.846] [Checkpoint Sync] Retrieving lightclient bootstrap from sentinel root=6cd2f0f4018d7ca17c9bfaf69f7eb46706b5a9b3356b9686aa71ae15a11c47e4
```

feat: add Gnosis and Chiado to CL

---

cmd/rpcdaemon/commands/tracing.go
consensus/bor/statefull/processor.go
eth/tracers/api.go
turbo/transactions/tracing.go

State sync transactions can be enabled using `"borTraceEnabled": true` parameter, this is to ensure that the current behaviour is unchanged.

State sync transactions added to debug_traceBlockByNumber call

---

cmd/rpcdaemon/commands/eth_block.go

Makes it consistent with response of bor. Fixes [Issue#735](https://github.com/maticnetwork/bor/issues/735).

Remove miner address from eth_getBlockByNumber for bor RPC calls

---

cl/clparams/config.go
cmd/utils/flags.go

Only Nimbus peers support light clients, and there's not enough Nimbus peers on Gnosis.

Don't use embedded CL by default for Gnosis

---

consensus/aura/aura.go
consensus/aura/config.go
consensus/aura/contracts/embed.go
consensus/aura/contracts/withdrawal.json
consensus/serenity/serenity.go

See https://github.com/gnosischain/specs/blob/master/execution/withdrawals.md

Withdrawals on Gnosis Chain

---

cmd/rpcdaemon/cli/config.go

The CLI logging currently emits the configured address when noting that the HTTP or Engine RPC services are started.  This is _usually_ the same as the listening address, but not always.  In particular, when the bind directive specifies an ambiguous parameter, like port 0 for an ephemeral port, the actually bound address will differ.
This change will help users to operate Erigon while binding to ephemeral ports.  This is especially helpful for developers trying to run multiple instances of Erigon concurrently in tests which may or may not be executing in parallel.

Log bound addresses instead of configured ones

---

cmd/hack/hack.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/commands/tracing.go

Not sure if this is too aggressive or not, but return early once we have a block number if state history has been pruned for that block number.

check prune history on trace calls

---

cmd/sentinel/sentinel/handlers/lightclient.go

Saw this when trying to sync goerli today:
```
INFO[02-23|11:10:20.611] [2/15 Headers] Waiting for Consensus Layer...
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14a58dd]
goroutine 11484998 [running]:
github.com/ledgerwatch/erigon/cl/cltypes.(*LightClientOptimisticUpdate).EncodingSizeSSZ(0x0)
github.com/ledgerwatch/erigon/cl/cltypes/lightclient.go:620 +0x1d
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/communication/ssz_snappy.EncodeAndWrite({0x77f6a74bc058?, 0xc03912b100?}, {0x2c2f628, 0x0}, {0xc022ad9f
5c, 0x1, 0x1})
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/communication/ssz_snappy/encoding.go:34 +0xae
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/handlers.(*ConsensusHandler …
```

handle nil update return values without panic

---

eth/stagedsync/stage_headers.go

This gives Erigon a chance to execute snapshot blocks before CL is ready. Not sure why it was commented out in PR #5684.

Allow snapshot block execution before waiting for CL

---

Dockerfile
Dockerfile.debian
docker-compose.yml
tests/automated-testing/docker-compose.yml

Providing an ENTRYPOINT in Dockerfiles is best practice, so I've added an ENTRYPOINT to Dockerfile and Dockerfile.debian, setting it to erigon, because it's the binary most people want to run. The setting can be overridden in the ` docker run`  command to execute different binaries. Currently everybody has to override it anyway, because there's neither a CMD nor an ENTRYPOINT given.
The Dockerfile.release already contains the ENTRYPOINT erigon.
P.S.: This PR originated in #6862.

add ENTRYPOINT to Dockerfile and Dockerfile.debian

---

eth/stagedsync/sync.go

Fixes https://github.com/ledgerwatch/erigon/issues/6982

Break out of staged sync step when bad block is found

---

cmd/integration/commands/flags.go
cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_domains.go
cmd/state/commands/erigon4.go

added subcommand `state_domains` of `bin/integration` to start processing of existing chaindata with use of state domains and commitment.
It creates two directory in `datadir`: `state` and `statedb` for files and mdbx respectively. 
This version runs blocks one after another and produces merged files. 
Want to add some metrics to export later.

run E4 via integration binary

---

cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_filtering.go

Gateway reported an issue with a trace returning an odd result, similar to the recent problem we'd seen with gnosis.  I found that debug_traceTransaction worked fine so found where the differences were.  trace_transaction wasn't checking for service transactions so the trace failed around fees when it shouldn't.
A number of code paths use callManyTransactions so they should all now check for service messages where needed.

check for free messages when calling trace_transaction

---

docs/programmers_guide/dupsort.md

The doc in [dupsort.md](https://github.com/ledgerwatch/erigon/blob/devel/docs/programmers_guide/dupsort.md#erigon) points to a non-existent `AbstractKV.md`
As best as I can tell, the `AbstractKV.md` was reworked and renamed in commit
0bc61c06edd1d2de3d9376736e0e4f4f4e7b9ed1
then, this was later moved into erigon-lib.  This commit simply repoints the doc at this new location.

Fix broken link in doc

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go
core/types/accounts/account_proof.go
turbo/trie/hashbuilder.go

This PR adds missing tests for eth_getProof and does some mild refactoring with switching from strings to more strict types.  It's likely best/most easily reviewed commit by commit.
Note, the tests include quite a number of helper types and functions for doing the proof validation.  This is largely because unlike Geth, Erigon's approach to trie computations only requires serializing the trie nodes, not deserializing them.  Consequently, it wasn't obvious how to leverage the existing trie code for doing deserialization and proof checks.  I checked on Discord, but, there were no suggestions.  Of course, any feedback is welcome and I'd be happy to remove this code if it can be avoided.
Additionally, I've opted to change the interface type for `GetProof` to use a `common.Hash` for the storage …

Backfill eth getproof tests

---

rpc/handler.go
rpc/handler_test.go

should handle nil having already been written in any rpc call before writing it again causing invalid json to be returned.

check for nil before returning invalid json in rpc streaming calls

---

p2p/server.go

the log line here was the culprit for the race.  made sense to just capture this on localnode creation instead and hold onto it for when the server is started.
ran test with `-race` and `-count=5000` to double check and all looks good

get localnode address up front on creation to save potential data race

---

cmd/release/docker-compose.yml
cmd/release/main.go

Updated initial traefik config so the http -> https redirect on download.erigon.sh will work.

fix(release): download page https redirect

---

debug.Dockerfile

- removes dbtools from debug container
- adds delve to debug container

feat(docker): add debug.Dockerfile with delve

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/mainnet.json

See https://github.com/ethereum/execution-specs/pull/727. Also, `BellatrixForkEpoch` should be 144896, not 144869: refer to [the spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/fork.md).

Schedule mainnet Shapella. Fix BellatrixForkEpoch

---

eth/protocols/eth/protocol.go

This fixes the following issue observed on gnosis_withdrawals_devnet_2:
```
[DBUG] [03-21|09:24:15.060] Handling incoming message                stream=RecvMessage err="newBlock66: too large block TD: bitlen 144"
```

Total difficulty can be huge on Gnosis

---

cmd/txpool/main.go
cmd/utils/flags.go
core/tx_pool.go
turbo/cli/default_flags.go
turbo/cli/flags.go

Adds flag _--txpool.commit_every_ to control how often transactions should be committed to the storage
[Related Issue](https://github.com/ledgerwatch/erigon/issues/7002)

add flag txpool.commit_every

---

cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/corner_cases_support_test.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/debug_api_test.go
cmd/rpcdaemon/commands/erigon_receipts_test.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_api_test.go
cmd/rpcdaemon/commands/eth_block_test.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_callMany_test.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/commands/eth_filters_test.go
cmd/rpcdaemon/commands/eth_mining_test.go
cmd/rpcdaemon/commands/eth_system_test.go
cmd/rpcdaemon/commands/gen_traces_test.go
cmd/rpcdaemon/commands/otterscan_contract_creator_test.go
cmd/rpcdaemon/commands/otterscan_search_backward_test.go
cmd/rpcdaemon/commands/otterscan_transaction_by_sender_and_nonce_test.go
cmd/rpcdaemon/commands/send_transaction_test.go
cmd/rpcdaemon/commands/trace_adhoc_test.go
cmd/rpcdaemon/commands/txpool_api_test.go
eth/stagedsync/stage_interhashes.go
turbo/adapter/ethapi/get_proof.go
turbo/trie/trie_root.go

This PR starts with a few small commits of code cleanup.  Reviewed separately they should hopefully obviously be functionally no-ops.  I'm happy to strip these out and submit them separately if desired.
The final commit is to add support for older blocks as a parameter to eth_getProof.  In order to compute proofs, the function leverages the staged sync unwinding code to bring the hashed state table back to its historic state, as well as to build a list of trie nodes which need to be invalidated/re-computed in the trie computation.  Because these operations could be expensive for very old blocks, it limits the distance proofs are allowed from the head. It also adds some additional checks for correctness, as well as tests which verify the implementation.
This was discussed a bit on Discord …

Add eth_getProof support for historical blocks

---

eth/backend.go

```
==================
Write at 0x00c0005dc570 by goroutine 273633:
github.com/ledgerwatch/erigon/turbo/shards.(*Accumulator).Reset()
github.com/ledgerwatch/erigon/turbo/shards/state_change_accumulator.go:32 +0x5ec
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep()
github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:163 +0x3bd
github.com/ledgerwatch/erigon/turbo/stages.StageLoop()
github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:94 +0x197
github.com/ledgerwatch/erigon/eth.(*Ethereum).Start.func1()
github.com/ledgerwatch/erigon/eth/backend.go:1058 +0x10b
Previous write at 0x00c0005dc570 by goroutine 273468:
github.com/ledgerwatch/erigon/turbo/shards.(*Accumulator).Reset()
github.com/ledgerwatch/erigon/turbo/shards/state_change_accumulator.go:32 +0x2ef …
```

to fix txpool startup race

---

cl/clparams/config.go

I have replaced the `ethdevops.io` endpoints with `ethpandaops.io`. The Sepolia endpoint was failing with `no such host` and the checkpoint sync documentation shows `ethpandaops.io` to be the official source for EF checkpoint sync endpoints.

cl: Update checkpoint sync endpoints

---

cl/utils/crypto.go
cmd/devnet/requests/tx.go
cmd/erigon-cl/core/state/state.go
core/vm/contracts.go
crypto/ecies/ecies_test.go
crypto/ecies/params.go
go.mod
p2p/discover/v5wire/crypto_test.go
p2p/discover/v5wire/encoding.go
p2p/server_test.go
turbo/trie/vtree/verkle_utils_test.go

@shyba hi, seems this lib doesn't work with ghcr.io/goreleaser/goreleaser-cross (which producing release binaries) 
removing it for now, feel free to add it in future - if can make it work with goreleaser-cross
see: https://github.com/ledgerwatch/erigon/issues/7210

remove simd lib, because it doesn't work with ghcr.io/goreleaser/goreleaser-cross (which producing release binaries)

---

cmd/prometheus/dashboards/erigon.json

Fixed the following Grafana panels:
* DB Size
* GC and State
* DB Pages Ops/sec
* Commit Counters
* Getrusage
* Latest Block
Also partially fixes https://github.com/ledgerwatch/erigon/issues/7226

chore: update outdated grafana panels

---

accounts/abi/bind/backends/simulated.go
cmd/integration/commands/state_domains.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/state/commands/erigon4.go
cmd/state/commands/history22.go
cmd/state/commands/opcode_tracer.go
core/blockchain.go
core/chain_makers.go
core/state_processor.go
core/types/block.go
eth/stagedsync/stage_mining_exec.go

Tiny addition to ApplyTransaction. Now it expects excessDataGas param so the BlockContext can be created with it

eip-4844: ApplyTransaction now expects excessDataGas

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go
turbo/trie/gen_struct_step.go
turbo/trie/hashbuilder.go
turbo/trie/retain_list.go
turbo/trie/retain_list_test.go
turbo/trie/trie_root.go

This PR completes the implementation of `eth_getProof` by adding support for storage proofs.
Because storage proofs are potentially overlapping, the existing strategy of simply aggregating all proofs together into a single result was challenging.  Instead, this commit rewires things to introduce a ProofRetainer, which aggregates proofs and their corresponding nibble encoded paths in the trie.  Once all of the proofs have been aggregated, the caller requests the proof result, which then iterates over the aggregated proofs, placing each into the relevant proof array into the result.
Although there are tests for `eth_getProof` as an RPC and for the new `ProofRetainer` code, the code coverage for the proof generation over complex tries is lacking.  But, since this is not a new problem I'll …

Add storage proof support to eth_getProof

---

params/version.go

Current release is v2.42 ... it gets confusing if make shows v2.41

Update version.go to be higher than current release

---

cmd/txpool/main.go
cmd/txpool/readme.md

it would appear that an extra `e` was added somewhere along the way to the cli flags for txpool. If this was intentional I was curious as to why, otherwise it seems like fixing the flag would remedy some confusion. Thank you
Upon further investigation it would appear https://github.com/ledgerwatch/erigon/blob/devel/cmd/utils/flags.go#L173 shows corrected spelling.

txpool: update cli flags

---

Makefile

**Reproducer:**
```sh
$ git clone --depth 1 https://github.com/ledgerwatch/erigon
$ cd erigon
$ make db-tools
...
CC+LD mdbx_load
CC+LD mdbx_chk
CC+LD mdbx_drop
make[2]: Leaving directory '/home/user/devel/er/erigon/vendor/github.com/torquem-ch/mdbx-go/mdbxdist'
make[1]: Leaving directory '/home/user/devel/er/erigon/vendor/github.com/torquem-ch/mdbx-go'
cd vendor/github.com/torquem-ch/mdbx-go/mdbxdist && cp mdbx_chk /home/user/devel/er/erigon/build/bin && cp mdbx_copy /home/user/devel/er/erigon/build/bin && cp mdbx_dump /home/user/devel/er/erigon/build/bin && cp mdbx_drop /home/user/devel/er/erigon/build/bin && cp mdbx_load /home/user/devel/er/erigon/build/bin && cp mdbx_stat /home/user/devel/er/erigon/build/bin
cp: cannot create regular file '/home/user/devel/er/erigon/build/bin': No …
```

make: fix db-tools target error when it's first command after cloning

---

turbo/adapter/ethapi/api.go

Pre-Shanghai blocks should have `nil` withdrawals, while post-Shanghai blocks should have non-nil withdrawals (empty or non-empty slice, but not `nil`). Judging from Issue #6976, that's not always a case. PR #7279 attempted to fix the issue, but unfortunately it only masks the root cause.
This reverts commit c60a6a2962c95e4bafd5e295bf1b3332baf2bfd9.

Revert "return [] instead of null for withdrawals (#7279)"

---

accounts/abi/bind/backends/simulated.go
cmd/integration/commands/state_domains.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/otterscan_search_trace.go
cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/tracing.go
cmd/state/commands/erigon4.go
cmd/state/commands/history22.go
cmd/state/commands/opcode_tracer.go
core/blockchain.go
core/chain_makers.go
core/evm.go
eth/stagedsync/stage_mining_exec.go
go.mod
go.sum
turbo/transactions/call.go

`excessDataGas` has been partially made eip-4844 ready, so instead of passing nils to functions, now it actually assigned to some value (it is expected to be nil until cancun update).

eip-4844: assigned value to excessDataGas, unused packages removed

---

accounts/abi/bind/backends/simulated.go
consensus/clique/clique.go
consensus/clique/verifier.go
consensus/ethash/consensus.go
consensus/serenity/serenity.go
core/blockchain.go
core/chain_makers.go
core/genesis_write.go
eth/stagedsync/stage_mining_exec.go
turbo/transactions/tracing.go

In this PR Header's ExcessDataGas is set to the actual value, but it's still unused. It will be used to compute data fee for eip-4844 data blobs, logic of which will be added in later PRs. Also eip-4844 header verification logic added.

eip-4844: setting header's excess_data_gas, verifiying eip-4844 headers

---

cmd/rpcdaemon/commands/eth_call_test.go
turbo/trie/retain_list.go
turbo/trie/retain_list_test.go

According to EIP-1186 the `proof` parts of the response to eth_getProof should be returned "starting with the stateRoot-Node, following the path of the SHA3 (address) as key."  Currently, the proof is returned in traversal order, rather than from the root.
Although all of the proof elements are there and correct, this is contrary to the EIP and will cause problems for some clients.  The existing rpc test uses a map to lookup proof elements by hash, rather than by index, so this bug was not initially caught.
This commit fixes the behavior, updates the existing test, and adds additional checks to the rpc test.

Fix eth_getProof element order

---

accounts/abi/bind/backends/simulated.go
core/state_transition.go
core/types/transaction.go
interfaces.go

Small additions that will be used to compute data blob fees and to verify transactions for "willingness" to pay for these fees.

eip-4844: extensions to compute fees for data blobs

---

cmd/rpcdaemon/commands/engine_api.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/rpcservices/eth_backend.go
consensus/misc/eip4844.go
core/blockchain.go
core/state_transition.go
core/types/blob_tx_wrapper.go
core/types/transaction.go
ethdb/privateapi/ethbackend.go
tests/state_test_util.go
turbo/adapter/ethapi/api.go
turbo/rpchelper/interface.go

types.NewMessage now expects maxFeePerDataGas param, which will be used in transaction verification (preCheck). GetPayloadV3 method added to EngineAPI. Some cosmetic changes applied.

eip-4844: NewMessage now expectes maxFeePerDataGas & GetPayloadV3 impl

---

cmd/rpcdaemon/commands/eth_call_test.go
turbo/trie/proof.go
turbo/trie/retain_list_test.go
turbo/trie/trie.go
turbo/trie/trie_root_test.go

This PR extends the function merged in #7337 to cover the proof generation paths as well.
The first commit simply migrates the internal proof checking code from the rpc `eth_getProof` test to be available externally exported under `turbo/trie`.  In the process, it translates the in place testing assertions to return more normally as errors and adapts to use the pre-existing trie node types which are defined slightly differently (although this code is still intended only for testing purposes).
The second commit refactors the existing trie fuzzing tests from the previous PR and adds new fuzzing tests for the proof generation.  In order to validate the proofs, these fuzzing tests fundamentally do two things.  Firstly, after bootstrapping the test (by seeding, and modifying the db), for each …

Add additional trie proof testing

---

wmake.ps1

https://github.com/golang/go/issues/57757
i think we added netgo tag for the internalcl, since there was an issue with resolution there on linux at some point, but i guess in windows, netgo localhost resolution is broken.  
i just tested on my windows machine and removing netgo seems to work with both --internalcl=true  and false

"fix" windows localhost resolution

---

cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go
turbo/trie/gen_struct_step.go
turbo/trie/hashbuilder.go
turbo/trie/proof.go
turbo/trie/retain_list.go
turbo/trie/retain_list_test.go
turbo/trie/trie_root_test.go

This addresses the last known deficiency of the eth_getProof implementation.  The previous code would return an error in the event that the element was not found in the trie.  EIP-1186 allows for 'negative' proofs where a proof demonstrates that an element cannot be in the trie, so this commit updates the logic to support that case.

Enable negative Merkle proofs for eth_getProof

---

cmd/rpcdaemon/commands/erigon_receipts.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/graphql_api.go
cmd/rpcdaemon/commands/otterscan_api.go
cmd/rpcdaemon/commands/otterscan_search_trace.go
core/state_processor.go

Small additions to block receipts. Now it includes `dataGasPrice` and `dataGasUsed`. `dataGas` is a new type of a gas and blobs are priced in it.

eip-4844: receipts to include dataGasPrice and dataGasUsed

---

cmd/rpcdaemon/commands/engine_api.go
core/types/access_list_tx.go
core/types/block.go
core/types/dynamic_fee_tx.go
core/types/legacy_tx.go
core/types/receipt.go
core/types/transaction.go

Transaction extension to support BlobTxWrapper (or network representation of BlobTx). BlobTxWrapper wraps BlobTx with additional data: blobs, commitments and proofs. Unwrap() returns unwrapped tx if its network tx, otherwise returns itself.

eip-4844: Unwrap() additional tx method

---

README.md
cmd/utils/flags/flags.go
diagnostics/CHANGELOG.md
diagnostics/flags.go
diagnostics/version.go
turbo/debug/flags.go

To expose context flags through diagnostic endpoint `/debug/metrics/flags`. 
The current `/debug/metrics/cmdline` only provides the command run by user. In the case when user runs Erigon using config file, `cmdline`’s info does not truly reflect the ‘launch setting' and flags set that Erigon is running on.
```
erigon --datadir /tmp/data --config test.yaml
```
```
datadir : '/tmp/data'
chain : "sepolia"
http : true
metrics: true
private.api.addr : "localhost:9090"
http.api : ["eth","debug","net"]
```
```
SUCCESS
chain=sepolia
config=test.yaml
datadir=/tmp/data
http=true
http.api=eth,debug,net
metrics=true
private.api.addr=localhost:9090
```

Add diagnostics endpoint for flags

---

cmd/rpcdaemon/rpcservices/eth_backend.go

fixes a logging statement was logging the outer rpc proto instead of the inner rlp of the block as intended

fix block rlp logging bug

---

cmd/rpcdaemon/commands/daemon.go
consensus/chain_reader.go
consensus/clique/api.go
consensus/clique/clique.go
consensus/clique/verifier.go
eth/stagedsync/stage_mining_finish.go

* Enable the `clique` option in the `--http.api` flag.
* List of Clique commands:
`clique_getSnapshot(block number)`
`clique_getSnapshotAtHash(block hash)`
`clique_getSnapshotAtHash(block hash)`
`clique_getSigners(block number)`
`clique_getSignersAtHash(block hash)`
`clique_proposals()`
`clique_propose(signer address, bool)`
`clique_discard(signer address)`
`clique_status()`
Example:
`curl --data '{"method":"clique_getSigners","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545`
* Please be careful while using the Clique API. Do not make the HTTP API public on the Clique's signer node, as anyone can directly call a Clique command. Instead, it should only be allowed in the localhost by using the flag `--http.addr "127.0.0.1"`.

Add clique API, support "clique" option in --http.api flag

---

cmd/rpcdaemon/commands/erigon_receipts.go

When calling erigon_getLatestLogs, I was getting a crash in [erigon_receipts.go](https://github.com/ledgerwatch/erigon/blob/beb97784d43ece5acde365a74efe8763692ebdba/cmd/rpcdaemon/commands/erigon_receipts.go#L254). I think it is a simple indexing bug
```
[service.go:217 panic.go:884 panic.go:113 erigon_receipts.go:254 value.go:586 value.go:370 service.go:222 
handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
[WARN] [05-05|21:13:59.749] Served                                   
conn=100.70.204.111:50141 method=erigon_getLatestLogs reqid=1 t=621.5936ms err="method handler crashed"
```

fix: erigon_getLatestLogs

---

consensus/clique/clique.go
consensus/clique/verifier.go
consensus/ethash/consensus.go

therefore it doesn't make sense to check for it in pre-Merge engines

Cancun cannot happen before Merge

---

p2p/server.go

The peer ID in sentry.proto is a H512 / 64 bytes value, and MarshalPubkey creates it from a public key.
There's no need to cut the first byte, because MarshalPubkey already does it.
Doing so results in a 63 bytes value that is incompatible with silkworm sentry.

p2p: fix peer ID serialization

---

params/bootnodes.go

New sepolia bootnodes managed by EF devops. Cherry pick https://github.com/ethereum/go-ethereum/pull/27099

params: new sepolia bootnodes

---

eth/backend.go

Currently, the p2p ports require an explicit enumeration of ports to pick.  Sometimes, for instance when writing integration tests utilizing an Erigon binary the particular p2p port does not matter and trying to pick non-allocated port ranges is fragile.
This small PR simply checks to see if the enumerated port is '0', in which case it disables the probing check which would otherwise cause Erigon not to try binding to an ephemeral port.

Allow ephemeral ports for p2p

---

turbo/app/support_cmd.go

Minor fix in args usage message of support flag. The current message says that the flag should be 'metrics.url' but it reality it should be 'metrics.urls'

Args usage msg bug fix

---

consensus/aura/aura.go
consensus/bor/bor.go
consensus/clique/verifier.go
consensus/ethash/consensus.go
consensus/merge/merge.go
consensus/misc/eip1559.go
consensus/misc/eip1559_test.go

Dirty hack to fix Chiado until #7151 is properly implemented. Should fix the following error:
```
[WARN] [05-23|17:07:39.303] Verification failed for header           hash=0x4eee718e5958a862746ea9a9531a16e6a404698d3a0e8120e8aff743b9f1e0a2 height=1 err="invalid gas limit: have 12500000, want 10000000 +-= 9764"
```

Skip gas limit checks for chains with gas limit contract

---

consensus/bor/bor.go
consensus/bor/heimdall/span/spanner.go
consensus/bor/span.go
consensus/bor/span_mock.go

Fixes issues with consensus validation. Compare against current producer set instead of whole validator set.

consensus/bor: use current producers for extra data validation

---

cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/commands/erigon_receipts.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/eth_system.go
cmd/rpcdaemon/commands/eth_txs.go
cmd/rpcdaemon/commands/eth_uncles.go
cmd/rpcdaemon/commands/otterscan_api.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/tracing.go
core/rawdb/accessors_chain.go
core/types/receipt.go
eth/gasprice/feehistory.go
eth/gasprice/gasprice.go
eth/gasprice/gasprice_test.go
eth/protocols/eth/handler_test.go
eth/protocols/eth/handlers.go
eth/stagedsync/stage_senders_test.go

preparation for adding BlockID

receipts: less allocs in DeriveFields, use blockReader, remove ReadReceiptsByHash, gasPriceOracle don't read block twice and use blockLru

---

accounts/abi/bind/template.go

feature: support generate parse transaction input bytes codes in `abigen`.  
It's easy to use abigen to generate code that help you parse the event log and call the payable method with the transactor.
But parsing the transaction call data is missing. You can only send a transaction with a transactor. This PR aims to generate codes that help developer parse transaction calldata.
abigen can generate code to parse the transaction call data.    
With this PR, transaction parse codes are generated like this:   
```go
// CollectParams is an auto generated read-only Go binding of transcaction calldata params
type CollectParams struct {
Param_params INonfungiblePositionManagerCollectParams
}
// Parse Collect method from calldata of a transaction
//
// Solidity: function …
```

feature: support generate parse transaction input bytes codes in `abigen`

---

cmd/evm/staterunner.go

This implements batched state-test exectution, similar to https://github.com/ethereum/go-ethereum/pull/27318 . 
Some speedtests, executing a state-test twice on current master takes ~4-5 seconds, and scales linerarly.
```
Doing 2 execs old style
real    0m8.185s
user    0m8.081s
sys     0m0.110s
```
Doing `100` executions on this PR -- a few seconds of ramp-up time, but very quick execution after that : 
```
Doing 100 execs v2
real    0m5.009s
user    0m4.560s
sys     0m0.508s
```
I also tested a version where I moved the db instantiation into the top callsite, with the `MustOpen` and `.Close` only performed once, instead of `100` times -- however, I noticed no additional speed gains from doing so (my branch `batched_evm_v2`). 
Therefore, I suspect that the slowdowns comes not from the …

cmd/evm: support batched statetest-mode

---

cmd/erigon-el/stages/stages.go
cmd/hack/tool/fromdb/tool.go
cmd/integration/commands/stages.go
cmd/state/commands/check_change_sets.go
core/rawdb/accessors_chain.go
core/rawdb/blockio/block_writer.go
eth/stagedsync/default_stages.go
eth/stagedsync/stage_headers.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stage_senders_test.go
eth/stagedsync/stage_snapshots.go
eth/stagedsync/stage_txlookup.go
metrics/exp/exp.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/block_reader.go
turbo/snapshotsync/block_snapshots.go
turbo/stages/mock_sentry.go
turbo/stages/stageloop.go

- stage_senders: don't re-calc existing senders
- stage_tx_lookup: prune less blocks per iteration - because random-deletes are expensive. pruning must not slow-down sync. 
- prune data even if --snap.stop is set
- "prune as-much-as-possible at startup" is not very good idea: at initialCycle machine can be cold and prune will cause big downtime, no reason to produce much freelist in 1 tx. People may also restart erigon - because of some bug - and it will cause unexpected downtime (usually Erigon startup very fast). So, I just remove all `initialSync`-related logic in pruning.   
- fix lost metrics about disk write byte/sec

prune speedup. stage_senders: don't re-calc existing senders

---

cmd/state/commands/check_change_sets.go
cmd/state/commands/opcode_tracer.go
cmd/state/commands/state_root.go
consensus/bor/bor.go
consensus/bor/snapshot.go
consensus/bor/snapshot_test.go
consensus/bor/valset/validator_set.go
core/chain_makers.go
core/systemcontracts/upgrade.go
eth/stagedsync/stage_mining_exec.go

I've added a non root logger to bor.ValidatorSet validator set. This creates a signature change on a number of calling functions to propagate the logger. This is mostly constrained to the bor package but impacts a number of tests and utilities which call the validators set.

Added non root logger to bor.ValidatorSet

---

consensus/bor/bor.go
consensus/bor/snapshot.go

I realised that the term `checkpoint` is used in 2 different meanings in the code, which are distinct. Renaming one of the to persistentSnapshots to reduce confusion

[bor] Desambiguate the term checkpoint

---

cmd/rpcdaemon/cli/config.go
rpc/client.go
rpc/handler.go
rpc/server.go
rpc/service.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/stageloop.go

This is another update to logging to replace the root logger with a contextual logger

rpc service and stageloop logger updates

---

core/state/history_test.go
core/state/historyv2read/history.go
core/state/plain_readonly.go

- do it only once in HistoryStateReader

e2: avoid do RestoreCodeHash twice

---

cmd/rpcdaemon/commands/send_transaction.go

When testing with `Bor` consensus turned on I discovered that `SendRawTransaction` returns a 0x000... hash when transactions are submitted during block transitions.  This turns out to be spurious in the sense that the transaction insertion is successful.  
The cause is that `ReadCurrentBlockNumber` returns a nil block number.
This in turn is caused by the following: In `accessors_chain.go` there are two methods: `WriteHeader`  and `WriteHeadHeaderHash` when the first is called the block number is written for the header.  The second writes the header has, but there is no guarantee when it does that the head header will have been written yet.  In fact it seems to happen sometime later.
The problem for `SendRawTransation` is that it begins a transaction after inserting into the txpool.  And …

eth_sendRawTransaction: remove logging, because we have `--txpool.trace.senders` which enabling more verbose logging for given senders list

---

cmd/evm/internal/t8ntool/transition.go
core/types/block_test.go
core/types/dynamic_fee_tx.go
core/types/legacy_tx.go
core/types/transaction_marshalling.go
core/types/transaction_signing.go
core/types/transaction_test.go
eth/stagedsync/stage_bodies_test.go
migrations/txs_begin_end_test.go
migrations/txs_v3_test.go
turbo/stages/blockchain_test.go

For legacy transactions ChainID is optional (missing in pre-[EIP155](https://eips.ethereum.org/EIPS/eip-155) transactions) and is derived from `V` anyway.
Also, cherry pick https://github.com/ethereum/go-ethereum/pull/27452.

Move ChainID from CommonTx to DynamicFeeTransaction

---

turbo/cli/default_flags.go

enable -rpc.txfeecap flag on the RPC daemon in the default sets of CLI flags

enable cli RPCGlobalTxFeeCapFlag

---

cmd/utils/flags.go

reasons:
- mainnet: even nodes with small FreeList - still have millions of pages there `GC: 46446830 5.8%`. Probability of getting into state where space re-use will be slower than free-list grow is > 0% (we now using db version which limiting  freelist-overhead, but increasing such probability)
- polygon: size is > 8Tb
- hardware slowly moving towards bigger pageSizes (because for OS/Hardware) maintenance of pages metadata is also not free (metadata, lists, LRU, etc...). Macbook's default pagesize now is 16Kb. Network disks in cloud are also likely working with 16Kb pages. 
pros:
- less db fragmentation (better FS-level compression)
- less overflow pages in DB (which also reducing free-list overhead)
- smaller free-list 
- bigger key-size-limit 
- no 8Tb db size limit
- can setup FS - …

change --db.pagesize default to 8KB

---

cmd/integration/commands/root.go

Fixes https://github.com/ledgerwatch/erigon/issues/7814, it can be really confusing when `erigon` and `integration` process `~` in path in different ways.
I can't fix it for `integration` the same way it is done for `erigon`,  because in main app it is done with `urfave/cli` package that is not used in `integration`,  so I've used other simplest way to do it.

Expand home dir from tilda for integration tool settings

---

core/vm/jump_table.go
core/vm/opcodes.go

See https://github.com/ethereum/EIPs/pull/7074. Also enable [EIP-1153](https://eips.ethereum.org/EIPS/eip-1153) in [Cancun](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/cancun.md).

core/vm: move TSTORE,TLOAD to correct opcode nums

---

eth/stagedsync/stage_finish.go

This fixes an indexing panic when bor sync event logs are returned via a subscription.
It applies the same tx computation that is used by the getlogs rpc call

Added ComputeBorTxHash to subscription reader

---

cmd/integration/Readme.md
cmd/integration/commands/reset_state.go

Adds `clear_bad_blocks` command to integration tool. This command allows to re-process blocks that were erroneously marked as bad. 
Command just clears `BadHeaderNumber` table. It can be safer in some cases than
```
./integration state_stages —unwind=<some_number>
./integration stage_headers —unwind=<some_number>
```
and can be used in the cases like this one https://github.com/ledgerwatch/erigon/issues/7892%20 
Command syntax:
```
./integration clear_bad_blocks --datadir=<datadir>
```

Adds clear_bad_blocks command

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/cli/httpcfg/http_cfg.go
cmd/utils/flags.go
turbo/cli/default_flags.go
turbo/cli/flags.go
turbo/jsonrpc/daemon.go
turbo/jsonrpc/otterscan_api.go
turbo/jsonrpc/otterscan_contract_creator_test.go
turbo/jsonrpc/otterscan_search_backward_test.go
turbo/jsonrpc/otterscan_transaction_by_sender_and_nonce_test.go

Otterscan API search methods allow the user to inform the page size.
This PR adds an internal max (default == 25 results) to cap the page size, regardless of what the user asks.
It also adds a `--ots.search.max.pagesize` CLI args to override this max (either in erigon and rpcdaemon binaries).

Max cap search results for ots API by default + cli flag to override it

---

eth/tracers/native/call.go

Previously the call tracer failed on this Ethereum transaction [0xecfc724f75e39fa9e882ec44a4d0985e099b7a3ac9415466196128770def5bc2](https://etherscan.io/tx/0xecfc724f75e39fa9e882ec44a4d0985e099b7a3ac9415466196128770def5bc2)
Querying with this request
```shell
curl  http://localhost:8545  -X POST  -H "Content-Type: application/json"  --data '{"method":"debug_traceTransaction","params":["0xecfc724f75e39fa9e882ec44a4d0985e099b7a3ac9415466196128770def5bc2", {"tracer": "callTracer",  "tracerConfig": {"withLog": true}}],"id":1,"jsonrpc":"2.0"}
```
Resulted in this response
```json
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32000,"message":"method handler crashed"}}
```
With this error message in the console:
`RPC method debug_traceTransaction crashed: runtime error: index out of …

fix: prevent index out of range during call trace

---

cl/fork/fork_test.go

I'm not sure what caused this failure (for instance, CI for PR #7888 was green), but currently we have the following test failure in `devel`:
```
--- FAIL: TestGnosisForkDigest (0.00s)
fork_test.go:79: 
Error Trace:    github.com/ledgerwatch/erigon/cl/fork/fork_test.go:79
Error:          Not equal: 
expected: [4]uint8{0x82, 0x4b, 0xe4, 0x31}
actual  : [4]uint8{0x21, 0xa6, 0xf8, 0x36} 
```

Remove failing TestGnosisForkDigest

---

turbo/jsonrpc/trace_adhoc.go

this fixes vmtrace after shanghai
before:
```python
VMOperation(pc=24, cost=2, ex=VMExecutedOperation(used=1942085, push=[], mem=None, store=None), sub=None, op='PUSH0', idx='14-644-13')
```
after:
```python
VMOperation(pc=24, cost=2, ex=VMExecutedOperation(used=1942085, push=[HexBytes('0x00')], mem=None, store=None), sub=None, op='PUSH0', idx='14-644-13')
```

fix: show stack for push0

---

core/state/intra_block_state.go
core/state/state_object.go
core/vm/eips.go
core/vm/evmtypes/evmtypes.go
core/vm/instructions.go
core/vm/jump_table.go

Cherry pick https://github.com/ethereum/go-ethereum/pull/27189

Implement EIP-6780: SELFDESTRUCT only in same transaction

---

tests/block_test.go

as it doesn't work with e3 for some reason. Follow up to RP #7981

Disable TestBlockchainEIP with e3

---

eth/backend.go

Fix checks  `chainConfig.TerminalTotalDifficulty` for nil in  `isChainPoS`.  Not doing so causes the Bor startup flow to panic.

check difficulty for nil

---

cmd/state/exec3/state.go
cmd/state/exec3/state_recon.go
consensus/aura/aura.go
consensus/aura/aura_test.go
consensus/bor/bor.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/merge/merge.go
core/blockchain.go
eth/stagedsync/stage_mining_exec.go
turbo/jsonrpc/trace_filtering.go
turbo/transactions/tracing.go

This fixes the trie state root issue that was occurring in the Hive tests for Cancun.

Call InitializeBlockExecution in SpawnMiningExecStage (EIP-4788)

---

core/state/db_state_writer.go

Here is my case:
writeIndex function takes about 39% in pprof flame graph.  I dive into it and find out that we use POA consensus, therefore mining addresses have a big bitmap.  
```
func writeIndex(blocknum uint64, changes *historyv2.ChangeSet, bucket string, changeDb kv.RwTx) error {
buf := bytes.NewBuffer(nil)
for _, change := range changes.Changes {
k := dbutils.CompositeKeyWithoutIncarnation(change.Key)
index, err := bitmapdb.Get64(changeDb, bucket, k, math.MaxUint32, math.MaxUint32)
if err != nil {
return fmt.Errorf("find chunk failed: %w", err)
}
index.Add(blocknum)
if err = bitmapdb.WalkChunkWithKeys64(k, index, bitmapdb.ChunkLimit, func(chunkKey []byte, chunk *roaring64.Bitmap) error {
buf.Reset()
if _, err = chunk.WriteTo(buf); err != nil {
return err
}
return …
```

fixed bitmap performance when write index

---

turbo/engineapi/engine_types/jsonrpc.go

According to the [spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md#blobsbundlev1), commitments/proofs/blobs in `BlobsBundleV1` should have the [DATA](https://github.com/ethereum/execution-apis/blob/main/src/engine/common.md#encoding) encoding.

Fix JSON marshalling of BlobsBundleV1 (EIP-4844)

---

cmd/sentry/sentry/sentry_grpc_server.go
cmd/sentry/sentry/sentry_grpc_server_test.go

problem: it was possible to call startSync
and start sending messages before our Status is sent
solution: wait for the sender goroutine to finish
before calling startSync
refactor handShake parameters to not require peerID and a startSync callback

sentry: fix eth handshake sequence

---

cmd/sentry/sentry/sentry_multi_client.go

if dropUselessPeers = false,
skip processing empty responses same as if it was true

sentry: do not process empty responses

---

eth/backend.go
params/config.go

because bor doesn't have headers,
ReadCurrentHeader returns nil as expected
refactor isChainPoS to only call ReadCurrentHeader/ReadTd if needed and use chain config IDs

bor: fix panic reading total difficulty for isChainPoS

---

cmd/integration/commands/stages.go
cmd/sentry/sentry/broadcast.go
cmd/sentry/sentry/sentry_grpc_server.go
cmd/sentry/sentry/sentry_multi_client.go
consensus/bor/bor.go
consensus/bor/bor_test.go
eth/backend.go
turbo/stages/mock/mock_sentry.go

Currently PropagateNewBlockHashes and BroadcastNewBlock
selects a subset of all sentries by taking a `Sqrt(len(sentries))`,
and then for each sentry SendMessageToRandomPeers
selects a subset of its peers by taking `Sqrt(len(peerInfos))`.
This behaviour limits the broadcast scope with a lot of peers, e.g. 100 becomes 10,
but is not great with very few peers, or if the message is very important
to broadcast to everyone, which is the case of bor validator/proposer nodes.

bor: BroadcastNewBlock to all peers from validator nodes

---

cmd/observer/observer/handshake.go
p2p/peer.go
p2p/transport.go
p2p/transport_test.go

The disconnect message could either be a plain integer, or a list with one integer element. We were encoding it as a plain integer, but decoding as a list. Change this to be able to decode any format.

p2p: fix RLPx disconnect message decoding

---

cmd/integration/commands/stages.go
cmd/sentry/sentry/sentry_multi_client.go
cmd/utils/flags.go
eth/backend.go
eth/ethconfig/config.go
turbo/cli/default_flags.go
turbo/stages/mock/mock_sentry.go

The current logic is flawed, because it drops all peers that are less synced.
It is valid to return empty responses by the eth spec.
A proper logic should penalize from the context of the sync process,
where enough "reputation" data is collected about a peer.
In order to be able to connect to erigon 2.48 peers that have --sentry.drop-useless-peers enabled,
this adds a check to not reply with an empty headers list.
If we reply with an empty list, we're going to be considered useless and kicked.
Once enough of erigon nodes are updated in the network past this commit, this check should be removed,
because it is totally acceptable to return an empty list by the eth spec.

sync: revert flawed dropUselessPeers logic and alleviate its issues

---

eth/ethconfig/config.go
params/chainspecs/holesky.json
params/config.go

Small fixes to PR #8064:
- Don't set cancunTime for Holesky – otherwise we'll have to overwrite it later using the `--override.cancun` flag
- We don't have block snapshots for Holesky yet
- Add Holesky to `isChainIDPoS`
See https://github.com/eth-clients/holesky/pull/68

Small fixes to Holesky config

---

eth/tracers/native/prestate.go

fix: Prevent nonce overflow in debug_traceTransaction
fix #8099

fix debug_traceTransaction get noce overflow
