erigontech/erigon

erigon-lib/chain/chain_config.go, eth/ethconsensusconfig/config.go, eth/stagedsync/stagedsynctest/harness.go, polygon/bor/borcfg/bor_config.go, polygon/bor/state_receiver.go, polygon/bridge/bridge.go, polygon/bridge/reader.go, polygon/tracer/trace_bor_state_sync_txn.go
All usages so far were converting the string to an address. The string is still directly accessible via the variable.
=> borcfg: GetStateReceiverContract returns common.Address

turbo/jsonrpc/otterscan_transaction_by_sender_and_nonce.go
Fixes the following test cases from rpc-tests:
```
0586. ots_getTransactionBySenderAndNonce/test_05.json              Failed
0592. ots_getTransactionBySenderAndNonce/test_11.json              Failed
```
- don't return error in case the address doesn't exist/doesn't have state, hence the result must be null
=> Fixes for ots_getTransactionBySenderAndNonce

eth/tracers/logger/json_stream.go
=> Make structlog's error field a string instead of an object

turbo/jsonrpc/eth_callMany.go
if revert happend in eth_callMany, the error will be included in the normal result rather than error result, and the revert info will be ignored when response marshaling.
current response: 
`{
......
"error": {}
......
}`
expected response:
`{
......
"error": {
"message": "execution reverted: ......",
"data": "0x......"
}
......
}`
=> fix: err msg for eth_callMany

.github/workflows/qa-constrained-tip-tracking.yml
Performing this test every day is too expensive, other more important tests are blocked, it is rescheduled so that it is performed only on Sunday.
=> qa-tests: reschedule constrained-tip-tracking

.github/workflows/release.yml, Dockerfile.release
Main changes:
- get rid of goreleaser
- use latest debian base image
- build and deliver silkworm library and support for AMD64 and AMD64v2
- use golang debian bookworm 1.22 docker image to build artifacts
- use github workflow cache with a week number in the name (to avoid use of expired content)
=> Rework release workflow for release/2.60 branch

.github/workflows/qa-rpc-integration-tests.yml
The PR https://github.com/erigontech/erigon/pull/12322 fixed the behavior of erigon relative to these tests so we re-enable them
=> qa-tests: enable ots_getTransactionBySenderAndNonce tests

.github/workflows/qa-rpc-integration-tests.yml
Update the rpc test suite to a new version that better supports Erigon v3
=> qa-tests: bump rpc-tests version

polygon/bridge/db.go
```
EROR[10-16|01:26:00.055] Staged Sync                              err="runtime error: index out of range [7] with length 3, trace: [stageloop.go:202 panic.go:770 panic.go:114 binary.go:183 db.go:548 db.go:474 stage_polygon_sync.go:1306 stage_polygon_sync.go:1816 stage_polygon_sync.go:578 stage_polygon_sync.g
o:196 default_stages.go:479 sync.go:531 sync.go:410 stageloop.go:249 stageloop.go:101 asm_arm64.s:1222]"
```
Fixes an index out of range found while running Astrid stage integration. The problem was due to encoding mismatch in the BorTxLookup table. The current code uses big.Int byte encoding for storing the block number, while the Astrid Bridge assumed binary.BigEndian.Uint64 encoding.
This PR fixes the runtime error and brings the 2 implementations in sync by keeping the new one …
=> polygon/bridge: fix BorTxLookup encoding discrepancy

turbo/snapshotsync/freezeblocks/block_snapshots.go
It looks like the closeIdx function here will close indexes while they are referenced by transactions.
This adds a check to stop that.
=> Dont reopen idx with refs

eth/stagedsync/exec3.go, eth/stagedsync/stage_execute.go, eth/stagedsync/stage_senders.go
Run into below error when running Astrid standalone. Handling blocks in Astrid is done by the driver, so we should not be calling ReportBadHeaderPoS in execution when run outside of Astrid. Additionally, ReportBadHeaderPoS should currently only be called for Ethereum-based PoS chains.
```
[INFO] [10-16|14:34:46.953] [4/6 Execution] Done                     blk=4540047 blks=4895 blk/s=1091.2 txs=10820 tx/s=2.41k gas/s=47.01M buf=566.5KB/512.0MB stepsInDB=0.00 step=5.9 alloc=307.2MB sys=920.5MB
panic: assignment to entry in nil map
goroutine 862285 [running]:
github.com/erigontech/erigon/turbo/stages/headerdownload.(*HeaderDownload).ReportBadHeaderPoS(0xc000b46a00, {0x9d, 0x6f, 0x66, 0x23, 0x29, 0x7d, 0x90, 0x89, 0x20, ...}, ...)
github.com/erigontech/erigon/turbo/stages/headerdownload/heade …
```
=> astrid: fix ReportBadHeaderPoS nil ptr in standalone

polygon/sync/execution_client.go, turbo/execution/eth1/forkchoice.go
For internal users of the execution api allow the option of not timing out so they can wait indefinitely.
To avoid api changes this is signaled by passing a 0 timeout which is interpreted as wait forever rather than return immediately.
=> Optionally disable fcu timer

.github/workflows/qa-rpc-integration-tests.yml
Enable more erigon_getBlockByTimestamp tests after a bug is fixed with this commit
https://github.com/erigontech/erigon/commit/b266c6562f18c0f28164387260e7497df089779f
=> qa-tests: enable more erigon_getBlockByTimestamp tests

.github/workflows/qa-snap-download.yml
Change snap-download test scheduling so as not to clash with the tip-tracking schedule
=> qa-tests: change snap-download scheduling

cmd/devnet/services/polygon/proofgenerator_test.go, turbo/jsonrpc/debug_api.go, turbo/jsonrpc/eth_receipts.go, turbo/jsonrpc/otterscan_api.go, turbo/jsonrpc/tracing.go, turbo/transactions/tracing.go
Refinement from #12315 as this condition should only be allowed under certain cases.
=> rpcdaemon: Only allow large txIndex for state sync transactions

.github/workflows/qa-rpc-integration-tests.yml, turbo/jsonrpc/otterscan_search_v3.go
fixes https://github.com/erigontech/erigon/issues/12248
This PR retrofits the receipts generator and remove lots of custom code in order to fix the tests.
However it should be noticed that the receipts generator currently replays the entire block and doesn't consume the receipts domain, i.e., eth_getTransactionReceipt still suffers from the same issue.
From our conversation on Discord, Illya is working on it, so let's wait for his work be finished and we can retrofit his optimizations if needed.
Also, I'm reenabling all `ots_searchTransactions*` rpc-tests, leaving only `ots_searchTransactionsBefore/test_13.json` out. From my analysis so far, that one is breaking because of another unrelated exception, so I need more time to debug separately.
=> Fix ots_searchTransactions* rpc-tests

cmd/devnet/services/polygon/proofgenerator_test.go, turbo/jsonrpc/otterscan_api.go, turbo/jsonrpc/receipts/receipts_generator.go, turbo/jsonrpc/tracing.go, turbo/transactions/tracing.go
A follow up to #12316, instead of relaxing conditions on `ComputeTxEnv` which may cause unintended edge cases, we split the function into two smaller, well-defined functions. When tracing state sync events, we do not care about generating TxContext so we can skip validation surrounding it.
=> rpcdaemon: Split ComputeTxEnv

turbo/jsonrpc/tracing.go, turbo/transactions/tracing.go
Following #12342, we were missing a check on `debug_traceBlockByNumber` for state sync events during `ComputeTxEnv`.
=> rpcdaemon: Add missing flag

turbo/jsonrpc/receipts/bor_receipts_generator.go
We were incorrectly setting `ContractAddress`, and missing some data in the log entries. This PR also refines the generator to use the newly introduced `ComputeBlockContext`.
=> rpcdaemon: Fix missing data in Bor receipts

cl/beacon/handler/rewards.go
The Beacon API specs say (rather not clearly, but still), that on non-participation of a validator in an epoch, no data should be returned.
See https://github.com/ethereum/beacon-APIs/issues/480
=> Fix sync_committee rewards to return no data on non-participation

erigon-lib/downloader/downloader.go, erigon-lib/downloader/downloader_grpc_server.go, erigon-lib/go.mod
```
Read at 0x00c001bee46c by goroutine 599:
github.com/erigontech/erigon-lib/downloader.(*Downloader).Completed()
github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:2933 +0x4b
github.com/erigontech/erigon-lib/downloader.(*GrpcServer).Completed()
github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader_grpc_server.go:153 +0x12
github.com/erigontech/erigon-lib/direct.(*DownloaderClient).Completed()
github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/direct/downloader_client.go:53 +0x5b
github.com/erigontech/erigon/turbo/snapshotsync.WaitForDownloader()
github.com/erigontech/erigon/turbo/snapshotsync/snapshotsync.go:372 +0x133a …
```
=> downloader: `.Completed()` method race fix

turbo/jsonrpc/bor_snapshot.go
**Fix: Outdated validatorByte Method in apply Function**
The outdated validatorByte method in apply() (found in turbo/jsonrpc/bor_snapshot.go) caused the newVals array to remain empty. As a result, the validator's power was always set to 0, leading to incorrect RPC information.
This bug affected the following RPC calls:
- getSnapshot
- bor_getSnapshotProposerSequence
**Changes:**
- Fixed the logic within the apply() function to ensure newVals is populated correctly.
- Validators now retain their proper power, resulting in accurate responses for the affected RPC calls.
This fix ensures that the snapshot and proposer sequence information are reflected correctly in RPC outputs.
=> turbo/jsonrpc: correction in fetching validatorByte in bor_snapshot.go

turbo/stages/headerdownload/header_algos.go
relates to https://github.com/erigontech/erigon/issues/11387, https://github.com/erigontech/erigon/issues/11473, https://github.com/erigontech/erigon/issues/10734
tried to simulate the OOM using https://github.com/erigontech/erigon/pull/11799
What I found was infinitely growing alloc of headers when receiving new header messages in sentry's `blockHeaders66` handler (check screenshot below).
It looks like this is happening because in the case of a bad child header: we delete it from the `links` map, however its parent link still holds a reference to it so the deleted link & header never get gc-ed. Furthermore if new similar bad hashes arrive after deletion they get appended to their parent header's link and the children of that link can grow indefinitely …
=> headerdownload: fix OOM due to inifinitely growing children in link

erigon-lib/commitment/hex_patricia_hashed_fuzz_test.go
problem: test can go to `2^32` random keys - and timeouting on CI
with `2^16` limit it takes ~20sec
probably we need re-work this fuzz test - to make it faster
=> speedup Fuzz_ProcessUpdates_ArbitraryUpdateCount

erigon-lib/commitment/hex_patricia_hashed_fuzz_test.go, turbo/execution/eth1/ethereum_execution.go, turbo/execution/eth1/inserters.go
```
panic: semaphore: released more than held
goroutine 10342 [running]:
golang.org/x/sync/semaphore.(*Weighted).Release(0xc002e8cdc0, 0x1114288c0?)
golang.org/x/sync@v0.8.0/semaphore/semaphore.go:127 +0xb8
github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).Start(0xc003766780, {0x10fef16f8, 0xc001901d60})
github.com/erigontech/erigon/turbo/execution/eth1/ethereum_execution.go:349 +0x167
created by github.com/erigontech/erigon/eth.(*Ethereum).Start in goroutine 1
github.com/erigontech/erigon/eth/backend.go:1516 +0xddf
exit status 2
```
=> handle error from `semaphore.Aquire` 

cmd/downloader/main.go, eth/backend.go
```
==================
Read at 0x00c0266a01e0 by goroutine 24836:
github.com/erigontech/erigon-lib/downloader.(*Downloader).notifyCompleted()
github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:2957 +0x665
github.com/erigontech/erigon-lib/downloader.(*Downloader).torrentCompleted()
github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:2946 +0x65d
github.com/erigontech/erigon-lib/downloader.(*Downloader).mainLoop.func2()
github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/downloader/downloader.go:956 +0x1f84
Previous write at 0x00c0266a01e0 by main goroutine:
github.com/erigontech/erigon-lib/downloader.NewGrpcServer() …
```
=> downloader: race at startup 

p2p/sentry/sentry_multi_client/sentry_multi_client.go, turbo/stages/bodydownload/body_algos.go, turbo/stages/bodydownload/body_data_struct.go
Block bodies no longer have requests after PR #12370
=> Remove remnants of requests from block body downloader

erigon-lib/state/aggregator.go
Fixed ```MDBX_TXN_OVERLAPPING: Overlapping read and write transactions for the current thread, label: chaindata, trace: [kv_mdbx.go:782 kv_mdbx.go:935 aggregator.go:1959 aggregator.go:1635 exec3.go:369 stage_execute.go:164 stage_execute.go:254 default_stages.go:238 sync.go:531 sync.go:410 forkchoice.go:453 asm_amd64.s:1695]"```
=> txn overlap

.github/workflows/qa-rpc-integration-tests.yml
Due to this commit: https://github.com/erigontech/erigon/pull/12430
=> rpc-tests: remove test on engine_exchangetransitionconfigurationv1

eth/tracers/logger/json_stream.go
Cherry pick #12241 into `release/2.61`
=>  Type of error field in structlog logger differs from geth, alloy

cmd/evm/internal/t8ntool/transition.go, core/types/access_list_tx.go, core/types/blob_tx.go, core/types/blob_tx_wrapper.go, core/types/block.go, core/types/dynamic_fee_tx.go, core/types/encdec_test.go, core/types/legacy_tx.go, core/types/set_code_tx.go, core/types/transaction.go, core/types/transaction_marshalling.go, core/types/transaction_test.go
Cherry pick #11512 into `release/2.61`
=> Block: use generic atomics

turbo/engineapi/engine_server.go, turbo/engineapi/interface.go
Fixes the issue when json decoding empty requests in param to `newPayload`, spefically, the following would keep coming up in Hive tests (EEST)
```
Exception: Error calling JSON RPC newPayloadV4, code: -32602, message: invalid argument 3: illegal base64 data at input byte 0
```
=> engineapi: Fix json unmarshal issue

.github/workflows/test-integration-caplin.yml
Cache is branch-specific.
For pull-requests based on some feature-branch we can skip cache and save available space on our workflow cache as well as time required to run workflow.
=> Use cache only for main and latest two release branches.

eth/stagedsync/exec3.go, eth/stagedsync/exec3_parallel.go
This is a non-functional refactor of ExecV3 which moves the parallel execution code out on the main function and puts it in a separate type/file
This is to facilitate parallel execution testing/development without merge clashes
=> Split out parallel exec

turbo/jsonrpc/eth_block.go
Until hive implements https://github.com/ethereum/execution-apis/pull/570
Partial revert of https://github.com/erigontech/erigon/pull/11809/files
The reason this would still work with or without the snapshot files change:
- RPC tests don't have to know about this PR, since it's based on a state with assumed nil for the `totalDifficulty` field.
- Hive tests don't progress till pruning, nor do they start with any snapshots (unless this changes somehow)
=> jsonrpc: Add totalDifficulty back as interim hive fix

.github/workflows/test-hive.yml
- Read the last AND second last lines to parse how many tests have failed.
- Re-enable test on push to `main`
=> workflows: Fix incorrect status print in CI hive test

.github/workflows/qa-rpc-integration-tests.yml
I ran all ots_ tests locally and they are all passing.
It seems they "fixed by themselves" as part of some other fix.
=> Reenable all ots_ rpc-tests

tests/init_test.go
Added parallel execution for integration tests which is speedup them by 25% in average
=> integration tests: added parallel execution

eth/stagedsync/sync.go
Reverting [this](https://github.com/erigontech/erigon/pull/11385/files#diff-1a50e885d0d9cf95e595879af5fe15ea7a65b9b8a7f7f637913f11a83b157989R451-R453) change because it broke the contract of `ExecutionEngine.UpdateForkChoice`. Previously calling `executionPipeline.Run` would not return error upon bad block and would eventually reach this [point](https://github.com/erigontech/erigon/blob/main/turbo/execution/eth1/forkchoice.go#L477) where we set the `ForkChoiceReceipt.Status` to `ExecutionStatus_BadBlock`. Now, however, because of this newly returned error we never reach there and the response doesn't have the correct status. Checked with @JkLondon and looks like returning this error may not be necessary.
This appeared during an Astrid run on mainnet as per the logs below. Astrid relies on …
=> stagedsync: revert Sync.Run return error on bad block

turbo/jsonrpc/trace_adhoc.go, turbo/jsonrpc/trace_filtering.go
Prior to this PR in `callManyTransactions` (invoked by `trace_block`) changes made by `InitializeBlockExecution` were discarded, leading to issues like #12432. That was immaterial before since no much was happening at the beginning of a block. But that changed in Dencun with [EIP-4788](https://eips.ethereum.org/EIPS/eip-4788) – see `(s *Merge) Initialize`.
=> trace API: commit state changes from InitializeBlockExecution

.github/workflows/qa-rpc-integration-tests.yml
Erigon2 v2.6x add correct **error reason** to some json rpc api responses.
Previously, the expected reason for the error was "{}".
Affected apis are `debug_traceCall`, `debug_traceCallMany`, `debug_traceTransaction`.
This PR uses a new branch of the rpc-tests repo that has been updated with these changes.
=> qa-tests: handle Erigon2 json rpc api improvements regarding the error reason

core/state_transition.go, erigon-lib/chain/chain_config.go
See https://github.com/gnosischain/specs/pull/51
=> EIP-4844-pectra (collect blob gas fee)

polygon/heimdall/client.go
reverts a change from https://github.com/erigontech/erigon/commit/73476abdb0de07654c3a1f9ca6567951e12c2900#diff-ace6e4f24916671d83adb720ebd0fff8e611f09ed451f334e92e10aeb8591525R489-R491
not sure why this has been done - seems like a weird hack that has been left behind maybe unintentionally - it is definitely unnecessary
main reason for removing is:
- it entirely circumvents the retryBackoff config of the client and always overrides the value which is wrong
- it slows down tests a lot - this test should take milliseconds, but after this change it takes a minute
=> heimdall/client: revert retryBackoff hack left behind

.github/workflows/qa-rpc-integration-tests.yml
Sometimes the changes made in the code cause the test to hang for a long time. 
To avoid delaying the other executions a timeout of 15 min is added (currently the executions take less than 5 minutes).
=> qa-tests: add timeout to rpc test suite

.github/workflows/qa-constrained-tip-tracking.yml, .github/workflows/qa-snap-download.yml, .github/workflows/qa-tip-tracking.yml
This PR re-schedule some tests to run at 08:00 PM UTC - It is a try to help team members working at non-EU timezones
=> qa-tests: change test scheduling

.github/workflows/ci-cd-main-branch-docker-images.yml
Keep only latest 100 docker images with tag matching pattern main-XXXXXXX
=> Cleanup old snapshot docker images (main-xxxxxxx).

.github/workflows/qa-rpc-integration-tests.yml, .github/workflows/scripts/run_rpc_tests.sh
Using a shell script to start the python test is useful 
- to manually launch tests on debug machines and 
- to allow us to insert comments that would otherwise violate yaml rules into the workflow
=> qa-tests: use external shell script in rpc tests

Makefile
changes:
-  7 chars for commit id
- match pattern *.*.* (for example -- it will match v2.60.9 or 2.60.9)
=> Sync GIT_TAG with main branch

eth/gasprice/feehistory.go
To read MaxBlobGasPerBlock it is necessary use the method GetMaxBlobGasPerBlock() that returns MAX_BLOB_GAS_PER_BLOCK (EIP-4844) if not override in config with custom value MaxBlobGasPerBlock
=> rpcdaemon: fix on FeeHistory check on GetMaxBlobGasPerBlock() method of chainConfig

turbo/jsonrpc/tracing.go
=> debug_traceCallMany: support of txIndex param

.github/workflows/scripts/run_rpc_tests.sh
Temporarily disable debug_storageRangeAt/test_11.json broken by  https://github.com/erigontech/erigon/pull/12642
=> qa-tests: disable failing test

.github/workflows/qa-sync-from-scratch.yml
This add chiado chain to sync-from-scratch test.
Erigon will be runned with:
```
--chain=chiado
--batchSize=1g
```
=> qa-tests: add chiado to sync from scratch test

cl/clparams/initial_state/initial_state.go
We couldn't start chiado without passing genesis state file and custom config. 
```
open /Users/shota/Desktop/work.nosync/datadir/caplin-chiado3/caplin/genesis/genesis_state.ssz_snappy: no such file or directory
```
Now
```
./build/bin/caplin --datadir ../datadir/caplin-chiado --chain=chiado
```
works.
=> fix generating genesis config for chiado

cl/clparams/config.go
trying to get Caplin to run on Chiado, need to update `EmbeddedSupported` for it otherwise E3 waits endlessly (no CL active to control it)
follow up from https://github.com/erigontech/erigon/pull/12699
=> cl/params: enable chiado embedded support

cl/cltypes/solid/uint64slice_byte.go, cl/merkle_tree/merkle_tree.go, cl/phase1/core/state/copy.go, cl/phase1/network/services/aggregate_and_proof_service.go
=> Caplin: reduced in `MerkleTree`'s `CopyInto`

core/rawdb/accessors_chain.go, erigon-lib/kv/tables.go, ethdb/privateapi/ethbackend.go, turbo/jsonrpc/eth_system.go
- fixes a nil pointer here https://github.com/erigontech/erigon/blob/main/ethdb/privateapi/ethbackend.go#L167 (need to initialise a SyncingReply_StageProgress pointer)
- fixes an issue where the api wasn't returning `false` when the node was following chain tip (regression in https://github.com/erigontech/erigon/pull/12505 due to setting `LastNewBlockSeen: math.MaxUint64`)
- tidies up some duplicate code in eth_syncing RPC API after moving the logic of it in ethbackend https://github.com/erigontech/erigon/pull/12505
=> privateapi: fix ethbackend.Syncing api nil dereference

turbo/node/node.go
minor one, log used to be showing up as devnet
```
Starting Erigon on "devnet"=chiado
```
=> turbo/node: log gnosis chain init not as a devnet

cmd/integration/commands/stages.go, eth/backend.go, eth/stagedsync/stage_polygon_sync.go, polygon/p2p/service.go, polygon/sync/service.go, polygon/sync/sync.go, turbo/shards/events.go, turbo/stages/stageloop.go
`eth_syncing` API used to flicker between syncing and not syncing during initial Astrid sync. This is due to how the initial sync algorithm works and the new last new block seen notification logic.
E.g.
This PR fixes this.
=> polygon/sync: notify about latest waypoint end block on initial sync

cmd/integration/commands/stages.go, core/rawdb/accessors_chain.go, eth/stagedsync/default_stages.go, eth/stagedsync/stage_execute.go, eth/stagedsync/stage_txlookup.go, turbo/jsonrpc/eth_call_test.go
adding periodic logging for some pruning operations because after recent changes we may spend a lot of time in pruning - this happened to me while doing dev work and for quite a long time it looked like my node is stuck - there was no info in the logs on what it is doing
=> stagedsync: add periodic progress logs for long prunning during initial sync

.github/workflows/release.yml
See https://github.com/erigontech/erigon/issues/12661 for more details.
Changes:
- workflow will create git tag referencing to the last commit id in "checkout_ref" (branch name as for now)
- in case of not successful build -- second job will start and will remove git tag.
- workflow will now contain useful name which reflects released version, branch used to build artifacts and person who run workflow.
- latest docker base images debian:12.8-slim
=> Create git tag before release build, small cosmetic changes.

erigon-lib/state/history.go, erigon-lib/state/inverted_index.go
my node had old and broken .ef file - i didn't know about it - until found that GetAsOf used one `.ef` file and totally different `.v` (because `.ef` returned some out-of-bound txNum). 
addad post-validation to `ii.seekInFiles` method
=> inverted_index: sanity error 

cl/beacon/beacontest/linux_basepathfs.go, cl/cltypes/solid/bitlist.go, cl/phase1/forkchoice/fork_graph/fork_graph_disk.go, cl/phase1/stages/stage_history_download.go, consensus/merge/merge_test.go
Fix some comments, including the name of the struct, the typos  in the comment.
=> chore: fix some comments

.github/workflows/ci-cd-main-branch-docker-images.yml, .goreleaser.yml, Makefile
Reintroducing `netgo` into the builds to fix the following issues:
https://github.com/erigontech/erigon/issues/12556
https://github.com/erigontech/erigon/issues/12570
`netgo` was removed in this PR:
https://github.com/erigontech/erigon/pull/7421
but didn't seem to fix that issue.
=> Reintroduce netgo (fix issues #12570 and #12556)

diagnostics/profile.go, turbo/app/support_cmd.go
Keep consistent with previous case naming, like:
```
case "application/json"
case "application/octet-stream"
```
=> chore: update profile's Content-Type

txnprovider/txpool/README.md
Move https://github.com/erigontech/erigon/wiki/Transaction-Pool-Design next to the code, like it's the case for `erigon-lib/etl`. Rationale: documentation sits next to the code; there're fewer places where documentation may live.
=> Move txpool wiki next to code

eth/stagedsync/stage_polygon_sync.go
e.executeForkChoice(tx) always returns err which is expected but the linter complains that there is an unnecessary if err != nil check in the caller of executeForkChoice which is a fair suggestion to remove
=> polygon: fix linter

cl/persistence/state/historical_states_reader/historical_states_reader.go, cmd/integration/commands/stages.go, eth/backend.go, eth/stagedsync/exec3.go, eth/stagedsync/stage.go, eth/stagedsync/stagedsynctest/harness.go, eth/stagedsync/stages/sync_mode.go, eth/stagedsync/sync.go, eth/stagedsync/sync_test.go, turbo/stages/mock/mock_sentry.go, turbo/stages/stageloop.go
releasing parts of https://github.com/erigontech/erigon/pull/12104 step-by-step
=> release sync mode type. no functional changes.

cl/clparams/config.go, eth/stagedsync/stages/sync_mode.go
Lighthouse VC was throwing the below error when running a validator with Caplin on Chiado:
```
The minimal/mainnet spec type of the beacon node does not match the validator
```
After a bit of debugging I found that it was because Lighthouse expects the preset base to be set to "gnosis"
=> cl: fix caplin interop with lighthouse vc on gnosis

consensus/merge/merge.go, consensus/misc/eip6110.go, tests/exec_spec_test.go, turbo/builder/block_builder.go, turbo/engineapi/engine_server.go, turbo/execution/eth1/block_building.go
- Add requests sidecar to Seal func
- Additional logging for better debugging on live networks
- Fix issue with requests in getPayload API
=> Block building fixes found for large deposit requests set

.github/workflows/ci-cd-main-branch-docker-images.yml, .goreleaser.yml, Makefile
The released binaries of erigon3-alpha5 have cross-compatibility issues as demonstrated here:
https://github.com/erigontech/erigon/issues/12556
https://github.com/erigontech/erigon/issues/12570
The reason for this was the static linking of system libraries which may not work correctly  in other operating systems (e.g. Arch Linux).
This problem can be averted by producing a dynamically linked binary instead, and assume that the user has correctly working system library dependencies.
=> Switch to dynamically linked binaries in goreleaser

README.md
I removed the section titled '#blocks-execution-is-slow-on-cloud-network-drives' from the README because the title did not exist. This action is called 'cleaning up invalid or erroneous content'
=> docs: removed a non-existent section from the README

erigon-lib/state/cache.go, erigon-lib/state/domain.go
- no prealloc to reduce unit-tests RAM use
=> d_lru: no prealloc, increase limit

.github/workflows/qa-constrained-tip-tracking.yml, .github/workflows/qa-rpc-integration-tests.yml
This PR modifies the tip-tracking test to test Erigon on the chain tip by limiting the ram usage to 32gb (previously 64gb).
The ram limitation was obtained via cgroups:
```
cgcreate -a runner_user:runner_user -g memory:constrained_res_32G -t runner_user:runner_user
cgset -r memory.max=32G constrained_res_32G
cgset -r memory.swap.max=max constrained_res_32G
```
One [run](https://github.com/erigontech/erigon/actions/runs/11939412573/job/33279879839) showed some difficulty holding the tip. It is not clear if this was a coincidence.
=> qa-tests: test Erigon on a 32GB memory machine

cl/beacon/handler/block_production.go, cl/beacon/handler/handler.go, cl/beacon/handler/utils_test.go, cl/beacon/synced_data/synced_data.go, cl/phase1/forkchoice/fork_choice_test.go, cl/phase1/network/gossip_manager.go, cl/phase1/network/services/aggregate_and_proof_service.go, cl/phase1/network/services/aggregate_and_proof_service_test.go, cl/phase1/network/services/attestation_service.go, cl/phase1/network/services/attestation_service_test.go, cl/phase1/network/services/blob_sidecar_service_test.go, cl/phase1/network/services/block_service_test.go, cl/phase1/network/services/bls_to_execution_change_service_test.go, cl/phase1/network/services/proposer_slashing_service_test.go, cl/phase1/network/services/sync_committee_messages_service_test.go, cl/phase1/network/services/sync_contribution_service_test.go, cl/phase1/network/services/voluntary_exit_service_test.go, cl/phase1/network/tb_rate_limiter.go, cl/phase1/stages/forkchoice.go, cl/sentinel/gossip.go, cl/sentinel/service/service.go, cl/spectest/consensus_tests/fork_choice.go, cl/validator/attestation_producer/attestation_producer.go, cmd/caplin/caplin1/run.go
Issues: 
- Had to fix an hack I added for a race
- Basically we need to process attestations otherwise the network kicks us out. However, we can rate limit the stream.
- Fixed switching ENRs logic
=> Caplin: Fixed single validator performance 

cl/beacon/handler/block_production.go, cl/phase1/stages/forkchoice.go, cl/validator/attestation_producer/attestation_producer.go, cl/validator/attestation_producer/interface.go
Cache attestation before calling `OnHeadState`, the reason why it was a probably is that it takes up to a second to update the head state but if we wait too much other nodes might stop accepting attestations and we may lose the block vote
=> Caplin: fix occasional missed attestations

cmd/commitment-prefix/readme.md, cmd/evm/testdata/10/readme.md, erigon-lib/kv/temporal/historyv2/readme.md
**PR Description:**
###Fixed typos in documentation:
- `proceeded` → `processed` in `cmd/commitment-prefix/readme.md`.
- `misbehaving` → `misbehaved` in `testdata/t8/readme.md`.
- `became` → `becomes` in `erigon-lib/kv/tempora/historyv2/readme.md`.
=> Fix Typos in Documentation Files

.github/workflows/kurtosis/pectra.io, .github/workflows/kurtosis/regular-assertoor.io, .github/workflows/test-kurtosis-assertoor.yml
Cherry pick https://github.com/erigontech/erigon/pull/12889
- Adding Pectra kurtosis/assertoor tests from Ethpandaops in the workflows
- Renaming file for regular kurtosis from `config.properties` to `regular-kurtosis.io` as it supports syntax highlighting on vscode(possibly others) for yaml-like file
=> workflows: add Pectra kurtosis assertoor tests (#12889)

cmd/devnet/README.md
The previous link has expired and has been replaced with the latest address.
=> chore: fix 404 status URL in cmd/devnet/README.md

erigon-lib/commitment/commitment.go, erigon-lib/commitment/commitment_bench_test.go
`binary.Write` is slow: 
- does dynamic interface method call 
- does alloc
- bench of `binary.Write` vs `binary.BigEndian.PutUint32` shows 100ns vs 1ns 
Also i turned `putUvarAndVal` into method (otherwise it allocates closure - and it's context).
=> commitment: avoid binary.Wirte 

erigon-lib/commitment/hex_patricia_hashed.go
follow up on https://github.com/erigontech/erigon/pull/12812
=> commitment: reuse pre-allocated buffer for hash computation, step2

erigon-lib/kv/mdbx/kv_mdbx_temporary.go, eth/stagedsync/stage_bodies.go, p2p/sentry/sentry_multi_client/sentry_multi_client.go, turbo/engineapi/engine_block_downloader/block_downloader.go, turbo/engineapi/engine_block_downloader/body.go, turbo/engineapi/engine_block_downloader/core.go, turbo/engineapi/engine_server.go, turbo/stages/bodydownload/body_algos.go, turbo/stages/bodydownload/body_test.go
Fixes https://github.com/erigontech/erigon/issues/12225
=> Fix externalcl integration for erigon3

erigon-lib/downloader/README.md, erigon-lib/downloader/mdbx_piece_completion.go
- `availible` -> `available`
- Correct spelling of "available" in documentation
- `seperate` -> `separate` 
- Correct spelling of "separate" in documentation
- `reather` -> `rather`
- Correct spelling of "rather" in documentation
- `intefere` -> `interfere`
- Correct spelling of "interfere" in code comment
The changes fix typos and grammatical errors to improve code documentation quality and readability. Having correct spelling and grammar in documentation and comments helps other developers better understand the codebase.
All changes are simple text corrections with no functional code changes.
=>  Fix typos in documentation and comments

cmd/evm/runner.go, cmd/evm/staterunner.go, cmd/integration/commands/stages.go, cmd/rpcdaemon/cli/config.go, core/genesis_write.go, core/rawdb/rawdbhelpers/rawdbhelpers.go, core/vm/runtime/runtime.go, erigon-lib/config3/config3.go, erigon-lib/kv/temporal/temporaltest/kv_temporal_testdb.go, erigon-lib/state/files_item.go, eth/backend.go, eth/stagedsync/exec3.go, turbo/app/snapshots_cmd.go, turbo/app/squeeze_cmd.go, turbo/snapshotsync/snapshotsync.go
I always forget that constant name when I need to check the value, let's rename it to something more direct.
I think we could also rename/move the package "config3" to some other place with global constants, but no idea of good place.
=> Rename constant to DefaultStepSize

erigon-lib/kv/mdbx/kv_mdbx_temporary.go, turbo/engineapi/engine_block_downloader/block_downloader.go, turbo/engineapi/engine_block_downloader/body.go, turbo/engineapi/engine_block_downloader/core.go
Fixes https://github.com/erigontech/erigon/issues/12225
=> Additional fix for externalCL integration (prevent MDBX_MAP_FULL)

erigon-lib/state/aggregator.go, erigon-lib/state/history_test.go, erigon-lib/state/merge.go, eth/stagedsync/stage_snapshots.go, turbo/app/snapshots_cmd.go
It seems the "build optional missed indices" does nothing now and all the chain of calls can be safely removed.
Please ignore otherwise or if want to keep the code.
=> Remove optional missed indices; code is noop

cmd/integration/commands/state_domains.go, core/state/cached_reader.go, core/state/cached_reader3.go, core/state/database.go, core/state/database_test.go, core/state/history_reader_v3.go, core/state/intra_block_state.go, core/state/rw_v3.go, core/state/state_object.go, eth/stagedsync/stage_mining_exec.go, turbo/jsonrpc/eth_accounts.go
- moved empty-code-hash check to callers: `ibs` and `stateObject`
- removed CodeHash param from state reader interface (E3 does store code by acc address. E2 did by code hash)
=> StateReader: remove CodeHash parameter

erigon-lib/state/cache.go, erigon-lib/state/domain.go
- decompressing CodeDomain values: taking ~7% of execution speed
=> d_lru: to store decompressed values

erigon-lib/state/domain_shared.go
now `.Account()` method does 2 reads - but on pprof i can't separate "which of them impacts performance. created named funcs for them. 
Pic after change:
=> sdc.Account: separate reads by domain on pprof

erigon-lib/go.mod, erigon-lib/go.sum, erigon-lib/state/existence_filter.go, go.mod, go.sum
- bloom is not different from other files
- we can't afford reading 5TB at each startup (all files) and checksum it
- also such read may flood PageCache
- so we trying to minimize amount of reads at startup
- we have `.torrent` for each file - which is "array of chunks checkums". We can verify checksums at any time by `downloader --verify` or `--verify.failfast`. 
- yes, need to open PR to origin repo. but currently i need to keep focus on e3 release.
=> bloom: don't calc checksum at startup

Dockerfile.release
See https://github.com/erigontech/erigon/issues/12900 for more details.
1. Hardcode uid/gid to 1000/1000 in order to prevent potential change in the future, once such uid or gid already exist.
It should simplify upgrade for our users.
2. Install binaries with owner/group root/root for security reasons.
=> Feature/lystopad/issue 12900 (#12957)

cmd/integration/commands/stages.go, core/rawdb/rawdbreset/reset_stages.go, eth/stagedsync/stage_headers.go, eth/stagedsync/stage_polygon_sync.go
An `UnwindReason` created w/o an error (by `ForkReset`) means that a block has to be unwound, but it's not bad, so it shouldn't be inserted into `BadHeaderNumber` by `TruncateCanonicalHash`. `ForkReset` is used in Bor milestone rewind.
=> Don't mark unwound non-bad blocks as bad

p2p/sentry/sentry_grpc_server.go, txnprovider/txpool/send.go
[eth/68](https://eips.ethereum.org/EIPS/eip-5793) and eth/67 are only different w.r.t. to `NewPooledTransactionHashes`. Previously the determination of `msgcode` was sometimes failing because it relied only on one protocol version,  namely `ss.Protocols[0].Version`.
=> Fix eth/67 vs eth/68 peers for NewPooledTransactionHashes

erigon-lib/state/inverted_index.go
Throw error in `seekInFiles`  if txNum is less than smallest txNum in files.
Eventually this error needs to be handled by IntrablockState, and ideally the RPC call layer should check if the data is available to serve the request, but that will be a feature for later.
Issue: https://github.com/erigontech/erigon/issues/12977
=> Throw error if txNum is less than smallest txNum in files

.github/workflows/release.yml, .github/workflows/reusable-release-build-debian-pkg.yml
See https://github.com/erigontech/erigon/issues/12891 for more details.
Changes:
- new reusable workflow for building debian packages
- this reusable workflow is a part of release workflow. Binaries which is built during build stage used to build docker image, debian package and to publish as release artifacts.
=> Add support for building Debian packages (arm/amd) in the release workflow.

cl/beacon/handler/block_production.go, cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go
so the issues is that decoding caches from disk was too IO intensive. this does one batch read and calls it a day.
=> Caplin: better fix for orphaned blocks

erigon-lib/common/errors/errors.go, erigon-lib/kv/stream/stream_interface.go, erigon-lib/recsplit/eliasfano32/elias_fano.go, erigon-lib/recsplit/eliasfano32/elias_fano_test.go
As part of https://github.com/erigontech/erigon/pull/12907 I'll have other iterator-like sequence implementations.
It makes sense to generalize the ErrEliasFanoIterExhausted and move it to a common package and reuse it, rather than making a bunch of IteratorExhausted-like for each implementation.
=> Generalize iterator exhausted error

core/types/block.go, turbo/snapshotsync/freezeblocks/block_reader.go
Apparently we saved some pre-Shappella blocks into snapshots with empty rather than nil withdrawals. This is a work-around for issues like #12297 to avoid regenerating block snapshots. You can see the problem by running
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x103716A",false],"id":1}' http://localhost:8545
```
=> Pre-Shapella blocks must have nil withdrawals

params/version.go, turbo/engineapi/engine_server.go, turbo/engineapi/engine_types/jsonrpc.go, turbo/engineapi/interface.go
A rather simple implementation for `engine_getClientVersionV1`
=> Implement GetClientVersionV1

cmd/devnet/README.md, cmd/evm/testdata/9/readme.md, erigon-lib/downloader/README.md, p2p/simulations/README.md
This pull request addresses multiple typos found in various `README.md` files.  
**Summary of Changes:**  
1. Corrected the use of "a" to "an" where appropriate (e.g., before words starting with a vowel sound).  
2. Adjusted grammatical errors and refined phrasing for clarity.  
3. Ensured consistent usage of terms across files (e.g., "an HTTP API" instead of "a HTTP API").  
**Files Modified:**  
- `cmd/devnet/README.md`  
- `cmd/evm/testdata/9/readme.md`  
- `erigon-lib/downloader/README.md`  
- `p2p/simulations/README.md`  
These updates enhance the readability and grammatical accuracy of the documentation.
=> Fix typos in README files across multiple directories

docs/examples/single-process.md
I noticed that there were extra quotation marks in the commands section, specifically after the `--chain=sepolia` and `--port=30304` options
This caused a syntax issue when trying to execute the commands. The unnecessary quotation marks have been removed to ensure the commands work properly without errors.
Here is the corrected version:
```bash
--chain=sepolia \
--port=30304 \
```
This change is important because it prevents syntax errors that could confuse users or lead to failed command executions.
=> Fix extra quotation marks in the command section

.github/workflows/kurtosis/regular-assertoor.io
Should fix the recent broken kurtosis tests due to some Lighthouse or Nimbus release
=> workflows: use fixed CL images for kurtosis-assertoor tests

cl/beacon/handler/block_production.go, cl/clparams/config.go
=> Add `MAX_BLOB_COMMITMENTS_PER_BLOCK` in Caplin Beacon API /eth/v1/config/spec

eth/stagedsync/stage_polygon_sync.go
the `err` has been checked. so it's value must be nil, so should return `r.err`
I have an idea to detect code that returns a non-relevant nilness error bug. I checked the top 1000 GitHub Go repositories and found this, all result listed in https://github.com/alingse/sundrylint/issues/4
=> fix: check `r.err != nil` but return a nil value error `err`

cmd/rpcdaemon/cli/config.go, consensus/aura/aura.go, consensus/aura/epoch.go, erigon-lib/kv/helpers.go, erigon-lib/kv/tables.go, polygon/bor/bor.go
=> Implement AuRa remoteConsensusEngine

eth/backend.go
While working on Shutter, I decided to follow the same `Run(ctx)` pattern that we use in Astrid to initiate long running background goroutines which are ctx aware and do their own shutdown/cleanup logic as part of defers inside `Run(ctx)` so that when the parent ctx is cancelled each component with a Run manages its own shutdown logic.
However, I noticed that when the `Ethereum.Close` function is called we do not wait for these `Run` functions of  bg goroutines to finish before exiting the `Close` function. So I added a `bgComponentsEg` errgroup to the `Ethereum` object which is used in `Start` and `Close` to wait properly in the following Shutter PR https://github.com/erigontech/erigon/pull/13081/files#diff-9cc7046826ce92d9cc5432cf41ed4fc14bb6907da44f771e3932302c40e8dbc2R1640-R1643. …
=> polygon: astrid service to run inside bg components errgroup for shutdown wait

turbo/jsonrpc/eth_receipts.go, turbo/jsonrpc/receipts/receipts_generator.go
closes #13088
Not really sure about 2 caches conception but like it
=> cache tx granularity

.github/workflows/release.yml, Dockerfile.release
Fix for the https://github.com/erigontech/erigon/issues/13092 
Main changes:
- get rid of goreleaser, build binaries on Debian based golang docker containers;
- **get rid of Darwin artifacts: only linux artifacts will be published;**
- switch from Alpine base image to Debian one;
- sync with release workflow in release/2.6x
- preparation for Silkworm (which is not yet ready for 3.x) support;
=> Changes in the release workflow: get rid of goreleaser, debian base image, etc.

.github/workflows/release.yml
job is frozen on xxlarge runner for some reasons.
=> Run release workflow on default runner

.github/workflows/manifest.yml
This restricts the manifest check to those sources which are actually contributing to snapshots distribution.
=> Selective check for manifest

cmd/utils/flags.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, txnprovider/provider.go, txnprovider/shutter/config.go, txnprovider/shutter/pool.go
pretty straightforward tidy up PR
1. moves DisableTxPoolGossip from ethconfig.Config to txpoolcfg.Config
2. adds some license/doc comments to tidy up previous PR
=> txpool: tidy NoGossip config

accounts/abi/bind/bind.go, accounts/abi/bind/bind_test.go
Cherrypick https://github.com/ethereum/go-ethereum/pull/25307
* accounts/abi: substitude arg%d to the range keyword
* support more keywords
* review feedback
=> accounts/abi: substitude arg%d to the range keyword (#25307)

erigon-lib/go.mod, go.mod, go.sum
Rolls back the snapshot lib update introduced in https://github.com/erigontech/erigon/pull/13163
=> Rollback snapshot lib

turbo/jsonrpc/tracing.go
The check on gasUsed should be done only if refund is true (default case)
=> debug_traceBlockByNumber with refund=false

p2p/enode/nodedb.go
pick https://github.com/erigontech/erigon/pull/10114
for https://github.com/erigontech/erigon/issues/12826
=> e2 nodedb: batch updates as in E3

.github/workflows/qa-clean-exit-block-downloading.yml, .github/workflows/qa-tip-tracking.yml
tip-tracking and clean-exit (block downloading) require the prebuilt db to be copied before execution, so as not to corrupt it. But the prebuilt db has grown in size and there is no room to keep 2 copies of it on the runner.
So, as a temporary solution, we will run tests on release/2.6x on the pre-built db itself, and not on its copy.
=> qa-tests: temporary solution for runner n.1 out of space 

cl/phase1/core/state/cache.go, cl/phase1/core/state/ssz_test.go, cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go
This PR should simplify the cache system during reorgs by removing caches which should not be bottlenecks anymore
=> Caplin: simplified cache-query

erigon-lib/downloader/snaptype/files.go, erigon-lib/seg/seg_auto_rw.go, erigon-lib/state/aggregator.go, erigon-lib/state/aggregator_test.go, erigon-lib/state/domain.go, erigon-lib/state/domain_committed.go, erigon-lib/state/domain_shared.go, erigon-lib/state/files_item.go, erigon-lib/state/history.go, erigon-lib/state/inverted_index.go, erigon-lib/state/merge.go, erigon-lib/state/squeeze.go, turbo/app/snapshots_cmd.go, turbo/rpchelper/helper.go
- `torrent_create --all`
- seedable files list
=> `.kvi` support in tooling

erigon-lib/event/notifier.go, erigon-lib/event/observers.go, polygon/heimdall/scraper.go, polygon/heimdall/service.go, polygon/p2p/message_listener.go, polygon/p2p/peer_event_registrar.go, polygon/p2p/peer_event_registrar_mock.go, polygon/p2p/peer_tracker.go, polygon/p2p/peer_tracker_test.go, polygon/p2p/publisher_test.go, polygon/p2p/service.go, polygon/sync/tip_events.go
moving `EventNotifier` and `Observers` structs from `polygon/polygoncommon` pkg to `erigon-lib/event` pkg since those will be used in other packages outside of polygon (e.g. using in `shutter` pkg as part of https://github.com/erigontech/erigon/pull/13306)
=> erigon-lib: move event notifier and observers to erigon-lib

Makefile
Backport from main branch.
See https://github.com/erigontech/erigon/issues/11715
=> Build with GOAMD64=v2 by default for AMD64 arch.

wmake.ps1
This pull request addresses a typo in the `wmake.ps1` file:
- Corrected "insterted" to "inserted" in a comment.
- Improved the accuracy of comments by fixing a minor spelling error.
This change only updates a comment in the script and does not affect the script's functionality. No additional testing is required.
Please review the corrected comment to ensure compliance with the project's documentation standards. Let me know if further updates are necessary. Thank you!
=>  typo fix Update wmake.ps1

accounts/abi/event.go, accounts/abi/reflect.go, accounts/abi/type_test.go, cl/cltypes/block_production.go, cmd/erigoncustom/main.go, consensus/aura/config.go, consensus/merge/merge.go, turbo/node/node.go
This pull request corrects the use of articles in multiple code files, specifically replacing the incorrect "a" with "an" and vice versa in places where the next word starts with a vowel sound or a consonant sound. 
These changes improve the clarity and grammatical accuracy of comments and documentation.
=> Fix article usage in code comments and documentation

cl/beacon/beaconhttp/api.go, cl/beacon/handler/handler.go, cl/beacon/handler/node.go
This fixes an issue where correct response headers were not set for these endpoints. Specifically, `Content-Type` was being set to `text/plain` instead of `application/json`.
=> caplin: Use `HandleEndpointFunc` for `node` endpoints

erigon-lib/downloader/downloader.go
Set initial values `prevStats.BytesDownload` and `prevStats.BytesCompleted` if they are zero, which can occur if the node was restarted or launched for first time.
Fix for https://github.com/erigontech/erigon/issues/13250 and https://github.com/erigontech/erigon/issues/13044
=> downloader: show correct rates after restart

cl/beacon/handler/block_production.go, cl/cltypes/solid/hash_list.go, cl/cltypes/solid/uint64slice_byte.go, cl/cltypes/solid/validator_set.go, cl/merkle_tree/merkle_tree.go, cl/phase1/core/state/cache.go
* It was a pre-optimization and it is now not needed
* simpler code
* less headaches for concurrency
=> Caplin: Remove cache files completely

turbo/jsonrpc/eth_block.go
Fixes #12690
```bash
➜  ~ curl --request POST \
-s --url http://127.0.0.1:8545/ \
--header 'Content-Type: application/json' \
--data '{
"method": "eth_getBlockByNumber",
"params": [
"0x3F515FC",
false
],
"id": 1,
"jsonrpc": "2.0"
}' | jq '.result.miner'
"0x83d69448f88bf9c701c1b93f43e1f753d39b2632"
➜  ~ curl --request POST \
-s --url http://127.0.0.1:8545/ \
--header 'Content-Type: application/json' \
--data '{
"method": "eth_getBlockByHash",
"params": [
"0xd925f567ee22d63a003f890af94c1e77e6d4d55a3bcef2b35b7b2317948d7f28",
false
],
"id": 1,
"jsonrpc": "2.0"
}' | jq '.result.miner'
"0x83d69448f88bf9c701c1b93f43e1f753d39b2632"
```
=> rpcdaemon: Set miner on `eth_getBlockByNumber` on Polygon

polygon/bridge/snapshot_store.go
Running Amoy with --no-downloader failed with trie root mismatch because the bridge didn't return correct events mapping for the first block with events which is 35072. This was because the snapshot store incorrectly checked in snapshots instead of in the DB store when Events was called with start=0
=> polygon: astrid fix --no-downloader issue due to bridge snapshot store bug

params/protocol_params.go, tests/exec_spec_test.go
See: https://github.com/ethereum/EIPs/pull/9144
=> BlockHash EIP-2935 changes for pectra-devnet-5 

turbo/engineapi/engine_api_methods.go, turbo/engineapi/engine_types/jsonrpc.go
For specs: https://github.com/ethereum/execution-apis/blob/main/src/engine/identification.md#engine_getclientversionv1
The issue earlier was in json marshalling of strings returned by CL clients. Since Git commits are already hex, no need to further hexlify the string.
Commit string with "0x" prefix - that's contentious
The version string doesn't have size limits, hence extending it to what we would be using otherwise.
=> engineapi: Fix `engine_getClientVersionV1`

cmd/utils/flags.go
Follow up after https://github.com/erigontech/erigon/pull/13003 changed default devp2p peers from 100 to 32
Keep the previous default of 100 pers for polygon since the recommendation for it is to keep a higher peer count as per recent changes to their peering strategy - https://forum.polygon.technology/t/introducing-our-new-dns-discovery-for-polygon-pos-faster-smarter-more-connected/19871
=> polygon: keep devp2p max peers default to 100 as before

accounts/abi/bind/bind.go, accounts/abi/bind/bind_test.go
Cherrypick https://github.com/ethereum/go-ethereum/pull/25307
* accounts/abi: substitude arg%d to the range keyword
* support more keywords
* review feedback
=> accounts/abi: substitude arg%d to the range keyword (#25307) (#13190)

cl/antiquary/beacon_states_collector.go
Seems it happens with many allocs in ETL buffers
=> Fixed `cannot alloc memory`

erigon-lib/commitment/hex_patricia_hashed.go
Closes https://github.com/erigontech/erigon/issues/13235
=> commitment: clarify update kind based on `afterMap`

README.md
Current source: https://erigon.tech/erigon-3-alpha-2-introducing-blazingly-fast-sync-on-archive-nodes-with-ottersync-and-other-improvements/
In the future we might want to update this based on automatically collected QA testing data.
=> Add sync times table in readme

.github/workflows/ci.yml, .github/workflows/test-integration-caplin.yml, .github/workflows/test-integration.yml, params/protocol_params.go
See https://github.com/ethereum/EIPs/pull/9119 and https://github.com/ethereum/EIPs/pull/9118
Cherry pick https://github.com/erigontech/erigon/pull/13069
=> Update addresses for EIPs 7002 and 7251 (#13069)

consensus/merge/merge.go, consensus/misc/eip6110.go, consensus/misc/eip7002.go, consensus/misc/eip7251.go, core/blockchain.go, core/types/block.go, core/types/eip7685_requests.go, core/types/reqeusts_test.go, core/types/requests_test.go, turbo/builder/block_builder.go, turbo/engineapi/engine_server.go, turbo/execution/eth1/block_building.go
The updated EIP-7685 says requests with empty `request_data` should be dropped from `executionRequests` field in the API and ignored for hash calculation.
See https://github.com/ethereum/EIPs/pull/8989, https://github.com/ethereum/execution-apis/pull/599
=> Update Empty requests list behaviour for Pectra-5

core/genesis_write.go
`erigon init genesis.json` was causing a genesis block to be created with the wrong hash due to using inccorrect RequestsHash for blocks before Prague
this caused the Hive tests to fail with:
```
parent's total difficulty not found with hash 6549118a1de2c28b204c671688e0aa4f6b522e72bf3a4a3f76cc8def0a7ecc8f and height 0: <nil>
```
when trying to insert blocks, causing a considerable amount of tests in rpc-compat to fail, hence making the CI red
=> core: fix genesis to block to use empty requests hash to fix Hive tests

core/genesis_write.go
e2 port of https://github.com/erigontech/erigon/pull/13436
`erigon init genesis.json` was causing a genesis block to be created with the wrong hash due to using inccorrect RequestsHash for blocks before Prague
this caused the Hive tests to fail with:
```
parent's total difficulty not found with hash 6549118a1de2c28b204c671688e0aa4f6b522e72bf3a4a3f76cc8def0a7ecc8f and height 0: <nil>
```
when trying to insert blocks, causing a considerable amount of tests in rpc-compat to fail, hence making the CI red
=> core: fix genesis to block to use empty requests hash to fix Hive tests (#13436)

eth/backend.go
QA test failed after https://github.com/erigontech/erigon/pull/13376 with 
```
!!->[EROR] [01-15|15:37:50.790] catch panic                              err="interface conversion: chain.BorConfig is nil, not *borcfg.BorConfig" stack="[main.go:46 panic.go:770 iface.go:262 iface.go:272 service.go:52 backend.go:983 node.go:143 main.go:98 make_app.go:71 command.go:276 app.go:333 app.go:307 main.go:51 proc.go:271 asm_amd64.s:1695]"
*** - 2025-01-15 15:38:48 - Check failed: panic
```
https://github.com/erigontech/erigon/actions/runs/12791773578/job/35660649947
=> backend: fix interface conversion: chain.BorConfig is nil panic

turbo/cli/default_flags.go
the following line was missing from https://github.com/erigontech/erigon/pull/13107
=> Enable param on erigon binary

accounts/abi/bind/backends/simulated.go, cmd/devnet/services/polygon/proofgenerator_test.go, cmd/state/commands/opcode_tracer.go, cmd/state/exec3/state.go, consensus/merge/merge.go, consensus/misc/eip1559.go, consensus/misc/eip4844.go, core/blockchain.go, core/chain_makers.go, core/evm.go, erigon-lib/chain/chain_config.go, eth/ethutils/receipt.go, eth/gasprice/feehistory.go, eth/stagedsync/stage_mining_exec.go, tests/exec_spec_test.go, tests/state_test_util.go, turbo/engineapi/engine_server.go, turbo/execution/eth1/inserters.go, turbo/jsonrpc/eth_system.go, turbo/jsonrpc/receipts/receipts_generator.go, turbo/stages/mock/mock_sentry.go, turbo/stages/stageloop.go, txnprovider/txpool/assemble.go, txnprovider/txpool/pool.go, txnprovider/txpool/pool_fuzz_test.go, txnprovider/txpool/pool_test.go
See https://github.com/ethereum/EIPs/pull/9060
Tasks board - https://github.com/erigontech/erigon/issues/12401
=>  Implement EIP-7691 blob gas price changes for pdn-5

erigon-lib/downloader/downloader.go
Removed `rate` value from logs as it duplicates download or completion rate
=> removed rate value

polygon/sync/sync.go
closes https://github.com/erigontech/erigon/issues/13474
=> polygon/sync: fix race due to header copy

core/types/block.go, core/types/block_test.go, core/types/encdec_test.go
relates to https://github.com/erigontech/erigon/pull/13480
fully fixes https://github.com/erigontech/erigon/issues/13474
Seems like `Header.hash` memoization changes from a few months ago have made `Block.Header()` (which makes a copy by calling `CopyHeader`) show race warnings. This is because we are copying over `atomic.Pointer` in `CopyHeader`.  
This PR fixes this by manually copy-ing all fields and skipping copy of the `hash atomic.Pointer` attribute (instead it will get set using its zero value - correct behaviour) and then the hash will be memoized using it as part of the copy later on.
This is a bit clumsier as we can miss updating the `CopyHeader` function when adding new attributes to the `Header` struct - to address that I've added a reflection based test which will generate …
=> core: fix header copy race

cl/phase1/network/services/sync_committee_messages_service.go, cl/sentinel/handlers/blobs.go
added circuit breaker if too many iterations are performed
=> Caplin: fixed remote DOS

erigon-lib/chain/chain_config.go, polygon/bor/borcfg/bor_config.go
Print
`"{ChainID: 1, Terminal Total Difficulty: 58750000000000000000000, Shapella: 2023-04-12 22:27:35 +0000 UTC, Dencun: 2024-03-13 13:55:35 +0000 UTC, Pectra: <nil>, Fusaka: <nil>, Engine: ethash}"`
instead of 
`"{ChainID: 1, Homestead: 1150000, DAO:
1920000, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773
000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: 
1681338455, Cancun: 1710338135, Prague: <nil>, Osaka: <nil>, Engine: ethash}"`
Also print the last three forks for Polygon.
=> [UX] Print only recent forks in chain config

erigon-lib/go.mod, erigon-lib/go.sum, go.mod, go.sum
If Ottersync fails to download latest erigon-snapshot `.toml` version from `raw.github.com` (e.g. due to Issue #13171), it'll fall back to the version in `go.mod`, so it makes sense to update it from time to time.
This updates the version to https://github.com/erigontech/erigon-snapshot/commit/6cc4c0c
=> deps: update erigon-snapshot to 6cc4c0c

Makefile, turbo/engineapi/engine_server.go
Fix issues like header hash mismatch in hive tests for pectra-devnet-5
`RequestData` refers to the raw output from the various different requests contract, in the rest of the code
=> engineapi: fix req root mismatch upon `newPayload`

erigon-lib/chain/snapcfg/util.go, turbo/snapshotsync/merger.go
Now it does too much allocs because often parsing file names of `.Preverified` immutable list: 
I don't want to make more complex changes before `beta1` release - so small memoization is enough.
=> optimize FindMergeRange

erigon-lib/state/domain.go, erigon-lib/state/files_item.go, erigon-lib/state/files_test.go, erigon-lib/state/history.go, erigon-lib/state/inverted_index.go
- one change is that earlier, if `dir.FileExist(fName)` returned error, we would log and continue (in ii/history). Now we panic in domain/ii/history.
- the error "not found" is already handled by this method (it returns exists=false, err=nil); while for other errors we crash. This should be okay.
- issue: https://github.com/erigontech/erigon/issues/12798
=> dedup find missed accessors logic

cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go, eth/stagedsync/stage_polygon_sync.go, polygon/bridge/mdbx_store.go, polygon/bridge/service.go, polygon/bridge/store.go, polygon/sync/sync.go
fixes https://github.com/erigontech/erigon/issues/13493
Error:
`pos sync store failed: nonsequential block in bridge processing: 66842880 != 66842848"`
Happened because we were inserting `ProcessedBlockInfo` with gaps when processing a batch of blocks in `ProcessNewBlocks` that contain more than 1 sprint start block. We should always be inserting 1 `ProcessedBlockInfo` per sprint start block. In this particular case however, we were only inserting the last 1 - causing a gap in the table. This manifested itself as an error in rare situations when bridge unwinds happened due to change of forks.
This PR also adds some store flush and bridge synchronisation points that we've missed to avoid race conditions.
=> polygon/bridge: fix process new blocks gaps

.github/workflows/qa-tip-tracking-polygon.yml
To speed up erigon on polygon and avoid it not reaching the tip in the expected test times when the pre build db is old, we opt to run in full node instead of archive node.
We also extend the test times as required to be able to see spikes on the block_consumer_delay metric
=> tip-tracking: use full node and increase test time on polygon

p2p/enode/nodedb.go
Discussion in:
https://github.com/erigontech/erigon/issues/13457
This PR brings back SafeNoSync from v2.60.10 to prevent DB from being congested and slowdown.
=> revert SafeNoSync

txnprovider/txpool/pool.go
The txpool does not broadcast remote transactions or send them to their peers. Steps to reproduce the bug:
1) The devnet contains 3 nodes: node1 is connected to node2 via P2P, and node2 is connected to node3 via P2P. 
2) Send a transaction to node3, 
3) It is added to node3 as a local transaction and broadcasted to node2. 
4) Node2 receives it as a remote transaction, adds it to its pool, but never broadcasts it to its peers.
Is this the expected behavior, or is it a bug?
If it is a bug, it seems we may have forgotten to promote transactions added to the pool (similar to how local transactions are handled in the AddLocalTxns function).
=> txpool: addRemoteTxs broadcast - missed some txs

cl/sentinel/sentinel.go, cmd/utils/flags.go
Caplin's sentinel opens UDP port controlled by flag `--caplin.discovery.port` we open it at `0.0.0.0` ignoring another flag `--caplin.discovery.addr` which is `127.0.0.1`. TCP port opened correctly with respect of `.addr`.
PR fixes default behavior.
=> Caplin: use sentinel default UDP address 0.0.0.0

turbo/execution/eth1/ethereum_execution.go
current header must never be purged because it cannot be part of a "bad" chain
=> Erigon 3: Do not purge currentHeader

turbo/execution/eth1/forkchoice.go
This makes logging at chain tip cleaner since at this point in the code `headHash == blockHash`.
=> Remove `headHash` from fork choice log

cmd/rpcdaemon/cli/config.go, contracts/backend.go, eth/backend.go, rpc/handler.go, rpc/subscription.go, turbo/jsonrpc/eth_api.go, txnprovider/shutter/pool.go
relates to https://github.com/erigontech/erigon/issues/13383
takes a chunk of changes out of bigger shutter PR https://github.com/erigontech/erigon/pull/13553 in which we collect data from various shutter smart contracts
context on this PR:
- smart contracts objects generated by `abigen` rely on `bind.ContractBackend` in order to be used
- we currently do not have an implementation of that interface in Erigon (apart from `SimulatedBackend` which is used in testing - inherited from Geth)
- in this PR im adding an implementation of `ContractBackend` which uses the `EthApi` jsonrpc object and directly calls it instead of going via http rpc and/or websocket (for log update subscriptions) - this is analogous to how we have `direct` and `remote` grpc clients for our grpc-based components
- ive …
=> contracts: add direct contract backend

core/state_transition.go, core/types/authorization_test.go
A recent [RLP related commit](https://github.com/erigontech/erigon/pull/12869/files#diff-ec3e5ec81bd7c4746ee5d895260767e2282f268684ffc0de73d4a7018975493c) created a uint256 encoding that assumes len = 32 for the passed in buffered byte array. However, this PR doesn't fix any inherent issues with [that approach](https://github.com/erigontech/erigon/pull/12869) itself. This PR fixes one issue found in `pectra_devnet_5` that creates a mismatched recovered signer address.
=> core: Fix signature mismatch issues due to authorization encoding

eth/stagedsync/exec3.go
After the root hash computation `flushAndCheckCommitmentV3` switches from handling the main happy flow, to handling the error flow when the root hash doesn't match what's in the header. 
In this PR, I am moving the handling of the unhappy flow to a separate function, so that the main body of `flushAndCheckCommitmentV3` can continue to handle the happy flow,
=> Handle wrong root hash unhappy flow separately

.github/workflows/qa-constrained-tip-tracking.yml
On Polygon the prebuilt db was built with --prune.mode==full, on Ethereum with --prune.mode==archive.
So we need to specify this mode when running the tests.
=> qa-tests: use explicit prune mode in constrained-tip-tracking test

erigon-lib/state/aggregator.go, erigon-lib/state/aggregator2.go, erigon-lib/state/aggregator_test.go, erigon-lib/state/domain.go, erigon-lib/state/domain_committed.go, erigon-lib/state/domain_shared.go, erigon-lib/state/history.go, erigon-lib/state/merge.go, turbo/app/snapshots_cmd.go
- respond to [this](https://github.com/erigontech/erigon/pull/13444#discussion_r1917638547) comment 
- benchmark results (pr [here](https://github.com/erigontech/erigon/pull/13602/files))
```
main
BenchmarkAggregator_BeginFilesRo/begin_files_ro-16 1490890 850.0 ns/op 3280 B/op 22 allocs/op
aggr12 branch
BenchmarkAggregator_BeginFilesRo/begin_files_ro-16 1688707 712.3 ns/op 3216 B/op 21 allocs/op
```
=> eliminate business logic from IndexRange

consensus/misc/eip1559.go, erigon-lib/chain/chain_config.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, turbo/jsonrpc/eth_block.go, turbo/jsonrpc/eth_system.go, turbo/stages/stageloop.go
Cherry pick #11992 "Add support to `eth_blobBaseFee`, `eth_baseFee` and EIP4844 support to `eth_feeHistory`" into `release/2.61` and also #13467 "Make secondsPerSlot available in chain config"
=> Add support to `eth_blobBaseFee`, `eth_baseFee` and EIP4844 support to `eth_feeHistory`

cl/clparams/config.go, cl/cltypes/beacon_block.go, cl/phase1/core/state/util.go, cl/transition/impl/eth2/operations.go
Fixes an issue where the `/eth/v1/config/spec` was returning an incorrect output.
```bash
curl -s 0.0.0.0:5052/eth/v1/config/spec | jq '.data | with_entries(select(.key | test("REQUEST_TYPE$")))'
{
"DEPOSIT_REQUEST_TYPE": "0x00",
"WITHDRAWAL_REQUEST_TYPE": "0x01",
"CONSOLIDATION_REQUEST_TYPE": "0x02"
}
```
=> caplin: Fix config type

eth/stagedsync/exec3.go
Exec latency checking is inconsistent for ethereum chains this fixes that by using  ModeForkValidation || ModeApplyingBlocks as the criteria for producing metrics.
`ModeApplyingBlocks` happens when we call `UpdateForkChoice` - that is when we should be calling UpdateBlockConsumerPreExecutionDelay and UpdateBlockConsumerPostExecutionDelay
`ModeForkValidation` happens when we call ValidateChain - we should be updating the above block consumer metrics here too for the following reasons:
* first ValidateChain is called => the block is valid and the extending fork hash is rememberred by the fork validator as per validateAndStorePayload - at this point the execution loop has been run with an in-mem db approach
* then UpdateForkChoice is called with hash==extendingForkHash from the previous …
=> changed exec metrics guard to use sync mode

.github/workflows/qa-rpc-integration-tests.yml, .github/workflows/scripts/run_rpc_tests.sh
This PR contains:
- new label of RPC-tests (new tests, integration tests runned in parallel)
- create exception list valid also for beta1
=> integration_test: Update qa integration test for beta1

erigon-lib/crypto/crypto.go
Fixes [CVE-2025-24883](https://nvd.nist.gov/vuln/detail/CVE-2025-24883)
See https://github.com/ethereum/go-ethereum/pull/31100
=> crypto: add IsOnCurve check

turbo/execution/eth1/block_building.go
Fixes an issue reported for `devnet-5` with trace as follows
```
[INFO] [01-29|21:33:12.026] Received GetPayloadV4                    payloadId=369
[EROR] [01-29|21:33:12.026] RPC method engine_getPayloadV4 crashed: runtime error: index out of range [0] with length 0
[service.go:223 panic.go:770 panic.go:114 block_building.go:223 execution_client.go:53 engine_server.go:475 engine_api_methods.go:74 value.go:596 value.go:380 service.go:228 handler.go:534 handler.go:484 handler.go:425 handler.go:245 handler.go:338 asm_amd64.s:1695]
```
=> execution: Fix request append out of range in block building

turbo/jsonrpc/corner_cases_support_test.go, turbo/jsonrpc/debug_api_test.go, turbo/jsonrpc/erigon_receipts_test.go, turbo/jsonrpc/eth_api_test.go, turbo/jsonrpc/eth_block_test.go, turbo/jsonrpc/eth_callMany_test.go, turbo/jsonrpc/eth_call_test.go, turbo/jsonrpc/eth_filters_test.go, turbo/jsonrpc/eth_mining_test.go, turbo/jsonrpc/eth_system_test.go, turbo/jsonrpc/send_transaction_test.go
Set default FeeCap value (1eth) for tests.
Looks like there is mistake in https://github.com/erigontech/erigon/pull/10636 
`checkTxFee` function expects FeeCap in Ether not in Wei. https://github.com/erigontech/erigon/blob/34714c0c25cc59587240ae7abc1c2758315254af/turbo/jsonrpc/send_transaction.go#L80
=> put reasonable feeCap value in tests

turbo/jsonrpc/net_api.go
Replace hardcoded value with actual network state check.
**The method now properly reflects network connectivity status by checking if the node can communicate with the network.**
=> fix: improve net_listening implementation

polygon/sync/execution_client.go, polygon/sync/service.go
a user on discord flagged the following issue (discord [link](https://discord.com/channels/687972960811745322/983710221308416010/1334851657355235358)): 
```
[INFO] [01-31|10:44:40.015] [sync] update fork choice done           in=807.13624ms
[INFO] [01-31|10:44:40.022] [sync] update fork choice                block=67365147 hash=0xb697ef9de67d61f300fda27367617ec270d9bcd15e9a7c73facdc253b6fc0273 age=3s
[EROR] [01-31|10:44:40.022] failed to update fork choice             latestValidHash=0x0000000000000000000000000000000000000000000000000000000000000000 err="fork choice update failure: status=5, validationErr=''"
[EROR] [01-31|10:44:40.038] runPostForkchoiceInBackground            error="[1/6 OtterSync] db closed"
[EROR] [01-31|10:44:43.029] polygon sync crashed - stopping node     err="pos …
```
=> polygon/sync: retry ufc on busy response

.github/workflows/scripts/run_rpc_tests.sh
The PR https://github.com/erigontech/erigon/pull/13617 fixed some important incompatibilities between Erigon RPC and other clients RPC as listed here: https://hive.pectra-devnet-5.ethpandaops.io/suite.html?suiteid=1738266984-51ae1a2f376e5de5e9ba68f034f80e32.json&suitename=rpc-compat
While we wait to change the tests in the suite, let's disable the ones that fail.
=> qa-tests: (temporarily) disable rpc tests that fail after PR #13617 

ChangeLog.md, turbo/jsonrpc/eth_call.go
seems we already support - but 1 check used "latest state reader"
=> `eth_estimateGas`: support historical blocks

eth/stagedsync/exec3.go, turbo/execution/eth1/forkchoice.go
Now that we are using Astrid by default it means that all of our block consumers for all chains (Ethereum/Gnosis/Polygon) use the same flow for execution - UpdateForkChoice.
This means we can simplify when/where we call `UpdateBlockConsumerPreExecutionDelay` and `UpdateBlockConsumerPostExecutionDelay`.
This should also resolve the inconsistencies that @mriccobene has seen between Polygon/Ethereum.
=> execution: fix and simplify block consumer exec delays

turbo/execution/eth1/ethereum_execution.go
```
[DBUG] [01-31|15:55:48.356] Inserted block                           hash=0x3ba1f6f721c32def207c318dc049e765eeb87d1e4b81c78a8e6574bb200057b9 number=7611267
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2a8 pc=0x1184f4f]
goroutine 270390026 [running]:
github.com/erigontech/erigon/core/types.(*Header).Hash(0x0)
github.com/erigontech/erigon/core/types/block.go:584 +0x2f
github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).unwindToCommonCanonical(0xc000c043c0, {0x34c19c0, 0xc1c1982780}, 0xc0862da2c8)
github.com/erigontech/erigon/turbo/execution/eth1/ethereum_execution.go:175 +0x425
github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).ValidateChain.func2({0x34c19 …
```
=> parent nil ptr fix

eth/stagedsync/stage_txlookup.go
it's valid txnum of genesis block
=> TxLookup stage: allow TxNum=0

cmd/rpcdaemon/cli/config.go, turbo/snapshotsync/snapshots.go
Fixes:  https://github.com/erigontech/erigon/issues/13663
If there is downloader we need to call DownloadComplete in the snapshot constructor so that users of the Ready flag don't hang waiting.
This fix assumes that the rpcdeamon never runs with a downloader
=> Dont wait for downoader if none

dashboards/erigon_custom_metrics/erigon_custom_metrics.internal.json
The erigon_custom_metrics dashboard got changed so the new version should overtake the currently stored one, which should in turn get archived in a compressed form
=> [automation] Backup of erigon_custom_metrics dashboard - 05 Feb 2025

turbo/jsonrpc/debug_api.go, turbo/jsonrpc/debug_api_test.go
See https://github.com/ethereum/execution-apis/blob/main/src/debug/getters.yaml#L39
This is ported mostly from `eth_getRawTransaction` implementation plus a test
=> Implement `debug_getRawTransaction`

turbo/engineapi/engine_server.go
As per updated specs, this check should preemptively return -32602 
See https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#engine_newpayloadv4
=> engineapi: Add request ascending order check

README.md, consensus/clique/clique.go, eth/stagedsync/stage_mining_exec.go
We encountered an issue with producing blocks in the devnet environment when the --dev.period flag is set to 0, which is its default value. The issue was caused by an infinite wait on a channel read in one of the goroutines inside the `StartMining` function.
Additionally, in this PR, I removed the unused `noempty` variable from the `stage_mining_exec.go` file. The logic remains unchanged—I only removed if blocks that were never executed.
=> Fixed clique consensus mining process

erigon-lib/commitment/commitment.go, erigon-lib/commitment/commitment_bench_test.go, erigon-lib/commitment/commitment_test.go, erigon-lib/commitment/hex_patricia_hashed.go, erigon-lib/commitment/hex_patricia_hashed_bench_test.go, erigon-lib/commitment/hex_patricia_hashed_fuzz_test.go, erigon-lib/commitment/hex_patricia_hashed_test.go, erigon-lib/commitment/patricia_state_mock_test.go, erigon-lib/state/domain_shared.go, erigon-lib/state/domain_shared_test.go
This reverts commit 1f87c1699c79b9f2a5870ee9c224abeb391bfa7d.
=> Revert #13509 "Commitment: do not use cell getter function to fold.."

erigon-lib/commitment/hex_patricia_hashed.go
fixes https://github.com/erigontech/erigon/issues/13739
I deactivated most of them, but:
- I didn't delete them, maybe @antonis19 you want to keep it, but demote to debug or trace log levels instead?
- there is another block of code apparently doing only logs, but I didn't remove it bc I'm not familiar with the code and it looks like only getters, but maybe it could have some side effect, I didn't dig deeper, maybe you want to confirm.
=> Deactivate printfs that are polluting logs on eth_getProof

turbo/jsonrpc/eth_receipts.go
Using the param instead of returned value. Fixes one more rpc-compat hive test
=> jsonrpc: Fix block not found err in `eth_getBlockReceipts`

erigon-lib/trie/proof.go, erigon-lib/trie/retain_list.go, erigon-lib/trie/retain_list_test.go, erigon-lib/types/accounts/account_proof.go, turbo/jsonrpc/eth_api.go, turbo/jsonrpc/eth_call.go, turbo/jsonrpc/eth_call_test.go
Should be able to handle inputs less than 32-bytes and output values in a compact string format to align with geth
=> trie, jsonrpc: Fix `eth_getProof` format

ChangeLog.md, polygon/bridge/service.go, polygon/bridge/service_test.go, polygon/sync/store.go, polygon/sync/sync.go
Last week my Amoy node deadlocked (logs and explanation at the end). It was due to an edge case in `handleBridgeOnBlocksInsertAheadOfTip` and calling `bridge.Synchronize`.
Coincidentally, the logic in `bridge.Synchronize` is no longer needed (it is actually useless, pretty much no-op) after it was superseded by the logic in `bridge.waitForScraper` which does its job but I never had the time to delete it. Additionally, calling `bridge.Synchronize` in the `Sync` component is not needed as we are covered by calling `store.Flush` anyway - it ensures all pending writes to both execution engine and the bridge have finished.
Now that I noticed it got us into a deadlock it is about time to remove it.
The logs for it are:
```
[DBUG] [02-04|01:42:47.088] [bridge] processing new blocks …
```
=> polygon/bridge: remove unnecessary synchronize logic

ethstats/ethstats.go
Fixes an issue on startaup:
```
2025-02-13 13:03:15.102  
[INFO] [02-13|09:03:15.101] head updated                             hash=0x67f34674738b118c66deac95137e9e4c0f47411aed142bda9b7a452537e29ee3 number=396 age=0 execution=3.025816ms mgas/s=0.00 average mgas/s=0.00 commit=696.106µs alloc=41.2MB sys=87.1MB
2025-02-13 13:03:18.152  
2025-02-13 13:03:18.152  
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2409c54]
2025-02-13 13:03:18.152  
goroutine 154 [running]:
2025-02-13 13:03:18.152  
github.com/erigontech/erigon/core/types.(*Block).Hash(...)
2025-02-13 13:03:18.152  
github.com/erigontech/erigon/core/types/block.go:1483
2025-02-13 13:03:18.152 …
```
=> ethstats: Fix nil ptr

erigon-lib/commitment/hex_patricia_hashed.go
We need to set those contexts because in the line `p.mounts[i].ctx = p.ctx[i]` of the function `unfoldRoot`
`p.mounts[i].ctx` becomes `nil`
=> Reset each context

erigon-lib/state/aggregator_bench_test.go
throughput benchmark
work = loopv value (more time spent on iteration, longer living rotx)
I didn't plot for goroutines < 2^16, since the value remains the same pretty much (no deterioration till 2^16 goroutines).
Tested on Apple M3 map (16 core).
`number of goroutines = *parallel*runtime.GOMAXPROCS(0)`
conclusion -- as **number of goroutines** starts to go above from 2^20 (1 million), perf starts to deteriorate. Specially beyond 2^21 (2 million rotxs), performance degrades significantly. 
even for loopv=10^7, same observation (above 2^21 goroutines, significant deterioration); same scenario for loopv=1.
The work done inside rotx is computational intensive, and not accessing db.
=> add benchmark for BeginFilesRo

turbo/jsonrpc/eth_block.go
Fixes incorrect patch for #12690
See: https://github.com/erigontech/erigon/issues/12690#issuecomment-2654978535
```
➜  curl --request POST \
-s --url http://127.0.0.1:8545/ \
--header 'Content-Type: application/json' \
--data '{
"method": "eth_getBlockByHash",
"params": [
"latest",
false
],
"id": 1,
"jsonrpc": "2.0"
}' | jq '.result.miner'
"0x0000000000000000000000000000000000000000"
➜  curl --request POST \
-s --url http://127.0.0.1:8545/ \
--header 'Content-Type: application/json' \
--data '{
"method": "eth_getBlockByNumber",
"params": [
"latest",
false
],
"id": 1,
"jsonrpc": "2.0"
}' | jq '.result.miner'
"0x0000000000000000000000000000000000000000"
```
=> rpcdaemon: Don't set miner

go.mod, go.sum
This fixes compilation with go 1.24 (see https://github.com/supranational/blst/releases/tag/v0.3.14)
=> deps: upgrade blst to v0.3.14

erigon-lib/kv/rawdbv3/txnum.go
- Fix Min -> Max in doc
- Fix return variable name bc it is confusing when it autocompletes (min function, but returns max?)
=> Fix misleading doc, return variable name

ethstats/ethstats.go
Fixes an issue on startaup:
```
2025-02-13 13:03:15.102
[INFO] [02-13|09:03:15.101] head updated                             hash=0x67f34674738b118c66deac95137e9e4c0f47411aed142bda9b7a452537e29ee3 number=396 age=0 execution=3.025816ms mgas/s=0.00 average mgas/s=0.00 commit=696.106µs alloc=41.2MB sys=87.1MB
2025-02-13 13:03:18.152
2025-02-13 13:03:18.152
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2409c54]
2025-02-13 13:03:18.152
goroutine 154 [running]:
2025-02-13 13:03:18.152
github.com/erigontech/erigon/core/types.(*Block).Hash(...)
2025-02-13 13:03:18.152
github.com/erigontech/erigon/core/types/block.go:1483
2025-02-13 13:03:18.152
github.com/erigontech/erigon/ethstats.(*Service).reportHistory(0xc …
```
=> ethstats: Fix nil ptr (#13794)

.github/workflows/qa-rpc-integration-tests.yml
Diable test that are failing due to:
- Pectra changes (eth_feeHistory)
- totalDifficulty removal (eth_getBlockByHash, eth_getBlockByNumber)
=> qa-tests: disable failing rpc tests from 2.61

erigon-lib/state/aggregator.go, erigon-lib/state/aggregator_files.go, erigon-lib/state/btree_index.go, erigon-lib/state/files_item.go, erigon-lib/state/inverted_index.go, erigon-lib/state/merge.go, erigon-lib/state/squeeze.go, eth/stagedsync/stage_snapshots.go, go.mod, go.sum, turbo/silkworm/silkworm.go, turbo/silkworm/snapshots_repository.go, turbo/snapshotsync/snapshots.go
Previously the Silkworm library was capable of reading Erigon 2 "blocks" snapshots (.seg and .idx). The code to provide them to Silkworm was a part of RoSnapshots. The old code is moved to be a part of silkworm.SnapshotsRepository, and migrated to the updated Silkworm C API.
The new code adds an ability to provide Erigon 3 "state" snapshots for reading by Silkworm during evmone execution mode (`--silkworm.exec`). It is based on the AggregatorRoTx.StaticFilesInRange method that was made public (with the related DTOs) to be accessible from the silkworm package.
BtIndex.DataHandle() added to expose the memory mapped file pointer to Silkworm (in the same way as Decompressor and recsplit.Index). A bunch of public methods added to filesItem via FilesItem interface to expose the snapshot file …
=> silkworm: add state snapshots

polygon/heimdall/snapshot_store.go
highlighted by https://github.com/erigontech/erigon/issues/13746
relates to https://github.com/erigontech/erigon/pull/13844#discussion_r1958403527
snapshot store should return last entity from snapshots if there are none in the db
=> polygon/heimdall: fix snapshot store last entity to check in snapshots too

erigon-lib/kv/kv_interface.go, erigon-lib/kv/mdbx/kv_mdbx.go, erigon-lib/metrics/gaugevec.go, erigon-lib/metrics/register.go
Currently the MDBX metrics recorded by `CollectMetrics()` are hardcoded , and work only for the main `chaindata`  MDBX instance. 
In this PR I add a label to the MDBX metrics to denote the DB instance for which the metrics are collected. 
This will enable me to tune the performance of node DB :  https://github.com/erigontech/erigon/issues/13550
=> Add DB label to MDBX metrics

.github/workflows/release.yml
Go 1.23
Base image: debian:12-slim
=> Bump builder and base docker images.

.github/workflows/qa-tip-tracking.yml
After a tip-tracking test the prebuilt db is left empty but Erigon is started to bring it back to the tip.
However if it starts immediately after another test the db remains almost empty; in this condition the rpc-integration tests fail.
In this PR we try to save and then restore the previous chaindata.
This is a tentative solution to https://github.com/erigontech/erigon-qa/issues/61
=> qa-tests: fix the cause of rpc tests failing intermittently

cl/phase1/core/state/ssz.go, cmd/devnet/blocks/fees.go
use a more straightforward return value
=> refactor: use a more straightforward return value

erigon-lib/kv/kv_interface.go, erigon-lib/kv/mdbx/kv_mdbx.go
- Moved the MDBX metric summaries initialization to `Open()` .
- Because the concurrent map is not statically typed, there was an issue when the Put was on key of type `string`  but Get was on a key of type `kv.Label`. Now I made both cases have type string.
=> Fix  mdbx summaries initialization

cl/aggregation/pool_impl.go, cl/aggregation/pool_test.go, cl/beacon/handler/block_production.go, cl/clparams/config.go, cl/cltypes/beacon_block.go, cl/cltypes/block_production.go, cl/cltypes/eth1_block.go, cl/cltypes/solid/attestation.go, cl/cltypes/solid/bitlist.go, cl/cltypes/solid/bitlist_test.go, cl/cltypes/solid/bitvector.go
- After Electra, the aggregation bits indicate the bit-maps that appear only in the committee bits, so merge them in a way similar to merge sort
- Fix bugs in BitList structure
- Remove the problematic SetVersion() function that leads to the empty attestation bug
=> Cherry-pick: Fix failure in block production (#13840)

core/vm/contracts.go, core/vm/instructions.go
Cherry pick https://github.com/ethereum/go-ethereum/pull/25183. See https://github.com/erigontech/security/issues/4
=> core/vm: return copy of input slice in identity precompile. don't deep copy return data slice upon call completion

.github/workflows/scripts/run_rpc_tests.sh
Temporarily removes the eth_estimateGas/test_14.json test; we need to add to the test case the error message that Erigon now generates  in this case after https://github.com/erigontech/erigon/pull/13903.
=> qa-tests: remove RPC test eth_estimateGas/test_14.json

.github/workflows/qa-tip-tracking-polygon.yml
must be:
`workflow timeout   >   TOTAL_TIME_SECONDS`
=> qa-tests: fix workflow timeout value for polygon tip tracking test

cl/phase1/forkchoice/fork_graph/fork_graph_disk.go, cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go, erigon-lib/common/dbg/experiments.go
Cherry pick PR #13893 into `release/3.0`
=> Caplin: removed reusable states in reorg (not really used anymore) Cherry-pick

cmd/utils/flags.go
Our mainnet validators suffered because the default caplin limits were too aggressive.
=> Caplin: less restrictive rate limiting

erigon-lib/diagnostics/txpool.go, turbo/app/support_cmd.go, txnprovider/txpool/fetch.go
Sending all incoming transactions to diagnostics in order to be streamed to the UI. Alongside with these transactions also sending hashes of duplicated transactions `knownTxns` it will show how many duplicates wandering around. This is the first implementation so in future object structure will be updated.
Closes #13400
=> diagnostics: stream all incoming transaction to diagnostics

cl/sentinel/gossip.go, ethdb/privateapi/ethbackend.go, txnprovider/txpool/pool.go
just to not worry about them in tests and small cli tools
=> less startup logs

cmd/utils/flags.go
Our mainnet validators suffered because the default caplin limits were too aggressive.
=> Caplin: less restrictive rate limiting (#13904)

cl/beacon/handler/committees.go, cl/beacon/handler/duties_attester.go
Prysm VC gave errors due to sync committee and attester duties max lookahead mismatching.
=> Caplin: Use common future lookahead for committee/attester duties.

erigon-lib/kv/mdbx/kv_mdbx.go, p2p/enode/nodedb.go
From observing real-time metrics it appears  that `db.Batch` does not yield better performance (i.e. shorter commit time, fewer dirty pages in memory, etc.) than `db.Update`  while using `SafeNoSync` flag, and flushing every n seconds.
=> Use db.Update instead of db.Batch in NodeDB

polygon/heimdall/snapshot_store.go
cherry-pick https://github.com/erigontech/erigon/pull/13845 patch into release/3.0
highlighted by https://github.com/erigontech/erigon/issues/13746 
relates to https://github.com/erigontech/erigon/pull/13844#discussion_r1958403527 snapshot store should return last entity from snapshots if there are none in the db
=> polygon/heimdall: fix snapshot store last entity to check in snapshots too (#13845)

txnprovider/shutter/decryption_keys_signature_data.go, txnprovider/shutter/decryption_keys_signature_data_test.go, txnprovider/shutter/eon_tracker.go, txnprovider/shutter/internal/testhelpers/eon_key_generation_mock_data.go, txnprovider/shutter/internal/testhelpers/identity_preimage_mock_data.go
found a few issues during testing:
- fix identity preimage hash ssz
- logging verbosity (was too chatty)
=> txnprovider/shutter: fixes to identity preimage hash ssz and logging

turbo/jsonrpc/eth_accounts.go
This was done earlier to align with a hive test, but there is no need for this check.
=> jsonrpc: remove index length <32 check from `eth_getStorageAt`

docs/programmers_guide/guide.md
I was reading through the [programmer guide](https://github.com/erigontech/erigon/blob/main/docs/programmers_guide/guide.md), as suggested here: https://docs.erigon.tech/about/contributing and it contained some dead link (which isn't so great ux wise).
This small PR fixes it.
=> docs: update links from programmer guide

.github/workflows/qa-tip-tracking.yml
On cancellation the guard condition to restore the chaindata will fail even if the step was successful.
So we now use always() to handle workflow cancellation
=> qa-tests: fix tip-tracking workflow under cancellation

go.mod, go.sum
Release v0.38.6 of mdbx-go : https://github.com/erigontech/mdbx-go/releases/tag/v0.38.6  includes bindings for `mdbx_env_set_syncbytes` and `mdbx_env_get_syncbytes` , which will allow a more comprehensive assessment of MDBX using `SafeNoSync` .
Related task: https://github.com/erigontech/erigon/issues/13550
=> Bump mdbx-go to v0.38.6 release

erigon-lib/go.mod, erigon-lib/go.sum, erigon-lib/kv/mdbx/kv_mdbx.go, erigon-lib/kv/mdbx/kv_mdbx_test.go, go.sum, p2p/enode/nodedb.go
Dirty data will be flushed to disk automatically when the size threshold of `syncBytes` is reached or when  the time period of `syncPeriod` is reached.
=> Add syncbytes threshold to NodeDB

erigon-lib/go.mod, erigon-lib/go.sum, erigon-lib/kv/kv_interface.go, erigon-lib/kv/mdbx/kv_mdbx.go, go.mod, go.sum
Task: https://github.com/erigontech/erigon/issues/13996
This allows us to track how much data has been committed but not yet flushed to disk when `mdbx.SafeNoSync` flag is used.
=> Add metric for unsynced bytes

erigon-lib/crypto/bn256/cloudflare/gfp12.go, erigon-lib/crypto/bn256/google/gfp12.go
Update the Erigon-Lib.
Fix a simple known bug in gfp12.MulScalar in the `erigon-lib/crypto`.
The problem has been patched in related repos.
* https://cs.opensource.google/go/x/crypto/+/8d7daa0c54b357f3071e11eaef7efc4e19a417e2
* https://github.com/cloudflare/bn256/pull/33
* https://github.com/ethereum/go-ethereum/pull/30974
=> Update the bn256 crypto lib.

p2p/sentry/sentry_grpc_server.go
Avoid creating temporal struct.
=> trackPeerStatistics reduced memory usage

eth/stagedsync/default_stages.go
when debug syncstage process check this comment hint:
=> eth/stagedsync: Fix UploaderPipelineStages function comment format

cmd/state/exec3/historical_trace_worker.go, erigon-lib/kv/kv_interface.go, erigon-lib/kv/membatchwithdb/memory_mutation.go, erigon-lib/kv/remotedb/kv_remote.go, erigon-lib/kv/temporal/kv_temporal.go, erigon-lib/state/aggregator.go, erigon-lib/state/domain_shared.go, erigon-lib/state/squeeze.go, eth/stagedsync/stage_custom_trace.go, turbo/jsonrpc/eth_call.go
discussed in https://github.com/erigontech/erigon/issues/13261
=> "less direct agg use": remove `sd.aggTx.d[kv.CommitmentDomain].Files()` add API `Files(domain)`

core/vm/interpreter.go
This is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: using slices.Contains to simplify the code

erigon-lib/state/domain_shared.go, erigon-lib/state/domain_stream.go
push-down `IteratePrefix` method logic from SD to DomainRoTx
step towards reducing private field use by SD
=> sd: push-down `IteratePrefix` method logic

turbo/logging/logging.go
close:https://github.com/erigontech/erigon/issues/14041
current log flag Priority: LogConsoleVerbosityFlag (if explicitly set) > LogVerbosityFlag (if explicitly set) > default
after change:
=> fix: verbosity debug level not works

ChangeLog.md
Copy the changelog bit of PR #14069 into `main`
=> Add v3.0.0-rc2 changelog

consensus/misc/eip6110.go
Cherry pick PR #14066 into `release/2.61`. 
See
https://sepolia.etherscan.io/tx/0xaebb84d80e12682fd1eafc494081cc8207abd26af3feb75c65b3c398561f2328#eventlog
=> Pectra: fix bad deposit contract deposit unmarshalling

cmd/utils/flags.go
Start erigon with something like `--chain=xxx`
BEFORE:
```
[EROR] [03-05|16:11:59.146] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[main.go:46 panic.go:787 panic.go:262 signal_unix.go:925 flags.go:1722 flags.go:1942 node.go:121 main.go:96 make_app.go:71 command.go:276 app.go:333 app.go:307 main.go:51 proc.go:283 asm_amd64.s:1700]"
```
AFTER:
```
Fatal: ChainDB name is not recognized: xxx
```
=> Avoid nil pointer when chain is unknown

core/types/blob_tx_wrapper.go, turbo/engineapi/engine_server_test.go
Restores `MarshalBinary` contents from before https://github.com/erigontech/erigon/pull/13975
The full marshal of wrapped blobs are only used in a test, hence moved the logic to `MarshalBinaryWrapped`. This does make this different from other transaction types, as it only returns the marshalled bytes of the internal
Fixes an issue in which wrapped blobs were getting included to the returned payload.
=> types: Move wrapped blob txn marshal to different func

turbo/jsonrpc/eth_receipts.go
can reproduce on amoy/bor, `release/3.0` and `main`, by:
```
curl 'http://localhost:8545' -H 'Content-Type: application/json' --data '{"id": 1, "jsonrpc": "2.0", "method": "eth_getLogs", "params": [ {"fromBlock": "14300401","toBlock": "14300501"} ]}'
```
```
`EROR[03-06|03:25:55.613] RPC method eth_getLogs crashed: runtime error: index out of range [0] with length 0
[service.go:223 panic.go:785 panic.go:115 bor_receipts_generator.go:86 eth_receipts.go:306 eth_receipts.go:143 value.go:581 value.go:365 service.go:228 handler.go:534 handler.go:484 handler.go:425 handler.go:245 handler.go:338 asm_amd64.s:1700]` 
```
=> nil ptr in gen bor logs

txnprovider/txpool/txpoolcfg/txpoolcfg.go
This pull request includes updates to the `DiscardReason` function to handle additional discard reasons for transactions. The most important changes include adding new cases for different types of transaction validation errors.
=> txpool: add more cases to return err instead of panicking on invalid Txn cases

txnprovider/txpool/txpoolcfg/txpoolcfg.go
…Txn cases (#14093)
This pull request includes updates to the `DiscardReason` function to handle additional discard reasons for transactions. The most important changes include adding new cases for different types of transaction validation errors.
Cherry-Pick #14093
=> txpool: add more cases to return err instead of panicking on invalid Txn cases (#14093)

turbo/jsonrpc/eth_accounts.go
I don't think anybody cares about the returned error. Silencing for now, may remove in the future. There was little value in keeping it strict
=>  jsonrpc: Lenient on param check for eth_getStorageAt 

.github/workflows/qa-tip-tracking.yml
Avoid copying pre-build db on tip-tracking test on test runner for Erigon v2
=> qa-tests: avoid running out of disk on runner for Erigon v2

cmd/integration/commands/stages.go
Fix the error handling in the LogStats callback function in stages.go. Previously, the function was unconditionally returning an error even when FindBlockNum succeeded, resulting in confusing error messages like findBlockNum(5046875000) fails: . Now the function only returns an error when FindBlockNum actually fails.
This improves error reporting and prevents misleading error messages when working with transaction numbers and block lookups.
=> [cmd/integration] fix: correct error handling in LogStats callback

docs/merry-go-round-sync.md
Noticed and fixed a couple of grammar issues:  
- "each ticks starts" → "each tick starts" (each requires a singular noun)  
- "the mining of certain block" → "the mining of a certain block" (a is needed before a singular countable noun)
=> docs: Fix grammar mistakes

docs/programmers_guide/db_faq.md
Hi! The link to the MDBX documentation in `db_faq.md` was pointing to a dead domain (`https://libmdbx.website.yandexcloud.net`), which no longer resolves.
=> docs: update dead link in `db_faq.md`

turbo/app/init_cmd.go
close:https://github.com/erigontech/erigon/issues/14142
run:
```
init
--datadir=erigon-data
--chain=xxx
/tmp/genesis/genesis.json
```
logs:
```
[INFO] [03-12|17:25:24.120] logging to file system                   log dir=erigon-data/logs file prefix=erigon log level=info json=false
[INFO] [03-12|17:25:36.500] Starting Erigon on                       devnet=xxx
[WARN] [03-12|17:25:36.504] No snapshot hashes for chain             chain=xxx
[INFO] [03-12|17:25:36.519] Maximum peer count                       total=32
[INFO] [03-12|17:25:36.520] starting HTTP APIs                       port=8545 APIs=eth,erigon,engine
```
=> feat: add --chain flag for init command

eth/gasprice/feehistory.go, eth/gasprice/gasprice.go, eth/integrity/receipts_no_duplicates.go, turbo/jsonrpc/eth_receipts.go, turbo/jsonrpc/eth_system.go, turbo/jsonrpc/receipts/receipts_generator.go
Currently, a significant amount of time is spent on re-executing transactions. However, in reality, only the gasused by the transaction is needed, which can be obtained through the `kv.ReceiptDomain`
Reproduce
```
curl --location --request POST 'localhost:8545' --header 'content-type: application/json' --data-raw '[
{ "method": "eth_feeHistory", "params": ["0x100", "0x2CA3220", [25,75]], "id": 1, "jsonrpc": "2.0" }
]'
```
Following this optimization, the latency has been dramatically reduced from minutes to milliseconds.
=> feehistory.go: optimize the high latency of eth_feeHistory.

turbo/execution/eth1/ethereum_execution.go, turbo/execution/eth1/forkchoice.go
The current implementation calculates a cumulative average of all measurements, which becomes less meaningful over time due to historical bias.
Using a 1 hour EMA allows for a more live view of performance as it gives significantly more weight to recent measurements, while smoothing out extreme fluctuations.
=> Use 1hr EMA for average mgas/sec

consensus/aura/aura.go, consensus/clique/clique.go
found in https://github.com/erigontech/erigon/pull/13983
we aren't closing consensus db for AuRa and Clique 
this PR adds this as part of Engine.Close (consensus engine is the owner of the consensus db so makes sense to do it there; also Bor already does it there)
=> consensus: engine to close consensus db for AuRa and Clique

erigon-lib/chain/snapcfg/util.go, erigon-lib/go.mod, erigon-lib/go.sum, go.mod, go.sum
We want erigon 3.0 to use branch `release/3.0` of [erigon-snapshot](https://github.com/erigontech/erigon-snapshot). 
This is a prerequisite change. It depends on https://github.com/erigontech/erigon-snapshot/pull/469.
=> Explicit DefaultSnapshotGitBranch

erigon-lib/log/v3/handler.go, erigon-lib/log/v3/log_test.go, erigon-lib/log/v3/logger.go
Moved the stack.Caller to a func on the Record. Calling the stack multiple times every log gets expensive even when you are logging under the level defined in config. This is because the call stack will get created every time the Log() func runs on the handlers, even if the call stack is not being used.
This issue came up in CDK Erigon saying the log was performing poorly in a pprof benchmark.
Issue 1: [1637](https://github.com/0xPolygonHermez/cdk-erigon/issues/1637)
Issue 2: [1770](https://github.com/0xPolygonHermez/cdk-erigon/issues/1770)
After running a bechmark pprof after this changeset, the call stack has gone from the flame graph and improves performance.
[1f4cca638da71ffec4490bf21fa84004984b3546](https://github.com/gateway-fm/log/commit/1f4cca638da71ffec4490bf21fa84004984b3546)
=> improvement(log): add call stack to func on the record

cmd/devnet/requests/transaction.go, contracts/direct_backend.go, contracts/jsonrpc_backend.go
used in https://github.com/erigontech/erigon/pull/13983 
taking a cohesive unit of logic out of the bigger PR for ease of reviewing
a jsonrpc based contracts backend is something that will be useful for future use cases, hence putting in the `contracts` pkg
=> contracts: add jsonrpc backend

cl/phase1/execution_client/execution_client_rpc.go, erigon-lib/go.mod, erigon-lib/go.sum, erigon-lib/jwt/http_round_tripper.go, turbo/engineapi/engine_api_jsonrpc_client.go, turbo/engineapi/engine_types/jsonrpc.go
used in https://github.com/erigontech/erigon/pull/13983
taking a cohesive unit of logic out of the bigger PR for ease of reviewing
adds a json rpc client for interacting with the engine api
the gist is:
- we have an integration test which starts up Erigon as EL only
- we drive Erigon with a MockCl
- in order to be able to drive Erigon we need to access it's engine api json rpc (for this we need an engine api client)
- analogous to that, we need a json rpc api client for the rpcdaemon publicly exposed apis (e.g. the "eth_" namespace, "debug_", etc.)
- this is a black box test where we feed Erigon inputs via the public api surface and check the end result again via the public api surface
=> engineapi: add jsonrpc client

eth/backend.go, eth/stagedsync/exec3_serial.go, turbo/engineapi/engine_helpers/fork_validator.go, turbo/execution/eth1/ethereum_execution.go, turbo/execution/eth1/forkchoice.go, turbo/shards/events.go, turbo/stages/mock/mock_sentry.go
found in https://github.com/erigontech/erigon/pull/13983
we weren't getting any new log notifications (rpc log subscriptions api) when the EL was going via the `e.forkValidator.FlushExtendingFork` code path which does an in-memory flush of the previously cached execution of `EthereumExecutionModule.ValidateChain`
=> execution: fix missing log notifications when flushing extending fork

cl/phase1/stages/forward_sync.go, cl/phase1/stages/stage_history_download.go
- Removed logging of println around the code
- Made better and more readable loggings of downloading history
- Filtered out bad logs in `ForwardSync`
=> Cherry-Pick: More user-friendly logging (#14226)

RELEASE_INSTRUCTIONS.md, cmd/erigon/main.go, erigon-lib/chain/snapcfg/util.go, erigon-lib/version/version.go, params/version.go
Rationale: `DefaultSnapshotGitBranch` should be updated alongside the version when a release branch is forked.
=> Move DefaultSnapshotGitBranch into version.go

.github/workflows/qa-clean-exit-snapshot-downloading.yml, .github/workflows/qa-snap-download.yml, .github/workflows/qa-sync-from-scratch-minimal-node.yml, .github/workflows/qa-sync-from-scratch.yml, .github/workflows/qa-sync-with-externalcl.yml
Require that tests only run on qa-labeled runners
=> qa-tests/dispatch test wf to qa runners 3.0

README.md
The link to DEV_CHAIN.md in README.md was pointing to the root directory, but the file is located in the `docs` subdirectory.
This commit updates the link to point to the correct location:
- From: `[DEV_CHAIN](/DEV_CHAIN.md)`
- To:   `[DEV_CHAIN](/docs/DEV_CHAIN.md)`
=> fix(docs): correct broken link in README.md

tests/bor/mining_test.go
example failure: https://github.com/erigontech/erigon/actions/runs/13968954264/job/39105830886
```
Time to execute 5000 txs: 12.984522584s
--- FAIL: TestMiningBenchmark (13.41s)
testing.go:1232: TempDir RemoveAll cleanup: unlinkat /var/folders/bz/h4njq8yd7td8qk42rt_9f0p00000gn/T/TestMiningBenchmark3328505942/001: directory not empty
FAIL
FAIL	github.com/erigontech/erigon/tests/bor	13.965s
```
=> tests/bor: attempt to fix flakey TestMiningBenchmark integration test

txnprovider/shutter/decryption_keys_listener.go
closes https://github.com/erigontech/erigon/issues/13379
closes https://github.com/erigontech/erigon/issues/13380
not needed, go-libp2p-pubsub manages the peers well enough with our current approach of connecting to boot nodes
peers are quickly populated to up to 7 on startup and are maintained as per libp2p pubsub spec
=> txnprovider/shutter: remove libp2p todos as they are not needed

txnprovider/txpool/pool_test.go
Added a benchmark test `BenchmarkProcessRemoteTxns` to measure the performance of the transaction pool when processing remote transactions. The benchmark:
- Creates 100 test accounts with 1 ETH balance
- Processes transactions from different senders with varying nonces
- Measures processing time, memory allocations, and number of allocations
- Processing time: ~3.1-3.2 microseconds per transaction
- Memory usage: ~4.7-4.8 KB per transaction
- Allocations: 43-45 allocations per transaction
=> Remote txns benchmark

core/test/marked_appendable_test.go, core/test/unmarked_appendable_test.go, erigon-lib/state/appendable.go, erigon-lib/state/appendable_interfaces.go, erigon-lib/state/proto_appendable.go
- MarkedTxI is consolidated "temporal" interface using `Get()`
- can use DebugFiles() or DebugDb() to get fine-grained api which can query at db level (`GetDb`) or files level (`GetFromFiles` etc.)
=> debug api for appendables

txnprovider/txpool/pool_txn_parser.go
We need to skip the subtype byte
=> Fix `eth_sendRawTransaction` for AA transactions

turbo/jsonrpc/receipts/receipts_generator.go
- Latency impact: no impact. But 1 block executed once (even if multiple parallel requests) - means less CPU, means less chance to over-load server (what will increase latency).
- Throughput impact on "many parallel requests of same block" case (most of requests hit cache): benchmarks don't show throughput difference
=> receipts gen: dedup parallel re-exec of same block

erigon-lib/commitment/commitment.go, erigon-lib/commitment/commitment_bench_test.go, erigon-lib/commitment/commitment_test.go, erigon-lib/commitment/hex_patricia_hashed.go, erigon-lib/commitment/hex_patricia_hashed_test.go
part of #13884 
So we had etl inside branchencoder which we used to sort commitment updates long ago and then ended up not filling this one so it was NOOP code. 
also removed duplicated import
=> `commitment`: remove useless collector from `BranchEncoder`

turbo/execution/eth1/forkchoice.go
ErrBehindCommitment is wrapped with extra info: "TxNums index is at block %d and behind commitment %d"
would be helpful to see that to figure out Astrid "validationErr='domain ahead of blocks'" which happens sometimes after "rm -rf chaindata && polygon-bridge && heimdall".
current theory is that this could happen when domains is ahead of blocks with more than 5,000 blocks because on startup when we call executionModule.CurrentHeader we insert N+1, N+2, ... -> but we limit how much we insert (using LoopBlockLimit which is 5,000 blocks) before we call UpdateForkChoice on the batch
=> execution: debug log for ufc domain ahead of blocks err

.github/workflows/qa-rpc-integration-tests-polygon.yml, .github/workflows/scripts/run_rpc_tests_polygon.sh
Thanks to https://github.com/erigontech/rpc-tests/pull/347 we can now run an initial RPC test suite against
=> qa-tests: add rpc-integration tests for Polygon

turbo/engineapi/engine_server.go
The [specs](https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#engine_newpayloadv4) don't explicitly mention it tho
=> engineapi: Add requests nil check

core/state_transition.go
To avoid having to do the compute expensive `RecoverSigner` if gas is low.
Verified authorities are not needed for intrinsic gas check
=> core: move gas check in state transition to before auths check

cmd/rpctest/rpctest/bench_ethgetlogs.go
optimize `go run ./cmd/rpctest invariantsEthGetLogs` to not check same address twice in same block
on bor-mainnet it gives ~100x
=> rpctest invariantsEthGetLogs: speedup by checking each addr only once in each block

erigon-lib/go.mod, erigon-lib/go.sum, go.mod, go.sum
Downgrade of the gopsutils dependency due to a regression introduced in version v4.24.9.
After upgrading to gopsutils v4.24.9, we encountered issues detailed in [Erigon Issue #14415](https://github.com/erigontech/erigon/issues/14415). The problem appears to be introduced specifically in that release.
To maintain stability and avoid the regression, we are reverting gopsutils to the last known working version until a fix is introduced upstream.
=> Downgrade gopsutils version

.github/workflows/release.yml
Now the release workflow is only used for Erigon 3, so the test job will take less than 12 hours.
Taking into account the time needed to find free test runners, we can reduce the workflow timeout from 5 days to 2 days.
Implement https://github.com/erigontech/erigon-qa/issues/77
=> qa-tests: decrease release process timeout

cmd/state/exec3/state.go, core/state_transition.go
- Move AA execution to its own function to make it easier to read the primary branch of execution
- Removed duplication in validating auths in StateTransition
=> Cleaner AA execution code

turbo/engineapi/engine_server.go
The [specs](https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#engine_newpayloadv4) don't explicitly mention it tho
Cherry-pick #14421
=> engineapi: Add requests nil check (#14421)

.github/workflows/kurtosis/fast_lifecycle.io
Replaced a broken URL that returned 404 (som/kurtosis_lifecycle) with the correct path to main branch.
This ensures the workflow can load validator-lifecycle-test-v3.io properly.
=> Fix 404 link to validator lifecycle test file

txnprovider/txpool/pool.go
Should check sender is a previously pending authority, before adding the authorities to `p.auth`
=> txpool: Fix same sender-authority invalidation

core/test/marked_appendable_test.go, core/test/unmarked_appendable_test.go, erigon-lib/state/appendable_extras/registry.go, erigon-lib/state/appendable_extras/snap_config.go, erigon-lib/state/appendable_extras/snap_schema.go, erigon-lib/state/appendable_extras/snap_schema_test.go, erigon-lib/state/history.go, erigon-lib/state/simple_index_builder.go, erigon-lib/state/snap_repo.go, erigon-lib/state/snap_repo_config_test.go, erigon-lib/state/snap_repo_test.go
- freezing range tests: given snapshotConfig (with or without preverified files), find the output freezing ranges for which snapshots should be build
- SnapshotRepo tests (`snap_repo_test.go`) -- openfolder, integrate dirty files, close files after root num
- pending: merge files test.
=> tests for snap_repo and freezing ranges

polygon/bridge/reader.go
when doing rpc requests - I see many:
```
DBUG[04-08|22:06:46.266] [bridge] events for block                block=70070560 start=3051918 end=3051918
DBUG[04-08|22:06:46.268] [bridge] events for block                block=70070560 start=3051918 end=3051918
DBUG[04-08|22:06:46.268] [bridge] events for block                block=70070560 start=3051918 end=3051918
```
=> rpc: spam debug logs about events

core/types/block.go, core/types/block_test.go
There are scenarios where we copy an immutable header, apply changes to it, then calculate the new hash, but because the cached value is also copied over in `CopyHeader()`, then we end up calculating a stale hash.
This could happen due to the modifications in `NewBlock()` which invalidate the copied over cached hash. 
Likewise `*Block.WithSeal()` makes a mutable header immutable, however it doesn't ensure to refresh the cached hash.
These scenarios are covered in this PR by refreshing the cached header hash.
=> Invalidate potentially stale header hash

core/state_transition.go, turbo/privateapi/ethbackend.go
Notice that succesfull pre-charging the entire transaction gas limit is part of the transaction validity condition.
Also, as this empties the gas pool, it is not clear how to re-charge the gas for individual frames in that scenario. I assume only one of the gas subtractions can be kept, while the other should be discarded.
=> Provide 'totalGasLimit' to the 'ValidateAATransaction' gas pool; comment out sub gas

core/types/block.go
geth doesn't
e2 doesn't 
see also: https://github.com/erigontech/erigon/pull/14485#issuecomment-2785067138
=> CopyHeader: don't copy hash

cmd/observer/observer/diplomat.go, core/vm/memory_table.go, eth/tracers/js/goja.go, polygon/bridge/snapshot_store.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
=> refactor: use the built-in max to simplify the code

.github/workflows/qa-sync-from-scratch-minimal-node.yml
The execution time depends on the distance between the height of the snapshots and the height of the tip and sometimes 5 hours of testing were not enough
Implement https://github.com/erigontech/erigon-qa/issues/86
=> qa-tests: increase sync-from-scratch (minimal node) test timeout

core/types/eip7685_requests.go, core/types/requests_test.go
Pro:
Follows the [EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7685.md#block-header) to the letter 
Con:
In case empty requests pass through, the hash check would let it! (But it would not unless code is changed poorly)
=> core/types: Filter empty requests before hashing

erigon-lib/kv/kvcache/cache.go, erigon-lib/kv/kvcache/cache_test.go
- Added more logs to the `Coherent` cache implementation in the `erigon-lib/kv/kvcache/cache.go`
- Added a goroutine dump mechanism in the test suite
=> Added more logs

erigon-lib/state/aggregator.go
https://github.com/erigontech/erigon/issues/14515
FilesInRange return visibleFiles which are managed by aggRoTx created at start of mergeLoopStep.
MergeFiles don't need to closed (except when aggTx.mergeFiles return err != nil)
=> remove unsafe closing of subsumed files in mergeLoopStep

eth/tracers/debug/tracer.go, turbo/stages/mock/mock_sentry.go
this has helped me quite a lot with debugging failing blockchain tests for EOF (e.g. helps with gas mismatches and state root mismatches)
- adds an env var which MockSentry reads to start with a full debug tracer which write all of the newly added tracing hooks to json files in a user specified output directory 
- adds an env var which MockSentry reads for logging level
=> mock: mock sentry ability to use debug tracer and debug logs via env var

turbo/jsonrpc/trace_adhoc.go, turbo/jsonrpc/trace_filtering.go
- Prevent all transactions being run through state sync transaction branch
- Set correct block number for bridge reader
(cherry picked from commit fcd40723220ca9e5574004462777db2693737533)
=> Fix `trace_transaction` for Polygon chains (#14470)

.github/workflows/qa-rpc-integration-tests.yml
Due to a change in the major version of mdbx on main branch we need to use 2 pre-built db, one for main branch tests and one for release/3.x tests
=> qa-tests: fix rpc-integration tests

.github/workflows/qa-rpc-integration-tests.yml
Due to the recent removal of Aura fields from erigon_getHeaderByHash and erigon_getHeaderByNumber we need to use a new rpc-tests version.
=> qa-tests: use a new branch of rpc-tests where aura fields have been removed.

cl/beacon/handler/events.go
Fix for:
```
curl localhost:3500/eth/v1/events?topics=block,finalized_checkpoint
```
`invalid Topic: block,finalized_checkpoint`
According to https://discord.com/channels/687972960811745322/1359671377392566352
=> caplin: fix parsing topics

params/version.go
Padded 2 decimals is not desirable for minor version
=> params: Use no padding in minor version

cl/beacon/handler/events.go
Fix for:
```
curl localhost:3500/eth/v1/events?topics=block,finalized_checkpoint
```
`invalid Topic: block,finalized_checkpoint`
According to
https://discord.com/channels/687972960811745322/1359671377392566352
=> Cherry-Pick: caplin: fix parsing topics (#14543)

erigon-lib/state/appendable_extras/snap_config.go, erigon-lib/state/appendable_extras/snap_schema.go, erigon-lib/state/appendable_extras/snap_schema_test.go, erigon-lib/state/files_item.go, erigon-lib/state/proto_appendable.go, erigon-lib/state/snap_repo.go, erigon-lib/state/snap_repo_test.go
- remove fileCompression from btindex, as it's property of seg file and not btindex
- no need to take AccessorExtension as input from user
- `VisibleFile` interfcae to expose some minimal information outside erigon-lib/state (e.g [pull#14601](https://github.com/erigontech/erigon/pull/14601/files))
=> preparing snap_repo for use outside erigon-lib/state

.github/workflows/qa-tip-tracking-polygon.yml
We are trying to use an archive node for polygon so that we can do rpc tests on historical data. 
But the archive node is bigger. It is possible to better manage the backup of the pre-built db as we did with the Ethereum mainnet i.e. avoid the complete backup of the pre-built db and only backup/restore the chaindata
=> qa-tests: polygon tip-tracking with chaindata backup/restore

.github/workflows/qa-tip-tracking-polygon.yml
We are trying to use an archive node for polygon so that we can do rpc tests on historical data.
But the archive node is bigger. It is possible to better manage the backup of the pre-built db as we did with the Ethereum mainnet i.e. avoid the complete backup of the pre-built db and only backup/restore the chaindata
=> qa-tests: polygon tip-tracking with chaindata backup/restore (v3)

eth/stagedsync/stage_custom_trace.go, turbo/jsonrpc/eth_receipts.go, turbo/jsonrpc/receipts/bor_receipts_generator.go
Workaround to support state sync events in `eth_getLogs` and correct log indices in receipts. Requires re-generation of receipts domain (using `stage_custom_trace`).
=> Support state sync events in `eth_getLogs`, set correct log indices

erigon-lib/state/aggregator.go, eth/stagedsync/exec3.go, eth/stagedsync/stage_execute.go, turbo/app/snapshots_cmd.go
non-chain-tip: greedy prune
chain-tip: no greedy prune (because we need start processing new blocks ASAP)
=> no greedy prune of commitment hist on chain-tip

erigon-lib/recsplit/eliasfano32/elias_fano.go, erigon-lib/recsplit/eliasfano32/elias_fano_test.go, erigon-lib/state/inverted_index.go
`seekInFiles` is in top of heap alloc_objects profiling 
```
BenchmarkRead/read.seek  	 9455366	       121.3 ns/op
BenchmarkRead/reset.seek 	15614156	        77.01 ns/op
```
=> historical re-exec: re-used EliasFano object

erigon-lib/downloader/downloadercfg/downloadercfg.go
I did set it high in E3 as an experiment when played with webseeds. But we don't need it.
=> downloader: same NetworkChunkSize as in Erigon2

erigon-lib/kv/mdbx/kv_mdbx.go
During the investigation of the issue: https://github.com/erigontech/erigon/issues/14638
=> fix: mdbx.Coalesce is deprecated: always turned on since v0.12, deprecated since v0.13

eth/tracers/debug/tracer.go, eth/tracers/internal/tracetest/prestate_test.go, turbo/stages/mock/mock_sentry.go
- adds option to wrap the debug tracer around another tracer (helped with debugging prestate tracer tests in EOF branch)
- fixes evm memory and stack data recording (with options to enable/disable)
- fixes incorrect error message recording 
- fixes balance and gas change reason recording
=> tracers/debug: enchance debug tracer

cmd/downloader/main.go, erigon-lib/downloader/downloader.go, eth/backend.go
See https://github.com/erigontech/erigon/issues/14637.
I've exposed it to the default serve mux which I use for debugging with GOPPROF=http.
Should it be exposed to any other debug/HTTP endpoints?
=> Expose downloader torrent client status to HTTP

erigon-lib/downloader/downloadercfg/downloadercfg.go
pick: https://github.com/erigontech/erigon/pull/14585
Reason: it fixing Bittorrent p2p peers issue
=> [3.0 pick] downloader: same NetworkChunkSize as in Erigon2

cmd/utils/flags.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, txnprovider/shutter/block_building_integration_test.go, txnprovider/shutter/decryption_keys_listener.go, txnprovider/shutter/decryption_keys_processor.go, txnprovider/shutter/decryption_keys_validator.go, txnprovider/shutter/decryption_keys_validator_test.go, txnprovider/shutter/encrypted_txns_pool.go, txnprovider/shutter/eon_tracker.go, txnprovider/shutter/pool.go, txnprovider/shutter/shuttercfg/config.go
reason: `ethconfig` package must be `light-weight` (must not import big packages with many complex dependencies). 
So, to achieve it - config objects must live in own packages `downloadercfg`, `txpoolcfg`, etc...
Otherwise: easy to face cyclic-imports
=> shutter: move cfg to dedicated `shuttercfg` package

rpc/jsonrpc/daemon.go, rpc/jsonrpc/internal_api.go
This is a 2-in-1 PR proposal based on some recurring code snipet I've been keeping in private branches, so I'd like to propose:
1 - Adding and `internal_` JSONRPC namespace
Reserve an `internal_` JSONRPC namespace to attach internal, not supported, Erigon-only, "hacky" tools to quickly get info from a node.
It would have similar purpose to `integration` and `hack` binaries, but in a RPC form and with the following differences:
- Adding some quick and dirty feature to integration for example requires adding a lot of boilerplate code for setting up CLI args, open mdbx, open snapshots, etc., while adding a new JSON is more direct, usually the BaseImpl already gives you the node DB ready to use (counterpoint would be integration binary could provide a better boilerplate)
- `integration` and …
=> Add internal_ namespace + internal_getTxNumInfo method

.github/workflows/qa-rpc-integration-tests.yml
1) execute only on ready-for-review PRs; 
2) protect the pre-built db backing up and restoring the chaindata; 
3) check infrastructure failure
Implement https://github.com/erigontech/erigon-qa/issues/99
=> qa-tests: repair rpc-integration tests 

Makefile, tools.go
https://github.com/erigontech/erigon/pull/10783 has added a new `//go:generate stringer` directive for code gen - this PR adds a `make stringer` cmd and also adds `stringer` to `make gen` for easy code re-gen
=> make: add make stringer

README.md
Updates the Erigon Blog URL from https://erigon.substack.com to https://erigon.tech/news in the README.md file.
This change reflects the migration of the Erigon blog from Substack to their own domain.
=> Update Erigon Blog URL in README.md

.github/workflows/test-hive-eest.yml
Temporarily increase failure threshold. Failures because of mismatch in error mappings or sequence. Some of these are nice to have but not urgent:
https://github.com/ethereum/execution-spec-tests/pull/1416
=> workflows: increase hive eest threshold temporarily

.github/workflows/qa-sync-test-bisection-tool.yml
The default timeout is 2 days. This PR increases the timeout to 5 days.
=> qa-tests: increase timeout of the sync-from-scratch based bisection tool

core/state/rw_v3.go, erigon-lib/kv/kv_interface.go, erigon-lib/kv/membatchwithdb/memory_mutation.go, erigon-lib/kv/remotedb/kv_remote.go, erigon-lib/kv/temporal/kv_temporal.go, erigon-lib/state/domain_shared.go, erigon-lib/state/domain_shared_test.go, erigon-lib/state/domain_stream.go, erigon-lib/state/kv_temporal_copy_test.go
adding a new `HasPrefix(domain, prefix) (firstKey []byte, ok bool, err error)` api to `TemporalGetter`
this will be used later on to implement eip-7610 `HasStorage` check in the various StateReader implementations that we have
in a subsequent PR I will also add an implementation for `HasPrefix` for the remote kv
note: the reason for `firstKey` return is that in `ReaderParallelV3` we record the read list so that will be used there to record a touch of the first storage slot (this is a bit of a question mark - not sure if we have to do it or not yet - waiting for response from Alex - but either way the API is probably most useful like this)
=> kv: add HasPrefix to TemporalTx and SharedDomains

.github/workflows/test-hive-eest.yml
More failures after 4.3.0 EEST tests updated at https://github.com/erigontech/erigon/pull/14403
=> workflows: threshold further higher for hive-eest

core/snaptype/block_types.go, erigon-lib/downloader/snaptype/type.go, turbo/snapshotsync/freezeblocks/block_snapshots.go, turbo/snapshotsync/freezeblocks/dump_test.go
pick https://github.com/erigontech/erigon/pull/14763
=> blocks retire: to use core rlp package instead of txpool's one

erigon-lib/kv/mdbx/kv_mdbx.go
Reason: CL using it as in-mem batch for blocks - and seems we touched the limit - it's ok to increase it.
=> [r30] increase in-mem db limit 

erigon-lib/state/aggregator.go
https://github.com/erigontech/erigon/issues/14300
this will make the downloaded salt and the default salt have same values, and therefore fixing the above error
=> revert rand source for salt

eth/stagedsync/exec3.go, eth/stagedsync/exec3_parallel.go, eth/stagedsync/exec3_serial.go, execution/exec3/state.go
Block's gas limit should be used for the gasPool, for `state_transition` to work correctly
=> eth, execution: Use block level gasPool in serial execution

erigon-lib/state/aggregator.go, erigon-lib/state/aggregator_files.go, erigon-lib/state/aggregator_fuzz_test.go, erigon-lib/state/aggregator_test.go, erigon-lib/state/domain_shared_test.go, erigon-lib/state/integrity.go, erigon-lib/state/merge.go, erigon-lib/state/squeeze.go, eth/stagedsync/exec3.go, eth/stagedsync/stage_execute.go, turbo/app/snapshots_cmd.go
reason: greedy prune can hold erigon from executing new blocks ASAP (missed attestations, etc...)
=> [r30] no greedy prune on chain-tip

turbo/jsonrpc/eth_receipts.go, turbo/jsonrpc/eth_receipts_test.go
For multi-block `eth_getLogs` requests, state sync transaction events will appear out of order. This fix ensures that logs are placed in the right spot in the response.
=> Make state sync events in order

cmd/rpcdaemon/cli/config.go
```
[dbg] newRoSnapshots created with empty ChainName stack="[snapshots.go:554 snapshots.go:549 block_snapshots.go:77 config.go:418 main.go:43 command.go:985 command.go:1117 command.go:1041 command.go:1034 main.go:69 proc.go:283 asm_amd64.s:1700]"
```
=> fix empty chain name in external

polygon/p2p/fetcher_config.go
got a few `await *eth.BlockBodiesPacket66 response interrupted: context deadline exceeded` errors while testing stuff on Amoy for https://github.com/erigontech/erigon/pull/13689
bumping up the `responseTimeout` for the block download within the initial sync to tip by x2 to 10 secs (on chain tip we have a lower 1 sec responseTimeout - less blocks to download there in a batch)
this is safe to do so and some further tweaking may be useful in the future if we still get frequent response timeouts from peers - it is a balance between not stalling for too long when hitting slow peers but also not missing out on too many peers because our timeout is too aggressive
=> polygon/p2p: tune awaitResponse timeout for initial sync to tip block download

eth/integrity/bor_snapshots.go, polygon/heimdall/snapshot_store.go, turbo/app/snapshots_cmd.go
reviving work on https://github.com/erigontech/erigon/pull/13689 to help @eastorski 
had a situation while testing where there were no gaps in seg files for checkpoints but there was a gap between last checkpoint in files and first in the db
this PR enhances the check for spans, milestones, checkpoints snapshots in "erigon seg integrity" to also check if there is a gap between the last snapshot in the seg files and the first one in the db if any (also adds a check for consecutiveness in the db as part of that because it is low effort and good extra info to have so why not)
=> seg: enhance integrity check for astrid snapshots

cmd/state/exec3/state.go, eth/stagedsync/exec3.go, eth/stagedsync/exec3_parallel.go, eth/stagedsync/exec3_serial.go
Block's gas limit should be used for the gasPool, for `state_transition` to work correctly
Cherry-pick #14761
=> eth, execution: Use block level gasPool in serial execution (#14761)

polygon/sync/execution_client.go, polygon/sync/sync.go
Relates to improving our support of "rm -rf chaindata" (somewhat relates to https://github.com/erigontech/erigon/issues/13674)
After adding more debug logs in https://github.com/erigontech/erigon/pull/14414 it is now clear why with Astrid we sometimes get "domain ahead of blocks" err sometimes after "rm -rf chaindata" during "sync to tip" and it is also clear what the fix should be.
The theory I had previously of when this err could happen is confirmed:
- when we insert N+1, N+2, ... -> we limit how much we insert using LoopBlockLimit which is 5,000 blocks before we call UpdateForkChoice on the batch 
- so if domains is ahead of blocks with more than 5,000 blocks we will hit this error 
- this is confirmed with below logs 
- you can see we insert around ~5000 from 21069939 to 21075570
- …
=> polygon/sync: tolerate domain ahead of blocks err on initial sync to tip 

Makefile
Small changes to allow easier modifying of builds for things like cross compilation.
For example I use this for cross compilation with
```
GOOS="linux" GOARCH="amd64" CGO_ENABLED="1" CXX="x86_64-linux-gnu-g++" CC="x86_64-linux-gnu-gcc" \
make erigon GO_FLAGS='-race -v' EXTRA_BUILD_TAGS='nosilkworm'
```
Which uses all the usual Go command build adjustments (git branches, trims, default build tags) but adds a few extra pieces needed for clean cross-compilation.
I put detail in the commit messages.
=> Tweak Makefile flag variables and build output

cmd/downloader/main.go, erigon-lib/downloader/downloader.go, eth/backend.go
Cherry pick for release. See issue referred in commit.
Per last #networking meeting, @mh0lt plans to expose through the conventional Erigon pprof as well but in the meanwhile this is still usable and worth having access to for diagnostics.
=> Expose downloader torrent client status to HTTP (#14639)

erigon-lib/chain/snapcfg/util.go, erigon-lib/go.mod, erigon-lib/go.sum, go.mod, go.sum
This is a companion PR to https://github.com/erigontech/erigon-snapshot/pull/544
From multi CDN support, it switches it to R2.
Files are not published yet (for main and release/3.0) at the time I'm opening this PR, so to test it you should add: `SNAPS_GIT_BRANCH="michele-mirror-test"` env variable.
This is a minimalistic PR in order to quickly workaround https://github.com/erigontech/erigon/issues/14808 ; other long term improvements are required.
=> Switches CDN to R2

turbo/snapshotsync/freezeblocks/block_reader.go
This err return is important if the file is really needed to return the block for the calling function. Also to be noted that whether the file was supposed to be there was already checked above
=> snapshotsync: return txnSeg file err

.github/workflows/kurtosis/pectra.io
Been failing for no reason on GH actions only, probably hardware issue. Will optimize this test and enable in future.
=> workflows: Temp disable 7702 invalidation test on kurtosis

.github/workflows/qa-constrained-tip-tracking.yml, .github/workflows/qa-tip-tracking.yml
Implement the same solution adopted for tip-tracking test handling the pre-built db
=> qa-tests: constrained tip-tracking with chaindata backup/restore

.github/workflows/qa-clean-exit-block-downloading.yml
Same solution implemented in the tip-tracking test
=> qa-tests: clean-exit with chaindata backup/restore

erigon-lib/state/merge.go
merge must not affect chain-tip: enabling madv - will impact not only merge, but any file touches (for example by RPC)
=> less disk IO during files merge

erigon-lib/state/merge.go
merge must not affect chain-tip: enabling madv - will impact not only merge, but any file touches (for example by RPC)
=> reduce disk IO during files merge

.github/workflows/test-hive-eest.yml, Makefile, cmd/utils/flags.go
This removes the 2-3 second wait times when using the `init` cmd (and most other cmd's for that matter). And reduces mass testing like Hive. This is important to improve our CI too
=> cmd/utils: Remove unnecessary `LoadSnapshotsHashes` invocation

cl/sentinel/handlers/handlers.go
- Replaces the `TODO` comment inside the error handler with an actual `log.Warn(...)` statement to ensure errors are properly reported.
- Minor formatting tweak for the `if` condition checking goodbye stream closure errors — improves readability and aligns with style conventions.
=> Improve error visibility in stream handler by replacing TODO with log.Warn

cmd/utils/flags.go, turbo/execution/eth1/forkchoice.go
Still can see `1Gb/s`. But `sys` goes down from `20Gb` to `8Gb`
(on ethmainnet)
=> [e30] reduce default `--torrent.download.slots` 

erigon-lib/go.mod, erigon-lib/go.sum, go.mod, go.sum
Without this change I was getting 
```
github.com/erigontech/erigon-snapshot@v1.3.1-0.20250502062723-10cd437f34d8: invalid version: unknown revision 10cd437f34d8
```
while building erigon.
=> deps: merged erigon-snapshot & interfaces commits

turbo/jsonrpc/eth_receipts.go
Merge PR #14869: rpcdaemon: reuse getReceipt() to improve performance using receipt-cache
=> rpcdaemon: merge PR 14869 on 3.0 (re-use getReceipt() on logs retrieval)

.github/workflows/reusable-release-build-debian-pkg.yml
This pull request updates the link in the Erigon installation script to point to the new documentation site.
=> Updated docs link in the pre-built binaries installation message

.github/workflows/qa-sync-from-scratch-minimal-node.yml
12 hours are not enough for polygon
=> qa-tests: increase sync-from-scratch (minimal node) test time

erigon-lib/downloader/downloadercfg/downloadercfg.go
pick https://github.com/erigontech/erigon/pull/14958
=> [r31] Revert "[3.0 pick] downloader: same NetworkChunkSize as in Erigon2" 

cl/aggregation/pool_test.go, cl/beacon/beaconevents/model.go, cl/beacon/beaconevents/operation_feed.go, cl/beacon/handler/pool.go, cl/cltypes/solid/attestation.go, cl/cltypes/solid/bitlist.go, cl/cltypes/solid/bitlist_test.go, cl/phase1/core/state/cache_accessors.go, cl/phase1/network/services/attestation_service.go, cl/phase1/network/services/sync_committee_messages_service.go, cl/phase1/network/services/sync_contribution_service.go, cl/validator/sync_contribution_pool/sync_contribution_pool.go
- Resolve bug in `SingleAttestation.ToAttestation` causing incorrect `aggregation_bits`.
- Fix "invalid bls verification" error caused by new sync_commitee [algo](https://github.com/ethereum/consensus-specs/blob/dev/specs/electra/beacon-chain.md#modified-get_next_sync_committee_indices), which results in duplicate validators within the sync subcommitee.
- relates to issue https://github.com/erigontech/erigon/issues/14830
=> Cherrypick: Caplin: Fix misc issues after electra (#14910)

cmd/evm/t8n_test.go
This PR disables newly added `evm` tests b/c they don't pass on Windows target. Issue is going to be fix soon.
=> cmd/evm: Hotfix. Disable new tests `evm` for Windows built.

cmd/evm/t8n_test.go, turbo/cmdtest/test_cmd.go
Fixes: https://github.com/erigontech/erigon/issues/14993
=> tests: Increase `cmd/evm` tests  subprocess timeout to 30 sec

cmd/utils/flags.go
- Hoodi that's without snapshots right now easily hits this limit after 2-3 months on "archive"
- This is really an artificial limit, may wanna increase it further. Having a very high limit, that's only 1% used is better than having a very low limit that can be hit 20% of the use cases
=> cmd: Increase default `db.size.limit`

turbo/transactions/tracing.go
This PR resolves the issue reported in #14999, where the `debug_traceTransaction` API does not include event logs in the output, even when the `withLog = true` parameter is specified. The existing unit tests also failed to detect this issue, as they did not flag the missing event logs.
After analyzing the API call and unit test workflows, the issue was traced to `turbo/transactions/tracing.go` at line 188 in the `ExecuteTraceTx` function. The function lacked a critical step to set hooks on `ibs` before executing the transaction. This caused the `OnLog` hook to remain unset, resulting in no event logs being included in the output, regardless of the `withLog` parameter.
- Added the necessary hook-setting step at the beginning of the `ExecuteTraceTx` function to ensure the `OnLog` hook is …
=> fix bug #14999, withlog tracerConfig param NOT work in debug_traceTnsaction API

rpc/jsonrpc/tracing.go
This pull request addresses the issue described in #15024, where the `TraceCallMany` function in `rpc/jsonrpc/tracing.go` (line 431) incorrectly resets the intermediate block state (`ibs`) during the transaction execution loop at line 552. The inclusion of `ibs.Reset()` caused two primary problems:
1. **Violation of API semantics**: The API specifies that transactions in the `transactions` parameter are executed sequentially, with subsequent transactions depending on the results of prior ones. The reset operation broke this dependency.
2. **Incorrect state reset**: Resetting `ibs` before executing transactions disrupted the intended state management.
By removing the erroneous `ibs.Reset()` call at line 552, this PR fixes both issues, ensuring that `stateOverrides` (used with `tracer = …
=> bugfix #15024, do not reset ibs before each tx exec and StateOverrides

turbo/app/snapshots_cmd.go
Decided to pick up different route (simpler). Effectively it was an issue with the tool, not the process.
The tool unnecessarily computed the new range `Retire Process` should operate on, but it should just give a point where to start from (the last block in the snapshot). The actual range is calculated in a loop in the:
```
if err := br.RetireBlocks(ctx, from, to, log.LvlInfo, nil, nil, nil); err != nil {
return err
}
```
The tool precomputed the entire range before running the retirement process, but giving it already narrowed range.
The `RetireBlock` function computes the range itself, it just needs to know where to start from.
=> Fix snapshot file creation

.github/workflows/qa-tip-tracking-polygon.yml
Erigon uses a different snapshot scheme for the main and release/3 branches, so we need two pre-built databases on the Test Runner.
However, there is no disk space to host two pre-built databases.
As this is an upgrade test, we are disabling the tests on the main branch.
=> qa-tests: disable polygon tip-tracking on main branch

Makefile, core/snaptype/block_types.go, erigon-lib/downloader/snaptype/type.go, erigon-lib/recsplit/index_test.go, erigon-lib/recsplit/recsplit.go, erigon-lib/recsplit/recsplit_fuzz_test.go, erigon-lib/recsplit/recsplit_test.go, erigon-lib/state/simple_index_builder.go, erigon-lib/state/snap_repo_test.go, polygon/heimdall/types.go
keep finding erigon-lfp-buf* files in temp/; this PR cleans them up once done
=> fill in recsplit.close() at different places

erigon-lib/state/inverted_index.go
I noticed that RPC Integration Tests started failing systematically after #15065, so I checked the changes in such PR and spotted this.
RPC Integration Tests are OK here: https://github.com/erigontech/erigon/actions/runs/15052494612
=> Inverted Index: fix check for file existence

erigon-lib/downloader/downloader_test.go
```
--- FAIL: TestVerifyData (1.99s)
downloader_test.go:97:
Error Trace:	github.com/erigontech/erigon-lib/downloader/downloader_test.go:97
Error:      	Received unexpected error:
openClient: torrentcfg.openClient: torrent.NewClient: subsequent listen: listen udp4 :53091: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Test:       	TestVerifyData
testing.go:1232: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestVerifyData2884756745\001\downloader\mdbx.dat: The process cannot access the file because it is being used by another process.
FAIL
```
enable by: https://github.com/erigontech/erigon/issues/15096
=> TestVerifyData: disable on win 

core/vm/instructions.go, core/vm/jump_table.go, core/vm/runtime/runtime_test.go, core/vm/stack/stack.go
closes #15114
benchmark vs main
```
goos: darwin
goarch: arm64
pkg: github.com/erigontech/erigon/core/vm/runtime
cpu: Apple M3 Max
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
EVM_SWAP1/10k-16   63.24µ ± 2%   59.99µ ± 2%  -5.14% (p=0.000 n=10)
│   old.txt    │            new.txt             │
│     B/op     │     B/op      vs base          │
EVM_SWAP1/10k-16   4.280Ki ± 4%   4.327Ki ± 4%  ~ (p=0.391 n=10)
│  old.txt   │            new.txt             │
│ allocs/op  │ allocs/op   vs base            │
EVM_SWAP1/10k-16   49.00 ± 0%   49.00 ± 0%  ~ (p=1.000 n=10) ¹
```
=> VM OPSwap optimisation

docs/programmers_guide/witness_formal_spec.md
- Updated reference to witness_operators_test.go in witness_formal_spec.md to point to erigon-lib/trie/witness_operators_test.go instead of trie/witness_operators_test.go
- Updated reference to witness_operators_test.go in witness_format.md to point to erigon-lib/trie/witness_operators_test.go
- Updated reference to witness_operators.go in witness_format.md to point to erigon-lib/trie/witness_operators.go
=> docs: fix broken link

erigon-lib/downloader/downloader_test.go
```
--- FAIL: TestVerifyData (1.99s)
downloader_test.go:97:
Error Trace:	github.com/erigontech/erigon-lib/downloader/downloader_test.go:97
Error:      	Received unexpected error:
openClient: torrentcfg.openClient: torrent.NewClient: subsequent listen: listen udp4 :53091: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Test:       	TestVerifyData
testing.go:1232: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestVerifyData2884756745\001\downloader\mdbx.dat: The process cannot access the file because it is being used by another process.
FAIL
```
pick https://github.com/erigontech/erigon/pull/15095
=> [r30] TestVerifyData: disable win test

cl/phase1/forkchoice/fork_choice_test.go, cmd/evm/t8n_test.go, erigon-lib/types/encdec_test.go, p2p/dial_test.go, p2p/nat/nat_test.go, polygon/heimdall/client_http_test.go, rpc/client_test.go, rpc/jsonrpc/send_transaction_test.go, tests/bor/mining_test.go, txnprovider/shutter/block_building_integration_test.go
Continuation of PR #14662. I used [gotestsum](https://github.com/gotestyourself/gotestsum#finding-and-skipping-slow-tests) with 500ms threshold.
=> tests: disable more slow tests in short testing

core/vm/contracts.go, erigon-lib/types/transaction_signing.go, execution/consensus/ethash/consensus.go, txnprovider/shutter/internal/crypto/encryption.go
see https://github.com/ethereum/go-ethereum/pull/29911
=> optimization: replace division/multiplication by 2^x with shifts

core/test/domains_restart_test.go, erigon-lib/state/aggregator_bench_test.go, erigon-lib/state/aggregator_fuzz_test.go, erigon-lib/state/aggregator_test.go, erigon-lib/state/domain_shared.go, erigon-lib/state/domain_shared_test.go
next step will be: add txNum parameter (it will be step towards removing txNum from SD)
=> `temporal.DomainPut`: remove `k2` parameter

cl/clparams/config.go
Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.
=> refactor: replace []byte(fmt.Sprintf) with fmt.Appendf

cmd/utils/flags.go
pick https://github.com/erigontech/erigon/pull/15018
- Hoodi that's without snapshots right now easily hits this limit after 2-3 months on "archive"
- This is really an artificial limit, may wanna increase it further. Having a very high limit, that's only 1% used is better than having a very low limit that can be hit 20% of the use cases
=> [r30] cmd: Increase default `db.size.limit`

erigon-lib/common/dbg/dbg_env.go, erigon-lib/common/dbg/experiments.go, erigon-lib/common/dbg/leak_detector.go
This is support for the implementation of parallel processing.  Most of it is to enable environmental management of various levels of block tracing to work out the route cause of state root mismatches in parallel execution vs the serial flow.
=> Env vars to manage parallel execution and block tracing

turbo/jsonrpc/receipts/receipts_generator.go
quick-fix until https://github.com/erigontech/erigon/pull/14221 landed in `release/3.0`
=> [r30] adjust txnum fro current env 

erigon-lib/kv/kv_interface.go, erigon-lib/kv/mdbx/kv_mdbx.go, erigon-lib/kv/membatchwithdb/memory_mutation.go, erigon-lib/kv/remotedb/kv_remote.go, erigon-lib/kv/temporal/kv_temporal.go, erigon-lib/state/domain_shared.go, eth/stagedsync/exec3.go, eth/stagedsync/exec3_parallel.go, eth/stagedsync/stage_custom_trace.go, eth/stagedsync/stage_execute.go, eth/stagedsync/stage_snapshots.go, turbo/app/snapshots_cmd.go
This change adds an Apply(tx) function to transactions and an AsyncTx which uses a channel to pass the apply function between go-routines.
It is used to enable parallel workers to access the headers/blocks on the main RW execution thread, even with an external tx whilst maintaining their own read only transaction for state access.
There is an overhead in doing this - but so long as the main execution thread remains live in its wait loop this does not impact processing due to the relative rareness of these types of call from the evm.
=> Add apply/async operations for transactions

rpc/ethapi/api.go, rpc/ethapi/internal.go, rpc/jsonrpc/debug_api.go, rpc/jsonrpc/erigon_block.go, rpc/jsonrpc/eth_block.go, rpc/jsonrpc/eth_call_test.go, rpc/jsonrpc/eth_uncles.go, rpc/jsonrpc/graphql_api.go, rpc/jsonrpc/otterscan_api.go, rpc/jsonrpc/otterscan_block_details.go
https://github.com/erigontech/nitro-erigon/issues/154
adding support for 
`l1BlockNumber`, `sendCount`, `sendRoot`, as described in https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/rpc-methods#additional-fields-2
Additionally, for legacy Arbitrum Classic blocks, before Nitro, `sendCount` and `sendRoot` weren't used, `l1BlockNumber` was different, which is also implemented
=> RPCd: Add arbitrum specific getBlock changes

turbo/app/snapshots_cmd.go
https://github.com/erigontech/erigon/issues/15174
- need state-salt file else `integration` command won't work.
- perhaps the proper way would be provide a separate `gen-state-salt` command, which can be executed when the intention is to regen state snapshot files -- but this is not important for now. Just retaining salt file works.
=> don't delete state-salt file on rm-all-state-snapshots.

eth/stagedsync/stage_execute.go, execution/exec3/historical_trace_worker.go
- also added access list to warmup
=> mapReduce: final txn must be executed in `reduecer` because require "all receipts of block" 

eth/stagedsync/exec3.go, eth/stagedsync/stage_execute.go, execution/exec3/historical_trace_worker.go
pick #15205 
- also added blocks read-ahead at non-chain-tip (and added accesslist use there)
=> [r30] mapReduce: final txn must be executed in reduecer because require "all receipts of block" 

.github/workflows/qa-rpc-integration-tests.yml, rpc/jsonrpc/otterscan_transaction_by_sender_and_nonce.go
closes #13238
Fix on range nextTxnID-prevTxnID+1
If the change is in the tx identified by nextTxnId, the transaction is not considered and the API returns null (as described in the issue) (because txn.GetNonce() != nonce)
Added two integration tests to verify the resolution of the problem (with the previous software version, the new RPC tests failed).
=> rpcdaemon: Fix issue 13238 ots get transaction by sender and nonce

core/blockchain.go, core/state/database.go, core/state_transition.go, core/vm/evm.go, core/vm/evm_test.go, core/vm/evmtypes/evmtypes.go, core/vm/interface.go, core/vm/mock_vm.go, eth/tracers/js/tracer_test.go, eth/tracers/logger/access_list_tracer.go, eth/tracers/logger/logger_test.go, rpc/jsonrpc/eth_callMany.go, rpc/jsonrpc/tracing.go, turbo/transactions/tracing.go
Mostly was motivated by seen `AccessList` methods in profiler
```
go test -bench=BenchmarkCall -run=Benchmark  ./core/vm/runtime -count=10 > new2.txt
go test -bench=BenchmarkCall -run=Benchmark  ./core/vm/runtime -count=10 > old2.txt
/home/erigon/go/bin/benchstat old2.txt new2.txt
goos: linux
goarch: amd64
pkg: github.com/erigontech/erigon/core/vm/runtime
cpu: AMD EPYC 4344P 8-Core Processor
│  old2.txt   │              new2.txt              │
│   sec/op    │   sec/op     vs base               │
Call-16   3.165m ± 0%   3.097m ± 1%  -2.13% (p=0.000 n=10)
│   old2.txt   │              new2.txt               │
│     B/op     │     B/op      vs base               │
Call-16   1.800Mi ± 0%   1.758Mi ± 0%  -2.34% (p=0.000 n=10)
│  old2.txt   │            new2.txt             │
│  allocs/op  │ …
```
=> evm: non-interface IntraBlockState

rpc/jsonrpc/eth_subscribe_test.go, turbo/privateapi/ethbackend.go
Fixes #14546 
The main task executing `TestEthSubscribe` sporadically gets blocked waiting for new headers in case the anonymous task created and started in `rpchelper.New` running the subscription loop has not yet reached the `Subscribe` call, when `stages.StageLoopIteration` completes its execution. In such a case, the internal subscription channels in `Events` have not been created yet and thus the NEW_HEADER notifications are not sent.
A simple solution, not touching the production code, is relying on the initial NEW_SNAPSHOT notification that is sent unconditionally by `EthBackendServer` after creating the internal subscription channels.
=> ci: fix and enable TestEthSubscribe

tests/bor/mining_test.go, txnprovider/shutter/block_building_integration_test.go
PRs https://github.com/erigontech/erigon/pull/14972 and https://github.com/erigontech/erigon/pull/15144 have unintentionally disabled `TestMiningBenchmark` and `TestShutterBlockBuilding`:
- The first PR moved those tests from "medium" to "short" by introducing the `go:build !race` build tag
- Then, the second PR skipped them entirely because they were too slow
Instead we should just:
- skip the tests if we are running the "short" test suite
- skip the tests if we are running the "medium" test suite but the os is "darwin" until https://github.com/erigontech/erigon/issues/15007 gets resolved - this way the tests will be run on the linux and win "medium" test runs as opposed to never being run
=> tests: run TestShutterBlockBuilding and TestMiningBenchmark in medium tests

execution/eth1/ethereum_execution.go, turbo/snapshotsync/snapshots.go
also skip making a goroutine in the average case
=> Engine-API: Fixed `context canceled`

rpc/jsonrpc/eth_call.go
closes #12850
eth_call(): for future blocks should return an error not null
=> rpcdaemon: eth_call for future blocks should return an error (ssue 12850)

turbo/engineapi/engine_server.go
Block building is critical, 500ms is too little. I pick 12s because it is the slot duration of ETH 2.0
=> Engine-API: Extend fcu waiting to 12 seconds from 500 milliseconds when building block

polygon/sync/sync.go
noticed some `response interrupted: context deadline exceeded` errs on Amoy in a case where there were no milestones for over 4 hours and right after initial sync-to-tip finished we had to backwards connect a new block event with around 700 blocks gap
=> polygon/sync: tweak fetch blocks backwards timeout

cmd/devnet/services/polygon/proofgenerator_test.go, cmd/evm/internal/t8ntool/transition.go, cmd/state/commands/opcode_tracer.go, core/blockchain.go, core/chain_makers.go, core/evm.go, core/state/txtask.go, core/state_processor.go, core/vm/evmtypes/evmtypes.go, core/vm/instructions.go, core/vm/runtime/runtime.go, core/vm/runtime/runtime_test.go, eth/stagedsync/exec3.go, eth/stagedsync/exec3_parallel.go, eth/stagedsync/stage_mining_exec.go, eth/stagedsync/stage_witness.go, execution/abi/bind/backends/simulated.go, execution/consensus/clique/clique_test.go, execution/exec3/historical_trace_worker.go, rpc/jsonrpc/eth_callMany.go, rpc/jsonrpc/otterscan_search_trace.go, rpc/jsonrpc/overlay_api.go, rpc/jsonrpc/receipts/receipts_generator.go, rpc/jsonrpc/tracing.go, tests/state_test_util.go, turbo/transactions/call.go, turbo/transactions/tracing.go
This change adds an error return to GetHashFn and GetHeaderFn so that these are passed to the EVM during execution.
These errors where previously swallowed in processing resulting in a difficult to diagnose state root mismatch due to different processing paths.
=> Add error to GetHashFn & GetHeaderFn

polygon/sync/sync.go
noticed some `response interrupted: context deadline exceeded` errs on Amoy in a case where there were no milestones for over 4 hours and right after initial sync-to-tip finished we had to backwards connect a new block event with around 700 blocks gap
=> polygon/sync: tweak fetch blocks backwards timeout (#15328)

cmd/devnet/main.go, cmd/integration/commands/flags.go, cmd/utils/flags.go, consensus/misc/eip1559.go, core/forkid/forkid.go, core/vm/contracts.go, core/vm/evm.go, core/vm/interpreter.go, core/vm/jump_table.go, erigon-lib/chain/chain_config.go, erigon-lib/common/fixedgas/intrinsic_gas.go, erigon-lib/common/fixedgas/intrinsic_gas_test.go, eth/backend.go, eth/ethconfig/config.go, eth/stagedsync/stage_mining_create_block.go, eth/stagedsync/stage_mining_exec.go, eth/stagedsync/stagedsynctest/harness.go, params/mining.go, params/protocol_params.go, polygon/bor/bor.go, polygon/bor/borcfg/bor_config.go, tests/bor/helper/miner.go, txnprovider/txpool/assemble.go, txnprovider/txpool/pool.go, txnprovider/txpool/pool_fuzz_test.go, txnprovider/txpool/pool_test.go
This is a cherry pick from main of the https://github.com/erigontech/erigon/pull/15261: Which implements the Bhilai fork changes as specified in:
[PIP-63](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-63.md)
and also the feature to allow early block announcements specified in:
[PIP-66](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-66.md)
The individual changes included here are:
[PIP-60: Increase gas limit to 45M](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-60.md)
[PIP-58: Increase BaseFeeChangeDenominator to 64](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-58.md)
[EIP-2537: Precompile for BLS12-381 curve …
=> R3 Polygon Bhilai Fork Updates

cmd/integration/commands/state_domains.go, core/state/cached_reader.go, core/state/cached_reader3.go, core/state/database.go, core/state/history_reader_v3.go, core/state/rw_v3.go, core/state/state_object.go, core/state/stateless.go, core/state/triedb_state.go, core/state/versionedio.go, rpc/jsonrpc/eth_accounts.go, rpc/jsonrpc/eth_call.go, turbo/engineapi/engine_types/jsonrpc.go
This is mainly to reduce garbage from IO when running the EVM.  This forces an early conversion to an [4]uint64 array which is then passed back via the stack rather than escaping to the heap.  This []byte escape is a significant source of garbage when the evm is running.
=> Make ReadAccountStorage return uint256 not []byte

execution/eth1/ethereum_execution.go, turbo/snapshotsync/snapshots.go
This reverts commit b605ef07c1285d01e1ac08311074f003401ff2ec.
Revert is needed for Hive-EEST, unless another fix is available
=> Revert "Engine-API: Fixed `context canceled` (#15277)"

cmd/downloader/main.go, cmd/integration/Readme.md, cmd/integration/commands/stages.go, cmd/scripts/mirror-datadir.sh, core/vm/stack.go, erigon-lib/etl/buffers.go, erigon-lib/etl/etl.go, erigon-lib/kv/membatch/mapmutation.go, erigon-lib/recsplit/recsplit.go, erigon-lib/rules.go, erigon-lib/seg/compress.go, erigon-lib/seg/parallel_compress.go, erigon-lib/state/aggregator.go, erigon-lib/state/aggregator2.go, erigon-lib/state/aggregator_files.go, erigon-lib/state/aggregator_test.go, erigon-lib/state/btree_index.go, erigon-lib/state/history.go, erigon-lib/state/merge.go, erigon-lib/state/squeeze.go, eth/stagedsync/exec3.go, eth/stagedsync/stage_execute.go, eth/stagedsync/stage_senders.go, rules.go, turbo/app/snapshots_cmd.go
In PR:
- `seg.compress` to use ETL buffs pool (small buffs for workers, large bufs for Dict reducer)
- `recsplit` to use ETL buffs pool
- `bt` to use ETL buffs pool
- `seg.compress` rare check `ctx` in `AddWord`
- `seg.compress` no superstrings `growslice` in `AddWord`
- `DictionaryBuilder.processWord` re-use objects - less `common.Copy(chars)` (which does `make([]byte)`)
- mergeFiles: reduce code depth
- mergeFiles: report progress of merge
- exec3: to use 2 merge threads (when not on chain-tip)
- retire: to use 4 merge threads
- linter for `NewCollectorWithAllocator` defer close
=> retire: more merge threads

turbo/engineapi/engine_server.go
In real life, we cannot expect any block to be download in half a second because of latency. this is way too little.
=> Engine-API: Faster recovery for the block downloader

core/state/intra_block_state.go, core/state/rw_v3.go, erigon-lib/state/domain.go, erigon-lib/types/accounts/account_test.go
Zombie address is encoded to `0000` so during commitment it is empty, not Deleted
=> fix zombie address protection marking

core/state/database_test.go, core/state/dump.go, execution/abi/bind/backends/simulated.go, rpc/jsonrpc/receipts/receipts_generator.go, tests/block_test_util.go, tests/state_test_util.go, tests/statedb_chain_test.go, tests/statedb_insert_chain_transaction_test.go, turbo/stages/blockchain_test.go, turbo/stages/chain_makers_test.go, turbo/stages/mock/mock_sentry.go
This is a refactor to get tests to use `BeginTemporalRw` and `TemporalView` rather than blind casting `kv.Tx` to `TemporalGetter`.
=> Use temporal db + views rather than cast tx

Dockerfile, Dockerfile.all
- Move the older one to `Dockerfile.all`
- Build only erigon and rpcdaemon
Saves time, most of the use cases covered
=> Use a smaller dockerfile by default

cmd/devnet/services/polygon/proofgenerator_test.go, cmd/evm/internal/t8ntool/transition.go, cmd/state/commands/opcode_tracer.go, core/blockchain.go, core/chain_makers.go, core/evm.go, core/state/intra_block_state_test.go, core/state/txtask.go, core/state_processor.go, core/vm/evmtypes/evmtypes.go, core/vm/instructions.go, core/vm/runtime/runtime.go, core/vm/runtime/runtime_test.go, eth/stagedsync/exec3.go, eth/stagedsync/exec3_parallel.go, eth/stagedsync/stage_mining_exec.go, eth/stagedsync/stage_witness.go, execution/abi/bind/backends/simulated.go, execution/consensus/clique/clique_test.go, execution/exec3/historical_trace_worker.go, rpc/jsonrpc/eth_callMany.go, rpc/jsonrpc/otterscan_search_trace.go, rpc/jsonrpc/overlay_api.go, rpc/jsonrpc/receipts/receipts_generator.go, rpc/jsonrpc/tracing.go, tests/state_test_util.go, turbo/transactions/call.go, turbo/transactions/tracing.go
https://github.com/erigontech/erigon/pull/15344 was failing tests due to their use of repeating block numbers which does not happen in normal operation.
This change fixes the tests at the cost of slightly worse memory usage and performance in normal operations as caching is now done at a block rather than process level.
=> Fix for: Add error to GetHashFn & GetHeaderFn

turbo/execution/eth1/forkchoice.go, turbo/jsonrpc/receipts/receipts_generator.go
Basically, need to regen if the block was reorged.
=> Cherry-pick: Fix receipts dangling from reorged blocks (#15401)

polygon/heimdall/snapshot_store.go
related to discussion from last week:
https://discord.com/channels/1133875232453693480/1133875633819242526/1377999996875571331
fixes 2 issues in "seg integrity":
- if first entity in snapshots (e.g. 10) is greater than first expected entity (e.g. 1) and all are consecutive there will be no error - it should err because there is a gap from e.g. 1 to 10
- fixes a bug in the integrity code which prevented us from catching a gap in Spans snapshots `unexpected span gap: last=3454,new=3456` (e.g. issue
[here](https://github.com/erigontech/erigon/issues/15316#issuecomment-2920187952))
=> integrity: fix check for spans and checkpoints (#15447)

.gitignore, Makefile
Move hive tests output to `temp/`, which is in .gitignore
=> Makefile: move hive output to temp folder

eth/stagedsync/stage_snapshots.go, turbo/snapshotsync/merger.go, turbo/snapshotsync/snapshots.go, turbo/snapshotsync/snapshots_test.go, turbo/snapshotsync/snapshotsync.go
Michele reported that a minimal node for the Amoy validator encounters an error after syncing from scratch:
```
[EROR] [05-28|13:04:52.818] [sync] waypoint execution err            lastCorrectTipNum=22134999 lastCorrectTipHash=0xc0ee90a99bc09918f402c5f2811f3d7fa8a64f859417163990ac4659228da34f execErr="updateForkChoice: [4/6 Execution] nil block 21638397"
```
Upon investigation, I found that the issue is related to inconsistent snapshot folder contents. Specifically, for minimal nodes, we filter out too many transaction snapshots.
The last commitment domain snapshot contained block number 21,638,396, but the first transaction snapshot started from block number 22,000,000. This discrepancy arises because minimal nodes retain snapshots only within a ~100K block range.
As a result, there is a …
=> Fixed snapshot downloader inconsistency for minimal mode node

eth/stagedsync/stage_snapshots.go, p2p/sentry/simulator/sentry_simulator.go, turbo/snapshotsync/merger.go, turbo/snapshotsync/snapshots.go, turbo/snapshotsync/snapshots_test.go, turbo/snapshotsync/snapshotsync.go
Michele reported that a minimal node for the Amoy validator encounters an error after syncing from scratch:
```
[EROR] [05-28|13:04:52.818] [sync] waypoint execution err            lastCorrectTipNum=22134999 lastCorrectTipHash=0xc0ee90a99bc09918f402c5f2811f3d7fa8a64f859417163990ac4659228da34f execErr="updateForkChoice: [4/6 Execution] nil block 21638397"
```
Upon investigation, I found that the issue is related to inconsistent snapshot folder contents. Specifically, for minimal nodes, we filter out too many transaction snapshots.
The last commitment domain snapshot contained block number 21,638,396, but the first transaction snapshot started from block number 22,000,000. This discrepancy arises because minimal nodes retain snapshots only within a ~100K block range.
As a result, there is a …
=> Fixed snapshot downloader inconsistency for minimal mode node (#15429)

turbo/cli/flags.go
eth_subscribe should emit all matching logs.
In case rpcdaemon stand-alone the subscriber channel is created with channel size 8192 (https://github.com/erigontech/erigon/blob/main/cmd/utils/flags.go#L487) so its is works.
In case embedded rpcdaemon the channel is created with zero that in https://github.com/erigontech/erigon/blob/main/rpc/rpchelper/subscription.go#L38 is defaulted to 8 therefore the client receives at maximum 8/9 logs
Fixes #15423
=> erigon: set default subscriber notification channel size to 8192 (as rpcdaemon stand-alone)

rpc/jsonrpc/trace_adhoc.go
Line 64:
Corrected typo in comment:
prams → params
Reason: Fixed a spelling mistake in a code comment to enhance clarity and maintain consistent documentation quality.
Line 198:
Corrected typo:
feilds → fields
Reason: Fixed a spelling error in the comment to improve readability and professionalism.
Line 224:
Replaced method:
maxFeePerBlobGas.SetFromBig(args.MaxFeePerBlobGas.ToInt()) →
maxFeePerBlobGas = uint256.MustFromBig(args.MaxFeePerBlobGas.ToInt())
Reason: Using MustFromBig is safer and more idiomatic. It avoids mutating an existing value and ensures proper initialization.
=> jsonrpc: Fix nil ptr in trace_callMany 

RELEASE_INSTRUCTIONS.md, cmd/integration/commands/state_domains.go, turbo/app/snapshots_cmd.go
- compaction is standard db term for what purification does..
- `--no-commitment` removed; and `--domain` accepted (just like `stage_custom_trace` cmd)
issue: https://github.com/erigontech/erigon/issues/15339
=> rename purification to compaction

cmd/scripts/mirror-datadir.sh, erigon-lib/state/aggregator.go, erigon-lib/state/entity_integrity_check.go, erigon-lib/state/history.go
https://github.com/erigontech/erigon/issues/15531
- key issue: `iifCfg.name` (denoting inverted index) was not set properly when initializing InvertedIndex, leading to incorrect maps in entity_checker.
- other small changes: changed the `mirror-datadir` script to copy in parallel, make it fast; 
- consistency in comments and code in `UniversalEntity`
=> fix for stage_custom_trace failure after ii/hist dependency

core/vm/contracts.go, go.mod, go.sum
**Before**
```
Running tool: /usr/bin/go test -benchmem -run=^$ -bench ^BenchmarkPrecompiledBn256Add$ github.com/erigontech/erigon/core/vm -v
goos: linux
goarch: amd64
pkg: github.com/erigontech/erigon/core/vm
cpu: Intel(R) Core(TM) Ultra 5 135H
BenchmarkPrecompiledBn256Add
BenchmarkPrecompiledBn256Add/chfast1-Gas=150
BenchmarkPrecompiledBn256Add/chfast1-Gas=150-18 102675 11298 ns/op 150.0 gas/op 13.27 mgas/s 64 B/op 1 allocs/op
BenchmarkPrecompiledBn256Add/chfast2-Gas=150
BenchmarkPrecompiledBn256Add/chfast2-Gas=150-18 171644 9354 ns/op 150.0 gas/op 16.03 mgas/s 64 B/op 1 allocs/op
BenchmarkPrecompiledBn256Add/cdetrio1-Gas=150
BenchmarkPrecompiledBn256Add/cdetrio1-Gas=150-18 8909247 146.8 ns/op 150.0 gas/op 1022 mgas/s 64 B/op 1 allocs/op
BenchmarkPrecompiledBn256Add/cdetrio2-Gas=150 …
```
=> Change `bn256Add` to use consensys gnark-bn254 lib

.github/workflows/ci.yml, .github/workflows/qa-rpc-integration-tests.yml, .github/workflows/test-integration-caplin.yml, .github/workflows/test-integration-erigon.yml, erigon-lib/state/domain.go
maybe helps with recent tests scheduling flakiness
---
when new commits are pushed into PR, the job runs of previous commits of the PR (in particular, qa-rpc and integration tests) should be cancelled.
This already happens with ci test. Just adding it for other two workflows.
It's just something to save unnecessary job runs.
NOTE: this doesn't effect job runs on main branch or release branches (these are the branches on which the requirement to know "which commit broke a test" is needed)
=> cp: cancel previous job runs in integration and qa-rpc

core/vm/evm.go
Fixes #10594 
If the contract code cannot be saved into state because gas is not enough for covering the storage cost, we must return empty code both in pre-Homestead case (tx successful, but code not deployed => silent failure) and in post-Homestead case (tx failed, error store out-of-gas).
See also new RPC integration tests in https://github.com/erigontech/rpc-tests/pull/384
=> rpc: return empty code for store out-of-gas in CREATE calls

erigon-lib/common/dir/rw_dir.go
Backport of #15594. I guess just merge when/if people are happy with behaviour of patch on main.
(cherry picked from commit 4122f833cab250cc77fb214c9f7887036aa8aff3)
=> Backport: Fix datadir execution permissions for multi-user setups (#15594)

rpc/jsonrpc/bor_snapshot.go
Fixes https://github.com/erigontech/erigon/issues/15285 .
The previously used `ReadHeaderByNumber` function only used MDBX and was not aware of snapshots.
Now using blockReader the header can be properly read.
I will create another task to investigate more places where we rely on `ReadHeaderByNumber` to make sure we are not getting wrong results.
=> fix bor_getAuthor

cmd/integration/commands/flags.go, eth/backend.go, eth/ethconfig/config.go
Extra note:
EthMainnet: 45M
EthTestnets: 60M
BorChains: 45M
AuraChains: 17M
=> Added chain-specific gas limit defaults

.github/workflows/qa-rpc-integration-tests-polygon.yml, .github/workflows/qa-rpc-integration-tests.yml, .github/workflows/qa-rpc-performance-tests.yml, .github/workflows/qa-rpc-test-bisection-tool.yml, .github/workflows/qa-sync-test-bisection-tool.yml, .github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
1. avoid job name clash
2. add chain name to jobs
=> qa-tests: rename workflow jobs 

.github/workflows/qa-rpc-integration-tests.yml, .github/workflows/qa-rpc-performance-tests.yml, .github/workflows/qa-rpc-test-bisection-tool.yml, .github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
1. avoid job name clash
2. add chain name to jobs
(cherry picked from commit eb4c44b611bd17baa3f7b6e19dea8ba2990aa4b7)
=> [r30] qa-tests: rename workflow jobs  (#15488) 

cmd/integration/commands/stages.go, cmd/rpcdaemon/cli/config.go, cmd/rpcdaemon/rpcservices/eth_backend.go, cmd/state/commands/opcode_tracer.go, core/rawdb/accessors_chain_test.go, core/vm/gas_table_test.go, eth/integrity/e3_history_no_system_txs.go, eth/integrity/receipts_no_duplicates.go, eth/stagedsync/exec3.go, eth/stagedsync/stage_commit_rebuild.go, eth/stagedsync/stage_custom_trace.go, eth/stagedsync/stage_execute.go, eth/stagedsync/stage_snapshots.go, execution/exec3/historical_trace_worker.go, tests/state_test_util.go, turbo/app/snapshots_cmd.go, turbo/jsonrpc/debug_api.go, turbo/jsonrpc/eth_api_test.go, turbo/jsonrpc/receipts/bor_receipts_generator.go, turbo/jsonrpc/receipts/receipts_generator.go, turbo/rpchelper/helper.go, turbo/services/interfaces.go, turbo/snapshotsync/freezeblocks/block_reader.go, turbo/stages/mock/mock_sentry.go
issue: https://github.com/erigontech/erigon/issues/15593
- blockReader based txNumReader has cache..
- makes sense to have a single instance or a way to share the cache built in `txBlockIndexWithBlockReader`
=> share and use txnumreader cache via blockreader (#15597)

rpc/handler.go, rpc/http.go, rpc/json.go, rpc/server.go, rpc/server_test.go, rpc/testdata/invalid-nonobj.js
This PR contains fixes  in case malformed JSON returns "parse error" with httpStatus BadRequest(400) instead of OK(200)
=> rpcdaemon:  in case of ParseError set the HttpStatus to BadRequest as spec

cmd/downloader/main.go, cmd/snapshots/sync/sync.go, erigon-lib/chain/snapcfg/util.go, erigon-lib/downloader/downloader.go, erigon-lib/downloader/downloadercfg/downloadercfg.go, erigon-lib/downloader/util.go, erigon-lib/state/entity_extras/registry.go, erigon-lib/state/entity_extras/snap_config.go, eth/stagedsync/stage_snapshots.go, turbo/snapshotsync/snapshotsync.go
This is to complete an item from https://github.com/erigontech/erigon/pull/15043:
> Don't redownload files after preverified.toml is committed if they go missing. This occurs due to merges etc.
At node startup, the preverified.toml that was committed locally from a previous initial sync is scanned and the torrents in it are requested from the downloader. If in a previous run, torrents were removed due to merges, the torrents in the final snapshot will be added again (to my understanding). I can see two ways to deal with this:
1. Mark manually removed torrents with a file like name.removed, or
2. Once the preverified.toml is committed, don't request any torrents from it any longer.
The second option removes a lot of the logic from the downloader, where it doesn't belong. This PR implements …
=> Don't add preverified hashes after initial sync completed

erigon-lib/state/aggregator_test.go
somehow the previous pr got merged even after test failure
=> fix dependency test on windows

.github/workflows/qa-sync-from-scratch-minimal-node.yml
We need to wait for the snapshots to be recreated.
=> [r30] qa-tests: temporarily disable bor-mainnet from sync-from-scratch test 

polygon/sync/sync.go
This fixes an issue with erigon during the Heimdall v1->V2 migration where 
1. Erigon waits for hiemdall to get into sync - which is not going to happen for a potentially long period of time (several hours)
2. On syncing Erigon stalls because it can't fetch enough backward headers due to loack of milestones and checkpoints
=> Fix post hiemdall v2 sync stall

execution/eth1/forkchoice.go
protects the `limitedBigJump` calculation from a uint64 underflow 
e.g. there can be cases (for example on chains like bor) where the ufc header number is a few blocks less than the previous exec progress from the last ufc - if we are on block 10 on fork A but then block 9 on fork B appears with higher difficulty (or when we handle milestone mismatches for example we call ufc for the milestone finalised end block which can be ~16 blocks behind)
such an underflow can cause limitedBigJump to be set to `true` which then sets `IsInitialCycle=true` potentially causing furious/aggressive prunes on chain tip
=> execution: fix potential limitedBigJump calc uint underflow in updateForkChoice

txnprovider/txpool/txpoolcfg/txpoolcfg.go
As Fusaka will see massive increases - we make the assumptions that hardware now on average is better than 2 years ago and can handle it
=> txpool: Bump default txpool blob limits

erigon-db/downloader/downloader.go, erigon-db/go.mod, erigon-db/go.sum, go.mod, go.sum
Fix a concurrent map read/write spotted by @AskAlexSharov. It occurred in one of the three code paths that called into this function. I switched to an atomic Map, and cleaned up the file verification which I noticed could cause conceivably cause pieces to be indefinitely added to verification. Guarding by file should prevent that possibility. Atomic map might be overkill but there's very little synchronization required.
=> Fix concurrent map read/write and change to file verification

polygon/bridge/service.go
I am fixing this error:
```
[EROR] [06-27|13:28:09.522] background component error               err="pos sync failed: nonsequential block in bridge processing: 38189056 != 38189008"
```
It happens because we have dynamic sprint length in mainnet network:
```
"sprint": {
"0": 64,
"38189056": 16
},
```
When we apply the sprint length to the prev processed block - yweu should apply sprint length which this block was produced for
=> Fixed sprint length check in block processing

cl/phase1/stages/forward_sync.go
Basically do not download old blobs that are too old unless we are doing so by user request
fixes #15422
=> Caplin: skip DA checks on long distances 

.github/workflows/release.yml
For debian packages use commit suitable for the workflow in the release/3.0 branch
=> Fix release workflow dependency

cmd/rpctest/rpctest/bench_ethgetlogs.go, eth/integrity/receipts_no_duplicates.go, execution/stagedsync/stage_custom_trace.go
also, don't check `logIdx` in `ReceiptsNoDupsRange`; since final systemTx has logindex=0.
=> EthGetLogsInvariants: wait for pending work

cmd/evm/t8n_test.go, erigon-lib/common/race/race_disabled.go, erigon-lib/common/race/race_enabled.go, tests/bor/mining_test.go, txnprovider/shutter/block_building_integration_test.go
follow up from previous PRs - only skip tests on macos that are non compatible with the race detector (due to issue: https://github.com/erigontech/erigon/issues/15007) when the race detector is enabled - this allows us to still run these tests (without having to uncomment the skip) locally on macos when not in race mode
before:
```
➜ go test -v -count 1 -run '^TestShutterBlockBuilding' ./txnprovider/shutter
=== RUN   TestShutterBlockBuilding
block_building_integration_test.go:70: issue #15007
--- SKIP: TestShutterBlockBuilding (0.00s)
PASS
ok      github.com/erigontech/erigon/txnprovider/shutter        6.527s
```
after:
```
➜ go test -v -count 1 -run '^TestShutterBlockBuilding' ./txnprovider/shutter
=== RUN   TestShutterBlockBuilding/eon_1/build_shutter_block
=== NAME …
```
=> tests: disable non-compatible tests with race detector only when race mode is enabled

rpc/jsonrpc/tracing.go
This PR contains:
- align debug_traceCallMany() to debug_traceCall()
- avoid to load block with all txs and senders but only headers
-  debug_tarceCall use api that check before if the data are in the cache
=> rpcdaemon: use header instead of blockWithSenders() (debug_traceCall() debug_traceCallMany())

params/chainspecs/bor-mainnet.json
Move the `bhilaiBlock` to bor config instead of global in polygon mainnet genesis.
=> params: move bhilai fork to bor config

eth/integrity/receipts_no_duplicates.go
On sepolia's staging (`main`) integrity ReceiptsNoDups:
```
INFO[07-01|09:30:23.641] [integrity] ReceiptsNoDups starting      fromBlock=1 toBlock=8668050
INFO[07-01|10:21:49.795] [integrity] ReceiptsNoDups: done         err=nil
```
50 mins 
on this branch the same:
```
INFO[07-01|13:04:02.623] [integrity] ReceiptsNoDups starting      fromBlock=1 toBlock=8669114
INFO[07-01|13:07:06.487] [integrity] ReceiptsNoDups: done         err=nil
``` 
3 mins)
=> [r3.1] Big Beautiful Speedup (integrity ReceiptsNoDups)

erigon-lib/snaptype/type.go, polygon/heimdall/snapshot_store.go, polygon/heimdall/types.go, turbo/snapshotsync/freezeblocks/bor_snapshots.go
BorEvents snapshots contain incorrect txnhash values for every entity. This is because the snapshot generation during the retirement process was using the CanonicalHash read from the database. At the time the snapshot is produced (or regenerated), there is no guarantee that the hash is still present in the database. 
This PR fixes the issue: all canonical hash resolution now includes a lookup in the database first, and if the hash is not found, it falls back to checking the snapshots.
=> Fixed bor events snapshot retirement

go.mod, go.sum
This finishes out the pending tasks in https://github.com/erigontech/erigon/pull/15765.
> This moves performance from ~5-10MB/s up past the old limit of ~100-125MB/s to ~350+MB/s in my testing.
Performance remains high, it bounces between 200 and 450 MB/s in testing.
> In particular it's slow to finish up small files as it does requests on a timer.
Fixed.
> I haven't tested how it reacts to bad snapshots yet.
Still true.
> I haven't prune the boundaries of request extents to avoid a small amount of waste.
It now trims dirty chunks (already downloaded but not hashed) at the start of requests. Well tested.
> Webseed requests don't terminate early to avoid unnecessary downloads, they should just error out and then pick something else.
Requests are cancelled if it doesn't need the next chunks …
=> Pull finishing webseed tweaks from anacrolix/torrent

eth/backend.go, polygon/bor/bordb/prune.go, polygon/heimdall/entity_store.go, polygon/heimdall/snapshot_store.go, polygon/heimdall/types.go
Heimdall V2 upgrade resets milestone ID counter, which means we can not use anymore IDs for milestones before the upgrade. It also breaks our assumptions about the sequence of milestone IDs, which leads to performance issues (since we can not finalise the blocks and keep them much longer in memory).
This PR fixes the issue described above.
=> Removed milestones from snapshots scheme and and added pruning for milestones on start

rpc/contracts/direct_backend.go, rpc/jsonrpc/eth_api.go, rpc/jsonrpc/eth_api_test.go, rpc/jsonrpc/eth_call.go, rpc/jsonrpc/eth_call_test.go
In case the blockNum is not specified must be considered LatestBlock
closes #15793
=> rpcdaemon: fix eth_call without BlockNum

execution/stagedsync/stage_execute.go
sometimes on chain tip prune execution takes a long time (on my slow laptop's eth perfnet node I sometimes see 50s spent in pruning execution at chain tip) - adding these logs to pinpoint easily which part of the prune doesn't adhere to the 250ms timeout as a first step
=> execution/stagedsync: add debug timing logs to exec prune steps

rpc/rpchelper/helper.go
remove same check on 3.0
fixes #15632
=> rpcdaemon: remove check to avoid panic when access to Debug() method of KV remote

erigon-lib/etl/README.md
Old link pointed to incorrect path: /eth/stagedsync/
New link points to correct path: /execution/stagedsync/
The change ensures developers are directed to the right documentation.
=> Updated ETL framework documentation link in README.md

erigon-lib/recsplit/index.go, erigon-lib/recsplit/recsplit.go, erigon-lib/state/btree_index.go, erigon-lib/state/domain.go
- add version inside file header - `v0`
- prepare for future adding `v1`
PR is backward-compatible - no new functionality
this pr probably will go to `3.0` and `v1` will go to `main` - but will see (seems can release `v1` without re-sync)
related to: https://github.com/erigontech/erigon/issues/14371 and https://github.com/erigontech/erigon/issues/12852
`v1` likely will address 2 bottlenecks: txn_lookup_by_txn_hash, stage_history_get.
=> recsplit: add version inside file header

eth/integrity/receipts_no_duplicates.go
On sepolia's staging (`main`) integrity ReceiptsNoDups:
```
INFO[07-01|09:30:23.641] [integrity] ReceiptsNoDups starting      fromBlock=1 toBlock=8668050
INFO[07-01|10:21:49.795] [integrity] ReceiptsNoDups: done         err=nil
```
50 mins
on this branch the same:
```
INFO[07-01|13:04:02.623] [integrity] ReceiptsNoDups starting      fromBlock=1 toBlock=8669114
INFO[07-01|13:07:06.487] [integrity] ReceiptsNoDups: done         err=nil
```
3 mins)
Co-authored-by: JkLondon <ilya@mikheev.fun>
(cherry picked from commit a7697bde824b430a8e6e9f2694c6ede52d3276ec)
=> [r3.0] Big Beautiful Speedup (integrity ReceiptsNoDups) cp

erigon-db/rawdb/accessors_chain.go, erigon-lib/kv/kv_interface.go, erigon-lib/kv/remotedb/kv_remote.go, erigon-lib/kv/temporal/kv_temporal.go, erigon-lib/state/aggregator.go, erigon-lib/state/files_item.go, erigon-lib/state/kv_temporal_copy_test.go, erigon-lib/types/receipt.go, eth/integrity/integrity_action_type.go, eth/integrity/rcache_no_duplicates.go, eth/integrity/receipts_no_duplicates.go, rpc/jsonrpc/receipts/receipts_generator.go, turbo/app/snapshots_cmd.go
- checks invariants of rcache domain: around `logIndex` and cumulative gas 
- since logs are available in rcache, it can do stricter check of logIndex. (more than monotonically increasing).
- executes faster than `invariantsEthGetLogs`;  also it doesn't catch rcache error around expected firstLogIdx, which this integrity check does,
```
-> time ./build/bin/erigon seg integrity --check RCacheNoDups --datadir /erigon-data/sepoli
a_ethlogs3_crash
....
INFO[07-07|07:36:57.024] [integrity] progress                     progress=97.8%
INFO[07-07|07:37:17.040] [integrity] progress                     progress=98.3%
INFO[07-07|07:37:34.629] [integrity] RCacheNoDups: done           err="RCacheNoDups: non-monotonic logIndex at txnum: 582812500, block: 8637385(582812
459-582812725), logIdx=61, …
```
=> rcache integrity check

txnprovider/shutter/decryption_keys_listener.go
in case of connect err return early so that we dont increment `connected.Add(1)`
=> txnprovider/shutter: fix missing return on err in connectBootstrapNodes

core/state/intra_block_state.go, core/state_transition.go
The recover function in TransitionDB is specific to parallel processing
=> Add versioning check for recovery

erigon-lib/kv/remotedb/kv_remote.go, rpc/rpchelper/helper.go
Implemented the Debug() interface method on remoteKV to permit to re-enable test on pruning
=> rpcdaemon: Re enable test on pruning 

cmd/scripts/mirror-datadir.sh, execution/stagedsync/exec3_serial.go, turbo/snapshotsync/snapshotsync.go
- fast fail if fallback lastTx exec produces errors
- remove `adjustStepPrune` -- it's rounding "state prune point" to greater values for certain inputs. But now the logic needs to be more stringent as mechanisms like receipt fallback rely on history files being actually present. e.g. amoy has last state step 48, which was rounded to 64. 
issue: https://github.com/erigontech/erigon/issues/16004
=> relax state prune calculation in snapshot download

.github/workflows/scripts/run_rpc_tests_ethereum.sh
enable tests erigon_getHeaderByNumber () and erigon_getHeaderByHash() without Verkle fields
=> qa-tests: use 1.67 rpc-test version and enable erigon_getHeaderByHash and number

cmd/downloader/main.go, erigon-db/downloader/downloader.go
Panic introduced by https://github.com/erigontech/erigon/pull/15982, and route restored per https://github.com/erigontech/erigon/pull/15982#issuecomment-3048460301.
=> Fix panic in debug muxxing and restore GOPPROF handler route

erigon-lib/rlp/decode.go, erigon-lib/types/log.go, erigon-lib/types/receipt_test.go
real 20kb receipt from BorMainnet: 
```
from
51569 ns/op	  101299 B/op	    1395 allocs/op
to  
18759 ns/op	   37921 B/op	     304 allocs/op
```
it's small step towards rlpgen:
- introduced MoreDataInList and ReadBytes methods
- found that can pre-alloc: if list-item has known size. but attacker can craft big rlp prefix - and trigger huge pre-alloc. So, added limit.
=> rip: Log.DecodeRLP method

erigon-db/go.mod, erigon-db/go.sum, erigon-lib/common/debug/log_panic.go, erigon-lib/state/aggregator.go, go.mod, go.sum
Update golang.org/x/sync preemptively to avoid this breaking change in the future.
Worker functions added to sync.Group will need to defer RecoverPanicIntoError manually again.
Addresses https://github.com/erigontech/erigon/pull/15988#pullrequestreview-3005544729.
=> errgroup.PanicError was removed upstream

turbo/privateapi/ethbackend.go, turbo/snapshotsync/freezeblocks/block_reader.go
In case of block not found in remote configuration (grpc) the response was different (end of list in decoding) 
In case of txnHash not found in remote configuration (grpc) the response was different.
=> rpcdaemon: align response (block not found or txnHash not found) in case remote conf with local one (embedded or stand-alone) 

polygon/bridge/service.go
This will make the `TestService_ProcessNewBlocksWithOverride` test pass.
=> Fix endId calculation logic

erigon-lib/types/access_list_tx.go, erigon-lib/types/block.go, erigon-lib/types/bloom9.go, erigon-lib/types/encdec_test.go, erigon-lib/types/log.go, erigon-lib/types/receipt.go, erigon-lib/types/withdrawal.go
hope it will help for withdrawals - now their decoding is 25% of allocs
headers: 25 -> 15 allocs
=> rlp: use .ReadBytes() in other places

rpc/jsonrpc/eth_receipts.go
If an eth_getLogs() request specifies neither an address nor topics, and the requested range falls on a pruned state, an error is returned to the client. While if the request includes an address and/or topics, no error is returned; instead, an empty log array is provided, which means the client is not directly informed of the problematic request context (i.e., querying a pruned state).
This happens because reverse index returns en empty list therefore becomes empty logs
=> rpcdaemon: eth_getLogs(): add check on pruning

eth/backend.go
```
./build/bin/erigon --datadir /erigon-data/bormainnet31 --authrpc.jwtsecret /erigon-data/amoy31/jwt.hex  --prune.mode=minimal --chain=bor-mainnet --bor.heimdall="https://heimdall-api.polygon.technology" --log.console.verbosity=4 --torrent.download.rate=1g --pprof --pprof.port=6061 --http=false --txpool.disable --metrics --persist.receipts --db.pagesize=16kb > /erigon-logs/erigon-process.log 2>&1 &
panic: pattern "/downloader/torrentClientStatus" (registered at github.com/erigontech/erigon-db@v0.0.0-00010101000000-000000000000/downloader/downloader.go:1355) conflicts with pattern "/downloader/torrentClientStatus" (registered at github.com/erigontech/erigon-db@v0.0.0-00010101000000-000000000000/downloader/downloader.go:1353):
/downloader/torrentClientStatus matches the same requests as …
```
=> double register url in hot-fix

erigon-lib/Makefile, erigon-lib/direct/downloader_client.go, erigon-lib/gointerfaces/downloaderproto/downloader.pb.go, erigon-lib/gointerfaces/downloaderproto/downloader_client_mock.go, erigon-lib/gointerfaces/downloaderproto/downloader_grpc.pb.go
The command `make -C erigon-lib` fails after #15912 because of empty BUILD_TAGS in erigon-lib.
Changes:
- remove BUILD_TAGS from erigon-lib (not sure about this, do we need to pass them from command-line sometimes?)
- update some Downloader files after successful generation
=> erigon-lib: fix gRPC generation

execution/stages/genesis_test.go
issue: https://github.com/erigontech/erigon/issues/15976
can see from stacktrace that a temporaldb is closed, while salt is created by another goroutine. Better to use separate tmpdir since these are parallel tests.
=> resolve flaky TestSetupGenesis: different tmpdir for each parallel test

erigon-db/rawdb/accessors_chain.go
fixes:
```
[INFO] [07-14|10:52:37.471] [4/6 Execution Prune] pruning table periodic progress ChangeSets3=blockNum LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
```
=> erigon-db/rawdb: fix prune table periodic log

cmd/integration/commands/stages.go, erigon-lib/kv/table_sizes.go, eth/backend.go, execution/stagedsync/sync.go
in bloatnet we're exploding the chaindata db size up to 500GB on chain tip - something is not right
this PR aims to make it easy to see what is happening by adding periodic table size metric collection for grafana chart and debug logs (collect every 5 mins - configurable)
=> kv: add periodic table size metrics and logs

cmd/downloader/main.go, cmd/snapshots/sync/sync.go, erigon-db/downloader/downloadercfg/downloadercfg.go, erigon-db/downloader/util.go, erigon-lib/chain/snapcfg/util.go, eth/backend.go, execution/stagedsync/stage_snapshots.go, turbo/app/init_cmd.go, turbo/snapshotsync/freezeblocks/block_snapshots.go, turbo/snapshotsync/freezeblocks/caplin_snapshots.go, turbo/snapshotsync/freezeblocks/dump_test.go, turbo/snapshotsync/merger.go, turbo/snapshotsync/snapshots.go, turbo/snapshotsync/snapshots_test.go, turbo/snapshotsync/snapshotsync.go
closes https://github.com/erigontech/erigon/issues/15880
reverts https://github.com/erigontech/erigon/pull/15606
panic due to missing state salt file happened because the user run a testnet (e.g. with `--networkid=7032118028`) but they hadn't set `--no-downloader`
we can continue syncing even without `--no-downloader` (stage snapshots will be no-op since there is no snapshots toml file) so we should detect that and create the salt file on startup in this scenario
=> backend: create new salt file if unknown snap cfg for chain name

cmd/rpcdaemon/cli/config.go
`BridgeBackend` and `HeimdallBackend` are services specific to the Bor network, so `rpcdaemon` should check their version compatibility only on Bor chain.
Fixes #16049
=> rpcdaemon: check BridgeBackend version only on Bor network

ethstats/ethstats.go
Move the regex compilation for netstats URL parsing from the New function to the package level as a global variable. This avoids recompiling the regular expression on each function call, improving performance when the function is called multiple times.
=> ethstats: optimize regex compilation by moving it to package level

execution/stagedsync/metrics.go, execution/stagedsync/stage_finish.go
allows us to measure how long it takes us to do the initial sync
one metric that is good to have/requested for bloatnet
=> execution/stagedsync: measure time spent in initial cycle

rpc/jsonrpc/bor_snapshot.go
The header needs to be read by hash using `FullBlockReader` which has access to snapshots and MDBX, instead of `rawdb` which has access only to MDBX data.
This was fixed before when the input is a block number in https://github.com/erigontech/erigon/pull/15622 and in https://github.com/erigontech/erigon/pull/15630 .
This PR handles the case where the input is a block hash.
Issues fixed: 
- https://github.com/erigontech/erigon/issues/15285
- https://github.com/erigontech/erigon/issues/16020
=> Cherry-pick Fix bor_getAuthor by hash (#16121)

cmd/prometheus/dashboards/erigon_internals.json
state file timings dashboards weren't using histograms correctly - updated into the below
=> cmd/prometheus: update erigon_internals with new dashboards

erigon-db/downloader/downloader.go, erigon-db/downloader/downloader_grpc_server.go, erigon-db/downloader/util.go
solution for slow `[snapshots] initializing downloads       torrents=2724/7061`:
- probably there is some race between adding torrents and starting some background activities which taking mutex for long time. moving any line from `afterAdd()` to `addTorrentSpec` making  `initializing downloads` slow. 
- `ts.DisableInitialPieceCheck` - need initial check only if manual verification requested. 
- and seems this PR solving problem download-rate `1mb/s` -> ` 126MB/s` (non-header-chain). (monitoring of machine shows 1gb/s - but it's another story. rclone shows 600mb/s).
example of race: 
- if web seeds list came from trackers first - then `t.AddWebSeeds` will ignore `opts`. (no solution in this PR)
- probably there are more logical races (this is reason why this PR helps)
=> [r31] downloader: inverse verify flag use

.github/workflows/qa-clean-exit-block-downloading.yml, .github/workflows/qa-constrained-tip-tracking.yml, .github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
The new test scheduling policy, which is made up of a combination of two labels ('chain' and 'test-type'), failed to address the tip-tracking tests.
This PR fixes this issue.
=> qa-tests: fix tip-tracking scheduling

.github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
The tip-tracking test has been superseded by the sync-from-scratch test that is a sync from scratch plus a tip tracking, running erigon for 2 hours on the tip. 
The tip-tracking test requires a pre-built database, and it is difficult to ensure the correct database while there are many backward incompatible changes on the main and release branches (MDBx versions, new tables, different snapshot formats, etc.).
We will therefore transform the tip-tracking test into a "migrate + tip-tracking" to test the migration procedure from Release 3.0 to Release 3.1.
This PR remove the test scheduling from the main branch.
=> qa-tests: de-schedule tip-tracking

.github/workflows/qa-clean-exit-block-downloading.yml, .github/workflows/qa-constrained-tip-tracking.yml, .github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
This PR address 2 tip-tracking issues:
1) The new test scheduling policy, which is made up of a combination of two labels ('chain' and 'test-type'), failed to address the tip-tracking tests. This PR fixes this issue.
2) The tip-tracking test has been superseded by the sync-from-scratch test that is a sync from scratch plus a tip tracking, running erigon for 2 hours on the tip.
The tip-tracking test requires a pre-built database, and it is difficult to ensure the correct database while there are many backward incompatible changes on the main and release branches (MDBx versions, new tables, different snapshot formats, etc.).
We will therefore transform the tip-tracking test into a "migrate + tip-tracking" to test the migration procedure from Release 3.0 to Release 3.1.
This PR add the …
=> [r31] qa-tests: add migration procedure to the tip-tracking test

erigon-lib/state/commitment_context.go
allows to correctly dereference values during read from commitment history while building proof trie
=> Fix eth_getProof on hisotry values

polygon/bridge/service.go
Cherry pick of this commit: https://github.com/erigontech/erigon/pull/16226
=> Added validation of ordering and consistency for state sync events inside the scraper

.github/workflows/release.yml
It should protect release workflow from potential dependency issues in the future releases 3.1.x
=> Update release.yml - debian package dependency

core/state_processor.go, core/vm/evm.go, execution/stages/mock/mock_sentry.go, p2p/sentry/sentry_multi_client/sentry_multi_client.go, rpc/jsonrpc/eth_api.go, rpc/jsonrpc/receipts/handler_test.go, rpc/jsonrpc/receipts/receipts_generator.go, turbo/transactions/tracing.go, txnprovider/shutter/block_building_integration_test.go
without this pr - very long `debug_traceCall` can cause DB grow
---------
(cherry picked from commit b1ab89c178c1af65d35db218047cfdfea8aa7996)
=> [r31 branch] receipt_generator: follow --rpc.evmtimeout

.github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
The tip-tracking test currently use a `seg reset` command before running. 
This PR change "seg reset" with the more conservative `seg update-to-new-ver-format` which is the method we expect to work for almost all customers and which is preferable because it is less expensive.
=> [r31] qa-tests: tip-tracking with seg update

erigon-lib/kv/mdbx/kv_mdbx.go
reverts:
- https://github.com/erigontech/erigon/commit/b937120bb0c8596a0bcb715e3020a146e3162cc5
- https://github.com/erigontech/erigon/commit/c9480171d183bfef915c324071a243bf09b226ad
- https://github.com/erigontech/erigon/commit/9e8ecf229f4958ed0ad05adad648a456609cae36
- https://github.com/erigontech/erigon/commit/31551783c6b359efa2d071dbcef8f643328a0de5
kurtosis crashes with 3 different types of errors (vary per occasion) but all due to the `PeriodicFlusher`:
- ```mdbx:20786: dxb_sync_locked: Assertion `target == head.ptr_c || constmeta_txnid(target) < pending->unsafe_txnid' failed.```
- ```mdbx:20743: dxb_sync_locked: Assertion `legal4overwrite' failed.```
- ```Assertion failed: legal4overwrite (mdbx: dxb_sync_locked: 20743)```
Sample full error:
```
[el-08-erigon-lighthouse] Assertion …
```
=> kv/mdbx: revert nosync periodic flusher

rpc/batch_limit_ws_test.go, rpc/client.go, rpc/server.go
- Extends the existing `--rpc.batch.limit` flag to WebSocket and IPC connections
- Previously, batch size limits were only enforced for HTTP connections
- Adds consistent batch limit enforcement across all RPC transport methods
1. **Modified `rpc/client.go`**:
- Added `batchLimit` field to the `Client` struct
- Implemented batch size check in the `dispatch` method for WebSocket/IPC connections
- When limit is exceeded: logs warning, sends error response, and closes connection
2. **Modified `rpc/server.go`**:
- Updated `initClient` call to pass `batchLimit` parameter for WebSocket/IPC connections
3. **Added `rpc/batch_limit_ws_test.go`**:
- New test to verify batch limit enforcement for WebSocket connections
- Tests that batches exceeding the limit result in connection closure
- When a …
=> rpc: Apply batch limit to WebSocket/IPC connections

erigon-lib/commitment/hex_patricia_hashed.go, erigon-lib/commitment/hex_patricia_hashed_test.go, rpc/jsonrpc/eth_call_test.go
Successor of https://github.com/erigontech/erigon/pull/16011
+ storage singleton
+ bunch of accounts with common prefix
+ storages with common prefix before first branch
+ witness tracing
+ optional memoisation in commitment , disabled memoisation for proofs
=> Fix `getProof` edge cases correctly

core/gdbme/gdbme_darwin.go
**Description:**  
This PR improves reliability by checking and handling errors not only when writing, but also when closing the temporary file for the LLDB script. This prevents silent failures in case the file is not fully written to disk due to system issues.
=> Properly handle file close errors when writing LLDB script

erigon-lib/state/commitment_context.go
allows to correctly dereference values during read from commitment history while building proof trie
=> Cherry-pick: fix `eth_getProof` for historical values

cmd/utils/flags.go
because limits of ethmainnet are growing: can have hundreds of kb code/txn
=> [r30] increase default `--db.pageSize` to 16kb

cmd/integration/commands/flags.go, cmd/integration/commands/stages.go, cmd/integration/commands/state_stages.go, cmd/snapshots/genfromrpc/genfromrpc.go, cmd/utils/flags.go, eth/backend.go, eth/ethconfig/config.go, execution/stagedsync/exec3.go, execution/stagedsync/stage_headers.go, execution/stages/headerdownload/header_algos.go, execution/stages/mock/mock_sentry.go, execution/stages/stageloop.go, turbo/app/snapshots_cmd.go, turbo/cli/default_flags.go, turbo/cli/flags.go, turbo/snapshotsync/freezeblocks/block_snapshots.go
so until sequencer feed is not done, rely on fetching blocks and transactions from external L2 (pruned node is fine) RPC. 
New flag for erigon: `--l2rpc` allows to pass a host for rpc queries called in Headers stage and then triggering dump blocks and execution.
=> Chain tip arbitrum testnet

.github/workflows/qa-rpc-integration-tests-polygon.yml
For disk space reasons, we are disabling tests on the 3.0 branch on the test runner.
=> [r30] qa-tests: disable rpc integration tests on polygon 

README.md
Update upgrade documentation to avoid possible reset of old snapshot files.
=> Clarify snapshots reset before file naming update

core/blockchain.go, core/state_transition.go, erigon-lib/state/version_schema.go, erigon-lib/version/file_version.go, execution/exec3/historical_trace_worker.go, execution/exec3/state.go, rpc/jsonrpc/trace_filtering.go
issue: https://github.com/erigontech/erigon/issues/16339
- enable tracer in final tx exec (for tracesfrom/tracesto)
- use `ibs.SetTxContext` in final tx exec: this was causing txTask.Logs to be incorrectly set to nil. 
- remove unused hooks/tracers from fn signatures
- need to regen files after this -- logaddrs/logtopics/tracesfrom/tracesto/receipts.
=> fix polygon's ii and receipt values for system tx

core/vm/contracts_test.go
This enables benchmarking the PointEvaluation precompile similarly to every other precompile.
=> core: add benchmark for PointEvaluation

polygon/bor/bor.go, polygon/bor/bor_internal_test.go
This removes dead code from `bor.go` (primarily `bor.snapshot()` which is no longer used in any flow), and also removes the `useSpanReader` flag, as the span reader is always used.
=> Remove dead code from `bor.go`

execution/builder/block_builder.go, execution/eth1/block_building.go, execution/stagedsync/stage_mining_exec.go
Test `"Blob Transaction Ordering, Multiple Clients (Cancun) (erigon)"` is flaky (example run - https://github.com/erigontech/erigon/actions/runs/16647657985/job/47112094838)
the test setup is:
- 2 EL clients
- some blob txns are sent to client A others to client B
- after they are all sent, payloads are built by client A
- expectation is that each block will have 6 blob txns included
we flake because:
- we stop block building when the txpool dries out
- in the test the time between FCU and GetPayload is 2 seconds
- we do not wait the full 2 seconds
- sometimes we get the blob txns in time, other times we dont (depends on txpool propagation delay which can vary depending on hardware/resource consumption on the machine, note we run with --sim.parallelism 8 which can also affect this)
- if …
=> execution/builder: keep polling dry txnpool for txns until we are interrupted

turbo/snapshotsync/freezeblocks/dump_test.go
we recently merged https://github.com/erigontech/erigon/pull/16268 which should fix the flaky test - let's give it a try and see how it goes
=> turbo/snapshotsync: re-enable TestDump

eth/integrity/integrity_action_type.go
snapshotters always have rcache; 
lets do this, so integrity command becomes simpler as well
=> [r31] move RCacheNoDups into default integrity

erigon-lib/state/domain.go
on crash, recover sets error which is not surfaced; using named return value surfaces the recover-set-err.
=> [r31] surface drowning error in accessor building

eth/integrity/integrity_action_type.go
snapshotters always have rcache;
lets do this, so integrity command becomes simpler as well
=> cp: move RCacheNoDups into default integrity

README.md
This matches what we already have in some snapshotters after the previous recommendation failed short.
=> Update advised max memory regions/process

erigon-lib/chain/snapcfg/util.go, erigon-lib/version/app.go
Default is release/3.1
Will add snapshots into this branch as a part of next snapshot publication.
=> Arb: use main branch for snapshot delivery

erigon-lib/common/datadir/dirs.go, erigon-lib/common/datadir/dirs_test.go, turbo/app/snapshots_cmd.go
If you downgrade after running node on old files for some time (i.e. until chaintip) erigon will create by itself some new files with new versions. So, the downgrade from that point w/o delete this files is impossible. FYI @AskAlexSharov
=> [r3.1] downgrade now remove new version unsupported files

db/downloader/downloader.go, go.mod, go.sum
Also pulls change in anacrolix/torrent to be less pedantic about chunk size when adding torrents that already exist in the client.
Fixes #16481.
Needs to be cherry-picked to 3.1 after merge.
=> AddNewSeedableFile was skipping lock and bypassing checks

erigon-lib/common/dbg/experiments.go
snapshotters have gaps. Need to find where they're getting deleted from
=> enable trace deletion

db/snapcfg/util.go
in `integrateMergedDirtyFiles`, non-frozen files before "new merged 100k file (frozen)" is collected for deletion. This caused deletion of 500k files which was merged offline. These ranges in preverified.toml are still 100k and `isFrozen` is strict. 
This PR extends the definition of `isFrozen`.
=> fix 500k file deletion on snapshotters

cmd/utils/flags.go, db/downloader/downloadercfg/downloadercfg.go, db/snapcfg/util.go, go.mod, go.sum
Modifies `--webseed` to set the webseeds to *only* those URLs. Fixes anacrolix/torrent from automatically merging in webseeds from metainfos which made `--webseed` unreliable.
ERIGON_REMOTE_PREVERIFIED is the location of a file that contains preverified snapshot hashes. It is returned for all chains rather than using R2 or GitHub. Very useful for testing webseeds among other things.
=> Support overriding remote preverified hashes and clobbering webseeds

cl/sentinel/sentinel_requests_test.go
Removes t.Skip from TestSentinelStatusRequest and fixes unreachable code issue in error handling. The test was previously skipped due to incorrect error handling pattern where return statement made require.NoError unreachable.
=> Fix TestSentinelStatusRequest: remove skip and fix unreachable code

eth/integrity/bor_snapshots.go, turbo/app/snapshots_cmd.go, turbo/snapshotsync/freezeblocks/block_snapshots.go
getting "temporarily unavailable" heimdall store error because it was opened twice (once in `openSnaps` then in `ValidateBorSpans` etc.)
=> reuse already prepared heimdall store in integrity check

turbo/app/snapshots_cmd.go
Follow up to https://github.com/erigontech/erigon/pull/16620
I did not noticed that there were auto merge enabled so left comment and Accepted PR just to avoid further blocking. Here is missing fixes.
=> [r31] fix wrong `hasRoot=true` during check on commitment state key

erigon-db/downloader/downloader.go
Prevent torrents being added from disk and due to Downloader's special expectations around `.torrent` files from adding a torrent back in before the delete is complete.
=> Delete torrent file before dropping

erigon-lib/state/aggregator_test.go, erigon-lib/state/files_item.go, execution/stagedsync/stage_snapshots.go, turbo/app/snapshots_cmd.go, turbo/snapshotsync/freezeblocks/block_snapshots.go, turbo/snapshotsync/merger.go, turbo/snapshotsync/snapshots.go, turbo/snapshotsync/snapshots_test.go
- also `RemoveOverlaps` didn't call onDelete
- closing https://github.com/erigontech/erigon/issues/16658
=> [r31] `downloader.Delete`: `.idx` files are missed

txnprovider/provider.go, txnprovider/shutter/pool.go, txnprovider/shutter/pool_test.go, txnprovider/txpool/pool.go
cherry-pick 2437ffa
---
found that there is a discrepancy in logic in how the the txn ids filter option is handled in shutter and devp2p pool:
- shutter expects the caller to populate the filter with yielded transactions
- devp2p pool fills the filter with the yielded transactions itself
- this PR changes the shutter logic to follow the devp2p pool logic
- additionally fixes the default - original intention was for it to be none by default but that change was forgotten (all prod code paths use a filter option so no logical change here)
=> txnprovider: align txns id filter behaviour between devp2p pool and shutter (#16646)

erigon-db/rawdb/rawtemporaldb/accessors_receipt.go, erigon-lib/state/aggregator2.go, erigon-lib/state/aggregator_test.go
- v1.0 -> v2.0  is a breaking change. It causes a change in interpretation of "logFirstIdx" stored in receipt domain.
- We wanted backwards compatibility however, so that was done with if checks, See `ReceiptStoresFirstLogIdx`
- This brings problem that data coming from v1.0 vs v2.0 is interpreted by app in different ways,
and so the version needs to be floated up to the application.
- So to simplify matters, we need to do- v1.0 files, if it appears, must appear alone (no v2.0 etc.)
- This function updates current version to v1.1  (to differentiate file created from 3.0 vs 3.1 erigon)
issue: https://github.com/erigontech/erigon/issues/16293
closes: https://github.com/erigontech/erigon/issues/16647
=> adjust receipt data files version

eth/backend.go
This reverts commit https://github.com/erigontech/erigon/commit/26d43d57e2c080f8bdf58eaae5348f418248d29e.
We can't use `engine.Start` at the moment because currently Astrid manages when the Execution loop gets called. It makes sure that all relevant data from heimdall has been scraped and is available - via the BridgeService and HeimdallService. 
The problem with calling `engine.Start` is that it completely circumvents the synchronisation logic that Astrid has to ensure that all relevant data is pre-fetched and ready before we call Execution (i.e. `ProcessFrozenBlocks` does not have any waiting logic as Astrid does before calling `UpdateForkChoice`) - Elton run into a problem as a result of this.
Additionally, calling `engine.Start` and `ProccesFrozenBlocks` is no longer necessary after …
=> Revert "polygon: use execution server start (#16485)"

txnprovider/txpool/pool.go
part of https://github.com/erigontech/erigon/issues/14413
- in commit a149cbf53fd674a354bc3b5f0e1e8a79eb38cb85 I added a goroutine dump just before the test timeout is reached to help spot a deadlock
- the following [CI run](https://github.com/erigontech/erigon/actions/runs/16985462951/job/48153373260) failed and the goroutine dump was printed 5 secs before the test ctx was cancelled (due to the timeout) - so it captured everything nicely (look for `goroutine dump timer expired` in the logs)
we can see that:
- `p.best` has acquired `p.lock` but it is waiting on acquiring the `poolDB.BeginRo` semaphore which has a limit of `runtime.GOMAXPROCS(-1) * 16` (search for `(*TxPool).best` in the dump)
- there are 64 goroutines that have acquired a `poolDB.RoTx` (via `poolDB.View`) but are waiting …
=> txnprovider/txpool: fix deadlock

.github/workflows/qa-rpc-integration-tests-gnosis.yml, .github/workflows/qa-rpc-integration-tests-polygon.yml, .github/workflows/qa-rpc-integration-tests.yml
Making changes to MDBX tables does not result in failing RPC tests.
=> workflows: Run `run_migrations` before running RPC tests

.github/workflows/qa-rpc-performance-tests.yml
Ignore connection errors returned by Vegeta load testing tool if success rate is still 100%
=> qa-tests: less strict error handling in RPC Performance Tests

db/downloader/downloader.go, db/snapcfg/util.go, eth/backend.go
- **Fix snapshot overriding (#16624)**
- **Require torrents added from disk to complete on `downloader.verify` (#16655)**
=> Cherry pick snapshot overriding and downloader.verify fixes from 3.1

.github/workflows/qa-tip-tracking.yml
The latest "tip-tracking & migration" executions show that it takes more than ten hours to run two erigon cycles, so this PR raises the timeout to more than 16 hours (8 hours are expected per cycle).
Furthermore, when the test is cancelled due to a timeout, GitHub displays a grey icon, which is misleading. This PR should change it to red, forcing a check to be performed. The error condition deliberately treats false positives as errors, i.e. the test not being performed on erigon during upgrades and downgrades.
=> [r3.1] qa-tests: improve tip-tracking timeout and error reporting 

polygon/heimdall/snapshot_store_test.go, polygon/heimdall/span_range_index.go, polygon/heimdall/span_range_index_test.go
Follow-up to : https://github.com/erigontech/erigon/pull/16683
The previous PR relied on the assumption that `span.StartBlock` is monotonically increasing, but it turns out that assumption is not true due to a future span being announced in advance from Heimdall and a span rotation taking place before the announced span.
e.g.
```Go
var spans = []Span{
Span{
Id:         0,
StartBlock: 0,
EndBlock:   999,
},
Span{
Id:         1, // new span announced
StartBlock: 1000,
EndBlock:   1999,
},
Span{
Id:         2, // span rotation
StartBlock: 5,
EndBlock:   1999,
},
}
```
Therefore, this PR adapts the lookup algorithm by starting the search from `entry := cursor.Seek(blockNum)` and walking the `BorSpans` table backwards using `cursor.Prev()` while recording the highest span id which is in range, …
=> VeBlop: Update span index lookup and add more unit tests

turbo/app/snapshots_cmd.go
- checks file size, and recsplit components size (golombRice encoding, existence etc.)
- compares offsets; but doesn't compare offsets  for non-ordinal keys (hashes)
- if enums=true, compares ordinal lookup values
=> tool to compare recplit files

turbo/app/snapshots_cmd.go
- issue: https://github.com/erigontech/erigon/issues/16767
- when `rm-state --domain=rcache` etc. provided, commitment state key is still checked and some logs done around that. This PR avoids it.
```
./build/bin/erigon seg rm-state --datadir /erigon-data/chiado --domain=rcache,receipt
INFO[08-22|06:39:19.426] logging to file system                   log dir=/home/erigon/.local/share/erigon/logs file prefix=erigon log level=info json=false
found state key with kvi /erigon-data/chiado/snapshots/domain/v1.1-commitment.0-32.kv
found state key with kvi /erigon-data/chiado/snapshots/domain/v1.1-commitment.32-34.kv
removed 52 state snapshot segments files
```
=> [r31] avoid extraneous commitment logs in rm-state

execution/eth1/inserters.go
Correct error message function references from "InsertHeaders" to "InsertBlocks"
in three locations to match the actual function name.
=> fix: align error messages with function name in InsertBlocks

polygon/bridge/mdbx_store.go
it was causing `seg retire` to just continue looping on prune
=> [r31] fix for bor events prune

eth/integrity/e3_history_no_system_txs.go
- use txNumReader.FindBlockNumber/max/min judiciously
- time taken on bor down from 20m+ to 1m.
=> faster HistoryNoSystemTxs integrity check

execution/exec3/historical_trace_worker.go, execution/exec3/state.go
Fix two issues in AA transaction execution:
1. Add missing return statement after setting txTask.Error when 
ValidationResults is empty to prevent panic from accessing 
empty slice and type assertion
2. Fix negative length calculation in "validated AA bundle" log 
from (startIdx-endIdx) to (endIdx-startIdx+1)
=> fix: add missing return and fix AA bundle length log in execAATxn

polygon/heimdall/entity_fetcher.go
Due the Veblop hard fork the span sorting by `span.StartBlock` does not make sense because the `StartBlock` will not be strictly increasing. The sorting by `StartBlock` resulted in a span id gap in `ObserveSpan()` due to a span with a lower Id but higher StartBlock being relocated to higher indexes in the sorted array of fetched spans.
Therefore, this PR disables the sorting, and just relies on the `span.Id` for the order.
=> VeBlop: Skip span sorting by StartBlock in EntityFetcher

.github/workflows/scripts/test_report/generate-test-report.ts
Canceled test run with steps are not timed-out
=> qa-test: improve test report (handle canceled with steps status)

rpc/batch_limit_ws_test.go, rpc/client.go
=> tests: fix deadlock in TestBatchLimit_WebSocket_Exceeded on macOS

db/kv/tables.go, db/state/aggregator.go, db/state/aggregator2.go, db/state/aggregator_debug.go, db/state/aggregator_test.go, db/state/btree_index.go, db/state/btree_index_test.go, db/state/dirty_files.go, db/state/domain.go, db/state/domain_committed.go, db/state/domain_stream.go, db/state/domain_test.go, db/state/entity_integrity_check.go, db/state/history.go, db/state/history_test.go, db/state/integrity_checker_test.go, db/state/inverted_index.go, db/state/inverted_index_stream.go, db/state/inverted_index_test.go, db/state/merge.go, db/state/merge_test.go, db/state/snap_repo.go, db/state/snap_repo_test.go, db/state/snap_schema.go, db/state/snap_schema_test.go, db/state/statecfg/accessors.go, db/state/statecfg/statecfg.go, db/state/version_schema.go, turbo/app/snapshots_cmd.go
moved `salt` out of config objects 
and `dirs` too (not compile-time-known field)
=> agg: configs immutability

.github/workflows/qa-constrained-tip-tracking.yml, .github/workflows/qa-snap-download.yml, .github/workflows/qa-sync-from-scratch-minimal-node.yml, .github/workflows/qa-sync-from-scratch.yml, .github/workflows/qa-sync-with-externalcl.yml, .github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking-polygon.yml, .github/workflows/qa-tip-tracking.yml
From QA meeting, we're missing the torrent logs for a snapshot download CI stalling.
=> Upload all logs generated by erigon node in CI

turbo/snapshotsync/snapshotsync.go
fixes https://github.com/erigontech/erigon/issues/16852
checking the `blackListForPruning` was accidentally removed in https://github.com/erigontech/erigon/pull/16648
diff of Downloader.Add logs (before/after fix): https://www.diffchecker.com/MoE9EsyG/
=> snapshotsync: fix minimal nodes downloading all snapshots

polygon/heimdall/service.go
Cherr-pick of https://github.com/erigontech/erigon/pull/16877
Per VeBlop specs (https://hackmd.io/pG_1DC3YSoaFTOngy92ffw) the span check interval is 200 ms.
=> cherry-pick: VeBlop: change span scraper timeout to 200 ms (#16877)

eth/stagedsync/stage_polygon_sync.go, polygon/sync/service.go, polygon/sync/sync.go, polygon/sync/tip_events.go
If the tip is behind the milestone end, then this triggers an unwind to the previous verified milestone and download of blocks from previous verified milestone block until new milestone end block. 
This is unnecessary since we can put the milestone back in the event queue, and it will be picked up later, and hopefully by that time the tip will be in sync with milestone. This is expected to reduce the number of unwinds.
=> Do not apply milestone if tip is behind it

db/state/aggregator.go, db/state/dirty_files.go, db/state/domain.go, db/state/domain_test.go, db/state/history.go, db/state/history_test.go, db/state/inverted_index.go, db/state/inverted_index_test.go, execution/stages/mock/mock_sentry.go, tests/block_test_util.go
now agg does scandir for each domain/ii. but once per agg.OpenFolder() is enough. 
it was 8% of `go test -run=TestLegacyBlockchain`
next bottlenecks are: `BlockTest.Run -> mock.Mock -> datadir.New -> MkdirAll` and `memdb.Close -> RemoveAll`
=> tests: remove `agg scandir` bottleneck

db/recsplit/eliasfano16/elias_fano_fuzz_test.go, db/recsplit/eliasfano32/elias_fano_fuzz_test.go, db/recsplit/recsplit_fuzz_test.go, db/seg/compress_fuzz_test.go, db/seg/patricia/patricia_fuzz_test.go, db/state/aggregator_fuzz_test.go, erigon-lib/Makefile, execution/commitment/hex_patricia_hashed_fuzz_test.go, txnprovider/txpool/pool_fuzz_test.go, txnprovider/txpool/pool_txn_packets_fuzz_test.go, txnprovider/txpool/pool_txn_types_fuzz_test.go
fuzz tests in normal during tests runs - do not fuzz (do not do heavy) - but do run known test-cases (from saved testdata)
so, in my head it must not impact `-race` or `-short` speed
=> remove `nofuzz` build tag

turbo/snapshotsync/freezeblocks/block_snapshots.go
FrozenBorBlocks is used to calculate blockFrom number to use it as a left-end interval in block retirement process. The thing is - this function returns the highest known block in snapshots among bor related snapshots. For example if you have 3 snapshots:
```
1000-2000.spans
1000-2000.events
0000-1000.checkpoints
```
it returns 1999. And in that case we will never retire correctly checkpoints in interval [0000, 1000). It is possible that bor snapshots have different height, that's why using FrozenBorBlocks in a way like it did is wrong. 
In previous my PRs I was fixing the similar problem which was causing race condition in block pruning. I introduced parameter align for the function, which changes it behaviour to return not just the highest block, but the highest aligned. In the example …
=> Fixed calculation of start block number in snapshot retirement

.github/workflows/qa-tip-tracking.yml, erigon-lib/common/datadir/dirs.go, erigon-lib/state/domain.go, turbo/app/reset-datadir.go, turbo/app/snapshots_cmd.go
- Handles missing or obsolete format chaindata (Fixes #16717 and https://discord.com/channels/1133875232453693480/1356926710502916096/1407195677930295348).
- Fixes double logging setup (observed on Discord a few times but I missed it).
- Correctly loads _explicit_ chain flag "IsSet" setup from parent CLI contexts.
- Logs datadir operated on (so default datadir action is clear).
=> Improve snapshots reset action

cmd/integration/commands/stages.go, cmd/rpctest/main.go, erigon-lib/datastruct/existence/existence_filter.go, erigon-lib/datastruct/fusefilter/fusefilter_reader.go, erigon-lib/recsplit/index.go, erigon-lib/state/domain.go, erigon-lib/state/history.go, erigon-lib/state/integrity.go, erigon-lib/state/inverted_index.go, erigon-lib/state/merge.go
We may experiment with MADV_WILL_NEED in future versions of Erigon
Reason: without it perf of commitment is much lower (Mark reported 10x slowdown).
Cons: +1G RAM use by Erigon
=>  [r31] fuse_filter: keep in app's memory instead of `mmap` 

polygon/bridge/mdbx_store.go
it was causing `seg retire` to just continue looping on prune
=> cp: fix for bor events prune

turbo/snapshotsync/freezeblocks/block_snapshots.go
FrozenBorBlocks is used to calculate blockFrom number to use it as a left-end interval in block retirement process. The thing is - this function returns the highest known block in snapshots among bor related snapshots. For example if you have 3 snapshots:
```
1000-2000.spans
1000-2000.events
0000-1000.checkpoints
```
it returns 1999. And in that case we will never retire correctly checkpoints in interval [0000, 1000). It is possible that bor snapshots have different height, that's why using FrozenBorBlocks in a way like it did is wrong.
In previous my PRs I was fixing the similar problem which was causing race condition in block pruning. I introduced parameter align for the function, which changes it behaviour to return not just the highest block, but the highest aligned. In the example …
=> Fixed calculation of start block number in snapshot retirement (#16902)

rpc/jsonrpc/receipts/receipts_generator.go
Assign correctly the receipt.FirstLogIndexWithinBlock when the receipt contains zero logs to avoid panic() if ASSERT_ERIGON is enabled
=> rpcdaemon: fix to avoid panic()  on receipts log index when ASSERT_ERIGON is enabled

core/state/cached_reader3.go
Fix error handling in CachedReader3.ReadAccountCode
- Add proper error validation before length check
- Return code with nil error instead of code with error
- Align with Go error handling principles and other implementations
=> fix: correct error handling in CachedReader3.ReadAccountCode

core/state/intra_block_state.go, rpc/jsonrpc/eth_call.go
fixing this
https://github.com/erigontech/nitro-erigon/issues/247
Passing `common.Num0` by reference to `ArbitrumExtraData` could overwrite it (turning 0 into something else), which breaks things.
=> fix node failure after eth_call with state override

core/vm/testdata/precompiles/modexp_eip2565.json
Originally added to EEST in
https://github.com/ethereum/execution-spec-tests/pull/2052.
=> core/vm: add one more modexp benchmark

db/etl/collector.go
Fixed a bug in the ETL collector's flushBuffer method where the wrong buffer reference was used when creating a new buffer for background flushing operations. The code was incorrectly using c.buf.SizeLimit() instead of fullBuf.SizeLimit(), which could result in creating buffers with incorrect size limits when sortAndFlushInBackground is enabled. This fix ensures proper buffer size allocation and prevents potential performance degradation or memory allocation issues during ETL operations.
=> fix(etl): use correct buffer size when creating new buffer in background flush

rpc/jsonrpc/receipts/bor_receipts_generator.go
https://github.com/erigontech/erigon/issues/16944
=> handles a bug in receipt values when there's only 1 tx in the block (query only)

cl/sentinel/handlers/handlers.go
Our current timeouts cause some minor memory spikes. better limit them properly
=> Caplin: add stricter timeouts to p2p handling

cl/rpc/rpc.go
I think it is buggy, it causes us to lose sync sometimes. let's keep it simple and fix later
=> Caplin: disable queue based peer selection

cmd/evm/README.md
Fix broken link to fork configurations - point to execution/testutil/forks.go
instead of non-existent tests/init.go.
=> fix: correct path to fork configurations in EVM README

cmd/integration/commands/stages.go, cmd/utils/flags.go, db/kv/kv_interface.go, db/kv/remotedb/kv_remote.go, db/kv/temporal/kv_temporal.go, db/rawdb/rawtemporaldb/accessors_commitment.go, db/rawdb/rawtemporaldb/accessors_receipt_test.go, db/state/aggregator.go, db/state/aggregator_test.go, db/state/changeset/state_changeset.go, db/state/changeset/state_changeset_test.go, db/state/domain.go, db/state/domain_committed.go, db/state/domain_shared.go, db/state/domain_shared_test.go, db/state/domain_test.go, db/state/history_test.go, db/state/merge.go, db/state/metrics.go, db/state/squeeze.go, db/state/squeeze_test.go, db/state/temporal_mem_batch.go, eth/ethconfig/config.go, execution/commitment/commitmentdb/commitment_context.go, execution/commitment/commitmentdb/commitment_context_test.go, execution/eth1/forkchoice.go, execution/stagedsync/exec3.go, execution/stagedsync/stage_execute.go, execution/stagedsync/sync.go
- move `changeset` from `state` to own package
- move `commitment_context.go` to `execution/commitmentdb` package
- move remove Unwind methods from `Agg` - because they did contain biz-logic (serialization format of Commitment) to `temporalrawdb` package (maybe will merge it to `rawdb` pkg in future - doesn't matter). 
- no functional changes
- `commitment_context.go` to use `interface` instead of exact `SharedDomains` type (maybe in future we will somehow break circular dependency here - but it's small already)
step towards: move biz-logic outsize of `state` pkg
=> move commitment and changeset db format outside of `db/state` package

erigon-lib/common/dir/rw_dir.go, erigon-lib/common/dir/rw_dir_test.go, erigon-lib/datastruct/existence/existence_filter.go, erigon-lib/datastruct/fusefilter/fusefilter_writer.go, erigon-lib/recsplit/recsplit.go, erigon-lib/seg/compress.go, erigon-lib/seg/parallel_compress.go, erigon-lib/state/btree_index.go, erigon-lib/state/domain_test.go
two recsplit creation triggered for same file:
- the first one finishes build and closes (along with doing `rm tmpFile`)
- `tmpFile` is not removed immediately because it's also `Build` by second trigger.
- when second trigger is done, it closes file (which `rm tmpFile` for real) and then tries to rename, which fails.
- this PR adds a random number to the filename so that different triggers on same file end up having different filenames. In case there's still clash, we can ask user to try again.
Possibly the two triggers are: `MergeLoop` in backend.go and `BuildMissedAccessors` in SnapshotsStage (after ottersync is finished)
=> add randomness to temp file names - to remove race condition

turbo/app/import_cmd.go
fixes remaining 17 failures in eest/consume-rlp at https://hive.ethpandaops.io/#/test/fusaka-devnet-5/1757032589-b9bf2c1dc686584baa05a74da9ca4cd6
seeing lots of:
```
could not start caplin                   err="snappy: corrupt input"
```
caplin/snap downloader dont need to be run as part of "import" chain cmd which is what is used for consume-rlp tests
also note the eest/consume-rlp tests run the import cmd with --networkid=1 so adding that in too
=> turbo/app: do not use caplin and snap downloader in import cmd

.github/workflows/test-kurtosis-assertoor.yml
we want to run these checks on PRs (mandatory) before merging into main (used by EF DevOps for continuous deployment into fusaka devnets)
in order to minimise chances of this CI failing due to changes in ethereum-package or CLs we want to use fixed versions (we can update these when needed and/or periodically)
=> workflows: run kurtosis on PRs and use fixed ethereum-package version

polygon/sync/service.go, polygon/sync/sync.go
cherry-pick of https://github.com/erigontech/erigon/pull/16803
If the tip is behind the milestone end, then this triggers an unwind to the previous verified milestone and download of blocks from previous verified milestone block until new milestone end block.
This is unnecessary since we can put the milestone back in the event queue, and it will be picked up later, and hopefully by that time the tip will be in sync with milestone. This is expected to reduce the number of unwinds.
---------
=> cherry-pick: Do not apply milestone if tip is behind it (#16890)

db/datastruct/existence/existence_filter.go, db/datastruct/fusefilter/fusefilter_writer.go, db/recsplit/recsplit.go, db/seg/compress.go, db/seg/parallel_compress.go, db/state/btree_index.go, db/state/domain_test.go, erigon-lib/common/dir/rw_dir.go, erigon-lib/common/dir/rw_dir_test.go
two recsplit creation triggered for same file:
- the first one finishes build and closes (along with doing `rm tmpFile`)
- `tmpFile` is not removed immediately because it's also `Build` by second trigger.
- when second trigger is done, it closes file (which `rm tmpFile` for real) and then tries to rename, which fails.
- this PR adds a random number to the filename so that different triggers on same file end up having different filenames. In case there's still clash, we can ask user to try again.
Possibly the two triggers are: `MergeLoop` in backend.go and `BuildMissedAccessors` in SnapshotsStage (after ottersync is finished)
cp: https://github.com/erigontech/erigon/pull/17010
=> add randomness to temp file names - to remove race condition (#17010)

polygon/sync/canonical_chain_builder.go, polygon/sync/canonical_chain_builder_test.go, polygon/sync/sync.go, polygon/sync/tip_events.go
cherry-pick of https://github.com/erigontech/erigon/pull/16929
This PR changes the event processing logic at the tip, so that if there is a need to fetch blocks from P2P this is done asynchronously, so as to not delay the processing of subsequent events in the queue.
---------
=> cherry-pick  polygon: download blocks asynchronously during tip processing

.github/workflows/test-all-erigon.yml
This reverts commit 7cb2082dbb44b5c259604bc009100be81c182f9d.
looks like we didnt update submodules on windows CI on purpose - these tests are too slow on our win runner and also even cause mdmx errors (see https://github.com/erigontech/erigon/issues/17083)
=> Revert "Add submodules update and lfs=true for windows case. (#17081)"

polygon/heimdall/validator_set.go
Even though the error was only logged, this was interfering with QA tests which were picking up the error and aborting the test.
=> [r31] demote empty valset error to warning

polygon/heimdall/snapshot_integrity.go, turbo/app/snapshots_cmd.go
was getting error:
```
mdbx_env_open: resource temporarily unavailable, label: heimdall, trace: [kv_mdbx.go:323 database.go:79 database.go:86 once.go:78 once.go:69 database.go:85 entity_store.go:137 once.go:78 once.go:69 entity_store.go:136 snapshot_store.go:74 snapshot_integrity.go:13 snapshots_cmd.go:892 snapshots_cmd.go:370 command.go:276 command.go:269 command.go:269 app.go:333 app.go:307 main.go:45 proc.go:283 asm_amd64.s:1700]
```
=> use already opened heimdall store

.github/workflows/qa-snap-download.yml
To avoid wasting resources, do not cancel the Snap-Downloader test execution.
=> qa-tests: avoid cancelling the running Snap Downloader test execution.

erigon-lib/Makefile, erigon-lib/synctest/synctest.go, erigon-lib/synctest/synctest_go_1_24.go, erigon-lib/synctest/synctest_go_1_25_and_beyond.go, txnprovider/shutter/pool_test.go
cherry-pick 1554f550602fba78469241f0788030f8059b1838
(can wait for 3.1.1)
---
closes https://github.com/erigontech/erigon/issues/16916 
closes https://github.com/erigontech/erigon/issues/16917
=> txnprovider/shutter: fix synctest issues with go1.25 (#16965)

erigon-db/downloader/downloader.go
Accidentally broke this in 40ea287b3a43404eaff2559ec9f1b1150b4f2529.
It's not affecting normal operation since most users aren't running with this flag but it's there as an option.
=> Fix DOWNLOADER_DISABLE_HTTP2 not working

.github/workflows/release.yml
Better way to implement https://github.com/erigontech/erigon/pull/16228
In this case same reusable workflow would be checked out from the same tag/branch as caller workflow.
=> Change Debian package workflow to local reference

db/snapshotsync/caplin_state_snapshots.go
Cherry-pick of this commit: https://github.com/erigontech/erigon/pull/17168
=> Fixed fd leak in caplin .idx files (#17168)

node/nodecfg/defaults.go, txnprovider/txpool/tests/helper/p2p_client.go
Keep eth/68 on port 30303 to keep Hive tests passing for now.
Hive test run: https://github.com/erigontech/erigon/actions/runs/17908526341/job/50914448868
=> Enable eth/69, drop eth/67

execution/tests/engine_api_tester.go
after https://github.com/erigontech/erigon/pull/17164 we got a flake in this [run](https://github.com/erigontech/erigon/actions/runs/17908063097/job/50913085203) with:
```
engine_api_tester.go:223: 
Error Trace:	github.com/erigontech/erigon/execution/tests/engine_api_tester.go:223
github.com/erigontech/erigon/execution/tests/engine_api_tester.go:63
github.com/erigontech/erigon/execution/tests/engine_api_reorg_test.go:34
Error:      	Received unexpected error:
Post "http://127.0.0.1:58525/": dial tcp 127.0.0.1:58525: connectex: No connection could be made because the target machine actively refused it.
Test:       	TestEngineApiInvalidPayloadThenValidCanonicalFcuWithPayloadShouldSucceed
```
adding the corresponding err to the retry-able errors for the engine api tester (it is an …
=> execution/tests: add retry to engine api tests for no connection on win

.github/workflows/scripts/run_rpc_tests_ethereum_latest.sh
Before starting the RPC Integration Tests on latest block, the test framework verifies that both Erigon and reference system are synchronised to the same block. If not, it waits until this condition is met
=> qa_tests: ensure same block for RPC tests on latest

eth/integrity/rcache_no_duplicates.go, eth/integrity/receipts_no_duplicates.go, execution/stagedsync/stage_custom_trace.go
- do not throw error, but print warning when domain progress < account progress
- rename `AssertNotBehindAccounts` -> `ValidateDomainProgress`
- use `ValidateDomainProgress` in integrity check
- some comments to indicate why the above might happen
- fix check for rcache (which would fail for consecutive empty blocks causing `diff > 1`)
=> validate domain progress in integrity

eth/rawdbreset/reset_stages.go
The error string for the Headers progress save incorrectly referenced “Bodies,” likely due to copy/paste. This change aligns the error message with the actual stage being saved, improving log accuracy and debuggability.
=> rawdbreset: correct error message when saving Headers progress

polygon/chain/chainspecs/bor-mainnet.json
See https://forum.polygon.technology/t/bor-v2-3-0-and-heimdall-v0-4-0-release-rio-hard-fork-for-veblop-upgrade/21310 and https://github.com/0xPolygon/bor/pull/1788
=> polygon: Set Rio Hard Fork Block for bor-mainnet

.github/workflows/scripts/run_rpc_tests_ethereum.sh, .github/workflows/scripts/run_rpc_tests_ethereum_latest.sh, .github/workflows/scripts/run_rpc_tests_gnosis.sh, rpc/jsonrpc/call_traces_test.go, rpc/jsonrpc/trace_filtering.go
The RPC specification for trace_filter includes support for block tags (e.g., 'latest', 'earliest'). 
Nethermind also supports this feature.
=> rpcdaemon: trace_filter:  support block tags 

.github/workflows/scripts/run_rpc_tests_ethereum.sh, rpc/contracts/direct_backend.go, rpc/ethapi/block_overrides.go, rpc/jsonrpc/eth_api.go, rpc/jsonrpc/eth_api_test.go, rpc/jsonrpc/eth_call.go, rpc/jsonrpc/eth_call_test.go, rpc/jsonrpc/tracing.go, turbo/transactions/call.go
Update eth_call with blockOverrides according specs and Geth behaviour
Included new rpc-tests TAGS with NEW  tests
=> rpcademon: eth_call update with blockOverrides

polygon/chain/chainspecs/bor-mainnet.json
Cherry pick #17254 into `release/3.1`
=> [r31] polygon: Set Rio Hard Fork Block for bor-mainnet

erigon-lib/mmap/mmap_unix.go
- MmapRw is dead code: there are zero references across the repository.
- The API is non-portable: there is no Windows implementation of MmapRw, so introducing usage would break Windows builds.
- All current call sites use read-only mapping via Mmap; no write-enabled mapping is needed.
- Removing it simplifies the API surface and avoids confusion about supported functionality.
=> erigon-lib/mmap: remove dead MmapRw from mmap_unix.go

cmd/erigon/main.go, core/syscheck/syscheck.go
```
erigon@dev-bm-e3-ethmainnet-n1:~/erigon$ make erigon && ./build/bin/erigon --datadir=/erigon-data/ethmainnet31 --chain=mainnet --log.console.verbosity=4 --prune.mode=archive
Building /home/erigon/erigon/build/bin/erigon
cd ./cmd/erigon && GOARCH=amd64 GOAMD64=v2  CGO_CFLAGS="-O2 -g  -DMDBX_FORCE_ASSERTIONS=0  -DMDBX_DISABLE_VALIDATION=0  -DMDBX_ENV_CHECKPID=0  -D__BLST_PORTABLE__ -Wno-unknown-warning-option -Wno-enum-int-mismatch -Wno-strict-prototypes -Wno-unused-but-set-variable -O3" CGO_LDFLAGS="-O2 -g -O3 -g" GOPRIVATE="github.com/erigontech/silkworm-go" go  build -trimpath -buildvcs=false -ldflags "-X github.com/erigontech/erigon/db/version.GitCommit=8d983e9d54645f01ef75c1d030fe09fb0d867c47 -X github.com/erigontech/erigon/db/version.GitBranch=jklondon/syscheck -X …
```
=> added syscheck on linux

eth/ethconfig/config.go, execution/chain/spec/chainspecs/mainnet.json
Cherry pick #16949 into `release/3.2`
=> [r32] Bump eth mainnet default block gas limit to 60M

cmd/utils/flags.go, execution/engineapi/engine_server.go, turbo/cli/default_flags.go
- Document that these flags set limits on a per protocol level
- `maxpendpeers` flag was being set in config but not accessible to the user
=> Update maxpeers and maxpendpeers flag documentation

db/kv/temporal/kv_temporal.go, db/state/aggregator.go, db/state/domain.go, db/state/history.go
Currently default return value of 0 leads to `PrunedError` not being thrown when commitment history is not available when `eth_getProof` is invoked. This leads to incorrect root hash error, but instead a `PrunedError` should be thrown.
A default value of +∞ is more appropriate, and fixes https://github.com/erigontech/erigon/issues/16776 as well.
UPDATE: It could happen that there are no history files, but there is history in MDBX, so the function is now updated to look into MDBX for the first txnum if there are history files in snapshots.
=> Use MaxUint64 as return value to `HistoryStartFrom()` if no files present

.github/workflows/qa-tip-tracking-gnosis.yml, .github/workflows/qa-tip-tracking.yml
The error reason of the tip-tracking test is present in the test run summary, see below
But in the log, it was not clear what happened:
Now the error reason is also present in the test run log.
=> qa-tests: show a more specific error message inside the tip-tracking log

execution/stagedsync/exec3.go, execution/stagedsync/stage_txlookup.go
This fixed an issue on main where exec did not advance the stage becuase the final call to calculate comittment was never called when err more was returned by the exec function.
=> Start final commitment calc

core/blockchain.go
porting on 3.2 fix issue 17220
=> [3.2] debug_traceCall fix avoid to trace sysContract

core/state_transition.go
This fixes 11 eest/consume-engine tests due the additional error reason for GAS_LIMIT_EXCEEDS_MAXIMUM breaking the hive message parser.
This should also fix any other parsing of execution abort messages.
=> Return original abort error string if exsists

common/crypto/bn254/cloudflare/bn254_test.go, common/crypto/bn254/google/bn254_test.go, common/crypto/crypto_test.go, common/crypto/ecies/ecies_test.go, common/crypto/signature_test.go
These changes use b.Loop() to simplify the code and improve performance
Supported by Go Team, more info: https://go.dev/blog/testing-b-loop
More info can see https://go.dev/issue/73137.
Before:
```shell
go test -run=^$ -bench=. ./common/crypto -timeout=1h     
goos: darwin
goarch: arm64
pkg: github.com/erigontech/erigon/common/crypto
cpu: Apple M4
BenchmarkSha3-10                  	 4661552	       240.0 ns/op
BenchmarkEcrecoverSignature-10    	   74696	     16256 ns/op
BenchmarkVerifySignature-10       	   94023	     13391 ns/op
BenchmarkDecompressPubkey-10      	  526609	      2280 ns/op
PASS
ok  	github.com/erigontech/erigon/common/crypto	5.807s
```
After:
```shell
go test -run=^$ -bench=. ./common/crypto -timeout=1h  
goos: darwin
goarch: arm64
pkg: …
```
=> refactor: use b.Loop() to simplify the code and improve performance
