erigontech/erigon

.golangci/step1.yml
.golangci/step2.yml
.golangci/step3.yml
.golangci/step4.yml
Makefile

* added new step
* removed verbose mode
* downgrade golangci-lint version

Lint clean

---

cmd/hack/hack.go
cmd/state/state.go
common/dbutils/suffix_type.go
core/pruner/pruner.go
core/pruner/pruner_test.go
core/state/database.go
core/state/intra_block_state_test.go
core/state/readonly.go
ethdb/database.go
ethdb/interface.go
ethdb/mutation.go
ethdb/table.go
trie/database.go

Extract suffix type
Move mutation to separated flag
Simple pruning test

Added pruning package. Extract suffix type

---

core/state/database.go
tests/block_test.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/146

Fix suicideStorageCheck block tests

---

core/state/intra_block_state.go
core/state/intra_block_state_test.go
core/tx_noncer.go
eth/api_tracer.go
miner/worker.go

Remove `Copy` from `IntraBlockState` and add thread synchronization.

---

core/types/derive_sha.go
core/types/derive_sha_test.go
docs/programmers_guide/guide.md
trie/resolver.go
trie/structural_2.go
trie/structural_test.go

Use `GenStructStep` from `structural_2` in `DeriveSha`.

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
core/blockchain.go
eth/backend.go
eth/config.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/160

Downloader flag to quickly download the blockchain without processing blocks

---

cmd/state/stateless.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/154

Prine tries (in memory) in the same cycle as db commits

---

cmd/state/state.go
cmd/state/state_snapshot.go
cmd/state/stateless.go
trie/debug.go

Fix snapshot saving and add an interval setting.

---

cmd/pics/state.go
cmd/state/state.go
cmd/state/stateless.go
cmd/state/stateless_chart.go
cmd/state/stateless_stats.go
core/state/database.go
trie/proof_generator.go
trie/proof_generator_test.go

Write tape stats to a csv file.

---

cmd/hack/hack.go
cmd/state/stateless.go
core/state/database.go
core/state/stateless.go
trie/debug.go
trie/debug_test.go
trie/gen_struct_step.go
trie/hashbuilder.go
trie/proof_generator.go
trie/resolve_set.go
trie/resolver.go
trie/stream.go
trie/structural_test.go

More fixes for the calculation of the state root without modifying the trie. This part is to enable the work in fixing the mining

Further fixes for the no-mod-root

---

cmd/state/commands/global_flags_vars.go
cmd/state/commands/stateless_chart.go
cmd/state/commands/verify_snapshot.go
cmd/state/stateless/stateless.go
cmd/state/stateless/stateless_chart.go
cmd/state/stateless/stateless_stats.go
core/state/block_witness_stats.go
core/state/database.go
trie/proof_generator.go

Write proper stats to the CSV file; restore charting capabilities.

---

core/blockchain.go

fixes https://github.com/ledgerwatch/turbo-geth/issues/202

deadlock fix

---

core/types/derive_sha.go
trie/gen_struct_step.go
trie/hashbuilder.go
trie/proof_generator.go
trie/resolver.go
trie/stream.go
trie/structural_test.go

Remove tapes from HashBuilder

---

core/types/derive_sha.go
trie/gen_struct_step.go
trie/resolver.go
trie/stream.go
trie/structural_test.go

Remove tapes from GenStructStep

---

core/blockchain.go
miner/worker.go

Restore chainHeadEvent in writeBlockWithState
closes https://github.com/ledgerwatch/turbo-geth/issues/254

Fix mining after geth 1.9.9

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpctest/main.go
core/headerchain.go
core/rawdb/accessors_chain.go
eth/api.go
eth/api_test.go
eth/downloader/fakepeer.go
ethdb/badger_db.go
ethdb/bolt_db.go
ethdb/mutation.go
ethdb/remote/bolt_remote.go
ethdb/remote/remote_bolt_db.go
ethdb/walk.go

For #226 
- `bench1()` test passed
- but hardcoded mainnet config and PoW engine

RPC Daemon: storage range at

---

cmd/rpcdaemon/commands/daemon.go
cmd/state/commands/gas_limits.go
cmd/state/commands/state_growth.go
cmd/state/stateless/state.go
ethdb/bolt_db.go
ethdb/remote/bolt_remote.go
ethdb/remote/chain_remote.go
ethdb/remote/remote_bolt_db.go

Reopen https://github.com/ledgerwatch/turbo-geth/pull/269 to merge to master

Merged 269 PR into wrong branch

---

cmd/hack/hack.go
cmd/hack/scripts/geth_log_parse.py

Quite sloppy, but just to have it in

bolt vs badger log parser and chart

---

ethdb/bolt_db.go
ethdb/remote/bolt_remote.go
ethdb/remote/remote_bolt_db.go

this request does 55 GetAsOf calls, each this call produce 8 requests to remotedb

remote_bolt.CmdGetAsOf

---

ethdb/remote/bolt_remote.go
ethdb/remote/bolt_remote_test.go

- reconnect after server gone
- reconnect after network error
- periodic ping from client: https://github.com/ledgerwatch/turbo-geth/issues/235

reconnect after server gone

---

eth/firehose.go

Parity only supports 3 letter capabilities

---

cmd/geth/retesteth.go

Main problem was: C implementation expected 0 be encoded as "0x00" while we returned "0x000000000000000000"

Retesteth: storageRangeAt compatibility

---

core/state/database.go
core/state/readonly.go
ethdb/history_index.go
ethdb/mutation.go
tests/block_test.go

closes https://github.com/ledgerwatch/turbo-geth/issues/312

fix thin_history tests

---

docs/programmers_guide/witness_format.md
trie/gen_struct_step.go
trie/hashbuilder.go
trie/resolver.go
trie/stream.go
trie/trie_from_witness.go
trie/witness_builder.go

Add Incarnation support for accounts

---

cmd/state/commands/stateless.go
cmd/state/stateless/stateless.go
cmd/state/stateless/witness_db.go
cmd/state/stateless/witness_db_test.go
core/state/database.go
miner/worker.go
trie/resolver.go
trie/resolver_stateful.go
trie/resolver_stateless.go
trie/resolver_stateless_test.go
trie/trie_from_witness.go
trie/trie_witness.go
trie/witness.go
trie/witness_builder.go
trie/witness_builder_test.go
trie/witness_operators.go

Stateless Resolver: store and use witnesses for resolved subtries

---

common/dbutils/changeset.go
ethdb/walk.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/343

Copy values from the ChangeSet bucket during Rewind

---

docs/programmers_guide/witness_formal_spec.md

opening a PR early to discuss and settle on a format

BRANCH formal semantics

---

consensus/result.go
miner/environment.go
miner/worker.go

fix https://github.com/ledgerwatch/turbo-geth/issues/357 also should help with https://github.com/ledgerwatch/turbo-geth/pull/355 (https://app.circleci.com/jobs/github/ledgerwatch/turbo-geth/2268)

Mining data races

---

cmd/hack/hack.go
cmd/state/stateless/state_snapshot.go
cmd/state/stateless/state_snapshot_test.go
common/changeset/changeset.go
common/changeset/storage_changeset.go
common/dbutils/bucket.go
common/dbutils/history_index.go
eth/backend.go
eth/backend_test.go
eth/config.go
migrations/changeset_migration.go
migrations/changeset_migration_test.go
migrations/migrations.go
migrations/migrations_test.go

closes https://github.com/ledgerwatch/turbo-geth/issues/323

migrations

---

core/blockchain.go

removed repetitions in 'l' bucket

---

cmd/restapi/apis/intermediate_hash_api.go
cmd/restapi/rest/serve_rest.go
debug-web-ui/package.json
debug-web-ui/src/App.js
debug-web-ui/src/App.test.js
debug-web-ui/src/components/ErrorCatcher.js
debug-web-ui/src/components/LookupAccountForm.js
debug-web-ui/src/components/LookupStorageTombstonesForm.js
debug-web-ui/src/components/SearchField.js
debug-web-ui/src/page/Accounts.js
debug-web-ui/src/page/StorageTombstones.js
debug-web-ui/src/utils/API.js
debug-web-ui/yarn.lock
ethdb/remote/bolt_remote.go

simple ui - just show tombstones

Storage Tombstones UI 

---

cmd/restapi/apis/storage_tombstone_api.go
core/state/database.go
core/state/database_test.go
debug-web-ui/src/components/LookupStorageTombstonesForm.js

Move .Put out of .View and remove deletion of all tombstones when delete acc

Make AccountCreation do determined amount of operations and Move .Put out of .View 

---

core/state/state_test.go
trie/debug.go
trie/debug_test.go
trie/trie_witness.go
trie/witness.go
trie/witness_builder.go

Use the binary witness format to serialize tries.

---

.dockerignore
cmd/prometheus/.gitignore
cmd/prometheus/Readme.md
cmd/prometheus/dashboards/dashboard.yml
cmd/prometheus/dashboards/turbo_geth.json
cmd/prometheus/datasources/prometheus.yml
cmd/prometheus/docker-compose.yml
cmd/prometheus/prometheus.yml
cmd/restapi/Dockerfile
core/state/intermediate_hashes.go
debug-web-ui/Dockerfile
debug-web-ui/src/Logo.svg
debug-web-ui/src/logo.svg
go.sum
trie/resolver_stateful.go
trie/resolver_stateful_cached.go
trie/resolver_stateless.go

Build: `cd cmd/prometheus && docker-compose build --parallel`
Run: `cd cmd/prometheus && TGETH_DATADIR=/geth/data/dir docker-compose up`
Grafana: [localhost:3000](localhost:3000), admin/admin
DebugUI: [localhost:3001](localhost:3001)

Prometheus and Grafana setup

---

common/dbutils/history_index.go
core/block_validator.go
core/state/database.go

Also closes https://github.com/ledgerwatch/turbo-geth/issues/176

Fix sync issue related to self-destructs

---

core/blockchain.go
core/state/database.go
core/state/database_writer.go
core/state/db_state_writer.go
core/state/history_test.go
eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/stagedsync_downloader.go
eth/downloader/stagedsync_stage_bodies.go
eth/downloader/stagedsync_stage_execute.go
eth/downloader/stagedsync_stages.go
ethdb/interface.go

NB! No hash checks are done there.

Add "execute blocks" stage to the staged sync.

---

core/blockchain.go
core/state/change_set_writer.go
core/state/database.go
core/state/db_state_reader.go
core/state/db_state_writer.go
core/state/intra_block_state.go
core/state/readonly.go
core/state/stateless.go
core/vm/gas_table_test.go
eth/downloader/queue.go
eth/downloader/stagedsync_stage_bodies.go
eth/downloader/stagedsync_stage_execute.go

Fix canonical hashes in staged bodies sync

---

trie/resolver.go
trie/resolver_stateful.go

- Reuse accAddrHashWithInc buffer
- Remove non-essential copying

Simplify resolver

---

cmd/hack/hack.go
core/blockchain.go
trie/resolver_stateful.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/513

Fix for the sync failure on block 2792476

---

cmd/hack/hack.go
core/state/database.go
core/state/db_state_reader.go
core/state/db_state_writer.go
core/vm/gas_table_test.go
eth/downloader/stagedsync_stage_execute.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/528

Introduce incarnationMap in both DbStateReader and DbStateWriter

---

trie/resolver_stateful.go

Unfortunately, it was not possible to merge `hb` and `hbStorage`. Because in Ethereum's patricia merkle trie the storage tries are viewed as separate tries and not part of the one big trie. That is why we need to employ two hashbuilders to emulate that

Small refactoring of resolver_stateful

---

cmd/hack/hack.go
trie/flatdb_sub_trie_loader.go

Continuation of work on `eth_getProof`. Now there is a little prototype of it in the `cmd/hack/hack.go`, which does not work correctly yet though

Decompose SubTrieLoader into DB loading and trie building part

---

cmd/prometheus/dashboards/turbo_geth.json
ethdb/bolt_db.go
internal/debug/flags.go

BoltDB stats export to prometheus (not bucket stats)

---

.circleci/config.yml
Makefile

Linting step speedup from 6min to 2min

[wip] Cache z3 build on CI, up golangci-lint to v1.27.0

---

cmd/state/stateless/deps.go
cmd/state/stateless/naked_accouts.go
cmd/state/stateless/naked_storage.go
cmd/state/stateless/spec_exec.go
cmd/state/stateless/state.go
cmd/state/stateless/tokens.go
cmd/state/stateless/transaction_stats.go
common/pool/pool_stack.go
core/vm/eips.go
core/vm/gas_table.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/interpreter.go
core/vm/jump_table.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
core/vm/memory_table.go
core/vm/stack/stack.go
eth/tracers/tracer.go

I think there is no reason to make a stack each time. This optimization reduces stackGrown and GC

EVM stack optimizations

---

Makefile
consensus/clique/snapshot_test.go
core/bench_test.go
core/block_validator_test.go
core/blockchain_test.go
core/dao_test.go
core/generate_index_test.go
core/genesis_test.go
core/rawdb/accessors_chain_test.go
core/rawdb/accessors_indexes_test.go
core/rlp_test.go
ethclient/ethclient_test.go
ethdb/database_test.go
ethdb/kv_badger.go
ethdb/kv_lmdb.go
miner/worker_test.go

- fully passed LMDB tests
- badger's tests still failing in some places, but sync on badger also failing. I will try to debug sync another time.

Lmdb and Badger tests

---

ethdb/kv_lmdb.go
go.mod
go.sum

- lastest version of lmdb
- same version of c bindings

lmdb version up to 2020

---

cmd/prometheus/dashboards/turbo_geth.json
ethdb/bolt_db.go
ethdb/kv_bolt.go

send bolt buckets stats (new one) to prometheus 

---

cmd/state/py/chain.py
cmd/state/py/common.py
cmd/state/py/dbutils.py
cmd/state/py/main.py

Experiment with rewriting gas_limits to python+lmdb: 
- just to see how it can be, and to see impact of analytics to working turbo-geth node.
- and to get reviewed, as I'm not python professional.

Experiment with Python+Lmdb and state analytics

---

cmd/hack/hack.go
core/rawdb/accessors_chain.go
ethdb/abstractbench/abstract_bench_test.go
ethdb/bolt_db.go
ethdb/kv_lmdb.go
ethdb/mutation.go
ethdb/mutation_puts.go
ethdb/object_db.go

- remove the unused slice from MultiPut
- mutation: reuse tuples slice 
- use pool for bucket objects in kv_lmdb

Optimize multi put

---

core/blockchain.go
eth/downloader/downloader.go
eth/downloader/downloader_stagedsync.go
eth/downloader/downloader_stagedsync_test.go
eth/stagedsync/stage_headers.go
eth/stagedsync/state.go
eth/stagedsync/state_test.go

Fix to terminate the sync cycle after unwind needs to be improved, therefore tests have been disabled for now

Various fixes to make sync work

---

eth/stagedsync/stage_headers.go
eth/stagedsync/stage_headers_test.go

Fix total difficulty calculation in staged sync.

---

cmd/hack/hack.go
eth/downloader/downloader_test.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stagedsync.go
eth/stagedsync/stages/stages.go

because of the behaviour of SELFDESTRUCT, we cannot unwind the stage6 past any self-destruct without first unwinding stage5

Combine stage5 and stage6

---

common/etl/collector.go
common/etl/dataprovider.go
common/etl/etl_test.go

closes https://github.com/ledgerwatch/turbo-geth/issues/681

Fix last chunk order

---

common/etl/buffers.go
common/etl/dataprovider.go

On SSD speedup 3x for Flush/Read etl buffer files

increase IO buffers size

---

core/blockchain.go
core/blockchain_insert.go
eth/stagedsync/stage_bodies.go

added insertBodies

---

core/blockchain.go

removed unused actions in stage 2

---

cmd/hack/hack.go
eth/stagedsync/stage_interhashes.go
trie/flatdb_sub_trie_loader.go
trie/gen_struct_step.go
trie/hashbuilder.go
trie/node.go
trie/retain_list.go

Revert "Only useful IH cursor (#694)" #703
This reverts commit 63c998c91f488f14129f726290fd199df07ec7e8.

Revert "Only useful IH cursor (#694)"

---

core/blockchain.go
eth/downloader/downloader.go
eth/downloader/downloader_stagedsync_test.go
eth/downloader/downloader_test.go

fix stage 2

---

cmd/hack/hack.go

Description is here: https://github.com/ledgerwatch/turbo-geth/compare/lmdb_dupsort_state_experiment?expand=1#diff-7d9462b79270a0328f4ab1e837cfb3cdR1982

Experiments: state in DupSort layout and speed of large DupSort key deletion

---

eth/stagedsync/stage_hashstate.go

Found it by test: https://github.com/ledgerwatch/turbo-geth/pull/714

pass deleted code to collector

---

cmd/integration/db_utils.go
cmd/integration/flags.go
cmd/integration/reset_state.go
cmd/integration/stages.go
cmd/integration/state_stages.go
eth/stagedsync/stage_txlookup.go
eth/stagedsync/stagedsync.go

```
go run ./cmd/integration compare_states
go run ./cmd/integration stage9
```

Add commands "compare_states", add command "stage9", fix unwind of stage9 (it walked over whole db)

---

cmd/integration/stages.go
cmd/integration/state_stages.go
eth/stagedsync/stage_txlookup.go
eth/stagedsync/stagedsync.go

TxLookup unwind: Remove entries for blocks between unwindPoint+1 and stage.BlockNumber

TxLookup unwind: Remove entries for blocks between unwindPoint+1 and stage.BlockNumber

---

eth/backend.go
eth/stagedsync/stage_txpool.go
eth/stagedsync/stagedsync.go

It most of the time is `tx pool is already started error` and it's ok to process further with the error

dont stop txPool stage on error

---

cmd/integration/commands/reset_state.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
eth/downloader/downloader.go
eth/protocol_test.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stagedsync.go
eth/stagedsync/state.go
eth/stagedsync/unwind.go
eth/stagedsync/unwind_test.go

- integration: use stagedsync.State object 
- IH stage: don't skip persistent steps even if they complete before interruption
- reset_state: clear unwind stages info too

integration: fix problem with interruption

---

cmd/integration/commands/reset_state.go
cmd/integration/commands/stages.go
eth/stagedsync/stage.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/unwind.go
ethdb/interface.go

- If step is bigger - then clear buckets and gen hashed state from scratch
- Incremental steps  - un-interruptable 
- Gen from scratch - interruptable

Limit incremental step size of stages 5 and 6. 

---

ethdb/kv_lmdb.go

To easier change bucket settings (for example by releasing new version or just by switching git branches)

re-create bucket on b.Clear 

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/get_modified_accounts.go

debug_getModifiedAccountsByNumber, debug_getModifiedAccountsByHash 
closes #772

GetModifiedAccounts by hash and block number

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/get_balance.go

Rpc getBalance

---

eth/handler.go

Workaround panic in staged sync.

---

cmd/geth/chaincmd.go
cmd/geth/consolecmd.go
cmd/geth/consolecmd_test.go
cmd/geth/main.go
cmd/geth/usage.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/service/service.go
cmd/utils/flags.go
eth/config.go
eth/downloader/modes.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_execute_test.go

closes #765
I did it the simple way, keeping `core.UsePlainStateExecution = false` by default, otherwise too many tests break. I will think about how to do it better and probably follow-up.

Make plain state + staged sync the default

---

cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/debug_api.go
core/state/dump.go
core/state/history.go
core/state/history_test.go
core/state/state_test.go
eth/api_test.go

closes https://github.com/ledgerwatch/turbo-geth/issues/764
+ some walkAsOf fixes&tests

Account range

---

eth/backend.go
params/version.go

Use CalVer for turbo-geth versioning.

---

node/defaults.go

Change the default datastore dir

---

common/dbutils/bucket.go
eth/backend.go
ethdb/storage_mode.go
ethdb/storage_mode_test.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/798

Remove preimage storage mode, write receipts by default

---

core/blockchain.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/801

Remove last fast block message, and possibilty for db reset

---

core/blockchain.go
eth/stagedsync/stage_headers.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/808

Move the check for BadHashes to stage1

---

cmd/rpcdaemon/commands/call.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/get_balance.go
cmd/rpcdaemon/commands/root.go
core/evm.go
internal/ethapi/api.go

RpcDeamon eth_call and eth_estimateGas

---

cmd/integration/commands/stages.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_execute_test.go
eth/stagedsync/stagedsync.go

Closes https://github.com/ledgerwatch/turbo-geth/issues/805

Delete receipts in unwind stage4

---

eth/downloader/downloader_test.go
eth/downloader/peer.go
eth/fetcher/block_fetcher_test.go
eth/handler.go
eth/handler_test.go
eth/helper_test.go
eth/peer.go
eth/protocol.go
eth/protocol_test.go
eth/sync_test.go

for  https://github.com/ledgerwatch/turbo-geth/issues/802
Created couple new issues after: 
https://github.com/ledgerwatch/turbo-geth/issues/821
https://github.com/ledgerwatch/turbo-geth/issues/820

remove eth/63

---

node/defaults.go

Support XDG_DATA_DIR on Linux

---

cmd/prometheus/dashboards/turbo_geth.json

Around 2.4M block we do 250K/sec

Add db.Get() calls/sec chart to prometheus

---

common/etl/dataprovider.go
common/etl/etl.go

Log total ETL file sizes when removing them

---

.golangci.yml
.golangci/step4.yml
cmd/integration/commands/root.go
ethdb/kv_bolt.go
internal/debug/flags.go
metrics/exp/exp.go

- adopt --metrics.addr flag in integration
- remove bolt internal metrics

adopt --metrics.addr flag in integration

---

ethdb/kv_lmdb.go

problem: double-rollback did call wg.Done() twice - which end up to negative value

lmdb allow multi-rollback

---

cmd/rpcdaemon/commands/call.go
cmd/rpcdaemon/commands/eth_api.go

Eth_call: `overrides` as an optional argument

---

core/generate_index.go

Use batches when unwinding indexes

---

trie/flatdb_sub_trie_loader.go

```
Sequence - if between 2 IH records not possible insert any state record - then they form "sequence"
Example1:
1234
1235
Example2:
12ff
13
Example3:
12ff
13000000
If 2 IH records form "sequence" then it can be consumed without moving StateCursor
```

[merge after release] enable IH sequence feature

---

cmd/rpcdaemon/commands/net.go
cmd/rpcdaemon/commands/net_version.go
core/eth_backend.go
eth/backend.go
ethdb/kv_abstract.go
ethdb/kv_remote.go
ethdb/remote/remotedbserver/ethbackend.go

my bad @akme , I forgot to push my last commit.
Thank you for patience and testing!
closes #935

grpc regenerate

---

eth/stagedsync/stage_interhashes.go
ethdb/interface.go
ethdb/kv_lmdb.go
ethdb/tx_db.go
trie/flatdb_sub_trie_loader.go

- instead of collecting RetainList: open Tx, delete all IH (all prefixes of items in retain list), run loader on this Tx, commit only if hash root matched
- speed: on promoting 1, 10, 100, 4000 blocks it shows same speed as current version

IH: no retain list

---

eth/stagedsync/stage_interhashes.go
ethdb/interface.go
ethdb/tx_db.go
trie/flatdb_sub_trie_loader.go

Reverts ledgerwatch/turbo-geth#946

Revert "IH: no retain list"

---

eth/config.go

Store ethash datafiles in a separate directory.

---

cmd/restapi/commands/root.go

for https://github.com/ledgerwatch/turbo-geth/issues/985

restapi_to_follog_geth_cli_variables

---

cmd/integration/commands/state_stages.go
cmd/state/stateless/check_change_sets.go
ethdb/object_db.go

crushed because faced closed tx

Fix integration command

---

README.md

* Add net_peerCount and a note about its non-standard behavior

Update README for net_peerCount

---

cmd/rpcdaemon/commands/daemon.go

Update totalDifficulty from Big to hexutil.Big

---

cmd/rpcdaemon/commands/eth_api.go
eth/stagedsync/README.md
eth/stagedsync/stagedsync.go

rpcdaemon, stagedsync: make sure we update the current block number after a sync cycle

---

eth/downloader/downloader.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_txpool.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/1023

Bad rewind issues fix

---

cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/commands/get_receipts.go

fixed chainconfig

---

cmd/integration/commands/stages.go
eth/downloader/downloader_stagedsync_test.go
eth/handler.go
eth/stagedsync/stagebuilder.go
eth/stagedsync/stagedsync.go

Also, provides `DefaultStages()` and `DefaultUnwindOrder()` convenience methods.

Initialize Staged Sync with stages.

---

docs/programmers_guide/indices.md
ethdb/kv_lmdb.go

Reverts ledgerwatch/turbo-geth#1019

Revert "simplify cursor.Next and cursor.First implementation"

---

cmd/rpcdaemon/main.go
cmd/rpctest/rpctest/bench1.go
cmd/rpctest/rpctest/utils.go
ethdb/kv_remote.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/1057

Fix for RPC daemon leak

---

Makefile
README.md
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/web3_api.go
cmd/rpcdaemon/main.go

Fixes #1074
Please see small open questions on the issue

1074 web3 client version

---

README.md
cmd/rpcdaemon/commands/eth_api.go

1070 eth get code

---

core/state/history.go

We had some buggy code (which I did not have time to debug) which was handling the case when history index is out of sync with the changesets (history itself). But now we have transactional cycles (as long as the cycles are <= 1024 blocks), in most cases we do not need to worry about these buckets being out of sync.
However, this reminds me that we probably need to get RPC daemon to detect when the buckets are out of sync (looking at the sync progress) and return errors instead of wrong results

Remove changeset processing in FindHistory

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/coinbase.go
cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/commands/error_messages.go
cmd/rpcdaemon/commands/get_receipts.go
cmd/rpcdaemon/commands/net_api.go
cmd/rpcdaemon/commands/send_transaction.go
cmd/rpcdaemon/commands/trace_api_adhoc.go

Fixes issue #1139 - crash when running chaindata mode

---

docs/programmers_guide/db_walkthrough.MD

I made some updates to the db walk through document to hopefully improve its readability. I found a few grammatical errors and style inconsistencies. Thanks for such a thorough document!

Improve DB walk through doc readability

---

cmd/hack/hack.go
common/dbutils/bucket.go
core/rawdb/accessors_chain.go
core/types/receipt.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_log_index.go
migrations/dupsort_state.go
migrations/migrations.go
migrations/receipts.go

Problem: rlp overhead to deserealize 10.9M receipts - 1.5hours.

Switch to cbor

---

turbo/transactions/call.go

This would optimise a common use-case

eth_call to use current state when blockNumber == latest

---

cmd/tg/main.go
node/node.go
p2p/server.go
turbo/node/node.go

Reverts ledgerwatch/turbo-geth#1179

Revert "Cancel P2P server by signal (pass root ctx to p2p server)"

---

eth/stagedsync/README.md

Reviewing the sync stages readme, I noticed a missing stage LogIndex. Plus re-ordered index stages to agree with the DefaultStages array in the code.

Update stages readme

---

Makefile
cmd/hack/binary-deps/main.go

`make lmdb-tools` to install
to print freelist info `./build/bin/lmdb_stat -f <chain_data>`

Include lmdb_stat tool

---

cmd/tgcustom/main.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stagebuilder.go
eth/stagedsync/stagedsync.go

needed to update bloom or whatever filters between blocks

turbo-api: custom state writers

---

cmd/hack/hack.go
cmd/integration/commands/flags.go
cmd/integration/commands/root.go
cmd/integration/commands/stages.go
cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/testdata/RPC_Testing.json
cmd/utils/flags.go
ethdb/walk.go

Closes #1232 
See comment: https://github.com/ledgerwatch/turbo-geth/issues/1232#issuecomment-707438492

Fixes issue #1232

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_forkid.go
cmd/rpcdaemon/commands/eth_system.go
cmd/rpcdaemon/commands/get_chain_config.go
core/forkid/forkid.go
eth/stagedsync/stages/stages.go

closes #1239 
Examples:
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_forks","params":["latest"],"id":1}'  http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":{"genesis":"0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3","passed":[],"next":1150000}}
Response:
type Forks struct {
GenesisHash common.Hash `json:"genesis"`
Passed      []uint64    `json:"passed"`
Next        *uint64     `json:"next,omitempty"`
}
```
@vorot93 could you check if API is right for you?

ForkID api

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/commands/daemon.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/tg_api.go
cmd/rpcdaemon/commands/tg_block.go
cmd/rpcdaemon/commands/tg_receipts.go
cmd/rpcdaemon/commands/tg_system.go

Extract nonstandard APIs and introduce tg namespace

---

docs/programmers_guide/db_walkthrough.MD

Update description of table Headers in DB walk-through doc

Update description of table Headers

---

cmd/integration/commands/state_stages.go
eth/stagedsync/state.go

index out of range: 14 of capacity 14

Integration crush on unwind inside state.LogPrefix() method 

---

cmd/rpcdaemon/commands/tg_api.go
cmd/rpcdaemon/commands/tg_system.go
cmd/rpcdaemon/postman/RPC_Document.md

tg_forks returns only full forks list

---

ethdb/mutation.go
ethdb/mutation_puts.go
ethdb/object_db.go
ethdb/tx_db.go
go.mod

Reverts ledgerwatch/turbo-geth#1294

Revert "[WIP - Discussion - Perf Testing] Use BTree instead of maps for Mutation (batch)"

---

Makefile
README.md
cmd/rpcdaemon/README.md
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_deprecated.go
cmd/rpcdaemon/commands/eth_filters.go
cmd/rpcdaemon/commands/send_transaction.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_api.go
cmd/rpcdaemon/commands/web3_api.go
cmd/rpcdaemon/main.go
cmd/rpcdaemon/postman/RPC_Testing.json

I'll use this to update a few test cases:
1) Fix tests for `eth_mining` and `tg_fork` routines.
2) Review tracing tests (probably not complete)
3) Add tests for filtering/log routines
I'll remove [WIP] when this is ready to merge.

Updating RPC tests in Postman

---

common/dbutils/bucket.go
ethdb/interface.go
ethdb/kv_abstract.go
ethdb/kv_abstract_test.go
ethdb/kv_lmdb.go
ethdb/kv_mdbx.go
ethdb/kv_remote.go
ethdb/kv_snapshot.go
ethdb/mdbx/txn.go
ethdb/mdbx/txn_test.go
ethdb/mutation.go
ethdb/object_db.go
ethdb/tx_db.go

Compatible with `mdbx_dbi_sequence`

Sequence for each table 

---

core/generate_index.go

Reason: 
- history effects are written into map 
- "last but one" chunk renamed to 0xffff suffix first
- then "the last" chunk deleted (in case when no data left after truncate) and write into the same map with key 0xffff - nil - and delete result of previous point
Result: "last but one" chunk of history dissappear from DB during unwinds - when truncating more than one chunk.
Way to reproduce:
```
./cmd/integration state_stages --unwind=2 --unwind_every=5 --block=10000
./cmd/state checkChangeSets
```

history: "last but one" chunk dissapear

---

eth/stagedsync/stage_interhashes.go
turbo/trie/trie_root.go

Reverts ledgerwatch/turbo-geth#1357

Revert "IH: regenerate must clear IH bucket  "

---

cmd/headers/commands/sentry.go
cmd/headers/download/sentry.go

I added support for a couple additional sentry args, if you're interested. Otherwise feel free to close!

Accept discover,netrestrict,staticpeer arguments for sentry

---

cmd/rpcdaemon/commands/eth_receipts.go

for https://github.com/ledgerwatch/turbo-geth/issues/1381

move_get_logs_by_hash_to_tg_namespace

---

node/config.go
node/node.go

for https://github.com/ledgerwatch/turbo-geth/issues/1386

need handle empty db path special way in couple places - with meaning "in-mem db"

---

ethdb/remote/remotedbserver/ethbackend.go

not perfect hack for https://github.com/ledgerwatch/turbo-geth/issues/1382
need to think about better event api (geth's version looks complex)

subscription_doesnt_preserve_shutdown

---

cmd/integration/commands/stages.go

IntermediateHashes and HashState are flipped

Fix order of print to match stage numbers in integration

---

cmd/integration/commands/reset_state.go
cmd/rpcdaemon/commands/debug_api.go
cmd/rpcdaemon/commands/eth_system.go
cmd/rpcdaemon/commands/rpc_block.go
cmd/state/generate/regenerate_tx_lookup.go
cmd/state/stateless/check_change_sets.go
cmd/state/stateless/state.go
eth/downloader/downloader.go
eth/stagedsync/all_stages.go
eth/stagedsync/stage.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_execute_test.go
eth/stagedsync/stage_interhashes.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stage_senders_test.go
eth/stagedsync/stages/stages.go
eth/stagedsync/state.go
eth/stagedsync/state_test.go
eth/stagedsync/unwind.go
eth/stagedsync/unwind_test.go
migrations/dupsort_state.go
migrations/migrations_test.go
migrations/stagedsync_to_use_stage_blockhashes.go
migrations/stagedsync_to_use_stage_blockhashes_test.go
turbo/rpchelper/helper.go
turbo/snapshotsync/postprocessing.go

Not used anywhere, apparently legacy from the past.

Remove StageData

---

turbo/trie/trie_root.go

fix for https://github.com/ledgerwatch/turbo-geth/issues/1451

Split ih cursors

---

turbo/cli/flags.go

cli: fix snapshot mode tooltip

---

cmd/rpcdaemon/commands/debug_api.go
turbo/transactions/tracing.go

Was pretty easy to do, for: https://github.com/ledgerwatch/turbo-geth/issues/1455

Adding debug_accountAt

---

ethdb/remote/remotedbserver/events.go

This is a different approach to the desired functionality of supporting multiple subscribers of the new head event. The original text from #1477:
> This change will allow a one to many subscription model for the stagedsync's notifier. While implementing the txpool provider, I realized that it wasn't possible to have both the rpcdaemon and it running at the same time since the struct can only maintain 1 subscriber at a time. This change will allow multiple services to subscribe to new chain head updates.

Support multiple new head subscribers

---

consensus/clique/verifier.go

panic while Gorly sync

---

Makefile

Fix Typo in Makefile

---

cmd/rpcdaemon/README.md

Add debug_accountAt to rpcdaemon README

---

ethdb/id.go
ethdb/object_db.go

Makes it a dumb-wrapper which we can create at will

ObjectDatabase cleanup

---

cmd/rpcdaemon/commands/eth_receipts.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/1619

Lazy fix for eth_getLogs

---

cmd/rpcdaemon/commands/eth_api.go
internal/ethapi/api.go

for https://github.com/ledgerwatch/turbo-geth/issues/1635

infinite gas cap for gas estimate

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/test.http

for https://github.com/ledgerwatch/turbo-geth/issues/1636

estimate_gas: to accept optional block or hash

---

go.mod
go.sum

Reverts ledgerwatch/turbo-geth#1705

Revert "lmdb v0.9.70"

---

cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_api.go
cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_traceblock.go
cmd/rpctest/rpctest/request_generator.go

trace_block

---

cmd/rpcdaemon/commands/trace_filtering.go

Remove vmTrace from trace_block

---

cmd/rpcdaemon/commands/trace_filtering.go

trace_block (part 2)

---

cmd/rpcdaemon/cli/config.go

for https://github.com/ledgerwatch/turbo-geth/issues/1756

RPCDaemon: Fix verbosity

---

cmd/rpcdaemon/README.md

* Add eth_getBlockReceipts to rpcdaemon README

Add eth_getBlockReceipts to rpcdaemon README

---

cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
eth/downloader/downloader.go
eth/handler.go
eth/stagedsync/stage_mining_create_block.go
eth/stagedsync/stagebuilder.go

- Started TxPool on app start - if mining enabled and it's not mainnet

 Start mining on new tx

---

cmd/utils/flags.go
eth/downloader/downloader.go
eth/stagedsync/all_stages.go
eth/stagedsync/stagebuilder.go
ethdb/kv_mdbx.go

For: https://github.com/ledgerwatch/turbo-geth/issues/1761

Notify RPCDaemon after sync cycle commit

---

core/state/history.go
core/state/history_test.go
core/state/plain_readonly.go

Reverts ledgerwatch/turbo-geth#1769

Revert "GetAsOf: do not return error on nil"

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/commands/storage_range.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/tracing.go
cmd/state/commands/check_change_sets.go
core/state/plain_readonly.go
eth/stagedsync/stage_call_traces.go
turbo/rpchelper/pending.go
turbo/stages/blockchain_test.go
turbo/transactions/call.go
turbo/transactions/tracing.go

deprecate PlainDbState in favor of PlainKvState

---

cmd/headers/download/downloader.go
cmd/integration/commands/snapshot_check.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_stages.go
common/changeset/storage_changeset.go
core/rawdb/accessors_account.go
core/state/history_test.go
eth/stagedsync/all_stages.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stagebuilder.go

exec unwind etl

---

eth/stagedsync/README.md

Correct typo in stagedsync README.md

---

cmd/headers/download/broadcast.go
cmd/headers/download/downloader.go
eth/protocols/eth/protocol.go
eth/stagedsync/stage_headers_new.go
turbo/adapter/block_propagator.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

@AlexeyAkhunov , take a look please at Hashes Announce broadcast. If it's ok, I will switch bodies broadcast to same style
- no limit for announces list size. Do we need?

broadcast new headers

---

eth/backend.go
turbo/stages/headerdownload/header_algos.go

Fixes https://github.com/ledgerwatch/turbo-geth/issues/1855

[download.v2] Prevent deadlock by starting txPool early

---

ethdb/remote/remotedbserver/events.go

Fixes for: https://github.com/ledgerwatch/turbo-geth/issues/1876

fix concurrent map write

---

eth/downloader/downloader.go
eth/handler_eth.go
eth/stagedsync/all_stages.go
eth/stagedsync/stage_blockhashes_test.go
eth/stagedsync/stage_headers.go
eth/stagedsync/stage_headers_test.go

It counteracts the removal of pinging the sync prior to every handshake

Qucker reaction to new block headers

---

cmd/rpcdaemon/commands/eth_receipts.go

Fix for: https://github.com/ledgerwatch/turbo-geth/issues/1948

RPCDaemon: add block existence check

---

ethdb/kv_lmdb.go
ethdb/kv_mdbx.go

Maybe it's fix for: https://github.com/erthink/libmdbx/issues/195

tx.Cursor() ignored error (maybe it's fix for MDBX_PROBLEM)

---

cmd/headers/download/downloader.go
eth/backend.go
eth/stagedsync/stage_headers_new.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/stageloop.go

for https://github.com/ledgerwatch/erigon/issues/1967

fixes for dv2 cancelation

---

turbo/snapshotsync/snapshot_builder.go
turbo/snapshotsync/snapshot_builder_test.go

closes https://github.com/ledgerwatch/erigon/issues/1938

Fix flacky test

---

.gitignore
win-build.ps1

Implement #2023 
Add build files from MDBX to .gitignore

Win build patch

---

core/genesis.go
p2p/enode/nodedb.go
turbo/node/node.go

For: https://github.com/ledgerwatch/erigon/issues/2007

pass cli flag to enode

---

core/genesis.go
ethdb/kv_mdbx.go
turbo/node/node.go

for https://github.com/ledgerwatch/erigon/issues/2007

genesis switch db

---

eth/stagedsync/stage_execute.go

for https://github.com/ledgerwatch/erigon/issues/2020

log tx per sec

---

README.md
common/etl/README.md
win-build.ps1

* Path to compilers enforcements for win_build.ps1
* Add notes to Readme about anti-viruses

Win build patch 2

---

cmd/rpcdaemon/cli/config.go
node/rpcstack.go

For https://github.com/ledgerwatch/erigon/issues/2065

rpcdaemon: --http.compression flag (default: true)

---

cmd/integration/commands/stages.go
cmd/utils/flags.go
eth/backend.go
p2p/server.go
turbo/snapshotsync/wrapdb.go

Now it's disabled by default. Is it ok?

cli param to enable eth65 and counfigure it's port

---

cmd/rpcdaemon/commands/eth_block.go

Introduces eth_callBundle rpc call to simulate an ordered sequence of transactions on top of a given block state.
Using it in our research to observe the effects of transaction reordering and censoring

Implement historical tx simulation rpc api

---

cmd/rpcdaemon/README.md

Add eth_callBundle to README

---

rpc/handler.go

- parallel exec
- limited amount of goroutines per batch
- fallback if request is streamable or "*_subscribe"

Rpcdaemon batch

---

Dockerfile
Makefile
cmd/erigon/main.go
win-build.ps1

```
INFO [06-05|18:24:52.631] Build info                               git_branch=build-info git_tag=v2021.06.01-20-g5ba3ea162 git_commit=5ba3ea162a2155e8e412b79d3628eefce8c80634
```
For Win and *nix 
Docker file updated too

Add repo tag to build info

---

cmd/evm/staterunner.go

closes https://github.com/ledgerwatch/erigon/issues/2135 #2130

EVM test deadlock

---

turbo/stages/headerdownload/header_algos.go

[message (6).txt](https://github.com/ledgerwatch/erigon/files/6639359/message.6.txt)

Downloader panics on nil parentTd

---

cmd/utils/flags.go
turbo/cli/default_flags.go
turbo/cli/flags.go

This PR adds the --maxpeers cli option. Closes #2150

Add --maxpeers cli option (#2150)

---

common/debug/log_panic.go
node/node.go
turbo/stages/headerdownload/header_algos.go

Forgot that git always ingnores empty dirs, so the "crashreports" directory was not created from my last PR

Added temp file in crashreports because git is stupid

---

cmd/sentry/download/downloader.go
cmd/sentry/download/sentry.go
cmd/sentry/download/sentry_api.go
cmd/sentry/download/sentry_test.go
cmd/utils/flags.go
consensus/clique/aura.go
core/forkid/forkid.go
eth/backend.go
eth/ethconfig/config.go
eth/stagedsync/stage_headers.go
params/config.go

- Do I need change `>=` to `>`?
- Now i sending GetBlockHeaders with 1 header in request

Send GetBlockHeaders immediately if TD of connected peer >= our TD

---

common/debug/log_panic.go
core/types/dynamic_fee_tx.go
core/types/legacy_tx.go
core/types/transaction.go
eth/ethconfig/config.go
eth/gasprice/gasprice.go
turbo/stages/headerdownload/header_algos.go

Changed gas price oracle to use effective tip. Added GetEffectiveGasTip method to dynamic_tx and legacy_tx.

Changed gas price oracle to use effective tip and ignoreUnder parameter for 1559.

---

cmd/sentry/download/sentry.go
eth/stagedsync/stage.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_log_index.go
eth/stagedsync/stage_senders.go
eth/stagedsync/stagedsync.go
ethdb/kv_lmdb.go
ethdb/kv_mdbx.go
ethdb/kv_remote.go
ethdb/kv_snapshot.go
ethdb/mdbx/env.go
ethdb/mdbx/txn.go
ethdb/mutation.go
ethdb/remote/remotedbserver/mining.go
ethdb/tx_db.go
tests/block_test_util.go
turbo/stages/blockchain_test.go
turbo/stages/bodydownload/body_data_struct.go
turbo/stages/genesis_test.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/mock_sentry.go

fix warnings produced by https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment

fix fieldalignment linter warnings

---

core/forkid/forkid_test.go
params/config.go

Add london testnet blocks to params/config & forkid_test

add london testnet blocks

---

.github/workflows/ci.yml

This reverts commit 470a9918b2221d12ed1b99016563d08b7774d67d.

Revert "info"

---

common/dbutils/bucket.go

Reverts ledgerwatch/erigon#2180

Revert "Remove unused tables, soft rename"

---

common/dbutils/bucket.go
ethdb/kv/kv_mdbx.go

Now ripped out the whole soft rename infrastructure

Remove unused tables, soft rename, take 2

---

eth/stagedsync/stage_execute.go

Print Mgas/second during execution

---

cmd/rpcdaemon/commands/eth_receipts.go

Change in api response:
```
--- v2021.06.04.json    2021-06-28 18:49:28.229320489 +0300
+++ v2021.06.05.json    2021-06-28 18:51:39.273014469 +0300
-    "status": "0x1",
+    "status": 1,
```

fix_receipt_status

---

cmd/erigon/main.go
cmd/erigoncustom/main.go
cmd/integration/commands/root.go
cmd/utils/flags.go
eth/backend.go
migrations/header_prefix_test.go
migrations/migrations.go
migrations/migrations_test.go
node/node.go
node/node_test.go
turbo/node/buckets.go
turbo/node/node.go
turbo/snapshotsync/downloader.go
turbo/snapshotsync/wrapdb.go

- later it will allow us change cli framework and add RPCDaemon into Erigon

separate configs setup from node and eth objects creation

---

cmd/rpcdaemon/commands/trace_adhoc.go
cmd/snapshots/debug/debug_test.go
core/state/cached_writer.go
core/state/change_set_writer.go
core/state/database.go
core/state/db_state_writer.go
core/state/history_test.go
core/state/intra_block_state.go
core/state/plain_readonly.go
core/state/plain_state_writer.go
core/state/state_object.go
core/state/state_test.go
eth/stagedsync/testutil.go

step towards https://github.com/ledgerwatch/erigon/issues/2212

remove ctx from state writer interface

---

turbo/transactions/call.go

fix for 
```
goroutine 93 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc00381a6c0, 0x8, 0xc003843ca0)
github.com/ledgerwatch/erigon/rpc/service.go:220 +0xc6
panic(0x10d6460, 0x1be3490)
runtime/panic.go:965 +0x1b9
github.com/holiman/uint256.(*Int).Lt(...)
github.com/holiman/uint256@v1.2.0/uint256.go:766
github.com/holiman/uint256.(*Int).Gt(...)
github.com/holiman/uint256@v1.2.0/uint256.go:727
github.com/holiman/uint256.(*Int).Cmp(0xc003857330, 0x0, 0x0)
github.com/holiman/uint256@v1.2.0/uint256.go:791 +0x5
github.com/ledgerwatch/erigon/core.(*StateTransition).preCheck(0xc0035a7780, 0x203000, 0xc003842cd0, 0x45815b)
github.com/ledgerwatch/erigon/core/state_transition.go:246 +0x43e
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc0035a7780, …
```

eth_call base_fee

---

core/state_transition.go

Reverts ledgerwatch/erigon#2360

Revert "buy gas optimize"

---

rpc/handler.go

- deoptimize for now
- probably need remove 1 layer of abstractions because `rpc/jsonWriter.writeJSON` doesn't have method to stream batch responses

RPC: fix batch streaming

---

core/types/access_list_tx.go
internal/ethapi/api.go

for https://github.com/ledgerwatch/erigon/issues/2162
and for https://github.com/ledgerwatch/erigon/issues/2328

RPC: Access list storage keys are non-nil

---

core/error.go
core/state_transition.go

Remove unnecessary value transfer check from TransitionDb

---

Dockerfile
Makefile

conform dockerfile to be OCI compliant
update makefile to utilize buildkit 
change turbo-geth to erigon

minor dockerfile improvements 

---

go.mod
go.sum

increased Readers limit 
changelog: https://github.com/erthink/libmdbx/releases

mdbx: v0.10.2

---

turbo/cli/flags.go

we are testing - maybe will reduce it more

reduce default bodies ram usage to fit 16g

---

eth/stagedsync/README.md

Hi, I have updated the readme to list all the current 18 sync stages. 
I was confused when first syncing erigon with stages that didn't show up on here, when trying to get an idea about how far into the process I was.

Update stagedsync readme to show all current stages

---

cmd/rpcdaemon/README.md

Small followup PR to #2407. I forgot to document the RPC method in the README.md.

README.md: add txpool_status

---

cmd/rpcdaemon/commands/trace_adhoc.go

Fixes: https://github.com/ledgerwatch/erigon/issues/2522

Fix trace_filter crash

---

core/state/plain_state_writer.go
eth/stagedsync/stage_execute.go
turbo/shards/state_change_accumulator.go
turbo/stages/mock_sentry.go

- to support selfDestruct+revive case

create new Change object if incarnation increased

---

internal/ethapi/api.go

Remove gasPrice inner variable to avoid shadowing
Fixes #2559

Fix gas price in eth_call

---

README.md

Add Default Ports to FAQ

---

README.md

The `>` angle brackets are unnecessary and get in the way if you copy the entire sequence.

Improve readme experience

---

cmd/rpcdaemon/commands/eth_api.go

for https://github.com/ledgerwatch/erigon/issues/2598

Rpcdaemon race on chainConfig set

---

cmd/rpcdaemon/main.go
go.mod
go.sum
rpc/handler.go

for https://github.com/ledgerwatch/erigon/issues/2598

Rpcdaemon: handle "WaitGroup is reused before previous Wait has returned" panic on shutdown

---

wmake.ps1

Seems like there are two alternative DisplayName formattings

Refine git search

---

cmd/rpcdaemon/commands/trace_filtering.go

For https://github.com/ledgerwatch/erigon/issues/2598

RPCDaemon: try revert json iter  pool change

---

eth/backend.go

for https://github.com/ledgerwatch/erigon/issues/2647

fix --bad.block nil pointer

---

cmd/utils/cmd.go
eth/stagedsync/stage_interhashes.go
internal/debug/flags.go
internal/debug/signal.go
internal/debug/signal_unix.go
internal/debug/signal_windows.go
turbo/stages/stageloop.go

doesn't require having --pprof flag

Print goroutines trace to STDOUT without app stop on SIGUSR1

---

eth/stagedsync/stage.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_senders.go

Enriavil1 more generalised prune receipts

---

cmd/sentry/download/sentry.go

*Use atomics for `PeerInfo.Height()` and `PeerInfo.SetHeight(uint64)`

sentry/download:

---

p2p/enode/nodedb.go

for https://github.com/ledgerwatch/erigon/issues/2632

Enode quit race

---

core/tx_pool.go

for 
```
Write at 0x00c0000de1d4 by goroutine 58:
github.com/ledgerwatch/erigon/core.(*TxPool).Start()
github.com/ledgerwatch/erigon/core/tx_pool.go:326 +0x79e
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnTxPool()
github.com/ledgerwatch/erigon/eth/stagedsync/stage_txpool.go:64 +0x591
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func49()
github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:259 +0x104
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage()
github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316 +0x190
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run()
github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233 +0x49d
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep() …
```

fix sentry forks slice race

---

common/dbutils/composite_keys.go
core/rawdb/accessors_chain.go

ReceiptsKey is the same as EncodeBlockNumber

Remove ReceiptsKey in favour of EncodeBlockNumber

---

cmd/cons/commands/clique.go
cmd/integration/commands/stages.go
cmd/integration/commands/testing.go
cmd/rpcdaemon/commands/eth_block.go
cmd/snapshots/downloader/commands/root.go
internal/ethapi/api.go

fix for https://github.com/ledgerwatch/erigon/issues/2712

Sender check read from db

---

eth/stagedsync/stage_finish.go

Wrong notifyFrom value in NotifyNewHeaders

---

cmd/rpcdaemon/cli/config.go

*Change `TxPoolApiAddr` to match that one being set by default

rpcdaemon:

---

core/vm/evm.go

Add check to have pre-Homestead behavior on code store error

---

cmd/rpcdaemon/cli/config.go

Reverts ledgerwatch/erigon#2752

Revert "txpool change default port in rpcdaemon"

---

core/rawdb/accessors_chain.go

for https://github.com/ledgerwatch/erigon/issues/2770

No senders is fine

---

cmd/integration/commands/root.go
eth/stagedsync/stage_interhashes.go
go.mod
go.sum

for https://github.com/ledgerwatch/erigon/issues/2691

IntermediateHash stage - switch from incremental to re-generate mode - if jump > 100K blocks

---

cmd/rpcdaemon/cli/config.go
core/state/cached_reader2.go
go.mod
go.sum
turbo/cli/default_flags.go
turbo/cli/flags.go

maybe will somehow disable it in future "if no subscribers". But right now it's only way to make RPCDaemon work out of box when no --datadir set

Enable "State stream" by default

---

params/config.go

when terminalTotalDifficulty is reached then proof-of-work is transitioned to proof-of-stake

Added terminalTotalDifficulty field in ChainConfig

---

common/fdlimit/fdlimit_bsd.go
common/fdlimit/fdlimit_unix.go
eth/stagedsync/stage_hashstate.go

HashState stage genesis sync - read PlainState only once

---

DEV_CHAIN.md
README.md

I created a tutorial to run a local dev chain (DEV_CHAIN.md) and also inserted:
-  a link to it into the readme.md 
-  it as a question to FAQ

Dev Chain Tutorial

---

cmd/hack/hack.go
go.mod
go.sum

if set limit maxPatternLen lower - then can increase maxDictPatterns - because dictionary is not bloated by large permutations

Compress: add maxPatternLen=64

---

eth/stagedsync/stage_bodies.go

For https://github.com/ledgerwatch/erigon/issues/2888

 Check existence before write - because WriteRawBody isn't idempotent 

---

eth/stagedsync/stage_bodies.go

For https://github.com/ledgerwatch/erigon/issues/2888

 Check existence before write - because WriteRawBody isn't idempotent (it allocates new sequence range for transactions on every call) (#2941)

---

core/state/state_object.go
core/types/transaction_signing_test.go
core/vm/evm.go
core/vm/gas_table.go
core/vm/interpreter.go
turbo/trie/stream.go
turbo/trie/trie_root.go

Only a micro-optimization, but it helps with readability as well.

Use IsZero() instead of Sign() for uint256.int

---

cmd/sentry/download/sentry.go

A general clean-up that will make upcoming changes simpler.

Refactor sentry peers

---

go.mod
go.sum

this if fix for local txs propagation problem

P2p pooled tx rlp stable

---

cmd/rpcdaemon/commands/eth_accounts.go
go.mod
go.sum

* pending nonce
* Increment nonce of last tx to get tx count
* Upgrade erigon-lib

[stable] `eth_getTransactionCount` to work with `pending` from txpool

---

cmd/rpcdaemon/commands/trace_filtering.go

Fixes https://github.com/ledgerwatch/erigon/issues/2581

trace_block to return empty result for genesis

---

cmd/rpcdaemon/commands/trace_filtering.go

[beta] trace_block to return empty result for genesis

---

cmd/rpcdaemon/commands/eth_call.go

Fixes: https://github.com/ledgerwatch/erigon/issues/2944

eth_estimateGas to correctly recap to balance for London txs

---

cmd/integration/commands/stages.go
cmd/sentry/download/broadcast.go
cmd/sentry/download/downloader.go
cmd/sentry/download/sentry.go
cmd/sentry/download/sentry_api.go
cmd/sentry/download/sentry_test.go
eth/backend.go
eth/fetcher/tx_fetcher.go
eth/fetcher/tx_fetcher_test.go
eth/protocols/eth/handler.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_headers.go
go.mod
go.sum
p2p/peer.go
p2p/protocol.go
p2p/server.go
p2p/server_test.go
p2p/simulations/test.go
p2p/transport.go
p2p/transport_test.go
tests/fuzzers/txfetcher/txfetcher_fuzzer.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/mock_sentry.go
turbo/stages/txpropagate/deprecated.go
turbo/txpool/p2p.go

For consistency with all clients.

Change sentry peer_id from H512 pubkey to H256 keccak256(pubkey)

---

cmd/rpcdaemon/commands/eth_call.go

[beta] eth_estimateGas to correctly recap to balance for London txs

---

Makefile
cmd/devnettest/main.go
cmd/devnettest/requests/request_generator.go
cmd/devnettest/requests/requests.go
cmd/devnettest/requests/utils.go
cmd/devnettest/services/utility.go

- Currently only made one for `eth_getBalance`, the rest will be done after making corrections.
- The flag parsers are not scalable at the moment, a fix to follow that done in `cmd/rpctest` will be made after.
- Not figured out how to return responses to the request caller yet, so a print to console is made for the result

Implemented devnet test for eth_getBalance

---

cmd/sentry/download/sentry.go

A peer's `Height` (`MinBlock`) was being updated with an atomic load and an atomic store, but the logical operation of these together was not atomic.
This change replaces `PeerInfo.SetHeight()` with `PeerInfo.SetIncreasedHeight()` using a CAS loop to make the update atomic.

Fix atomic peer height update

---

cmd/sentry/download/sentry.go

for https://github.com/ledgerwatch/erigon/issues/2942

Enable p2p receipts methods

---

p2p/server.go

* Update server.go
* Update server.go

[beta] Not try to create temporary file with enode

---

cmd/txpool/main.go
cmd/utils/flags.go
eth/backend.go
go.mod
go.sum

[beta] [txpool] Introduce PriceBump, change tx replacement logic, add test

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go

[beta] Reverse order of arguments in eth_createAccessList

---

eth/stagedsync/default_stages.go
eth/stagedsync/stage_headers.go

Fixed spawnStageHeader not passing the test

fixed SpawnStageHeader not passing the test

---

cmd/rpcdaemon/commands/eth_receipts.go

* eth_getLogs to start from latest by default
* Update eth_receipts.go
* Update eth_receipts.go
* Update eth_receipts.go

[beta] eth_getLogs to start from latest by default

---

cmd/rpcdaemon/commands/trace_adhoc.go

[beta] trace_ include subtraces to precompiles with value > 0

---

cmd/sentry/download/downloader.go
cmd/sentry/download/sentry.go
cmd/utils/flags.go
eth/backend.go
turbo/cli/default_flags.go

Minimal set of changes to stop running second sentry for eth/65

[beta] Remove eth/65 support

---

cmd/rpcdaemon/commands/trace_adhoc.go
cmd/state/commands/opcode_tracer.go
core/vm/access_list_tracer.go
core/vm/eips.go
core/vm/evm.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/interpreter.go
core/vm/jump_table.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
crypto/blake2b/blake2b_ref.go
eth/calltracer/calltracer.go
eth/tracers/logger/access_list_tracer.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
eth/tracers/tracers_test.go
turbo/transactions/tracing.go

closes: #2447 
Ports go-ethereum changes in a way that does not change erigon's tracers behaviour.

change: port js tracer changes

---

cmd/sentry/sentry/downloader.go
cmd/sentry/sentry/sentry.go
go.mod
go.sum

Transactions are announced to all peers (by sending their hashes), but also also broadcast to sqrt(peer_number) randomly chosen peers

Txpool: broadcast transaction along with announcements

---

cmd/integration/commands/flags.go
cmd/utils/flags.go
core/block_validator.go
core/chain_makers.go
eth/ethconfig/config.go
eth/stagedsync/stage_mining_create_block.go
params/mining.go
turbo/cli/default_flags.go

Port https://github.com/ethereum/go-ethereum/pull/23213

Simplify miner gas limit post EIP-1559. Default to 30M

---

go.mod
go.sum

for https://github.com/ledgerwatch/erigon-lib/pull/221

RLP: suspend parse errors from logs 

---

go.mod
go.sum

https://github.com/ledgerwatch/erigon-lib/pull/222

RLP: suspend parse errors from logs

---

eth/stagedsync/stage_issuance.go

maybe will fix https://github.com/ledgerwatch/erigon/issues/3181 and https://github.com/ledgerwatch/erigon/issues/3189

issuance stage depends on bodies, not on headers

---

eth/backend.go
eth/ethconfig/config.go

For https://github.com/ledgerwatch/erigon/discussions/3216

Increase body download timeout

---

core/skip_analysis.go

[stable] Skip analysis and preverified hashe update

---

eth/backend.go
eth/ethconfig/config.go

This reverts commit f0f33f1519a8a85fc8d690757cdc866de9ac5938.

Revert "increase body download timeout (#3217)"

---

eth/backend.go
eth/ethconfig/config.go

This reverts commit 4aca7e85e8e6fad353d5070218b96b1d76b78df2.

Revert "increase body download timeout (#3217) (#3237)"

---

turbo/stages/headerdownload/header_algos.go

[stable] Inverted lowestNum and highestNum in header downloader (#3301)

---

core/skip_analysis.go

[stable] skip analysis and preverified hashes update (#3300)

---

cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/trace_filtering.go

Reimplemented behaviour of `TraceFilterModeIntersection` in accordance with https://github.com/ledgerwatch/erigon/pull/3167#issuecomment-1014241624.

follow-up on #2119: realigned TraceFilterModeIntersection behaviour

---

cmd/erigon/main.go
cmd/erigoncustom/main.go
cmd/utils/flags.go
eth/backend.go
eth/ethconfig/config.go
turbo/app/import.go
turbo/app/init.go
turbo/app/make_app.go
turbo/app/snapshots.go
turbo/stages/bodydownload/prefetched_blocks.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/stageloop.go

- Ability to import a sequence of blocks (of course linked to the local leading block) based on the rlp file for a chain.

Add Erigon Import feature for Hive integration purpose

---

cmd/utils/flags.go
eth/backend.go
ethdb/privateapi/ethbackend.go
turbo/cli/default_flags.go

This pull request changes the --proposer flag to be on by default and adds a flag to disable proposing

Enabled proposer by default

---

cmd/utils/flags.go
consensus/db/db.go
go.mod
go.sum
node/config.go
node/node.go
turbo/cli/default_flags.go

bsc - wanna try performance of bigger pageSize to remove 8tb db size limit
you can see current pageSize of db by:
```
./build/bin/mdbx_stat -e <your_datadir>/chaindata
```

Mdbx page size

---

cmd/rpcdaemon/commands/starknet_call.go
common/types.go
common/types_test.go

- Created StarknetAddress type
- Implemented StarknetAddress to Address converting
- Updated starknet_call API

StarknetAddress type

---

rlp/decode.go

stable pick of https://github.com/ledgerwatch/erigon/pull/3232

penalize peer for invalid rlp

---

cmd/rpcdaemon/commands/eth_txs.go

[stable] fix compatibility of getting tx by number

---

migrations/migrations.go

This reverts commit db7fa3d0ed0758fdca29efd337c85200a290becf.

Revert "Change major db version check (#3241)"

---

cmd/rpcdaemon/commands/eth_txs.go

eth_GetTransactionByHash: to return nil pending txn by hash

---

cmd/rpcdaemon/commands/eth_txs.go

devel has no such problem - because this bug was introduced by snapshot sync changes

GetTransactionByHash: fallback to txpool

---

eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go

Update instead of SaveStageProgress for stages.Header

---

cmd/sentry/sentry/sentry.go

for: https://github.com/ledgerwatch/erigon/issues/3496#event-6057062458

Atomic close 2 channels

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go

* Make blockNrOrHash optional in CreateAccessList (in line with geth)
* OptimizedAccessList
* cosmetics
* optimizeGas param instead of separate method
* Inline toAddress

Optimized eth_createAccessList (#3453)

---

cmd/rpcdaemon/README.md
cmd/rpcdaemon/commands/erigon_api.go
cmd/rpcdaemon/commands/erigon_block.go
cmd/rpcdaemon/commands/eth_call_test.go

correct naming for erigon_getBlockByTimestamp

---

Makefile

Silence non-important comments in the "make erigon" output.

Makefile: silence a few build messages.

---

cmd/rpcdaemon/commands/erigon_api.go
cmd/rpcdaemon/commands/erigon_block.go
cmd/rpcdaemon/commands/eth_call_test.go
rpc/types.go

Better inputs

---

cmd/rpcdaemon/commands/eth_call.go
core/state/state_object.go

Fixes to access list and state overrides (#3570)

---

cmd/rpcdaemon/commands/eth_accounts.go
turbo/rpchelper/helper.go
turbo/transactions/call.go

* Optimise eth_getStorageAt for current state
* Fix

Optimise eth_getStorageAt for current state (#3580)

---

cmd/sentry/sentry/sentry.go
cmd/utils/flags.go
core/genesis.go
params/bootnodes.go
params/config.go

Simplify node URL list logic.
Handle errors.

Refactor discovery bootnodes parsing.

---

cmd/rpcdaemon/commands/eth_accounts.go
cmd/rpcdaemon/commands/eth_api_test.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/tracing.go
turbo/rpchelper/helper.go
turbo/transactions/call.go

* Auto detect latest block for optimal use of plain state and state cache
* Fix lint
* Fix test

[stable] Auto detect latest block for optimal use of plain state and cache

---

eth/stagedsync/sync.go

by some reason we lost "Timings" of forward stages from logs

Add timings of forward stages to logs

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/tracing.go
eth/tracers/api.go
internal/ethapi/state_overrides.go
turbo/transactions/call.go

State override support

---

cmd/integration/commands/stages.go
cmd/utils/flags.go
core/genesis.go
params/config.go

* get chain config, genesis hash and network ID by chain name in params/config
* get genesis block chain name in core/genesis

Refactor getting chain info by chain name.

---

go.mod
go.sum

more info: 
https://github.com/erthink/libmdbx/releases/tag/v0.11.5
https://github.com/erthink/libmdbx/issues/269

mdbx v0.11.5 (fix for false-corruption on Linux kernel 4.19)

---

docs/readthedocs/source/rpc/index.rst
eth/protocols/eth/handler.go

Remove mentions of Morden testnet

---

p2p/enode/nodedb.go

Revert "Prevent frequent commits to the node DB in sentries (#2505)"
This reverts commit 65a9a265c2049b22f9fe78f0f93715ed00a33014.

Revert node DB cache (#3581)

---

.github/CONTRIBUTING.md

File is visible on Github via Insights/Community Standards and the pull request page. 
Links pointed to go_ethereum project.

fix contributing doc

---

internal/ethapi/api.go

1. no need to panic 
3. fix error message

no need to panic

---

cmd/rpcdaemon/commands/tracing.go

Previously `txCtx` is not updated for every tx in a block, which leads to wrong tracing results.

rpcdaemon: fix TxContext in traceBlock

---

cmd/rpcdaemon/commands/tracing.go

Previously `txCtx` is not updated for every tx, which
leads to wrong tracing results.

rpcdaemon: fix TxContext in traceBlock (#3716)

---

p2p/node_key_config.go

The logic was not saving the key file.

Fix NodeKeyConfig.save()

---

go.mod
go.sum

Pick up https://github.com/ledgerwatch/erigon-lib/pull/391.

[Fix] missing Spammer in (DiscardReason) String()

---

go.mod
go.sum

fix for https://github.com/erthink/libmdbx/commit/d522069080a2aeb996c6442d74ad08475d8280f7

Mdbx fix after v0.11.6

---

cmd/rpcdaemon/commands/rpc_block.go
core/rawdb/accessors_chain.go
eth/stagedsync/stage_headers.go
go.mod
go.sum
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

See [Erigon Hive test failure](https://notes.ethereum.org/@3a9tFrpLTxq1U828RfGEEw/BJoZYjPMc#Latest-Block-after-NewPayload).

Prefer forkchoice head as latest block in RPC

---

go.mod
go.sum

for https://github.com/ledgerwatch/erigon/issues/3799

fix nil pointer in fetch.go

---

cmd/hack/hack.go

This is just a convenience addition to make it easier to dump pre-verified hashes up until N blocks behind head.

hack: Allow blockTotal <= 0 as offset from head

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go

* Fix 'all defaults' case for eth_estimateGas
* fix tests
Co-authored-by: Igor Mandrigin <i@mandrigin.ru>

[stable] Fix 'all defaults' case for eth_estimateGas (#3790)

---

cmd/rpcdaemon/commands/engine_api.go

See https://github.com/ethereum/execution-apis/pull/179 for more info.

ExchangeTransitionConfiguration: allow non-zero TerminalBlockNumber

---

params/config.go

Reference : https://github.com/maticnetwork/launch/blob/master/testnet-v4/sentry/sentry/bor/genesis.json
https://github.com/maticnetwork/bor/pull/375

Update bor mumbai config

---

.gitmodules

Same change as already merged in `devel`

Update libmdbx source

---

eth/stagedsync/stage_txlookup.go

* save
* save
* tolerate some fails
* tolerate some fails

[alpha] TxLookup fix 2 (#3994)

---

eth/stagedsync/stage_headers.go

This should fix `Unknown SafeBlockHash` Hive test.

Check that safe & finalized blocks are canonical for no-op forkChoice

---

cmd/hack/hack.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_call_traces.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_headers.go
eth/stagedsync/sync.go
go.mod
go.sum
turbo/snapshotsync/block_snapshots.go

change:
```
alloc="7.56 GiB" sys="14.98 GiB"
alloc=7.56Gb sys=14.98Gb
```

shorter logs 

---

p2p/discover/v5_udp_test.go

The test was flaky, because of the "endpoint prediction".
The test starts 5 nodes one by one.
Node 0 is used as a bootstrap node for nodes 1-4.
When it is about to add, say, node 3, nodes 0 and 1 might already have had a chance to communicate,
and updateEndpoints() deletes the node 0 UDP port, because fallbackUDP port was not configured.
In this case node 3 would get a bootstrap node 0 without a port and lead to an error:
v5_udp_test.go:110: bad bootstrap node "enr:...": missing UDP port
The problem was reproducible by this command:
go test ./p2p/discover -run TestUDPv5_lookupE2E -count 500

p2p: fix flaky TestUDPv5_lookupE2E

---

Makefile
p2p/discover/table_integration_test.go
p2p/discover/table_test.go

* refactor test
* add a fast fixed examples test for the main suite
* split slow test for the integration suite

p2p: improve test TestTable_findnodeByID

---

.github/workflows/ci.yml
Dockerfile

Reverts ledgerwatch/erigon#4038

Revert "Speed up docker image build by use layer cache"

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/filters/filters.go
cmd/rpcdaemon/services/eth_backend.go
eth/stagedsync/stage_headers.go
ethdb/privateapi/ethbackend.go
ethdb/privateapi/events.go
turbo/stages/mock_sentry.go
turbo/stages/stageloop.go

Not done by this PR: rpcdaemon to able open snapshots without erigon.

RPCDaemon - open snapshots only when they are ready (and indices ready).

---

.github/workflows/ci.yml
.github/workflows/test-integration.yml
wmake.ps1

* list "all" targets explicitly
* add missing targets
* add missing build flags
* add test-integration target
* show tests output
* use wmake test on CI
* update submodules for all targets (like Makefile)
* remove unused function Test-Administrator

make: wmake refactoring

---

Dockerfile
README.md
cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/test.http
docker-compose.yml
node/defaults.go

See https://github.com/ethereum/execution-apis/pull/219.

Engine API: remove unauth port

---

params/config.go

Ropsten Merge TTD

---

eth/backend.go
eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go
turbo/stages/stageloop.go

It changes when the stage loop runs. Now stage loop will run only whenever we are on the initial cycle or have headers inside of header downloader

No hack skip cycle

---

ethdb/privateapi/ethbackend.go

Reverts ledgerwatch/erigon#4170

Revert "Fixed initial finality"

---

cmd/downloader/trackers/embed.go

for https://github.com/ledgerwatch/erigon/issues/4154

Trackers: split file lines cross-platform way

---

cmd/downloader/downloader/downloader.go
cmd/evm/runner.go
cmd/hack/flow/flow.go
cmd/hack/hack.go
cmd/state/commands/erigon2.go
common/debug/memstats.go
eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_call_traces.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_hashstate.go
eth/stagedsync/stage_headers.go
eth/stagedsync/stage_indexes.go
eth/stagedsync/stage_log_index.go
eth/stagedsync/stage_tevm.go
go.mod
go.sum
internal/debug/api.go
metrics/runtime_test.go
migrations/txs_begin_end.go
turbo/snapshotsync/block_snapshots.go

runtime.ReadMemStats - does stopTheWorld
NO_MEMSTAT=true env variable added
Removed runtime.ReadMemStats call on each etl.collector.Load

option to disable runtime.ReadMemStats

---

eth/backend.go
go.mod
go.sum

Snap: reduced memory footprint on building huffman table

---

eth/backend.go
turbo/app/snapshots.go

fixing: small time after app start - all rpc requests returned nil, then start returning data

It's safe now to open snapshots at app start

---

.gitmodules

Reverts ledgerwatch/erigon#4241

Revert "mdbx submodule did require github login"

---

core/genesis.go

In particular, this makes `engine_exchangeTransitionConfigurationV1` to obey  `--override.terminaltotaldifficulty`.

Ensure stored config is overridden when overrideTerminalTotalDifficulty

---

core/state_transition.go
tests/transaction_test.go
tests/transaction_test_util.go

Update consensus tests to [v10.4](https://github.com/ethereum/tests/releases/tag/v10.4).

Update consensus tests to 10.4

---

tests/state_test.go
tests/state_test_util.go

Ignore expected errors in TestState

---

turbo/snapshotsync/block_snapshots.go

Reverts ledgerwatch/erigon#4309

Revert "Warn not error when body is missing"

---

consensus/clique/clique.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/24957.
* consensus/clique: remove race condition
* consensus/clique: fix one more signer data race
Co-authored-by: Gary Rong <garyrong0905@gmail.com>

consensus/clique: fix race condition (#24957)

---

eth/stagedsync/stage_headers.go
ethdb/privateapi/ethbackend.go

See https://github.com/ethereum/execution-apis/pull/211, https://github.com/ethereum/execution-apis/pull/213, and https://github.com/ethereum/execution-apis/pull/214.

Update Engine API errors

---

.github/CONTRIBUTING.md

Replaces "go-ethereum" with "Erigon"

Fix CONTRIBUTING.md file

---

eth/stagedsync/README.md

replace with link to stages.go

fix broken link (stagedsync.go)

---

eth/stagedsync/stage_headers.go

Reverts ledgerwatch/erigon#4367

Revert "Handling of already canonical payloads"

---

go.mod
go.sum

Pick up https://github.com/ledgerwatch/erigon-lib/pull/480

Start txpool in AddLocalTxs

---

core/types/block.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/25010

core/types: remove unused field 'td' in Block (#25010)

---

go.mod
go.sum

Errors are like: https://github.com/edsrzf/mmap-go/issues/22

up mmap-go version to solve Win problem

---

cmd/rpcdaemon/commands/bor_helper.go
cmd/rpcdaemon/commands/erigon_block.go
cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_call_test.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/eth_system.go
cmd/rpcdaemon/commands/eth_txs.go
cmd/rpcdaemon/commands/eth_uncles.go
cmd/rpcdaemon/commands/rpc_block.go
cmd/rpcdaemon/commands/rpc_getBlockNumber.go
cmd/rpcdaemon/commands/trace_filtering.go
rpc/types.go
turbo/rpchelper/helper.go
turbo/rpchelper/rpc_block.go

See https://github.com/ethereum/execution-apis/pull/200

safe and finalized blocks from eth_getBlockByNumber

---

go.mod
go.sum

fix for https://github.com/RoaringBitmap/roaring/issues/358

Roaring version up

---

params/chainspecs/chapel.json

Update the Euler fork heigh of the chapel network configuration.
ref: https://github.com/bnb-chain/bsc/pull/885

add eulerBlock in chapel.json

---

docs/programmers_guide/db_faq.md

fixed a minor typo in /docs/programmers_guide/db_faq.md.

fixed typo in db_faq.md

---

rpc/types.go
turbo/rpchelper/helper.go

This is a follow-up to PR #4436.

JSON parsing of safe & finalized

---

DEV_CHAIN.md
README.md
cmd/observer/observer/handshake.go
cmd/observer/observer/handshake_test.go
cmd/observer/observer/sentry_candidates/log_test.go
cmd/observer/observer/server.go
cmd/rpcdaemon/commands/eth_subscribe_test.go
cmd/rpcdaemon/commands/send_transaction_test.go
cmd/rpcdaemon22/commands/eth_subscribe_test.go
cmd/rpcdaemon22/commands/send_transaction_test.go
cmd/sentry/main.go
cmd/sentry/sentry/broadcast.go
cmd/sentry/sentry/eth_handshake_test.go
cmd/sentry/sentry/sentry_api.go
cmd/sentry/sentry/sentry_grpc_server.go
cmd/sentry/sentry/sentry_grpc_server_test.go
cmd/sentry/sentry/sentry_multi_client.go
cmd/utils/flags.go
eth/backend.go
eth/protocols/eth/handler_test.go
eth/protocols/eth/protocol.go
eth/protocols/eth/protocol_test.go
ethdb/privateapi/ethbackend.go
go.mod
go.sum
p2p/dial_test.go
turbo/stages/mock_sentry.go
turbo/stages/sentry_mock_test.go

This reverts commit 16e57aa8a2a94a8ec872b088c9c9f43ac818d979.

Revert "Switch from eth/66 to eth/67 (#4549)"

---

eth/stagedsync/stage_headers.go

This fixes "Invalid GasUsed NewPayload (Syncing)" Hive test.

ReportBadHeaderPoS with memoryOverlay

---

cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_block_test.go

I added tests for `eth_GetBlockByNumber` so if we change `rpchelper.GetBlockNumber` then we won't have to worry if `eth_GetBlockByNumber`

More tests

---

eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go

Reverts ledgerwatch/erigon#4614

Revert "fixed compilation"

---

cmd/rpcdaemon/commands/engine_api.go
core/rawdb/accessors_chain.go
eth/stagedsync/stage_headers.go
ethdb/privateapi/ethbackend.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/stageloop.go

Reverts ledgerwatch/erigon#4604

Revert "Proper Pos block checker when INVALID/ACCEPTED status is sent"

---

eth/stagedsync/stage_headers.go

Te previous logic is useful to ensure, for example, that we don't unwind snapshot blocks on FCUs pointing to old blocks for some reason.
This reverts PR #4636 and restores PR #4466.

Revert "Small simplification of startHandlingForkChoice (#4636)"

---

eth/stagedsync/stage_headers.go

This fixes "Re-Org Back into Canonical Chain" Hive test.

Don't write headBlockHash & co when FCU points to an old canonical block

---

eth/stagedsync/stage_headers.go

safeAndFinalizedBlocksAreCanonical -> writeForkChoiceHashes

---

Makefile

This commit didn't make it into the merged changeset. Sorry!

Fix Makefile grep regex from PR #4677

---

cmd/utils/flags.go

Conflict resolution of @hexoscott's changes to fix #884.

use nested datadir/network path for db supporting legacy

---

eth/stagedsync/stage_headers.go

Separted interrupt logic into a function called handle interrupt.

separated interrupt logic

---

Makefile
cmd/rpcdaemon/commands/eth_system_test.go

Increased timeout for CI to pass with new tests - based on https://github.com/ledgerwatch/erigon/pull/4705

Gas api unit tests

---

params/chainspecs/goerli.json

See https://github.com/ethereum/execution-specs/pull/563

Görli Terminal Total Difficulty

---

.github/workflows/ci.yml
.github/workflows/hive-results.yml

- add step to use latest hive image which supports parsing test run output
- publish hive results to the PR

Hive CI output parse

---

.github/workflows/ci.yml
.github/workflows/hive-results.yml
.github/workflows/hive.yml

- Don't run CI on draft PR
- Run hive on successful CI

hive - run on successful CI

---

cmd/rpcdaemon/commands/trace_adhoc.go

fix(vmtrace): missing pushes

---

hooks/build

switch default pid back to 1000 - for backward compatibility

docker_hub_default_pid

---

eth/backend.go

Fix RemoveContents for non-existing dir

---

rpc/http.go

See https://github.com/ethereum/execution-apis/pull/256

Increase JWT issued-at window to 60s

---

eth/stagedsync/stage_headers.go

More timeout prevention

---

turbo/stages/mock_sentry.go

Fix consensus tests (`go test ./tests/... -tags integration`)

Fix consensus tests

---

cmd/rpcdaemon22/commands/engine_api.go

See https://github.com/ethereum/pm/issues/574#issuecomment-1197771890

No TTD mismatch if there's no TTD in chainConfig yet

---

cmd/utils/flags.go

Signed-off-by: Delweng <delweng@gmail.com>

cmd/utils/flags: fix a typo

---

cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/tracing.go
cmd/rpcdaemon22/commands/trace_filtering.go
cmd/rpcdaemon22/commands/tracing.go

Reverts ledgerwatch/erigon#4861

Revert "fix streaming in error case"

---

cmd/rpcdaemon/cli/config.go

cmd: make sure regular rpc server start is reachable

---

cmd/rpcdaemon/README.md

related to #4876. We can already subscribe to pending blocks

updated eth_subscribe info

---

go.mod
go.sum

for https://github.com/ledgerwatch/erigon-lib/pull/567

Mdbx: semaphore fix release 

---

cmd/rpcdaemon/commands/eth_call.go

Solving nil ptr  issue in eth_CreateAccessList #4920

check if eip-1559

---

.github/workflows/ci.yml
.github/workflows/hive-results.yml

Switch out broken xUnit test output parser for working implementation. 
Tested and working here: https://github.com/RevittConsulting/output-test/pull/4/checks?check_run_id=7692854389

feat(ci): hive xunit output parse

---

internal/ethapi/api.go

Solving issue #4948 by adding `v, r, s` value of zero into bor tx

added VRS hard-coded values

---

cmd/rpcdaemon/commands/eth_filters.go
eth/stagedsync/stage_finish.go

Checking if header is canonical before notifying of new header #4917

notifying header if cannonical

---

internal/ethapi/api.go

Solving issue #4989 by always having a transactions field even when not included.

having transactions

---

cmd/state/commands/check_index.go
cmd/state/commands/opcode_tracer.go
cmd/state/stats/index_stats.go
cmd/state/verify/check_indexes.go

After using state for a number of hours I enhanced it in some places with either better logging to help troubleshoot or take an extra parameter to allow filtering where the previous operation was always at the beginning of the table and I wanted to be able to re-run the command at a further point in the table rather than at the beginning

State logging improvements

---

cmd/hack/hack.go

After using hack for a number of hours I enhanced it in some places with either better logging or adding some message to be shown every N iterations in a few places it was missing

Hack logging improvements

---

.github/workflows/ci.yml
.github/workflows/hive-results.yml

- uncomment the previously failing CI test runs
- use the dockerhub image: https://hub.docker.com/r/thorax/hive

feat(hiveci): thorax dockerhub repo with updated hive

---

params/chainspecs/mainnet.json

See https://github.com/ethereum/execution-specs/pull/585

Mainnet Terminal Total Difficulty

---

go.mod
go.sum

Solving issue #4974 by adding a proper nil ptr check inside of erigon-lib

erigon-lib nill ptr check

---

turbo/stages/headerdownload/header_algos.go

fix stage sync hang at a mined block

---

cmd/rpcdaemon/cli/config.go
turbo/snapshotsync/block_snapshots.go

for https://github.com/ledgerwatch/erigon/issues/5068

fix nil pointer at startup when not all indices available yet

---

README.md
cmd/erigon/main.go

Solving issue #5109 by adding support to slices in yaml and toml files

added config file slice support

---

README.md

Specify execution client

---

docker-compose.yml

reasoning: https://github.com/ledgerwatch/erigon/issues/4780#issuecomment-1222228095

docker-compose.yml explicit datadir

---

cmd/erigon/main.go
ethdb/prune/storage_mode.go

fixed prune flag not working with htrc

---

eth/stagedsync/stage_mining_exec.go

The actual errors are wrapped by `Errorf`, so we need to use `errors.Is`.

Correct classification of errors in addTransactionsToMiningBlock

---

README.md
ethdb/prune/storage_mode.go
turbo/cli/flags.go

This is an alternative to PR #5182.

Fix description of --prune=r flag

---

cmd/sentry/sentry/sentry_multi_client.go

Lower log level as requested in issue: #5157

tweak(sentry): downgrade inbound message handling err to debug

---

Makefile
cmd/evm/staterunner.go
tests/state_test_util.go

- add evm makefile command
- fix evm output (patch from #5077)
- fix uint256 conversion making message

EVM fix - issue #5077

---

turbo/trie/verkle_utils.go
turbo/trie/verkle_utils_test.go

This PR implements this section of the Verkle Tree EIP set: https://notes.ethereum.org/@vbuterin/verkle_tree_eip#Header-values

Added verkle tree key hash generating functions.

---

cmd/sentry/sentry/sentry_grpc_server.go

Recently sentry has started using pubkey as peer-id, but pubkey has unprintable characters.
This PR print peer-id using hex encoding and cutting the output to first 20 characters

Print peer-id using hex encoding to avoid unprintable characters

---

cmd/evm/staterunner.go
tests/state_test_util.go

Looking good fuzzing with geth

fix(evm): fee and tip calc bug #5077

---

eth/stagedsync/stage_headers.go

Sometimes the line gets too long so I divided it into two for better UX

getting rid of breaking line

---

cmd/rpcdaemon/README.md

Should have been included in https://github.com/ledgerwatch/erigon/pull/4567

Add eth_callMany and debug_traceCallMany to README

---

go.mod
go.sum

See https://github.com/holiman/uint256/releases/tag/v1.2.1

Update uint256 to v1.2.1

---

eth/tracers/internal/tracers/4byte_tracer.js
eth/tracers/internal/tracers/evmdis_tracer.js
eth/tracers/internal/tracers/prestate_tracer.js
eth/tracers/internal/tracers/tracers.go

Updated the tracers using geth tracers.

updated tracer js

---

cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon22/commands/trace_filtering.go

fixes https://github.com/ledgerwatch/erigon/issues/5344

fix trace_block response for post merge blocks

---

core/rawdb/bor_receipts.go
eth/stagedsync/stage_execute.go

Bor receipts are not being pruned when pruning in execution stage

pruning bor receipts with receipts

---

eth/stagedsync/stage_headers.go

Slight rephrasing of PR #5376.

Tiny log improvement

---

eth/stagedsync/stage_finish.go
eth/stagedsync/sync.go

Better debugging error messages and changing states

Log stage finish

---

cmd/rpcdaemon/commands/trace_filtering.go
eth/stagedsync/stage_headers.go

Solving issue #5408.
After the merge erigon doesn't have block rewards or uncles anymore

dont check for block reward or uncles if we are tracing POS

---

cmd/verkle/buckets.go
cmd/verkle/incrementAccount.go
cmd/verkle/incrementStorage.go
cmd/verkle/incrementalVerkle.go
cmd/verkle/pedersen_hashstate.go
cmd/verkle/verkle_tree_writer.go
cmd/verkle/workers.go

No deletion involved anymore, no code storage deletion, correct codeHash/CodeSize values and overall less I/O for incremental generation.

Adapted verkle tree generation in preperation of Beverly Hills

---

cmd/lightclient/clparams/config.go
cmd/lightclient/main.go
cmd/lightclient/sentinel/config.go
cmd/lightclient/sentinel/discovery.go
cmd/lightclient/sentinel/gater.go
cmd/lightclient/sentinel/peers/peers.go
cmd/lightclient/sentinel/sentinel.go
cmd/lightclient/sentinel/utils.go
core/types/gen_erigon_log_json.go

LightClient P2P refactoring 

---

go.mod
go.sum

https://github.com/ledgerwatch/erigon-lib/pull/650

update erigon-lib following up erigon-lib pr#650

---

README.md
cmd/erigon/main.go

Currently our config files toml/yaml does not take any other value than a string. This PR solves that
#5489

Config flag upgrade

---

core/types/block.go
core/types/block_test.go
eth/stagedsync/stage_bodies.go
rlp/decode.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go
turbo/stages/bodydownload/body_test.go

This reverts commit 7fc7b91270abefe15be7daa2af235961f0d9c203.

Revert "OOM fix for bodies stage (#5253)"

---

eth/stagedsync/stage_bodies.go
eth/stagedsync/stage_headers.go

… log period.
Should help with https://github.com/ledgerwatch/erigon/issues/5516

feat(headers): log no block headers message when no blocks written #5516

---

cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/trace_types.go

Solving issue #5462 by only getting rid of miner reward when POS

returning validator in POS trace

---

cmd/rpcdaemon/commands/erigon_receipts.go
core/types/gen_erigon_log_json.go
core/types/log.go

Erigonlogs fields are now the same as the Logs but with an extra timestamp field

changed erigon logs fields

---

cmd/lightclient/main.go
cmd/lightclient/sentinel/request.go

better retry

---

core/types/block.go
core/types/block_test.go
eth/stagedsync/stage_bodies.go
rlp/decode.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go
turbo/stages/bodydownload/body_test.go

Brings back the OOM changes with a couple of notable changes:
- logs out timed out peers when we encounter them
- uses a simple in memory map when processing stages in memory

Reintroduce oom fix

---

eth/stagedsync/stage_bodies.go
turbo/stages/bodydownload/body_algos.go

Moves bodies request logic to pre OOM changes.  No logging or checking for timeouts and moving forwards with every request made.  Tested on a local node that went through the DB migration on this branch and worked fine, caught back up to the tip.  Tested on POW initial sync and looked to be working fine writing bodies, although didn't have time to see this run all the way through the merge.

back to existing request bodies logic

---

turbo/snapshotsync/block_snapshots.go

for https://github.com/ledgerwatch/erigon/issues/5651

fix nil ptr in integration

---

cmd/state/commands/erigon23.go
cmd/state/commands/global_flags_vars.go
go.mod
go.sum

-  Fixed commitment issues both erigon3/erigon4
-  get back update-based commitments approach
-  partially fixed state seeking

commitment fixes for erigon4

---

eth/stagedsync/stage_mining_exec.go

Seems simple enough, don't stop on interrupt but start a timer instead and check on each loop if we should stop now or allow the block to finish on its own

wait for at most 500ms when receiving the GetPayload message from CL

---

cmd/rpcdaemon/commands/erigon_receipts.go
cmd/rpcdaemon/commands/eth_receipts.go

Fixing this err= ```EROR[10-13|08:27:56.405] RPC method eth_getLogs crashed: runtime error: index out of range [289] with length 289
[service.go:217 panic.go:838 panic.go:93 eth_receipts.go:222 value.go:556 value.go:339 service.go:222 handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]```

checking if bor log

---

core/state_transition.go

[EIP-3651](https://eips.ethereum.org/EIPS/eip-3651) is part of [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).

core: implement EIP-3651, warm coinbase

---

turbo/builder/block_builder.go

This should fix the following error reported by stickx:

Fix potential nil pointer dereference in NewBlockBuilder

---

ethdb/privateapi/ethbackend.go

This log message is mostly redundant after PR #5792.

Remove verbose and partially redundant log

---

cmd/lightclient/sentinel/peers/peers.go

Change the amount of max peers from 200 -> 33

lowered the amount of max peers

---

accounts/abi/bind/backends/simulated.go
cmd/rpcdaemon/commands/trace_adhoc.go
consensus/aura/aura.go
consensus/aura/config.go
consensus/aura/consensusconfig/poagnosis.json
consensus/aura/contracts/certifier.json
consensus/aura/contracts/embed.go
consensus/bor/bor.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/parlia/parlia.go
consensus/serenity/serenity.go
core/blockchain.go
core/state_processor.go
core/state_transition.go
core/types/transaction.go
eth/stagedsync/stage_mining_create_block.go
tests/state_test_util.go
tests/transaction_test_util.go
turbo/adapter/ethapi/api.go

and the don't pay baseFee after EIP-1559.
See https://openethereum.github.io/Permissioning.html#gas-price

AuRa service transactions are free

---

cmd/devnet/devnetutils/utils_test.go
cmd/devnet/requests/account.go
cmd/devnet/requests/request_generator.go
cmd/devnet/requests/request_generator_test.go
cmd/devnet/requests/requests.go
cmd/devnet/requests/tx.go
cmd/rpctest/rpctest/request_generator_test.go

- Added tests for request_generator in devnet
- Added tests for request_generator in rpctests

Tested functionalities for request_generator

---

cl/rpc/common.go

part of https://github.com/ledgerwatch/erigon/issues/5884. we have tested this manually, but need to include it in the CL client RPC layer.

Adding BeaconBlocksByRangeReq to consensus layer RPC

---

cl/rpc/common.go

https://github.com/ledgerwatch/erigon/issues/5884. 
Follows up on https://github.com/ledgerwatch/erigon/pull/5967 to implement the by root request as well.

Adding BeaconBlocksByRoot req to consensus layer RPC

---

eth/stagedsync/stage_execute.go

It is not being used and it hasn't been used for a while #5847

got rid of effective engine

---

cmd/rpcdaemon/README.md

refactor: add `erigon_getLatestLogs` & fix typo

refactor: add `erigon_getLatestLogs` & fix typo

---

common/sorted.go
consensus/aura/aura.go
ethdb/privateapi/ethbackend.go

Iteration order over go maps is random.

AuRa: iterate over durations in order

---

cmd/rpcdaemon/commands/tracing.go

write trace transaction errors to json and continue

trace json error fix

---

go.mod
go.sum

Reverts ledgerwatch/erigon#6068

Revert "e3: more mainnet snapshots"

---

cmd/sentinel/sentinel/discovery.go

skip connection to private IPs

---

.github/workflows/test-integration.yml

Reverts ledgerwatch/erigon#6097

Revert "e3: enable integration testss"

---

cmd/erigon-cl/cl-core/syncfromcheckpoint.go
cmd/erigon-cl/main.go

Part of https://github.com/ledgerwatch/erigon/issues/5965.

Add get blocks by range request to recent block sync

---

.github/workflows/hive-nightly.yml
README.md

Was not working as expected, and probably necessary now we can see hive result nightly.

tidy(hive): remove badge and generation code

---

core/vm/evm.go
core/vm/gas_table.go

See https://github.com/ethereum/EIPs/pull/6040 & https://github.com/ethereum/tests/pull/1105

Update EIP-3860 according to ethereum/EIPs/pull/6040

---

cmd/erigon-cl/core/transition/process_slots.go
cmd/erigon-cl/core/transition/process_slots_test.go

See https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#beacon-chain-state-transition-function.

Add verify block signature function and unit test

---

cmd/erigon-cl/core/transition/process_slots.go
cmd/erigon-cl/core/transition/process_slots_test.go

See https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#beacon-chain-state-transition-function.

Add state transition function and unit test.

---

cmd/sentry/sentry/sentry_grpc_server.go
core/types/transaction.go
eth/gasprice/gasprice.go
p2p/util.go
turbo/stages/headerdownload/header_data_struct.go

Set the deleted item to its zero val so it can be garbage collected.

Avoiding leaking the popped item

---

common/hasher.go
core/state/plain_readonly.go
turbo/shards/state_cache.go
turbo/trie/hasher.go

for https://github.com/ledgerwatch/erigon/issues/6195

hashers to use sync.pool

---

turbo/stages/headerdownload/header_algos.go

Demote "[Downloader] posAnchor" log to debug

---

cmd/evm/staterunner.go

cmd/evm: show staterooot in result from running statetest

---

cmd/rpcdaemon/commands/tracing.go

Fixes https://github.com/ledgerwatch/erigon/issues/4935

Trace block formatting fix, error handling formatting fix

---

cmd/rpcdaemon/commands/trace_adhoc.go

Fixes https://github.com/ledgerwatch/erigon/issues/4778

vmTrace - prevent panic at stack underflow

---

consensus/aura/aura.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_headers.go
eth/stagedsync/stage_mining_exec.go
turbo/transactions/tracing.go

Support 0-gas service transactions in tracing module.

Fix debug_traceTransaction on Gnosis Chain

---

cmd/rpcdaemon/commands/erigon_receipts.go

fixed tx index being empty

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/eth_txs.go

Get bor state sync tx and receipt has some error:
```
Reqeust:
curl -X "POST" "{{polygon_rpc_endpoint}}" -H 'Content-Type: application/json; charset=utf-8' -d $'{
"jsonrpc": "2.0",
"id": 1,
"method": "eth_getTransactionByHash",
"params": [
"0x9916e99b24daba1fb01e093105bc6988b49125ea15fd4b3c4cfa18719e1631ad"
]
}'
Response:
{"jsonrpc":"2.0","id":1,"result":null}
```
```
Reqeust:
curl -X "POST" "{{polygon_rpc_endpoint}}" -H 'Content-Type: application/json; charset=utf-8' -d $'{
"id": 1,
"method": "eth_getTransactionReceipt",
"jsonrpc": "2.0",
"params": [
"0x9916e99b24daba1fb01e093105bc6988b49125ea15fd4b3c4cfa18719e1631ad"
]
}'
Response
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"EOF"}}
```
fixed:
```
Request:
curl -X "POST" "{{polygon_rpc_endpoint}}" -H 'Content-Type: …
```

Fix eth_getBlockByNumber  and eth_getTransactionReceipt some bugs for polygon

---

cmd/rpcdaemon/commands/eth_subscribe_test.go
cmd/rpcdaemon/commands/send_transaction_test.go
turbo/app/import.go
turbo/stages/mock_sentry.go
turbo/stages/sentry_mock_test.go
turbo/stages/stageloop.go

StagedSync: break dependency to CurrentHeader. Always run non-initial cycle in 1 RwTx

---

core/vm/contract.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/23974

core/vm: simplify op lookup in contract

---

core/rawdb/accessors_chain_test.go
core/vm/interpreter.go
core/vm/jump_table.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/24048

core/vm: avoid memory expansion check for trivial ops

---

Makefile

for https://github.com/ledgerwatch/erigon/issues/6113#issuecomment-1359526277

clang15 warning fix

---

core/vm/instructions.go
core/vm/interpreter.go
core/vm/jump_table.go

Cherry-pick https://github.com/ethereum/go-ethereum/pull/23970

core/vm: Move interpreter.ReadOnly check into the opcode implementations

---

cmd/utils/flags.go
core/genesis.go
core/genesis_test.go
eth/backend.go
eth/ethconfig/config.go
turbo/cli/default_flags.go

and remove `--override.terminaltotaldifficulty` & `--override.mergeNetsplitBlock`

Add override.shanghaiTime flag

---

cl/fork/fork.go
cmd/erigon-cl/core/transition/beacon_state_utils.go
cmd/erigon-cl/core/transition/beacon_state_utils_test.go
cmd/lightclient/lightclient/verify.go

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#randao

Implement ProcessRandao

---

cmd/erigon-cl/core/transition/beacon_state_utils.go
cmd/erigon-cl/core/transition/beacon_state_utils_test.go

Spec: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#eth1-data

Implement ProcessEth1Data

---

core/state/intra_block_state_test.go

Fix intra_block_state_test

---

core/types/block.go
turbo/engineapi/fork_validator.go
turbo/stages/bodydownload/prefetched_blocks.go

Small refactoring after PR #6515.

Unify forkSegment with HeaderAndBody

---

cmd/erigon-cl/core/state/setters.go
cmd/erigon-cl/core/transition/mutators.go
cmd/erigon-cl/core/transition/mutators_test.go

Spec: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#slash_validator

Adding SlashValidator

---

tests/block_test.go

Pick a fix to https://github.com/ethereum/tests/issues/1133

Fix basefee in ethereum tests

---

cmd/rpcdaemon/commands/engine_api.go

Small simplification to PR #6554.

GetEffectiveGasTip in getTxValueForBlockValue

---

eth/stagedsync/README.md

Link ETL Repository

---

eth/stagedsync/default_stages.go
eth/stagedsync/stage_bodies.go

In the vein of PR #5574.
Logs before:
```
[INFO] [01-13|12:37:02.940] [2/16 Headers] Handling new payload      height=25889655 hash=0xe41526b51c04f1a2547d356d4009ff43b9f2e
b8691fce5f0cdc2a9e763b23828
[INFO] [01-13|12:37:02.940] [2/7 Bodies] Writing block bodies        block_num=25889655 remaining=0 alloc=108.4MB sys=222.5MB
[INFO] [01-13|12:37:02.942] [2/16 Headers] Waiting for Consensus Layer... 
```
Logs after:
```
[INFO] [01-13|12:50:55.227] [2/16 Headers] Handling new payload      height=25891426 hash=0x2b890eb0ae6e3ce32fe6cad02d1defebbea71ec27d8c02c42233f369a27f40ad
[INFO] [01-13|12:50:55.237] [2/16 Headers] Waiting for Consensus Layer... 
```

Quiet virtual stage bodies in PoS validator

---

cl/cltypes/attestations.go
cmd/erigon-cl/core/transition/operations.go
cmd/erigon-cl/core/transition/operations_test.go

Spec: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#attester-slashings

ProcessAttesterSlashing

---

cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_ethgetBalance.go

Add test on eth_getBalance() also with vegeta files creation to make performance tests

Add eth_getBalance test

---

core/types/block.go
tests/block_test.go

Pick up https://github.com/ethereum/tests/pull/1147

Wei -> Gwei tests update

---

turbo/stages/bodydownload/body_algos.go

This time incorrect handling of the empty bodies (which should be requested)

More fixes to bodies download

---

cmd/rpcdaemon/commands/erigon_block.go

Got rid of the lasts pr change of test data #6664

Fix erigon get block by time stamp

---

Dockerfile

minor improvement to the Dockerfile

mount caches when building db-tools

---

cl/cltypes/lightclient.go
cl/cltypes/network_test.go
cl/fork/fork.go
cl/rpc/rpc.go
cmd/lightclient/lightclient/lightclient.go
cmd/lightclient/lightclient/process_updates.go
cmd/lightclient/lightclient/store.go
cmd/lightclient/lightclient/subscriber.go
cmd/lightclient/lightclient/verify.go
cmd/sentinel/sentinel/communication/ssz_snappy/encoding.go
cmd/sentinel/sentinel/handlers/heartbeats.go
cmd/sentinel/sentinel/handshake/handshake.go
cmd/sentinel/sentinel/handshake/rules.go
core/types/block.go

* LightClientHeader: Capella
* Added versions to lightclient
* TODO: Capella->Bellatrix transition

Shangai Compatible embedded CL lightclient

---

cmd/abigen/main.go

fix - abigen failed with latest dev version

---

cmd/rpcdaemon/commands/engine_api.go

Implementation of https://github.com/ethereum/execution-apis/pull/364

introduce engine_getCapabilities

---

cl/clparams/config.go
cl/cltypes/justification_bits.go
cl/cltypes/justification_bits_test.go
cl/cltypes/participation_flags.go
cl/cltypes/participation_flags_test.go
cl/cltypes/validator.go
cmd/erigon-cl/core/checkpoint.go
cmd/erigon-cl/core/state/accessors.go
cmd/erigon-cl/core/state/accessors_test.go
cmd/erigon-cl/core/state/getters.go
cmd/erigon-cl/core/state/root.go
cmd/erigon-cl/core/state/setters.go
cmd/erigon-cl/core/state/ssz.go
cmd/erigon-cl/core/state/state.go
cmd/erigon-cl/core/state/test_util.go
cmd/erigon-cl/core/transition/finalization_and_justification.go
cmd/erigon-cl/core/transition/finalization_and_justification_test.go

* Added processing of checkpoints
* Unit tests rigorously imported from prysm
* They all pass :)

Added checkpoints and justification bits processing (post-altair)

---

README.md

Add some missing backticks to the README.

Fix code envs in README

---

consensus/bor/snapshot_test.go
go.mod
go.sum

The Read method of math package used in randomAddress function is not thread safe, instead I've used crand package which is used by matic and is a fork of thread safe crypto package.

fix race condition in snapshot_test

---

cmd/rpcdaemon/commands/engine_api.go
ethdb/privateapi/ethbackend.go
rpc/errors.go
rpc/handler.go

See https://github.com/ethereum/execution-apis/pull/366 and https://github.com/ethereum/execution-apis/pull/370.
Also fix a couple of issues so that the Hive tests pass.

Validate params of GetPayloadBodiesByHash and ByRange

---

cl/clparams/config_test.go

Was only testing `MainnetNetwork` repeatedly before.

test: fix clparams config test

---

cmd/lightclient/lightclient/execution.go
cmd/lightclient/lightclient/lightclient.go
cmd/lightclient/main.go
cmd/sentinel/cli/cliSettings.go
cmd/sentinel/cli/flags/defaultFlags.go
cmd/sentinel/cli/flags/flags.go
eth/backend.go

How to run:
Erigon flags needed: --private.api.addr <ADDR> --externalcl
Lightclient flags needed: --private.api.addr <ADDR>

added separable lightclient

---

turbo/transactions/tracing.go

verified by gateway that the JSON is formed correctly with this change.

fix for missing result in error condition during trace

---

core/forkid/forkid_test.go
params/chainspecs/sepolia.json

See https://github.com/ethereum/execution-specs/pull/716

Schedule Shanghai fork on Sepolia

---

cl/merkle_tree/chunk.go
cl/merkle_tree/list.go
cl/merkle_tree/merkle_root.go
cmd/erigon-cl/core/state/accessors.go
cmd/erigon-cl/core/state/root.go
cmd/erigon-cl/core/transition/process_attestations.go
cmd/erigon-cl/core/transition/process_slots.go
cmd/sentry/sentry/sentry_grpc_server.go

Most notably use of more than a single thread. there is still potential for me but there are more important things for now to work on.

~2x Optimization to state root computation 

---

turbo/stages/bodydownload/body_algos.go

Potentially fixes Issue #6817.

Body downloader: fix empty withdrawals in empty bodies

---

cmd/lightclient/lightclient/subscriber.go

https://github.com/ledgerwatch/erigon/issues/6905

temporary solution for lightclient ratelimit

---

cl/clparams/config.go

See https://github.com/eth-clients/sepolia/pull/30

Schedule Capella on Sepolia

---

DEV_CHAIN.md

Fix typos in DEV_CHAIN.md

---

README.md

Add light client to README.md

---

node/node.go
node/node_test.go
node/utils_test.go

The server attribute was only still used in a broken, skipped unit test which we may rewrite later

Remove unused code from Node struct

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/goerli.json

See https://github.com/ethereum/execution-specs/pull/724 & https://github.com/eth-clients/goerli/pull/160

Schedule Shapella on Görli/Prater

---

cl/clparams/config.go

See https://github.com/eth-clients/goerli/pull/160

Rename SHARDING_FORK to DENEB_FORK

---

cmd/devnet/devnetutils/utils.go
cmd/devnet/services/block.go

- invalid gas price range with max < min
- nonce bumped for transactions that will not be mined

Fix test in devnet tool

---

cmd/rpcdaemon/commands/eth_call.go

Spotted this typo when poking at Cloudflare's public gateway and mapped it back here 🙈

fix typo in eth_call error

---

.github/workflows/download-page.yml
.github/workflows/release.yml
cmd/release/page/main.js

Checksum not working as the file isn't available in the assets when run in the same job.

fix(release): run download page update separately

---

cmd/hack/hack.go
cmd/integration/commands/stages.go
cmd/integration/commands/state_domains.go
cmd/integration/commands/state_stages.go
cmd/rpcdaemon/commands/get_chain_config_test.go
cmd/state/commands/root.go
cmd/utils/flags.go
consensus/aura/aura_test.go
core/genesis.go
core/genesis_test.go
core/rawdb/rawdbreset/reset_stages.go
core/system_contract_lookup.go
turbo/stages/genesis_test.go

Small cosmetic changes and clean-ups

Drop Default from GenesisBlock* functions

---

cmd/rpcdaemon/README.md

add eth_getFilterLogs to docs

---

cmd/rpcdaemon/commands/engine_api.go
consensus/misc/eip4844.go
consensus/misc/eip4844_test.go
core/error.go
core/gaspool.go
core/genesis.go
core/types/block.go
core/types/legacy_tx.go
core/types/transaction.go
core/vm/eips.go
core/vm/evmtypes/evmtypes.go
core/vm/opcodes.go
ethdb/privateapi/ethbackend.go
params/protocol_params.go
turbo/adapter/ethapi/api.go

This PR contains very small EIP-4844 additions. GasPool is modified and now it is a struct with 2 fields "gas" and "dataGas" (blobs are priced in dataGas). ExcessDataGas block header field added. ExcessDataGas needed to compute the data gas price.  EIP-4844 helper functions are added as well.

eip-4844: small additions and modified gaspool

---

.goreleaser.yml

i think issue is https://github.com/golang/go/issues/30310#issuecomment-471669125
i was able to reproduce on my machine using go releaser dry run, and adding this build flag fixed it.
apparently its some glibc issue, what a surprise! :)

hopefully fix #7130

---

consensus/aura/aura.go
consensus/aura/contracts/withdrawal.json

See https://github.com/gnosischain/specs/pull/3

Add maxNumberOfFailedWithdrawalsToProcess to executeSystemWithdrawals

---

ethdb/privateapi/ethbackend.go

Should hopefully help with Issue #7172

Release transaction in EngineGetPayloadBodiesByRangeV1 (and by hash)

---

accounts/abi/bind/backends/simulated.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/otterscan_search_trace.go
cmd/state/exec3/state.go
consensus/parlia/parlia.go
core/blockchain.go
core/evm.go
core/state_processor.go
eth/stagedsync/exec3.go
tests/state_test_util.go
turbo/transactions/call.go
turbo/transactions/tracing.go

Small change in core.NewEVMBlockContext and now it expects excessDataGas. This will be used in state transition to compute data fee for eip-4844 data blobs. The logic that computes it will be added in the next PRs.

eip-4844: NewEVMBlockContext now expects excessDataGas

---

cmd/devnet/commands/all.go
cmd/devnet/commands/block.go
cmd/devnet/models/model.go
cmd/devnet/requests/block.go
cmd/devnet/requests/request_generator.go
cmd/devnet/requests/tx.go
cmd/devnet/services/block.go
cmd/devnet/services/tx.go

- Fix tx numbers expected
- Check for baseFee subpool size too
- Fix tx counting
- Wait for blocks in baseFee subpool to be promoted and mined
- Add BlockNumber request

Some additions to the devnet tool

---

eth/backend.go

This reverts commit 36cce22d811ccd4831c46d7c0435a8bb6b0145fb.

Revert "to fix txpool startup race (#7165)"

---

Makefile
go.mod
go.sum

gohashtree to support go1.20 https://github.com/prysmaticlabs/gohashtree/pull/8

hashtree dep up

---

cmd/rpcdaemon/commands/tracing.go

https://github.com/ledgerwatch/erigon/issues/7248

Fix nullnull issue

---

cmd/rpcdaemon/commands/debug_api.go

Add  json rpc api :
debug_getRawHeader
debug_getRawBlock 
doc:
https://ethereum.github.io/execution-apis/api-documentation/

add api debug_getRawHeader debug_getRawBlock

---

cmd/erigon-cl/core/state/state.go

Before caches were recomputed, now caches are not recomputed anymore for BeaconStates internals

added deep copy to BeaconState copy

---

go.mod
go.sum

port of https://github.com/ethereum/go-ethereum/pull/27027

snappy: arm64 support

---

cmd/caplin-phase1/caplin1/run.go
go.mod
go.sum

Improved CPU usage by 10x, we just really avoid re-compressing and re-validating public keys

Added caching for BLS affines

---

cl/cltypes/beacon_blob_side_car.go
cl/cltypes/beacon_blob_side_car_test.go

This PR adds the new p2p containers from Deneb into Caplin 
#7389

adding deneb p2p containers

---

cmd/rpcdaemon/commands/eth_api.go
cmd/rpcdaemon/commands/eth_receipts.go
core/types/blob_tx_wrapper.go
core/types/transaction_marshalling.go
ethdb/privateapi/ethbackend.go
turbo/adapter/ethapi/api.go

Small additions to support eip-4844 transaction marshalling

eip-4844: RPCTransactions to support BlobTx

---

accounts/abi/bind/backends/simulated.go
cmd/rpcdaemon/commands/eth_block.go
cmd/rpcdaemon/commands/eth_call.go
cmd/rpcdaemon/commands/eth_callMany.go
cmd/rpcdaemon/commands/eth_receipts.go
cmd/rpcdaemon/commands/otterscan_api.go
cmd/rpcdaemon/commands/otterscan_generic_tracer.go
cmd/rpcdaemon/commands/otterscan_search_trace.go
cmd/rpcdaemon/commands/trace_adhoc.go
cmd/rpcdaemon/commands/trace_filtering.go
cmd/rpcdaemon/commands/tracing.go
cmd/state/commands/history22.go
cmd/state/commands/opcode_tracer.go
core/blockchain.go
core/types/legacy_tx.go
core/types/transaction.go
eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/internal/tracetest/prestate_test.go
eth/tracers/tracers_test.go
tests/state_test_util.go
turbo/transactions/call.go

Adding `data_gas` to gas pool. EIP-4844 gas pool includes data_gas which is used to fee blob transactions.

eip-4844: adding data_gas to gaspool

---

cmd/rpcdaemon/commands/eth_receipts.go
consensus/misc/eip4844.go
consensus/misc/eip4844_test.go
core/error.go
core/state_transition.go

Logic to compute fees for data blobs as well as additional check that verifies if user was willing to pay the current `data_gas` price.
Updated `FakeExponential` function to work with uint256.

eip-4844: data gas fees & related check

---

cmd/observer/observer/handshake.go
cmd/observer/observer/handshake_test.go
cmd/sentry/sentry/eth_handshake_test.go
cmd/sentry/sentry/sentry_grpc_server.go
cmd/sentry/sentry/sentry_grpc_server_test.go
cmd/sentry/sentry/sentry_multi_client.go
cmd/utils/flags.go
eth/protocols/eth/handler_test.go
eth/protocols/eth/protocol.go
ethdb/privateapi/ethbackend.go
node/nodecfg/defaults.go
turbo/stages/mock_sentry.go

Set `DefaultConfig.ProtocolVersion` to [68, 67, 66] instead of [67, 68]. See https://github.com/ethereum/hive/pull/776

Prioritize eth/68 by default

---

cmd/downloader/main.go
p2p/enode/localnode.go
p2p/server.go

for https://github.com/ledgerwatch/erigon/issues/7472

Enode logging broke when NAT Parameter set in 2.43.0

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/chiado.json

See https://github.com/NethermindEth/nethermind/pull/5160, https://github.com/NethermindEth/nethermind/pull/5688, and  https://github.com/gnosischain/configs/pull/11

Schedule Shapella on Chiado

---

params/chainspecs/chiado.json

Amend ShanghaiTime for Chiado

---

core/forkid/forkid_test.go

Fix fork ID test for Chiado

---

cl/freezer/.gitignore
cl/freezer/freezer.go
cl/freezer/freezer_test.go
cl/freezer/fs_freezer.go
cl/freezer/mem_freezer.go
cl/freezer/store.go

interface for recording things

[caplin] record mode

---

cmd/erigon-el/backend/backend.go
consensus/bor/bor.go
consensus/bor/contract/client.go
eth/backend.go
params/chainspecs/bor-devnet.json
params/chainspecs/mumbai.json

This PR does the following things:
- Updates the hardfork number of the upcoming Indore hardfork schedule at block 36877056. 
- Refactoring to `CommitStates` method of bor consensus
- Fixes a bug in triggering mining

Indore hardfork for polygon mumbai and fixes in bor consensus

---

consensus/merge/merge.go
core/types/blob_tx_wrapper.go
params/protocol_params.go

See https://github.com/ethereum/EIPs/pull/7154

EIP-4844: Increase Blob Throughput

---

README.md
cmd/utils/flags.go
docker-compose.yml
k8s/google-kubernetes-engine/statefulset-erigon-patch.yaml
node/rpcstack.go
node/rpcstack_test.go
tests/automated-testing/docker-compose.yml

This change adds 'any' as an alternate wildcard to '*'.
I have updated all doc references in the main erigon repo - let me know if there is anywhere else that needs changing.

7667 cli params vhost

---

cl/cltypes/eth1_block.go
cl/phase1/execution_client/execution_engine.go

Added so now we can have version 3 payloads preparing for Deneb

[Caplin] added deneb into converting payload to grpc

---

DEV_CHAIN.md
RELEASE_INSTRUCTIONS.md
TESTING.md
cmd/downloader/readme.md
cmd/rpcdaemon/README.md
docs/evm_semantics.md
docs/merry-go-round-sync.md
eth/stagedsync/README.md
ethdb/Readme.md

Fix: typos

---

core/types/blob_tx_wrapper.go
core/types/transaction_test.go

Fix some issues introduced in PR #7715

Fix lint issues

---

core/types/dynamic_fee_tx.go
core/types/transaction_signing.go

Fix integration tests after ChainID move

---

core/state/rw_v3.go
eth/stagedsync/stage_execute_test.go

Fixes test `TestExec22/UnwindExecutionStagePlainStatic`.

fix for test

---

consensus/bor/bor.go
consensus/bor/contract/client.go

This reverts commit 7671f419f84f7b5a7b5928ef515f6018f5621403.

Revert "Remove excessive logging in bor (#7690)"

---

core/state/rw_v3.go
eth/stagedsync/exec3.go

- `domains.DeleteAccount(kb, list.Vals[k])` - here must be `prev` instead of `list.Vals[k]`
this pr fixing next test: 
```
DISCARD_COMMITMENT=true go test -tags=e4,integration,nosqlite -run='TestDoubleAccountRemoval' -p 1 -v ./turbo/stages
```

e4: fix deleted acc prev

---

turbo/rpchelper/subscription.go

`go test -p 1 -race -count=100 -run='TestFiltersDeadlock_Test' ./turbo/rpchelper/...`

Fix subscription closing race

---

docs/programmers_guide/db_walkthrough.MD

Fix typo in db_walkthrough.MD

---

cmd/sentinel/sentinel/handlers/handlers.go

some people are getting confused by this log. 
it is not really an error anyways.

reduce log level

---

core/blockchain.go

The DAO irregular state change was specific to Ethereum mainnet, while sys calls are not used there.

No need to ApplyDAOHardFork in sys calls

---

core/vm/eips.go
core/vm/gas_table.go
core/vm/instructions_test.go
core/vm/jump_table.go
core/vm/memory.go
core/vm/memory_table.go
core/vm/memory_test.go
core/vm/opcodes.go

Cherry pick https://github.com/ethereum/go-ethereum/pull/26181

core/vm: implement EIP-5656, mcopy instruction

---

consensus/aura/aura.go

Fix an issue with historical block execution introduced by PR #7727

Fix Gnosis sync from scratch

---

cmd/sentinel/cli/cliSettings.go
cmd/sentinel/cli/flags/flags.go
cmd/sentinel/main.go
cmd/sentinel/sentinel/config.go
cmd/sentinel/sentinel/gater.go
cmd/sentinel/sentinel/sentinel.go
p2p/discover/ntp.go

conn gater
so this is what prysm did to address the issue https://github.com/prysmaticlabs/prysm/pull/8648/files

[caplin] conn gater

---

turbo/execution/eth1/eth1_test.go
turbo/execution/eth1/ethereum_execution.go
turbo/execution/eth1/getters.go
turbo/execution/eth1/inserters.go

Prototyped FCU for EL module

---

core/vm/contracts.go
core/vm/runtime/runtime_test.go

See https://github.com/ethereum/EIPs/pull/7172 & https://github.com/ethereum/EIPs/pull/7214

Update EIP-2537 and EIP-4844 precompile addresses

---

core/types/blob_tx_wrapper.go

Fix TestBlobTxWrappedEncodeDecode

---

turbo/engineapi/engine_server.go
turbo/engineapi/engine_server_experimental.go

See the [engine_newpayloadv3](https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md#engine_newpayloadv3) spec

EIP-4844: Verify expectedBlobVersionedHashes

---

accounts/abi/bind/backends/simulated.go
core/evm.go
core/state_transition.go
core/types/blob_tx.go
core/types/blob_tx_wrapper.go
core/types/legacy_tx.go
core/types/transaction.go
core/types/transaction_marshalling.go
core/vm/eips.go
core/vm/evmtypes/evmtypes.go
core/vm/opcodes.go
interfaces.go
turbo/adapter/ethapi/api.go
turbo/engineapi/engine_server.go
turbo/engineapi/engine_server_experimental.go
turbo/execution/eth1/block_building.go
turbo/jsonrpc/eth_receipts.go

See https://github.com/ethereum/EIPs/pull/7001

EIP-4844: rename "data hash" to "blob hash"

---

tests/init.go
tests/state_test.go

See https://github.com/ethereum/tests/releases/tag/v12.3

Upgrade EL tests to v12.3

---

consensus/misc/eip4788.go

See https://github.com/ethereum/EIPs/pull/7431

EIP-4788: set nonce of beacon root history address to nonzero

---

eth/stagedsync/stage_senders.go

This fixes "blob tx is not supported by signer", which occurred in some Hive tests.

Pass proper timestamp in stage senders

---

cl/phase1/execution_client/execution_client_direct.go
cl/phase1/execution_client/execution_client_rpc.go
cl/phase1/execution_client/interface.go
cl/phase1/forkchoice/fork_graph/fork_graph.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/on_attester_slashing.go
cl/phase1/forkchoice/utils.go
cl/phase1/stages/clstages.go
cl/phase1/stages/stage_history_download.go
cl/transition/impl/eth2/validation.go
cmd/caplin-phase1/caplin1/run.go
cmd/sentinel/sentinel/communication/send_request.go
eth/backend.go
turbo/execution/eth1/forkchoice.go

caplin just using execution.proto

[Caplin Phase 2]: Initial working implementation

---

cl/beacon/handler/blocks.go
cl/beacon/handler/handler.go
cl/beacon/router.go
cl/persistence/beacon_indicies/sql_indexer.go
cl/persistence/block_saver.go
cl/persistence/db_config/db_config.go
cl/persistence/db_config/db_config_test.go
cl/persistence/sql_migrations/migrations.go
cl/phase1/execution_client/interface.go
cmd/capcli/cli.go
cmd/caplin-phase1/caplin1/run.go
cmd/caplin-phase1/main.go
eth/backend.go

This PR stores Execution Headers in Caplin when running without storing fullblocks

Caplin: Storing Execution Headers in Caplin

---

cmd/integration/commands/state_domains.go

Fix an issue introduced by PR #8095

Fix applyBlock in commands/state_domains

---

Makefile
cl/persistence/beacon_indicies/sql_indexer.go
cl/persistence/beacon_indicies/sql_indexer_test.go
cl/persistence/block_saver_test.go
cl/persistence/db_config/db_config_test.go
cl/persistence/sql_migrations/migrations_test.go
cmd/capcli/cli.go
cmd/caplin-phase1/caplin1/run.go
go.mod
go.sum

Updating Libs

---

eth/ethconfig/estimate/esitmated_ram.go

https://github.com/ledgerwatch/erigon/issues/8189

reduce amount of index workers

---

metrics/collector.go
metrics/prometheus.go

This fixes issue https://github.com/ledgerwatch/erigon/issues/8181

Group metrics by type and fix missed label stripping

---

eth/tracers/native/call.go

When we call the debug_traceXXX API provided by Erigon, the withLog option in tracerConfig is very helpful.
However, currently, the tracer cannot guarantee that the order of logs output is consistent with the event logs returned in the transaction receipt. This may make it difficult to use the output of the APIs. If you need to access event logs in order, it is recommended to use the event logs returned in the transaction receipt.
Here is an example to illustrate the reason why the order of callTracer logs and receipt eventlogs can be inconsistent: 
In a call trace tree, if a call has multiple logs and this call has multiple child calls, and logs are also output in the child calls, the logs of the child calls may be output between the logs of the parent call in receipt.
I add an index …

add eventlog index when using callTracer withLog

---

eth/tracers/native/call.go

Reverts ledgerwatch/erigon#8195

Revert "add eventlog index when using callTracer withLog"

---

cl/clstages/clstages.go
cl/phase1/stages/clstages.go

A chain gap can occur when peers may not give us enough info

Fixed accidental chain gap

---

core/state_transition.go
core/vm/eips.go
core/vm/jump_table.go
core/vm/opcodes.go

[EIP-7516](https://eips.ethereum.org/EIPS/eip-7516) is part of [devnet-9](https://notes.ethereum.org/@ethpandaops/dencun-devnet-9)

Implement EIP-7516: BLOBBASEFEE opcode

---

consensus/bor/heimdall/client.go

Fix Errorf

---

turbo/engineapi/engine_server.go

See https://discord.com/channels/595666850260713488/892088344438255616/1154413019170869379

Add engine_forkchoiceUpdatedV3 to engine_exchangeCapabilities

---

cl/beacon/handler/format.go
cl/beacon/handler/handler.go

Added support for ssz response

Beacon API: added support octect-stream

---

cl/beacon/handler/blocks.go
cl/beacon/handler/format.go
cl/beacon/handler/handler.go
cl/beacon/handler/states.go
cl/clparams/config.go
cl/cltypes/aggregate.go
cl/persistence/beacon_indicies/sql_indexer.go
cl/persistence/beacon_indicies/sql_indexer_test.go
cl/phase1/cache/attestation_indicies_cache.go
cl/phase1/forkchoice/fork_choice_test.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/on_attestation.go
cl/phase1/network/gossip_manager.go
cl/phase1/stages/clstages.go
cl/spectest/consensus_tests/appendix.go
cl/spectest/consensus_tests/fork_choice.go
cmd/caplin-phase1/caplin1/run.go
cmd/caplin-regression/regression/tester.go
cmd/sentinel/sentinel/service/start.go

Added /eth/v1/beacon/states/{state_id}/root and /eth/v1/beacon/states/{state_id}/fork

Added states/fork and states/root to beacon API

---

core/genesis_write.go
params/chainspecs/holesky.json
params/config.go
params/version.go

Holesky relaunch

---

turbo/jsonrpc/eth_receipts.go

Add support for additional block number values in eth_getLogs

---

turbo/engineapi/engine_helpers/fork_validator.go

Somebody forgot to close temp dbs

Fixed excessive garbage in temporary directory

---

cmd/utils/flags.go

little thing i forgot to fix up.

fixed --internalcl flag for gnosis

---

cmd/utils/flags.go
node/nodecfg/defaults.go

for https://github.com/ledgerwatch/erigon/issues/8396

don't try to create default datadir

---

cmd/rpcdaemon/cli/config.go
cmd/rpcdaemon/cli/httpcfg/http_cfg.go
cmd/utils/flags.go
node/nodecfg/config.go
turbo/cli/default_flags.go
turbo/cli/flags.go
turbo/engineapi/engine_server.go
turbo/jsonrpc/corner_cases_support_test.go
turbo/jsonrpc/daemon.go
turbo/jsonrpc/debug_api_test.go
turbo/jsonrpc/erigon_receipts_test.go
turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_api_test.go
turbo/jsonrpc/eth_block_test.go
turbo/jsonrpc/eth_callMany_test.go
turbo/jsonrpc/eth_call_test.go
turbo/jsonrpc/eth_filters_test.go
turbo/jsonrpc/eth_mining_test.go
turbo/jsonrpc/eth_system_test.go
turbo/jsonrpc/send_transaction.go
turbo/jsonrpc/send_transaction_test.go

Refer to linked issue https://github.com/ledgerwatch/erigon/issues/8381

Re-enable non-EIP155 unprotected txns

---

turbo/jsonrpc/eth_receipts.go

Follow up for #8281 
**Changes**
- Use const in `getLogsIsValidBlockNumber` func

Use const in getLogsIsValidBlockNumber

---

core/types/block.go
core/types/block_test.go

Fixed corrupted transactions in GetPayloadBodies

---

erigon-lib/downloader/downloader.go
erigon-lib/kv/mdbx/kv_mdbx.go
erigon-lib/kv/memdb/memory_mutation.go
p2p/enode/nodedb.go
params/version.go
turbo/engineapi/engine_helpers/fork_validator.go
turbo/execution/eth1/forkchoice.go

Patch release 2.52.1

---

accounts/abi/bind/backends/simulated.go
cmd/state/commands/opcode_tracer.go
consensus/merge/merge.go
consensus/misc/eip4844.go
core/blockchain.go
core/chain_makers.go
core/state_transition.go
core/types/blob_tx_wrapper.go
core/vm/eips.go
erigon-lib/chain/chain_config.go
erigon-lib/common/fixedgas/protocol.go
erigon-lib/txpool/pool.go
erigon-lib/txpool/pool_fuzz_test.go
erigon-lib/txpool/pool_test.go
erigon-lib/txpool/txpooluitl/all_components.go
eth/backend.go
eth/stagedsync/stage_mining_exec.go
params/chainspecs/chiado.json
params/chainspecs/gnosis.json
params/protocol_params.go
tests/state_test_util.go
turbo/engineapi/engine_server.go
turbo/jsonrpc/eth_receipts.go
turbo/stages/mock/mock_sentry.go
turbo/stages/stageloop.go

See https://github.com/gnosischain/specs/pull/20 & https://github.com/gnosischain/specs/pull/24

Configure EIP-4844 parameters for Gnosis

---

core/types/block.go

Small extra check of ReceiptHash

---

cl/cltypes/clone.go
cl/cltypes/eth1_block.go
cl/cltypes/withdrawal.go
cl/phase1/core/state/accessors.go
cl/transition/impl/eth2/operations.go
cl/transition/impl/funcmap/impl.go
cl/transition/machine/machine.go
core/types/withdrawal.go
core/types/withdrawal_test.go

Added separate Withdrawal data type to Caplin

---

.github/workflows/test-integration-caplin.yml
cl/spectest/Makefile
cl/spectest/wmake.ps1

Consensus Specification Tests takes less than 8 minutes so I think they can be in a PR's own CI for whenever it is ready. for reference it is less than make test

CI Job for Consensus specs

---

cmd/caplin-phase1/caplin1/run.go
eth/backend.go

Just does not make it die silently

Verbose --internalcl for whenever we fail at startup

---

Dockerfile.debian
Makefile
README.md
cmd/release/go.mod
erigon-lib/.github/workflows/ci.yml
erigon-lib/go.mod
go.mod
wmake.ps1

Because 1.19 is not working anymore.

go.mod: minimal go version 1.20

---

eth/ethconfig/estimate/esitmated_ram.go

related to https://github.com/ledgerwatch/erigon/issues/8485 and https://github.com/ledgerwatch/erigon/issues/6646

GOMEMLIMIT: support

---

core/state_transition.go
erigon-lib/chain/chain_config.go
params/chainspecs/bor-devnet.json
params/chainspecs/bor-mainnet.json
params/chainspecs/chiado.json
params/chainspecs/gnosis.json
params/chainspecs/mumbai.json
params/config_test.go

burntContract, introduced in PR #8504, is more generic than eip1559FeeCollector

Replace eip1559FeeCollector with burntContract

---

cl/antiquary/antiquary.go
cl/persistence/block_saver.go
cl/persistence/block_saver_test.go
cl/persistence/block_store.go
cl/persistence/interface.go
cl/phase1/network/backward_beacon_downloader.go
cl/phase1/stages/clstages.go
cl/rpc/rpc.go
cl/sentinel/service/service.go
cmd/capcli/cli.go

will do a more advanced version later

Same range parallel downloader

---

consensus/bor/bor.go
core/genesis_write.go
core/state/intra_block_state.go
core/vm/interpreter.go
erigon-lib/chain/chain_config.go
erigon-lib/txpool/pool.go
erigon-lib/txpool/pool_fuzz_test.go
erigon-lib/txpool/pool_test.go
erigon-lib/txpool/txpooluitl/all_components.go
turbo/stages/mock/mock_sentry.go

Fixes and simplifications to PR #8504

Fix wiring of AgraBlock into tx pool

---

cmd/sentry/sentry/sentry_grpc_server.go

Daniel please check whether I fix error or it's expected to be like that

possible error fix

---

eth/tracers/native/call.go

Newly introduced `t.logGaps` was being set to `nil` and still accessed within `clearFailedLogs`. This PR changes the ordering, moving the nil setting to `CaptureTxEnd`.

Fix null ptr in debug_traceTx

---

eth/tracers/native/call.go
params/version.go

Cherry pick https://github.com/ledgerwatch/erigon/pull/8585

Fix null ptr in debug_traceTransaction

---

erigon-lib/downloader/downloadercfg/logger.go

downloader: less webseed logs (#8586)

---

core/forkid/forkid.go
core/forkid/forkid_test.go

otherwise we start losing maticnetwork/bor peers on devp2p

Mumbai: fix fork ID for Agra

---

eth/ethconfig/config.go

Now our timings are 8.6 MB/sec

Bumps down Bodies Timeout from 30 secs to 2 secs

---

cmd/rpctest/main.go
cmd/rpctest/rpctest/bench_debugTraceBlockByNumber.go
cmd/rpctest/rpctest/request_generator.go

added debug_traceBlockByNumber API pattern test

debug_traceBlockByNumber pattern test

---

cmd/state/exec3/state.go
core/state/database_test.go
erigon-lib/kv/mdbx/kv_mdbx.go
erigon-lib/kv/mdbx/kv_mdbx_test.go
erigon-lib/state/domain_committed.go
erigon-lib/state/domain_shared.go
erigon-lib/state/history.go
erigon-lib/state/history_test.go
erigon-lib/state/inverted_index.go
eth/stagedsync/exec3.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_headers.go

-  to use history.IdxRange instead of IteratePrefix
- history.IdxRange(Desc) support
-

e35: SeekCommitment - doesn't see history of commitment

---

turbo/builder/latest_block_built_test.go
turbo/rlphacks/bytes_test.go
turbo/rpchelper/filters_deadlock_test.go
turbo/rpchelper/filters_test.go
turbo/shards/state_cache_test.go
turbo/stages/blockchain_test.go
turbo/stages/bodydownload/body_test.go
turbo/stages/chain_makers_test.go
turbo/stages/genesis_test.go
turbo/stages/headerdownload/header_algo_test.go
turbo/stages/mock/sentry_mock_test.go

Tests that don't affect each other should run in parallel

turbo: run tests in parallel

---

turbo/engineapi/engine_server.go

fixed https://github.com/ledgerwatch/erigon/issues/8746

Fixed getPayloadBodiesByHash

---

cl/phase1/execution_client/execution_client_direct.go
turbo/engineapi/engine_server.go
turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go

Revisit getPayloadBodiesByHash

---

cl/beacon/handler/format.go
cl/beacon/handler/handler.go
cl/beacon/handler/states.go
cl/cltypes/historical_summary.go
cl/cltypes/justification_bits.go
cl/cltypes/solid/bitlist.go
cl/cltypes/solid/pending_attestation.go
cl/cltypes/solid/sync_committee.go
cl/cltypes/solid/sync_committee_test.go
cl/cltypes/solid/validator.go
cl/cltypes/solid/validator_set.go
cl/cltypes/solid/validator_test.go
cl/persistence/beacon_indicies/indicies.go
cl/phase1/core/state/cache_accessors.go
cl/phase1/core/state/raw/state.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/interface.go
cmd/sentinel/cli/flags/flags.go

Added jsonification to beacon state

working debug/state/ for early states

---

cl/beacon/handler/states.go
cl/persistence/base_encoding/primitives.go
cl/persistence/state/state_accessors.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/interface.go
cl/phase1/forkchoice/on_block.go
cl/phase1/stages/clstages.go
cmd/caplin/caplin1/run.go
erigon-lib/kv/tables.go

We store public keys contiguosly and batch update them on forkchoice

Added data model for public keys validator

---

erigon-lib/kv/tables.go
erigon-lib/state/aggregator_v3.go
erigon-lib/state/domain.go
erigon-lib/state/domain_test.go

e35: remove domain.largeValues=false feature (because it was hard to support and not enough profit)

---

tests/erigon-ext-test/go.mod.template

Fixes https://github.com/ledgerwatch/erigon/actions/runs/6930037092/job/18850944152

temp fix for erigon-ext-test

---

p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_lookup_test.go
p2p/discover/v5_udp_integration_test.go
p2p/discover/v5_udp_test.go
p2p/discover/v5wire/encoding_test.go

TestUDPv4_smallNetConvergence tests are often timeout on mac - disabling this tests on mac CI

disable disc tests on Mac

---

.github/workflows/ci.yml
.github/workflows/test-integration-caplin.yml
.github/workflows/test-integration.yml
README.md
erigon-lib/.github/workflows/ci.yml

From comment https://github.com/ledgerwatch/erigon/issues/8623#issuecomment-1831473288

Update mingw cmake version for windows

---

go.mod
go.sum

see https://github.com/erigontech/silkworm-go/commit/c5729e30cfd05ea860c705c318b3395d8a1ed0d6

silkworm: disable on arm64 Linux

---

cmd/utils/flags.go

Spotted this typo when follow the help commond

chore:TxPoolGossipDisableFlag usage

---

Makefile
go.mod
go.sum

https://github.com/erigontech/silkworm-go/commit/61782fa8d0e0fd9605e5c0a3783f4527fe36d975
https://github.com/erigontech/silkworm-go/commit/435dee4642d4d243cf1566e5e16183edbe5b90bb

silkworm: macOS Intel library

---

cl/antiquary/state_antiquary_test.go
cl/persistence/state/historical_states_reader/historical_states_reader_test.go
turbo/stages/stageloop.go

Caplin snapshots only enabled with caplin.backfill

Backfill only with flag

---

erigon-lib/common/dbg/experiments.go
erigon-lib/downloader/util.go
eth/stagedsync/stage_execute.go

use `DOWNLOADER_ONLY_BLOCKS=true STAGES_ONLY_BLOCKS=true` to gen E2 snaps

e35: env DOWNLOADER_ONLY_BLOCKS, STAGES_ONLY_BLOCKS

---

cmd/evm/README.md

use geth found this doc problem https://github.com/ethereum/go-ethereum/pull/28635

cmd/evm:fix Env struct json tag 

---

erigon-lib/state/aggregator_v3.go
erigon-lib/state/domain_shared_test.go

Reverts ledgerwatch/erigon#8950

Revert "e35: minmax exclude"

---

cl/beacon/handler/blocks.go
cl/beacon/handler/handler.go
cl/cltypes/beacon_block_test.go
cl/cltypes/blinded_beacon_block.go
cl/cltypes/eth1_header.go

* Added blinded block for internal uses
* Added blinded block to the Beacon API

Added Blinded blocks type and Beacon endpoints

---

cl/sentinel/handlers/handlers.go
cl/sentinel/handlers/heartbeats.go

* Some requests may lead to undefined behaviour this will make sure to call .Close once

Cleanuped up request handling

---

erigon-lib/commitment/hex_patricia_hashed.go

remove intermediate etl code for commitment updates.

e35: write commitment to domains instead of intermediate etl option

---

erigon-lib/commitment/commitment.go
erigon-lib/commitment/hex_patricia_hashed.go

e35: cleanup commitment update collecting

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/goerli.json

See https://github.com/ethereum/EIPs/pull/8051 & https://github.com/ethereum/execution-specs/pull/860

Schedule Dencun for Görli

---

cmd/integration/Readme.md

Added integration stage_headers command

integration stage_headers

---

cl/beacon/handler/handler.go
cl/beacon/handler/node.go
cl/beacon/handler/node_test.go
cl/beacon/handler/utils_test.go
cl/phase1/core/state/accessors.go
cl/phase1/core/state/cache.go
cl/phase1/forkchoice/fork_choice_test.go
cl/phase1/forkchoice/forkchoice_mock.go
cl/phase1/forkchoice/interface.go
cl/phase1/forkchoice/on_attestation.go
cl/phase1/network/gossip_manager.go
cl/phase1/stages/clstages.go
cl/pool/operation_pool.go
cl/sentinel/service/start.go
cl/spectest/consensus_tests/fork_choice.go
cmd/caplin-regression/regression/tester.go
cmd/caplin/caplin1/run.go

* Added handling of AggregateAndProof

Caplin: Fixed crash in OnAttestation

---

cl/beacon/handler/validators_test.go

https://github.com/ledgerwatch/erigon/issues/9130

disable TestGetValidatorsBalances: oom on CI

---

eth/backend.go

integration test TestMiningBenchmark is failing the CI on devel - this PR aims to fix it

bor: fix for TestMiningBenchmark

---

cl/beacon/handler/handler.go
cl/beacon/handler/pool.go
cl/beacon/handler/pool_test.go
cl/cltypes/solid/attestation.go
cl/phase1/forkchoice/forkchoice_mock.go
cl/phase1/forkchoice/interface.go

Added publishing of aggregates and proofs

Added EthV1AggregateAndProofs API

---

turbo/app/snapshots_cmd.go

This fixes the snapshot uploader start as flags have been moved to default

Remove duplicate flags

---

docs/readthedocs/source/etl.rst
docs/readthedocs/source/rpc/index.rst
docs/readthedocs/source/stagedsync.rst
docs/readthedocs/source/types.rst

Hi, caught a few mistakes while reading the docs. Hope I can be of any help.
Have a nice day.

chore: some proofreading in the docs

---

p2p/dnsdisc/tree.go

similar to https://github.com/ledgerwatch/erigon/pull/9202

refactor(p2p/dnsdisc): replace strings.IndexByte with strings.Cut

---

turbo/engineapi/engine_block_downloader/block_downloader.go

"[EngineBlockDownloader] Downloading PoS headers... height=unknown" might be [confusing](https://discord.com/channels/687972960811745322/1001501454076477450/1197365760125841550) for users.

logs: remove "height=unknown"

---

turbo/engineapi/engine_block_downloader/block_downloader.go
turbo/engineapi/engine_block_downloader/core.go
turbo/engineapi/engine_server.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

DownloaderTip was only written, but never read

Remove downloaderTip

---

turbo/app/snapshots_cmd.go

added to `erigon snapshots rm-state-snapshots` ability to remove intermediate steps if given steps to remove is larger than 1 step. eg want to remove domain steps 1280-1500 but history stop merges after some threshold. All history and index files within range 1280-1500 will be removed.

E35 rm snapshot steps 

---

erigon-lib/downloader/downloader.go
erigon-lib/downloader/downloader_grpc_server.go
erigon-lib/downloader/torrent_files.go
erigon-lib/downloader/webseed.go
eth/backend.go
params/version.go

release: downloader: prohibit_new_downloads.lock check missed download

---

consensus/misc/eip1559.go
erigon-lib/txpool/pool.go

(release) txpool: fix initial blockGasLimit and setBlobFee()

---

turbo/execution/eth1/getters.go

This fixes issues appearing on validator when calling `getPayloadBodiesByRangeV1`
The change follows the [specification (ethereum/execution-apis)](https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#specification-4)

Handle nil in GetBodiesByRange

---

diagnostics/diagnostic.go
diagnostics/snapshot_sync.go
erigon-lib/diagnostics/entities.go
erigon-lib/downloader/downloader.go

Collect snapshot files list in order to show alert in diagnostics if some file has no peers or webseeds

added snapshot files names list collection for diagnostics

---

erigon-lib/kv/remotedbserver/remotedbserver.go
eth/integrity/snap_blocks_read.go
params/version.go
turbo/app/snapshots_cmd.go

(release) RpcDaemon doesn't see recently retired blocks

---

core/forkid/forkid_test.go
params/chainspecs/mumbai.json

This PR adds Napoli HF Block number for Mumbai

add napoli block

---

core/forkid/forkid_test.go
params/chainspecs/mumbai.json
params/version.go

Mumbai: add Napoli block

---

turbo/snapshotsync/freezeblocks/block_snapshots.go

allow: delete bor snaps and re-start erigon - to re-gen them.

bor snaps: gen bor snaps, if they are behind block snaps

---

cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/stages/stage_history_download.go

Fixed error that makes CL not download

---

eth/stagedsync/stage_bor_heimdall.go

@mh0lt this one is very minor, just breaks long lines, cleans unused input args and other super minor stylistic changes - can wait after your bigger PR if you think it may cause merge conflicts

eth/stagedsync: minor code style cleanup of stage_bor_heimdall.go

---

turbo/snapshotsync/freezeblocks/caplin_snapshots.go

Left an Headers type in there :(

Fixed small hiccup in BeaconBlocks snapshots

---

eth/backend.go
go.mod
go.sum

depends on:
https://github.com/erigontech/silkworm/pull/1741
https://github.com/erigontech/silkworm-go/pull/1/files
https://github.com/erigontech/mdbx-go/pull/130 - merged

silkworm: libmdbx version check

---

cl/phase1/network/beacon_downloader.go
cl/phase1/stages/clstages.go
cl/sentinel/service/service.go

Now we are not Epochs-constrained anymore.

Replaced CatchUpEpochs with ForwardDownloader

---

erigon-lib/state/domain_shared.go

roll back to more tested approach

E35 revert domain deletiion

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/mainnet.json

Refer to https://github.com/ethereum/EIPs/pull/8173

Schedule Dencun on mainnet

---

eth/ethconfig/config.go

[release] Add default config for txpool explicitly (#9429)

---

cl/clparams/config.go
core/forkid/forkid_test.go
params/chainspecs/gnosis.json

Refer to https://github.com/gnosischain/configs/pull/33

Schedule Dencun for Gnosis

---

eth/backend.go
turbo/app/import_cmd.go

This PR should solve issue https://github.com/ledgerwatch/erigon/issues/9179

Import PoS blocks implementation 

---

cl/antiquary/antiquary.go
cl/antiquary/state_antiquary.go
cl/antiquary/state_antiquary_test.go
cl/persistence/beacon_indicies/indicies.go
cl/persistence/block_store.go
cl/persistence/state/historical_states_reader/historical_states_reader.go
cl/persistence/state/historical_states_reader/historical_states_reader_test.go
cl/persistence/state/slot_data.go
cl/persistence/state/state_accessors.go
cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/forkchoice_mock.go
cl/phase1/forkchoice/interface.go
cl/phase1/forkchoice/on_attestation.go
cl/phase1/network/gossip_manager.go
cl/phase1/stages/clstages.go
cl/sentinel/gossip.go
cl/sentinel/service/notifiers.go
cmd/caplin/caplin1/run.go
erigon-lib/kv/tables.go

* Minified Beacon Blocks
* Added sparse branching Diffs
* Removed kv.CurrentEpochAttestations and kv.PreviousEpochAttestations
* Never misses a single block on gossip (improved network)
* Simplified blocks insertion
* Added birectional balances links.
* Bugs fixed and overall stability improved.
* Mainnet Archive node size: 144 GB
* States reconstruction time: 1 Day 16 Hours

[Caplin] More efficient Archive format

---

erigon-lib/state/aggregator_test.go
erigon-lib/state/aggregator_v3.go

- to prune earlier 
- some domains will not write/collate/build during execution (but will build later in map-reduce stage)

e35: allow collate/build/integrate 1 domain  

---

README.md

Updated README.md with link to official documentation on Gitbook

Update README.md with link to official documentation on Gitbook

---

tests/init.go

See https://github.com/ethereum/tests/releases/tag/v13.1

Upgrade Ethereum tests to v13.1

---

turbo/execution/eth1/inserters.go

Reverts ledgerwatch/erigon#9476

Revert "el: check gaps early"

---

diagnostics/diagnostic.go
erigon-lib/diskutils/diskutils.go
erigon-lib/diskutils/diskutils_darwin.go
eth/backend.go

- find mount point name from reign data directory 
- get disk info depending on used mount point 
Implemented only on "darwin", I don't have hardware to test on other archs

get disc info depending from chain data path

---

erigon-lib/seg/decompress.go

Fix the last uncovered part calculation in case of a non-empty initial buffer.
Note: in practice we always pass an empty buffer, but the bug was accidentally discovered when I forgot to empty it.
See also:
https://github.com/erigontech/silkworm/pull/1857

snapshots: fix decompressor.Next with a non-empty buffer

---

erigon-lib/diskutils/diskutils_darwin.go

- added check is directory is symbolic link

added check for smlynk

---

erigon-lib/kv/mdbx/kv_mdbx.go

now it panics
for https://github.com/ledgerwatch/erigon/issues/9522

return error when PlainState has empty value 

---

erigon-lib/common/mem/common.go
erigon-lib/common/mem/mem.go
erigon-lib/common/mem/mem_linux.go
eth/backend.go

- Make memory values readable
- Add go heap stats to `LogVirtualMemStats`

metrics: Readable memory values

---

core/state_transition.go

See https://eips.ethereum.org/EIPS/eip-4844#execution-layer-validation for how to `validate_block` with check for sufficient balance

Use maxFeePerBlobGas for balance check

---

eth/ethutils/utils.go
turbo/engineapi/engine_server.go

"all versioned blob hashes must start with VERSIONED_HASH_VERSION_KZG" as per https://eips.ethereum.org/EIPS/eip-4844#execution-layer-validation

Add first byte check for versioned hash

---

core/vm/runtime/runtime.go
erigon-lib/chain/chain_config.go
eth/stagedsync/default_stages.go

Verkle is scheduled for Osaka rather than Prague

Move Verkle to Osaka

---

erigon-lib/downloader/webseed.go

Remove debug print statement from downloadTorrentFilesFromProviders

Remove webseed print statement

---

cl/antiquary/antiquary.go
cl/beacon/handler/blobs.go
cl/beacon/handler/handler.go
cl/beacon/handler/utils_test.go
cl/phase1/stages/stage_history_download.go
cl/sentinel/sentinel_requests_test.go
cmd/capcli/cli.go
cmd/caplin/caplin1/run.go
erigon-lib/downloader/snaptype/type.go
eth/stagedsync/stage_snapshots.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go
turbo/snapshotsync/snapshotsync.go
turbo/stages/mock/mock_sentry.go
turbo/stages/stageloop.go

Antiquates blobs to snapshot format.

Caplin: Added blob's snapshots to Caplin

---

cmd/downloader/main.go
erigon-lib/chain/snapcfg/util.go

problem: we did call `Seedable` with empty network name

torrent_create: support 500K files

---

turbo/jsonrpc/tracing.go

for https://github.com/ledgerwatch/erigon/issues/8721

debug_traceBlockByHash: reject non-canonical hash

---

erigon-lib/txpool/txpool_grpc_server.go

Found this flaw while investigating a Hive test failure ("Withdrawals Fork on Block 1 - 1 Block Re-Org (Paris)").

Don't add last local transaction to txpool if err

---

erigon-lib/downloader/downloader.go

downloader: disable webDownloadClient - feature not ready yet 

---

erigon-lib/downloader/util.go

this code did delete .idx files also

downloader: dont delete torrent files

---

cmd/capcli/cli.go
core/rawdb/accessors_chain.go
erigon-lib/txpool/fetch.go
turbo/snapshotsync/freezeblocks/block_reader.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/bor_snapshots.go
turbo/stages/stageloop.go

this PR is preventing error `err="DumpBlocks: DumpBodies: header missed`

retire blocks: pre-check if db has enough data to build files

---

.github/workflows/qa-tip-tracking.yml

This test measures the ability of Erigon to remain synchronised on the chain tip for a long time.
It needs a database that is close to the tip.

qa tests: add tip-tracking test

---

cl/phase1/network/gossip_manager.go

Handle next cases: 
- it's ok if remote server not started yet - can wait (`Start` is in own goroutine) 
- it's ok if remote server restart sometime - can re-connect
- don't re-connect if Ctrl+C pressed (checked global `ctx` before connect)

GossipManager: grpc stream reconnect and wait for remote server start 

---

erigon-lib/downloader/downloader.go
params/version.go

Cherry pick PR #9757 into the release

Demote downloader hash warnings

---

cmd/devnet/contracts/lib/rlpreader.sol
erigon-lib/downloader/README.md
tests/solidity/contracts/OpCodes.sol

chore: fix typos

---

cl/phase1/stages/clstages.go

This is kind of a low priority issue.
We need blobs corresponding to each blocks, but before we were not checking if we received all of them, now we ask until the request returns the desired amount.

Caplin: Fixed not calling FCU due to faulty blob handling

---

cl/phase1/core/state/accessors.go
cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
cl/phase1/forkchoice/forkchoice.go
cl/phase1/forkchoice/on_attestation.go
cl/phase1/network/gossip_manager.go
cl/sentinel/gossip.go
cl/sentinel/service/start.go
cmd/caplin/caplin1/run.go
cmd/sentinel/main.go

This PR does the following:
* Implement correct handling of beacon proof handler (without aggregation)
* Disable beacon aggregate and sync committee contribution gossip if not in validator mode 
Check implemented: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#beacon_aggregate_and_proof

Correct handling of beacon aggregates

---

accounts/abi/reflect.go
erigon-lib/state/inverted_index.go
turbo/trie/trie_root.go

SonarCloud highlights duplicated code branches as bugs

Remove duplicated branches

---

erigon-lib/common/mem/mem_linux.go

Addresses: https://github.com/ledgerwatch/erigon/pull/9754#discussion_r1529846654

metrics: Fix conversion unit

---

cmd/capcli/cli.go
cmd/caplin/main.go
cmd/sentinel/main.go
cmd/snapshots/main.go
turbo/debug/flags.go

Addresses: https://github.com/ledgerwatch/erigon/pull/9672#discussion_r1533231359

metrics: Add logging to other binaries

---

erigon-lib/diagnostics/provider.go

according to - https://github.com/ledgerwatch/erigon/pull/9787#issuecomment-2019375288

removed returning an error for send func

---

core/forkid/forkid_test.go
params/chainspecs/amoy.json
params/version.go

Napoli block for Amoy network

---

erigon-lib/diagnostics/provider.go

Fixed issue with Context error message

Diagnostics cancel context fix

---

cmd/downloader/main.go
erigon-lib/downloader/webseed.go

For better integration with GH Actions added overview in the end of reports and exit with code 1 in case when met some errors.

exitCode 1 when got webseed errs, added report overview in the end

---

erigon-lib/txpool/pool.go

Fix https://github.com/ledgerwatch/erigon/issues/9834
Let's check and validate blob configurations only if the txn is BlobTx

txpool: check blob fields only if txn is Blob Tx

---

cl/validator/committee_subscription/committee_subscription.go

Caplin encounters an obstruction caused by CommitteeSubsManagement

---

cmd/downloader/main.go

we did make `downloader` more passive (erigon-driven), but it did break `--seedbox` flag also

downloader: `--seedbox` stopped to be self-driven

---

erigon-lib/kv/mdbx/kv_mdbx.go
node/node.go
turbo/app/make_app.go

Fix flags in `init` command

---

cl/beacon/handler/handler.go
cl/beacon/handler/pool.go
cl/beacon/handler/utils_test.go
cl/beacon/handler/validator_test.go
cl/phase1/forkchoice/forkchoice_mock.go
cl/phase1/forkchoice/interface.go
cl/phase1/forkchoice/on_attestation.go
cl/phase1/network/subnets/subnets.go
cl/validator/committee_subscription/committee_subscription.go
cmd/caplin/caplin1/run.go

endpoint: `/eth/v1/beacon/pool/attestations`
https://ethereum.github.io/beacon-APIs/#/Beacon/submitPoolAttestations

caplin: post beacon pool attestations

---

common/debug/log_panic.go
p2p/discover/table.go
p2p/server.go

fixes two minor race conditions

fix race conditions

---

cl/gossip/gossip.go
cl/phase1/network/gossip_manager.go
cl/sentinel/service/notifiers.go
cl/sentinel/service/service.go

fix `IsTopicBeaconAttestation ` and slightly revise notifier.

Caplin: wrong IsTopicBeaconAttestation

---

eth/backend.go
eth/stagedsync/exec3.go
eth/stagedsync/stage.go
eth/stagedsync/stage_execute.go
eth/stagedsync/stage_snapshots.go
eth/stagedsync/stages/metrics.go
eth/stagedsync/stages/stages.go

- added updating prometheus sync metrics once in 180 seconds log loop
https://github.com/ledgerwatch/erigon/issues/8438

Updating sync stages metrics along with DB update

---

cmd/prometheus/dashboards/erigon.json
cmd/prometheus/dashboards/erigon_internals.json

staking - it's some feature to sum 2 graphics - have no idea when it can be useful - only confusing now.

grafana: disable staking 

---

p2p/sentry/sentry_grpc_server.go
p2p/server.go
turbo/stages/headerdownload/header_algos.go

* fix GrpcServer.p2pServer race
* fix HeaderDownload.latestMinedBlockNumber race
see https://github.com/ledgerwatch/erigon/issues/8704

data races running TestMiningBenchmark (#8704)

---

polygon/heimdall/checkpoint.go
polygon/heimdall/heimdall.go

minor tidy up of code I wrote last week

polygon/heimdall: use value receiver for checkpoints sort

---

cl/phase1/network/backward_beacon_downloader.go

```
Gotten unexpected root                   got="[25 97 1 2 224 23 12 23 98 201 172 124 211 121 115 79 189 245 64 97 147 7 148 171 53 37 124 29 33 89 66 161]" expected=0xf09b99bb8c94f0c631625f020805ff21f111fac6f889fe78b9b91e71c6cf16ce
```

beacon downloader: improve logging of hashes

---

erigon-lib/state/aggregator_v3.go

E35 fix npe accumulate

---

.github/workflows/ci.yml
.golangci.yml
common/paths/paths.go
erigon-lib/.github/workflows/ci.yml
erigon-lib/.golangci.yml
erigon-lib/common/datadir/dirs.go
erigon-lib/kv/membatchwithdb/memory_mutation.go
erigon-lib/kv/memdb/memory_database.go
erigon-lib/kv/remotedb/kv_remote.go
erigon-lib/kv/remotedbserver/remotedbserver.go
erigon-lib/seg/compress.go
erigon-lib/tools/golangci_lint.sh
eth/ethconfig/config.go

remove some deprecated linters and fields: https://golangci-lint.run/product/changelog/

golangci-lint v1.57.2

---

erigon-lib/downloader/downloader.go

for https://github.com/ledgerwatch/erigon/issues/9940

downloader: RecalcStat to not expect that something downloading on synced node 

---

cl/antiquary/antiquary.go
turbo/app/snapshots_cmd.go
turbo/snapshotsync/freezeblocks/caplin_snapshots.go

also created https://github.com/ledgerwatch/erigon/issues/9997

`erigon snapshots index: support caplin's files

---

core/types/gen_header_json.go

This should fix https://github.com/ledgerwatch/erigon/issues/9854

Header marshalling/unmarshalling update

---

erigon-lib/chain/chain_config.go

To Follow suit with rest of the naming

chain-config: capital IsOsaka

---

erigon-lib/downloader/downloader.go
erigon-lib/downloader/downloader_grpc_server.go

Reverts ledgerwatch/erigon#10036

Revert "Added downloader request count"

---

erigon-lib/chain/chain_config.go
params/chainspecs/amoy.json
params/chainspecs/bor-devnet.json
params/chainspecs/bor-mainnet.json
params/chainspecs/chiado.json
params/chainspecs/gnosis.json
params/chainspecs/goerli.json
params/chainspecs/mainnet.json
params/chainspecs/mumbai.json
params/chainspecs/sepolia.json

As the other fields are json marshaled into lowerUpper case, we should use the same style.

chore(config): json marshal chainName

---

cl/phase1/network/services/attestation_service.go

fix issue https://github.com/ledgerwatch/erigon/issues/10089

wrong ttl value initialization in expirable lru cache

---

erigon-lib/kv/mdbx/kv_mdbx.go

now: if --pageSize flag not passed - dirty size set to wrong size.

e35: preopen pagesize

---

polygon/sync/storage.go

Before:
If Flush() is blocked while Run() exits after insertBlocks() error or ctx.Done(), some tasks might be still in the queue, the waitGroup is not done, so waitGroup.Wait() won't exit and Flush() might hang (or leak its goroutine).
Solution:
Replace waitGroup with manual counting of tasks and a channel-based signal to Flush().

polygon/sync: fix executionClientStorage.Flush hanging in err cases

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

Update torrent v1.54.2-alpha -> v1.54.2-alpha-7

---

turbo/debug/flags.go

Cherry pick PR #10155 into the release

dvovk/pprof fix (#10155)

---

erigon-lib/downloader/downloader.go
erigon-lib/downloader/webseed.go

Set existing torrent webseeds after download

---

README.md

/mnt/data/erigon$ du -sh
1.5T	.
/mnt/data/erigon$ du -sh *
840G	chaindata
580G	snapshots
...

Update mainnet disk requirements in README

---

p2p/sentry/sentry_multi_client/sentry_multi_client.go
p2p/sentry/status_data_provider.go

Cherry pick PR #10187 into the release

Unnecessary Logs in sentry removed

---

cmd/diag/downloader/diag_downloader.go
cmd/diag/stages/stages.go

url update

---

turbo/execution/eth1/ethereum_execution.go
turbo/execution/eth1/forkchoice.go
turbo/execution/eth1/inserters.go

for https://github.com/ledgerwatch/erigon/issues/10203

Release: fix logs spam

---

turbo/execution/eth1/ethereum_execution.go
turbo/execution/eth1/forkchoice.go
turbo/execution/eth1/inserters.go

Fix logs spam (#10211)

---

erigon-lib/go.mod
erigon-lib/go.sum
go.mod
go.sum

torrent v1.54.2-alpha-7 -> v1.54.2-alpha-8

---

core/rawdb/rawdbreset/reset_stages.go
core/state/rw_v3.go
erigon-lib/kv/kv_interface.go
erigon-lib/kv/mdbx/kv_mdbx.go
erigon-lib/kv/tables.go
erigon-lib/state/aggregator.go
erigon-lib/state/aggregator_test.go
erigon-lib/state/domain_shared.go
erigon-lib/state/domain_shared_test.go
erigon-lib/state/inverted_index.go
eth/stagedsync/stage_custom_trace.go

reduce amount of hard-coded CRUD methods.
default CRUD methods.

Custom domain write: step 1
