- tests/bor/mining_test.go
- tests/exec_spec_test.go
TestExecutionSpec takes significant time to run (12s for me),
and frequently timeouts on Windows PR builds:
https://github.com/ledgerwatch/erigon/actions/runs/5974942021/job/16235304043?pr=8077
Same with bor.TestMiningBenchmark:
https://github.com/ledgerwatch/erigon/actions/runs/6024465717/job/16343219099
Move it to the integration workflow where the timeout is longer.
> ci: move TestExecutionSpec and TestMiningBenchmark to integration test suite

- cmd/integration/commands/state_domains.go
- cmd/state/commands/erigon4.go
- cmd/state/commands/opcode_tracer.go
- cmd/state/exec3/state.go
- cmd/state/exec3/state_recon.go
- consensus/aura/aura.go
- consensus/aura/aura_test.go
- consensus/bor/bor.go
- consensus/bor/fake.go
- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- consensus/merge/merge.go
- core/blockchain.go
- core/chain_makers.go
- core/state/intra_block_state.go
- eth/stagedsync/stage_mining_exec.go
- turbo/jsonrpc/trace_filtering.go
- turbo/transactions/tracing.go
Now all protocol-stipulated changes at the beginning of the block (AuRa stuff, [DAO](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md) irregular state change, Calcutta system contract upgrade, [EIP-4788](https://eips.ethereum.org/EIPS/eip-4788) beacon root) are handled by consensus engine `Initialize()`.
> Move ApplyDAOHardFork & UpgradeBuildInSystemContract to engine.Initialize

- cmd/sentry/sentry/eth_handshake.go
- cmd/sentry/sentry/sentry_grpc_server.go
- cmd/sentry/sentry/sentry_grpc_server_test.go
- p2p/message.go
- p2p/peer.go
- p2p/peer_error.go
- p2p/peer_test.go
- p2p/protocol.go
- p2p/server.go
- p2p/simulations/test.go
- p2p/transport_test.go
- rlp/decode.go
Improve p2p error handling to propagate errors
from the origin up the call chain the Server peer removal code
using a new PeerError type containing a DiscReason and a more detailed description.
The origin can be tracked down using PeerErrorCode (code) and DiscReason (reason)
which looks like this in the log:
> [TRACE] [08-28|16:33:40.205] Removing p2p peer                        peercount=0 url=enode://d399f4b...@1.2.3.4:30303 duration=6.901ms err="PeerError(code=remote disconnect reason, reason=too many peers, err=<nil>, message=Peer.run got a remote DiscReason)"
> p2p: refactor peer errors to propagate with a DiscReason

- turbo/jsonrpc/trace_adhoc.go
vmtrace routine wasn't outputting the memory extcodecopy has written.
> fix: correctly process extcodecopy in vmtrace

- turbo/jsonrpc/eth_block.go
The FIX is necessary to permit to use API also in case block is in the snapshot files
> RPCdaemon: fix to work also with snapshot

- cl/phase1/core/state/lru/lru.go
- cl/phase1/core/state/ssz.go
- cl/transition/impl/eth2/operations.go
- cl/transition/machine/block.go
- cmd/caplin-regression/main.go
- cmd/erigon/main.go
- cmd/integration/commands/state_domains.go
- cmd/sentinel/sentinel/peers/manager.go
- consensus/bor/heimdall/metrics.go
- core/blockchain.go
- eth/stagedsync/all_stages.go
- metrics/collector.go
- metrics/exp.go
- metrics/prometheus.go
- metrics/register.go
- metrics/timer.go
- p2p/metrics.go
- p2p/peer.go
- p2p/transport_test.go
- rpc/metrics.go
- turbo/debug/flags.go
- turbo/shards/state_cache.go
This is a non functional change which consolidates the various packages under metrics into the top level package now that the dead code is removed.
It is a precursor to the removal of Victoria metrics after which all erigon metrics code will be contained in this single package.
> moved metrics sub packages types to metrics

- turbo/snapshotsync/freezeblocks/block_snapshots.go
Problem was errgroup subroutines finished before their logs could internally trigger
> Fixed snapshots logging

- p2p/peer.go
- p2p/peer_error.go
see:
https://github.com/ethereum/go-ethereum/pull/27887
> p2p: limit ping requests from a single peer

- metrics/collector.go
This is a fix for 
```cache_total{target="acc_read"} counter it's invalid syntax of metric type. prometheus parsing error```
which does not remove the whole metadata tag
> Strip labels when writing metric metadata

- metrics/prometheus.go
- metrics/register.go
Metrics handler was missing erigon-lib metrics - which where added to the VM default set 
This fixes that whilst avoiding duplicates from erigon registrations
> Added write of vm default set to metrics

- eth/stagedsync/stage_execute.go
A potential small fix that I made while looking at the Polygon bad header issue (don't think it's the root cause though).
> Don't mark block as bad if execution was cancelled

- eth/ethconsensusconfig/config.go
Fix ``CreateConsensusEngineBareBones`` for bor and aura. Current codes will pass a ``**chain.BorConfig`` or ``**chain.AuraConfig to`` ``CreateConsensusEngine`` and cause a panic
> config: fix CreateConsensusEngineBareBones

- core/genesis_write.go
This reverts commit 438dd6bdb133048eafd67ceccae1cf8860701489.  Broke CI. Reverted. Will make another PR.
> Revert "remove extra data from holesky genesis (#8207)"

- cmd/silkworm_api/snapshot_idx.go
In order to assess Silkworm recsplit index creation capability we need some utils to trigger native (go) index creation
> Add util to test native recsplit index creation

- turbo/adapter/ethapi/api.go
This PR adds the ability to pass `input` instead of `data` in `eth_call`.
Go-ethereum has support for the `input`-attribute (instead of the `data`) in `eth_call` for some time. The recent go-ethereum release v1.13.0 changed the ethclient to do a `eth_call` with the `input` attribute rather than "data". This makes the latest go-ethereum ethclient incompatible with erigon.
> turbo/adapter/ethapi: Add `CallArgs.Input` attribute

- .github/workflows/ci.yml
- .github/workflows/test-integration.yml
- README.md
It's safer to have branches for individual release series like `release/2.50` for 2.50.x releases instead of overwriting `stable`. geth does that already.
> Support release/x.xx branches in CI

- eth/stagedsync/exec3.go
Post fix to PR #8197. [This integration test failure](https://github.com/ledgerwatch/erigon/actions/runs/6212734514/job/16863165117) should be fixed now.
> Fix e3 integration tests

- eth/backend.go
Apparently `log.New()` doesn't discard messages. Before this change I saw the following in the console log:
```
[INFO] [09-27|15:25:36.225] [NewPayload] Handling new payload        height=18227379 hash=0xa82630b9acf814930f18b45cad533a635076eaaf8e0ae596914d906db02ea3aa
[INFO] [09-27|15:25:36.624] [5/7 Execution] Completed on             block=18227379
[INFO] [09-27|15:25:37.245] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
[INFO] [09-27|15:25:37.854] RPC Daemon notified of new headers       from=18227378 to=18227379 hash=0xa82630b9acf814930f18b45cad533a635076eaaf8e0ae596914d906db02ea3aa header sending=9.615µs log sending=336ns
[INFO] [09-27|15:25:37.854] head updated …
```
> Subdue logging from stages in inMemoryExecution

- erigon-lib/kv/mdbx/kv_mdbx.go
- node/node.go
This is to fix an issue with resource usage if the db.size.limit is increased from its default setting of 2TB.  This is applied to the chain DB, but should not be used on the consensus DB which has smaller data requirements. Expanding both DBs results in excessive RAM being reserved by the underlying OS.
> Only reduce the consensus db size based on flags values

- cmd/evm/internal/t8ntool/transition.go
fixing crash on consensus/merge/merge.go#Initialize function, on this line.
```
chain.Config().IsCancun(header.Time)
```
> fix t8n call to ExecuteBlockEphemerally by passing chainReader

- erigon-lib/kv/mdbx/kv_mdbx.go
- node/node.go
- params/version.go
This is to fix an issue with resource usage if the db.size.limit is increased from its default setting of 2TB. This is applied to the chain DB, but should not be used on the consensus DB which has smaller data requirements. Expanding both DBs results in excessive RAM being reserved by the underlying OS.
> Only reduce the consensus db size based on flags values (#8321)

- turbo/engineapi/engine_helpers/fork_validator.go
- turbo/engineapi/engine_server.go
- turbo/engineapi/interface.go
- turbo/stages/headerdownload/header_data_struct.go
Changes:
Reorder some Engine API invalid checks to be closer to specs/hive tests
Move the Engine API direct method names to `interfaces`
> Fix some hive tests

- eth/tracers/logger/access_list_tracer.go
- turbo/jsonrpc/eth_call.go
This builds upon #3453 and #3524, which previously implemented gas optimizations for the access lists generated by Erigon's implementation of the `eth_createAccessList` RPC call.
Erigon currently optimizes inclusion of the recipient address based on how many storage keys are accessed, but does not perform the same optimization for sender address and precompiled contract addresses. These changes make the same optimization available for all of these cases.
Additionally, this handles the cases of block producer address and created smart contract addresses. If these cases were omitted on purpose since they heavily rely on state, it may still make sense to offer them to users but disable them by default.
> Extend gas optimization for eth_createAccessList

- turbo/jsonrpc/eth_call.go
Enable gas optimizations of PRs #3453 & #8261 unless the `optimizeGas` argument is explicitly set to `false`.
> Optimize gas by default in eth_createAccessList

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/util.go
-  don't start server listener. it may stick port for some time and can be assumed as port-scanning-activity
> downloader: don't probe port naive way 

- consensus/bor/heimdall/client.go
- eth/borfinality/whitelist.go
- eth/borfinality/whitelist_helpers.go
When a new feature (like for the upcoming `Aalborg` hard fork) for Polygon hasn't kicked in (in heimdall), the endpoints of heimdall will now return 503 (Service Unavailable) status code. This PR makes sure that erigon handles that code separately and doesn't keep retying to fetch info. It also acts as a notifier of the HF in erigon. 
Similar reference PR in bor: https://github.com/maticnetwork/bor/pull/1023
> eth, consensus/bor: handle 503 response from heimdall

- eth/borfinality/whitelist.go
- eth/borfinality/whitelist_helpers.go
This PR adds a few checks on top of https://github.com/ledgerwatch/erigon/pull/8364 to prevent access logging. Moreover, fixes a bug which sent wrong error to parent function.
> eth/borfinality: handle errors to prevent access logging

- erigon-lib/txpool/pool.go
- erigon-lib/txpool/pool_fuzz_test.go
As per [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559) , there is only initial base fee after which it adjusts automatically. There are no current references to a minimum protocol base fee on Ethereum, Gnosis or Polygon.
The existing code would put a 7 wei minimum limit on transactions to be included in the pool. This PR removes this check within txPool. Any transaction can now be added to the `queued` sub-pool after which it could get promoted to `pending` or `baseFee` subpools.
The`pricelimit` flag still exists and acts on non-local transactions as a minimum feeCap for inclusion.
> Remove protocolBaseFee checks

- cmd/utils/flags.go
- eth/stagedsync/stage_bor_heimdall.go
- Made milestones enabled by default, since it has now been tested on devnets
- Small bug fix which fixes nil panic while minning
> fix bor.milestone flag

- eth/borfinality/whitelist.go
- eth/borfinality/whitelist_helpers.go
- eth/stagedsync/default_stages.go
- eth/stagedsync/stage_bor_heimdall.go
Don't log every sync event action, but gather stats and print every 30 secs
> Bor reduce logging verbosity

- eth/stagedsync/stage_headers.go
TruncateCanonicalHash should only have all pruned in the case of a badBlock or a fork unwind
> Prune all only on unwindBlock

- cmd/devnet/main.go
- cmd/sentry/sentry/broadcast.go
- cmd/sentry/sentry/sentry_multi_client.go
- consensus/bor/bor_test.go
- core/types/block.go
- eth/stagedsync/stage_headers.go
- turbo/stages/bodydownload/body_algos.go
- turbo/stages/bodydownload/body_data_struct.go
- turbo/stages/bodydownload/body_test.go
Fixes and issue with Polygon validators where locally mined blocks are broadcast with invalid header hashes because the NewBlock message constructor was removing the ReceiptHash which contributed to the header hash.
The results in the bor header validation code not being able to correctly identify the signer of the header - so header validation fails.
This also likely fixes part of the bogon-block issue which was identified by the polygon team.
> Fix invalid pre-fetched header broadcast

- cmd/devnet/main.go
- cmd/sentry/sentry/broadcast.go
- cmd/sentry/sentry/sentry_multi_client.go
- consensus/bor/bor_test.go
- core/types/block.go
- turbo/stages/bodydownload/body_algos.go
- turbo/stages/bodydownload/body_data_struct.go
- turbo/stages/bodydownload/body_test.go
Fixes and issue with Polygon validators where locally mined blocks are broadcast with invalid header hashes because the NewBlock message constructor was removing the ReceiptHash which contributed to the header hash.
The results in the bor header validation code not being able to correctly identify the signer of the header - so header validation fails.
This also likely fixes part of the bogon-block issue which was identified by the polygon team.
> Fix invalid pre-fetched header broadcast (#8442)

- cmd/sentry/sentry/sentry_multi_client.go
This PR removes the empty headers check when responding to `GetBlockHeaders` p2p request. Currently, as we return from the function, the requests on the caller's end gets timed out causing peer drop. This will prevent that from happening by sending empty header list which will be of no use but still helps in maintaining the peer connection. 
With this change, those running erigon 2.48 with `--sentry.drop-useless-peers` will drop peers as they consider receiving empty headers a harsh move which is fine. 
We have also discovered that if we don't remove this check maintaining connectivity to Bor is not maintained.  This is  significant as Erigon becomes a minority validator, as bor chain stability (reducing forks) is dependent upon good validator connectivity.
> cmd/sentry: remove empty headers check

- cmd/devnet/main.go
Add the possibility to change the RPC address used in `devnet` without requiring a rebuild.
> chore(devnet): add `rpc.host` and `rpc.port` flags in `devnet` cmd

- core/types/block.go
This PR is a follow-up of #8442.
1. The previous PR resolved the issue where newly mined blocks had their receipt hash set to an empty root hash. But I think it introduced an issue where the new blocks include no transactions. So this PR addresses that.
2. On top of that, this new PR introduces a validation step for the receipt hash when peers receive new blocks at the p2p layer. If the receipt hash is set to the empty root hash, but the block contains transactions, it will now raise an error.
- When running a local erigon devnet with the new receipt hash check and before #8442 fix (with a few more logs).
**=> error message: `newBlock66: block has empty receipt hash: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 but it includes 2 transactions`**
```sh
Received new block …
```
> fix: newly mined blocks now include transactions and check new blocks with empty receipt hash

- consensus/bor/bor.go
- eth/stagedsync/stage_headers.go
- turbo/stages/headerdownload/header_algos.go
- turbo/stages/headerdownload/header_data_struct.go
If HeaderDownload.VerifyHeader always returns false, the memory usage grows at a fast pace
due to Link objects (containing headers) not deallocated even after the link queue pruning.
> sync: fix a memory leak when header verification fails

- erigon-lib/downloader/downloader.go
- erigon-lib/txpool/txpooluitl/all_components.go
db must not use "Durable" and "SyncPeriod" in same time
txpool and downloader must be: Durable
nodedb:  SafeNoSync+SyncPeriod
because txpool and downloader already can call sync when they need (txpool after regular flush, downloader after piece download+validation completion).
> mdbx: don't mix modes

- consensus/bor/bor.go
on 16-core mumbai's initFrozenSnapshot took 10min (to 38M block)
> bor initFrozenSnapshot: parallel erecover

- p2p/server.go
Problem:
"Started P2P networking" log message contains port zero on startup, e.g.: 127.0.0.1:0 because of the outdated localnodeAddrCache.
Solution:
Call updateLocalNodeStaticAddrCache after updating the port.
> p2p: bad p2p server port in the log

- .github/ISSUE_TEMPLATE/bug.md
- README.md
- cmd/devnet/README.md
- cmd/evm/testdata/3/readme.md
- cmd/evm/testdata/4/readme.md
- cmd/evm/testdata/8/readme.md
- docs/examples/single-process.md
- docs/programmers_guide/guide.md
- erigon-lib/kv/temporal/historyv2/readme.md
Spell Check: 
Concensus --> Consensus
prodiced --> produced
configuraion --> configuration
cabable --> capable
structue --> structure
eample --> example
nework --> network
configration --> configuration
regestering --> registering 
registratio --> registration
excuted --> executed
Simlarly --> Similarly
dictactes --> dictates
respresented --> represented
lengthes --> lengths
> Spell Check: Fix typos

- erigon-lib/types/txn.go
- erigon-lib/types/txn_test.go
N.B. [eth/68](https://eips.ethereum.org/EIPS/eip-5793) is implemented by `EncodeAnnouncements` in `erigon-lib/rlp/encodel.go`
> eth/68: always announce tx sizes with envelopes

- eth/stagedsync/stage_execute.go
Currently we cannot use Silkworm execution if r/w transaction is a memory mutation
> Use Erigon execution for memory mutations

- erigon-lib/go.mod
- erigon-lib/go.sum
- erigon-lib/kv/kv_interface.go
- erigon-lib/kv/mdbx/kv_mdbx.go
- erigon-lib/kv/mdbx/kv_mdbx_temporary.go
- erigon-lib/kv/remotedb/kv_remote.go
- eth/backend.go
- go.mod
- go.sum
- turbo/silkworm/silkworm.go
This introduces _experimental_ RPC daemon run by embedded Silkworm library. Same notes as in PR #8353 apply here plus the following ones:
- activated if `http` command-line option is enabled and `silkworm.path` option is present, nothing more is required (i.e. currently, both block execution and RPC daemon run by Silkworm when specifying `silkworm.path`, just to keep things as simple as possible)
- only Execution API endpoints are implemented by Silkworm RPCDaemon, whilst Engine API endpoints are still served by Erigon RPCDaemon
- some features are still missing, in particular:
- state change notification handling
- custom JSON RPC settings (i.e. Erigon RPC settings are not passed to Silkworm yet)
> Add RPC daemon using Silkworm

- core/types/access_list_tx.go
- core/types/accounts/account.go
- core/types/blob_tx.go
- core/types/block.go
- core/types/dynamic_fee_tx.go
- core/types/legacy_tx.go
- eth/protocols/eth/protocol.go
Use `ListPrefixLen` & `StringLen` from erigon-lib more
> Simplify RLP size calculations

- erigon-lib/rlp/encode.go
- erigon-lib/rlp/encode_test.go
Should fix the [following issue](https://discord.com/channels/687972960811745322/738982866670714901/1164291343745568858):
```
git_branch=devel git_tag=v2.52.0-50-g82f1e9f34-dirty git_commit=82f1e9f342ae46d38f41b0561f879f192cdd8fa0
[WARN] [10-18|19:40:19.892] newPayload failed                        err="rlp: element is larger than containing list"
[WARN] [10-18|19:40:19.892] fail to process block                    reason="rlp: element is larger than containing list" slot=7569470
```
> Fix rlp.EncodeString for length 56

- erigon-lib/types/txn.go
- erigon-lib/types/txn_test.go
It turns out that Marius got it the other way round in Issue #8456. See https://discord.com/channels/595666850260713488/1162151688816308245
> eth/68: always announce tx sizes without envelopes

- README.md
By default sentinel is embedded and direct
> remove sentinel port from README

- erigon-lib/txpool/pool.go
Fixes a nil pointer panic in the isagra check when running on an empty chain db.  In this case the block will return as nil with no error.
> Fix panic in isAgra check for txpool

- erigon-lib/metrics/register.go
- erigon-lib/txpool/pool.go
Calling vm to get a metric and then preregistering it to avoid duplication is expensive.
To avoid this we can make a local lookup first which is a map this quicker. This is a temporary fix
until vm is removed at which point we'll have a single prom_client registry
Fixes: https://github.com/ledgerwatch/erigon/issues/8558
> Fix metrics get perf regression

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
Historically we had several times when:
- erigon downloaded new version of .seg file
- or didn't finish download and start indexing
this was a "quick-fix protection" against this cases
but now we have other protections for this cases
let's try to remove this one - because it's not compatible with "copy datadir" and "restore datadir from backup" scenarios
> sapshots: remove modtime protection

- Makefile
- erigon-lib/go.mod
- erigon-lib/go.sum
- go.mod
- go.sum
```
error: conflicting types for ‘mdbx_get_datacmp’ due to enum/integer mismatch; have ‘int (*(unsigned int))(const MDBX_val *, const MDBX_val *)’ {aka ‘int (*(unsigned int))(const struct iovec *, const struct iovec *)’} [-Werror=enum-int-mismatch]
26609 | __cold MDBX_cmp_func *mdbx_get_datacmp(unsigned flags) {
|                       ^~~~~~~~~~~~~~~~
mdbx.h:4932:1: note: previous declaration of ‘mdbx_get_datacmp’ with type ‘int (*(MDBX_db_flags_t))(const MDBX_val *, const MDBX_val *)’ {aka ‘int (*(MDBX_db_flags_t))(const struct iovec *, const struct iovec *)’}
```
can't upgrade mdbx version for now
> make db-tools: suspend enum-int linter error

- erigon-lib/txpool/fetch.go
read transaction was opened before stream.Recv(), but stream.Recv() is blocking infinity loop. so, this read transaction never rollback - causing unlimited db grow.
---------
Merge PR #8596 into `devel`
> Txpool: db unlimited grow fix (#8596)

- cmd/rpcdaemon/README.md
- cmd/rpcdaemon/cli/config.go
- cmd/rpcdaemon/cli/httpcfg/http_cfg.go
- cmd/utils/flags.go
- node/endpoints.go
- turbo/cli/default_flags.go
- turbo/cli/flags.go
new flag examples.
--https.enabled
--https.addr="0.0.0.0"
--https.port=443
--https.url="unix:///file.wow"
--https.cert="keyfile.cert" 
--https.key="certfile.cert"
also adds support for h2c to the http handler - http2 protocol without tls.
> Enable h2c for http handler. add https handler for http2

- cmd/devnet/accounts/accounts.go
- cmd/devnet/args/node.go
- cmd/devnet/args/node_args.go
- cmd/devnet/args/node_args_test.go
- cmd/devnet/devnet/context.go
- cmd/devnet/devnet/network.go
- cmd/devnet/devnet/node.go
- cmd/devnet/main.go
- cmd/devnet/requests/account.go
- cmd/devnet/requests/admin.go
- cmd/devnet/requests/block.go
- cmd/devnet/requests/event.go
- cmd/devnet/requests/request_generator.go
- cmd/devnet/requests/trace.go
- cmd/devnet/requests/transaction.go
- cmd/devnet/requests/tx.go
- cmd/devnet/services/accounts/faucet.go
- cmd/devnet/services/polygon/checkpoint.go
- cmd/devnet/services/polygon/heimdall.go
- cmd/devnet/services/polygon/proofgenerator.go
- cmd/devnet/services/polygon/statesync.go
- cmd/devnet/transactions/tx.go
- cmd/utils/flags.go
- consensus/bor/bor.go
- params/config.go
- rpc/http.go
- rpc/websocket.go
* fix "genesis hash does not match" when dev nodes connect  
The "dev" nodes need to have the same --miner.etherbase in order to generate the same genesis ExtraData by DeveloperGenesisBlock(). Override DevnetEtherbase global var that's used if --miner.etherbase is not passed. (for NonBlockProducer case)
* fix missing private key for the hardcoded DevnetEtherbase  
Fixes panic if SigKey is not found. Bor non-producers will use a default `DevnetEtherbase` while Dev nodes modify it. Save hardcoded DevnetEtherbase/DevnetSignPrivateKey into accounts so that SigKey can recover it.
* refactor devnet.node to contain Node config  
This avoids interface{} type casts and fixes an error with Heimdall.validatorSet == nil
* add connection retries to rpcCall and Subscribe of requestGenerator  
Fixes …
> devnet: configuration fixes

- turbo/jsonrpc/bor_snapshot.go
At `turbo/jsonrpc/bor_snapshot.go:239` creates read only transaction and acquire semaphore but does not rollback or commit transaction and unrelease semaphore lock. Over time, this will result in the locking all of semaphore resources. Any other resources can't acquire semaphore. 
I added defer function to rollback transaction to release semaphore.
> add rollback tx at GetVoteOnHash #8637

- turbo/stages/headerdownload/header_algo_test.go
- turbo/stages/headerdownload/header_algos.go
Based on https://github.com/maticnetwork/bor/pull/871 in bor, this PR handles import of same difficulty chains (tie breaker conditions) based on their height and hash. 
This PR also modifies an existing test to check different types of side-chain import and how the canonical is decided.
> headerdownload: handle tie breaker for forkchoice in pow networks

- cmd/utils/flags.go
we plan step-by-step keep increasing this default
still see users for who it helped to handle more rpc 
tradeoff: increasing of this flag - increasing "historical rpc" throughput and decreasing "recent data rpc" throughput
> defaults change: increase default --db.read.concurrency 4 times

- turbo/snapshotsync/freezeblocks/block_reader.go
```
EROR] [11-16|07:33:02.592] RPC method eth_getLogs crashed: runtime error: invalid memory address or nil pointer dereference
Nov 16 07:33:02 i-0e4d4ce2636f49d8a erigon.sh[1739584]: [service.go:219 panic.go:914 panic.go:261 signal_unix.go:861 block_reader.go:615 block_reader.go:405 eth_receipts.go:228 value.go:596 value.go:380 service.go:224 handler.go:493 handler.go:443 handler.go:391 handler.go:222 handler.go:315 asm_amd64.s:1650]
```
> BlockReader: handle nil-body 

- eth/tracers/api.go
- turbo/jsonrpc/debug_api.go
- turbo/jsonrpc/tracing.go
This is a similar PR of https://github.com/ethereum/go-ethereum/pull/28460, support traceCall in the middle of a block
> eth/tracers: support traceCall with txIndex

- erigon-lib/metrics/register.go
Erigon currently uses a combination of Victoria Metrics and Prometheus client for providing metrics.
We want to rationalize this and use only the Prometheus client library, but we want to maintain the simplified Victoria Metrics methods for constructing metrics.
This task is currently partly complete and needs to be finished to a stage where we can remove the Victoria Metrics module from the Erigon code base.
* Make sure that the format change int->float implied by VM to Prometheus does not impact clients (pay particular attention to block numbers)
* Check that the prometheus/grafana dashboards defined in cmd/prometheus are functional after the change
(see docker-compose.yml for details and https://github.com/ledgerwatch/erigon/tree/devel/cmd/prometheus#readme)
* Confirm that the …
> metrics: switch to using prometheus library

- Makefile
- cl/antiquary/antiquary.go
- cmd/capcli/cli.go
- cmd/tooling/README.md
- cmd/tooling/cli.go
- cmd/tooling/main.go
- p2p/netutil/net.go
Upload beacon snapshots to R2 every week by default
> Automation tool to automatically upload caplin's snapshot files to R2

- p2p/discover/v4_udp.go
Problem:
Some goroutines are blocked on shutdown:
1. table close <-tab.closed // because table loop pending
1. table loop <-refreshDone // because lookup shutdown blocks doRefresh
1. lookup shutdown <-it.replyCh // because it.queryfunc (findnode - ensureBond) is blocked, and not returning errClosed (if it returns and pushes to it.replyCh, then shutdown() will unblock)
1. findnode - ensureBond <-rm.errc // because the related replyMatcher was added after loop() exited, so there's nothing to push errClosed and unlock it
If addReplyMatcher channel is buffered, it is possible that UDPv4.pending() adds a new reply matcher after closeCtx.Done().
Such reply matcher's errc result channel will never be updated, because the UDPv4.loop() has exited at this point. Subsequent discovery operations will …
> p2p: fix discovery shutdown (#8725)

- p2p/discover/v4_udp.go
Making the addReplyMatcher channel unbuffered makes the loop
going too slow sometimes for serving parallel requests.
This is an alternative fix for keeping the channel buffered.
> p2p: fix discovery shutdown (#8725) - alternative fix

- erigon-lib/txpool/fetch.go
- erigon-lib/txpool/fetch_test.go
- erigon-lib/txpool/pool.go
- erigon-lib/txpool/send.go
* limit remote transactions re-broadcast to 3-6 peers  
Broadcasting to 100 peers generates too much outgoing traffic.
* limit transactions count/size in PooledTransactions replies
Before it was sending 5.5-6.5 MiB/sec:
With the fixes it stays at 3-3.5 MiB/sec:
P.S. A baseline if everything is disabled (BroadcastPooledTxs, AnnouncePooledTxs, responses to GetPooledTransactions) is 0.5-1 MiB/sec.
> txpool: limit transactions outgoing messages (#8271)

- consensus/bor/finality/bor_verifier.go
- consensus/bor/heimdall/client.go
- eth/stagedsync/stage_bor_heimdall.go
log `ctx.Err()` - it can be canceled by many reasons: timeout, etc...
> bor: don't hide `ctx.Err()`

- .github/workflows/test-integration-caplin.yml
> cl: disable spec-integration CI on mac - until flaky test fix

- cl/clparams/config.go
- cl/cltypes/solid/bitlist.go
- cl/cltypes/solid/hash_list.go
- cl/cltypes/solid/uint64slice_byte.go
- cl/cltypes/solid/validator_set.go
- cl/fork/fork.go
- cl/merkle_tree/hasher.go
- cl/merkle_tree/list.go
- cl/persistence/db_config/db_config.go
- cl/phase1/cache/attestation_indicies_cache.go
- cl/phase1/core/state/cache_accessors.go
- cl/phase1/core/state/shuffling/shuffling.go
- cl/phase1/core/state/shuffling/shuffling_test.go
- cl/phase1/core/state/shuffling/util.go
- cl/phase1/forkchoice/on_operations.go
- cl/phase1/stages/clstages.go
- cl/sentinel/msg_id.go
- cl/sentinel/msg_id_test.go
- cl/spectest/consensus_tests/shuffling.go
- cl/transition/impl/eth2/operations.go
- cl/transition/impl/eth2/statechange/process_historical_roots_update.go
- cl/transition/impl/eth2/utils.go
- cl/utils/crypto.go
- cl/utils/crypto_test.go
- cl/utils/merkle.go
- cmd/utils/flags.go
- cmd/verkle/main.go
- eth/backend.go
- eth/ethconfig/config.go
* Correct naming of hash func in Eth2
* Customizable mode of operation for Caplin
> Adds flags to enable/disable backfilling and enable full historical beacon node

- consensus/bor/bor.go
- consensus/bor/snapshot.go
- core/types/block.go
- core/types/block_test.go
- erigon-lib/chain/chain_config.go
- eth/stagedsync/stage_bor_heimdall.go
This PR adds support to store the transaction dependency (generated by the block producer) in the block header for bor. This transaction dependency will then be used by the parallel processor ([Block-STM](https://github.com/ledgerwatch/erigon/pull/7812/)).
I have created another [PR](https://github.com/ledgerwatch/erigon-lib/pull/1064) in the erigon-lib repo which adds the `IsParallelUniverse()` function.
> Added TxDependency Metadata to ExtraData in Block Header in Bor for Block-STM

- p2p/sentry/sentry_grpc_server.go
Current value: 16 was added by me 1 year ago and didn't mean anything. Never seen this field holding much data, probably can increase. 
Currently I see logs like (and 10x like this): 
```
[DBUG] [11-24|06:59:38.353] slow peer or too many requests, dropping its old requests name=erigon/v2.54.0-aeec5...
[DBUG] [11-24|06:59:38.353] slow peer or too many requests, dropping its old requests name=erigon/v2.54.0-aeec5...
[DBUG] [11-24|06:59:38.353] slow peer or too many requests, dropping its old requests name=bor/v1.0.0-beta/linu...
[DBUG] [11-24|06:59:38.467] slow peer or too many requests, dropping its old requests name=erigon/v2.54.0-aeec5...
[DBUG] [11-24|06:59:38.469] slow peer or too many requests, dropping its old requests name=erigon/v2.51.0-a0160...
[DBUG] [11-24|06:59:38.469] slow …
```
> increase peer tasks queue size

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/downloadercfg/downloadercfg.go
- erigon-lib/downloader/webseed.go
because files with different name can have same hash: BitTorrent is content-addressable.
> webseed: .torrent file validation must check - fileName and hash 

- cmd/integration/commands/stages.go
sometimes need tool to apply migrations - without starting erigon (if erigon is buggy, or to prevent snapshots downloading, etc...)
> integration run_migrations: open in non-accede exclusive mode - to create new tables

- core/genesis_write.go
- erigon-lib/kv/mdbx/kv_mdbx.go
- erigon-lib/txpool/txpooluitl/all_components.go
- p2p/enode/nodedb.go
it didn't cause problems yet. but it seems a good idea in-general.
> mdbx: hard-limit of small db's dirty_space 

- core/vm/interpreter.go
This aligns the tracing behavior with Geth, Besu and Nimbus.
> Call Tracer.CaptureState before memory expansion

- cmd/utils/flags.go
> flags: bump default value of db.size.limit to 8TB

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/util.go
During initial sync magnet links to domain/index/history files are added along with `v1` snapshots. Since we do not seed snapshots.v2 - fall into endless "Waiting for torrent metadata" for those files which could not be actually downloaded yet. 
This restricts those files to be added for now.
> e35 skipv3 snapshots downloading

- cmd/utils/flags.go
As per the [comment](https://github.com/ledgerwatch/erigon/pull/8869#issuecomment-1836645516) in PR #8869, 8 TB is actually not enough for Polygon.
> flags: bump default value of db.size.limit to 12TB

- cl/antiquary/antiquary.go
- cmd/capcli/cli.go
Erigon by default must use as minimum resources as possible to build snapshots. But cli commands - can go opposite and maximize.
> caplin: to use 1 worker for snapshots compression 

- TESTING.md
Correction for "Lets assume":
Incorrect: "Lets assume"
Correct: "Let's assume"
Explanation: In this phrase, the word "Lets" is incorrectly written. The correct form should be "Let's," which is a contraction of "let us." 
Correction for the word "tripple":
Incorrect: "tripple"
Correct: "triple"
Explanation: The word "tripple" is misspelled. The correct spelling is "triple," which refers to something made up of three parts, or multiplied by three.
> fixing typos

- README.md
follow  Example TOML config file will cause parsing error
```
erigon git:(devel) ✗ ./build/bin/erigon --config ./config.toml --chain=sepolia
EROR[12-05|12:07:09.029] failed setting config flags from yaml/toml file err="(1, 1): parsing error: keys cannot contain ` character"
(1, 1): parsing error: keys cannot contain ` character
```
after remove ` character works 
```
✗ ./build/bin/erigon --config ./config.toml --chain=sepolia 
INFO[12-05|12:00:17.619] logging to file system                   log dir=data/logs file prefix=erigon log level=info json=false
INFO[12-05|12:00:17.620] Build info                               git_branch=devel git_tag=v2.54.0-91-g47a6ac16d-dirty git_commit=47a6ac16da6de62e589b655bde7936dcdb0eb073
INFO[12-05|12:00:17.620] Starting Erigon on Sepolia testnet... …
```
> fix: Example TOML config file  parsing error

- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
Example value of `r.FrozenBlocks()`: `499999`
In future PR I will rename this method to something like `MaxBlockNumInFiles()`
> blockReader: read `blockNum == r.FrozenBlocks()` from files

- README.md
- docs/mining.md
1. When running locally, found that these **TODO** json-rpc have been implemented. Updating these outdated information can make the document clearer.
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":1}' http://loca
lhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x02000000000000009c49b60f431cabc7"}
```
2. [but it's easy to accomplish] Points to an obsolete message (https://github.com/ledgerwatch/erigon/blob/9b8cdc0f2289a7cef78218a15043de5bdff4465e/eth/downloader/downloader.go#L673)
> update outdated information

- eth/stagedsync/stage_bor_heimdall.go
This fixes a bug on syncing from scratch if the start point is in a frozen block.
> Fix snap initialization from frozen blocks

- Makefile
- turbo/silkworm/silkworm_compat_check.sh
Silkworm built on Ubuntu 22 depends on glibc 2.34. In order to run on an older OS, Silkworm needs to be built and linked with an older glibc, but to build on an older OS we need a compatible compiler. Silkworm requires gcc 11+ that is not available on Ubuntu 20 or Debian 11.
To simplify the deployment disable Silkworm support on versions before Ubuntu 22, Debian 12, and glibc prior to 2.34. The check for Ubuntu and Debian is explicit, because some Ubuntu 16 installations report glibc 2.35 with ldd, but `go build` still uses an older system one and fails.
> silkworm: disable on incompatible Linux versions

- eth/tracers/logger/access_list_tracer.go
- eth/tracers/logger/access_list_tracer_test.go
Because access lists use maps with the `StorageKey` as the key, they are subject to inconsistent ordering in the results of the `.accessList()` method.
To get around this, an `accessListSorted` method has been added, and exposed with the same name. The `equal` method has also been exposed to allow for equality checks at this level outside of this module.
> Adds access list sorting

- Makefile
`--tags "a,b,nosilkworm",integration` doesn't work
> makefile: unquote silkworm build tag - to make it concatenatable

- cl/antiquary/state_antiquary.go
- cl/cltypes/eth1_block.go
- cl/persistence/state/historical_states_reader/historical_states_reader.go
- cl/phase1/core/state/cache_accessors.go
- cl/phase1/core/state/raw/copy.go
- cl/phase1/core/state/raw/hashing.go
- cl/spectest/consensus_tests/ssz_static.go
- cl/ssz/decode.go
- cl/ssz/encode.go
- cl/transition/impl/eth2/operations.go
- cmd/capcli/cli.go
- erigon-lib/types/ssz/ssz.go
* Most of the PR changed files are extra and slightly more complicated unit tests.
* Fixed Eth1DataVotes not inheriting genesis
* Fixed Attestations simulation using wrong slot when reconstructing partecipation
* Fixed Copy() operation on BeaconState on Eth1DataVotes
* Used correct ListSSZ type for Eth1DataVotes and HistoricalSummaries
* Fixed wrong []uint64 deltas on empty slots
> Resumable beacon state reconstruction

- turbo/silkworm/silkworm_compat_check.sh
Small fix to the script for the scenario where more than one matching library can be returned. 
For example, the command `/sbin/ldconfig -p | grep libstdc++ | awk '{ print $NF }'` can result in
```
/lib/x86_64-linux-gnu/libstdc++.so.6
/lib32/libstdc++.so.6
```
which then fails the check `if [[ ! -L "$link_path" ]]`
> Fix case when there are more than one matching libraries

- cl/abstract/beacon_state.go
- cl/antiquary/antiquary.go
- cl/antiquary/state_antiquary.go
- cl/clparams/config.go
- cl/persistence/base_encoding/uint64_diff.go
- cl/persistence/state/historical_states_reader/historical_states_reader.go
- cl/persistence/state/historical_states_reader/historical_states_reader_test.go
- cl/phase1/core/state/cache_accessors.go
- cl/phase1/core/state/upgrade.go
- cl/transition/impl/eth2/operations.go
* Reconstruct previous epoch without looking at DB: no hindrance to performance -> removed 15GB
* Store inactivity scores and slashings in MDBX and do not store diffs for them(they are tiny 700/400 bytes)
* Reduced dumps from every 2048 to 1024 -> Added 5 GB (maybe we should down it to 768)
* Parallel processing of shuffled sets, 2x performance boost in reading participation.
* Store balances diffs in a Btree diff matter, see: https://github.com/ledgerwatch/erigon-documents/blob/master/caplin/design/data-model.md#uint64listuint64vector
> Optimized beacon state retrieval

- erigon-lib/downloader/downloader.go
After a refactoring, the detailed bittorrent vs webseeds log has disappeared
> Fixup bittorrent/webseed download logs after refactoring

- Makefile
- go.mod
- go.sum
- turbo/silkworm/silkworm_lib_path.sh
We've got a report from a user that erigon fails to run with this error:
```
/opt/erigon/releases/latest/bin/erigon: error while loading shared libraries: libsilkworm_capi.so: cannot open shared object file: No such file or directory
```
On this system erigon is executed using a service-account user which has no permission to access the build user's $HOME where the libsilkworm_capi.so resides (inside $GOPATH/pkg/mod).
This adds a support to silkworm-go to look for the library relative to the executable path on Linux:
https://github.com/erigontech/silkworm-go/commit/d4ec8a8bce96936a0cf8056dfafe790fa83ae486
and a new `make DIST=<path> install` command which copies both the library and erigon binary to any destination.
> silkworm: make install

- cmd/state/exec3/state.go
- erigon-lib/commitment/commitment.go
- erigon-lib/commitment/hex_patricia_hashed.go
- erigon-lib/state/aggregator_test.go
- erigon-lib/state/domain_shared.go
- erigon-lib/state/domain_shared_test.go
- eth/stagedsync/exec3.go
this adds switch to write commitment either through etl or directly to domain WAL without pre-ordering.
> e35 commitment updates to domain wal

- turbo/jsonrpc/gen_traces_test.go
- turbo/jsonrpc/tracing.go
See https://github.com/ethereum/go-ethereum/pull/27183
> rpc: add `txHash` to  `debug_traceBlock*` results

- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_reader_test.go
During testing we run into a "span 7813 not found (db)" due to a very large unwind (1 million blocks). 
This is because the block reader's `LastFrozenSpanID` and `LastFrozenEventID` returned results that are not consistent with `FrozenBorBlocks`. The latter is taking into account the existence of `.idx` files while the former 2 functions were not.
Note such a large unwind is not likely to happen normally unless there is a bug in our unwind logic or an operator is manually unwinding very far back due to reasons like chain halts (ie mumbai bug problem from few months ago), devel testing or anything else along these lines. Regardless, it exposed the above discrepancy which is best to be fixed.
> freezeblocks: fix blockreader last frozen bor span and event ids

- README.md
Sync from scratch took about 4 days 15 hours, with total disk used about 2.8TB
```
ubuntu@localhost:/erigon$ cast block-number
18825796
ubuntu@localhost:/erigon$ ls
chaindata  downloader  jwt.hex  LOCK  nodekey  nodes  snapshots  temp  txpool
ubuntu@localhost:/erigon$ du -hs chaindata
2.2T    chaindata
ubuntu@localhost:/erigon$ du -hs downloader
17M     downloader
ubuntu@localhost:/erigon$ du -hs snapshots
473G    snapshots
ubuntu@localhost:/erigon$ du -hs temp
79G     temp
```
> Update Ethereum Mainnet storage requirements

- erigon-lib/downloader/downloader.go
- migrations/migrations.go
- migrations/prohibit_new_downloads_lock.go
it will protect existing nodes from downloading `v2` files - even if they do upgrade
> db migration: if stage_snapshots > 0, then create prohibit_new_downloads.lock file

- erigon-lib/state/aggregator_v3.go
- eth/ethconfig/config.go
- eth/stagedsync/test/harness.go
`e35` doesn't write genesis state by special func anymore - and Mock using `m.InsertBlocks` to process genesis block (as any other block).
> harness test: to use `Mock` for genesis write - for e35 compatibility 

- eth/backend.go
erigon didn't download form webseeds if StageSnapshots progress > 0. but sometime we want "just delete files and re-download them"
> webseed: remove dependency on db state

- erigon-lib/txpool/pool.go
Found the different log style for announced and broadcasted tx:
```
[INFO] [12-22|05:18:01.363] Local tx broadcasted                     txHash=ec6b1c87aafd7f8ead5794477be50bda696f2ce17271ad4f6022a756722fa0be to peer=10
[INFO] [12-22|05:18:01.363] local tx announced                       tx_hash=ec6b1c87aafd7f8ead5794477be50bda696f2ce17271ad4f6022a756722fa0be to peer=40 baseFee=1
```
adjust them to the same style
> txpool: the same logging style of announced and broadcasted tx

- erigon-lib/common/dbg/dbg_env.go
- erigon-lib/common/dbg/experiments.go
- eth/stagedsync/default_stages.go
`STAGES_ONLY_BLOCKS=true` may help to produce BlockSnaps by Erigon2 on weak machines - it disabling all stages after StageSenders.
> mode to produce block snapshots

- consensus/bor/heimdall/client.go
Add paths to the hiemdall config URL when creating calls so that extra paths needs by, for example proxy servers are not stripped from the flag value passed into the process.
> Allow proxy paths in Heimdall URL

- cl/antiquary/antiquary.go
- cl/antiquary/state_antiquary.go
- cl/antiquary/state_antiquary_test.go
- cl/antiquary/tests/tests.go
- cl/beacon/beaconhttp/api.go
- cl/beacon/handler/blocks.go
- cl/beacon/handler/blocks_test.go
- cl/beacon/handler/config_test.go
- cl/beacon/handler/duties_proposer.go
- cl/beacon/handler/duties_proposer_test.go
- cl/beacon/handler/format.go
- cl/beacon/handler/genesis.go
- cl/beacon/handler/genesis_test.go
- cl/beacon/handler/handler.go
- cl/beacon/handler/headers_test.go
- cl/beacon/handler/states.go
- cl/beacon/handler/states_test.go
- cl/beacon/handler/utils_test.go
- cl/beacon/handler/validators.go
- cl/beacon/synced_data/synced_data.go
- cl/persistence/state/historical_states_reader/historical_states_reader.go
- cl/persistence/state/historical_states_reader/historical_states_reader_test.go
- cl/persistence/state/state_accessors.go
- cl/phase1/forkchoice/forkchoice_mock.go
- cl/sentinel/handlers/handlers.go
- cl/sentinel/sentinel_gossip_test.go
- cl/sentinel/sentinel_requests_test.go
- cmd/capcli/cli.go
- cmd/caplin/caplin1/run.go
* Testing Beacon API
* Fixed sentinel code (a little bit)
* Fixed sentinel tests
* Added historical state support
* Fixed state-related endpoints (i was drunk when writing them)
> [Grindmas] Added tests to Beacon API, also fixed stuff. 

- cmd/silkworm_api/snapshot_idx.go
- p2p/sentry/simulator/sentry_simulator.go
- p2p/sentry/simulator/simulator_test.go
- p2p/sentry/simulator/syncutil.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
This adds a simulator object with implements the SentryServer api but takes objects from a pre-existing snapshot file.
If the snapshot is not available locally it will download and index the .seg file for the header range being asked for.
It is created as follows: 
```go
sim, err := simulator.NewSentry(ctx, "mumbai", dataDir, 1, logger)
```
Where the arguments are:
* ctx - a callable context where cancel will close the simulator torrent and file connections (it also has a Close method)
* chain - the name of the chain to take the snapshots from
* datadir - a directory potentially containing snapshot .seg files.  If not files exist in this directory they will be downloaded
*  num peers - the number of peers the simulator should create
*  logger - the loger to log actions to
It can be …
> Added sentry simulator implementation

- cmd/rpcdaemon/README.md
- turbo/jsonrpc/txpool_api.go
implement the `txpool_contentFrom` rpc, used to retrieve the specified address's tx contents.
> rpc: implement txpool_contentFrom

- consensus/bor/bor.go
- consensus/bor/heimdall/span/span_id.go
- consensus/bor/heimdall/span/span_id_test.go
- eth/stagedsync/stage_bor_heimdall.go
- polygon/sync/heimdall.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
follow up on naming as suggested here https://github.com/ledgerwatch/erigon/pull/9096#pullrequestreview-1798218317
> heimdall: use span id as naming

- consensus/bor/heimdall/client.go
- consensus/bor/heimdall/client_test.go
Users reported this error
```
[bor.heimdall] an error while trying fetching path=clerk/event-record/list attempt=5 error="unexpected end of JSON input"
```
Which may happen if:
1. Heimdall is behind and not sync-ed - for more info check https://github.com/maticnetwork/heimdall/pull/993
2. Or the header time erigon is sending is far into the future
The logs in this PR will help us see which of the 2 is the culprit but most likely it is 1. We will investigate further 2. if it ever happens.
Changes:
1. Improves logging upon heimdall client retries - prints out the full url that failed.
2. Fixes a bug where the body was incorrectly checked if it is empty - `len(body) == 0` vs `body == nil`
3. Unit test for the bug regression
4. Adds a log to indicate to users to check their heimdall process …
> heimdall: better error logging for clerk/event-record/list nil response

- cmd/evm/README.md
fix the relative path in cmd/evm/README.md
> chore(cmd/evm):fix link jump in cmd/evm/README.md

- cmd/devnet/args/node_args.go
- cmd/devnet/args/node_args_test.go
- cmd/devnet/services/accounts/faucet.go
- cmd/devnet/services/polygon/heimdall.go
Getting an error in one of the bor nodes in devnet when trying to run the "state-sync" scenario:
```
[EROR] [01-03|16:55:44.179] cli.StartRpcServer error                 err="could not start separate Websocket RPC api at port 8546: listen tcp 127.0.0.1:8546: bind: address already in use"
```
This happens for scenarios with more than 1 node.
Digging further this regressions has happened due to this change: https://github.com/ledgerwatch/erigon/pull/8909
This PR fixes this by updating the devnet `NodeArgs` struct to set the corresponding `--ws.port` `arg` tag which now exists.
> devnet: fix ws port clash for state-sync scenario

- cmd/devnet/devnet/node.go
- cmd/integration/commands/stages.go
- cmd/state/commands/check_change_sets.go
- eth/backend.go
- eth/ethconfig/config.go
A crash on startup happens on --chain=mumbai , because I've confused chainConfig.Bor (from type chain.Config) and config.Bor (from type ethconfig.Config) in the setup code.
ethconfig.Config.Bor property contained bogus values, and was used only to check its type in CreateConsensusEngine(). Its value was never read (before PR #9117).
This change removes the property to avoid confusion and fix the crash.
Devnet network.BorStateSyncDelay was implemented using ethconfig.Config.Bor, but it wasn't taking any effect. It should be fixed separately in a different way.
> bor: BorConfig setup fix

- eth/stagedsync/stage_snapshots.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
This moved the log level of retire progress messaging to debug, to avoid log nose on qa and test runs
> Change retire progress log level to debug

- .github/workflows/ci.yml
- .github/workflows/qa-clean-exit.yml
- .github/workflows/test-integration.yml
macos-13-xlarge was needed to use M1 CPU,
because previously silkworm-go didn't have macOS Intel support
> ci: run macOS jobs on macos-13 instead of macos-13-xlarge

- cmd/devnet/devnet/context.go
- cmd/devnet/tests/bor/devnet_test.go
- cmd/devnet/tests/generic/devnet_test.go
This PR fixes an infinite recursion (stack overflow) error in devnet integration tests that surfaced in our integration CI a week or more ago and additionally enables some integration tests that are now fixed - `TestStateSync` & `TestCallContract`.
> devnet: fix infinite recursion & enable TestStateSync & TestCallContract integration tests

- cl/clparams/config.go
In PR #9184 I confused slot with epoch. Refer to https://github.com/gnosischain/configs/pull/26.
> Fix DenebForkEpoch for Chiado

- cmd/devnet/tests/bor_devnet_test.go
- cmd/devnet/tests/context.go
- cmd/devnet/tests/generic_devnet_test.go
Integration tests CI is failing due to a port clash in devnet tests. I believe this is because there are 2 packages of devnet integration tests and go can run tests from separate packages in parallel (by default it does package level parallelism). A simple fix would be to just have all devnet integration tests in 1 package and run all these tests sequentially within the package (ie not use t.Parallel).  This PR moves all devnet integration tests in 1 package.
`"ContextStart devnet start failed: private api: could not create listener: listen top 127.0.0.1:10090: bind: address already in use, addr=localhost:10090"`
> devnet: integration tests port clash fix

- .github/workflows/qa-clean-exit-snapshot-downloading.yml
This PR
- increase the test time
- use the updated python scripts that reports as an issue a long exit time
- change the test name to states that it is runned in the snapshot downloading phase 
(a later PR will add a similar test on the block downloading phase)
> clean-exit test: increase test time

- eth/stagedsync/stage_bor_heimdall.go
- turbo/app/snapshots_cmd.go
This fixes a couple of regressions for running the uploader for mumbai
* Now flags have moved to a higher context they need to be set in the context not the flag values
* Span 0 of mumbai has a header/span mismatch for span zero sprint 0.  So the check here needs to be suppressed
> Mumbai uploader regression fixes

- erigon-lib/recsplit/recsplit.go
- erigon-lib/state/history.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
reasons: 
- indexing done in background (or in many workers)
- `recsplit` has 2 etl collectors
> recsplit: reduce ram pressure

- erigon-lib/kv/mdbx/kv_mdbx.go
can do it, because we don't do read-after-write in same rwtx
> mdbx: reduce 2 times hard dplimit

- erigon-lib/kv/iter/iter.go
- erigon-lib/state/history.go
According to the implementation of `UnionKV`, the first argument (`x`) receives priority when the keys are the same
> [E3] DB entries should have priority over files entries in HistoryRange iterator

- erigon-lib/metrics/parsing.go
above go1.18  Index calls are more clearly written using Cut.
https://github.com/golang/go/issues/46336
> refactor(erigon-lib/metrics): replace strings.IndexByte with strings.Cut

- turbo/jsonrpc/bor_snapshot.go
Removed the check for milestoneID in the GetVoteOnHash()
https://github.com/maticnetwork/bor/pull/1109
> Removed the check for milestoneID in the GetVoteOnHash()

- eth/backend.go
Pos downloader and the engine api code are not necessary for Bor.  This adds code to suppress their start up.
> Don't run pos downloader or engine api for bor

- cmd/txpool/main.go
- consensus/misc/eip1559.go
- erigon-lib/chain/chain_config.go
- erigon-lib/txpool/pool.go
- erigon-lib/txpool/pool_fuzz_test.go
- erigon-lib/txpool/pool_test.go
- erigon-lib/txpool/txpooluitl/all_components.go
- eth/backend.go
- eth/stagedsync/stage_execute.go
- turbo/shards/state_change_accumulator.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/stages/mock/mock_sentry.go
When the sync loop first runs it suppresses block sync events both in the initial loop and when the blocks being processed are greater than 1000.
This fix removed the first check, because otherwise the first block received by the process ends up not getting sent to the tx pool.  Which means it won't produce new block for polygon.
As well as this fix - I have also moved the gas initialization to the txpool start method rather than prompting it with a 'synthetic block event'
As the txpool start has access to the core & tx DB's it can find the current block and chain config internally so that it doesn't need to be externally activated it can just do this itself on start up.  This has the advantage of making the txpool more self contained.
> Fix startup sync for txpool processing for bor block production

- polygon/sync/canonical_chain_builder.go
- polygon/sync/canonical_chain_builder_test.go
- polygon/sync/difficulty.go
- polygon/sync/difficulty_test.go
- polygon/sync/header_time_validator.go
- polygon/sync/spans_cache.go
It is possible that a span update happens during a milestone.
A headers slice might cross to the new span.
Also if 2 forks evolve simulaneously, a shorter fork can still be in the previous span.
In these cases we need access to the previous span to calculate difficulty and validate header times.
SpansCache will keep recent spans.
The cache will be updated on new span events from the heimdall.
The cache is pruned on new milestone events and in practice no more than 2 spans are kept.
The header difficulty calculation and time validation depends on having a span for that header in the cache.
> polygon/sync: span updates

- p2p/enode/nodedb.go
If any DB method is called while Close() is waiting for db.kv.Close()
(it waits for ongoing method calls/transactions to finish)
a panic: "WaitGroup is reused before previous Wait has returned" might happen.
Use context cancellation to ensure that new method calls immediately return during db.kv.Close().
> p2p: panic in enode DB Close on shutdown (#9237)

- erigon-lib/downloader/util.go
seems we just choose the first 8 trackers in https://github.com/ledgerwatch/trackerslist/blob/master/trackers_best.txt.
> fix udpOrHttpTrackers amount

- .github/workflows/qa-clean-exit-block-downloading.yml
This test uses a pre-built database to test Erigon's behaviour on ctrl-c during the block download phase (Caplin sync).
> qa tests: add clean exit test on block downloading

- cl/fork/fork_test.go
Current fork digest for Görli has changed after the [Dencun upgrade](https://blog.ethereum.org/2024/01/10/goerli-dencun-announcement) on 17 Jan.
> Update TestGoerliForkDigest after Dencun

- erigon-lib/kv/mdbx/kv_mdbx.go
- erigon-lib/kv/mdbx/kv_mdbx_test.go
In the previous code WaitGroup db.wg.Add(), Wait() and db.closed were not treated in sync. In particular, it was theoretically possible to first check closed, then set closed and Wait, and then call wg.Add() while waiting (leading to WaitGroup panic).
In theory it was also possible that db.env.BeginTxn() is called on a closed or nil db.env, because db.wg.Add() was called only after BeginTxn (db.wg.Wait() could already return).
WaitGroup is replaced with a Cond variable.
Now it is not possible to increase the active transactions count on a closed database. It is also not possible to call BeginTxn on a closed database.
> mdbx: race conditions in MdbxKV.Close (#8409)

- cl/clparams/config.go
- core/forkid/forkid_test.go
- params/chainspecs/holesky.json
- params/chainspecs/sepolia.json
See https://github.com/ethereum/EIPs/pull/8051 & https://github.com/ethereum/execution-specs/pull/860
> Schedule Dencun for Sepolia & Holešky

- cl/persistence/block_saver_test.go
- cl/phase1/execution_client/execution_client_direct.go
- cl/phase1/execution_client/execution_client_rpc.go
- cl/phase1/execution_client/interface.go
- cl/phase1/forkchoice/on_block.go
- turbo/engineapi/engine_server.go
- turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
golang slice can be `nil`. There's no reason to pass it by pointer.
This is a fix to PR #9257. It fixes the following error in Hive test "Withdrawals Fork on Block 1 (Paris)":
```
<< (0953747c) {"jsonrpc":"2.0","id":5,"error":{"code":-32000,"message":"ethereumExecutionModule.InsertBlocks: blob gas used is nil"}}
CLMocker: Could not ExecutePayloadV1: ethereumExecutionModule.InsertBlocks: blob gas used is nil
CLMocker: BroadcastNewPayload Error (0953747c): ethereumExecutionModule.InsertBlocks: blob gas used is nil
```
> Pass slice of versionedHashes by value

- turbo/jsonrpc/eth_block.go
Fix for https://github.com/ledgerwatch/erigon/issues/7504#issuecomment-1891149390
Tests:
Prior to this fix the below endpoints were returning "0xa" (10) which is incorrect - should be "0xb" (11)
```
➜  ~ curl http://localhost:9545/ \                                                                                        
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_getBlockTransactionCountByNumber","params":["0x7F3A00"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":"0xb"}
````
```
➜  ~ curl http://localhost:9545/ \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_getBlockTransactionCountByHash","params":["0xb681901447981864462b5bf3004814c436b308150e6369341524b6e215092676"],"id":1,"jsonrpc":"2.0"}' …
```
> turbo/jsonrpc: fix GetBlockTransactionCountByNumber & ByHash for blocks with bor state sync event txn

- turbo/silkworm/silkworm_compat_check.sh
The silkworm_compat_check.sh script assumes that the os-release file declares both VERSION and VERSION_ID.  However, in the specification at:
https://www.freedesktop.org/software/systemd/man/latest/os-release.html
All of the variables simply _may_ be declared, and none are strictly required.  In particular, for Archlinux the file looks like:
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
And although an up to date Archlinux system has adequate library …
> Unbound variable error in silkworm_compat_check

- cmd/devnet/tests/bor_devnet_test.go
see https://github.com/ledgerwatch/erigon/issues/9290
I don't have enough knowledge about this flow of events, in particular, why pendingCheckpoint is expected to be present as soon as rootHeaderBlockChan produces a value.
Before we figure this out, I suggest to skip the test, because it currently ruins the CI integration tests suite for the others:
https://github.com/ledgerwatch/erigon/actions/workflows/test-integration.yml?query=branch%3Adevel
> devnet: skip TestStateSync until fixed (#9290)

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/downloader_grpc_server.go
- erigon-lib/downloader/torrent_files.go
- erigon-lib/downloader/webseed.go
- eth/backend.go
moved `.lock` file handling inside `TorrentFiles` class - which is available everywhere and guarded by mutex. 
fixing: https://github.com/ledgerwatch/erigon/issues/9294
> downloader: prohibit_new_downloads.lock check missed download .torrent from WebSeed

- consensus/misc/eip1559.go
- erigon-lib/txpool/pool.go
PR #9219 missed blockGasLimit.
This PR fixes a failure in Hive test "Withdrawals Fork on Block 1 (Paris)"  due to transactions excluded from block 1 because of failing `NotTooMuchGas` check.
> txpool: fix initial blockGasLimit and setBlobFee()

- erigon-lib/kv/membatch/mapmutation.go
- erigon-lib/kv/membatch/mapmutation_test.go
When putting a `key, value` pair into the memory batch, the size count in bytes must be updated accordingly (i.e. add key length plus value length when key is not present, add value length diff when key is already present) but the presence check logic is inverted.
> Fix mapmutation size update

- cl/cltypes/withdrawal.go
per beacon API specs: https://github.com/ethereum/beacon-APIs/blob/master/types/withdrawal.yaml#L8
> Fix validator_index field name on beacon API

- turbo/execution/eth1/block_building.go
This fixes the piece of logic that return the previous payload ID in case CL sends the same request for some reason (previously it would fail because `param` & `e.lastParameters` had different `PayloadId`)
> Block building: Fix duplicate request check

- turbo/jsonrpc/trace_adhoc.go
Context: accidentally removed this line in https://github.com/ledgerwatch/erigon/pull/9276/files#diff-6d65959a2517f728bf3c59ed6bb41c1d71528e80fd0f8c9e155d4fde65e0b006L867-L868 - adding back
> turbo/jsonrpc: fix accidental regression in ReplayBlockTransactions

- cmd/rpcdaemon/rpcservices/eth_backend.go
- eth/integrity/no_gaps_in_canonical_headers.go
- eth/stagedsync/bor_heimdall_shared.go
- eth/stagedsync/stage_bor_heimdall.go
- eth/stagedsync/stage_mining_bor_heimdall.go
- eth/stagedsync/stage_snapshots.go
- turbo/app/snapshots_cmd.go
- turbo/services/interfaces.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
- moves `LastSpanID`, `LastFrozenSpanID`, `LastStateSyncEventID`,  `LastFrozenEventID` bor related functionality to `BorSpanReader` and `BorEventReader` interfaces respectively
- introduces a `SpanNotFoundErr` in `BlockReader.Span` function for a more idiomatic Go handling of "not found" situations
- noticed a few random funcs that should have been moved to the block reader interfaces but have been hacked in - `IterateFrozenBodies`, `FirstTxnNumNotInSnapshots`, `Integrity` so added them to `BlockReader`, `HeaderReader` and `TxnReader` respectivelly
- note the remote block reader and remote backend currently would panic with "not implemented" for these functions - their implementations can be added on a "need to implement" basis
> turbo/snapshotsync/freezeblocks: move pending funcs to full block reader interface

- eth/stagedsync/bor_heimdall_shared.go
- eth/stagedsync/stage_bor_heimdall_test.go
- polygon/bor/bor.go
- polygon/bor/span_id.go
2 issues found when syncing from scratch on mumbai/bor-mainnet
- Issue is that `bor.IsSecondSprintStart` only checks if `toBlockNum` == `second sprint start` but doesn't handle the case of `toBlockNum` being after `second sprint start` - e.g. consider the case where the stage is called with fromBlockNum=57 and toBlockNum=67 as in the logs
- a previous bad merge had accidentally reverted a change in `polygon/bor/bor.go checkAndCommitSpan`
```
[INFO] [02-02|18:03:13.416] [3/15 BorHeimdall] Processing sync events... from=57 to=67
[INFO] [02-02|18:03:13.558] [3/15 BorHeimdall] Sync events processed progress=66 lastSpanID=0 lastStateSyncEventID=0 total records=0 fetch time=132.744042ms process time=142.111667ms
[EROR] [02-02|18:03:13.559] [staged sync] BorSpan failed             err="span 1 …
```
> eth/stagedsync: fix span fetch logic for span 0 and 1

- eth/backend.go
- ethstats/ethstats.go
This PR addresses the issue where the EthStats panel was not displaying pending transaction data. Before this update, users were unable to see any information regarding pending transactions on the EthStats panel, which limited the panel's usefulness for real-time transaction monitoring.
This problem also appears on the Ethereum Devnet 12 EthStats dashboard:  https://ethstats.dencun-devnet-12.ethpandaops.io/
With these changes, the EthStats panel now accurately reports pending transaction information, providing users with comprehensive real-time data monitoring capabilities. This enhancement makes it easier for users to track transaction statuses and system health at a glance.
> ethstats: Fix Issue with Unreported Pending Transaction Information

- erigon-lib/tools/licenses_check.sh
```
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
```
> fix `find` warning

- core/types/blob_tx.go
This was noticed when running a hive test targeted at failing when there are no versioned hashes in the tx
> Return error when no blob hashes in txn

- .github/workflows/qa-clean-exit-block-downloading.yml
Delete destination chaindata before rsyncing to avoid "No space left on device"
> clean-exit test: avoid disk space exhaustion 

- erigon-lib/state/aggregator_test.go
- erigon-lib/state/domain_shared.go
test failed when generated key for code was of length 52 (randomly picked from already used keys or generated) and was not deleted because iterate prefix was used for storages only.
> e35 fix PruneSmallBatches test 

- turbo/silkworm/silkworm_go_devenv.sh
This PR add support to optionally use a local `silkworm-go` repo during development. If not available, a temporary repo clone is used as before.
The typical setup we use during Silkworm-for-Erigon development is described [here](https://github.com/erigontech/silkworm/blob/master/docs/CONTRIBUTING.md#c-api-for-erigon).
> silkworm: dev env using local silkworm-go

- cmd/txpool/main.go
- cmd/utils/flags.go
- erigon-lib/txpool/pool.go
- erigon-lib/txpool/pool_test.go
- erigon-lib/txpool/txpoolcfg/txpoolcfg.go
- eth/ethconfig/tx_pool.go
- turbo/cli/default_flags.go
**Summary**
Adds a new flag/parameter `totalBlobPoolLimit` to the txpool. 
Any time the number of blobs (total of all blobs in all type-3 txs) exceeds this number, the pool won't accept any more blob txs.
This is a very straightforward way to prevent blob spamming. It also gives a node operator the freedom to stay away from too many blobs in their own pool.
**More background**: Blob txs take a huge toll on the txpool and the rest of the system because of their size and cryptography involved.
> Add totalBlobPoolLimit flag

- consensus/misc/eip1559.go
```
[INFO] [02-08|22:58:28.974] new subscription to logs established
[INFO] [02-08|22:58:28.975] rpc filters: subscribing to Erigon events
[signal SIGSEGV: segmentation violation code=0x1 addr=0x240 pc=0x122572f]
goroutine 2343 [running]:
github.com/ledgerwatch/erigon/consensus/misc.eip1559Calculator.CurrentFees({}, 0xc046591900, {0x7f1202466db8, 0xc0341b7d40})
github.com/ledgerwatch/erigon/consensus/misc/eip1559.go:80 +0xcf
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).fromDB(0xc000936c80, {0x3277f60, 0xc000cd8eb0}, {0x3299818?, 0xc0341b7ce0}, {0x3299818?, 0xc0341b7d40?})  
github.com/ledgerwatch/erigon-lib@v1.0.0/txpool/pool.go:2095 +0x8b3
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).Start.func1({0x3299818 …
```
> fix nil-ptr in txpool fee calc

- turbo/engineapi/engine_server.go
This PR partially fixes https://github.com/ledgerwatch/erigon/issues/9407
> Hive: Do not validate payload attributes if nil or syncing and pre-cancun check

- README.md
I've found broken link to gnosis docs, this PR fixes the issue.
> fix: update broken link to gnosis

- erigon-lib/downloader/downloader.go
Fix for:
fatal error: concurrent map read and map write
goroutine 213 [running]:
github.com/ledgerwatch/erigon-lib/downloader.initSnapshotLock.func1()
github.com/ledgerwatch/erigon-lib@v1.0.0/downloader/downloader.go:329 +0x3a7
> Add lock for downloader version map

- erigon-lib/downloader/downloader.go
This fix avoid a potential hanging file close for tests which use !cfg.SnapshotLock to allow the creation of arbitary files for tests and hence want to avoid the lock
> Don't touch file for !cfg.SnapshotLock

- cmd/utils/flags.go
- eth/backend.go
- eth/stagedsync/stage_execute.go
- tests/bor/helper/miner.go
- turbo/app/import_cmd.go
- turbo/cli/flags.go
- turbo/node/node.go
In certain scenarios (e.g. Hive) genesis is initially populated by `erigon init` and afterwards erigon is started with some `networkid` flag, typically != 1. In that case it's incorrect to use default (mainnet) genesis instead of reading genesis from the DB.
This PR fixes Issue #9191 and also some Hive tests that were incorrectly returning `SYNCING` because they were trying to download mainnet snapshots.
> Don't default to mainnet if NetworkID != 1

- eth/stagedsync/stage_headers.go
- turbo/engineapi/engine_block_downloader/block_downloader.go
- turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
- turbo/execution/eth1/eth1_utils/grpc.go
- turbo/execution/eth1/eth1_utils/grpc_test.go
- turbo/execution/eth1/inserters.go
Since the merge of https://github.com/ledgerwatch/erigon/pull/7936, released in version `v2.49.0` and onward, Erigon has been unable to properly download and process historical Ethereum POW blocks. This makes a mainnet sync from block 0 with snapshotting disabled (`--snapshots=false`) impossible.
I discovered this issue while working on the Erigon-Pulse fork for PulseChain, but the issue remains here, and has been verified with a vanilla version of Erigon v2.57.3 against Ethereum Mainnet.
When doing a full sync from block zero with snapshotting disabled, the following error will occur:
```log
[INFO] [02-08|09:06:11.859] [3/12 Senders] DONE                      in=7h55m24.504489889s
[INFO] [02-08|09:06:11.861] [4/12 Execution] Blocks execution        from=0 to=19180016
[WARN] …
```
> Fix uncle processing in historical POW blocks

- core/chain_makers.go
- core/test/domains_restart_test.go
- erigon-lib/state/domain_shared.go
fix for skipped test. 
Problem was that i did not know that old trie algorithm requires account.Incarnation > 0 to also scan storage keys of that account. If incarnation 0, new algo uses storage keys but old ignores them.
> E35 test commit fix

- erigon-lib/compress/compress.go
- erigon-lib/compress/silkworm_seg_fuzz_test.go
A test that generates an input file,
compresses it using both erigon and silkworm,
and compares that the result matches.
> silkworm: seg compressor fuzz test

- cl/beacon/handler/attestation_rewards.go
- cl/beacon/handler/builder.go
- cl/beacon/handler/committees.go
- cl/beacon/handler/data_test.go
- cl/beacon/handler/duties_attester.go
- cl/beacon/handler/duties_proposer.go
- cl/beacon/handler/handler.go
- cl/beacon/handler/harness/lighthouse.yml
- cl/beacon/handler/harness_test.go
- cl/beacon/handler/lighthouse.go
- cl/beacon/handler/test_data/harness_inclusion_global_1.json
- cl/beacon/handler/test_data/harness_inclusion_local_1.json
- cl/beacon/handler/validators.go
- cl/beacon/router.go
- cl/beacon/synced_data/synced_data.go
- cl/persistence/base_encoding/primitives_test.go
- cl/persistence/base_encoding/uint64_diff.go
- cl/persistence/state/historical_states_reader/historical_states_reader.go
- cl/phase1/forkchoice/fork_graph/diff_storage/diff_storage.go
- cl/phase1/forkchoice/fork_graph/diff_storage/diff_storage_test.go
- cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
- cl/phase1/forkchoice/fork_graph/interface.go
- cl/phase1/forkchoice/forkchoice.go
- cl/phase1/forkchoice/forkchoice_mock.go
- cl/phase1/forkchoice/interface.go
- cl/phase1/network/gossip_manager.go
- cl/phase1/stages/clstages.go
- cl/sentinel/service/service.go
- go.mod
This change increases memory required from 4 GB ->10 GB but makes the Beacon API consistently performant. By default the Beacon API is not enabled so the memory will not be allocated consequently on the average run.
> Prevents DDOS attempts on the Beacon API.

- erigon-lib/downloader/snaptype/type.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
The method was iterating over snapshots.segments.Min().segments, but passing the index to view.Segments().
This might lead to a crash, because those 2 collections are different, and the indexes might not match.
view.Segments() only contains the snapshot files that are fully downloaded and indexed.
The code is changed to only use the view files (as it was before).
> snapshots: fix filesByRange (#9472)

- erigon-lib/txpool/pool.go
- erigon-lib/txpool/pool_test.go
There is a bug in the txpool which can manifest either as a race condition, or in more novel network configurations.  When a transaction is classified as either having `NotTooMuchGas` or its complement, the classification will never change (unless a change to the sender account triggers reevaluation of that transaction).
If the block gas limit changes upwards, then any transactions previously not marked as `NotTooMuchGas` will remain ineligible for promotion. Similarly, if the block gas limit changes downwards, then any transactions previously marked as `NotTooMuchGas` may inappropriately remain as pending.
Although block gas limits may be relatively static in practice, there is additionally a race condition which can cause this bug to manifest. When the tx pool is first constructed, the …
> txpool: Respect updates to block gas limit

- ethdb/prune/storage_mode.go
The previous default for `prune=htrc` would be different after the prune hack. This would lead to error in the node. This PR is to retain the value in the database for `prune.r` value before checking for change.
> Retain receipts pruning default on upgrade

- erigon-lib/chain/chain_config.go
- turbo/stages/stageloop.go
After PR #9408 `cfg.Genesis` may be `nil`. Fixes the following issue in Hive tests:
```
runtime error: invalid memory address or nil pointer dereference" stack="[main.go:29 panic.go:914 panic.go:261 signal_unix.go:861 stageloop.go:540 backend.go:773 node.go:124 main.go:65 make_app.go:52 command.go:279 app.go:337 app.go:311 main.go:34 proc.go:267 asm_amd64.s:1650]
```
> Fix nil pointer in Hive tests

- turbo/jsonrpc/trace_adhoc.go
- turbo/jsonrpc/tracing.go
relates to https://github.com/ledgerwatch/erigon/issues/9507
> turbo/jsonrpc: handle panics due to missed block==nil checks

- erigon-lib/downloader/downloader.go
I did delete 1 preverified file, and did want to re-download it.
I delete `snapshots/*lock*` and started erigon, but it didn't download missed file because it was filtered out by next check:
```
if maxDownloadBlock > 0 {
if fileInfo.From > maxDownloadBlock {
missingItems = append(missingItems, item)
}
}
```
> Can't download preverified file

- turbo/snapshotsync/freezeblocks/block_snapshots.go
Maybe you saw error messages like `[WARN] [03-01|02:31:17.630] [snapshots] retire blocks                err="DumpBlocks: DumpBodies: header missed in db: block_num=38500000` - i found 1 reason. If there is "absense of 1 sap file" (gap in files list) - for example if file manually deleted, erigon will ignore all files after gap and will try to create snapshots starting from "block number before gap" (38500000 in my case) and of-course doesn't have such blocks (erigon already created older snapshots in the past and removed such block). 
So, there is no bug in prune/retirement code of blocks, but just absence of some snapshot file. I will print it to debug logs now and maybe we will do something else about it in future. 
you can see this log for example by `integration print_stages …
> print gaps in files to debug logs

- node/node.go
We had > 1g in the past and reduced to 128Mb - which is fine for smaller db, but for chaindata need increase a bit.  
for https://github.com/ledgerwatch/erigon/issues/9545
> increase chaindata dirtyspace 

- turbo/adapter/ethapi/api.go
- turbo/jsonrpc/eth_api.go
`v` is not used in any transaction types other than legacy transactions. 
Before:
```
{
...
"type": "0x2",
"accessList": [],
"chainId": "0x13881",
"v": "0x1",
"r": "0x3b8d9ed8ccda5bc4ab0c9ec6165cec0052b2cf2fc77f19dc1daf6b349174080e",
"s": "0x222f86d644ad797d9dc1be772adff862cfe499c5113ec3c0e14e0a63c75ca158"
}
}
```
After:
```
...
"type": "0x2",
"accessList": [],
"chainId": "0x13881",
"yParity": "0x1",
"v": "0x1",
"r": "0x3b8d9ed8ccda5bc4ab0c9ec6165cec0052b2cf2fc77f19dc1daf6b349174080e",
"s": "0x222f86d644ad797d9dc1be772adff862cfe499c5113ec3c0e14e0a63c75ca158"
}
}
```
> rpc: Use `yParity` for non-legacy transactions

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/snapshotsync.go
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2a53ec4]
goroutine 2683 [running]:
github.com/ledgerwatch/erigon/turbo/snapshotsync.WaitForDownloader({0x4d19e28, 0xc000c27950}, {0xc0297bd902, 0xe}, 0x1, 0x0, 0x1, 0x468e91?, {0x4d4bb70, 0xc02be71e60}, ...)
github.com/ledgerwatch/erigon/turbo/snapshotsync/snapshotsync.go:86 +0x264
github.com/ledgerwatch/erigon/eth/stagedsync.DownloadAndIndexSnapshotsIfNeed(_, {_, _}, {_, _}, {{0x4d2e7a8, 0xc0018f9ec0}, {{0xc000a539a9, 0x7}, 0xc000a1f0e0, ...}, ...}, ...)
github.com/ledgerwatch/erigon/eth/stagedsync/stage_snapshots.go:234 +0x9d2
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnStageSnapshots(_, {_, _}, {_, _}, {{0x4d2e7a8, 0xc0018f9ec0}, …
```
> nil ptr `bor.close()`

- core/forkid/forkid_test.go
- params/chainspecs/bor-devnet.json
- params/chainspecs/bor-mainnet.json
Block number: 54876000 (March 20th, 2024 at around 10.30 AM UTC)
> Finalize cancun/napoli HF block number for polygon mainnet

- eth/backend.go
- turbo/engineapi/engine_block_downloader/block_downloader.go
- turbo/engineapi/engine_block_downloader/core.go
- turbo/execution/eth1/ethereum_execution.go
- turbo/execution/eth1/forkchoice.go
- turbo/stages/mock/mock_sentry.go
holesky:
```
INFO[03-06|19:10:29.101] [downloader] Downloaded PoS Headers      now=57243 blk/sec=844.800
INFO[03-06|19:10:54.024] P2P                                      app=caplin peers=59
INFO[03-06|19:10:55.694] [EngineBlockDownloader] Flushed buffer file name=erigon-sortable-buf-4082436526
INFO[03-06|19:10:59.101] [downloader] Downloaded PoS Headers      now=32091 blk/sec=838.400
INFO[03-06|19:11:29.102] [downloader] Downloaded PoS Headers      now=6363 blk/sec=857.600
WARN[03-06|19:11:36.829] [EngineBlockDownloader] Could not begin tx err="context canceled"
INFO[03-06|19:11:49.012] [NewPayload] Handling new payload        height=1083958 hash=0x260c4c4a12ea518830241b38bf4860d3364ff65e349b8a6d216d0b5b313d5db5
INFO[03-06|19:11:49.013] [EngineBlockDownloader] Downloading PoS headers... …
```
> EngineBlockDownloader to not pass http-request-ctx in unbounded goroutines 

- core/types/blob_tx_wrapper.go
- core/types/dynamic_fee_tx.go
- core/types/legacy_tx.go
- core/types/transaction.go
This call was likely necessary for the old transaction pool, but doesn't seem to be referenced anywhere now.  Removing as dead code.
> Remove Cost() from tx interface

- erigon-lib/downloader/downloader.go
This PR prevents Erigon from freezing when downloading torrents if the user asks to exit with ctrl-c.
Some tests highlight this with downloader related messages on exiting 
(see https://github.com/ledgerwatch/erigon/actions/runs/8168975069/job/22332103530)
other do not but Erigon remains stuck in the same manner. The simple insertion of this line has solved both.
Please check that this doesn't break some invariant.
> downloader: check exiting while downloading

- core/types/transaction.go
- erigon-lib/kv/tables.go
- erigon-lib/txpool/pool.go
In `PoolTransaction` txn RLP is prefixed with the sender.
> Fix reading blob transaction from PoolTransaction

- turbo/jsonrpc/trace_filtering.go
related to https://github.com/ledgerwatch/erigon/issues/8572#issuecomment-1984926108
and https://github.com/ledgerwatch/erigon/pull/9616
> rpc: trace_transaction return error if block is non-canonical

- turbo/snapshotsync/freezeblocks/block_snapshots.go
i see error: 
```
[1/12 Snapshots] can't build missed indices: v1-032520-032530-transactions.seg: TransactionsIdx: at=32520000-32530000, pre index building, expect: -259243781, got 128116" 
```
I don't know why it happening yet.
Adding assert to catch it earlier with more meaningful error
> assert on bodies file

- erigon-lib/downloader/downloader.go
- turbo/snapshotsync/snapshotsync.go
if erigon `kill -9` in the middle of downloading and re-start: 
it will too early set `stats.Completed = true`
Example: 
```
WARN[03-09|05:06:17.502] [dbg] stats.Complete                     stats.FilesTotal=6 stats.Completed=true
```
`stats.FilesTotal=6` but I have hundreds of files. 
2 cases: 
- `kill -9` in the middle of downloading and re-start - must download ALL preverified files - must "add new files"
- upgrade erigon version - must NOT downlaod new files
Solution: move prohibit_new_downloads.lock again AFTER downloads completed, not BEFORE.
> downloader: `stats.Completed == true` too early 

- cmd/snapshots/cmp/cmp.go
- erigon-lib/downloader/snaptype/files.go
- erigon-lib/downloader/snaptype/type.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
```
[1/15 Snapshots] can't build missed indices: v1-000000-000500-transactions.seg: can't open /mnt/erigon/snapshots for indexing: no such device
```
> snaps: fix lost file path 

- eth/stagedsync/stage_finish.go
- turbo/stages/stageloop.go
now, if `--sync.loop.block.limit=10` erigon may send all headers - because doesn't check jump end. Added:
- check that headerNum < `finishStageAfterSync` (it was missed)
- log amount of sent headers
- iterate over canonical markers instead of headers - it's cheaper and don't need additional hash check
related to https://github.com/ledgerwatch/erigon/issues/8721
> support `--sync.loop.block.limit` in newHeads notification

- erigon-lib/downloader/util.go
- erigon-lib/downloader/webseed.go
Fixes for e35
Fix logging
Intermediate
Filter out webseeds according to the downloaded torrent files
> Compute infohash before creating .torrent file from webseeds

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/util.go
This PR has a series of fixes around re instating changed and deleted files:
* It includes an early check of file size & mod time - before these are updated by t.MergeSpec
* Tidies recalc stats to avoid unnecessary logging and actions
* Add a channel wait to ScheduleVerifyFile, to allow the verify process to complete before returning (this avoids transient t.Complete.Bool states which can confuse other sections of the code
* If verify does not complete - the file is marked as incomplete in the db to initiate a new download
> Fixes to re-download changed files with verify

- erigon-lib/downloader/downloader.go
don't know why yet: 
```
SIGBUS: bus error
PC=0x40d3f7 m=9 sigcode=2
signal arrived during cgo execution
goroutine 344 [syscall, locked to thread]:
runtime.cgocall(0x10b3360, 0xc0014818f8)
runtime/cgocall.go:157 +0x4b fp=0xc0014818d0 sp=0xc001481898 pc=0x42788b
github.com/erigontech/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2(0x7faeec000b70, 0xc002520ac0, 0x1b, 0xc0009cec00, 0x76, 0x0)
_cgo_gotypes.go:1110 +0x4b fp=0xc0014818f8 sp=0xc0014818d0 pc=0xc4bdeb
github.com/erigontech/mdbx-go/mdbx.(*Cursor).Put.func1(0x0?, 0xc0014819d0?, {0xc002520ac0?, 0x1b, 0x120?}, 0x110?, {0xc0009cec00?, 0x76, 0x7faf0cbfa7a8?}, 0x0)
github.com/erigontech/mdbx-go@v0.27.24/mdbx/cursor.go:267 +0x9f fp=0xc001481958 sp=0xc0014818f8 pc=0xc4e25f
github.com/erigontech/mdbx-go/mdbx.(*Cursor).Put(0x0?, {0xc002520ac0?, …
```
> downloader: got sigbus on writemap

- cl/beacon/handler/data_test.go
- cl/beacon/handler/handler.go
- cl/beacon/handler/pool_test.go
- cl/beacon/handler/rewards_test.go
- cl/beacon/handler/states_test.go
- cl/beacon/handler/utils_test.go
- cl/beacon/handler/validator_registration.go
- cl/beacon/handler/validator_registration_test.go
- cl/sentinel/service/service.go
- cl/validator/validator_params/validator_params.go
- cmd/caplin/caplin1/run.go
Validator clients can now specify Ethereum 1.0 block parameters.
> Caplin: Added preparation for validator block building

- turbo/jsonrpc/tracing.go
evm transaction context not correct when txn is type 3 (EIP-4844)
> evm transaction context not correct when txn is type 3 (EIP-4844)

- erigon-lib/downloader/downloader.go
This removes a never ending loop when the downloader db is removed and the web downloader is not present
> Add torrentDownload to default downloader case

- cl/beacon/handler/block_production.go
- cl/beacon/handler/handler.go
- cl/beacon/handler/pool.go
- cl/beacon/handler/utils_test.go
- cl/cltypes/solid/attestation_data.go
- cl/cltypes/solid/attestation_test.go
- cl/persistence/state/historical_states_reader/attesting_indicies.go
- cl/phase1/core/state/cache_accessors.go
- cl/phase1/forkchoice/checkpoint_state.go
- cl/phase1/forkchoice/on_attestation.go
- cl/phase1/stages/clstages.go
- cl/transition/impl/eth2/operations.go
- cl/validator/attestation_producer/attestation_producer.go
- cl/validator/attestation_producer/attestation_producer_test.go
- cl/validator/attestation_producer/interface.go
- cmd/caplin/caplin1/run.go
When we are required to produce an attestation data object. we first asses 2 things:
* What epoch is it from?
* Is it from a future epoch?
* Is it from a past epoch?
This attestationData object changes only within different epochs, it is extremely cheap to produce `AttestationData` for the current epoch, but extremely expensive for past and future epochs.
```go
return solid.NewAttestionDataFromParameters(
slot,                                  // slot requested
committeeIndex,                        // committee_index request
headBlockRoot,                         // current head block root
baseState.CurrentJustifiedCheckpoint(),// current justified checkpoint
solid.NewCheckpointFromParameters(     // finalization vote
targetRoot,
targetEpoch,
),
), nil
```
This works in 90 microseconds …
> Caplin: Implemented Attestation Data production

- turbo/snapshotsync/freezeblocks/block_snapshots.go
slot.IDHash is used as a tx key, but for isSystemTx case, its value is not fully reset on loop iterations.
PutUint64 only sets the first 8 bytes while the rest 24 bytes contained garbage - a partial hash of a previous tx.
> snapshots: fix system tx hash in transactions indexes

- eth/stagedsync/stage_log_index.go
- eth/stagedsync/stage_log_index_test.go
Earlier assumption was that `PruneLogIndex` would only have to deal with block numbers after the last prune. So it could work with `tx.cursor.First()`. Now, after prune hack, `kv.TransactionLog` contains older logs for `noPruneContracts`, so, it must seek to the point of last prune progress.
Without this, for every update of head block, the stages would run incrementally, but `LogIndex Prune` would run from the beginning of `TransactionLog` table, spending 1-2 hours.
> Fix LogIndex Prune

- cl/sentinel/gossip.go
To avoid unnecessary map copy, let's use `sync.Map` to manage subscriptions
> use sync.Map in gossipManager.subscriptions

- erigon-lib/downloader/torrent_files.go
- erigon-lib/downloader/webseed.go
- don't skip webseed if .torrent file exists (because download maybe not completed yet)
- don't discover webseed if `prohibit_new_downloads.lock` exists - it's "download completed"
> downloader: don't skip webseed if .torrent file exists (because download maybe not completed yet)

- core/rawdb/accessors_chain.go
- erigon-lib/kv/mdbx/kv_mdbx.go
- turbo/jsonrpc/erigon_receipts.go
- turbo/jsonrpc/eth_receipts.go
- currently manually closing iterator, but later I may auto-close it when `it.HasNext()` turn false
- FYI: all iterators are also auto-closed now when `tx.Rollback/Commit`
> RPC: close `tx.Prefix` iterator for early release memory

- cmd/integration/commands/stages.go
- eth/backend.go
- eth/stagedsync/stage_headers.go
- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- turbo/stages/mock/mock_sentry.go
- turbo/stages/stageloop.go
Remove unused references to `forkValidator` and simplify parameters. No change to any logic
> forkvalidator: remove unsued references

- cl/gossip/gossip.go
- cl/sentinel/gossip.go
- cl/sentinel/sentinel_gossip_test.go
- cl/sentinel/service/start.go
- cl/validator/attestation_producer/attestation_producer.go
Sentinel has a time-based subscription system, which means that subscriptions persists only until a specific point in time is reached.
```go=
func (sub *GossipSubscription) OverwriteSubscriptionExpiry(expiry time.Time) {
sub.expiration.Store(expiry)
}
```
All gossip topics are joined which means we can publish at all times, but not all gossip topics are listened to, which means we are not listening for all topic's subscriptions. calling the function above will keep make Caplin listen to that topic until `expiry`is reached. once rached, the listener will be closed **but we can still publish** if we set the expiry, so that now we need to listen again, then we will revive the subscription.
> Proper Caplin's subscription listen

- erigon-lib/diagnostics/provider.go
On the exit of Erigon the Send function can be found sending on a closed channel causing panic. 
Given the nature of diagnostic messages, this can be avoided with a workaround.
> diagnostics: protect Send from panic 

- eth/stagedsync/stage_finish.go
new_heads events were not correctly emitted during block forks. This fix ensures accurate event generation and emission in fork scenarios.
> Fix new_heads Events Emission on Block Forks

- cmd/prometheus/dashboards/erigon.json
- erigon-lib/state/aggregator_v3.go
- erigon-lib/state/domain.go
- erigon-lib/state/domain_test.go
- erigon-lib/state/history.go
- erigon-lib/state/inverted_index.go
both index and domain `canPruneUntil` check returned false in case when `untilTx > maxTxInFiles && minIdxTx < maxTxInFiles` which led to db growth.
- Removed method `CanPruneUntil` because its redundancy
- fix same bug in domain
- added metrics for grafana to see if we got more to prune
> E35 prune check fix

- turbo/cli/default_flags.go
`miner.recommit` flag wasn't registered earlier to use in cli. This PR adds that. 
Note: This is for validator support on Polygon PoS.
> turbo/cli: register miner.recommit flag in cli

- erigon-lib/kv/mdbx/kv_mdbx.go
setup_debug is non-env global func
> mdbx: call global func only for chandb 

- cmd/integration/commands/stages.go
- eth/backend.go
- p2p/sentry/sentry_multi_client/broadcast.go
- p2p/sentry/sentry_multi_client/sentry_api.go
- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- p2p/sentry/status_data_provider.go
- polygon/p2p/message_listener.go
- polygon/p2p/message_listener_test.go
- polygon/p2p/service.go
- polygon/sync/service.go
- turbo/app/import_cmd.go
- turbo/jsonrpc/eth_subscribe_test.go
- turbo/stages/bodydownload/body_algos.go
- turbo/stages/mock/mock_sentry.go
- turbo/stages/mock/sentry_mock_test.go
- turbo/stages/stageloop.go
The responsibility to maintain the status data is moved from the stageloop Hook and MultiClient to the new StatusDataProvider. It reads the latest data from a RoDB when asked. That happens at the end of each stage loop iteration, and sometimes when any sentry stream loop reconnects a sentry client.
sync.Service and MultiClient require an instance of the StatusDataProvider now. The MessageListener is updated to depend on an external statusDataFactory.
> p2p/sentry: status data provider refactoring

- turbo/app/support_cmd.go
`erigon support` now doesn't exit on `Ctrl+C` and can't take a look list of goroutines without --pprof
> support: add --pprof flag (same as in erigon)

- erigon-lib/etl/collector.go
- erigon-lib/etl/dataprovider.go
- erigon-lib/kv/membatch/mapmutation.go
```
// sortAndFlushInBackground increase insert performance, but make RAM use less-predictable:
//   - if disk is over-loaded - app may have much background threads which waiting for flush - and each thread whill hold own `buf` (can't free RAM until flush is done)
//   - enable it only when writing to `etl` is a bottleneck and unlikely to have many parallel collectors (to not overload CPU/Disk)
```
I will enable it in: 
- e2 batch flush	
- e3 execution (it writing to 7 etl collectors) and batch flush
Example of bad behavior of this feature: I did run erigon on 112 core machine with slow disk and 1Tb RAM - did `erigon snapshots index`, it overloaded CPU and Disk and got OOM kill (and 10K-threads-limit golang's panic). Without this feature - erigon eat 24gb RAM
So, better make Erigon …
> etl: make `SortAndFlushInBackground` feature optional 

- eth/backend.go
- params/version.go
- turbo/execution/eth1/ethereum_execution.go
- turbo/execution/eth1/forkchoice.go
- turbo/stages/mock/mock_sentry.go
Revert PR #9315 since it apparently causes MDBX bloat and performance regression. The regression was introduced in [v2.58.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.58.0).
> Revert "updateForkChoice: support --sync.loop.block.limit (#9315)"

- core/rawdb/blockio/block_writer.go
- erigon-lib/kv/rawdbv3/txnum.go
- eth/stagedsync/stage_bodies_test.go
This patch will retry `MakeBodiesCanonical` in case it meet the gap (but it tries only once)
Should heal 
`err="[5/15 Bodies] make block canonical: append with gap blockNum=54700000, but current heigh=54592384`
> retry make canonical bodies in case of txnums  append gap

- cmd/utils/flags.go
- core/genesis_write.go
- erigon-lib/txpool/txpoolcfg/txpoolcfg.go
- erigon-lib/txpool/txpooluitl/all_components.go
- eth/backend.go
- eth/ethconfig/config.go
- turbo/cli/default_flags.go
Replaced the `--override.cancun` flag with `--override.prague`.
Also, removed `Txpool.OverrideCancunTime` as its counterpart isn't (yet) needed for Prague.
> override.cancun -> override.prague

- erigon-lib/downloader/downloader.go
we recently changed field which used to measure progress from `t.BytesCompleted()` to `t.Stats().BytesReadData` - and seems it doesn't include "re-hashing" progress - so progress doesn't grow in logs and looks like it's stuck.
argument to change - was: `t.BytesCompleted()` is not recommended to use for "download rate calculation". 
We don't use this field for rate calc, we using it for progress calc
> downloader: to show more gradual progress when re-hashing/verying files

- polygon/bor/bor.go
reverts 799a9405bf50466e53280243d0011f9f7f0a4226
> fix mumbai execution when no borevents got for block

- polygon/sync/block_downloader.go
- polygon/sync/block_downloader_test.go
- polygon/sync/execution_client.go
- polygon/sync/log_prefix.go
- polygon/sync/service.go
- polygon/sync/storage.go
- polygon/sync/sync.go
- polygon/sync/tip_events.go
Fixes problems found during bor-mainnet sync tests:
- sync.Run was missing a for loop for initial sync convergences
- temporarily disabling ForkChoiceUpdate execution since we are yet to solve and add missing state sync events and spans
- no need to flush storage inside block downloader (better async performance)
- logging improvements
> polygon/sync: fix issues found during testing

- polygon/heimdall/client.go
- polygon/heimdall/heimdall.go
- polygon/heimdall/log_prefix.go
- polygon/heimdall/waypoint.go
- fixes an issue where heimdall polling goroutines get terminated upon a heimdall http err which is incorrect - these polling routines should be kept alive upon errors and errors should simply be logged
- adds logging
- reduces cyclomatic complexity by extracting logic for polling events, spans, checkpoints
> polygon/heimdall: heimdall improvements after astrid sync tests

- cl/antiquary/state_antiquary.go
- cl/persistence/state/historical_states_reader/historical_states_reader_test.go
- cl/persistence/state/static_validator_table.go
Basically we keep the history of somewhat static fields in memory of our validatorset (this is cheap). however when restarting the node and reading these static fields, we do not reset them to the closes valid slot for incremental processing
> Caplin: Fixed archive node validator set lists.

- erigon-lib/seg/decompress.go
Do not open files which are bigger than 32 bytes but "has no" words in it.
> do not open corrupted file

- core/rawdb/accessors_chain.go
- p2p/sentry/status_data_provider.go
P2P fails on restart because rawdb.ReadCurrentHeader returns a nil header. It looks like ReadHeadHeaderHash fails to find the current header hash. However the correct hash is returned by ReadHeadBlockHash.
> p2p/sentry: StatusDataProvider ReadCurrentHeader error

- turbo/jsonrpc/debug_api.go
It seems like you need context when implementing `GetModifiedAccountsByHash`.
However, it is not specified in the interface.
> turbo/jsonrpc: improved interface readability

- turbo/adapter/ethapi/api.go
- turbo/jsonrpc/tracing.go
When not specified, gas fee cap should default to base fee to prevent errors where gas fee cap is less than block base fee.
Fixes #9870
> Fix default gas values in `debug_` RPCs

- .github/workflows/qa-snap-download.yml
Starts Erigon from scratch, monitors the snapshot download process and waits for it to complete within 4 hours, reporting times for download and indexing phases. Fails if the download phase doesn't finish on time
> qa tests: add snap download test workflow

- cmd/snapshots/cmp/cmp.go
- cmd/snapshots/copy/copy.go
- cmd/snapshots/manifest/manifest.go
- cmd/snapshots/torrents/torrents.go
- cmd/snapshots/verify/verify.go
- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/rclone.go
- erigon-lib/downloader/rclone_test.go
- eth/stagedsync/stage_snapshots.go
This PR adds headers which prevent the cloudflare firewall from banning the downloaders http requests.
At the moment these are not obfuscated in the codebase.
This should be reviewed before this change is committed to the core repo.
> Add cloudflare app firewall specific headers   

- eth/stagedsync/stage_log_index.go
- eth/stagedsync/stage_log_index_test.go
Improves upon https://github.com/ledgerwatch/erigon/pull/9913
Closes https://github.com/ledgerwatch/erigon/issues/9889
> Fix older logs pruning

- turbo/app/support_cmd.go
Set default values for "debug.addrs" and "diagnostics.addr"  to make support command compact:
OLD -> ./build/bin/erigon support --debug.addrs localhost:6060 --diagnostics.addr localhost:8080 --diagnostics.sessions 15947373
NEW -> ./build/bin/erigon support --diagnostics.sessions 15947373
> set default values for diagnostic address and debug address

- erigon-lib/seg/decompress.go
- erigon-lib/seg/decompress_test.go
- erigon-lib/state/domain.go
- erigon-lib/state/history.go
Introduces `ErrCompressedFileCorrupted`.
Those errors should be handled properly inside aggregator and inside different utilities.
At least we do not open wrong compressed files but we sometimes want to do some extra on those files (eg during run of a `downloader`)
> Clarify decompressor opening errors

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/webseed.go
* Added cf headers to webseed requests
* Extended torrent tequest transport to retry 500+ status responses and count progress and fails
* Added internal torrent status logging for stopped and no-progress files
> Added downloader http handling and extended logging

- cmd/integration/commands/stages.go
- eth/backend.go
- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- turbo/stages/mock/mock_sentry.go
Adds a `disableBlockDownload` boolean flag to current implementation of sentry multi client to disable built in header and body download funcitonality.
Long term we are planning to refactor sentry multi client and de-couple it from custom header and body download logic.
Astrid uses its own body download logic which is de-coupled from sentry multi client. 
When both are used at the same time (using `--polygon.sync=true`) there are 2 problematic scenarios:
- restarting Astrid takes a very long time due to the init logic of sentry multi client. It calls `HeaderDownload.RecoverFromDb` which is coupled to the Headers stage in the stage loop. So if Astrid has fetched 1 million headers but hasn't committed execution yet then this will result in very slow start up since all 1 million blocks have …
> p2p/sentry/sentry_multi_client: flag to disable block download code

- eth/stagedsync/stage_execute.go
- eth/stagedsync/stage_log_index.go
Existing prune had some confusing logic (thanks to me).
In PR, change the logic to:
if receipt, or any individual log in the receipt contains an address in `noPruneContracts` the entire log must be stored and indexed.
Also fixes a regression that logs were not getting indexed - this was due to 
```
if l.BlockNumber < pruneBlock && cfg.noPruneContracts != nil && !cfg.noPruneContracts[l.Address] {
```
Since the individual log object didn't have the block number - something that shouldn't matter.
In PR, change the logic to:
Use `blockNum` from outer loop
> Fix missing prune log index

- cmd/integration/commands/flags.go
- cmd/integration/commands/stages.go
- core/rawdb/rawdbreset/reset_stages.go
--reset clears all the tables associated with a stage, while we just want to reset the prune_at progress to 0 for some situations
> cmd/integration: log index stage sub command to reset only prune_at point

- erigon-lib/state/domain.go
- erigon-lib/state/domain_test.go
- erigon-lib/state/history.go
- erigon-lib/state/history_test.go
- erigon-lib/state/inverted_index.go
- erigon-lib/state/inverted_index_test.go
Fixes panic and log prints
```
DBUG[04-17|03:03:11.204] [agg] History.openFiles                  err="compressed file \"v1-accounts.1344-1408.v\" dictionary is corrupted: size 9.3 GB but no words in it" f=/mnt/erigon/snapshots/history/v1-accounts.1344-1408.v
panic: History(code).openFiles: compressed file "v1-code.1344-1408.v" dictionary is corrupted: size 3.9 MB but no words in it
github.com/ledgerwatch/erigon/cmd/integration/commands.allSnapshots.func1()
github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:1743 +0x4c8
sync.(*Once).doSlow(0xc00102fbc0?, 0xc00102b870?)
sync/once.go:74 +0xc2
sync.(*Once).Do(...)
sync/once.go:65
github.com/ledgerwatch/erigon/cmd/integration/commands.allSnapshots({0x1ebbe30?, 0x2c90460?}, {0x1ec32a0?, 0xc0004d68c0?}, …
```
> opening domains/hsit/indices with corrupted files on disk

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/torrent_files.go
- erigon-lib/downloader/util.go
- erigon-lib/downloader/webseed.go
- existence check and creation must be inside same `mutex.Lock`
- use ".tmp + rename" trick
Example of possible race: 
```
[EROR] [04-19|03:33:12.908] Erigon startup                           err="rename /mnt/erigon/snapshots/v1-000900-001000-transactions.seg.torrent.tmp /mnt/erigon/snapshots/v1-000900-001000-transactions.seg.torrent: no such file or directory"
```
> downloader: step towards atomic fs

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
- PutUvarint can produce 10 bytes
- re-using buffer - faster and less gc
> Caplin: indexing to use right buf size 

- cl/aggregation/pool_impl.go
- cl/beacon/handler/pool.go
- cl/beacon/handler/pool_test.go
- cl/beacon/handler/subscription.go
- cl/beacon/handler/utils_test.go
- cl/beacon/handler/validator_test.go
- cl/beacon/router.go
- cl/beacon/synced_data/synced_data.go
- cl/clparams/config.go
- cl/cltypes/solid/attestation.go
- cl/phase1/forkchoice/forkchoice_mock.go
- cl/phase1/network/gossip_manager.go
- cl/phase1/network/services/aggregate_and_proof_service.go
- cl/phase1/network/services/attestation_service.go
- cl/phase1/network/services/attestation_service_test.go
- cl/phase1/network/services/sync_committee_messages_service.go
- cl/phase1/network/services/sync_contribution_service.go
- cl/phase1/network/subnets/subnets.go
- cl/sentinel/discovery.go
- cl/sentinel/gossip.go
- cl/sentinel/handlers/heartbeats.go
- cl/sentinel/sentinel.go
- cl/sentinel/service/service.go
- cl/sentinel/utils.go
- cl/validator/attestation_producer/attestation_producer.go
- cl/validator/sync_contribution_pool/sync_contribution_pool.go
- cmd/caplin/caplin1/run.go
* Fixed and simplified unaggregated bits check.
* There are 2 bits on, one for the attester and one for the End-of-bitlist, needed to account for end of bitlist bit
* Wrong publishing topic for sync_committee_ messages
* Added more Ignore by receiving specific errors to avoid forwarding useless data.
* Replaced `validateAttestation` with full message processing
* Fixed forwarding of sync committee aggregates
* Fixed subnet announcements
> First round of fixes in making gossip publishing good for the validator: See comment

- turbo/jsonrpc/otterscan_trace_transaction.go
This is for E2.
It implements the backward compatible output field for traces on ots_traceTransaction: https://github.com/otterscan/execution-apis/pull/1
It'll be consumed by Otterscan in an upcoming release of this feature: https://github.com/otterscan/otterscan/issues/1530
> Implement the optional output field on ots_traceTransaction

- erigon-lib/downloader/downloader.go
Add missing body close method when webseed roundtrip is retried
> Added body close on retry for downloader round trip

- cmd/rpcdaemon/graphql/graph/schema.resolvers.go
- cmd/rpcdaemon/graphql/graphql_test.go
- cmd/rpcdaemon/graphql/query_block.graphql
Set baseFeePerGas value in graphql resolver for block
> Set block baseFeePerGas value in graphql response

- core/state_transition.go
- core/vm/evm.go
The `StateTransition` property `gas` actually tracks the remaining gas in the current context. This PR is to improve code readability.
Geth also uses similar naming.
> vm: Rename stateTransition gas to gasRemaining

- polygon/p2p/message_listener.go
Observed the following issue in a long running Astrid sync on bor-mainnet:
```
[DBUG] [04-17|14:25:43.504] [p2p.peerEventObserver] received new peer event id=Disconnect peerId=51935aa1eeabdb73b70d36c7d5953a3bfdf5c84e88241c44a7d16d508b281d397bdd8504c934bfb45af146b86eb5899ccea85e590774f9823d056a424080b763
[DBUG] [04-17|14:25:43.504] [p2p.peerEventObserver] received new peer event id=Connect peerId=51935aa1eeabdb73b70d36c7d5953a3bfdf5c84e88241c44a7d16d508b281d397bdd8504c934bfb45af146b86eb5899ccea85e590774f9823d056a424080b763
```
Note the timestamps are the same on the millisecond level, however the disconnect was processed before the connect which is wrong (connect should always be first).
This then got the `PeerTracker` in a bad state - it kept on returning peer …
> polygon/sync: message listener to preserve peer events ordering

- sonar-project.properties
- Excludes go mock generated files from analysis
- Excludes broken js files (valid as they are used for tracers and test data) to fix below warnings
> sonar: fix js warnings and exclude mocks

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/downloader_grpc_server.go
The downloader is not complete until all of its requested files have been downloaded.
This changes adds a request count to the downloader stats to be checked for completeness, otherwise the downloader
may appear complete before all required torrents have been added.
> Added downloader request count

- eth/stagedsync/stage_log_index.go
**Summary**
Fixes prune point for log (+index)
- Unnecessary to use ETL again for deleting `kv.Log` entries, delete in the initial loop
- Put the last `pruneTo` block number in the `PruneState` - this will begin pruning from that point. Earlier the `pruneFrom` point being passed in was buggy as it used some other assumption for this value
> stagedSync: Optimize prune old chunks

- cl/phase1/core/state/accessors.go
- eth/tracers/logger/access_list_tracer.go
> chore: fix comments

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/mdbx_piece_completion_test.go
After switching to more durable db mode https://github.com/ledgerwatch/erigon/pull/10010 - we don't need manual fsync anymore.
> downloader: remove deprecated manual fsync 

- cl/beacon/handler/pool.go
- cl/cltypes/solid/attestation.go
- cl/phase1/network/services/attestation_service.go
This PR fixes 2 things:
* Superset handling (should ignore)
* SSZ offset not set for custom ssz in attestation encoding after json unmarshalling
> Caplin: fixed attestation broadcasting

- turbo/jsonrpc/otterscan_api.go
- turbo/jsonrpc/otterscan_block_details.go
For E2: fix incorrect type + overflow in certain blocks
Corresponding otterscan issue: https://github.com/otterscan/otterscan/issues/1658
> [ots] Fix incorrect return type and overflow on total block fees calc

- cmd/utils/flags.go
- common/prque/lazyqueue.go
- crypto/signature_test.go
- erigon-lib/recsplit/recsplit.go
- eth/stagedsync/stage_log_index.go
- turbo/adapter/ethapi/api.go
- turbo/jsonrpc/eth_api.go
- turbo/rpchelper/helper.go
use https://github.com/Abirdcfly/dupword to check repetitive words
> chore: remove repetitive words with tools

- eth/stagedsync/stage_finish.go
- turbo/jsonrpc/eth_subscribe_test.go
Reverts ledgerwatch/erigon#10072
> Revert "Fix new_heads Events Emission on Block Forks"

- cmd/devnet/services/polygon/heimdall.go
- eth/stagedsync/bor_heimdall_shared.go
- eth/stagedsync/stage_bor_heimdall.go
- eth/stagedsync/stagedsynctest/harness.go
- polygon/bor/bor_test.go
- polygon/heimdall/client.go
- polygon/heimdall/client_mock.go
- polygon/heimdall/event_record.go
For period where there are not many sync events (mostly testnets) sync event fecthing can be slow becuase sync events are fetched at the end of every sprint.
Fetching the next and looking at its block number optimizes this because fetches can be skipped until the next known block with sync events.
> Fetch and skip sync events

- erigon-lib/state/aggregator_bench_test.go
- erigon-lib/state/btree_index.go
- erigon-lib/state/btree_index_test.go
- erigon-lib/state/domain_shared.go
- erigon-lib/state/domain_test.go
- turbo/app/snapshots_cmd.go
- Do not store data file pointer linked to index inside index itself
- ask external ArchiveGetter to be provided.
- use existing getters during storage iteration
- move functions suitable for testing to test
> E35 bt cleanup

- accounts/abi/bind/template.go
- consensus/aura/auraabi/gen_block_reward.go
fixes https://github.com/ledgerwatch/erigon/pull/7593 
it introduced a regression: `"fmt"` and `"reflect"` imports were added for all files generated by `abigen` assuming that they will be used in all cases, however that assumption was wrong for some cases resulting in invalid code being generated (in this case after running `make devtools`):
> abi: fix abigen issue with make devtools

- erigon-lib/kv/mdbx/kv_mdbx.go
`HasNext` will return true even with existing error and the application will expect a next entry. The `Next` function can get into an internal error (such as a `panic()`) while fetching the next cursor item and thus fail to return the error.
https://github.com/ledgerwatch/erigon/blob/5ee7f3e2e8f8bc35a27978b14119b32e18fe163d/erigon-lib/kv/mdbx/kv_mdbx.go#L2035-L2039
Inspired by https://github.com/ledgerwatch/erigon/issues/9893, with the logs available at https://gist.github.com/banteg/14cc9193c7c78331e97b28b71dc695c3
This is triggered (as above) in the following section
https://github.com/ledgerwatch/erigon/blob/5ee7f3e2e8f8bc35a27978b14119b32e18fe163d/turbo/jsonrpc/eth_receipts.go#L181-L183
Requesting additional comments, as I don't have deeper understanding of mdbx internals
> mdbx: Return err early in iter.Next()

- cmd/diag/db/db.go
- cmd/diag/main.go
Added command to print databases tables basic info. There are two options :
- print all info: ./build/bin/diag dbs all
- print only populated tables and dbs: ./build/bin/diag dbs pop   
Here is example output:
@taratorio if you want I can add flag which will print specific DB.
> added print DBs table sizes

- erigon-lib/kv/mdbx/kv_mdbx.go
Problem: if --pageSize parameter not set - we using `default pagesize` instead of `real pagesize of db`. And it causing different `dirtySpace` size (because it's accounted in "pages")
> mdbx: pre-open read pagesize from db

- turbo/jsonrpc/erigon_receipts.go
- turbo/jsonrpc/eth_api.go
- turbo/jsonrpc/eth_receipts.go
- turbo/jsonrpc/eth_system.go
- turbo/jsonrpc/graphql_api.go
- turbo/jsonrpc/otterscan_api.go
- turbo/jsonrpc/otterscan_block_details.go
- turbo/jsonrpc/otterscan_search_trace.go
- turbo/jsonrpc/otterscan_transaction_by_sender_and_nonce.go
- turbo/jsonrpc/overlay_api.go
for https://github.com/ledgerwatch/erigon/issues/10099
for things like `eth_getTransactionReceipt`, `ots_searchTransactionsAfter`, etc...
Also moved:
- moved `api.chainConfig()` inside `api.getReceipts()`
- switched `ots` to use blocks/receipts lru
- switched price oracle to use blocks/receipts
> RPC: Receipts LRU cache

- eth/backend.go
- polygon/sync/execution_client.go
- polygon/sync/service.go
ExecutionEngine was meant for the engine API compatibility mode. Switch to using a generated ExecutionClient interface. We never need a remote mode and it always ends up being an instance of ExecutionClientDirect implemented by EthereumExecutionModule.
If we want to add custom methods to it we could:
1) make our own PolygonExecution interface with the methods we need
2) make EthereumExecutionModule conform to PolygonExecution (add new methods there - it already implements all current execution.proto)
3) pass `backend.eth1ExecutionServer` as an instance of PolygonExecution
I can do this in the next PR if we want this.
> polygon/sync: use a direct execution API client

- erigon-lib/kv/mdbx/kv_mdbx.go
Reverts ledgerwatch/erigon#10113
> Revert "mdbx: pre-open read pagesize from db"

- eth/backend.go
- migrations/prohibit_new_downloads2.go
- turbo/snapshotsync/snapshotsync.go
When adding bor waypont types I have removed snaptype.AllTypes because it causes package cross-dependencies.
This fixes the places where all types have been used post the merge changes.
> Replace snaptype.AllTypes with local definitions

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-tip-tracking.yml
This PR
- avoids installing Golang on every test run, 
- clean up the testbed datadir at the end of the test
> qa-tests: small improvements

- cmd/utils/flags.go
`go run ./cmd/downloader torrent_create --datadir=/Users/alex.sharov/data/sepolia34 --chain=sepolia --pprof`
```
panic: unexpected type: *cli.UintFlag
github.com/ledgerwatch/erigon/cmd/utils.CobraFlags(0x2?, {0xc0009ebdc8, 0x3, 0x7660?})
github.com/ledgerwatch/erigon/cmd/utils/flags.go:1920 +0x20e
main.init.0()
github.com/ledgerwatch/erigon/cmd/downloader/main.go:85 +0xc9
exit status 2
```
> fix flags parsing 

- cl/pool/operation_pool.go
relates to https://github.com/ledgerwatch/erigon/issues/10139
> fix concurrent rw on map in operation_pool

- cmd/silkworm_api/snapshot_idx.go
- cmd/snapshots/cmp/cmp.go
- core/snaptype/block_types.go
- core/snaptype/block_types_test.go
- erigon-lib/chain/snapcfg/util.go
- erigon-lib/downloader/snaptype/caplin_types.go
- erigon-lib/downloader/snaptype/caplin_types_test.go
- erigon-lib/downloader/snaptype/files.go
- erigon-lib/downloader/snaptype/type.go
- eth/backend.go
- eth/stagedsync/stage_snapshots.go
- migrations/prohibit_new_downloads2.go
- p2p/sentry/simulator/sentry_simulator.go
- polygon/bor/snaptype/types.go
- polygon/bor/snaptype/types_test.go
- polygon/heimdall/simulator/heimdall_simulator.go
- turbo/app/snapshots_cmd.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_reader_test.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
- turbo/snapshotsync/snapshotsync.go
This resolves https://github.com/ledgerwatch/erigon/issues/10135
All enums are constrained by their owning type which forces package includsion and hence type registration. 
Added tests for each type to check the construction cycle.
> Refactored types to force runtime registrations to be type dependent

- erigon-lib/txpool/txpoolcfg/txpoolcfg.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/gasprice/gasprice.go
- eth/gasprice/gaspricecfg/gaspricecfg.go
This PR enforces the params `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` to be set to 30 gwei when running `erigon` for Polygon chains.
`bor` related PR: https://github.com/maticnetwork/bor/pull/1232
> eth, txpool: enforce 30gwei for gas related configs for polygon

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/webseed.go
Fix a timing hole where torrents that get created before webseeds have been downloaded don't get webseeds set.
> Set existing torrent webseeds after download

- erigon-lib/common/chan.go
- erigon-lib/go.mod
- erigon-lib/kv/mdbx/kv_mdbx.go
- erigon-lib/kv/remotedb/kv_remote.go
- rpc/http.go
- turbo/execution/eth1/block_building.go
- turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
- turbo/execution/eth1/ethereum_execution.go
- turbo/execution/eth1/forkchoice.go
- turbo/execution/eth1/getters.go
- turbo/execution/eth1/inserters.go
see https://github.com/ledgerwatch/erigon/issues/9786
Changes:
* improved logging
* check ctx in ServeHTTP: The context might be cancelled if the client's connection was closed while waiting for ServeHTTP. 
* If execution API returns ExecutionStatus_Busy, limit retry attempts to 10 seconds. This timeout must be lower than a typical client timeout (30 sec), in order to give the client feedback about the server status.
* If execution API returns ExecutionStatus_Busy, increase retry delay from 10 ms to 100 ms to avoid stalling ourselves with multiple busy loops. IMO this delay should be higher (e.g. 1 sec). Ideally we shouldn't do polling at all, but doing a blocking ctx call requires rearchitecting the ExecutionStatus_Busy logic.
> Engine API: NewPayload fails with a "context canceled" error when calling CurrentHeader/GetHeader (#9786)

- erigon-lib/common/chan.go
- erigon-lib/go.mod
- erigon-lib/kv/mdbx/kv_mdbx.go
- erigon-lib/kv/remotedb/kv_remote.go
- rpc/http.go
- turbo/execution/eth1/block_building.go
- turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
- turbo/execution/eth1/ethereum_execution.go
- turbo/execution/eth1/forkchoice.go
- turbo/execution/eth1/getters.go
- turbo/execution/eth1/inserters.go
* improved logging
* check ctx in ServeHTTP: The context might be cancelled if the client's connection was closed while waiting for ServeHTTP.
* If execution API returns ExecutionStatus_Busy, limit retry attempts to 10 seconds. This timeout must be lower than a typical client timeout (30 sec), in order to give the client feedback about the server status.
* If execution API returns ExecutionStatus_Busy, increase retry delay from 10 ms to 100 ms to avoid stalling ourselves with multiple busy loops. IMO this delay should be higher (e.g. 1 sec). Ideally we shouldn't do polling at all, but doing a blocking ctx call requires rearchitecting the ExecutionStatus_Busy logic.
see https://github.com/ledgerwatch/erigon/issues/9786
⚠️  note: this is a cherry-pick to `main` of a PR already merged in …
> Engine API: NewPayload fails with a "context canceled" error in Current/GetHeader (#9786)

- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- p2p/sentry/status_data_provider.go
Steps to reproduce:
1) Sync snapshots and no other stage
2) Stop
3) No Head Header so hell break loose.
> Unnecessary Logs in sentry removed

- eth/ethconfig/config.go
- eth/stagedsync/exec3.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
> nil block during execution

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-tip-tracking.yml
This PR brings the changes of #10195 to the branch release/2.60 with the necessary modifications
> qa-tests: updating test workflow on release/2.60

- erigon-lib/kv/iter/iter_exact.go
fixes `ttx.HistoryRange` iterator returning wrong results.
repro logs, for block 5528581, history == `kv.CodeHistory` on sepolia:
```
[INFO] [05-04|18:02:46.612] Min of                                   blockNum=5528581 minTxNum=189735001 maxTxNum=189735097 diff=96
[INFO] [05-04|18:02:47.645] contract                                 k=0xd1d2f378c8442782dc19acdc23d229e543dc9fc3 v=0x count=1
[INFO] [05-04|18:02:47.764] contract                                 k=0xe24403f5ff942dba1b2130835201c973547a08d3 v=0x count=2
[INFO] [05-04|18:02:47.764] contract                                 k=0xd1d2f378c8442782dc19acdc23d229e543dc9fc3 v=0x count=3
[INFO] [05-04|18:02:47.764] contract                                 k=0xe24403f5ff942dba1b2130835201c973547a08d3 v=0x count=4
[INFO] …
```
> Fix buffer overwrite on ttx.HistoryRange

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-tip-tracking.yml
Running a test every day doesn't make sense on an inactive branch. 
It also seems that the schedule trigger favours the main branch if the test workflow has the same name on the main and other branches.
So this PR changes the test trigger to "push events".
> qa-tests: fix workflows for release 2.60

- cmd/rpcdaemon/cli/config.go
- turbo/app/snapshots_cmd.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
Cherry pick PR #10214 into the release
> Blocks snaps - see 0 indices after reopen

- erigon-lib/go.mod
- erigon-lib/go.sum
- go.mod
- go.sum
This adds torrent fixes that remove bad peers due to non handling of http errs.
> torrent v1.54.2-alpha-7 -> v1.54.2-alpha-8 (release/2.60)

- cmd/downloader/main.go
- cmd/integration/main.go
- cmd/rpcdaemon/main.go
@mh0lt please make it compile-time impossible to not register some types. because we have many binaries in `./cmd/*`
steps to reproduce:
- remove borevent.seg file
- start `downloader --seedbox`
- it will not re-download file (even if remove downloader folder)
> downloader: --seedbox doesn't init snaptypes

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-tip-tracking.yml
This pull request introduces several enhancements:
- It specifies in the test workflow that commits on the main or release/3.x branches should be executed on the test-runner labeled Erigon3.
- It enhances the detection of test completion, and will skip uploading test results if they are incomplete, thus avoiding erroneous error signals during the upload process.
- It improves the directory cleanup process
- It increases the workflow timeout (which is 6 hours by default but can be increased to 35 days on self-hosted runners)
> qa-tests: targeting test-runners with labels, detecting test completion, increasing workflow timeout

- erigon-lib/common/dbg/experiments.go
- erigon-lib/seg/decompress.go
`KV_MADV_NORMAL=accounts,storage` - to enable MADVISE_NORMAL for all accounts.kv and storage.kv
`KV_MADV_NORMAL_NO_LAST_LVL=accounts,storage` - same, but don't enable for last-level-file - example: `v1-accounts.0-1024.kv`. Because last-level in-theory must receive lowest read-rate.  
`SNAPSHOT_MADV_RND=false` - can enable MADV_NORMAL for all files (including Blocks snaps)
I think we need enable `KV_MADV_NORMAL_NO_LAST_LVL=accounts,storage` by default - because it's useful for exec and commitment (code - not useful for commitment. commitment itself - seems is not a bottleneck). Let's collect evidences. 
Mainnet: 
```
du -hsc /mnt/erigon/snapshots/domain/*.0-*.kv
5.6G	/mnt/erigon/snapshots/domain/v1-accounts.0-1024.kv
19G	/mnt/erigon/snapshots/domain/v1-code.0-1024.kv
26G …
```
> flag to enable madv_normal for some type of .kv 

- cmd/caplin/main.go
- cmd/devnet/devnet/node.go
- cmd/erigon/main.go
- cmd/silkworm_api/snapshot_idx.go
- diagnostics/setup.go
- turbo/app/backup_cmd.go
- turbo/app/import_cmd.go
- turbo/app/init_cmd.go
- turbo/app/snapshots_cmd.go
- turbo/app/support_cmd.go
- turbo/debug/flags.go
fixed start diag server if metrics address is different from pprof address
> fixed start diag server

- erigon-lib/state/aggregator.go
- erigon-lib/state/domain.go
- erigon-lib/state/history.go
when execution is finished we call pruning with 12h time limit while heuristic could limit pruning throughput (but in this exact case better to increase batch size)
> remove batch limit heuristic for prunes>5h, added stateful prune cursors

- consensus/merge/merge.go
- consensus/misc/eip2935.go
- core/vm/eips.go
- core/vm/instructions.go
- core/vm/jump_table.go
- core/vm/operations_acl.go
- core/vm/runtime/runtime.go
- core/vm/runtime/runtime_test.go
- params/protocol_params.go
Ref https://eips.ethereum.org/EIPS/eip-2935
> EIP-2935 Historical block hashes

- erigon-lib/kv/iter/iter_exact.go
This is similar to https://github.com/ledgerwatch/erigon/pull/10206 , but I think this code is not actually exercised because it seems it would only be used if the first iter from `MergeKVS` is `nil`.
Anyway, since the code exists, it could be prone to the same double caching issue, and can be simplified by turning it into a pass-through adapter.
Also removed the `nil` check on `Close()` from both iterators since the `nil` check is done in the constructor and it doesn't keep internal state anymore.
> Simplify WrapKV in order to prevent breaking KV invariant 2

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-tip-tracking.yml
The recent removal of the `--internalcl` flag has introduced challenges to the Erigon launch command line during testing.
This PR introduces the ability to handle command lines that vary slightly depending on the software version. It is crucial that the command line remains linked to the workflow because it is specific to a repository commit. At the same time, the command line must be determined by the test script, which needs to be aware of certain parameters that influence measurements or operations.
For this iteration, we have opted to pass the Erigon version to the script, allowing it to decide on the appropriate command line configuration. This approach ensures that the test environment is both adaptable and precise, aligning with specific version requirements. Over time, we will …
> qa-tests: avoid --internalcl flag with Erigon3

- cmd/utils/flags.go
- migrations/prohibit_new_downloads2.go
- polygon/bor/snaptype/types.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
This adds additional flag processing to disable waypoint snaps is `bor.waypoints` is not set
> Add flag for bor waypoint types

- turbo/engineapi/engine_block_downloader/block_downloader.go
- turbo/engineapi/engine_block_downloader/core.go
For some reason, at least for the last 2 weeks I've seen some strange behavior, first on 2.60 branch and now on E3 main (not sure if it is related to some recent change or it randomly started manifesting < 2 weeks ago), when I start Erigon and it keep stuck in the "Downloading PoS headers" forever.
Sometimes it takes +15 min to start downloading headers, but most times it gets stuck forever (have left it overnight with no success).
While this PR doesn't fix the actual issue, while trying to do some debug I noticed:
- there is no activity log, it looks like the node is doing nothing.
- can't Ctrl+C to stop it when it gets in this state, have to kill it.
This PR:
- Replaces a for + sleep with a select channel + ticker + check
- Adds a logEvery ticker
- Listens to ctx.Done() in order to make …
> Add context to make function Ctrl+C friendly; add activity logs

- turbo/execution/eth1/forkchoice.go
fixes https://github.com/ledgerwatch/erigon/issues/10285
however, looking at the code, a few lines above, I'm wondering why `tx` actually is nil here, can `tx, err = e.db.BeginRwNosync(ctx)` return `tx == nil` when there is no error?
not clear to me what value `tx` is capturing inside the closure, I'm afraid this fix may hide another bug, I'm a little confused.
> Fix reverse nil check

- erigon-lib/state/history.go
- erigon-lib/state/inverted_index.go
- erigon-lib/state/merge.go
This refactoring should not change any of current code behavior.
- Extract the "get last txNum in files" logic which is duplicated in several places.
- Rename the `cold` param name to `onlyFrozen` in `maxTxNumInFiles` because the current naming is misleading:
- `cold == false`: returns the last txNum in [frozen..., cold...]  range.
- `cold == true`: returns the last txNum in [frozen...] range.
> Refactor maxTxNumInFiles logic; rename cold param to clarify its meaning

- p2p/server.go
fix for 
```
[p2p] Server                             protocol=68 peers=2 trusted=0 inbound=1 LOG15_ERROR= LOG15_ERROR= LOG15_ERROR= LOG15_ERROR= LOG15_ERROR= i/o timeout=53 EOF=65 closed by remote=215 too many peers=6 ecies: invalid message=5
```
> remove nils from p2p logs

- cmd/diag/downloader/diag_downloader.go
If snapshot file downloaded diagnostics command will display sum of downloading process which includes: size, total download time and average download rate.
Example:
> diagnostics: downloaded file details

- .github/workflows/release.yml
- .github/workflows/test-erigon-is-library.yml
- .github/workflows/test-integration-caplin.yml
- .github/workflows/test-integration.yml
Node16 is deprecated and Actions using it will stop being used 3rd of June
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> github: upgrade checkout action to version with node20

- turbo/cli/flags.go
Seems on all networks better have bigger defaults -> less commitments need to calc. 
gnosis has ~10 txs per block, polygon has ~100 txs per block. step is ~1.5M transactions. 
best performance we can show if compute commitment only 1 time per step (at end of step).
> e3 - increase defatults: batchSize from 256Mb to 512mb and default sync.loop.block.limit from 2K to 5K

- erigon-lib/common/collections.go
- polygon/heimdall/entity_store.go
- polygon/heimdall/heimdall.go
- polygon/heimdall/heimdall_mock.go
- polygon/heimdall/heimdall_test.go
- polygon/heimdall/scraper.go
- polygon/heimdall/service.go
- polygon/sync/service.go
- polygon/sync/tip_events.go
* add a new Service for the HeimdallComponent. It will replace `heimdall.go` once everything is ready.
* move entity stores from Scraper to the Service
* implement missing Heimdall interface methods
> polygon/heimdall: heimdall.Service

- core/state/plain_readonly.go
If repeatedly using the plainstate in an iteration you can end up with so many cursors that tx.Rollback/Commit takes a very long time. The fix is to clean up the cursors as you go with Close() on the plainstate.
> tweak(plainstate): add close func to close cursors

- rpc/handler.go
- rpc/handler_test.go
fixes https://github.com/ledgerwatch/erigon/issues/10376
fixes https://github.com/ledgerwatch/erigon/pull/10378
let's wait for user feedback before merging
> rpc/handler: do not append null to stream when json may be valid

- core/genesis_write.go
One thing is returned `statedb` has expired `stateReader` inside and kind of representing genesis updates only as in memory structure. 
#10200
> `GenesisToBlock` use v3 trie computation

- erigon-lib/kv/tables.go
- erigon-lib/state/aggregator.go
- erigon-lib/state/aggregator_files.go
- erigon-lib/state/domain_shared.go
- erigon-lib/state/inverted_index.go
- erigon-lib/state/inverted_index_test.go
- erigon-lib/state/merge.go
- erigon-lib/state/merge_test.go
This is a 1 of N refactoring, I think there is room to improve the code even more, but this PR is already big, so for now just removing duplicated code and grouping some abstractions.
This PR does NOT change any code semantics.
- Remove lots of duplicated code.
- Makes the internal management of the inverted indexes which are not associated with domains more like how domains are arranged.
- Main driver here is to make the code easier to add more inverted indexes, the current code requires touching a lot of places and encourage copy/pasting and repeating code.
> Refactor inverted indexes instances

- cmd/rpcdaemon/README.md
The default range for `eth_getProof` seems be the past 100k blocks instead of 1k as per https://github.com/ledgerwatch/erigon/blob/36b331100e7b31cf4b7469c00412bc0ebcdb610d/cmd/utils/flags.go#L515
> Change default eth_getProof to 100k

- cmd/state/exec3/state.go
- core/genesis_write.go
- core/rawdb/accessors_metadata.go
- erigon-lib/kv/tables.go
- eth/backend.go
E3 needs the genesis for the first block, so we save the genesis config to the database during the chain import and then if we could not recover it, check the DB.
> E3: Fixed import cmd and made Hive tests Runnable

- core/rawdb/accessors_chain.go
- erigon-lib/kv/tables.go
- erigon-lib/txpool/pool_test.go
- turbo/execution/eth1/ethereum_execution.go
- turbo/execution/eth1/forkchoice.go
- turbo/jsonrpc/eth_system.go
The approach is simple, every time the `Execution` module sees a block it saves the number in DB. That number is the heuristics for the "tip of the chain".
Also changes from stages.Finish to stages.Execution. the issue was that  for syncing up everything (stages.Headers as well) is in a single mdbx tx. Now we have separate key which is committed in a small `Update` before the processing.
> Improved `eth_syncing`

- erigon-lib/kv/mdbx/kv_mdbx.go
- eth/stagedsync/exec3.go
- on any disks - it will allow remove `pagefault-amounts` bottleneck and focus on next bottlenecks (like some data is too big, or merge_threshold is too big, etc...)
- it will allow speedup flush and prune on slow disks
- it will increase IO (because db will evict .kv files from page-cache - depends on RAM size)
- it will improve cold-start problem
- on chain-tip - much higher chance that prune will get slow (because old data may be much colder there).
-----
- it also "make sense" because chaindb now is "very hot data"
> mdbx: chaindata enable read-ahead by default

- eth/backend.go
Cherry-pick: https://github.com/ledgerwatch/erigon/commit/be889f6250ffc599e04438d263a0a6515471fd24
> Fixed Bor Log appearing on Ethereum Mainnet (#10405)

- erigon-lib/kv/kv_interface.go
- eth/backend.go
- polygon/heimdall/database.go
- polygon/heimdall/entity_store.go
- polygon/heimdall/service.go
- polygon/sync/service.go
Create a separate mdbx database in `<datadir>/heimdall`.
Rewrite entityStore to use it.
> polygon/heimdall: database

- erigon-lib/state/aggregator.go
- erigon-lib/state/inverted_index.go
- eth/stagedsync/exec3.go
- turbo/app/snapshots_cmd.go
temporal ability to prune commitment history after commitment happened. This decouples overall pruning and hist commitment pruning and helps reduce db size on chain tip. 
I allowed to prune half step right now.
> e3 commitment history backpressure

- erigon-lib/state/aggregator.go
- erigon-lib/state/domain_shared.go
- eth/stagedsync/exec3.go
Maybe it's time to introduce another lock file stored on disk protecting some ranges against their deletion. For now it's just in-memory boolean, which obviously could fault on restart. 
Storing such a lock in DB also doesn't cover corner case when DB empty/doesn't exist. 
This PR just sets in-mem lock during commitment evaluation (since merging is happening in background).
> protect files during commitment

- .github/workflows/qa-sync-from-scratch.yml
sync-from-scratch is now a workflow with multiple jobs each uploading a result file.
Those files need to have a unique name in the workflow.
> qa-tests: in sync-from-scratch use result file with chain in the name, add branch name

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-tip-tracking.yml
This PR adds:
- branch name to the test record on on MongoDb database for doing correct historical comparison
- chain name to prepare this test to run on different chains
> qa tests: add branch name and chain name

- core/vm/eips.go
- core/vm/operations_acl.go
Today it was decided to retroactively include https://github.com/ethereum/EIPs/pull/8564 into pectra-devnet-0 (or certainly for devnet-1).
> Update EIP-2935: Adjust gas-costs for 2935

- turbo/execution/eth1/forkchoice.go
before
```
INFO[05-22|16:23:12.719] RPC Daemon notified of new headers       from=19926586 to=19926587 amount=1 hash=0x983bf3221815287fe724f202acc956d3390bf7d20fff3524adbaddb4c4931385 header sending=8.413µs log sending=152ns
INFO[05-22|16:23:12.719] head updated                             hash=0x983bf3221815287fe724f202acc956d3390bf7d20fff3524adbaddb4c4931385 number=19926587
```
after
```
INFO[05-22|16:23:12.719] RPC Daemon notified of new headers       from=19926586 to=19926587 amount=1 hash=0x983bf3221815287fe724f202acc956d3390bf7d20fff3524adbaddb4c4931385 header sending=8.413µs log sending=152ns
INFO[05-22|16:23:12.719] head updated                             number=19926587 hash=0x983bf3221815287fe724f202acc956d3390bf7d20fff3524adbaddb4c4931385`
```
when latest log looks mostly like …
> print number first to match with new header notification order

- turbo/adapter/ethapi/api.go
`maxFeePerBlobGas` is nil, can not call SetFromBig directly
> fix eth_call 'method handler crashed' error when tx has set maxFeePerBlobGas

- turbo/adapter/ethapi/api.go
old code has side affect, it will cause baseFee to be changed.
so if you set `maxFeePerGas` the gas price will always be `maxFeePerGas` even if `baseFee`+`maxPriorityFeePerGas` is less than `maxFeePerGas`.
> fix gas price not right problem

- cmd/utils/flags.go
- diagnostics/setup.go
- erigon-lib/diagnostics/client.go
- erigon-lib/diagnostics/snapshots_test.go
- erigon-lib/diagnostics/speedtest.go
- Run speed test only once if "--no-downloader" flag set
- Stop speed test when snapshot downloading finished
> diagnostics: disable speedtest

- cmd/rpcdaemon/graphql/graph/schema.resolvers.go
- cmd/rpcdaemon/graphql/graphql_test.go
- cmd/rpcdaemon/graphql/query_block.graphql
Currently ommers hash is not filled in graphQL response.
I need ommers hash for historical data and have to make an additional request to retrieve the block with its uncles.
> Fill ommers hash in graphQL response

- params/bootnodes.go
see: https://github.com/ethereum/discv4-dns-lists
also proof it is functional:
```
dig TXT all.holesky.ethdisco.net
; <<>> DiG 9.10.6 <<>> TXT all.holesky.ethdisco.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6114
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;all.holesky.ethdisco.net.      IN      TXT
;; ANSWER SECTION:
all.holesky.ethdisco.net. 1568  IN      TXT     "enrtree-root:v1 e=72BET3MB7DRDRE2J56WNO6YGPM l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=920 sig=0IQu7ccrToT22F8Mawd1DhMscWrwuRZThKg9y9txXZ90xL5Wq0tCxLF3wt-mX307VSm93gXl8I1wPiP0SLbXUQA"
;; Query time: 5 msec
;; SERVER: 189.38.95.96#53(189.38.95.96)
;; WHEN: Fri May 24 04:01:02 -03 …
```
> Enable DNS p2p discovery on holesky

- core/rawdb/accessors_chain.go
- core/rawdb/blockio/block_writer.go
- eth/stagedsync/stage_bor_heimdall.go
- polygon/bor/bordb/prune.go
- polygon/bor/snaptype/types.go
This add a check for waypoint processing (checkpoints and milestones) to prune operations.
It aims to fix:
https://github.com/ledgerwatch/erigon/issues/10327
https://github.com/ledgerwatch/erigon/issues/10299
https://github.com/ledgerwatch/erigon/pull/10328
> add flag checking for pruning waypoints

- turbo/snapshotsync/freezeblocks/block_reader.go
it's ok to request header by number from files even if it doesn't have canonical marker
> [3/15 BorHeimdall] header not found: 56300000

- erigon-lib/kv/mdbx/kv_mdbx.go
Change merge_threshold=2 is default in mdbx/lmdb. 
It makes db a bit bigger - but prune faster (update/delete ops - cause less page-merged).
> make pruning faster by db size cost

- docs/programmers_guide/db_faq.md
Update db_faq.md because `bucket.go` no longer exists.
> [Doc] bucket.go no longer exists

- erigon-lib/diagnostics/client.go
- erigon-lib/diagnostics/snapshots_test.go
Added new constructor for diagnostics client to avoid DB creation while run test
> diagnostics: fix test db creation

- cl/clparams/config.go
- cl/phase1/core/checkpoint.go
- cmd/capcli/cli.go
- cmd/caplin/caplincli/config.go
- cmd/caplin/caplinflags/flags.go
- cmd/caplin/main.go
- cmd/sentinel/main.go
- cmd/utils/flags.go
- eth/backend.go
- turbo/cli/default_flags.go
- Multiple checkpoint sync urls configured via CLI flag is supported.
- Randomly choose url to try until request gets success
- Failover to default urls (if exist) once all configured urls are failed
> Caplin: configurable checkpoint sync url

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
- turbo/snapshotsync/freezeblocks/bor_snapshots.go
Otherwise: if start after `kill -9` in the middle of merge - may remove small files of 1 type of file, but leave small files of another type of files (which merge was not finished) - and leave node in un-mergable state: https://github.com/ledgerwatch/erigon/issues/10485
> e2: remove overlapped files only after merge

- cmd/integration/commands/stages.go
- eth/backend.go
- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- p2p/sentry/status_data_provider.go
- turbo/stages/mock/mock_sentry.go
ReadCurrentHeaderHavingBody must never return nil, but IRL sometimes it does. In this case the node gets stuck, because it is not possible to start sentry and make progress. Use genesis data when rawdb.ReadCurrentHeaderHavingBody returns nil.
> p2p/sentry: sentry doesn't start with ErrNoHead (#10454)

- polygon/bor/finality/whitelist/milestone.go
- polygon/bor/finality/whitelist/service_test.go
Fixes: https://github.com/ledgerwatch/erigon/issues/10479
> add lock to purgeMilestoneIDsList

- erigon-lib/state/aggregator.go
- erigon-lib/state/aggregator_files.go
A regression was introduced as part of https://github.com/ledgerwatch/erigon/pull/10402 during files merge process where a `nil` pointer can crash erigon.
```
INFO[05-27|15:38:55.343] [snapshots] state merge done accounts(val:148-150, hist:148-150, idx:148-150), storage(val:148-150, hist:148-150, idx:148-150), code(val:148-150, hist:148-150, idx:148-150), commitment(val:148-150)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x103324dfb]
goroutine 832220 [running]:
github.com/ledgerwatch/erigon-lib/state.(*Aggregator).integrateMergedDirtyFiles(_, {{{0xfc002088040, 0x2, 0x2}, {0xfc002088070, 0x2, 0x2}, {0xfc0020880a0, 0x2, 0x2}, ...}, ...}, ...)
github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator.go: …
```
> Fix nil handling

- polygon/heimdall/checkpoint.go
Fixes a recent regression causing unwinds due to checkpoints having zero root hash:
```
[WARN] [05-18|23:58:54.662] [bor] Root hash mismatch while whitelisting checkpoint expected=ac1c57270479250af3ce8eee90075cd8b2ba1bac55353105e063d9a4c87c743e got=0000000000000000000000000000000000000000000000000000000000000000
[WARN] [05-18|23:58:54.662] [bor] Rewinding chain due to checkpoint root hash mismatch number=57125727
```
Note this has already been fixed on Erigon 3 branch but as part of a non-related PR - https://github.com/ledgerwatch/erigon/pull/10124/files#diff-47d4532f399f2d6a45e6f19944a45c80bac573b4d1b5cb51485d0254229d1b16
> polygon/heimdall: fix checkpoint json marshalling

- cmd/diag/db/db.go
- cmd/diag/downloader/diag_downloader.go
- cmd/diag/stages/stages.go
- cmd/diag/util/util.go
Fix https://github.com/ledgerwatch/erigon/issues/10518
> diagnostics: print understandable error

- cmd/snapshots/manifest/manifest.go
- core/blockchain.go
- diagnostics/logs.go
> Fix capacity for immediate appends

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-sync-from-scratch.yml
- .github/workflows/qa-tip-tracking.yml
The sync-from-scratch test takes 12 hours per job (amoy job, sepolia job).
The two jobs can be run on different runners but still risk blocking the other tests.
Since this test does not pass at the moment, we decide to run it only once a week, on Sunday, the day on which we suspend the others.
> qa-tests: run sync-from-scratch only on sunday

- erigon-lib/diagnostics/snapshots.go
Keep listening for snapshot download events even after receiving the download finished event, as it looks like the download now consists of at least two parts:
- downloading the header chain
- download
So, there's a need to keep track of the downloading progress.
> keep snapshot download listener

- eth/ethutils/receipt.go
- turbo/jsonrpc/eth_receipts.go
- turbo/jsonrpc/otterscan_search_v3.go
This fixes Hive test failures like
```
<< (0f4f36d6) {"jsonrpc":"2.0","id":155,"result":{"blobGasPrice":"1","blobGasUsed":"0xc0000","blockHash":"0xdee5398befed018be8f4307ab6f7d4b0f06449880852b1f31d0c5c0820a74de1","blockNumber":"0x1","contractAddress":null,"cumulativeGasUsed":"0x5208","effectiveGasPrice":"0x6fc23ac0","from":"0xf4266f827277b31341deb04983e39c9bc4d66234","gasUsed":"0x5208","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
> blobGasPrice should be marshalled as hex

- cmd/integration/commands/stages.go
- cmd/rpcdaemon/cli/config.go
- erigon-lib/kv/rawdbv3/txnum.go
- erigon-lib/state/aggregator.go
- eth/stagedsync/stage_snapshots.go
- turbo/app/snapshots_cmd.go
```
./build/bin/integration stage_headers --reset --datadir=/erigon-data/ --chain=bor-mainet
INFO[05-31|04:16:21.773] logging to file system                   log dir=/erigon-data/logs file prefix=integration log level=info json=false
INFO[05-31|04:16:21.776] [db] open                                label=chaindata sizeLimit=12TB pageSize=8192
INFO[05-31|04:16:47.715] [snapshots:blocks] Stat                  blocks=56900k indices=56900k alloc=14.0GB sys=14.1GB
INFO[05-31|04:16:47.715] [snapshots:bor] Stat                     blocks=56300k indices=56300k alloc=14.0GB sys=14.1GB
panic: FindBlockNum(4014062500): seems broken TxNum value: 0000000001b21cee -> (, ); last in db: (56900059, 5593)
github.com/ledgerwatch/erigon-lib/kv/rawdbv3.txNums.FindBlockNum.func1(0x8?) …
```
> agg: logStat to `log.Warn` instead of panic

- eth/stagedsync/default_stages.go
- eth/stagedsync/stage_headers.go
- eth/stagedsync/stage_polygon_sync.go
While testing the new polygon sync stage I run into the below error:
```
[EROR] [05-29|21:26:54.099] Staged Sync                              err="[4/6 Execution] ExecV3: TxNums index is at block 6399999 and behind commitment 6426107: behind commitment"
```
This is because we weren't appending the canonical tx numbers to the TxNums index. 
This PR fixes this by extending `fixCanonicalChain` to return `newNodes` and `badNodes` on the path to the connecting point from the new fork choice update. `newNodes` can be used to append the right tx nums to the tx nums index while the `badNodes` can be used to unwind (this will be properly handled in a subsequent PR).
> stagedsync: polygon sync stage to append canonical tx nums

- cl/beacon/beaconhttp/args.go
- cl/beacon/handler/blobs.go
Just added the query params ?indices=1&indices=2&....
> Caplin: Update BlobSidecars Beacon API endpoint to the latest specs

- cl/clparams/config.go
Cherry pick PR #10512 into the release branch
> Caplin: Proper "Normalization" of length of ForkVersions to 8 hex characters

- turbo/snapshotsync/freezeblocks/bor_snapshots.go
Problem: `+1` was added to maxBlockNum instead of minBlockNum
for: https://github.com/ledgerwatch/erigon/issues/10554
> bor blocks retire: infinity loop fix

- eth/stagedsync/stage_polygon_sync.go
Errors from the background components in the new polygon sync stage were not propagated to the stage properly - upon errors the stage just seemed to get stuck without any information.
This was due to 2 reasons: `s.bgComponentsErr` channel not being initialised and errgroup used was not created using `WithContext`. 
This PR fixes that and a deadlock when calling `stopNode` which got uncovered as a result of fixing the 2 bugs above.
> stagedsync: fix error propagation in polygon sync stage

- erigon-lib/txpool/pool.go
- erigon-lib/txpool/pool_test.go
> txpool: EIP-3860 should only apply to create transactions

- polygon/heimdall/entity_fetcher.go
- polygon/heimdall/heimdall.go
Fixes 2 problems with batch fetch checkpoint that I run into during testing of the new polygon sync stage:
- when the tip is after the latest checkpoint.EndBlock we returned error which caused the sync to be stuck - we should return empty list
- turns out the checkpoints/list API has a bug that wasn't noticed - it does not include the "id" field in the json response - have a look at this for example https://heimdall-api-amoy.polygon.technology/checkpoints/list?page=1&limit=2 - this PR works around this by manually setting it within the batch fetch checkpoints logic
> polygon/heimdall: batch fetch checkpoint empty return and id fixes

- erigon-lib/state/history_test.go
- erigon-lib/state/inverted_index.go
- erigon-lib/state/inverted_index_test.go
- Remove useless RWCursor
- fix invariant `if indexed txNum is pruned, no keys in indexValues table should contain that txNum in values, therefore it's pruned fully`
- remove "smart" exit 
relates to https://github.com/ledgerwatch/erigon/issues/10484
> revisit history pruning

- eth/backend.go
Found that there was some unnecessary condition: because `break`'s are everywhere
> ports finder's loop: remove unnecessary checks

- turbo/engineapi/engine_server.go
This PR addresses an issue with the current implementation of the `engine_newPayload` request handling during the initial sync process.
The `engine_newPayload` request triggers validation of newly received payload, and during the initial sync process, Erigon downloads the block headers and blocks since more data is required for validation.
Inside this download logic is validating the chain data after it has finished downloading all the headers. When the node is initially downloading the headers, there is no validated blocks in the Erigon yet as it hasn't run the staged sync yet. Because of this, chain validation is skipped and mark the [download process as complete](https://github.com/ledgerwatch/erigon/blob/5d92302004b81af3ab95d0af31b0de63a6cb3ac7/turbo/engineapi/engine_block_downloader/c …
> Fix NewPayload Validation during header download

- accounts/abi/bind/backends/simulated.go
- cmd/state/exec3/trace_worker.go
- cmd/state/exec3/trace_worker2.go
- consensus/misc/eip1559.go
- core/blockchain.go
- core/evm.go
- core/genesis_write.go
- core/state_processor.go
- core/state_transition.go
- core/vm/eips.go
- core/vm/evmtypes/evmtypes.go
- eth/stagedsync/exec3.go
- eth/tracers/tracers_test.go
- tests/state_test_util.go
- turbo/jsonrpc/eth_block.go
- turbo/jsonrpc/eth_call.go
- turbo/jsonrpc/eth_callMany.go
- turbo/jsonrpc/otterscan_search_trace.go
- turbo/jsonrpc/overlay_api.go
- turbo/jsonrpc/trace_adhoc.go
- turbo/jsonrpc/trace_filtering.go
- turbo/jsonrpc/tracing.go
- turbo/transactions/call.go
- turbo/transactions/tracing.go
Avoid (potentially repeatedly) calling `GetBlobGasPrice` in `opBlobBaseFee`
> Optimize BLOBBASEFEE

- cmd/rpcdaemon/cli/httpcfg/http_cfg.go
- turbo/cli/flags.go
- turbo/engineapi/engine_server.go
- turbo/jsonrpc/corner_cases_support_test.go
- turbo/jsonrpc/daemon.go
- turbo/jsonrpc/debug_api_test.go
- turbo/jsonrpc/erigon_receipts_test.go
- turbo/jsonrpc/eth_api.go
- turbo/jsonrpc/eth_api_test.go
- turbo/jsonrpc/eth_block_test.go
- turbo/jsonrpc/eth_callMany_test.go
- turbo/jsonrpc/eth_call_test.go
- turbo/jsonrpc/eth_filters_test.go
- turbo/jsonrpc/eth_mining_test.go
- turbo/jsonrpc/eth_system_test.go
- turbo/jsonrpc/send_transaction.go
- turbo/jsonrpc/send_transaction_test.go
> rpc: Fix incorrect txfeecap

- core/rawdb/accessors_chain_test.go
- core/types/deposit_request.go
- core/types/encdec_test.go
- core/types/request.go
- turbo/engineapi/engine_types/jsonrpc.go
This is for consistency and since `Withdrawals` is already a terminology used, to which the "deposits" in the context is not 1-to-1 counterpart.
> core: Rename Deposit to DepositRequest for EIP-6110

- eth/stagedsync/stage_polygon_sync.go
- turbo/execution/eth1/inserters.go
One of those bugs...
We were getting the below error when syncing at the tip of the chain with the new polygon sync stage:
```
DBUG[06-06|17:47:24.707] [sync] onNewBlockEvent: couldn't connect a header to the local chain tip, ignoring err="canonicalChainBuilder.Connect: invalid header error invalid baseFee: have 15, want 14017, parentBaseFee 15, parentGasUsed 0"
```
This error is coming from the `VerifyEip1559Header` function and it is a very subtle one. There was nothing wrong with the calculation of Eip1559 base fee or the headers themselves. The issue was coming from the fact that we were unintentionally mutating the `common.Big0` static variable (of type `*big.Int`) which then interfered with subsequent calculations of `VerifyEip1559Header` which uses `common.Big0` …
> stagedsync: polygon sync stage fix invalid baseFee error

- erigon-lib/state/domain.go
- erigon-lib/state/domain_shared.go
- eth/stagedsync/sync.go
- turbo/engineapi/engine_helpers/fork_validator.go
3 Bugs were found:
Unwind would do >1000 blocks for some reason due to limitations of previous unwind, so I removed the restraint
CommitmentState key was not cached which means that the prevValue was always outdated to what the DB had
Caches did not keep track of previous step which caused massive pain and is potentially a cause to a potential corrupt snapshot
> Fixed bugs that made reorg unusable in some situations

- core/rawdb/accessors_chain.go
- erigon-lib/state/domain_shared.go
- erigon-lib/state/domain_shared_test.go
- erigon-lib/state/state_changeset.go
- eth/stagedsync/exec3.go
- eth/stagedsync/stage_execute.go
- eth/stagedsync/stage_finish.go
- turbo/engineapi/engine_helpers/fork_validator.go
- turbo/execution/eth1/ethereum_execution.go
- turbo/execution/eth1/forkchoice.go
We take advantage of sharedDoms
> Avoid using MemBatch in `ValidateChain`

- cmd/erigon/main.go
Simply prints a character graffiti of "Erigon 3"
It has the added benefits of 
- instantly alerting users and developers that they may need to change their ways 
- cross checking that it's the right version, if (like me) folks are switching between E2 and E3 multiple times during the day
- Letting users know that they're using a cool software :)
> fun: Add Erigon 3 graffiti

- cmd/hack/hack.go
- cmd/rpcdaemon/rpcservices/eth_backend.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/accessors_iter.go
- core/snaptype/block_types.go
- core/types/block.go
- erigon-lib/state/inverted_index_test.go
- turbo/jsonrpc/eth_block.go
- turbo/jsonrpc/eth_block_test.go
- turbo/services/interfaces.go
- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/dump_test.go
To avoid confusion, this PR renames occurrences of `txAmount` and `txsAmount` in the code base to `txCount`. The word amount has a different meaning, in general. Before this PR, no meaning of the word is being utilized with `txAmount` and can be confused with amount of gas utilized.
> chore: Rename txAmount to txCount

- cmd/rpcdaemon/cli/config.go
- cmd/rpcdaemon/cli/httpcfg/http_cfg.go
- erigon-lib/metrics/register.go
- erigon-lib/metrics/set.go
- eth/backend.go
- go.mod
- turbo/cli/default_flags.go
- turbo/cli/flags.go
- turbo/jsonrpc/eth_block_test.go
- turbo/jsonrpc/eth_call_test.go
- turbo/jsonrpc/eth_filters_test.go
- turbo/jsonrpc/eth_mining_test.go
- turbo/jsonrpc/eth_subscribe_test.go
- turbo/jsonrpc/send_transaction_test.go
- turbo/jsonrpc/txpool_api_test.go
- turbo/rpchelper/config.go
- turbo/rpchelper/filters.go
- turbo/rpchelper/filters_deadlock_test.go
- turbo/rpchelper/filters_test.go
- turbo/rpchelper/logsfilter.go
- turbo/rpchelper/metrics.go
- Introduced `GetOrCreateGaugeVec` function to manage Prometheus `GaugeVec` metrics.
- Implemented various subscription filter limits (max logs, max headers, max transactions, max addresses, and max topics).
- Updated various test files to utilize the new `FiltersConfig` and added comprehensive tests for the new filter limits.
- Added new flags for subscription filter limits.
- Improved log filtering and event handling with better memory management and metric tracking.
- Added configuration to handle RPC subscription filter limits.
- Minor typo fixes.
-------
RPC nodes would frequently OOM. Based on metrics and pprof, I observed high memory utilization in the rpchelper:
```text
File: erigon
Type: inuse_space
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top …
```
> Added RPC filter limits, metrics, and better memory management.

- erigon-lib/downloader/downloader.go
Without this `defer`, the loop here:
```
func() {
for int(done.Load()) < len(files) {
select {
case <-ctx.Done():
return // g.Wait() will return right error
case <-logEvery.C:
if int(done.Load()) == len(files) {
return
}
log.Info("[snapshots] Initiating snapshot-lock", "progress", fmt.Sprintf("%d/%d", done.Load(), len(files)))
}
}
}()
```
will immediately finish as long as all subroutines _start_ instead of _finish_. In worst cases, there is not any progress log get printed if the subroutines start together quickly and erigon seems like stucking forever (though it's processing). To fix it, the done counter should be added only after each subroutine finishes. I think this is the intended behavior of the original code.
> Better progress logging for initSnapshotLock

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-clean-exit-snapshot-downloading.yml
- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-sync-from-scratch.yml
- .github/workflows/qa-tip-tracking.yml
Store the self-hosted runner name in the MongoDB database of test results to better compare performance between test runs. The runner name is associated with its hardware configuration in a MongoDB table.
> qa-tests: save runner name 

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/downloadercfg/dns_cache_resolver.go
- erigon-lib/go.mod
cherry-pick https://github.com/ledgerwatch/erigon/pull/10693 to release
> downloader: Number of DNS requests seem excessive (#5145)

- turbo/jsonrpc/eth_api.go
- turbo/jsonrpc/trace_adhoc.go
and one warning print for sender recovery failure
> jsonrpc: optimization to read header directly in trace

- cmd/evm/internal/t8ntool/execution.go
- cmd/evm/internal/t8ntool/transition.go
- core/state/database_test.go
- core/state/state_writer_v4.go
- core/vm/gas_table_test.go
- core/vm/runtime/runtime.go
- core/vm/runtime/runtime_test.go
closes https://github.com/ledgerwatch/erigon/issues/10639
rest of usages seems to be e2 calls.
> move from e2 to e3 primitives

- core/vm/runtime/runtime.go
- core/vm/runtime/runtime_example_test.go
- core/vm/runtime/runtime_test.go
- tests/fuzzers/runtime/runtime_fuzz.go
for https://github.com/ledgerwatch/erigon/actions/runs/9517264736/job/26259577369?pr=10753#step:11:542
```
--- FAIL: TestBlockhash (0.01s)
runtime_test.go:397: expected no error, got open /tmp/execute-vm/snapshots/salt-state.txt: no such file or directory
FAIL
```
don't use `/tmp` / `os.TempDir()` - because tests are run in-parallel.
> use t.TempDir() in tests

- turbo/jsonrpc/debug_api.go
`debug_accountRange` is one of the cool rpc methods erigon provides. However, the hardcoded limit 256 makes it supper inefficient. In my personal benchmark, raising the limit to 8192 could boost the indexing process 3-4x faster and thus this PR raises the default limit.
I could understand the security consideration of the DDoS attack on this parameter. But it's an RPC method under the `debug` namespace, which is not common for external usage, and both limits impose similar database pressure. Therefore, it should be mostly safe to raise the limit to a moderate value.
> Raise the limit of debug_accountRange to 8192 (if storage not requested)

- erigon-lib/downloader/snaptype/files.go
- turbo/app/snapshots_cmd.go
Allows to skip checking latest actual file range and parse it automatically.
Parsed max step require user prompt to delete:
```
remove latest snapshot files with stepFrom=14?
1) Remove
2) Exit
(pick number): 1
```
> `snapshots rm-state-snapshots --latest` command

- .github/workflows/qa-clean-exit-block-downloading.yml
- .github/workflows/qa-tip-tracking.yml
Some tests utilise a prebuilt database. 
To facilitate historical comparisons, it is useful to record the exact version of Erigon used to pre-build this database
> qa-tests: record the db version used for test

- consensus/chain_header_reader_mock.go
- consensus/consensus.go
- consensus/merge/merge_test.go
- core/chain_makers.go
- core/vm/runtime/runtime_test.go
- eth/consensuschain/consensus_chain_reader.go
- eth/stagedsync/chain_reader.go
- eth/stagedsync/stage_headers.go
- polygon/bor/bor_test.go
The 2 new methods are made available in `consensus.ChainHeaderReader` interface to future usage in tracing revamp.
This is a split PR off of https://github.com/ledgerwatch/erigon/pull/10757.
> Added `CurrentFinalizedHeader` and `CurrentSafeHeader` in chain reader interface

- eth/tracers/config/api.go
- polygon/tracer/trace_bor_state_sync_txn.go
- turbo/jsonrpc/debug_api.go
- turbo/jsonrpc/debug_api_test.go
- turbo/jsonrpc/gen_traces_test.go
- turbo/jsonrpc/tracing.go
- turbo/transactions/tracing.go
This is extracted from https://github.com/ledgerwatch/erigon/pull/10757 to make the overall merge more manageable.
> Moved `tracers.TracerConfig` to its own package to avoid (future) import cycle

- core/state/cached_reader3.go
- core/state/database.go
- core/state/history_reader_v3.go
- turbo/jsonrpc/otterscan_search_trace.go
- turbo/jsonrpc/trace_adhoc.go
- turbo/jsonrpc/trace_filtering.go
- turbo/rpchelper/helper.go
for https://github.com/ledgerwatch/erigon/issues/10444
it also removing use of `state.NewCachedReader` seems need re-introduce it in E3 - to see perf impact.  Creating ticket for it: https://github.com/ledgerwatch/erigon/issues/10747
> trace_block: to change reader's state for each txIndex

- erigon-lib/common/datadir/dirs.go
- turbo/app/snapshots_cmd.go
maybe this is reason why we have couple broken .ef files on ethmainnet/bormainnet - maybe i run this command without stopping erigon (by mistake)
> `erigon snapshots retire` lock datadir

- erigon-lib/diagnostics/snapshots.go
- erigon-lib/diagnostics/snapshots_test.go
Don't display the percent downloaded until we have received all metadata and know the exact file size to avoid confusing users.
> diagnostics: don't show percent downloaded until we get all metadata

- p2p/discover/v4_udp.go
> Fix potential p2p shutdown hangup

- erigon-lib/diagnostics/resources_usage.go
- erigon-lib/diagnostics/snapshots.go
- erigon-lib/diagnostics/stages.go
- erigon-lib/diagnostics/stages_test.go
Fixed warn: 
`[WARN] [06-21|01:46:52.502] [Diagnostics] Can't find running stage or substage while updating Snapshots stage stats. stages:="[{ID:Snapshots State:Running SubStages:[{ID:Download header-chain State:Completed Stats:{TimeElapsed: TimeLeft: Progress:}} {ID:Download snapshots State:Completed Stats:{TimeElapsed:2m40s TimeLeft:999hrs:99m Progress:100.00%}} {ID:Indexing State:Completed Stats:{TimeElapsed: TimeLeft: Progress:}} {ID:Fill DB State:Completed Stats:{TimeElapsed: TimeLeft: Progress:}}] Stats:{TimeElapsed: TimeLeft: Progress:}} {ID:BlockHashes State:Queued SubStages:[] Stats:{TimeElapsed: TimeLeft: Progress:}} {ID:Senders State:Queued SubStages:[] Stats:{TimeElapsed: TimeLeft: Progress:}} {ID:Execution State:Queued SubStages:[] Stats:{TimeElapsed: TimeLeft: Progress:}} …
> diagnostics: fix marking completed stage as running

- turbo/rpchelper/filters.go
- turbo/rpchelper/filters_test.go
- Simplify and enhance tests.
- Add test for invalid slice operations panic.
- Remove unused Mutex
----
I experienced a rare panic with the new filter code.
```text
panic: runtime error: slice bounds out of range [121:100]
goroutine 25311363 [running]:
github.com/ledgerwatch/erigon/turbo/rpchelper.(*Filters).AddPendingTxs.func1({0xc011c67020?, 0xc00a049e20?, 0xc020720b40?}, 0x48?)
github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:720 +0x31a
github.com/ledgerwatch/erigon-lib/common/concurrent.(*SyncMap[...]).DoAndStore.func1(0x20?)
github.com/ledgerwatch/erigon-lib@v1.0.0/common/concurrent/concurrent.go:52 +0x22
github.com/ledgerwatch/erigon-lib/common/concurrent.(*SyncMap[...]).Do(0x33209a0, {0xc013409fa0, 0x20}, 0xc00a049ee0) …
```
> Prevent invalid slice operations in filters

- erigon-lib/downloader/downloader.go
release part of https://github.com/ledgerwatch/erigon/pull/10715
> dl: additional pre-check for having info

- cmd/downloader/main.go
- cmd/hack/tool/tool.go
- core/rawdb/accessors_metadata.go
reason: chainName is just for users. we don't store it in db. geth even removed this field.
> use chainID instead of name for startup assers

- cmd/integration/commands/reset_state.go
- core/rawdb/accessors_chain.go
- core/rawdb/blockio/block_writer.go
- erigon-lib/kv/tables.go
- polygon/bor/bordb/prune.go
because Txs now always stored in EthTx table: reorgs do not update/move txs.
> remove NoncanonicalTxs table

- core/state_transition.go
- core/vm/evm.go
- turbo/adapter/ethapi/api.go
- turbo/jsonrpc/eth_call.go
- turbo/transactions/tracing.go
Hi guys, we had an issue come up on our fork of erigon regarding some gas fee calculation: https://github.com/testinprod-io/op-erigon/issues/183
We thought this would apply to upstream erigon as well, so brought the changes here too. 
I'd appreciate any feedbacks or concerns for this 😄 
This PR fixes gas fee calculation for rpc calls. It mostly borrows changes from geth and resolves previous issues.
```bash
curl "https://localhost:8545 " -X POST -H "Content-Type: application/json" -d  ' {"jsonrpc": "2.0", "id": "1", "method": "eth_estimateGas", "params": [{"from": "0xa5B8492D8223D255dB279C7c3ebdA34Be5eC9D85","data": "0x00", "to": "0xa5B8492D8223D255dB279C7c3ebdA34Be5eC9D85" }, "pending"]}'   
```
Results in:
```
"code":-32000,"message":"insufficient funds for gas * price + value: address …
```
> Fix gas fee calculation for debug calls

- README.md
- erigon-lib/state/aggregator.go
- erigon-lib/state/domain.go
- erigon-lib/state/domain_test.go
- erigon-lib/state/inverted_index.go
for https://github.com/ledgerwatch/erigon/issues/10775
> handle case when account.kv is ahead of commitment.kv and we do `rm -rf chaindata`

- turbo/jsonrpc/eth_api.go
- turbo/jsonrpc/eth_call.go
- turbo/jsonrpc/eth_call_test.go
This reverts PR #10495 (see https://github.com/ledgerwatch/erigon/pull/10495#issuecomment-2188345464)
> Revert "eth_estimateGas: default feeCap to base fee (#10495)"

- core/types/transaction_test.go
`types2` import is same with `libtypes`. 
And no **type1** or **type3** in this test, so maybe we should delete it.
> test: remove redundant import

- cl/clstages/clstages.go
- cl/phase1/stages/clstages.go
There is comment that preferred way to use different context not bounded to general app context. But through it we propagate cancellations by signal. @Giulio2002 could you please clarify if we still need separated context or it's okay to pass ctx.
> allow to gracefully exit from CL downloading stage

- core/types/access_list_tx.go
- core/types/blob_tx.go
- core/types/dynamic_fee_tx.go
- core/types/legacy_tx.go
This is an additional check as #9990 could not be reliably reproduced.
The conjecture is that at some point there is a race condition somewhere related to either storing snapshot file for an older block or updating the DB for a more recent block.
Somewhere the code sets sender value directly to zero or overwrites a pointer, leading to sender address being incorrectly assigned to ZERO.
> Add zero check in tx.Sender func

- cl/cltypes/blob_sidecar.go
- cl/phase1/network/services/blob_sidecar_service_test.go
Fix:
https://github.com/ledgerwatch/erigon/issues/10762
I suspect the root cause is unexpectedly triggering the blobSidecarsScheduledForLaterExecution process loop every 5 milliseconds, which encounters a nil `CommitmentInclusionProof` value.
> Fix unstable blob_sidecar_service_test issue

- .github/workflows/qa-snap-download.yml
snap-download test doesn't require a pre-built db so can run on any self-hosted runner
> qa-tests: relax requirements for the snap-download test regarding the runner it should run on

- erigon-lib/state/aggregator.go
- erigon-lib/state/domain_committed.go
- erigon-lib/state/domain_shared.go
- erigon-lib/state/files_item.go
- erigon-lib/state/inverted_index.go
Depends on #10980
Ensures that merge does not further progress if latest merge ranges are different for commitment/storage/accounts.
Allows to merge if range for required domain has been already merged and file presents on disk/in visible files.
If discrepancy found and no needed files found, whole range gets on hold which allows to continue execution but not merge files any further.
After #10980 it will be able to fetch previously merged account/storage and conclude the merge.
> protect domain merging range 

- cl/phase1/execution_client/execution_client_rpc.go
- turbo/engineapi/engine_server.go
- turbo/engineapi/engine_types/jsonrpc.go
- turbo/engineapi/interface.go
see https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md
> engineapi: Add pectra engine api changes

- erigon-lib/state/domain_committed.go
Basically `commitment` waits for `accounts/storage` to be merged to be able to start replacements.
User can cancel execution at any point but for us that point had difference:
- lucky: if predicate domains has not been merged yet - just start over (including situations when merge is not yet concluded and .kv files are not yet available)
- unlucky: predicates are done but commitment is not yet finished, after restart commitment does not see required files (those ranges already merged)
- semi-lucky: small deviations of cases above with Great Random to decide outcome
PR fixes #10729 and should cover #10733 as well since they are highly related.
> Allow to merge commitment separately of other domains

- eth/tracers/native/call.go
made a mistake in previous PR https://github.com/ledgerwatch/erigon/pull/10986
should always pop the precompiles stack for correctness
> eth/tracers: always pop precompiles stack in callTracer

- cl/clstages/clstages.go
- cl/phase1/stages/clstages.go
> allow to gracefully exit from CL downloading stage (#10887)

- eth/tracers/native/call.go
cherry pick: 1a050db1f7d50d8a92b90d22e1ab10c243abc9e0
for E3
---
made a mistake in previous PR
https://github.com/ledgerwatch/erigon/pull/11022
should always pop the precompiles stack for correctness
> eth/tracers: always pop precompiles stack in callTracer (#11004)

- erigon-lib/diagnostics/client.go
- erigon-lib/diagnostics/entities.go
- erigon-lib/diagnostics/snapshots.go
- erigon-lib/diagnostics/stages.go
- erigon-lib/diagnostics/sys_info.go
Fix for https://github.com/ledgerwatch/erigon/issues/10932
> Diagnostics: Optimize db write

- erigon-lib/downloader/webseed.go
- not-finished downloads must be finished even if they are prohibited. (seems this filter was added as an optimization of HTTP calls amounts - of synced node startup).
- .lock must prohibit new .torrent creation, not webseeds discovery
cons: it will increase amount of HTTP calls at startup. will think about it in future
> dl: discover webseeds even if this file type is prohibited by .lock

- .github/workflows/qa-rpc-integration-tests.yml
Import rpcdaemon tests from Silkworm.
Not supported on Erigon: 
- debug_,trace_ 
Not supported without a running Erigon instance: 
- admin_,eth_mining,eth_getWork,eth_coinbase,eth_createAccessList/test_16.json,engine_,net_,web3_,txpool_,eth_submitWork,eth_submitHashrate,eth_protocolVersion,erigon_nodeInfo
> qa-tests: fix rpc integration test

- eth/tracers/logger/json_stream.go
- turbo/jsonrpc/trace_adhoc.go
Regression caused by this change in uint256 library:
https://github.com/holiman/uint256/commit/f24ed59bea89c23941cf073aeb3f702514f3b371
It was causing trace json to encode stack values as quoted (string) decimal values rather than a hex encoded value.
> fix regression in json encoding of stack values in traces due to change of uint256 String() method

- core/state/dump.go
- erigon-lib/kv/temporal/kv_temporal.go
- erigon-lib/state/aggregator.go
- erigon-lib/state/domain.go
- erigon-lib/state/domain_test.go
- erigon-lib/state/history.go
- turbo/jsonrpc/debug_api.go
had `ttx.DomainRange(kv.StorageDomain, addr[:], nil` - which means "all storage to the end of table" instead of "only storage of given account".
> debug_accountRange: to limit storage fetch prefix

- Makefile
it will allow `make erigon` to use default `-O2` on linux 
(`-O` it's `-O1`)
> ci: attempt to remove `-O` from makefile

- erigon-lib/txpool/txpoolcfg/txpoolcfg.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/gasprice/gasprice.go
- eth/gasprice/gaspricecfg/gaspricecfg.go
A followup PR to https://github.com/ledgerwatch/erigon/pull/10119 which sets the fields `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` to 25gwei only for polygon amoy network.
Upon sufficient announcements, it will be generalised to all polygon chains later.
> PIP-35 for amoy: enforce 25gwei gas config for amoy

- erigon-lib/txpool/txpoolcfg/txpoolcfg.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/gasprice/gasprice.go
- eth/gasprice/gaspricecfg/gaspricecfg.go
Cherry picks https://github.com/ledgerwatch/erigon/pull/11077
> A followup PR to https://github.com/ledgerwatch/erigon/pull/10119 which sets the fields `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` to 25gwei only for polygon amoy network.
> Upon sufficient announcements, it will be generalised to all polygon chains later.
> PIP-35 for amoy: enforce 25gwei gas config for amoy for erigon 2

- erigon-lib/go.mod
- erigon-lib/go.sum
- go.mod
- go.sum
Should fix:
https://github.com/ledgerwatch/erigon/issues/11070](https://github.com/ledgerwatch/erigon/issues/11070
Also fixes mainets stalls due to:
banned webpeers donimating small files
deadloc on peer reject
> update mod to v1.54.2-alpha-28

- erigon-lib/kv/membatchwithdb/memory_mutation.go
Adding missing `AppendableGet` to `MemoryMutation` so that it satisfies the `TemporalTx` interface.
> Add AppendableGet method to MemoryMutation

- erigon-lib/diagnostics/client.go
- erigon-lib/diagnostics/entities.go
- erigon-lib/diagnostics/resources_usage.go
- erigon-lib/diagnostics/snapshots.go
- erigon-lib/diagnostics/stages.go
- erigon-lib/diagnostics/stages_test.go
- erigon-lib/diagnostics/sys_info.go
- erigon-lib/diagnostics/utils.go
- erigon-lib/diagnostics/utils_test.go
- eth/stagedsync/stage_snapshots.go
- added snapshot fill from DB state gathering
- refactor persisted data parsing
> Diagnostics: snapshot stage info gathering

- erigon-lib/diagnostics/client.go
reason: 
- we already have 1 goroutine for saving data:
```
func (d *DiagnosticClient) runSaveProcess(rootCtx context.Context) {
ticker := time.NewTicker(5 * time.Minute)
go func() {
for {
select {
case <-ticker.C:
d.SaveData()
case <-rootCtx.Done():
ticker.Stop()
return
}
}
}()
}
```
no reason to save it from one more goroutine. just save it right here - in `case <-rootCtx.Done()` section. less concurrency - better. 
rootContext already subscribed to sigterm
> diag: thread-safety step4 - remove dedicated shutdown listener goroutine

- cmd/downloader/main.go
- skip `erigon2-v2` buckets - until https://github.com/ledgerwatch/erigon/issues/10967
> dl: manifest-verify green CI

- polygon/bor/finality/whitelist/milestone.go
```
==================
Write at 0x00c015bf2208 by goroutine 110:
github.com/ledgerwatch/erigon/polygon/bor/finality/whitelist.(*milestone).RemoveMilestoneID()
/home/ubuntu/erigon/polygon/bor/finality/whitelist/milestone.go:190 +0x164
github.com/ledgerwatch/erigon/polygon/bor/finality.handleNoAckMilestone()
/home/ubuntu/erigon/polygon/bor/finality/whitelist.go:237 +0x12c
github.com/ledgerwatch/erigon/polygon/bor/finality.retryHeimdallHandler()
/home/ubuntu/erigon/polygon/bor/finality/whitelist.go:159 +0x5c4
github.com/ledgerwatch/erigon/polygon/bor/finality.RetryHeimdallHandler()
/home/ubuntu/erigon/polygon/bor/finality/whitelist.go:117 +0x57
github.com/ledgerwatch/erigon/polygon/bor/finality.startNoAckMilestoneService() …
```
> bor: finality race - step 2

- erigon-lib/diagnostics/network.go
- erigon-lib/diagnostics/network_test.go
Refactor to pattern which was suggested by @AskAlexSharov 
- move business-logic inside private methods
- move mutex locking inside public methods
- call private methods from public. don't call public methods from private.
> diagnostics: refactor network peers mutex

- core/types/log.go
- core/types/log_test.go
- turbo/jsonrpc/erigon_receipts.go
- turbo/jsonrpc/eth_receipts.go
- turbo/jsonrpc/overlay_api.go
If user provides logCount param the API should returns logCount records, even if the block contains more logs that satisfy the filter.
The logCount param is already supported, this PR avoids to return the log records in excess.
Moreover I have created 14 integration tests for this API (run with success on erigon2).
> `erigon_getLatestLogs` add limit parameter

- erigon-lib/txpool/fetch.go
- erigon-lib/txpool/pool.go
for https://github.com/ledgerwatch/erigon/issues/11163
> pool: do fsync by non-empty update (e3)

- erigon-lib/txpool/pool.go
- eth/stagedsync/stage_snapshots.go
for https://github.com/ledgerwatch/erigon/issues/11163
> pool: do fsync by non-empty update (e2)

- erigon-lib/common/dbg/experiments.go
enable `KV_MADV_NORMAL_NO_LAST_LVL=accounts,storage,code,commitment` by default
> enable `madv_normal` for .kv files of > 0 lvl

- eth/backend.go
- turbo/engineapi/engine_server.go
- turbo/jsonrpc/daemon.go
- turbo/jsonrpc/debug_api_test.go
- turbo/jsonrpc/eth_api.go
- turbo/jsonrpc/eth_api_test.go
- turbo/jsonrpc/eth_block_test.go
- turbo/jsonrpc/eth_callMany_test.go
- turbo/jsonrpc/eth_call_test.go
- turbo/jsonrpc/eth_filters_test.go
- turbo/jsonrpc/eth_mining_test.go
- turbo/jsonrpc/gen_traces_test.go
- turbo/jsonrpc/otterscan_transaction_by_sender_and_nonce_test.go
- turbo/jsonrpc/parity_api_test.go
- turbo/jsonrpc/send_transaction_test.go
- turbo/jsonrpc/txpool_api_test.go
This PR brings back `datadir.Dirs` to `BaseAPI`, and removes a redundant `Aggregator` argument to `EngineServer.Start` .
> Bring back dirs to  BaseAPI

- turbo/jsonrpc/otterscan_search_trace.go
- turbo/jsonrpc/otterscan_transaction_by_sender_and_nonce.go
for: https://github.com/erigontech/erigon/issues/9967
> ots: nil-ptr in rpc

- cmd/integration/commands/refetence_db.go
- cmd/integration/commands/root.go
- cmd/integration/commands/state_domains.go
- erigon-lib/downloader/downloader.go
- erigon-lib/kv/mdbx/kv_mdbx.go
- node/node.go
> added var inside WriteMap for chain-like interface

- core/state_transition.go
- core/vm/evm.go
- core/vm/instructions.go
- core/vm/runtime/runtime.go
Add bailout mgt on evm.create() method (it is already mgt on evm.cal()).
When approved I will create PR on rel 2.60.x
> tracer: add support bailout on evm.create()

- rpc/client.go
- rpc/http.go
- rpc/http_test.go
- rpc/json.go
- rpc/server.go
- rpc/server_test.go
- rpc/testservice_test.go
- rpc/types.go
- rpc/websocket.go
- turbo/app/support_cmd.go
closes #11157 but a bit of scared that we probably don't have some MetadataFromContext method like in https://github.com/ethereum/go-ethereum/pull/24255
> added rpc info feature

- cl/beacon/handler/validators.go
fix https://github.com/erigontech/erigon/issues/11027
root cause: specific slot state data not found leads to empty validator set
> fix panic due to nil validator set

- core/state_transition.go
- core/vm/evm.go
- core/vm/instructions.go
- core/vm/runtime/runtime.go
Add bailout mgt on evm.create() method (it is already mgt on evm.cal())
> tracer: add support bailout on evm.create()  on e2

- .github/workflows/qa-sync-from-scratch-minimal-node.yml
the last few runs of the test did not complete on time
> qa-tests: increase test time of sync-from-scratch for minimal node

- .github/workflows/qa-sync-from-scratch.yml
The test results are uploaded to the github actions test run page at the end of the test. As this test has 2 jobs, we need to give the uploaded test results different names to avoid clashes.
> qa-tests: fix sync-from-scratch test result uploading

- erigon-lib/diagnostics/snapshots.go
- erigon-lib/diagnostics/stages.go
for https://github.com/erigontech/erigon/issues/11268
> diag: race in updateIndexingStatus 

- Makefile
Fixes https://github.com/erigontech/erigon/actions/runs/10041015251/job/27748204997#step:9:72 (caused by PR #10726 apparently). See also https://github.com/goreleaser/goreleaser-cross-example/pull/10
> fix goreleaser after update

- .github/workflows/release.yml
- Makefile
- switched to `v1.21.5` 
- added to UI checkbox "Publish Artifacts" - which is disabled by default. if not set: `make release-dry-run`
> e3 use same goreleaser-cross version as in e2

- eth/backend.go
- eth/gasprice/gasprice.go
Cherry-picked from https://github.com/erigontech/erigon/pull/11294
> Remove the checks for amoy added previously to prepare for mainnet release. 
> Sets `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` to 25gwei for all polygon based networks.
> PIP-35: enforce 25gwei gas config for all polygon chains for erigon 2

- eth/backend.go
- eth/gasprice/gasprice.go
Remove the checks for amoy added previously to prepare for mainnet release. 
Sets `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` to 25gwei for all polygon based networks.
> PIP-35: enforce 25gwei gas config for all polygon chains

- erigon-lib/commitment/bin_patricia_hashed.go
- erigon-lib/commitment/commitment.go
- erigon-lib/commitment/commitment_bench_test.go
- erigon-lib/commitment/commitment_test.go
- erigon-lib/commitment/hex_patricia_hashed.go
- erigon-lib/commitment/hex_patricia_hashed_test.go
- erigon-lib/state/domain_shared.go
Small refactor to improve the readability of some fields in the `hex_patricia_hashed.go` .
> refactor: rename fields in hex patricia trie

- eth/backend.go
- go.mod
- go.sum
closes #10086 but it uses old lib (https://github.com/karrick/godirwalk). This branch could be used for tests for someone who experiences troubles with RAM with RemoveContents func. (For example for this guy https://discord.com/channels/687972960811745322/1233600171821240380)
Maybe we should fork this lib :) thing for future milestone
> new dirWalk for test purposes

- turbo/snapshotsync/freezeblocks/bor_snapshots.go
- disabling bor files production - because it breaking execution 
- by some reason bor files are created ahead of execution stage - and also bor files are bad - and it breaking execution of bor-mainnet/amoy nodes
> bor: don't produce bor files 

- turbo/execution/eth1/forkchoice.go
This PR removes effectively `FlushExtendingFork` overhead at chain tip.
The reason why it works is that:
CL just needs FCU to return SUCCESS, and this promise is inherently mantained if the block has already been marked as valid.
What the PR actually do is: if we flush the fork built in NewPayload, return SUCCESS before the flushing (SUCCESS will be logically what would be returned anyway). this pushes the extra computation on Ethereum's idle block time, thus rendering it null and giving CLs more time to process attestations/blobs/etc...
> Erigon 3: Parallel state flushing

- polygon/bor/bor.go
- polygon/bor/snapshot.go
- polygon/bor/valset/validator_set.go
part 1 of https://github.com/erigontech/erigon/pull/11339 to make the PR smaller and easier to review
moves `getUpdatedValidatorSet` to `valset` package to solve a circular dependency and also for better code grouping since that code is related to validator sets
> polygon: move valset logic inside valset package

- polygon/heimdall/service.go
- polygon/heimdall/service_observer_options.go
- polygon/sync/tip_events.go
part 2 of https://github.com/erigontech/erigon/pull/11339 to make the PR smaller and easier to review
Adds an "observer options" optional param to "RegisterSpanObserver" and "RegisterMilestoneObserver" functions, as we have 3 different requirements for event limit: last 2 for span observer, last 5 for milestone observer and in the above linked PR we want all span events (ie no events limit)
> polygon/heimdall: add observer options

- turbo/adapter/ethapi/api.go
- turbo/adapter/ethapi/state_overrides.go
Change the datatype used for the "stateDiff" override to eth_call to a hash instead of a uint256.
https://github.com/ethereum/go-ethereum/blob/171430c3f5d474327bc1721c7c36ad83ad21b4b2/internal/ethapi/api.go#L975-L976
> Use the same data type as go-ethereum in the stateDiff override for eth_call

- .github/workflows/qa-sync-from-scratch.yml
This PR 
- adds Holesky net "sync-from-scratch" test
- increases test time due to Amoy's slowness
> qa-tests: add holesky to sync-from-scratch test

- core/rawdb/accessors_chain.go
- eth/backend.go
- turbo/engineapi/engine_block_downloader/block_downloader.go
- turbo/jsonrpc/trace_filtering.go
[Benchmark](https://github.com/ethereum/go-ethereum/pull/29490#issuecomment-2042789684) shows improvement
> Use big.Sign to compare with zero

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
now `ReopenSegments([]snaptype.Type{coresnaptype.Headers, coresnaptype.Bodies}` does close txs files 
for https://github.com/erigontech/erigon/issues/11384 and https://github.com/erigontech/erigon/issues/11314
> `ReopenSegments` must not close other files

- eth/stagedsync/stage_bor_heimdall.go
This adds a check to make sure that if the bor heimdall stage is behind bodies it catches up in one pass.
This is necessary to avoid missing sync events in execution and erroneously storing no sync events on retire
> Don't break bor_heimdall stage if behind bodies

- eth/stagedsync/stage_polygon_sync.go
was getting " unexpected end of JSON input" due to this - accidentally missed to set `k` in a previous PR
> polygon: sync stage fix blockRangeEntitiesFromBlockNum

- turbo/app/init_cmd.go
I was getting the following logs when running this:
```sh
docker run --rm -it  --user=1003:1003 --volume=/data/erigon:/data:rw --volume=/data/ethereum-network-config/metadata/genesis.json:/genesis.json:ro --network=shared ethpandaops/erigon:main-5e4478f --datadir=/data init /genesis.json
```
```
INFO[07-30|16:44:34.910] logging to file system                   log dir=/data/logs file prefix=erigon log level=info json=false
INFO[07-30|16:44:34.912] Starting Erigon on Ethereum mainnet...
INFO[07-30|16:44:34.914] Maximum peer count                       ETH=100 total=100
INFO[07-30|16:44:34.914] starting HTTP APIs                       port=8545 APIs=eth,erigon,engine
INFO[07-30|16:44:34.915] Opening Database                         label=chaindata path=/data/chaindata …
```
> Use the actual datadir when using init for custom network

- eth/stagedsync/stage_headers.go
- eth/stagedsync/stage_polygon_sync.go
Fix for below nil ptr in the new polygon sync stage using Astrid.
Gist of fix: move call of `downloadStateSyncEvents(header)` to the stage's `updateForkChoice` handler instead of the `insertBlocks` handler. The reason for this is because `downloadStateSyncEvents` uses `blockReader.HeaderByNumber` before `Indore` fork and that requires the canonical hash at each block height to be set before calling it. This is done by `fixCanonicalChain` and we only call that in the `updateForkChoice` handler so `downloadStateSyncEvents` needs to be called after it.
Note: `downloadStateSyncEvents` will be removed and replaced by integrating the bridge in the new polygon sync stage as part of https://github.com/erigontech/erigon/issues/11195 but for now would prefer to do this fix to unblock myself.
``` …
```
> astrid: fix for polygon sync stage bor events nil ptr

- core/vm/instructions.go
Not needed since https://github.com/holiman/uint256/commit/6785da6e3eea403260a5760029e722aa4ff1716d
> Remove redundant zero checks in instructions

- cl/beacon/handler/validators.go
Fix https://github.com/erigontech/erigon/issues/11414
root cause: empty validator set
> Fix panic in caplin api get validator

- erigon-lib/kv/remotedbserver/remotedbserver.go
It is necessary when using temporal KV remotely. This implementation does not support interface-level pagination because `HistoryRange` in `kv.TemporalTx` does not accept next key
> Implement HistoryRange in KvServer

- erigon-lib/chain/chain_config.go
The community seems to be using `depositContractAddress` in the standard format for importing genesis.json, as seen in pectra-devnet-2
(This was mandated in EIP-6110)
> chain_config: Fix json name for deposit contract address

- cmd/diag/main.go
- cmd/diag/sysinfo/sysinfo.go
- cmd/diag/util/util.go
- diagnostics/setup.go
- diagnostics/snapshot_sync.go
- diagnostics/sysinfo.go
- erigon-lib/diagnostics/entities.go
- erigon-lib/diagnostics/sys_info.go
- erigon-lib/diskutils/diskutils_darwin.go
- Added collections info about disk, as we are interested in disk type. For now it's only for macOS
> diagnostics: collect diskinfo for macos

- turbo/snapshotsync/freezeblocks/block_reader.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
Reverts erigontech/erigon#11434
> Revert "block files: use native `map` instead of `btree.Map`"

- docs/programmers_guide/guide.md
Hi, I'm diving into the merkle tree calculation step and thanks for such a detailed doc in `guide.md`, it is very helpful for understanding the entire process.
I found a logical error in the article that could mislead others' understanding, so I hope to help Erigon fix it.
I found the [corresponding position](https://github.com/erigontech/erigon/blob/main/turbo/trie/gen_struct_step.go#L270) in the code and proved that only the case of 'less' will cause a prefix group closing, while the original' equal 'will not cause it.
> fix: update mpt document logic

- eth/stagedsync/exec3.go
Custom chains started using `init` may put nil genesis here. I am working on a design fix for this, but this PR will prevent a panic
> stagedsync: Fix nil panic on custom chains

- erigon-lib/chain/snapcfg/util.go
Fixes the following issue:
This function is invoked regardless of the chain being known. For custom chains with `init` command, the network name is blank and this panic is triggered on restarting the node
> snapcfg:  should not panic on empty network name

- .github/workflows/qa-snap-download.yml
- .github/workflows/qa-sync-from-scratch-minimal-node.yml
- .github/workflows/qa-sync-from-scratch.yml
- .github/workflows/qa-tip-tracking.yml
Change test scheduling and timeouts after Ottersync introduction.
Now we can execute tests more frequently due to the significant reduction in test time.
Scheduled to run every night:
- tip-tracking
- snap-download
- sync-from-scratch for mainnet, minimal node
Scheduled to run on Sunday:
- sync-from-scratch for testnets, archive node
> qa-tests: update test scheduling and timeouts

- polygon/heimdall/service_test.go
forgot to silence the logging in the heimdall service tests in a previous PR
the logging lvl can be tweaked at times of need if debugging is necessary
> polygon/heimdall: silence service tests logging

- eth/stagedsync/default_stages.go
- eth/stagedsync/stage_bor_heimdall.go
- eth/stagedsync/stage_polygon_sync.go
- eth/stagedsync/stagebuilder.go
closes https://github.com/erigontech/erigon/issues/11177
- adds unwind logic to the new polygon sync stage which uses astrid
- seems like we've never done running for bor heimdall so removing empty funcs
> polygon: add unwind prune to sync stage

- cmd/diag/sysinfo/sysinfo.go
- cmd/diag/util/util.go
Refactored printing cpu info:
- move CPU details to table
- move CPU usage next to details table
- refactor code
> diagnostics: refactored cpu info

- erigon-lib/common/dbg/experiments.go
- eth/stagedsync/stage_headers.go
- turbo/stages/headerdownload/header_algos.go
relates to:
https://github.com/erigontech/erigon/issues/10734
https://github.com/erigontech/erigon/issues/11387
restart Erigon with `SAVE_HEAP_PROFILE = true` env variable
wait until we reach 45% or more alloc in stage_headers when "noProgressCounter >= 5" or "Rejected header marked as bad"
> stagedsync: add dbg.SaveHeapProfileNearOOM to headers stage

- turbo/snapshotsync/freezeblocks/block_snapshots.go
Removed unnecessary struct type
> turbo/snapshotsync: Fmt fix (#11493)

- polygon/bor/bor.go
- polygon/sync/sync.go
Crash was due to a missing early return.
> polygon/sync: Fix `onMilestoneEvent` crash

- cl/phase1/core/state/raw/copy.go
- cl/phase1/core/state/raw/hashing.go
- cl/phase1/core/state/raw/params.go
- cl/phase1/core/state/raw/state.go
got crash on sepolia due to concurrent rw panic:
```
fatal error: concurrent map iteration and map write
goroutine 125102027 [running, locked to thread]:
github.com/erigontech/erigon/cl/phase1/core/state/raw.(*BeaconState).CopyInto(0xc04b46c908, 0xc04b46cb48)
github.com/erigontech/erigon/cl/phase1/core/state/raw/copy.go:83 +0xd93
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).CopyInto(0xc08b77cea0, 0xc08b77d2c0)
github.com/erigontech/erigon/cl/phase1/core/state/copy.go:28 +0x74
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).Copy(0xc08b77cea0)
github.com/erigontech/erigon/cl/phase1/core/state/copy.go:66 +0x37
github.com/erigontech/erigon/cl/phase1/stages.emitNextPaylodAttributesEvent(0xc05c490c40, 0x56133a, {0x64, 0xac, 0xff, 0x77, 0xa0, …
```
> fix concurrent rw on touchedLeaves map

- cmd/diag/downloader/diag_downloader.go
- cmd/diag/stages/stages.go
- cmd/diag/sysinfo/sysinfo.go
- cmd/diag/util/util.go
- erigon-lib/sysutils/sysutils.go
- erigon-lib/sysutils/sysutils_test.go
Changes:
- Collecting CPU and Memory usage info about all processes running on the machine
- Running loop 5 times with 2 seconds delay and to calculate average
- Sort by CPU usage
- Write result to report file
- Display totals for CPU and Memory usage to processes table
- Display CPU usage by cores
- Print CPU details to table
Cherry pick from:
- #11516
- #11526
- #11537
- #11544
> diagnostics: export system info

- erigon-lib/common/dbg/experiments.go
- eth/stagedsync/stage_headers.go
- turbo/stages/headerdownload/header_algos.go
`log.Info` does not get piped to our log files, making it hard to figure out what is going on
need to pass in the correct `logger`
this PR adds optional args to `SaveHeapProfileNearOOM` to allow passing in loggers and memStats when needed
> dbg: add save heap options for logger and memstats inputs

- polygon/sync/sync.go
Previously, we were passing blocks directly to the execution client - bypassing events processing for the bridge as well as synchronisation necessary before `UpdateForkChoice`.
This fixes hash mismatches at chain tip.
> polygon/sync: Use store at tip

- erigon-lib/seg/decompress.go
- erigon-lib/state/aggregator_test.go
- erigon-lib/state/btree_index.go
- erigon-lib/state/domain.go
To reduce disk IO
To protect PageCache from restart
> bt: use madv_normal instead madv_readahead for index opening

- eth/stagedsync/stage_snapshots.go
to make commit time and prune time more predictable
> prune less blocks on chain-tip 

- turbo/trie/retain_list.go
This PR fixes the incorrect return type of `proof` field of `storageProof`. The return type from erigon is `null` whereas the correct return type should be `[]`.
Geth also returns `[]` in this special case which makes the PR compatible across different clients. Parsing `null` as return type breaks a few client like alloy.
> fix incorrect return type for `eth_getProof`

- core/snaptype/block_types.go
- erigon-lib/downloader/snaptype/type.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
bsc: 
```
before:
du -hsc /erigon-data/snapshots/*head*.idx
322M	total
after: 
380M	total
```
> Enable LessFalsePositives feature for header.idx

- eth/protocols/eth/handler_test.go
- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- turbo/stages/blockchain_test.go
- turbo/stages/chain_makers_test.go
- until measure LRU hit-rate on chain-tip of bormainnet/mainnet
- until measure chain-tip-impact
- maybe until https://github.com/erigontech/erigon/issues/11603
- maybe need limit - how old blocks are allowed to request
Reason: we have complains about chain-tip slowness and this feature is not essential. So, need look more careful on monitoring/stats before enabling.
> move p2p genReceipts behind experimental env flag

- cmd/integration/commands/state_stages.go
- cmd/rpcdaemon/cli/config.go
- consensus/aura/aura.go
- consensus/clique/clique.go
- consensus/clique/verifier.go
- consensus/consensus.go
- consensus/mainnet/mainnet.go
- consensus/merge/merge.go
- core/chain_makers.go
- eth/backend.go
- eth/stagedsync/stage_mining_create_block.go
- eth/stagedsync/stage_mining_finish.go
- eth/stagedsync/stagedsynctest/harness.go
- polygon/bor/bor.go
- polygon/bor/bor_test.go
- turbo/stages/mock/mock_sentry.go
- turbo/stages/mock/sentry_mock_test.go
Rationale: one small step to converge Polygon and Ethereum block production.
Also, now `(s *Merge) Seal` calls `block.WithSeal`, which is important after PR #11513.
> Merge MiningResultPOSCh with MiningResultCh

- .github/workflows/kurtosis/config.yaml
- .github/workflows/test-kurtosis-assertoor.yml
kurtosis assertoor tests in ci
decision points:
- since the job takes about 45 minutes to run, I decided not to run it on every PR, but rather we run it every 12 hours at 2AM/PM UTC.
- all tests are present in https://github.com/ethpandaops/assertoor-test/tree/master/assertoor-tests. This ci runs [these](https://github.com/erigontech/erigon/pull/11464/files#diff-b45e49409c33f39133315225d30c02d8cfacfd9a53d1157bca61284683a4c498R22) tests.
- test is for ubuntu only; not for mac or windows.
Many tests are failing; specially the validator related ones. Tracked separately - https://github.com/erigontech/erigon/issues/11590
> adds kurtosis-assertoor to ci

- cl/antiquary/state_antiquary.go
- cl/persistence/state/historical_states_reader/historical_states_reader.go
related to https://github.com/erigontech/erigon/issues/11482
> fix panic issue in initializeStateAntiquaryIfNeeded (#11608)

- eth/stagedsync/stage_execute.go
And write mb/s is also big at prune time - nvme handles it - but on a bit slower disks will affect chain-tip perf. 
BorMainnet: 
Gnosis:
> Prune still affecting chain-tip "fsync"

- turbo/snapshotsync/freezeblocks/block_reader.go
> integrity: use expectedTxnID rather than bad baseTxnID

- core/state/dump.go
- turbo/jsonrpc/debug_api_test.go
PR contains the FIX done on e2 see (PR #11669 )
> fix: debug_accountRange(): increase block_number on storage walk (e3)

- core/state/dump.go
- turbo/jsonrpc/debug_api_test.go
I have done specific integration test(on e2) and compare the result with etherscan (block number 0x3D08FF: 3999999).
etherscan link:
https://etherscan.io/tx/0x535bd65cfee8655a1ffd8a28e065b47bcf557b10641491a541ab1dd08496709e#statechange
for account 0xEce701C76bD00D1C3f96410a0C69eA8Dfcf5f34E if use block_number + 1 the debug_accountRange() returns correctly for storage 0x0000000000000000000000000000000000000000000000000000000000000004 the new value: 0x000000000000000000000000000000000000000000000064a66fad67042ceb4a; using current software returns the old value (0x000000000000000000000000000000000000000000000064a3a922764918eb4b).
debug_accountRange() returns :
"storage": {
......
"0x0000000000000000000000000000000000000000000000000000000000000004": "64a66fad67042ceb4a",
----
}
If approved I …
> fix: debug_accountRange(): increase block_number on storage walk (e2)

- polygon/bor/bor.go
So if `BOREVENTS_REMOTE_FALLBACK=true` then in case of empty borevents from files will check bor events with remote Heimdall.
We still sometimes get 0 events from files (so they are incorrect).
> get back fallback to remote borevents if env `BOREVENTS_REMOTE_FALLBACK` provided

- eth/stagedsync/exec3.go
Wrong mags log in latest main branch
> exec3.go: fix bad log of mags

- cl/sentinel/sentinel.go
After investigation I see that SIGINT default handler is modified AFTER the line `host, err := libp2p.New(opts...)`
I looked into the library but couldn't find where the handlers are modified. From experimentations it's clear that this is the line after which the SIGINT behaviour changes (does nothing). 
I'm resetting the default behavior after the call. 
I tested it simply running the caplin for a few seconds and shutting it down with ctl+c which didn't work before the change.
> reset sigint default handler after libp2p.New call

- cl/antiquary/antiquary.go
- cl/persistence/beacon_indicies/indicies.go
- cl/phase1/forkchoice/utils.go
- cmd/caplin/caplin1/run.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
2 bugs were fixed:
* Sometimes `Antiquary` was initizialized with nil genesis
* When building block snapshots from 0, block 0 was skipped
> Caplin: Fixed nil panic in antiquary initizialization and indexing

- erigon-lib/state/aggregator_test.go
- erigon-lib/state/bps_tree.go
- erigon-lib/state/btree_index.go
+ reduces amount of memory required to built .bt index - previously we put key into collector, now we put key into collector only if it's meant to be cached. 
+ In file, list of nodes is presented as `uint64 (len Nodes) + [uint64(di), uint16(lenKey), key], [...]`. All numbers are encoded in big-endian notion. So 11 bytes min for each node (8 di + 2 length + at least 1 byte key)
During .bt file opening, nodes are decoded and enriched with correct offset from `elias-fano.Get(di)`. No reads from kv file made on start.
Now M is also a parameter of `BtIndexWriter`
> `.bt` indices with list of keys to cache

- erigon-lib/downloader/downloader.go
Corrected the calculation of downloaded bytes, which was previously overestimating by at least 30%. This was one of the main reasons the logs would often appear stuck at 99.90% for long time. 
List of changes :
- Removed `DroppedCompleted, DroppedTotal` it wasn't used anywhere
- Use `connStats.BytesReadData` to calculate download rate as torrent library says `// Sample Torrent.Stats.DataBytesRead for actual file data download rate.`
> downloader: Fixed downloaded value

- erigon-lib/chain/snapcfg/util.go
- erigon-lib/chain/snapcfg/util_test.go
- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
closes #11653
```
goos: darwin
goarch: arm64
pkg: github.com/erigontech/erigon/turbo/snapshotsync/freezeblocks
cpu: Apple M3 Max
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
FindMergeRange/big        10.846m ± 1%   3.373m ± 4%  -68.90% (p=0.000 n=10)
FindMergeRange/big-16      7.673m ± 0%   2.879m ± 1%  -62.48% (p=0.000 n=10)
FindMergeRange/small      19.516m ± 1%   6.684m ± 1%  -65.75% (p=0.000 n=10)
FindMergeRange/small-16   14.212m ± 0%   5.985m ± 1%  -57.89% (p=0.000 n=10)
geomean                    12.33m        4.439m       -63.98%
│    old.txt    │               new.txt                │
│     B/op      │     B/op      vs base                │
FindMergeRange/big         7.819Mi ± 0%   1.712Mi ± 0%  -78.11% (p=0.000 …
```
> Know cfg new more optimized strings.split

- eth/stagedsync/bor_heimdall_shared.go
- eth/stagedsync/stage_bor_heimdall.go
This adds an overflow check to stop bor-heimdall failing to initialize after chain db has been removed
> Fix bor-heimdall stall after chaindb removal

- erigon-lib/go.mod
- erigon-lib/go.sum
- go.mod
- go.sum
Downgraded version of the google.golang.org/grpc/cmd/protoc-gen-go-grpc to v1.4.0
> downgraded protoc version

- eth/stagedsync/bor_heimdall_shared.go
- eth/stagedsync/stage_bor_heimdall.go
- eth/stagedsync/stage_mining_bor_heimdall.go
Sometimes via config events are skipped from particular blocks and
pushed into the next one, when this happens we need to skip validation
as the times won't match the expected window. 
In practice it only affects these blocks: 
14949120,14949184, 14953472, 14953536, 14953600, 14953664,
14953728, 14953792, 14953856 
So it seems keeping a local skip marker is good enough - it will only impact sync from origin operations.  If
this becomes more prevalent this will need to be re-thought
> Don't validate skipped events

- cmd/utils/flags.go
- erigon-lib/downloader/downloadercfg/downloadercfg.go
The `--torrent.staticpeers` param always append a hardcoded :80 port regardless of what is passed on CLI, it is already broken.
Removes the hardcoded part requiring the user to pass a complete host:port string.
Also fixes the help msg which seems copy/pasted from the p2p help.
> Fix --torrent.staticpeers param

- polygon/bor/snaptype/types.go
`extractRange` was being called for the same block number multiple times with different event ID ranges which broke the block reader.
> Fix duplicate borevent snapshot entries

- turbo/jsonrpc/eth_api.go
- turbo/jsonrpc/eth_call.go
- turbo/jsonrpc/eth_call_test.go
Fix EstimateGas returning error when passing StateOverrides argument: `too many arguments, want at most 2.`
[EstimateGas](https://github.com/ethereum/go-ethereum/blob/4e17f2874077488f8eb61a2fca490386fd1a9e52/internal/ethapi/api.go#L1228) in go-ethereum already supports StateOverrides parameter, and this change will make EstimateGas the same as [Call](https://github.com/erigontech/erigon/blob/03293defd62461df9be1f482ae5906eb42e947a7/turbo/jsonrpc/eth_call.go#L56) in erigon.
> EstimateGas supports overriding state

- eth/stagedsync/stage_polygon_sync.go
Astrid sync stage deadlocked on chain tip when a new fork choice update resulted in a change of fork. Logs:
```
INFO[08-23|23:24:36.845] [2/6 PolygonSync] forward                progress=11087680
DBUG[08-23|23:24:36.847] [bridge] processing new blocks           from=11087052 to=11087682 lastProcessedBlockNum=11087680 lastProcessedBlockTime=1724451852 lastProcessedEventID=2312
DBUG[08-23|23:24:36.848] [sync] inserted blocks                   len=631 duration=2.2985ms
DBUG[08-23|23:24:36.848] [bor.heimdall] synchronizing spans...    blockNum=11087682
DBUG[08-23|23:24:36.848] [bridge] synchronizing events...         blockNum=11087682 lastProcessedBlockNum=11087680
INFO[08-23|23:24:36.848] [2/6 PolygonSync] update fork choice     block=11087682 …
```
> polygon: fix astrid stage integration deadlock on tip unwind

- cl/beacon/handler/pool.go
- cl/phase1/network/services/aggregate_and_proof_service.go
- cl/phase1/network/services/attestation_service.go
- cl/phase1/network/services/block_service.go
- cl/validator/attestation_producer/attestation_producer.go
- cl/validator/attestation_producer/attestation_producer_test.go
- cmd/caplin/caplin1/run.go
- Memory issue
Memory usage spirals out of control when a large number of validators simultaneously request attestation data via `validator/attestation_data`. The root cause is that each request attempts to create a copy of the beacon state, which includes a memory-intensive validator set data structure. 
To mitigate this, here try to reduce the frequency of identical beacon state copies.
- Unwind issue
Reproduce step:
1. add or say register validator
2. caplin then subscribes some gossip channels to receive new blocks
3. receive an old block from gossip and process it.
4. leads to unwind to the old block
> memory exhaustion due to connections with numerous validators & unwind issue

- erigon-lib/downloader/downloader.go
- erigon-lib/downloader/downloader_grpc_server.go
- turbo/snapshotsync/snapshotsync.go
- Moved logging for downloader progress to downloader
- Updated log progress message structure
- Display correct state of file downloading which is solve user complaints that downloader stuck at 99%
Example of the log output which include downloading and verifying states:
`INFO[08-26|16:58:47.045] [1/6 OtterSync] Downloading              progress="(358/358 files) 97.21% - 216.0GB/222.2GB" rate=5.9MB/s time-left=0hrs:17m total-time=23m0s download-rate=5.9MB/s completion-rate=2.0GB/s alloc=10.9GB sys=13.7GB`
`INFO[08-26|16:59:07.019] [1/6 OtterSync] Downloading              progress="(358/358 files) 99.57% - 221.2GB/222.2GB" rate=268.3MB/s time-left=0hrs:0m total-time=23m20s download-rate=268.3MB/s completion-rate=839.4MB/s alloc=11.7GB sys=13.7GB`
`INFO[08-26|16:59:27.037] [1/6 OtterSync] …
> downloader: updated progress logging

- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile.release
It is a work on https://github.com/erigontech/erigon/issues/10251 .
Main changes:
- goreleaser reconfigured (more binaries added, most of the build flags passed to goreleaser)
- released erigon binary now has "Build info" dynamic values such as a branch, tag, commit id.
- amd64 binaries will be build using GOAMD64=v2 support for better support of modern CPUs.
- as agreed -- now it will generate release without prefix "v", i.e. "2.60.7", but not "v2.60.7".
- docker image will have following binaries: erigon, integration, diag, sentry, txpool, downloader and rpcdaemon. (Exactly the same binaries as published in artifacts in the release notes).
- multi-platform docker tag created with support of two OS/Arch -- linux/amd64/v2 and linux/arm64 which should cover almost all use cases when docker …
> Rework goreleaser configuration, release workflow and Dockerfile for release images.

- cl/sentinel/sentinel.go
Limiting default `StreamsOutbound` and `StreamsInbound` for p2p resource manager.
> set specific stream bound limits

- cl/phase1/network/backward_beacon_downloader.go
- cl/phase1/stages/clstages.go
- cl/phase1/stages/stage_history_download.go
- cmd/capcli/cli.go
fixes: https://github.com/erigontech/erigon/issues/11704
Implemented early-stopping at snapshots and reduced CPU usage to 0 by reducing calls to `HasBlock` and `FrozenBlocks`.
> Caplin: Fixed `History Download` CPU usage

- cl/beacon/handler/headers.go
- cl/persistence/beacon_indicies/indicies.go
- erigon-lib/kv/tables.go
So we need to get block roots that have a specific parent roots: there needs to be many
So added new table to indexing DB: parentRoot => list of block roots
Then I fixed the REST API with this new index
> Caplin: Fixed caplin parent root indexing

- eth/stagedsync/stage_polygon_sync.go
Run into a deadlock in my long running process of Astrid stage mode. It happened in the following scenario:
- there was an error returned from one of the background components running in the background (the process should have terminated with the error but instead it deadlocked)
- the errorgroup running all the background components ([here](https://github.com/erigontech/erigon/blob/main/eth/stagedsync/stage_polygon_sync.go#L485-L519)) cancelled the context
- `polygonSyncStageSbpsStore.Entity` func queued a tx action in the stream, the action got executed and was just about to pass back the response via the response channel however at the same time the `Entity` func exited due to the context cancelation and there was no one to consume the response from the response stream, so the writer …
> polygon: astrid sync stage fix deadlock on cancelled context

- consensus/misc/eip2935.go
Few points:
- Of the two options for inserting the parent block hash , we go for option 2, that is `Avoid EVM processing and directly write to the state trie.` . 
- Although option 1 is preferred "till verkle", there is no benefit in adding the EVM overhead. Furthermore, verkle-related changes will be there afterwards.
- Now this necessitates additional checking - `if no code exists at HISTORY_STORAGE_ADDRESS, the call must fail silently`.
- We include this check and add a debug log for the fail
Ref: https://github.com/ethereum/EIPs/blob/117933b21665ca7c0d040835a9d19b4a02392f47/EIPS/eip-2935.md
> el-consensus: Add 2935 condition to fail silently if no code in HistoryStorageAddress

- erigon-lib/common/dbg/dbg_env.go
step1: allow both, and log.Warn
step2 (in some future): something more radical
> Add "ERIGON_" prefix to env variables

- erigon-lib/config3/config3.go
- erigon-lib/state/aggregator.go
- erigon-lib/state/appendable.go
- erigon-lib/state/appendable_test.go
- erigon-lib/state/domain.go
- erigon-lib/state/domain_test.go
- erigon-lib/state/files_item.go
- erigon-lib/state/gc_test.go
- erigon-lib/state/history.go
- erigon-lib/state/history_test.go
- erigon-lib/state/inverted_index.go
- erigon-lib/state/inverted_index_test.go
- erigon-lib/state/merge.go
- erigon-lib/state/merge_test.go
- erigon-lib/state/reconst.go
Preventing pruning of domain A before all Domains produce `n+1` steps of files
fixing https://github.com/erigontech/erigon/issues/10724
> e3 visibleFiles: if domain `A` has `n+1` steps and domain `B` has `n` steps - then user will see only files up to step `n` 

- erigon-lib/commitment/hex_patricia_hashed.go
During unfold the cells of a row in the grid can get reset, and although setting the lengths of the fields to 0 is sufficient, the inner arrays appearing non-empty can give a false indication that those cells have not been reset, especially during debugging. So it is best to reset these arrays as well during cell reset.
> Reset inner cell arrays in cell.reset()

- .github/workflows/qa-rpc-integration-tests.yml
Import Silkworm RPC Integration tests.
Out of 800 tests about 268 are disabled and need investigation.
On Erigon v2 only 164 tests are disabled.
We can trace regressions from this point on.
The Silkworm team is investigating the failing tests: later we will update the list of these tests to include the bad ones that have been fixed or the correct ones that fail due to some erigon bug.
> qa-tests: add rpc integration tests (Erigon v3)

- core/vm/evm.go
- erigon-lib/chain/chain_config.go
- params/protocol_params.go
- polygon/bor/borcfg/bor_config.go
[Polygon] Bor: [PIP-30: increased max code size limit to 32KB](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-30.md)
> [Polygon] Bor: PIP-30: increased max code size limit to 32KB [For Erigon-2]

- tests/block_test.go
- tests/init_test.go
- tests/state_test.go
[v14.1](https://github.com/ethereum/tests/releases/tag/v14.1) is the last version to add new test vectors; going forward all new tests will be added to [execution-spec-tests](https://github.com/ethereum/execution-spec-tests).
> Update ethereum/tests to v14.1

- eth/stagedsync/exec3.go
Always save last 8 blocks of a "block batch"
> Erigon 3: Fix occassional need for reorgs (during first sync in polygon) through a "safety" threshold

- eth/integrity/no_gaps_bor_events.go
- turbo/stages/stageloop.go
noticed stagesHeadersAndFinish (used for deciding initial isSynced var used to determine whether to run all stages in 1 rwtx or separate) isn't taking into account PolygonSync stage progress
note BorHeimdall and PolygonSync stage are mutually exclusive - can't have both running at the same time, only either of the 2
> polygon: update stagesHeadersAndFinish to check PolygonSync stage progress

- eth/consensuschain/consensus_chain_reader.go
Once remove chaindata, it will always return nil when get block number by hash. Because the kv.HeaderNumber won't filled when FillDBFromsanpshot.
> consensuschain: fix getHeaderByHash return nil

- docs/programmers_guide/guide.md
The conception of the different between` Erigo`n and` Geth` in this guide is outdated. I found the part may be the correct part. But Im not 100% sure.
> guide: fix conception and link

- .github/workflows/ci-cd-main-branch-docker-images.yml
- .github/workflows/release.yml
- Dockerfile.release
New workflow ci-cd-main-branch-docker-images.yml
New Dockerfile targets for the new workflow in Dockerfile.release
Changes in release workflow: rename arg.
See issue https://github.com/erigontech/erigon/issues/10251 for more info.
> New workflow ci-cd-main-branch-docker-images.yml and changes in release workflow

- erigon-lib/kv/remotedbserver/remotedbserver.go
It is necessary when using temporal KV remotely.
Additional changes:
- remove what I think is an oversight in `IndexRange`, where `req.PageSize` was checked and cut to `PageSizeLimit`, but then not used (`PageSizeLimit` itself was used instead)
- remove useless `limit--` in `HistoryRange`
> Implement DomainRange in KvServer

- core/state_transition.go
**Existing behaviour:**
- Add up the possible value that user must pay beforehand to buy gas
- Deduct that amount from the sender's account in `intraBlockState`, but:
- Don't deduct the gas value amount if the user doesn't have enough, and `gasBailout` is set
**New behaviour:**
- Don't check if sender's balance is enough to pay gas value amount, nor deduct it, if `gasBailout` is set
**More rationale**
This would mean the sender's account would show `"balance": "="` in `trace_call` rpc method, that is, no change, if gas is the only thing the user pays for. This is fine because the gas price can fluctuate in a real transaction. This also removes the inconsistency of sometimes having to bother deducting the amount if it is less than sender's balance, thereby causing a bug/inconsistency.
> core: Check `gasBailout` before deducting balance in trace_call

- core/state_transition.go
**Existing behaviour:**
- Add up the possible value that user must pay beforehand to buy gas
- Deduct that amount from the sender's account in `intraBlockState`, but:
- Don't deduct the gas value amount if the user doesn't have enough, and `gasBailout` is set
**New behaviour:**
- Don't check if sender's balance is enough to pay gas value amount, nor deduct it, if `gasBailout` is set
**More rationale**
This would mean the sender's account would show `"balance": "="` in `trace_call` rpc method, that is, no change, if gas is the only thing the user pays for. This is fine because the gas price can fluctuate in a real transaction. This also removes the inconsistency of sometimes having to bother deducting the amount if it is less than sender's balance, thereby causing a …
> core: Check `gasBailout` before deducting balance in trace_call (#11813)

- polygon/sync/canonical_chain_builder.go
- polygon/sync/canonical_chain_builder_test.go
- polygon/sync/sync.go
fixes https://github.com/erigontech/erigon/issues/11818
issue was:
- when at tip we receive new block hashes and new block events
- we had an if statement which checked if the canonical chain builder tip changed after connecting new headers to the tree
- that if statement was used to determine whether we should call `InsertBlocks` for the blocks we've just connected and also to `commitExecution` (call `UpdateForkChoice`)
- this meant that when at the tip, we would not insert new blocks which would not change the tip of the canonical chain builder
- this is wrong because we should be inserting these blocks as they may end up being on the canonical path several blocks later in case the forks change in their favour based on the connected ancestors
fix is:
- augment …
> polygon/sync: fix parent td missing when forking at the tip

- eth/stagedsync/exec3.go
- eth/stagedsync/stage_polygon_sync.go
Next chain tip error caught and fixed for astrid stage integration:
```
append with gap blockNum=11561329, but current height=11561327
```
happens after unwind due to a fork change in the corresponding fork choice update.
This is due to a bug in the logic of handling fork choice updates in the stage integration. The issue is that when processing the `cachedForkChoice` after we have done the unwind, `fixCanonicalChain` returns empty `newNodes` (correctly, since the chain was fixed before we cached the fork choice). The solution is to cache the new nodes as the `cachedForkChoice` so that when we process the cached fork choice in the next iteration we can correctly update the tx nums for the new nodes.
Full logs:
```
INFO[09-04|16:14:31.018] [2/6 PolygonSync] update fork choice …
```
> astrid: fix stage integration cached fork choice logic

- polygon/p2p/message_sender.go
- polygon/sync/sync.go
fixes another crash on chain tip, happened due to a rare and unfortunate situation where the peer that gave us the new block hash event disconnected before we have processed that event and didn't give us a chance to fetch the block from it:
```
INFO[09-05|17:58:53.469] [2/6 PolygonSync] forward                progress=11604698
DBUG[09-05|17:58:55.192] [p2p.peerTracker] peer disconnected      peerId=de55d16b6e1fca28cdd3d11eb0dd89e3b77b96d4722172bd5e04ac255922324076a87748e97bc021af2307dccbb5ef8062389cfcba1845f77219eee7935dea9f
DBUG[09-05|17:59:13.075] Error while executing stage              err="[2/6 PolygonSync] stopped: peer not found: de55d16b6e1fca28cdd3d11eb0dd89e3b77b96d4722172bd5e04ac255922324076a87748e97bc021af2307dccbb5ef8062389cfcba1845f77219eee7935dea9f"
EROR[09-05|17:59:13.075] …
```
> polygon/sync: ignore safe peer not found err on tip event

- cmd/rpcdaemon/cli/config.go
- cmd/rpcdaemon/cli/httpcfg/http_cfg.go
- erigon-lib/metrics/register.go
- erigon-lib/metrics/set.go
- eth/backend.go
- go.mod
- go.sum
- turbo/cli/default_flags.go
- turbo/cli/flags.go
- turbo/jsonrpc/eth_block_test.go
- turbo/jsonrpc/eth_call_test.go
- turbo/jsonrpc/eth_filters_test.go
- turbo/jsonrpc/eth_mining_test.go
- turbo/jsonrpc/eth_subscribe_test.go
- turbo/jsonrpc/send_transaction_test.go
- turbo/jsonrpc/txpool_api_test.go
- turbo/rpchelper/config.go
- turbo/rpchelper/filters.go
- turbo/rpchelper/filters_deadlock_test.go
- turbo/rpchelper/filters_test.go
- turbo/rpchelper/logsfilter.go
- turbo/rpchelper/metrics.go
cherry pick from E3 https://github.com/erigontech/erigon/commit/adf3f438d8aae4c749e5ddacb3fe08afd6e695e7
-----
- Introduced `GetOrCreateGaugeVec` function to manage Prometheus `GaugeVec` metrics.
- Implemented various subscription filter limits (max logs, max headers, max transactions, max addresses, and max topics).
- Updated various test files to utilize the new `FiltersConfig` and added comprehensive tests for the new filter limits.
- Added new flags for subscription filter limits.
- Improved log filtering and event handling with better memory management and metric tracking.
- Added configuration to handle RPC subscription filter limits.
- Minor typo fixes.
-------
RPC nodes would frequently OOM. Based on metrics and pprof, I …
> Added RPC filter limits, metrics, and better memory management. (#10718)

- cmd/rpcdaemon/graphql/eip-1767.graphqls.ref
- cmd/rpcdaemon/graphql/geth-schema.graphqls.ref
- cmd/rpcdaemon/graphql/graph/generated.go
- cmd/rpcdaemon/graphql/graph/model/models_gen.go
- cmd/rpcdaemon/graphql/graph/schema.graphqls
- cmd/rpcdaemon/graphql/graph/schema.resolvers.go
- cmd/rpcdaemon/graphql/query_block.graphql
- cmd/rpcdaemon/postman/RPC_Testing.json
- cmd/rpctest/rpctest/type.go
- docs/readthedocs/source/rpc/index.rst
- erigon-lib/common/dbg/experiments.go
- eth/stagedsync/stage_snapshots.go
- turbo/adapter/ethapi/api.go
- turbo/jsonrpc/erigon_block.go
- turbo/jsonrpc/eth_block.go
- turbo/jsonrpc/eth_uncles.go
- turbo/jsonrpc/graphql_api.go
- turbo/jsonrpc/otterscan_api.go
Implements  https://github.com/ethereum/execution-apis/pull/570
> E3: Prune TotalDifficulty canonical markers

- cl/sentinel/discovery.go
I used simple "semaphore" to limit the number of goroutines to 4.
> use simple semaphore to limit peer connection opening

- cl/phase1/network/gossip_manager.go
- cl/phase1/network/services/attestation_service.go
- cl/validator/committee_subscription/committee_subscription.go
- cl/validator/committee_subscription/interface.go
- cl/validator/committee_subscription/mock_services/committee_subscribe_mock.go
Don't need to process attestations from gossip if the committee index associated with the attestation is not subscribed or doesn't require aggregation.
> Reducing unnecessary attestation processing from gossip

- cl/beacon/handler/pool.go
- cl/beacon/handler/utils_test.go
- cl/cltypes/aggregate.go
- cl/phase1/forkchoice/on_attestation.go
- cl/phase1/network/gossip_manager.go
- cl/phase1/network/services/aggregate_and_proof_service.go
- cl/phase1/network/services/aggregate_and_proof_service_test.go
- cl/phase1/network/services/interface.go
- cl/phase1/network/services/mock_services/aggregate_and_proof_service_mock.go
- cmd/caplin/caplin1/run.go
We are trying to optimise `AggregateAndProofService`. After profiling the service, I see that most of the CPU time is spent on signature verifications. From the graph, overall, the function took 6.6% (74 seconds) of all the time (not just execution time. Percentage would be much higher if we took just cpu time) see the screenshot:
Now we are trying to aggregate all the signatures and verify them altogether with `bls.VerifyMultipleSignatures` function in an async way and run the final functions if verifications succeed. I basically removed all the code where we verified those three signatures and instead gathered them for verifying later. After profiling that I see the following output:
Now most of the time, as I see, is spent on public key aggregation when we are verifying validator …
> Optimise aggregate and proof signature verification

- turbo/rpchelper/filters.go
- turbo/rpchelper/filters_test.go
cherry pick from E3 to E2: https://github.com/erigontech/erigon/commit/b760da20ce8da211e2ae877270415f64c3ab5fa8
----
- Simplify and enhance tests.
- Add test for invalid slice operations panic.
- Remove unused Mutex
----
I experienced a rare panic with the new filter code.
```text
panic: runtime error: slice bounds out of range [121:100]
goroutine 25311363 [running]:
github.com/ledgerwatch/erigon/turbo/rpchelper.(*Filters).AddPendingTxs.func1({0xc011c67020?, 0xc00a049e20?, 0xc020720b40?}, 0x48?)
github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:720 +0x31a
github.com/ledgerwatch/erigon-lib/common/concurrent.(*SyncMap[...]).DoAndStore.func1(0x20?)
github.com/ledgerwatch/erigon-lib@v1.0.0/common/concurrent/concurrent.go:52 …
```
> Prevent invalid slice operations in filters (#10826)

- diagnostics/profile.go
- diagnostics/setup.go
- diagnostics/sysinfo.go
Extended pprof read API to include:  goroutine, threadcreate, heap, allocs, block, mutex
> diagnostics: all pprofs

- turbo/rpchelper/config.go
This reverts commit 93ec6d96deeab3d88ba96fc5ac5cd4e03da11ee7.
based on advice from @bretep
https://discord.com/channels/687972960811745322/983710221308416010/1281647424569344141
> Revert "rpchelper: limits for filters by default (#11911) (#11912)"

- turbo/rpchelper/config.go
This reverts commit d7d9ded0ea3f5f887206f6c7f5e976eb58405154.
based on advice from @bretep
https://discord.com/channels/687972960811745322/983710221308416010/1281647424569344141
> Revert "rpchelper: limits for filters by default (#11911)"

- cmd/diag/ui/ui.go
- diagnostics/block_body_download_stats.go
- diagnostics/bodies_info.go
- diagnostics/bootnodes.go
- diagnostics/cmd_line.go
- diagnostics/db.go
- diagnostics/flags.go
- diagnostics/header_downloader_stats.go
- diagnostics/headers.go
- diagnostics/logs.go
- diagnostics/mem.go
- diagnostics/nodeinfo.go
- diagnostics/peers.go
- diagnostics/setup.go
- diagnostics/snapshot_sync.go
- diagnostics/sysinfo.go
- diagnostics/version.go
- Changed UI serving port to 5137 as 6060 is busy with diag API
- Refactored request headers to be set in middleware
> diagnostics: updated serving ui port (#11740)

- eth/backend.go
- eth/stagedsync/stage_polygon_sync.go
- polygon/heimdall/reader.go
- polygon/heimdall/service.go
- polygon/heimdall/service_test.go
- polygon/heimdall/span_block_producers_tracker.go
- Create `heimdall.Reader` for future use in `bor_*` API
- Make `AssembleReader` and `NewReader` leaner by not requiring full `BorConfig`
> polygon/heimdall: Split read functions into reader

- polygon/sync/block_downloader.go
- polygon/sync/block_downloader_test.go
Run into an issue since we started pruning total difficulty.
```
EROR[09-09|10:58:03.057] [2/6 PolygonSync] stopping node          err="parent's total difficulty not found with hash 9334099de5d77c0d56afefde9985d44f8b4416db99dfe926908d5501fa8dbd9e and height 11736178: <nil>
```
It happened for checkpoint [9703](https://heimdall-api-amoy.polygon.technology/checkpoints/9703). Our start block was in the middle of the checkpoint range which meant we have to fetch all the 8k blocks in this checkpoint to verify the checkpoint root hash when receiving blocks from the peer. 
The current logic will attempt to insert all these 8k blocks and it will fail with a missing parent td error because we only keep the last  1000 parent td records.
This PR fixes this by enhancing the block downloader to not …
> polygon/sync: block downloader to not re-insert blocks behind start

- erigon-lib/kv/rawdbv3/txnum.go
- erigon-lib/kv/stream/stream.go
- erigon-lib/kv/stream/stream_test.go
on empty request see error `can't find blockNumber by txnID=1235`
> trace_filter: return error at empty request

- .github/workflows/ci.yml
comment docker-build-check job as mentioned in the issue [11872](https://github.com/erigontech/erigon/issues/11872) -- it will save us 5-6 mins time of waiting for the routine check for each workflow run (faster PR check, etc).
get rid of "skip-build-cache" which is removed since v5
> comment docker-build-check job as mentioned in the issue 11872.

- cmd/rpcdaemon/cli/config.go
- eth/backend.go
- polygon/bridge/bridge.go
- polygon/bridge/bridge_test.go
- polygon/bridge/reader.go
- polygon/heimdall/reader.go
- polygon/heimdall/service.go
- polygon/heimdall/service_store.go
- polygon/heimdall/service_test.go
- polygon/polygoncommon/database.go
> polygon: Apply RoTx limit

- erigon-lib/go.mod
- go.mod
Otherwise I'm getting
```
go: download go1.22 for darwin/arm64: toolchain not available
```
on my mac.
See https://github.com/golang/go/issues/65568 & https://github.com/golang/go/issues/62278#issuecomment-1693538776
> Specify minor go version in go.mod

- .github/workflows/test-kurtosis-assertoor.yml
- core/state_transition.go
separate workflow into different jobs so failures in intermediate stages (like `make docker`) also gets reported as failure
> always send notifications for kurtosis assertoor ci runs 

- core/types/block.go
- p2p/sentry/sentry_multi_client/sentry_multi_client.go
- polygon/sync/blocks_verifier.go
- turbo/app/import_cmd.go
- turbo/stages/mock/mock_sentry.go
> I encountered a problem in the way we run execution-spec-tests, and need more eyes on it:
some execution spec tests have a failure associated with a block. An example is: a 7702 tx with empty auth list should cause block rejection because such a tx is invalid.
now when the BlockTest#Run executes, it tries to "insertChain", after which mock_sentry does block.HashCheck() before calling the el to insert block.
one of the check in HashCheck() is that if receiptRoot is emptyRootHash and block has any tx, it rejects the block right there, even before sending it to el (lots if not all execution-spec-tests wherein block should be rejected have receiptRoot=emptyRootHash)
The execution-spec-test in the above scenario passes, since the block was "rejected". But this can (and does) lead to false …
> partial hash check for mock_sentry.go

- Makefile
Use wider pattern to find most recent tag (not prefixed with "v") and set commit id by 7 chars only.
See - https://github.com/erigontech/erigon/issues/11968
> Fix for the issues/11968

- .github/workflows/ci-cd-main-branch-docker-images.yml
- Dockerfile.release
- Add actions/setup-go and use its cache (faster repeated builds)
- Build "snapshot" images one-by-one and pass GOAMD64=v2 flag for AMD64 architecture
- Simplify final docker image build process (just install binaries).
> Improve ci-cd-main-branch-docker-images workflow

- core/state/plain_readonly.go
`sort.Search` returns 0 for when a valid record in `systemContractLookup` was not found, and when we subtract 1 from it, it leads to an invalid index and a crash. 
Fixes #11936
> Fix codehash override index error

- erigon-lib/common/errors/errors.go
- polygon/bridge/bridge.go
- polygon/heimdall/scraper.go
fixes
```
DBUG[09-14|13:18:45.703] [p2p.peerTracker] peer connected         peerId=da870922d3a430bc9e0c71663884bb17968ceda35bf01f9f3d6318eb3c434a4e3ccf36eb1f6deb66a6037b9acf5b1473e2c94fbdcab98b4fe861134af08c8d05
WARN[09-14|13:18:45.920] [bor.heimdall] an error while fetching   path=clerk/event-record/list queryParams="from-id=2899&to-time=1726316275&limit=50" attempt=5 err="Get \"https://heimdall-api-amoy.polygon.technology/clerk/event-record/list?from-id=2899&to-time=1726316275&limit=50\": context deadline exceeded"
WARN[09-14|13:18:45.920] [bridge] scraper transient err occurred  from=2899 to=2024-09-14T13:17:55+01:00 err="Get \"https://heimdall-api-amoy.polygon.technology/clerk/event-record/list?from-id=2899&to-time=1726316275&limit=50\": context deadline exceeded" …
```
> polygon: fix more transient errors for astrid

- cmd/integration/commands/flags.go
- cmd/integration/commands/stages.go
- eth/stagedsync/stage_bor_heimdall.go
- eth/stagedsync/stage_polygon_sync.go
- turbo/stages/stageloop.go
relates to: https://github.com/erigontech/erigon/issues/11533
but mainly fixes an issue at tip that appeared in a run of astrid stage integration:
- we fetched event 2900 as soon as it appeared - this event was meant to be assigned to block 11962480
```
DBUG[09-14|13:57:41.878] [bridge] fetched new events periodic progress count=1 lastFetchedEventID=2900 lastFetchedEventTime=2024-09-14T12:57:35Z
```
- we then had a change of forks 
```
INFO[09-14|13:58:31.961] [2/6 PolygonSync] new fork - unwinding and caching fork choice unwindNumber=11962436 badHash=0x7e377810370189ece829b48172cc464672393678142cf105aad9212736893b8d cachedTipNumber=11962437 cachedTipHash=0x5076be24d339b5d75b52659dc746d3ceaa3d8dd873f3c34e5655849787d03d2b cachedNewNodes=1
DBUG[09-14|13:58:31.961] UnwindTo …
```
> astrid stage: do not unwind finalized data

- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile.release
Changes:
- compile new binaries for AMD64 microarchitecture level 1 (linux/amd64)
- explicitly use v2 suffix in binaries and docker images build for AMD64 microarchitecture level 2
After that change there will be multi-platform docker image with 3 OS/Arch:
- linux/arm64
- linux/amd64
- linux/amd64/v2
as well as a new release artifact.
> Add support for build for linux/amd64 (v1) [binaries/docker]

- rlp/decode.go
it's 15% of allocs of `blockReader.GetBlockWithSenders`
> rlp.Decode: alloc-free reader

- .github/workflows/qa-constrained-tip-tracking.yml
This PR introduces a version of the tip-tracking test that runs with limited resources. 
Currently only a RAM limit is set as per Erigon's readme.
> qa-tests: add constrained-tip-tracking test

- .github/workflows/ci.yml
- .github/workflows/test-integration-caplin.yml
- .github/workflows/test-integration.yml
- erigon-lib/go.mod
- go.mod
I am not sure about https://github.com/erigontech/erigon/pull/11897/files#diff-032140708bca135b7bd11337e3debb2651170c556efaa3c931896debca32eaf9L171
Please, check it and let me know if this commit should be also back-ported to release/2.60.
> Drop go 1.21 in release/2.60 - cherry pick PR 11966, 11897

- turbo/execution/eth1/getters.go
I'm running with erigon e3 in holesky chain, and found somd panic message in erigon's log:
```bash
[EROR] [09-18|23:57:23.899] RPC method engine_getPayloadBodiesByHashV1 crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:223 panic.go:770 panic.go:261 signal_unix.go:881 getters.go:154 execution_client.go:41 chain_reader.go:220 engine_server.go:599 engine_server.go:766 value.go:596 value.go:380 service.go:228 handler.go:534 handler.go:484 handler.go:425 handler.go:245 handler.go:338 asm_amd64.s:1695]
```
The panic was raised in this line https://github.com/erigontech/erigon/blob/1dd4a55ddf08f02d6484e66a767ce5ecddfb3a5e/turbo/execution/eth1/getters.go#L150-L154
After some digging, found `HeaderByNumber` maybe return `nil, nil`, so I think we need to handle …
> fix(turbo/execution): skip if header number is nil

- erigon-lib/common/hexutility/hex.go
`EncodeTs` will get inlined - and buffer will pass escape-analysis
> EncodeTs: heap-alloc

- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile.release
Changes:
- new binaries for linux/amd64 (v1)
- new docker image for linux/amd64 (v1)
- improve dockerhub health score
- remove checksum step from goreleaser and move it to workflow (due to dynamic archive for two amd64 cases)
- use bigger runner
- add Dockerfile stages for ci-cd routine builds (not required atm for release/2.60).
> Update release workflow for release/2.60

- .github/workflows/release.yml
- .goreleaser.yml
Move checksum step to github workflow due to
the issue with automatic processing in goreleaser
for both amd64 artifacts
> Improve release workflow in main branch

- eth/gasprice/feehistory.go
- eth/gasprice/feehistory_test.go
Added a maxQueryLimit constant to define the maximum number of requested percentiles (set to 100).
This implementation is the same as Geth: https://github.com/ethereum/go-ethereum/blob/a01e9742d997ea9e6cedfee41cba433433de9e10/eth/gasprice/feehistory.go#L245
Without this restriction, an attacker could submit a very large payload, causing Erigon to consume over 50GB of memory.
> Add maxQueryLimit to feeHistory

- erigon-lib/state/aggregator.go
`salt *uint32` is the return argument, so it is always nil inside the function before returning, no need to check it.
> feat(lib/state): no need to check salt with nil

- cl/beacon/handler/lighthouse.go
This is for example used in attestations rewards calculation, which was failing with the error message "no block found for this epoch".
In reality only the last block was not found in the epoch, and that already triggered the error.
With this change, we find the last non-missed block in this case.
> Make findEpochRoot work with missing blocks at the end of an epoch

- eth/stagedsync/stage_polygon_sync.go
fixes a mistake ive made in a previous PR that causes the below error on initial sync
```
INFO[09-23|18:10:08.623] [1/6 OtterSync] DONE                     in=3h7m31.843364875s block=12074999
... ^^ snapshots downloaded up to block 12074999 ...
DBUG[09-23|18:10:42.927] [sync] inserted blocks                   len=6267 duration=119.914625ms
... ^^ sync to tip started and downloaded first batch of 6267 blocks ...
INFO[09-23|18:10:42.928] [2/6 PolygonSync] update fork choice     block=12081266 age=6d4h58m hash=0x9d03bac27519eb1c655a9d354eeac6d0352ff69a09d421755a55813dd318ef2a
... ^^ update fork choice called for 12074999+1+6267 ...
DBUG[09-23|18:10:42.928] [2/6 PolygonSync] connecting tip         blockNum=12081266 blockHash=0x9d03bac27519eb1c655a9d354eeac6d0352ff69a09d421755a55813dd318ef2a …
```
> astrid: stage integration fix for connectTip error

- cl/beacon/handler/attestation_rewards.go
This typo (epoch vs. prevEpoch) caused little calculation differences compared to reality (as shown by balance changes on eth2).
Unfortunate, that we didn't have some kind of type system check catch this, as debugging took 2 days, and the name of the parameter showed that the function wants the previous epoch and not the current one.
Maybe previous epoch and epoch shouldn't be the same type...
> Fix attestations reward calculation inaccuracy

- tests/caplinrpc/beaconcha.in-query.py
I'm still debugging some corner-cases in caplin rpcs, and found this API, where the rate limits are enough for solo developer just comparing caplin to some upstream, well-tested source.
Might be useful later if bugs come up.
I understand this is not strictly related to erigon in any sense, happy to move it into a different directory inside the project (maybe we should have something like "misc" or "contrib") or just host it on my own github, if erigon doesn't want to include this.
> Add a small test utility to get rewards data from beaconcha.in

- core/vm/errors.go
- core/vm/gas_table.go
- core/vm/interpreter.go
align with go-ethereum of detailed oog reason, ref: https://github.com/ethereum/go-ethereum/blob/b018da9d02513ab13de50d63688c465798bd0e14/core/vm/interpreter.go#L273-L275
```go
dynamicCost, err = operation.dynamicGas(in.evm, contract, stack, mem, memorySize)
cost += dynamicCost // for tracing
if err != nil {
return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
}
if !contract.UseGas(dynamicCost, in.evm.Config.Tracer, tracing.GasChangeIgnored) {
return nil, ErrOutOfGas
}
```
> feat(core/vm): better oog error with backport ethereum/go-ethereum#29354

- .github/workflows/ci-cd-main-branch-docker-images.yml
- .github/workflows/ci-cd-main-branch-docker-images2.yml
- core/vm/interpreter.go
- revert changes to ci-cd-main-branch-docker-images.yml
- do those changes instead in ci-cd-main-branch-docker-images2.yml (temp copy) for quicker testing off PRs.
> prep work: getting kurtosis assertoor ci to depend on every docker image push workflow

- erigon-lib/common/dbg/experiments.go
I fixed the long caplin's snapshot wait time
> Caplin: Reduced snapshot semaphore to 1

- params/protocol_params.go
- tests/exec_spec_test.go
Ref - https://github.com/ethereum/EIPs/pull/8889
(Issue board - https://github.com/erigontech/erigon/issues/12106)
> Update EIP-7251 address

- turbo/jsonrpc/bor_snapshot.go
Moves spanProducersReader code down to the function that covers all use cases. Not all RPCs call `GetSnapshot`, which lead to errors when using Astrid.
> rpc: Move Astrid snapshot reader

- eth/tracers/logger/json_stream.go
https://github.com/erigontech/erigon/issues/12085
>  Type of error field in structlog logger differs from geth, alloy 

- eth/stagedsync/stage_polygon_sync.go
fixes 
```
INFO] [09-30|16:59:20.466] aggregator unwind                        step=2940 txUnwindTo=4595202440 stepsRangeInDB="accounts:0.9, storage:0.9, code:0.9, commitment:0.0, receipt:0.9, logaddrs: 0.9, logtopics: 0.9, tracesfrom: 0.9, tracesto: 0.9"
[EROR] [09-30|16:59:20.671] Staged Sync                              err="[3/9 BorHeimdall] unexpected missing first processed block info entry when unwinding"
```
that table (BorEventProcessedBlocks) is only populated as part of astrid, so bor heimdall stage should not attempt to unwind it (same for BorProducerSelections table)
> polygon: fix bor_heimdall stage unwinding due to event processed blocks table

- cmd/integration/commands/stages.go
- erigon-lib/chain/chain_config.go
- eth/stagedsync/stage_execute.go
- eth/stagedsync/stage_log_index.go
- eth/stagedsync/stage_log_index_test.go
- params/chainspecs/chiado.json
- params/chainspecs/gnosis.json
- params/chainspecs/goerli.json
- params/chainspecs/holesky.json
- params/chainspecs/mainnet.json
- params/chainspecs/sepolia.json
- turbo/stages/stageloop.go
> Turn NoPruneContracts into DepositContract

- polygon/bridge/bridge.go
- polygon/heimdall/service.go
fixes a crash when running astrid
```
[DBUG] [10-02|04:14:04.330] Error while executing stage              err="[2/6 PolygonSync] stopped: service unavailable: url='https://heimdall-api-amoy.polygon.technology/milestone/count', status=503"
[EROR] [10-02|04:14:04.330] [2/6 PolygonSync] stopping node          err="service unavailable: url='https://heimdall-api-amoy.polygon.technology/milestone/count', status=503"
```
> polygon/heimdall: add ErrServiceUnavailable transient err

- cmd/txpool/main.go
- core/types/encdec_test.go
- erigon-lib/txpool/pool.go
- erigon-lib/txpool/pool_fuzz_test.go
- erigon-lib/txpool/pool_test.go
- erigon-lib/txpool/txpoolutil/all_components.go
- erigon-lib/types/txn.go
- erigon-lib/types/txn_test.go
- eth/backend.go
- turbo/stages/mock/mock_sentry.go
> txpool changes for set_code_tx support

- polygon/heimdall/checkpoint.go
- polygon/heimdall/milestone.go
- polygon/heimdall/reader.go
- polygon/heimdall/service.go
- polygon/sync/block_downloader.go
- polygon/sync/block_downloader_test.go
- polygon/sync/waypoint_reader.go
- polygon/sync/waypoint_reader_mock.go
Fixes a rare error that occurred while testing Astrid on initial sync:
```
[DBUG] [10-03|13:41:32.989] [sync] downloading blocks using waypoints waypointsLen=1 start=12718963 end=12722546 kind=*heimdall.Checkpoint blockLimit=5000
...
[DBUG] [10-03|13:41:59.690] [sync] downloading blocks using waypoints waypointsLen=118 start=12724223 end=12729230 kind=*heimdall.Milestone blockLimit=5000
```
<br/>
Notice how the last block of the last checkpoint is `12722546` and then we start downloading using milestones however the start block of the first milestone is `12724223`.
This then causes an error because we end up inserting blocks with a gap:
```
[EROR] [10-03|13:42:04.075] [2/6 PolygonSync] stopping node          err="parent's total difficulty not found with hash …
```
> polygon/sync: block downloader to handle possible gaps between last checkpoint and first milestone

- turbo/snapshotsync/freezeblocks/block_snapshots.go
This fixes a race condition when merging dirty segs.
If the refcount is > 0 we should not remove the seg immediately because there is a visible segment holding a reference.
This will get tidied-up when the last visible segment closes and the file is removed.
This condition happens in a destructive way after a merge.  In this case any new visible segments will be given the newly merged file so will not hold references to this file.
I've tested this by running amoy to the chain tip and leaving it running and previous crashes seem to have been tidied up.
> Check refcount in reopen dirty seg

- .github/workflows/qa-rpc-integration-tests.yml
This PR uses rpcdaemon to run the tests in order to avoid copying the db.
In this way the tests run in 2 minutes.
> qa-tests: use rpcdaemon for rpc tests (Erigon 2)

- cl/sentinel/gossip.go
- cl/transition/impl/eth2/statechange/process_epoch.go
- cl/transition/impl/eth2/statechange/process_inactivity_scores.go
- cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go
- cl/transition/impl/eth2/statechange/process_slashings.go
- cl/transition/impl/eth2/statechange/worker_pool.go
Parallelising some tasks by using worker pool. 
Worker pool will save (last)error if any task returns it and we return it by `Error()` call after closing worker pool 
we do:
`wp := CreateWorkerPool(runtime.NumCPU())`
`wp.AddWork(func() error { some work })`
`wp.WaitAndClose()`
`return wp.Error()`
> parallelise epoch processing subtasks

- .github/workflows/qa-rpc-integration-tests.yml
This PR uses rpcdaemon to run the tests in order to avoid copying the db.
In this way the tests run in 2 minutes.
> qa-tests: use rpcdaemon for rpc tests (Erigon 2 - release/2.60) 

- core/types/request.go
This change was necessary for `TestExecutionSpec` to pass in e2.
Without this change the following check 		
```
if !reflect.DeepEqual(rss, requests) {
return nil, nil, nil, fmt.Errorf("invalid requests for block %d", header.Number.Uint64())
}
```
from `FinalizeBlockExecution` fails in e2. Apparently this check in not called in e3.
> Preserve requests nil-ness in (un)marshalling

- Makefile
- polygon/heimdall/scraper.go
- polygon/heimdall/service.go
- polygon/heimdall/service_test.go
- polygon/sync/block_downloader.go
- polygon/sync/block_downloader_test.go
- polygon/sync/sync.go
- polygon/sync/waypoint_headers_verifier.go
- polygon/sync/waypoint_headers_verifier_test.go
This PR captures several todos on my list of improving things related to Milestone hash mismatches that I noticed while testing Astrid on the tip:
- after restarts, when we initialise the canonical chain builder, we need to set the root to the last finalised waypoint header and connect the latest known tip to it. Previously, we set the root to the latest known tip which may not be the finalised one. This caused unnecessary unwinds on startup (with potentially incorrect unwind num for the bridge.Unwind) and although we auto recover from it it is still better to fix it properly as it may cause unexpected behaviour further down the line
- harden the milestone verifier to check for correct header connectivity via ParentHash and Number and also that the number of headers match with the number …
> polygon/sync: initialise canonical chain builder correctly

- turbo/trie/trie_root.go
With EIP-7702 even EOAs might have some storage set, and we use zero incarnation for EOAs.
> e2: Fix state root calculation for EIP-7702 accounts with storage

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/block_snapshots_test.go
We have a gap in our bor mainnet snapshot toml between
'v1-051900-052000-headers.idx' = 'd97b3c598f520888eb67244ba28d994998584e65'
'v1-054000-054100-headers.idx' = 'a20efd5aca03ebb528215b24ce6aa0c20cc90c55'
When syncing bor mainnet from scratch the node fails to sync due to that. We will fix the gap in our toml however the node should auto-recover by regenerating the .idx files
After digging further it seems like we have a regression in https://github.com/erigontech/erigon/pull/11557
idxAvailability used to stop when finding a seg which is not indexed
after that PR it does not, but instead it keeps on going so idxMax gets set to 62 mil although there is a gap (it should have been set to 52 mil where the gap is)
Tested on my node and it recreated the gap of indices
```
[INFO] …
```
> freezeblocks: fix max visible segment when there is a gap in .idx files

- cl/antiquary/antiquary.go
- cmd/capcli/cli.go
- eth/stagedsync/exec3.go
- turbo/snapshotsync/freezeblocks/beacon_block_reader.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
Now that `--caplin.snapgen` is false by default we can:
* Avoid the semaphore for antiquation speed
* Sanity check blob seg files
> Caplin: Add more sanity checks to blob antiquation

- cl/sentinel/service/start.go
randomly choosing two attestation subnets and subscribing indefinitely.
> Listen to two random attestation subnets

- polygon/sync/event_channel.go
- polygon/sync/event_channel_test.go
- polygon/sync/sync.go
- polygon/sync/tip_events.go
- polygon/sync/tip_events_test.go
Fixes an issue with Astrid at tip where the root of our canonical chain builder got too far away from the tip (> 1024 blocks) which is not to be expected. It should never happen at tip. Milestones are usually ~30 blocks on Mainnet. I've seen worst cases around ~200 blocks on Amoy. So if our processing is accurate our root should never be more than 1024 aways from the tip. The explanation for this is that every time we process a milestone we move our root forward, so it should always be 1 milestone worth of blocks behind tip.
The underlying root cause of this caused 2 problems:
1. an error that crashed the node 
```
[EROR] [10-09|16:54:25.194] [2/6 PolygonSync] stopping node          err="invalid fetch blocks amount: amount=1030"
```
<br/>
2. degrading performance of the node for some time …
> polygon/sync: avoid dropping milestone events

- turbo/snapshotsync/freezeblocks/block_snapshots.go
- turbo/snapshotsync/freezeblocks/caplin_snapshots.go
This PR removes a race condition from dirty segments processing by:
* ref counting finalized blocks - so they get ignored during open/close
* lock the dirty segments on begin transaction
The lock prevents the race condition where the retire process reads the refcount and starts processing the reopen of a file, then the view starts a transaction.
The view iteration generally happens faster than the file operations - causing a race as the refcount is incremented while the operations is happening.
I've tested this by running with race from scratch for amoy - and it now produces no data races, and panics.
> Lock dirty segs before incrementing ref counts

- cl/phase1/core/caches/shuffled_indicies_cache.go
- cl/phase1/core/state/cache_accessors.go
- cl/phase1/stages/forkchoice.go
- cl/sentinel/gossip.go
Moves the latency of shuffled sets in the `idle period` of the slot.
> Caplin: Shuffle validator set in idle time during previous epoch

- .github/workflows/test-hive.yml
It'll be re-activated when hive tests are stable again
> github/workflows: Silence on main branch push

- cl/beacon/handler/rewards.go
Sync rewards are earned every slot, not just on epoch boundary.
The rewards don't change throughout an epoch, so it's correct, that for the calculation we need the epoch head, but rewards can still be individually lost/earned in a slot: e.g. the whole network can miss slots (proposer misses), or individual sync committee members can get negative rewards for being offline.
> Make sync rewards accessible also in non-epoch boundary slots

- turbo/snapshotsync/freezeblocks/block_snapshots.go
This change adds a dirty segments read lock to 
```
(s *RoSnapshots) recalcVisibleFiles
```
To make sure that visible segments contains an atomic set of dirty segment references not interleaved with the file recalculation process.
> Add dirty lock to recalc visible segments

- turbo/jsonrpc/eth_receipts.go
Fix `eth_getLog` call log filtering in case when receipts are read from rawdb.
> filter logs from rawdb

- turbo/transactions/tracing.go
`ComputeTxEnv` relied on `txIndex < len(block.Transactions())` which is violated by Polygon's state sync event transaction. We handle this case by adding an early return for this case, returning only ibs and blockContext which is used during state sync event tracing.
Fixes #11701, #12007
> Add early return in `ComputeTxEnv` for state sync transactions

- .github/workflows/qa-tip-tracking-gnosis.yml
Having started testing Erigon v.3 on Gnosis, it is necessary to distinguish between the pre-build database of v.2 and v.3 on the test runner.
> qa-tests: Gnosis Tip-Tracking Test - use v2 pre-built database on release/2.60
